Simon-Initiative/oli-torus

assets/src/components/editor/Editor.tsx
This PR ensures that an edited document always contains a paragraph as the last item.
=> ensure paragraph is last node

lib/oli/lti.ex, lib/oli/lti/nonce.ex, lib/oli/lti/provider.ex, lib/oli/utils.ex, lib/oli_web/controllers/lti_controller.ex, priv/repo/migrations/20200310193550_init_core_schemas.exs, test/oli/lti/provider_test.exs, test/oli/lti_test.exs, test/oli_web/controllers/lti_controller_test.exs
This PR adds a table for storing LTI nonce and checking on every request that a duplicate nonce is not provided within the allowed request window. LTI request timestamp must be within 5 mins of the current time and nonces which are older than 1 day are purged to ensure that duplicate nonces are not used while minimizing the amount of nonces being stored.
Requirement for this feature comes from the LTI spec: [https://www.imsglobal.org/specs/ltiv2p0/security](https://www.imsglobal.org/specs/ltiv2p0/security)
"Upon receipt of the POST, the Tool Provider will perform the OAuth validation utilizing the shared secret it must have stored locally for the relationship with the Tool Consumer associated with the oauth_consumer_key.  The timestamp should also be validated to be within a specific time …
=> Add support for tracking and checking LTI nonce

assets/css/app.css, assets/package.json, assets/src/components/TextEditor.tsx, assets/src/components/resource/DragHandle.tsx, assets/src/components/resource/Editors.tsx, assets/src/components/resource/Objectives.tsx, assets/src/components/resource/Outline.tsx, assets/src/components/resource/ResourceEditor.tsx, assets/src/components/resource/TitleBar.tsx, assets/src/components/resource/undo.ts, assets/src/data/content/objective.ts, assets/src/data/content/resource.ts, assets/src/data/types.ts, assets/yarn.lock, lib/oli/db_seeder.ex, lib/oli/editing/editor.ex, lib/oli/learning/objective_revision.ex, lib/oli/publishing.ex, lib/oli/resources/resource_revision.ex, priv/repo/migrations/20200310193550_init_core_schemas.exs, priv/repo/seeds.exs, test/oli/activities_test.exs, test/oli/publishing_test.exs
This PR completes the 'enhanced resource editor'.  It adds in:
* Ability to reorder resource content items via drag and drop
* Ability to reorder resource content items via accessible keyboard manipulation (SHIFT + arrow keys)
* Ability to attach and detach learning objectives to a resource
Run `mix ecto.reset` after syncing.  The test project with the default resource will then contain three learning objectives that you can test adding / removing. 
Closes #40 
Closes #50 
Closes #54
=> Enhanced editor

assets/webpack.config.js, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/templates/layout/workspace.html.eex
This PR adjusts the webpack plugin to use the `splitChunks` optimization.  This is the current way that webpack supports splitting out vendor (react, slate, etc) and common and entry point code.
This is step one of N for activity integration. This needs to be in place so that our natively implemented activities can be bundled separately from other application code, thus unifying the approach for delivery and authoring for both 'native' and 'third-party' activities.
=> use splitChunks optimization

assets/src/components/activities/multiple_choice/MultipleChoice.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceAuthoring.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/multiple_choice/authoring-entry.ts, assets/src/components/activities/multiple_choice/delivery-entry.ts, assets/src/components/activities/multiple_choice/manifest.json, assets/src/components/activities/types.ts, assets/webpack.config.js, lib/oli/activities.ex, lib/oli/activities/activity_map_entry.ex, lib/oli/activities/manifest.ex, lib/oli/activities/mode_spec.ex, lib/oli/activities/registration.ex, lib/oli/editing/editor.ex, lib/oli/registrar.ex, priv/repo/migrations/20200310193550_init_core_schemas.exs, priv/repo/seeds.exs, test/oli/activities_test.exs, test/oli/publishing_test.exs, test/oli/registrar_test.exs
This PR implements a couple of key pieces of the emerging activity infrastructure:
1. The ability for the system to compile and bundle locally developed activities so that they can be delivered via standalone scripts includes (one for authoring and one for delivery).  This delivery script only includes the delivery component, the authoring includes both since the delivery component is needed for live preview of an activity.
2. The ability to "register" locally developed activities.  This involves populating the activity_registrations table with the activities that are found to be locally developed.
3. The ability to generate an "activity map", which is sent to the resource editor as part of its context. The activity map specifies to the front end application a mapping from activity types …
=> Local activity registration and activity map generation

lib/oli/editing/editor.ex, lib/oli/learning.ex, lib/oli/publishing.ex, lib/oli/resources/resource_revision.ex, priv/repo/migrations/20200310193550_init_core_schemas.exs, test/oli/learning_test.exs
This converts the usage of slugs in resource children and attached objectives back to database ids.
Logic was added in the resource editor to convert back and forth so that revision slugs are sent down to the client editing code.
=> Back to ids

lib/oli/authoring/editing/container_editor.ex, lib/oli_web/controllers/curriculum_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/curriculum/index.html.eex, test/oli/editing/container_editor_test.exs
This PR wraps up initial curriculum support by:
* Improving the look and feel of drag and drop ui 
* Fixing deletion to remove the item from the container and to mark it as deleted
* Adds units tests for module `ContainerEditor`
=> improve reordering, fix deletion, add unit tests

lib/oli_web/controllers/instructor_delivery_controller.ex, lib/oli_web/controllers/student_delivery_controller.ex, lib/oli_web/templates/delivery/_objectives.html.eex, lib/oli_web/templates/delivery/_previous_next_nav.html.eex, lib/oli_web/templates/instructor_delivery/index.html.eex, lib/oli_web/templates/instructor_delivery/page.html.eex, lib/oli_web/templates/student_delivery/index.html.eex, lib/oli_web/templates/student_delivery/page.html.eex, lib/oli_web/views/instructor_delivery_view.ex, lib/oli_web/views/student_delivery_view.ex, test/oli_web/controllers/student_delivery_controller_test.exs
This PR implements the display of previous page and next pages for page navigation.
It also improves the code sharing situation a bit between instructor and student delivery controllers, as well as cleans up the objectives display.
Closes #65
=> implement previous and next links, cleanup objectives display

lib/oli/authoring/course/family.ex, lib/oli/authoring/course/project.ex, lib/oli/db_seeder.ex, lib/oli/resources/revision.ex, lib/oli/utils/slug.ex, priv/repo/migrations/20200310193550_init_core_schemas.exs, test/oli/course_test.exs, test/oli/utils/slug_test.exs
This PR adjusts the slug logic for projects to ensure that slugs never change once they are set. 
There were a few other things that were wrong here.  Indices for families and projects were missing.  The logic in the revision slugging was backwards. 
I also added unit tests for the slugging logic. 
Closes #111
=> Project slug

assets/src/components/editor/Editor.tsx
With some help from folks in the Slate.js Slack, we can now differentiate between selection and content changes. 
Closes #123
=> propagate only content changes upward

lib/oli/publishing/authoring_resolver.ex, lib/oli/utils/slug.ex, test/oli/utils/slug_test.exs
This PR expands the logic for handling slugs - there was a gap in that it didn't properly handle preserving a slug across new revision creation. 
This change then exposed a bug in an authoring resolver method that wasn't considering that multiple revisions could have the same slug. 
Closes #142
=> handle slug generation properly across revisions

lib/oli/activities/model/transformations.ex, lib/oli/activities/transformers.ex, lib/oli/activities/transformers/shuffle.ex, lib/oli/activities/transformers/transformer.ex, lib/oli/delivery/attempts.ex, test/oli/activities/transformers_test.exs
The shell of the transformers implementation.  Complete enough to get us thru learnlab release as it supports shuffling of top-level keys (choices is what we will use it for).  We will eventually want to expand support for deeper path navigation and add other transformers (for template questions, in particular).
=> transformers impl

assets/src/components/activities/DeliveryElement.ts, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activity/ActivityEditor.tsx, lib/oli/activities/model/feedback.ex, lib/oli/activities/model/hint.ex, lib/oli/activities/state/activity_state.ex, lib/oli/authoring/editing/activity_editor.ex, lib/oli/db_seeder.ex, lib/oli/delivery/attempts.ex, lib/oli/delivery/attempts/activity_attempt.ex, lib/oli/delivery/attempts/part_attempt.ex, lib/oli/delivery/attempts/resource_attempt.ex, lib/oli/delivery/attempts/snapshot.ex, lib/oli/delivery/attempts/student_input.ex, lib/oli/delivery/evaluation/evaluator.ex, lib/oli/resources.ex, lib/oli/resources/revision.ex, lib/oli/resources/scoring_strategy.ex, lib/oli_web/controllers/attempt_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/student_delivery/page.html.eex, priv/repo/migrations/20200310193550_init_core_schemas.exs, priv/repo/seeds.exs, test/oli/delivery/hints_test.exs, test/oli/delivery/submission_test.exs
This PR adds support for activity and part submission - as well as activity (but not yet part) resetting.  Hints can also now be requested and shown. The `max_attempts` is now enforced with the default 0 meaning unlimited attempts. 
With this PR in place one can now:
Author and publish a page with a multiple choice activity.
Have a student LTI launch in and visit the page and submit a response for the question.
The student will receive immediate feedback and the question goes into a "read only" state.
The author can make a change to the activity (fix a typo, refine feedback) and publish the page
The student clicks "Retry" to try the question again. The question "resets", but the student now sees the updated version of the question.
=> Evaluation, Hints and number of attempts constraint

.github/workflows/deploy.yml, .github/workflows/main.yml
Splits CI/CD workflows so that we aren't repeating jobs on PR and push. To ensure all code that is pushed to test and production (including merges) is actually run through build and test, the github repo setting is updated to ensure branches have the latest before push.
=> refactor and split workflows

lib/oli/delivery/attempts.ex, lib/oli/delivery/page/page_context.ex, lib/oli_web/controllers/attempt_controller.ex, lib/oli_web/controllers/page_delivery_controller.ex, test/oli/delivery/attempts_test.exs, test/oli/delivery/hints_test.exs, test/oli/delivery/submission_test.exs
This PR adds transaction support for high-level `Attempts` functions were they were missing.
=> add transaction support where needed

lib/oli_web/router.ex, lib/oli_web/templates/curriculum/index.html.eex
curriculum reordering fails due to presence of CSRF. Solution is to move this endpoint to an API pipeline
=> fix reordering csrf problem

assets/src/components/editor/Editor.tsx, assets/src/components/editor/RichTextEditor.tsx, assets/src/components/editor/Toolbars.tsx, assets/src/components/resource/Editors.tsx, assets/src/components/resource/ResourceEditor.tsx
To reproduce this issue, follow these steps:
1. Edit a page that initially has just one Content item.
2. Add a new Content or MCQ item.
3. Attempt to edit the first Content item.
You will see the second item disappear.
This problem was a combination of referencing previous state at the `ResourceEditor` level and caching of state at the `Editors` level.  
To prevent re-rendering of toolbars I added in the `React.memo` wrappers around the fixed and hover toolbar.
=> Edit render fix

lib/oli/delivery/attempts.ex, lib/oli/delivery/page/page_context.ex, lib/oli_web/controllers/page_delivery_controller.ex
This PR adjusts the logic around handling resource attempts that are being revisited when the source resource has changed since the last visit. Previously in this situation we would throw the attempt away and create a new one.  This change allows that attempt to continue and ensures that the old version of the resource is used in rendering. 
Closes #165
=> Preserve graded attempts

assets/package.json, assets/src/components/editor/Editor.tsx, assets/src/components/editor/Toolbars.tsx, assets/src/components/editor/editors/Lists.tsx, assets/src/components/editor/utils.tsx, assets/src/components/resource/Outline.tsx, assets/yarn.lock
This PR allows the ordered and unordered list buttons to toggle the list state of the current selection.
The interesting aspect of this work (which was not obvious and hard to track down) was that our editor normalization code will seek to adjust the intermediate states that this code introduces.  I see no way in the Slate API to suspend normalization - so I have essentially added that by allowing client code to set `(editor as any).suspendNormalization = true` which suspends all custom normalization until set to `false`
I took this opportunity to upgraded us to the latest Slate version as well.
Closes #176
=> List toggle

assets/src/components/editor/Toolbars.tsx
This PR adjusts the logic to determine when to show/hide the floating toolbar.  With this PR in place, when the selection spans multiple blocks the hovering toolbar will not be displayed.
Closes #203
=> hide when selection spans multiple blocks

assets/src/components/editor/Toolbars.tsx, assets/src/components/editor/editors/SizePicker.tsx, assets/src/components/editor/editors/Table.tsx, assets/src/components/resource/toolbar.ts
This PR fixes the table creation size picker z-index problem.  
Unfortunately, the only solution I could come up with was to replace the bootstrap dropdown with a react-tiny-popover instance. 
Closes #232
=> convert dropdown button to use popover

lib/oli_web/live/history/pagination.ex, lib/oli_web/live/history/pagination_link.ex, lib/oli_web/live/history/revision_history.ex, lib/oli_web/live/history/table.ex
This PR adds pagination support for the tabular display in the revision history tool. 
Pagination will be necessary in production where we could expect hundreds of revisions to be present for a resource.
=> paginate table display

lib/oli/authoring/editing/page_editor.ex, lib/oli/authoring/editing/util.ex, test/oli/delivery/evaluation/parser_test.exs, test/oli/delivery/evaluation/rule_eval_test.exs, test/oli/editing/utils_test.exs
This implements server-side handling of deletion and undeletion for when activity references are found to be inserted or removed in a front-end initiated change through the `PageEditor`
=> set deleted flag on activity revision during page edits

assets/src/hooks/index.ts, assets/src/hooks/modal.ts, lib/oli/authoring/editing/objective_editor.ex, lib/oli/authoring/locks.ex, lib/oli/publishing.ex, lib/oli_web/live/common/manual_modal.ex, lib/oli_web/live/common/modal.ex, lib/oli_web/live/history/revision_history.ex, lib/oli_web/live/objectives/attachments.ex, lib/oli_web/live/objectives/objective_entry.ex, lib/oli_web/live/objectives/objectives.ex, test/oli/editing/activity_editor_test.exs, test/oli/editing/objective_editor_test.exs, test/oli/editing/page_editor_test.exs, test/oli/publishing_test.exs, test/oli_web/live/objectives_test.exs
This PR adds support for detaching objectives from resources when an objective is deleted. 
It does not allow detachment when the attaching resource is locked for editing. 
Closes #251
=> Objective removal

lib/oli_web/live/objectives/objective_render.ex, lib/oli_web/live/objectives/objectives.ex
This PR allows the "Objectives" link in the sidebar to highlight when that view is active.
It also removes the crosshairs image as a prefix from the objective rendering. 
Closes #254
=> highlight objective link when active

lib/oli/accounts/schemas/user.ex, lib/oli/delivery/lti/nonce.ex, priv/repo/migrations/20200310193550_init_core_schemas.exs
This PR cleans up the db schema ensuring that all table names follow the standard approach of using a pluralized version of the entity. 
user -> users
nonce_store -> nonces
Closes #240
=> pluralize users and nonces

assets/styles/authoring/layout/workspace.scss, lib/oli_web/templates/layout/_account_header.html.eex, lib/oli_web/templates/layout/_project_header.html.eex, lib/oli_web/templates/layout/_workspace_header.html.eex
This PR cleans up the header display, right-aligning the project name where it was centered.
Given that the active project can be switched via the projects page, we do not need a dropdown in the header to switch. 
Closes #211
=> improve header layout

assets/src/components/activities/multiple_choice/MultipleChoiceAuthoring.tsx, assets/src/components/activities/short_answer/ShortAnswerAuthoring.tsx
This PR fixes a problem where activity editors were posting an unnecessary, immediate save back to the server when they stood up.  The root cause was the effect driving this executes on the initial view of its dependency - not just when that dependency changes. 
Closes #286
=> prevent immediate save

assets/src/components/activity/Navigation.tsx, assets/src/components/common/BreadcrumbTrail.tsx, assets/src/components/resource/ResourceEditor.tsx, assets/src/data/content/activity.ts, lib/oli/authoring/editing/activity_context.ex, lib/oli/authoring/editing/activity_editor.ex, lib/oli_web/controllers/activity_controller.ex, lib/oli_web/controllers/resource_controller.ex, lib/oli_web/live/curriculum/container.ex
This PR adds breadcrumb trail navigation for the curriculum, page, and activitiy editors 
It also allows the left-hand nav "Curriculum" link to remain active when a page or activity editor is in view. 
I removed the Prev and Next activity navigation buttons from the activity editor. With the breadcrumb trail in place it just seemed like too much in the UI. 
Closes #287
=> breadcrumb trail navigation support

assets/src/components/editor/Toolbars.tsx
Fixes an issue caused by the change from visibility toggling to display toggling where the toolbar would no longer be displayed. The original change was to fix an issue where the toolbar caused the page to scroll past the bottom of the content leaving an empty white strip at the bottom of the page.
Closes #321
=> fix an issue where the formatting toolbar wasn't being displayed

lib/oli/authoring/course.ex, lib/oli_web/common/links.ex, test/oli/course_test.exs
This PR fixes an issue when the root container changes and a user clicks the "Publish" tab.  Root cause was that that type of change was considered as valid when constructing links.
I also adjusted the title of that root container to instead just be "Curriculum".  It was previously displaying the original title of the course with " root container" appended.  That title could get out of date as soon as a user edits the title.  
Closes #310
=> Resource link

lib/oli_web/live/curriculum/container.ex, lib/oli_web/live/history/details.ex, lib/oli_web/live/objectives/objectives.ex
I performed an audit on all uses of `String.to_atom`. 
Where possible I replaced with `String.to_existing_atom`
The only place where user input is converted to atoms is in the `./lib/oli/utils/snapshots/snapshot_seeder.ex` code that processes an external CSV to generate test data.  While this is primarily a test tool, it is being used right now to seed production data when a database is created.  It only triggers a dozen or so new atom creations, so I don't believe that it poses an risk. 
Moving forward we need to include in our code reviews a review of usages of `String.to_atom`
Closes #282
=> convert to to_existing_atom where possible

lib/oli_web/templates/layout/delivery.html.eex
This PR enables LaTex rendering in delivery mode, via MathJax v3.  
It pulls forward the same MathJax configuration, using \(   \) to delimit inline math, and $$ $$ and \[ \] to delimit block math.
Closes #308
=> enable mathjax 3 in delivery only

lib/oli/authoring/course.ex, lib/oli/utils/slug.ex, test/oli/utils/slug_test.exs
This PR adjusts slug generation to remove all non alpha numeric characters.  Some of these characters, when encoded as a URL were causing problems in routing, which breaks all LiveViews that include slugs in their URL 
[error] GenServer #PID<0.5095.0> terminating
** (ArgumentError) cannot invoke handle_params nor live_redirect/live_patch to "http://localhost:4000/project/my_test_project_%60~%21%40%23%24%25%5E%26%2A%28%29--%2B%3D%5B%5D%7B%7D%5C%7C%3B%3A%27%22%3C%3E%2C.%2F%3F/curriculum" because it isn't defined in OliWeb.Router
I have tested this locally and it fixes the problem 
Closes #334
=> Slug special chars

lib/oli/authoring/editing/page_editor.ex
Pass along the correct arguments, otherwise any time a title edit is made the user receives a persistence error.
=> pass along correct arguments

assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, lib/oli/delivery/attempts.ex, lib/oli_web/controllers/page_delivery_controller.ex
This PR hides the "Submit" button for single response quesions in a graded context.
In a graded context, all part attempts should be "not evaluated" at the time that the user clicks "Submit Assessment"
Having this button visible allowed a user to Submit a part, which broke assessment submission.
I'm filing a follow up bug to make Assessment submission more robust to this situation - because there will eventually be activity implementations that we do not control that submit ahead of time in a graded context. 
Closes #377 
Closes #295
=> do not display submit button, adjust error capture

assets/src/components/modal/ModalSelection.tsx, assets/styles/authoring/main.scss, assets/styles/delivery/main.scss, lib/oli/authoring/media_library/item_options.ex
Closes #383 
This was a simple fix, the default sort order field name was incorrect. 
Closes #368 
Also prevents the modal appearance from scrolling to the top of the page.  This was not obvious to me how to fix this, but the following SO question showed how: https://stackoverflow.com/questions/21604674/bootstrap-modal-background-jumps-to-top-on-toggle
I also added the class name to allow the Media Library to display vertically centered on the page.
=> Pair of Media Library fixes

priv/repo/migrations/20200710120811_adjust_string_lengths.exs
This PR adds a migration to adjust the lengths of a handful of fields in our schema that are currently set to a max of 255 characters. 
I tested this locally via `mix ecto.migrate` and it worked great. 
Closes #355
=> adjust length of various strings to allow them to exceed 255 chars

lib/oli_web/live/qa/qa_live.ex
"last review run" was not shown unless there were warnings, making it seem like the run review feature was broken. we should show an indication of the last review run regardless of the results
=> Show when last review was run even when there are no improvement opportunities

assets/src/components/editor/Editor.tsx, assets/src/components/editor/editors/SizePicker.tsx, assets/src/components/editor/editors/Table.tsx, assets/src/components/editor/normalizer.ts
Closes #397 
Closes #346 
This PR fixes three problems:
1) Deleting content in a cell can delete the cell, leaving the table in a weird state.  I have added table specific normalization to ensure that all rows always have the same number of cells, thus overriding a cell deletion
2) The auto-resizing table dropdown was hard to use when it was over certain elements (e.g. YouTube) and also rendered oddly when it pops up above the toolbar item (like when that toolbar item is at the bottom of the page).  I simply disabled the self-growing aspect of this size picker
3) In debugging the first issue, I caught a possibly SERIOUS performance issue with how our custom slate normalization was being installed.  Our custom `normalizeNode` function overrides the built-in one, but then calls the built in …
=> table fixes

assets/src/components/editor/Toolbars.tsx
Closes #364 
Removes 'title' from the list of text formatting options
=> remove title from heading list

assets/src/components/editor/Editor.tsx, assets/src/components/editor/editors/Blockquote.tsx
Closes #362 
Closes #348 
This PR does two things:
1) When a user is in a heading format (h1..h6) and has their cursor at the end of that block and presses Enter, the format for the next block that will get inserted will revert back to normal (a paragraph)
2) In doing the above, it made sense to pull out the blockquote constraint and fix that as well.  Now blockquotes can contain multiple paragraphs.
=> Reset heading format on Enter

lib/oli_web/templates/project/overview.html.eex, lib/oli_web/views/project_view.ex
Datashop export throws error for projects with no publications
Should move this to admin after learnlab
=> prevent datashop download from being clicked with no publications

assets/styles/authoring/layout/workspace.scss, lib/oli_web/templates/layout/_project_sidebar.html.eex, lib/oli_web/templates/project/overview.html.eex, lib/oli_web/templates/workspace/account.html.eex, lib/oli_web/views/project_view.ex
I accidentally branched off of one of the other open styling PRs, so the others should be merged first to hide those changes in this PR.
- Prevent workspace header from expanding horizontally with long project titles. We'll want to add a project title max size.
- Prevent long name from overflowing page
- Change styling in sidebar to get rid of the horizontal lines that blended in with the page
=> Account link and workspace sidebar/header fixes

lib/oli/analytics/datashop.ex, lib/oli/analytics/datashop/utils.ex, lib/oli_web/controllers/project_controller.ex, test/oli/datashop_test.exs
After some googling, I found this Phoenix controller method for sending file attachments from memory rather than the local file storage.
https://hexdocs.pm/phoenix/Phoenix.Controller.html#send_download/3
This works locally, but hasn't been tested on test/production. I'll need to test this with a deployed canvas course on tokamak/proton that has student attempts to make sure it works the same way.
=> Change datashop download method

lib/oli_web/live/objectives/objectives.ex
Based on feedback that the new / existing objectives sections ran together
=> Small style pr: Split out "new objective" from "existing objectives", add placeholder objective text

lib/oli/analytics/datashop/elements/event_descriptor.ex
Add a try catch around the problem area that was causing a datashop export failure from not being able to parse activity content.
The logging will help us identify the root cause if this happens again, which should be an easy fix once we know the activity model content that is triggering it.
=> Prevent one datashop export failure

assets/styles/authoring/curriculum.scss, lib/oli_web/live/curriculum/container.ex, lib/oli_web/live/curriculum/entry.ex, lib/oli_web/live/curriculum/settings.ex
This PR adds an activity and attached objective display rollup to the curriculum view.
At first load, the view now looks at all embedded activities contained in the list of pages in the container. It creates three maps to use in displaying the unique set of attached objectives for each page:
page_to_activity - a map of page resource ids to a list of activity ids
activity_map - a map of activity resource ids to the actual revision for that activity
objective_map - a map of objective resource ids to the actual revision for that objective
With these three maps it is straightforward (and efficient) to get the set of objective titles that are "attached" to a page, via its activities.
The view now also keeps active subscriptions open to these activities and objectives so that it can respond to …
=> Curriculum rollup

lib/oli/delivery/attempts.ex
This is a small adjustment to assessment submission logic necessary to support activities that directly submit outcomes (as opposed to using Torus server-side evaluations).   Currently this is only possible with code on the `iframe-activity` branch - but it makes sense to get this in place now (it would have prevented the problem that the long text single response caused during the alpha test, for example). 
The idea here is that activities that directly submit outcomes will be finalizing activity attempts before the student submits the assessment.  So the assertion in this code that all activity attempts are still "yet to be finalized" cannot hold.
=> finalize only those activities that are not evaluated

lib/oli_web/live/qa/state.ex, test/oli_web/live/qa_logic_test.exs
This was an easy fix - but in writing the test for it I noticed a flaw in the entire test suite for the qa_logic_test.exs - I hadn't properly set up the content review to get tagged as an actual "content" review.  Those warnings were being added to the "pedagogy" review. 
Close #359
=> correctly handle selection logic when filtered

assets/src/components/content/AddResourceContent.tsx, assets/src/components/modal/ModalSelection.tsx, assets/src/components/resource/Editors.tsx, assets/src/components/resource/ObjectiveSelection.scss, assets/src/components/resource/ObjectiveSelection.tsx, assets/src/components/resource/Objectives.tsx, assets/src/components/resource/ResourceEditor.tsx, assets/src/data/content/objective.ts, assets/src/data/persistence/activity.ts, lib/oli/activities/model/part.ex, lib/oli/authoring/editing/activity_editor.ex, lib/oli/authoring/editing/page_editor.ex, lib/oli/publishing.ex, lib/oli_web/controllers/activity_controller.ex, test/oli/editing/activity_editor_test.exs, test/oli/editing/objective_editor_test.exs, test/oli/publishing_test.exs
This PR introduces an explicit step for the selection (and optionally the creation) of objectives prior to the creation of an activity. 
I explicitly avoided an implementation that allowed creation of an objective as a separate step, since it seemed like it was going to be challenging for the user to understand that they then have to "select" that objective.  
So the approach taken here is to allow a user ability to *either* select any number of existing objectives, or the create and use a new one, or to simply skip attachment altogether.  
Closes #410
=> Objective modal

lib/oli/rendering/content/html.ex, test/oli/rendering/content/html_test.exs
* Audio
* Image
* Code
* Table
* Youtube
The accessible solution was to wrap the elements in a `<figure>` and use `<figcaption>` to display the caption. Tables are a little different in that they use a `<caption>` element within the table itself.
=> Display captions in delivery/preview mode

assets/src/components/content/AddResourceContent.scss, assets/src/components/content/AddResourceContent.tsx, assets/src/components/resource/Editors.scss, assets/src/components/resource/Editors.tsx
This PR expands the last drop area in content drag and drop mode to enable easier rearranging. It also addresses another point made in the alpha test by adding a pseudo button increasing the discoverability of how to add content and activities to a page.
Closes #401
=> Rearrange last drop area should be bigger

lib/oli/authoring/editing/page_editor.ex, lib/oli/authoring/editing/util.ex, test/oli/editing/page_editor_test.exs
This PR extends page deletion processing to include marking child activities within a page as deleted whenever the parent page is marked deleted.
=> Cascade page delete activities

assets/src/components/editor/Editor.tsx, assets/src/components/editor/editors/Image.tsx, assets/src/components/editor/editors/YouTube.tsx
Closes #347 
This PR simply adds a highlight border when an image or youtube video is selected, indicating to the user (perhaps) that pressing enter adds more content.  
This isn't a perfect solution, but it is a step in the right direction.
=> add outline highlight for selected image and youtube

assets/src/components/resource/ResourceEditor.tsx
Closes #438 
The issue here was browser specific.  For some reason Firefox suppresses the execution of HTTP requests from inlined code in a beforeunload window event.  Putting that same code in another execution context (via `setTimeout`) fixes the problem. 
I tested this and it still works in Chrome.
=> Fix locking

lib/oli/delivery/page/page_context.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/page.html.eex
On delivery mode; disables the "Submit Assessment" button if the assessment page has zero activities
=> hide submit button

assets/styles/delivery/page_delivery/page.scss, lib/oli/delivery/page/objectives_rollup.ex, lib/oli/delivery/page/page_context.ex, lib/oli/publishing/authoring_resolver.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli/publishing/resolver.ex, lib/oli/qa/reviewers/pedagogy.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/controllers/resource_controller.ex, lib/oli_web/templates/page_delivery/_objectives.html.eex, lib/oli_web/templates/resource/page_preview.html.eex, test/oli/delivery/page/page_context_test.exs, test/oli/publishing/authoring_resolver_test.exs, test/oli/publishing/delivery_resolver_test.exs, test/oli/qa/pedagogy_test.exs, test/oli_web/live/qa_logic_test.exs
Closes #371 
This PR does two things:
1) Removes the "attached objectives to a page" qa warning check
2) Displays a roll up of attached objectives to page delivery and page preview.  This roll up is designed to only show "top level objectives".  So if a user attaches a child objective to an activity - this rollup will display the title of the parent objective to that child objective on the page.  
Note, this is the first part of the system that takes the approach of having the resolver passed down into it.  This allows this rollup logic to work correctly when it is used in a delivery or authoring context, since it isn't directly depending on either of those resolvers.
=> Additional rollup work

assets/src/components/editor/editors/Link.tsx
Closes #365 
Unfortunately i had to punt on using the tiny-popover as the creation mechanism. It was a hack to begin with - getting it to auto display on link creation.  
This PR changes it to use a modal.
=> use a modal for link creation

assets/src/data/persistence/common.ts
Removes the `keep-alive` param from make requests.  This was added recently in the bug fix to allow requests to succeed when a page is closed.  This isn't needed to fix that problem - but , as we now discovered - it must be removed because it breaks certain types of HTTP requests. 
I tested making changes and quickly leaving the page and there is no data loss.  
Closes #467
=> remove keep-alive flag

assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, lib/oli/delivery/attempts.ex
Closes #481 
Closes #477 
This PR fixes the ability for text short answer input questions to properly restore their saved state. 
It also fixes a bug that ASU originally reported and that I was having trouble reproducing.  As soon as you get activity attempts for the same course resource from different resource attempts (e.g. you have multiple users visit a page with a practice activity) the query that we had that identifies the latest activity attempts and latest part attempts fails.  I adjusted the query to ensure the activity attempts join and the part attempt join are using the same parent record id. There were other places where similar query logic was present - I adjusted those as well.
=> Restore text activities

assets/src/components/editor/editors/YouTube.tsx
Closes #471 
A simple fix to allow YouTube insertion to occur at the last selection.  This was failing since the introduction of the modal selection for input of YouTube video id will cause the underlying Editor to lose its selection.
=> Youtube placement

assets/src/components/editor/editors/YouTube.tsx
This PR now allows the youtube creation logic to account for URLs of the form: "https://youtu.be/RbZ13TEHuOs"
=> account for youtu.be style URLs

lib/oli_web/live/objectives/objectives.ex
Closes #466  
This PR adds a sort of the top level objectives. The sort is by *resource* insertion date, not *revision* insertion date.  Revisions get created all the time, so sorting by that will not work.
=> sort by resource inserted_at

lib/oli_web/controllers/lti_controller.ex, lib/oli_web/live/objectives/objectives.ex
Closes #479 
This PR adds a step in the LTI process to detect that if a section exists for this launch, we update the section title based on the LTI launch param
=> Update section information

assets/src/components/content/AddResourceContent.tsx, assets/src/components/misc/EditLink.tsx, lib/oli_web/live/objectives/objectives.ex
Closes #455 
This PR fixes the initial display of a newly created activity in the page editor.  The objectives display incorrectly stated "No objectives attached" even when some were selected.
=> Fix objective display

lib/oli_web/templates/workspace/account.html.eex, lib/oli_web/views/layout_view.ex
- Remove theme selection from account view
- Change theme lookup logic to always use "default" (light) theme
=> Temporarily disable theme switching for LearnLab

lib/oli_web/templates/shared/_admin_edit_banner.html.eex
This PR addresses the issue of the admin bar covering up the toolbar. The admin bar is now fixed at the top of the page so it doesn't interfere with the sticky toolbar Since users can be admins now, this could be an annoyance to anyone with an admin account.
Closes #497
=> fix admin banner and toolbar

lib/oli/qa/reviewers/pedagogy.ex, lib/oli/qa/uri_validator.ex
Closes #503 
This PR fixes a bug in the objective attachment check.  This was introduced when we removed this check from pages. 
I also ran in to a problem - more serious - with the URI validator code in the content review.  I just happened to have a link in my content erroneously set to `https://www.google.coms`. Notice the `s` at the end.  This link was breaking the URI validator in a way that prevented the rest of the reviews from running.  Here is the exception it threw:
```
[error] GenServer #PID<0.8609.0> terminating
** (stop) exited in: Task.Supervised.stream(5000)
** (EXIT) time out
(elixir 1.10.2) lib/task/supervised.ex:303: Task.Supervised.stream_reduce/7
(elixir 1.10.2) lib/stream.ex:1609: Enumerable.Stream.do_each/4
(elixir 1.10.2) lib/enum.ex:3383: Enum.reverse/1
(elixir …
```
=> Fix review

assets/src/components/content/AddResourceContent.scss, assets/src/components/editor/Editor.tsx, assets/src/components/editor/editors/Lists.tsx, assets/src/components/editor/utils.tsx, assets/src/components/resource/Editors.scss
This PR attempts to fix an issue where course content created with an older version of the editor would crash slate instances by only setting the editor selection if the prop is not undefined. It also changes all null checks to also check for undefined since selection can be null or undefined.
It also includes two style tweaks: 1) improve selection within a content resource frame by moving the container padding to the slate instance itself and 2) recenter the add content button icon. These 2 changes are strictly style changes so they are relatively low risk.
=> Fix selection change causing slate crash

assets/src/components/resource/ResourceEditor.tsx
This PR fixes an issue where the modifier key in windows was the Windows key, which wasn't allowing users to actually click on anything and inadvertently popped up the start menu. This changes to use the system 'mod' key which on mac is CMD and windows is Ctrl
**Risk**: Low, only affects preview button
**Stability**: Tested on Mac and Windows and is stable. However, my windows instance only allowed about a second of time to click the button when Ctrl is down but I am wondering if that is something specific to my install.
=> fixes an issue with windows modifier key and preview

assets/src/components/media/manager/MediaManager.tsx
Firefox was not respecting the file upload mimetype filter we had in place because we had an invalid `/*` at the end of the mimetype list. 
On a separate note - the `mimeFilter` variable is a `string[] | undefined`, where undefined indicates "all" media is allowed. We don't use the "all" mimeFilter anywhere at the moment, but I tested it in chrome to make sure using `undefined` allows all media type uploads.
I also just changed the `multiple` attribute to remove the `true`. Apparently, `multiple` doesn't accept a parameter, it's just a tag.
Closes #519
=> Fix filetype accept filter for Firefox

lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/templates/resource/page_preview.html.eex
**Issue**: Latex was not properly rendering in page preview mode.
**Cause**: When the `ResourceEditor` swaps to preview mode, the MathJax delivery script is re-initialized with a new window variable but not executed to compile the Latex and render it. It works when opening the preview in a new tab, but not when it swaps out the current editor view.
**Solution**: This is more of a workaround than anything -- I would like to find a way to get the script to execute when loading the delivery file in preview mode -- but I added the MathJax script to the authoring template so that it can run in the author. I wrapped the authoring HTML in a div with an `ignore` class name, and then white listed the `delivery` preview mode HTML for MathJax to render it.
**Risk**: Moderate. This change is to the …
=> Add MathJax latex rendering to preview

assets/src/components/resource/ResourceEditor.tsx
Windows prevented the Preview Page link from opening in a new tab.
See https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
Tested on tokamak. This fixes the issue.
Low risk.
=> Handle keyboard repeat event in ResourceEditor preview button

assets/src/hooks/index.ts, assets/src/hooks/tooltip.ts, lib/oli_web/live/objectives/actions.ex
This PR fixes an issue where tooltips were not rendering in the objectives page Phoenix LiveView. The root cause was that LiveView changes the DOM out from under the Popper.js library. The solution to add `phx-update="ignore"` was suggested by an elixir forum member https://elixirforum.com/t/phoenix-liveview-and-bootstrap-tooltips/33401
Closes #528
=> fix tooltip issue with phx-update ignore

assets/src/data/content/writers/html.ts
There is an extra quote being inserted before tables when rendered client-side, and borders are not showing up. The second issue is a class name that was added to server-side rendering but not replicated client-side.
Risk: very low
=> Fix typo with html client-side rendering

assets/src/components/activities/common/Evaluation.tsx, assets/styles/delivery/activity.scss
Styling fixes for two issues:
1) When feedback spanned multiple lines or the score was more than one digit, it shrunk the result score box, pushing the numbers outside of the box. Handled by changing `width` to `flex-basis` and adding a `flex-shrink`
2) The `/` divider was not completely centered. Removed the spaces and added margins around it.
Closes #560
=> Fix result score box styling issue in delivery

assets/src/components/editor/editors/YouTube.tsx
The `insert` button in the bootstrap modal is difficult to disable with the way we handle the `selected` state. Instead of disabling it with no URL entered, I'm just keeping it enabled but inserting the youtube placeholder video when a URL is not entered.
Closes #556
=> Fix Youtube modal insert button

lib/oli/publishing/authoring_resolver.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli/publishing/resolver.ex, lib/oli/resources/numbering.ex, lib/oli/utils/db_seeder.ex, lib/oli/utils/hierarchy_node.ex, test/oli/publishing/authoring_resolver_test.exs, test/oli/publishing/delivery_resolver_test.exs, test/oli/resources/numbering_test.exs
This PR introduces the following:
1. `Oli.Resources.Numbering` - a module to use to calculate the levels and level-based numbering of containers in a course hierarchy.  It only offers full hierarchy calculation.  I intended to support path-specific, but after consideration this is an optimization that really doesn't buy us all that much. This currently only numbers containers, but we can expand it in the future to number pages. 
2. `hierarchy` resolution function in the `Resolver` behavior - a new resolver function to retrieve all the pages and containers in  a course hierarchy.  This can be used in conjunction with numbering to provide specialized hierarchy UIs
=> Path numbering

docs/LTI1.3.md, lib/oli/lti_1p3/context_roles.ex, lib/oli/lti_1p3/platform_roles.ex, lib/oli_web/controllers/delivery_controller.ex, test/oli/lti_1p3/context_roles_test.exs, test/oli/lti_1p3/platform_roles_test.exs, test/oli_web/controllers/delivery_controller_test.exs, test/support/lti_1p3_test_helpers.ex
This PR addresses an issue where users can have multiple roles on LTI launch and torus should use the role with the highest permissions, such as Instructor over Student.
This PR also includes unit tests for the ContextRoles and PlatformRoles modules.
Closes #609
=> Fix user can have multiple lti roles

lib/oli/grading.ex, lib/oli/grading/line_item.ex, lib/oli/grading/lti_ags.ex, lib/oli/grading/score.ex, lib/oli/lti_1p3.ex, lib/oli/lti_1p3/access_token.ex, lib/oli/lti_1p3/joken_config.ex, lib/oli_web/controllers/lti_controller.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/after_finalized.html.eex, test/oli/grading/lti_ags_test.exs, test/support/lti_1p3_test_helpers.ex
This PR adds support for LMS grade passback via LTI Assignment and Grade Services (LTI AGS) 2.0. 
1. A student submits a graded page attempt.
2. The system finalizes that attempt and rolls up a score to the `resource_access` record for that resource and student.
3. If the LTI Launch params have LTI AGS enabled, the system requests from the LMS an access token.
4. Using the access token as a Bearer token, the system queries the AGS endpoint to determine if a line item for this resource exists.  
5. If the line item does not exist, the system uses the access token to invoke another AGS endpoint to create that line item.
6. If the line item does exist, but it's label or max score relative to the current score is out of date, the system will issue a request to an AGS endpoint to update the …
=> Grade services

lib/oli/delivery/attempts.ex, lib/oli/delivery/attempts/scoring.ex, lib/oli/grading.ex, lib/oli/grading/line_item.ex, lib/oli/grading/lti_ags.ex, lib/oli/grading/score.ex, lib/oli/lti/line_item.ex, lib/oli/lti/lti_ags.ex, lib/oli/lti/lti_nrps.ex, lib/oli/lti/membership.ex, lib/oli/lti/score.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/grades/export.ex, lib/oli_web/live/grades/grade_sync.ex, lib/oli_web/live/grades/grades.ex, lib/oli_web/live/grades/line_items.ex, lib/oli_web/router.ex, lib/oli_web/templates/delivery/unauthorized.html.eex, lib/oli_web/templates/layout/live.html.leex, lib/oli_web/templates/page_delivery/index.html.eex, test/oli/delivery/attempts/scoring_test.exs, test/oli/delivery/submission_test.exs, test/oli/grading/lti_ags_test.exs
Adds a "Grades Management" UI that instructors can use to update line items, sync grades, and export gradebook.
The UI is LiveView driven and allows the serial execution of a collection of tasks related to creating, updating line items and posting scores.  After completion of each "task" a progress bar in the UI is updated.
A key change that was also made was to introduce a prefix to the resourceId attribute that we are populating in the LMS created line item.  This helps to guarantee that another, non-Torus tool populating line items and setting resource_ids does not conflict with Torus. 
This feature uses LTI Names and Roles Provisioning service to determine all currently enrolled students so that we do not attempt to post scores for students that have been removed from the LMS section. …
=> Full grade sync

lib/oli_web/templates/workspace/account.html.eex, mix.exs
This PR fixes an issue on accounts page where if AccountPreferences exist for a user, the page crashes with a fetch error. Instead of using [] notation to access the live_preview_display setting this uses Map.get.
Also updates the version number in mix.exs
=> Fix Accounts page issue and update version number

lib/oli_web/router.ex
When submitting an activity in delivery, the server would throw a missing lti_params error. This PR fixes that by running these requests through a delivery_protected plug, ensuring the user is authenticated and these lti_params are added to assigns
=> fix an issue with attempt submission lti_params missing

assets/styles/authoring/model-editors.scss
This PR applies the styles defined in model-editors to rich-text-editor.
Closes #688
=> add correct styles to editor in activities

.gitignore, docs/DEVELOPER.md, lib/oli/utils.ex, priv/repo/seeds.exs
This PR add the ability to automatically seed registrations in dev mode using a registrations.json file in the root of the project. If no file exists, no registration will be created.
Example registrations.json
```
[{
"issuer": "https://canvas.oli.cmu.edu",
"client_id": "XXXXXXXXXXXXX",
"key_set_url": "https://canvas.oli.cmu.edu/api/lti/security/jwks",
"auth_token_url": "https://canvas.oli.cmu.edu/login/oauth2/token",
"auth_login_url": "https://canvas.oli.cmu.edu/api/lti/authorize_redirect",
"auth_server": "https://canvas.oli.cmu.edu"
}]
```
=> create registrations in dev mode from json file if available

lib/oli/analytics/datashop/elements/event_descriptor.ex, lib/oli/lti/lti_ags.ex, lib/oli/utils/db_seeder.ex, test/oli/datashop_test.exs, test/oli/delivery/page/activity_context_test.exs, test/oli/registrar_test.exs
The problem was that registering new activity types changed the order of ids, so anywhere that we had a hardcoded activity type id that expected an activity of a certain type to be created was failing.
=> Fix Datashop tests

CHANGELOG.md
I incorrectly named the branch 0.3.0, but the change log and branches are both correct 0.4.0
=> Update Change Log 0.4.0

CHANGELOG.md, lib/oli/activities.ex, mix.exs, priv/repo/seeds.exs
This PR turns the `Oli.Registrar.register_local_activities()` function into an operation that is safe to run during every seeding. It will create new local activity registrations for new activities that are present and update records for existing ones that may have changed.
=> register new local activities during seeding, update existing

lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/delivery/configure_section.html.eex, lib/oli_web/templates/delivery/getting_started.html.eex, test/oli_web/controllers/delivery_controller_test.exs
This PR removes the display of "Open and Free" courses from both the "Getting Started" page and the "Create Section" page. 
It leaves the infrastructure (the db field and schema reference) in place in case we want to repurpose it once we figure out a longer term plan for how to handle open and free courses. 
Closes #281
=> remove open and free selection

lib/oli_web/controllers/lti_controller.ex, lib/oli_web/templates/email/registration_approved.html.eex, lib/oli_web/templates/lti/registration_pending.html.eex, priv/repo/migrations/20201211141735_improve_lti_workflow.exs
This PR fixes 2 database migration script issues:
1. The migration didn't properly add the `on_delete: :delete_all` rules to the tables. The old method lost the foreign key in the process, this PR keeps it.
2. The migration was not reversible. However, since foreign keys are ultimately being lost in the migration, the rollback has no way of restoring them. Therefore, even though this PR properly accounts for the `down` portion of the migration, this release is not easily reversible and a database restore will be the preferred method of rollback.
Also included is some wording changes and request details on the request pending page.
This PR is critical for the 0.5.0 release.
=> fix migration script

CHANGELOG.md, lib/oli/help/providers/freshdesk_help.ex
This PR adds missing support for handling status 201 response on FreshDesk API calls
=> Freshdesk api bug

CHANGELOG.md, lib/oli/accounts/schemas/user.ex, lib/oli/institutions/institution.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/templates/layout/help_email.text.eex, priv/repo/migrations/20210113153906_eliminate_user_inst_fkey.exs, test/oli/sections_test.exs, test/oli_web/controllers/delivery_controller_test.exs
This PR removes the relationship between individual users and institutions, and instead uses the deployment ⟶ registration ⟶ institution relationship to create a section. Once enrolled, a user's institution relationship can be identified through the user's section enrollment ⟶ section ⟶ institution relationship.
This is a more correct way of modeling these relationships, removing the tight coupling of users and institutions as well as eliminating the possibility of a user's institution being out of sync with one or more section institution fkeys.
Closes #767
=> Eliminate user inst fkey

CHANGELOG.md, assets/src/components/content/AddResourceContent.tsx, assets/src/components/modal/ModalSelection.tsx
Closes #492 
This PR fixes the problem where the use clicks the "X" button in the upper right corner of the objective selection dialog, thinking that they can cancel activity creation - but the activity gets added anyways.
The fix here is to simply remove the "X" button from the dialog.  This is really the only possible solution that doesn't involve a fair bit of rework because of how the "Cancel" action is overridden in this modal usage.  This "X" button is only removed for *this* instance of the modal usage, not all usages.
=> remove ability to cancel activity creation

CHANGELOG.md, assets/src/components/activity/ActivityEditor.tsx, assets/src/components/messages/Banner.tsx, assets/src/components/resource/resourceEditor/ResourceEditor.tsx
This PR closes #544 by ensuring the message banners in page and activity editing are always visible even if the page is scrolled.  It does so by set them to be "sticky".  
Also, in testing this I discovered that the messages for the various types of failures were not being de-duped by failure type (so if you get ten failures for bad content, you get ten messages).  I ensured that there is only one message instance per category of failure.
To test out the sticky-ness of the banner, go to the "update" function in `resource_controller.ex` and comment out the actual impl and have it simply return `error(conn, 500, "server error")`
=> Sticky warning

CHANGELOG.md, assets/src/components/editing/commands/AudioCmd.tsx, assets/src/components/editing/commands/BlockcodeCmd.tsx, assets/src/components/editing/commands/ImageCmd.tsx, assets/src/components/editing/commands/WebpageCmd.tsx, assets/src/components/editing/commands/YoutubeCmd.tsx, assets/src/components/editing/commands/table/TableCmd.tsx
Closes #710.  
This PR fixes the problem where certain block-level content types were now being inserted always at the bottom of the current structured content - and not at the location of the user's cursor.  I'm not sure whether this broke due to a change in Slate that we absorbed, or due to the refactoring of the UI/UX approach regarding toolbar and insertion.
The fix implemented here simply caches the editor selection prior to displaying any intermediate UI, and then using that cached selection for insertion.
=> cache the selection to use during insertion

CHANGELOG.md, lib/oli/publishing.ex, test/oli/publishing_test.exs
This PR fixes an issue where stale locks were being considered when displaying the list of actively edited resources in the curriculum view. 
The fix here is to filter out expired locks in `Publishing.retrieve_lock_info`.  
Interesting, this function was trying to return a map, but was implemented incorrectly and was returning a list.  I have removed that as it wasn't necessary anyways. 
Closes #773
=> Filter stale locks

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This PR streamlines the project `README.md` file, adds a `CODE_OF_CONDUCT.md` and a `CONTRIBUTING.md`
For the `README.md`, It moves the setup instructions to the Wiki, and replaces that with a marketing oriented list of features and pointers to the product roadmap, Wiki, and API docs.
=> revamp project's code docs

CHANGELOG.md, lib/oli/delivery/sections.ex, mix.exs
Fixes an issue where existing sections have null `lti_1p3_deployment_id`. Reverts to simply using context_id.
=> revert section lookup back to using context_id

CHANGELOG.md, assets/src/components/editing/editor/Editor.tsx
This PR fixes an issue where the editor crashes when content that contains newlines is pasted from an external source. It also fixes the issue with editor selection being outdated when a paste is performed, causing the pasted text to paste into an unexpected location. The fix was to move the onPaste callback to the Slate editor and use the latest editor provided to the callback.
Closes #801
=> fix an issue where editor crashes on paste

CHANGELOG.md, assets/src/data/content/writers/html.ts, assets/test/utils/writer_test.ts
Closes #824 
This PR fixes the client-side HTML rendering code to escape HTML special characters within text nodes.
=> Html escape

CHANGELOG.md, lib/oli/authoring/course.ex, lib/oli/interop/ingest.ex, lib/oli_web/templates/ingest/index.html.eex
This PR reverts the approach taken from letting a course digest specify its project slug, back to the the server owning that determination. 
Letting the digest decide was only necessary to allow "ahead of time" specification of media asset URLs in digest content that would match the project slug.  I realized that approach isn't strictly required as it really doesn't matter if the folder where a file is referenced in S3 differs from the actual slug, given that we track everything in the media assets relation in the DB. 
I also took a moment to improve some of the UI around documentation.
=> revert to server driven slug generation, improve docs

CHANGELOG.md, lib/oli/qa/utils.ex, lib/oli_web/live/qa/warning_details.ex, test/oli/qa/accessibility_test.exs
This PR fixes two problems related to QA mode:
1. Large images in accessibility warnings obscure the rest of the UI.  This was fixed by constraining their (and iframe) sizes.
2. In the course of fixing the above, I noticed that pages that contained multiple images that didn't have ALT text were not correctly showing up in accessibility warnings.  Specifically, the first image was repeated and the second image wasn't shown.  I tracked this down to the post processing we do to remove duplicates from the element in content JSONB path query.  Comments in that code explain the exact structure of the query results and what we need to do to properly dedupe.
Closes #834
=> Resize images, fix element query post processing

CHANGELOG.md, lib/oli_web/live/curriculum/settings/settings.html.leex
Closes #842 
This PR allows cancelling of a curriculum deletion request.  The `phx-capture-click` in conjunction with `phx-window-keydown` were firing the "delete" action immediately - instead of waiting until the `data-confirm` driven modal confirmation dialog was answered.
=> Cancel delete

lib/oli/utils/slug.ex, priv/repo/migrations/20210325175834_slug_alphanumeric_only.exs, test/oli/utils/slug_test.exs
This PR fixes an issue with slug generation where illegal UTF-8 chars could slip through the \W regex. The fix is to change the regex to explicitly only allow alphanumeric chars and underscores (_).
This PR also includes a migration to fix any existing slugs by regenerating slugs for the affected records.
Closes #864
=> Slug alphanumeric fix

CHANGELOG.md, assets/src/components/editing/editor/handlers/void.ts, assets/src/components/editing/editor/normalizers/normalizer.ts, assets/src/components/editing/models/audio/Editor.tsx, assets/src/components/editing/models/image/Editor.tsx, assets/src/components/editing/models/webpage/Editor.tsx, assets/src/components/editing/models/youtube/Editor.tsx, assets/src/data/content/model.ts
Fix deleting media items in editors when using the backspace/delete keys. This ended up being a simple fix for as long as it took to figure out what the problem was. Slate void nodes must have a `content-editable=false` node INSIDE them to work properly. The `content-editable` attribute apparently can't be on the void node itself.
Closes #832 
**Fixes**
- Handle keyboard deletion for `image`, `youtube`, `audio`, `webpage` elements
- Fix several errors on webpage/iframe embeds (normalizer failing, deletion, extra newline not being inserted after iframes) that had to do with `iframe` not being a `schema` type recognizable to slate.
=> Fix editor media item deletion / webpage embed

CHANGELOG.md, lib/oli_web/controllers/delivery_controller.ex, mix.exs
This PR fixes an issue where an admin could not configure a course section without being an instructor in that course.
Closes #871
=> Fix an issue where admin roles cant configure course section

CHANGELOG.md, lib/oli/analytics/by_activity.ex, lib/oli/analytics/by_objective.ex, lib/oli/analytics/by_page.ex, lib/oli/analytics/common.ex, test/oli/delivery/analytics/analytics_test.exs
The data analytics queries used on the insights page looked at all activity attempt snapshots for resources tied to a course, but the project duplication feature shares resources across projects. This was causing the Insights page to show analytics data for the parent project after duplication.
**Fix**:
- Change insights/analytics queries to only look at snapshots for sections tied to the project, rather than all snapshots for a project's resources.
Closes #877
=> Fix Insights page to not show analytics data from parent course in a duplicated course

CHANGELOG.md, assets/styles/delivery/activity.scss
This PR fixes an issue where certain element might overflow out of an activity in the editor.
Closes #839
=> fix an issue where codeblock overflows inside activity

CHANGELOG.md, lib/oli_web/templates/layout/_delivery_header.html.eex
This PR removes the "Help" link from page preview mode
Closes #886
=> remove help link in preview

CHANGELOG.md, lib/oli/interop/ingest.ex
This PR adjusts how the ingest logic gets the id for a resource to ingest.  Previously it simply parsed the id from the file name in the "in memory" unzipped digest.  This proved to be problematic for file names that contained unicode characters.  To account for this, ids are now simply extracted from the attribute of the JSON content.  But, since the three "special" files in a digest (manifest, project, hierarchy) do not use ids, a fallback exists to parse the id from the file name.
=> Ingest ids

config/config.exs, lib/oli/delivery/sections/enrollment.ex, lib/oli/user_identities/user_identity.ex
This PR fixes timezone support in some schemas that didn't specify. It also sets a configuration that all migrations should use `type: :timestamptz` by default for `timestamps()`. It appears that no migration is necessary for existing timestamps that didnt explicitly specify `:timestamptz` since they utilize the same underlying storage type and the timezone conversion is simply done at the DB layer, but the configuration was added for consistency and documentation purposes.
Related Posts:
- https://elixirforum.com/t/why-cant-timestamptz-be-set-up-as-default-timestamp-for-migrations-in-config/25778/2
- http://www.creativedeletion.com/2019/06/17/utc-timestamps-in-ecto.html
Closes #779
=> fix timezone support in certain schemas

lib/oli_web/controllers/static_page_controller.ex, lib/oli_web/templates/layout/_delivery_footer.html.eex, lib/oli_web/templates/layout/_delivery_header.html.eex, lib/oli_web/templates/layout/_footer.html.eex
This PR fixes an issue where cookie preferences link doesn't work in authoring workspace layout.
=> move cookie prefs render to footer

assets/src/components/activities/DeliveryElement.ts, assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx, assets/src/components/activities/adaptive/authoring-entry.ts, assets/src/components/activities/adaptive/delivery-entry.ts, assets/src/components/activities/adaptive/manifest.json, assets/src/components/activities/adaptive/schema.ts, assets/src/components/activities/adaptive/utils.ts, assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx, assets/src/components/activities/common/Evaluation.tsx, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/ordering/OrderingDelivery.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/components/activities/types.ts, lib/oli/activities/model/conditional_outcome.ex, lib/oli/activities/model/feedback_action.ex, lib/oli/activities/model/navigation_action.ex, lib/oli/activities/model/part.ex, lib/oli/activities/model/state_update_action.ex, lib/oli/delivery/attempts.ex, lib/oli/delivery/attempts/feedback_action_result.ex, lib/oli/delivery/attempts/navigation_action_result.ex, lib/oli/delivery/attempts/state_update_action_result.ex, lib/oli_web/controllers/attempt_controller.ex, test/oli/delivery/attempts_test.exs, test/oli/delivery/submission_test.exs, test/oli/registrar_test.exs
This PR introduces the following:
1. Adaptive Activity type. This is largely a stub for now, but necessary to get in place to support ingestion. 
2. Refinements to the Attempts eval infrastructure to allow parts to define a collection of `ConditionalOutcome` instances - each with a rule and a resultant set of actions that would be triggered if the rule is evaluated to true.  The presence of one or more `ConditionalOutcome` instances is what allows Torus to know whether or not to route that eval to the "adaptive eval engine" (which is a hardcoded stub for now).   
Closes #918
=> Adaptive activity impl

lib/oli_web/templates/open_and_free/index.html.eex, lib/oli_web/templates/open_and_free/show.html.eex, lib/oli_web/views/view_helpers.ex
This PR fixes the open and free section url in details to open in a new tab.
Since this work is part of open and free and is cosmetic, I didn't add a new change log entry for it.
=> open link in new tab

lib/oli_web/templates/layout/_header.html.eex
PR to remove duplicate cookie consent script. Was in both the header and footer. Removed one from header
Closes #929
=> remove duplicate cookie script

CHANGELOG.md, lib/oli/interop/ingest.ex, test/oli/interop/digest/u-analog_and_digital-m-analog_and_digital-p-analog_and_digital.json, test/oli/interop/ingest_test.exs
This PR adds ingestion support for detecting "internal" links in page content of the form: `%{"type" => "a", "idref" => id }` where the `idref` value is the original idref from the course digest.  This PR "rewires" that link to use an "href" attribute that correctly points to the slug of the revision that got created for that resource identified by `idref`. 
This rewiring works by essentially making a second pass through all pages, and recursively parses their contents, looking for "a" elements.  If it finds one of the form that contains an `idref` it does the rewiring and tracks a new revision for that resource.  There is an optimization in place that only tracks a new revision when a link has been rewired.  If no links are rewired in a page, then no new revision is created.
There is a …
=> Rewire links

lib/oli/accounts/schemas/user.ex, lib/oli_web/controllers/delivery_controller.ex, priv/repo/migrations/20210412213517_user_guest_flag.exs
This PR adds a flag to the user schema for tracking whether a user is a guest or not.
It falls under the Open and Free section support functionality in Enhancements, so there is no new change log entry for this PR.
=> Add guest flag to user

CHANGELOG.md, assets/src/components/activities/DeliveryElement.ts, assets/src/phoenix/activity_bridge.ts, lib/oli_web/controllers/attempt_controller.ex, lib/oli_web/controllers/extrinsic_state_controller.ex, lib/oli_web/router.ex
This PR accomplishes two things:
1. Updates the user state endpoints to align their URL structures to match the rest of the service endpoints. This involves inserting `state` and also the `course` section slug into the URL.  
2. Adds OpenAPI documentation to the full set of user state endpoints, categorized between "intrinsic" and "extrinsic" state (relative to the attempt).
=> User state refinements

CHANGELOG.md, lib/oli_web/router.ex
This PR makes OpenAPI docs available in all environments at /api/v1/docs.
Closes #941
=> make api docs available in all environments

CHANGELOG.md, lib/oli_web/controllers/activity_controller.ex, lib/oli_web/router.ex, test/oli_web/controllers/delivery_retrieve_test.exs
This PR fixes a couple of endpoints in the activity "storage service" that were using section database ids in their URLs, instead of section slugs.   
After these endpoints migrated over to having the section slug present in them, it was no longer necessary to fetch the entire section to get that slug so that we can check enrollment.  Instead, the endpoints just now directly check enrollment.
=> use section slugs instead of ids

CHANGELOG.md, assets/src/components/editing/models/image/commands.tsx, assets/src/data/content/model.ts, assets/src/data/content/utils.tsx, assets/src/data/content/writers/html.ts, lib/oli/rendering/content/html.ex
Images currently support being floated left or right to sit alongside content. However, this causes display problems whenever the next `div` after the image doesn't clear the float. Originally I had a bunch of CSS fixes to clear floats everywhere, and then I realized as soon as people start writing new activities, they'll run into this problem if they don't follow the class name convention to clear the floats that could be present in page content.
Eventually I just decided to remove support for floating images since it seems like more trouble than it's worth. Existing floated images will be rendered as blocks.
Closes #963
=> Remove support for image floating

lib/oli/rendering/content/html.ex, test/oli/rendering/content/example_content.json, test/oli/rendering/content/html_test.exs
This PR disallows the rendering of raw html in image captions.
Closes #951
=> Disallow the rendering of raw html in image captions

CHANGELOG.md, lib/oli/activities/model.ex, lib/oli/activities/model/part.ex, lib/oli/delivery/page/activity_context.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/delivery.html.eex
This PR:
1. Elevates "outcomes" attribute of a Part to be "rules" and places it at the top level of the authoring portion of the model
2. Makes "responses" an optional attribute of a Part. 
3. includes the resource attempt guid as a delivery param
4. Includes the delivery element name as part of the attempt id mapping that is available as a delivery param
=> include delivery element name, resource attempt guid

CHANGELOG.md, lib/oli_web/templates/delivery/configure_section.html.eex
This PR fixes an issue where clicking the "Select and Continue" button on section creation form would submit twice, creating two different sections and forcing the application into an invalid state. Subsequent requests would throw a database error.
Closes #874
=> prevent multiple clicks on create section button

lib/oli/accounts/schemas/user.ex, lib/oli/delivery/attempts.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/section.ex, lib/oli/grading.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/live/delivery/manage_section.ex, lib/oli_web/router.ex, lib/oli_web/templates/delivery/configure_section.html.eex, lib/oli_web/templates/page_delivery/index.html.eex, lib/oli_web/views/delivery_view.ex, lib/oli_web/views/view_helpers.ex, priv/repo/migrations/20210420175605_section_status.exs, test/oli/sections_test.exs
This PR add functionality to "unlink" a section from an LTI context by marking the section as deleted.
There is some future UI refactoring that should be done to clean up the Instructor and Admin facing features on the index page. For now, it is simply represented as two buttons, "Manage Grades" and "Manage Section"
Closes #976
=> Add ability to unlink course section

CHANGELOG.md, lib/oli/rendering/content/html.ex, lib/oli/rendering/content/plaintext.ex, test/oli/rendering/page/audio_missing_src.json, test/oli/rendering/page/html_test.exs, test/oli/rendering/page/iframe_missing_src.json, test/oli/rendering/page/image_missing_src.json, test/oli/rendering/page/link_missing_href.json, test/oli/rendering/page/missing_language.json, test/oli/rendering/page/youtube_missing_src.json
Closes #993 
This PR improves the robustness of server side content rendering. The root cause of this brittleness was the strict pattern matching for certain content elements in the content HTML renderer.  For instance the following was the only definition of the `code` function:
```
def code(
%Context{} = _context,
next,
%{
"language" => language
} = attrs
) do
figure(attrs, [
~s|<pre><code class="language-#{escape_xml!(language)}">|,
next.(),
"</code></pre>\n"
])
end
```
So if some poorly formatted `code` element somehow gets into the system that does not have a `language` attribute (perhaps via ingestion, or a bug) the entire page rendering breaks, since no `code` function match can be made at run time. 
This PR addresses this by providing fallback implementations for all the functions …
=> [BUG FIX] improve rendering robustness

CHANGELOG.md, assets/package.json, assets/src/components/activities/image_coding/ImageCodingAuthoring.tsx, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/image_coding/sections/ImageCodeEditor.tsx, assets/yarn.lock
Adds a syntax coloring, auto-indenting code editor for image code activity and authoring, using the react-ace version of the ACE code editor. It's configured to use a 14 point fixed width font and the "xcode" theme; available themes can be viewed at https://manubb.github.io/react-ace-builds/ . Other options have been set to emulate a plain text box: no line numbering, gutter, current line highlighting, or auto completion. The background is set to grey when disabled like our other other text input boxes. However it does not get the focus highlight border our other text boxes do.
=> image coding: use ACE syntax highlighting code editor

.github/workflows/build.yml, CHANGELOG.md, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/templates/layout/chromeless.html.eex, lib/oli_web/views/layout_view.ex
Some Adaptive Pages need to exercise full control over the CSS of the page, and to have nothing else rendered as "application chrome" by Torus.  These types of pages may provide their own page-to-page navigation. 
This PR introduces a top-level page content attribute `displayApplicationChrome`, that if set to `false` will allow the adaptive page to render without any Torus application chrome around it.  This attribute defaults to `true` if not set. 
Another top-level attribute `additionalStylesheets` is a collection of arbitrary style sheet URLs, that if set, will get injected into the `<head>` portion of the rendered page.
=> Chrome free pages

CHANGELOG.md, config/config.exs, config/dev.exs, lib/oli/publishing/authoring_resolver.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli/repo.ex, lib/oli/utils/database.ex, lib/oli/utils/db_seeder.ex, lib/oli/utils/explain.ex, oli.example.env, priv/repo/migrations/20210423011451_add_indices.exs
This PR does two things:
1. It addresses the problem of a large amount of sequential scans being performed on the `published_resources` table by adding some necessary database indexes and by optimizing the queries in `DeliveryResolver` and `AuthoringResolver`.
2. It adds developer-oriented support for flagging as a log warning "problematic queries".   
The problematic query detection impl works by intercepting all queries flowing through `Oli.Repo` via the `prepare_query` override.  If the `:problematic_query_detection` flag is set to `:enabled` (and you are not running in production), the query will first be explained and analyzed using the `"EXPLAIN ANALYZE true (...sql)"` sql. After explained, that JSON structure is traversed to find two different problems: 
1. Steps that involve …
=> [BUG FIX] Add missing database indexes, infra for flagging problematic queries 

priv/repo/migrations/20210506203507_fix_project_status.exs
This PR fixes a problem where the migration from the Delete Package PR did not account for existing project records, whose status fields are now null.  This is breaking project access for those projects since that plug explicitly checks for the value of `:active` in that field.
=> [BUG FIX] set all project statuses to active

CHANGELOG.md, assets/src/components/editing/editor/Editor.tsx
In attempting to reproduce another issue, I discovered an issue that when using Firefox, one is almost unable to do basic focus changes via mouse clicks in Slate editors.  Some quick research turned up a solution in the Slate GH: https://github.com/ianstormtaylor/slate/issues/1984#issuecomment-466992295
This PR applies that workaround. I've interactively tested editing with Firefox, Chrome and Safari and everything this to be working. 
Note, this PR does not address https://github.com/Simon-Initiative/oli-torus/issues/520
=> [BUG FIX] Fix firefox selection, focus problem

CHANGELOG.md, assets/styles/delivery/main.scss, lib/oli_web/templates/page_delivery/_link_assessment.html.eex, lib/oli_web/templates/page_delivery/_link_page.html.eex, lib/oli_web/templates/page_delivery/_outline.html.eex, lib/oli_web/templates/page_delivery/container.html.eex, lib/oli_web/views/page_delivery_view.ex
This PR fixes an issue were empty containers show as pages in overview. This is a non-obvious issue since most containers usually have children, but in the case which they don't, they were being rendered as pages. This PR fixes the issue by properly checking the resource type instead of for children.
Closes #1054
=> fix an issue were empty containers show as pages in overview

CHANGELOG.md, lib/oli_web/live/curriculum/container/container_live.html.leex
This PR fixes an issue where reordering an item to a greater position resulted in incorrect placement one less than desired index. This was because the item being moved was being filtered out before assigning an index. The fix here is to assign item indices before filtering out the item being moved.
=> fix an issue with indices on reorder item

.github/workflows/package.yml, config/releases.exs, config/test.exs
This PR adds a deployment task for the `deploy-loadtest` tag which will trigger a deployment of the tagged ref to loadtest.oli.cmu.edu.
This PR also includes a fix to the `load_testing_mode` config to make it runtime configurable.
=> Deploy loadtest

.github/actions/phoenix-builder/entrypoint.sh, .github/workflows/package.yml
Attempt to restore tokamak deployment.  This PR changes phoenix build in the `entrypoint.sh` and the versions of Elxiir and Erlang used in Docs build step (which is what appears to be failing). 
There are some other whitespace and single quote to double quote changes that VSCode insisted on making.
=> [CHORE] Restore docs build

.github/workflows/build.yml, mix.exs
This PR fixes the `mix test.watch` task. The issue was the preferred_cli_env specified to use the test env, however this task appears to actually run in dev before entering test. The fix is to remove this as well as the ecto.reset command in test. See https://github.com/lpil/mix-test.watch/issues/124 for more details.
As a result, a database reset is no longer automatically executed before tests are run. This shouldn't be an issue unless tests are aborted halfway through leaving an invalid database state, in which case the `MIX_ENV=test mix ecto.reset` command can be used to reset the test database. The [wiki docs have also been updated](https://github.com/Simon-Initiative/oli-torus/wiki/Setup-Dev-Environment) to reflect this change.
With this fix, a developer will be able to use the …
=> fix mix test watch

CHANGELOG.md, assets/src/components/activities/image_coding/Evaluator.ts
This fixes #1096, apparent problem with regex grading on image coding activities, which was due to the print function implementation printing a space at the end of each printed output line. The unexpected invisible space character prevented author from coming up with a working regexp for exact matching across output lines. Also fixes #1098 (a duplicate).
=> image coding: remove extra space at end of printed lines (problem for regexp grading)

CHANGELOG.md, assets/src/components/activities/image_coding/Evaluator.ts, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx
Resolves #1099, enhancement request to disable the submit button on image coding activities before user code is run. 
It is necessary to run the user-written code to generate the output which is checked by the evaluation. Clicking SUBMIT before running will always lead to an incorrect evaluation due to empty output. There is no reason to allow this error.
=> Image coding: disable submit until run

assets/src/components/resource/resourceEditor/ResourceEditor.tsx, lib/oli/interop/ingest.ex, lib/oli/interop/rewire_links.ex, lib/oli/interop/scrub.ex, test/oli/delivery/attempts/scoring_test.exs, test/oli/interop/scrub_test.exs
This PR adds support for cleaning data in course digests prior to ingest to ensure that it is structured properly.   It adds initially support or cleaning/adjusting two things:
1. Ensuring that code blocks only contain `code_line` instances as direct children. For code blocks that specify raw text or paragraphs (or anything else) it converts that to a `code_line`. 
2. Ensures that nodes that should have an `id` attribute get one assigned to it. 
The "scrubbing" support this PR adds can record and track the changes that it makes.  These changes are not yet exposed to the end user.  That will likely happen in future work when we expand ingest support.
=> [BUG FIX] Handle poorly formatted data during ingest

priv/repo/migrations/20210603205146_pow_delivery_user.exs
This PR fixes an issue where the user independent learner index didn't work correctly. The fix is to change this to be a partial unique index, which only applies to records that have `independent_learner = true`
=> make user email unique index a partial index

lib/oli/accounts.ex, lib/oli/utils/db_seeder.ex, lib/oli_web.ex, lib/oli_web/templates/layout/_delivery_header.html.eex, priv/repo/migrations/20210603205146_pow_delivery_user.exs, test/support/test_helpers.ex
This PR fixes the pow delivery users migration by flushing the table changes and setting all existing users independent_learner fields to false. It also hides the "My Courses" link from non-independent learners.
=> Set existing users in migration

lib/oli_web/pow/pow_helpers.ex, lib/oli_web/pow/users_context.ex, test/oli_web/pow/users_context_test.exs
This PR fixes an issue where authenticating with an email that already exists for non-independent user throws an error.
=> [BUG FIX] Override pow get_by to only query independent learner users

.gitignore, CHANGELOG.md, config/config.exs, lib/oli/application.ex, lib/oli_web/endpoint.ex, lib/oli_web/pow/pow_helpers.ex, test/oli_web/pow/pow_test.exs
This PR fixes an issue where checking the "Remember me" checkbox crashed the server for that user. It also introduces the proper configuration in order to persist session across server restarts/deployments per pow production checklist: https://hexdocs.pm/pow/1.0.14/production_checklist.html#content
=> [BUG FIX] fix an issue with persistent sessions config

lib/oli_web/live/breadcrumb/breadcrumb_trail_live.ex, lib/oli_web/live/common/manual_modal.ex, lib/oli_web/live/common/modal.ex, lib/oli_web/live/curriculum/container/container_live.html.leex, lib/oli_web/live/curriculum/entries/entry.ex, lib/oli_web/live/curriculum/entries/move_modal.ex, lib/oli_web/live/grades/grades.ex, lib/oli_web/live/history/pagination.ex, lib/oli_web/live/history/revision_history.ex, lib/oli_web/live/insights/insights.ex, lib/oli_web/live/objectives/objective_entry.ex, lib/oli_web/live/objectives/objective_render.ex, lib/oli_web/live/projects/cards.ex, lib/oli_web/live/projects/projects_live.ex, lib/oli_web/live/qa/qa_live.ex
I noticed that modals are broken on the curriculum view, and after looking further it seems as thought live_component no longer takes @socket argument as of LiveView 0.15.6.
This PR removes @socket from all live_components and fixes the issues in curriculum view
=> [BUG FIX] remove @socket from all live components as of phoenix 0.15.6

CHANGELOG.md, assets/src/phoenix/package_delete.ts, lib/oli_web/templates/project/overview.html.eex
Closes #1131 
There was a collection of encoding/decoding issues, both in the server code and client, preventing this from working.  The most robust way to allow it to work is to have both input and title strings be base 64 encoded - from the server rendering through to the comparison in TS code.
=> [BUG FIX] Allow course project deletion when title contains special characters

lib/oli_web/pow/pow_helpers.ex
This PR removes Github as a social login provider for independent learners (users).
=> [BUG FIX] remove github social login provider

lib/oli_web/router.ex
This PR add the reauthorization plug handler which according to the documentation https://github.com/pow-auth/pow_assent#powpersistentsession, this allows identity providers to mange persistent sessions for social login users.
=> [BUG FIX] enable reauthorization plug handler for social login persistent sessions

CHANGELOG.md, lib/oli/interop/export.ex, lib/oli/interop/ingest.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/project/overview.html.eex, priv/repo/seeds.exs, test/oli/interop/ingest_test.exs
Closes #904 
Closes #1123 
This PR introduces course project export.  It is effectively the inverse operation of ingestion.  Course project export takes the current unpublished content and creates a downloadable .zip file containing a course digest.
=> [FEATURE] Course project export

assets/src/apps/authoring/store/page/actions/initializeFromContext.ts, assets/src/apps/authoring/types.ts, assets/src/components/resource/resourceEditor/ResourceEditor.tsx, lib/oli/authoring/editing/page_context.ex, lib/oli/authoring/editing/page_editor.ex
Recent changes to master broke all activity editing from within a "basic page".  The cause was the removal of the `resourceId` property of the `ResourceContext` in favor of `resource_id`.  This PR restores that attribute, and allows it to be used where `resource_id` was expected.
=> Restore ability to edit activities

lib/oli/application.ex
This PR fixes the issue `[error] Error when processing submit_activity "Cannot find module 'rules'` by reading the nodejs rules module from oli priv dir.
Tested on tokamak, verified it fixes the issue.
=> [BUG FIX] Read rules module from oli priv dir

CHANGELOG.md, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/image_coding/sections/ImageCodeEditor.tsx
Image coding activities were incorrectly initializing with starter code on every page reload, so were not persisting student edits. This fixes to restore prior edits in an image coding activity so contents persist across page reloads.
This could motivate a need to add some way to discard students' edits and reload the starter code, in order to start afresh from the instructor-written paradigm. In the original KTH course that function was provided by a button labelled "reset", but in Torus the "reset" button does something different.
Fixes #1191
=> [BUG FIX] make image coding edits persist 

assets/package.json, assets/src/actions/media.ts, assets/src/components/messages/Message.tsx, assets/src/components/parts/janus-multi-line-text/MultiLineTextInput.tsx, assets/src/components/parts/janus-popup/Popup.tsx, assets/src/components/parts/janus-slider/Slider.tsx, assets/yarn.lock
builds on #1249 
replaces `any` with a specific type, and addresses warning/errors that arise.
increases coverage from 84.68%. with 47215 of 55753 identifiers covered, to 84.78%  with 47273 of 55755 identifiers covered.
=> chore: increase type coverage

CHANGELOG.md, assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx, assets/src/components/activities/common/delivery/gradedPoints/GradedPointsConnected.tsx, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/ordering/OrderingDelivery.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/data/content/activities/DeliveryState.ts, assets/src/data/content/activities/activityUtils.ts, assets/src/data/content/activities/utils.ts, assets/test/activities/redux_delivery_test.ts, assets/test/check_all_that_apply/cata_delivery_test.tsx
Short answer and ordering activities did not correctly restore their state when students typed in inputs or re-arrange choices and refresh the page. Ordering activities were not calling `onSaveActivity` after reordering, and there was a type error in Short Answer activities because the input is marked as `any` and was not being stored in an array when restored from persistence.
To test:
- Publish open and free course with short answer / ordering questions
- Preview in O&F mode
- Enter an input for a short answer and rearrange choices options for ordering
- Refresh page and ensure the submissions restore
=> [BUG FIX] Fix restoring "in progress" activity state from persistence

.github/actions/phoenix-builder/entrypoint.sh, lib/oli/release.ex
This PR fixes an issue where lti app configs were not loaded in release tasks that require them. It also set the mix env to prod for digest command.
=> [BUG FIX] fix an issue where lti app configs were not loaded in release tasks

assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx
-- making changes only in props.init call and that will resolve the issue.
-- I thought of changing the value to -1 in below line of code but It seems that Curtis changed that from -1 to 0 in Janus so there must be a reason behind that hence not touching that code.
`const [selectedChoice, setSelectedChoice] = useState<number>(0);`
=> [Bug]PMP-1645

lib/oli/delivery/snapshots/worker.ex
Fixes an issue where snapshot worker was failing due to missing timestamps.
=> [BUGFIX] fix an issue where snapshot worker was failing due to missing timestamps

CHANGELOG.md, lib/oli/delivery/snapshots/worker.ex, mix.exs
Fix an issue with timestamps in snapshots by truncating datetime microseconds
=> [BUGFIX] truncate datetime microseconds

.github/workflows/build.yml, config/config.exs, config/dev.exs, config/prod.exs, config/releases.exs, config/test.exs, oli.example.env
This PR allows an S3 bucket to be configured independently on development/production systems at runtime and removes the values which were hard coded.
In turn, it requires the following configs to be added to `oli.env` for a development environment to continue working:
```
S3_MEDIA_BUCKET_NAME="torus-media"
MEDIA_URL="your_s3_media_bucket_url.s3.amazonaws.com"
```
Of course, these values must correlate with the S3 bucket used for development.
=> [CHORE] Make S3 bucket runtime configurable

assets/src/adaptivity/operators/equality.ts, assets/test/adaptivity/rules_engine_test.ts
-- by mistake I replace 'value' with 'factvalue' in the parsing method which caused this issue
=> [BUG] MCQs not functioning when "array" is used

CHANGELOG.md, assets/src/components/resource/resourceEditor/ResourceEditor.tsx, assets/src/components/resource/resourceEditor/listeners.ts
This PR fixes an issue where pressing the mod key (Ctrl or Cmd) unselects the currently selected text. The issue appears to be related to a component state update where metaModifier state was causing a rerender which would reset the selection state. Since metaModifier state is no longer used anywhere, I simply removed it which fixes the issue.
Closes #1347
=> [BUG FIX] fix an issue where mod key changes selection

CHANGELOG.md, lib/oli/accounts/schemas/user.ex, priv/repo/migrations/20210804173741_generate_sub.exs
This fixes an issue/inconsistency where users who create accounts using a social login provider have null values for subs.
=> [BUG FIX] fix an issue where users with social logins have null subs

lib/oli_web/controllers/collaborator_controller.ex, lib/oli_web/templates/project/_collaborator.html.eex, lib/oli_web/templates/project/overview.html.eex, test/oli/part_components_test.exs, test/oli_web/controllers/collaborator_controller_test.exs
This PR adds the ability to specify multiple collaborator invites at once separated by comma. It also remove a rogue IO.inspect call, fixes some test warnings.
=> [ENHANCEMENT] allow multiple comma separated collaborators

CHANGELOG.md, lib/oli_web/live/grades/grades.ex
This PR fixes an issue where the "Update Line Items" action was failing. The issue was a section was being passed to the `fetch_graded_pages` function, but it needed a section slug.
=> [BUG FIX] fix an issue with update line items

assets/styles/authoring/main.scss, assets/styles/delivery/main.scss, lib/oli/accounts.ex, lib/oli/accounts/schemas/author.ex, lib/oli/accounts/schemas/user.ex, lib/oli_web/controllers/pow.ex, lib/oli_web/live/common/table/sortable_table.ex, lib/oli_web/live/users/accounts_live.ex, lib/oli_web/plugs/ensure_user_not_locked_plug.ex, lib/oli_web/pow/author_context.ex, lib/oli_web/pow/pow_helpers.ex, lib/oli_web/pow/user_context.ex, lib/oli_web/router.ex, lib/oli_web/templates/email/_header.html.eex, lib/oli_web/templates/layout/_delivery_header.html.eex, lib/oli_web/templates/layout/_header.html.eex, lib/oli_web/templates/project/_collaborator.html.eex, lib/oli_web/templates/project/publish.html.eex, priv/repo/migrations/20210809142945_lock_users.exs, test/oli_web/live/users/accounts_live_test.exs, test/oli_web/pow/users_context_test.exs
Adds some more advanced functionality to managing authors and users as an admin including the ability to resend email confirmation, manually confirm email, send a reset password link, lock/unlock an account as well as show some other important information such as whether or not an author/user has verified their email, whether a user is an independent learner, LTI user and what admin account they have linked.
Also includes a fix to filter out guest accounts from the Users view and fixes the logo sent in emails.
=> [ENHANCEMENT] Manage users

lib/oli_web/views/layout_view.ex
if the editor writes null or some other non string value into the additional stylesheets somehow it will crash the server during URI encoding. while the authoring tool should prevent this, I think it's better to skip these values rather than allow it to crash and give the "Internal Server Error" message :)
=> prevent server error from invalid strings in stylesheets

CHANGELOG.md, lib/oli/authoring/editing/activity_editor.ex, lib/oli_web/controllers/api/activity_controller.ex, lib/oli_web/router.ex, test/oli_web/controllers/activity_controller_test.exs
Closes #1424 
This PR adds an endpoint to allow a client to pass many activity documents to be edited at once. The body of the PUT operation must contain a top-level `"updates"` key whose value is an array of document attribute objects representing the change to make. Each of these objects must contain a `"resource_id"` key to allow the server to know which activity, by resource id, is to be edited.
=> [FEATURE] Allow bulk activity editing

CHANGELOG.md, assets/src/apps/authoring/Authoring.tsx, assets/styles/authoring/advanced-authoring.scss, config/releases.exs, lib/oli/rendering/activity.ex, lib/oli/rendering/activity/html.ex, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/page.ex, lib/oli/utils.ex, lib/oli_web/controllers/collaborator_controller.ex, lib/oli_web/templates/project/overview.html.eex, test/oli_web/controllers/collaborator_controller_test.exs
This PR introduces a limit to the amount of comma-separated collaborator emails that can be sent at a time. This is a security measure to limit the capability of blasting unlimited emails from the system without reverifying the captcha.
Also includes some richer logging of errors for collaborator invitations.
=> limit the amount of author invite emails at a time to 20

CHANGELOG.md, lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli_web/controllers/page_delivery_controller.ex
Closes #1425 
This PR allows graded pages to be submitted without the student having answered all questions.   
The change to allow this was fairly straightforward: There was an explicit check in the activity lifecycle evaluation logic that would fail submission if a single part of any activity had no state available (aka, was `nil`).  I removed this and made the eval's handling of `nil` states robust.
=> [FEATURE] Allow for finalization without answering all questions or parts

CHANGELOG.md, lib/oli_web/live/grades/grades.ex
This PR fixes a confusing link to the LMS gradebook inferred by the registration iss, which in practice is usually a generic url to canvas.instructure.com. Given the information from the registration, it is difficult to actually determine what this link URL should be without explicitly asking for it upon registration. Therefore, the easiest fix here is to simply remove it since it wasnt providing any real value and it was confusing some instructors.
Closes #1414
=> [BUG FIX] remove incorrect gradebook link from manage grades page

CHANGELOG.md, lib/oli/delivery/activity_provider.ex, test/oli/delivery/activity_provider_test.exs
This PR fixes an issue introduced by the new `ActivityProvider` implementation, namely that deeply nested activity references within adaptive page content were no longer being realized. The core issue was that the new impl only looks at the top-level `model` list.  A singular implementation was going to be fairly complex (due to content transformation requirements from bank selections), so instead I pattern matched and just do a `flat_filter` to find all activity references in the adaptive page case.
=> [BUG FIX] Provide specific impl to realize activities from adaptive page content

lib/oli/publishing.ex, priv/repo/migrations/20210823212647_advanced_section_creation.exs
This PR fixes the issue of deleted activity resolution in the event that a deleted activity needs to be resolved in delivery by creating the section resource record for deleted records as well.
There are two places that need to be changed. First is the function used by the section creation logic `get_published_resources_by_publication`. This function is only used by section creation logic so this change shouldn't affect other functions. Second is the migration logic that transforms all existing sections into a collection of section resources.
=> [BUG FIX] fix the resolution of deleted activities

assets/src/utils/common.ts, assets/test/utils/common_test.ts
-- Number.isNaN(parseFloat(item)) was causing trouble in parsing '56.5/-13/7'. It was returning '-56.5' instead 'NaN'.
=> [BUG] PMP-1741 | JAN-563

CHANGELOG.md, lib/oli_web/controllers/page_delivery_controller.ex
This PR fixes delivery to allow for graded adaptive pages to render the prologue page properly. 
The failure here was simply an overly aggressive pattern match that prevented the prologue case from hitting for both adaptive and basic pages.
=> [BUG FIX] Allow graded adaptive pages to render prologue

CHANGELOG.md, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/evaluation/evaluator.ex, lib/oli_web/templates/page_delivery/page.html.eex, lib/oli_web/templates/page_delivery/prologue.html.eex, lib/oli_web/views/page_delivery_view.ex
This PR fixes a couple of problems around use of Image Coding in graded contexts. 
1. It enables the "Submit" button for the activity even when graded.  This is the only way that a student can actually answer the question, given that it is a client-side evaluated activity. 
2. The PR adjusts evaluation logic to ensure that even unanswered questions will be counted as "0 out of 1" in evaluation and subsequent roll-up.  
3. It makes some page rendering logic robust against any existing or future cases where invalid values exist as the "out of" for a resource attempt, specifically any value less than or equal to 0
=> [BUG FIX] Allow use of image coding in graded pages

assets/src/apps/app.tsx, assets/src/apps/delivery/Delivery.tsx, assets/src/apps/delivery/store/features/page/slice.ts, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/controllers/resource_controller.ex, lib/oli_web/templates/page_delivery/advanced_delivery.html.eex, lib/oli_web/templates/resource/advanced.html.eex, lib/oli_web/templates/resource/advanced_page_preview.html.eex
this is mostly needed so that delivery can tell whether to send to the finalization page or overview page at the end of the lesson
=> expose graded flag so that authoring and delivery can use when necessary

CHANGELOG.md, lib/oli/accounts.ex, lib/oli_web/live/delivery/manage_section.ex, test/oli/accounts_test.exs
This PR fixes an issue where a user's platform role were failing to update on LTI launch
=> [BUG FIX] Fix update platform roles

CHANGELOG.md, lib/oli_web/live/projects/table.ex, mix.exs, test/oli_web/live/projects_live_test.exs
Fixes an issue where no collaborators for a project crashes the projects view. Updates the change log and version number for the hot fix.
=> [BUG FIX] Fix an issue where no collaborators for a project crashes the project view

CHANGELOG.md, assets/src/apps/bank/ActivityBank.tsx, assets/src/apps/page-editor/PageEditor.tsx, assets/src/components/activities/common/utils.tsx, assets/src/components/activities/multi_input/MultiInputAuthoring.tsx, assets/src/components/activities/multi_input/actions.ts, assets/src/components/activities/multi_input/utils.tsx, assets/src/components/activity/InlineActivityEditor.tsx, assets/src/components/editing/models/inputref/Editor.tsx, assets/src/data/activities/model/rules.ts, assets/src/data/content/bank.ts, assets/src/data/content/model.ts, assets/src/data/content/utils.tsx, assets/src/data/content/writers/writer.tsx
Add model validation for multi input activities in `PageEditor` and `ActivityBank`. This should prevent an invalid model (missing/extra `InputRef`s, `Input`s, `Part`s) from saving. I tested this by triggering the issue Darren noticed where adding multiple inputs to an activity, selecting all, deleting, and then undoing with `cmd+z` could trigger missing input refs.
Closes #1532
=> [ENHANCEMENT] Add multi input model validation

.github/workflows/build.yml, CHANGELOG.md, lib/oli_web/common/links.ex
This PR fixes an issue where generating resource links for tags throws a server error. It now handles tags and guards against unknown types.
=> [BUGFIX] Fix tag resource links

lib/oli_web/live/common/modal.ex, lib/oli_web/live/users/accounts_live.ex, lib/oli_web/views/layout_view.ex
This PR fixes an admin facing issue where modals on the accounts page unexpectedly disappear due to phoenix re-rendering. It also addresses another issue where some names aren't displayed correctly because certain login providers only provide the name (instead of first and last name). Logic in our schemas will generate a full name based on first and last in none is provided but has no good way to go the other way. For this reason, we should use the name field in the interface since it is the only one guaranteed to be present.
=> [BUG FIX] fix an issue with modals on accounts page

CHANGELOG.md, assets/src/components/logic/ActivityTypeSelection.tsx, assets/src/components/logic/Expression.tsx, assets/src/components/resource/Objectives.tsx, assets/src/components/resource/Tags.tsx, assets/src/components/resource/editors/Editors.tsx, assets/src/components/resource/editors/editor_error_boundary.tsx, lib/oli_web/live/objectives/actions.ex, mix.exs, test/oli_web/live/objectives_test.exs
This PR fixes an issue related to changing fact types in an activity selection where the old value remained in place breaking the page. It fixes the issue by resetting value to an empty list on fact change. It also introduces a react error boundary to prevent the entire page from breaking.
This PR also disables objective deletion and is expected to be followed up with a fix to #1616.
=> [BUGFIX] Fix selection changing types

CHANGELOG.md, lib/oli/analytics/common.ex, lib/oli/interop/export.ex, lib/oli/utils.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/live/insights/insights.ex, lib/oli_web/live/insights/table_row.ex, lib/oli_web/router.ex, lib/oli_web/templates/project/insights.html.eex
This PR pulls forward the raw data analytics download feature, but fixes a few things along the way:
1. Snapshot records with no objectives attached were not included. The fix here is to use a left_join on Objectives.
2. The pretty printing of JSON was breaking the file by introducing spurious newlines.  
3. More fields were added, ids of the part attempt, activity, page and objective, as well as the entire content of the activity
I'm going to file a follow on bug to fix the impl of the formatting in lines 199-206 of the `Insights` LV.  This repeated use of `Enum.at` and `List.replace_at` on every row is not the most effecient way of doing this and could lead to performance problems as the data sets get larger and larger.  This can be replaced with an approach that does two passes over …
=> [FEATURE] pull forward download impl, fix formatting and other issues

config/config.exs, config/releases.exs, lib/oli_web/controllers/payment_controller.ex, lib/oli_web/controllers/payment_providers/no_provider_controller.ex, lib/oli_web/templates/payment/guard.html.eex, lib/oli_web/templates/payment_providers/no_provider/index.html.eex, lib/oli_web/views/payment_providers/no_provider_view.ex
This PR adjusts how the system allows configuration of the payment provider.  Previously, a recompile was necessary to change providers. This PR allows the `PAYMENT_PROVIDER` env variable to determine the payment provider.  The valid values are `"stripe"` or `"none"`.  The default is `"stripe"` and any other value besides stripe or none defaults to `"none"`.  
When the payment provider is set to `"none"`, no link to initiate a direct payment is shown, only a link to redeem a payment code.
=> [FEATURE] allow for env var driven provider changes

assets/src/apps/authoring/Authoring.tsx, assets/src/apps/authoring/store/activities/actions/saveActivity.ts, assets/src/apps/authoring/store/app/slice.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityPartInheritance.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts, assets/src/apps/authoring/store/page/actions/savePage.ts
* PMP-1635: Add lock status flag to app
* PMP-1636: Ensure that all saving mechanisms use the lock
* PMP-1809: Release lock
You'll need access to two separate local accounts, opened in two separate windows and logged in at the same time (one regular, one incognito). In both windows, navigate to the "Curriculum" view of a project that contains an adaptive page. Click on "Edit" in the regular window to load Advanced Authoring, then switch to the incognito window and wait for a locked message to appear next to the "Edit" button. 
Next, click "Edit" in the incognito window and verify you see the "Editing in Progress" message and not the Advanced Authoring tool itself.
If you don't want to wait the full 10 minutes that the server is set to release the lock, you can modify the `@ttl` value on …
=> [FEATURE] [PMP-860 / JAN-327]: Match Locking and Saving Lessons in Adv Authoring Tool to Torus Behaviors

assets/src/apps/authoring/components/AdaptivityEditor/ConditionsBlockEditor.tsx, assets/src/components/parts/janus-capi-iframe/schema.ts
Fixes an issue where a bad CAPI sim type value was crashing the variable picker.
=> [BUGFIX][PMP-1924 / JAN-736] Support the Ability to pick the Variables for a CAPI Sim that is on a Layer

lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli/delivery/hierarchy.ex, lib/oli/delivery/paywall.ex, lib/oli/grading.ex, lib/oli/qa/reviewers/pedagogy.ex, lib/oli_web/controllers/open_and_free_controller.ex
Removes inspect statements, replacing them with Logger where needed. This is not only best practice and enables these to be better analyzed when we have a better logging solution in place, but also allows these conditions to be caught in unit tests.
=> [CHORE] replace inspect statements with logger

assets/src/components/parts/janus-text-flow/Markup.tsx
setting lineHeight 0px for the <P> tags with children. This is so far resolving the issue with not impacting P tags rendering.
=> [JAN-151 | PMP-1308] - space between text and sim

CHANGELOG.md, lib/oli_web/live/delivery/remix_section.ex, lib/oli_web/live/sections/mount.ex, mix.exs
This core issue here was that `breadcrumbs` was not set within a particular mount sublogic, which resulted in a failure of a static template render that expected it to be there: 
Nov  1 18:47:41 proton oli: ** (exit) an exception was raised:
Nov  1 18:47:41 proton oli: ** (ArgumentError) errors were found at the given arguments:
Nov  1 18:47:41 proton oli: * 1st argument: not a list
Nov  1 18:47:41 proton oli: :erlang.length(nil)
Nov  1 18:47:41 proton oli: (oli 0.14.2) lib/oli_web/templates/layout/_account_header.html.eex:1: OliWeb.LayoutView."_account_header.html"/1
Nov  1 18:47:41 proton oli: (oli 0.14.2) lib/oli_web/templates/layout/workspace.html.eex:10: OliWeb.LayoutView."workspace.html"/1
=> [BUGFIX] fix product remix access by supplying breadcrumb attribute for LV

assets/src/components/activities/DeliveryElement.tsx, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx, assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx, assets/src/components/parts/janus-popup/Popup.tsx, assets/src/components/parts/janus-popup/PopupAuthor.tsx, assets/src/components/parts/janus-popup/PopupWindow.tsx, assets/src/components/parts/janus-popup/delivery-entry.ts, assets/src/components/parts/janus-popup/types.ts
enable popup to render its window within the context of the activity;
having both the window and icon live within the bounds of the same web component proved to be problematic.
these changes send a reference to the container element that the activity renders its contents into all the way down to the part level. this allows a part to render secondary content (popup's window) within the confines of the activity along side of other parts. this way the window and the icon can have different z indexes and positions.
=> [BUGFIX] popup window

CHANGELOG.md, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/section.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/controllers/delivery_controller.ex, priv/repo/migrations/20211102141706_ensure_unique_active_section.exs, test/oli/accounts/user_browse_test.exs, test/oli/delivery/paywall/providers/stripe_test.exs, test/oli/delivery/paywall_test.exs, test/oli/delivery/sections/blueprint_test.exs, test/oli/delivery/sections/browse_test.exs, test/oli/delivery/sections/enrollments_browse_test.exs, test/oli/resources/numbering_test.exs, test/oli/sections_test.exs
This PR fixes an issue that allows multiple active sections to be simultaneously created with the same context id. It also adds a database unique constraint on the `context_id and status = 'active'` so that future sections cannot get caught in this state. Adding this constraint required updating some unit tests.
Closes #1790
=> [BUG FIX] wrap create section in db transaction

lib/oli_web/live/delivery/remix_section.ex
Closes #1809 
AppSignal details show the following for params:
```
{
"section_slug": "eli_test_course"
}
```
And the following for session:
```
{
"_csrf_token": "LHlW0uMmuUJeHm2MrP7GdXEm",
"author_auth": "SFMyNTY.OWQwOTYyNWMtNWU3YS00YzU1LWJkM2EtZTUzMDczYzY2ODk4.POLFJIgJki2w9PYYm3h3zIIpPBm79zLlLda0YBCytfQ",
"csrf_token": "BnAmE2lYISszHX0TCkAKdV88YwtcLDUeJ8JDY-lFFH7vB-88-lTL8tps",
"current_author_id": 31,
"section_slug": "eli_test_course"
}
```
The issue here appears that only an author id is present in session, and not a user id.  The fix adds another impl for `mount_as_instructor` that targets admin authors.   
I checked all other views that utilize `Mount.for` and none of them have any similar issues (they all handle mount logic in a more general, robust way)
=> [BUGFIX] Fix mount logic for remix

CHANGELOG.md, lib/oli_web/views/layout_view.ex, mix.exs
This handles a problem where the logic to extract initials for the authoring account name fails.  The problem I believe is the handling of both the empty string, and names where there is no space between the first and last name.
=> [BUGFIX] Determine authors initials in more robust manner

CHANGELOG.md, assets/src/data/content/writers/html.tsx, assets/test/writer/writer_test.ts
Closes #1825 
This PR removes the escaping of HTML special characters ( ' " & < > ) which was resulting in them rendering incorrectly. I'm not sure how this ended up getting broken, by my suspicion is that at some point this escaping was necessary given how we *used* to end up rendering the HTML around the raw text.  Given that we now are leveraging React to do this rendering around the text this escaping is simply not needed. 
To test this out, within a page editor create an activity.  Within that activity, place these special characters in the stem, hints, feedback and choices.  Create some code blocks and popups and place them there as well.  With this fix in place, the render correctly in all cases.
=> [BUGFIX] Fix HTML special character client-side rendering

assets/src/apps/authoring/components/AdaptivityEditor/VariablePicker.tsx
Adds the ability to select only `currentQuestionScore` and `tutorialScore` from the variable picker in a mutate action.
=> [PMP-2039 / JAN-835] [DEFECT]: Can't Mutate Session Variable from the Variable Picker

CHANGELOG.md, assets/src/components/activities/DeliveryElement.tsx, assets/src/components/activities/common/delivery/evaluation/EvaluationConnected.tsx, assets/src/components/activities/common/delivery/graded_points/GradedPointsConnected.tsx, assets/src/components/activities/types.ts, assets/styles/delivery/page_delivery/page.scss, assets/test/utils/activity_mocks.ts, lib/oli/authoring/editing/page_editor.ex, lib/oli/delivery/page/activity_context.ex, lib/oli/delivery/sections.ex, lib/oli/rendering/activity/activity_summary.ex, lib/oli/rendering/activity/html.ex, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/content/plaintext.ex, lib/oli/rendering/content/selection.ex, lib/oli/rendering/context.ex, lib/oli/rendering/page.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/templates/layout/page.html.eex, lib/oli_web/templates/page_delivery/_link_assessment.html.eex, lib/oli_web/templates/page_delivery/_link_page.html.eex, lib/oli_web/templates/page_delivery/_outline.html.eex, lib/oli_web/templates/page_delivery/_previous_next_nav.html.eex, lib/oli_web/templates/page_delivery/index.html.eex, lib/oli_web/templates/page_delivery/instructor_preview.html.eex, lib/oli_web/views/page_delivery_view.ex
Closes #1818 
Closes #1819 
This PR implements PR1 and PR2 from https://docs.google.com/document/d/1-zG0RBoZETN2jYUtfPRwRamzopATrEhu9YaVl-xFEls/edit#heading=h.armgq2vqmkmg.   Once I dug into it, it didn't make sense to split this work into two distinct PRs. 
1. Eliminates separate boolean flags for "review" "preview" modes for the `DeliveryElement` webcomponent in favor of a singular `mode` attribute that can take values as defined in `DeliveryMode` ("preview", "review", "delivery"). 
2. Creates a singular "mode" attribute on the server-side HTML rendering framework which can take values [:delivery, :review, :author_preview, :instructor_preview]
2. Changes the HTML activity render to render the Authoring component of an activity when the rendering mode is "instructor_preview". 
3. …
=> [FEATURE] Instructor "Preview" mode

lib/oli/delivery/sections.ex, lib/oli/rendering/content/html.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, lib/oli_web/templates/layout/page.html.eex, lib/oli_web/templates/page_delivery/_link_assessment.html.eex, lib/oli_web/templates/page_delivery/_link_page.html.eex, lib/oli_web/templates/page_delivery/_outline.html.eex, lib/oli_web/templates/page_delivery/container.html.eex, lib/oli_web/templates/page_delivery/index.html.eex, lib/oli_web/views/page_delivery_view.ex
This PR introduces are more explicit routing approach for instructor preview mode, one that allows a specific scope to be in place for the overview and page rendering routes that bypasses gating, paywall, and auto-enrollment for open and free.
=> [BUGFIX] Fix preview

assets/src/components/parts/janus-Carousel/Carousel.tsx
Carousel `CurrentImage` now responds to initState and mutateState.
=> [Bugfix] [PMP-2063 / JAN-855] Carousel CurrentImage InitState + MutateState Fix

assets/src/components/parts/janus-popup/PopupWindow.tsx
Hides the popup window X icon from screen-readers, based on 11/15 CSS theme check in discussions.
=> [BUGFIX/NOJIRA] Hide popup window "X" from screen readers

lib/oli/authoring/editing/page_editor.ex, lib/oli/delivery/hierarchy.ex, lib/oli/delivery/page/page_context.ex, lib/oli/delivery/previous_next_index.ex, lib/oli/delivery/sections/section.ex, lib/oli/delivery/student/summary.ex, lib/oli/delivery/updates/worker.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/delivery/remix_section.ex, lib/oli_web/templates/layout/page.html.eex, lib/oli_web/templates/page_delivery/_previous_next_nav.html.eex, lib/oli_web/templates/page_delivery/index.html.eex, lib/oli_web/templates/resource/_preview_previous_next_nav.html.eex, lib/oli_web/views/page_delivery_view.ex, priv/repo/migrations/20211111003243_add_section_link_map.exs, test/oli/delivery/hierarchy_test.exs, test/oli/delivery/page/page_context_test.exs, test/oli/delivery/previous_next_index_test.exs
Closes #1837
During the instructor preview work, it was remembered/discovered that the implementation of the determination of the "Previous" and "Next" pages in delivery was a potentially expensive operation.  This calculation was relying on the full delivery hierarchy being queried (returning all revisions of all resources in the section) and then reconstructed, then traversed to determine the preview and next pages. This was happening on every single page access in delivery. 
This PR significantly streamlines this by precalculating the "previous" and "next" pages link information in a new `previous_next_index` field in the `sections` schema.  With the section already being in the `conn.assigns` all that has to be done is at most three (likely constant time, maybe log n) lookups into …
=> [FEATURE] Implement more efficient determination of Previous and Next links 

CHANGELOG.md, priv/repo/migrations/20211116151722_nilify_published_resource_author.exs
Closes #1800 
The issue here was that the foreign key constraint from "published_resources" to authors prevented this hard delete.  This PR adds a migration that updates that constraint to nilify that entry when an authors record is deleted.  
I tested this by:
1. Create a new authoring account, create a project, create a page
2. Go into the page editor, which sets the author reference from that "published_resource" record.
3. Then, in a another browser logged in as admin, delete the user.  Without this PR this step fails, with this PR it succeeds.
=> [BUGFIX] Allow deletion of authors when they have resources locked for editing

assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts, assets/src/apps/authoring/store/page/actions/initializeFromContext.ts
Adds default / custom theme picker to the lesson panel.  Auto-selects the new default theme for new lessons, as well as auto-selects custom theme for lessons with existing theme urls.
=> [Feature] [PMP-2051 / JAN-844] Basic Theme Picker

assets/src/adaptivity/rules-engine.ts, assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/apps/delivery/store/features/groups/actions/deck.ts
PMP-2144 - sessons.visit variable for the page is getting set to 1 as soon as we come on the page which is causing the trapstate to be wrong as the criteria is sessions.visit should be 0.
PMP-1964 - The score was getting calculated for wrong attempts also when the negativescoring is not allowed, so that condition is added.
=> [JAN-947 | PMP-2144]   [JAN-679 | PMP-1964] - Wrong trap states firing

lib/oli/delivery/activity_provider.ex, lib/oli/delivery/activity_provider/result.ex, lib/oli/delivery/attempts/core/activity_attempt.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli_web/controllers/resource_controller.ex, priv/repo/migrations/20211117160940_add_scoreable.exs, test/oli/delivery/activity_provider_test.exs
This PR adds a new aspect to the attempt hierarchy: the ability for activity attempts to be "unscoreable".  An unscoreable activity attempt will not be auto finalized and will not factor into score rollup to the resource attempt.
This exists initially to support the adaptive page and its use of layers and banks activities. 
There is no way, yet, to designate an activity instance in a basic page as "unscoreable".
=> [FEATURE] Non scoreable attempts

CHANGELOG.md, assets/src/components/activities/common/delivery/inputs/DropdownInput.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/data/activities/utils.ts, assets/src/data/content/writers/html.tsx
Closes #1785 
Closes #1876 
This PR fixes two high priority Activity bugs
The bug here ultimately was because upon initial viewing, or after activity reset, the state of a user's "selected" choice for a dropdown part is the empty string.  This empty string gets sent to the server during submission, at which time the server correctly marks this as "wrong" and then returns the catch all feedback.  The UI, however, never displays an empty choice.  The UI is displaying upon first render - as a default - the first choice.  So if a user does not change choices (because why would they change a choice if they think that choice is the correct one?) the empty string is sent, but the user believes they have submitted an answer for the choice that is visible to them.
The easiest fix here is to simply …
=> [BUGFIX] Fix MultiInput and SingleResponse issues

lib/oli_web/templates/layout/workspace.html.eex
This PR makes the logic that varies which header is showing in authoring context more robust against instructor views that do not include a title.
=> [BUGFIX] Avoid requiring title assign to be present

CHANGELOG.md, lib/oli_web/live/grades/grades.ex, lib/oli_web/live/progress/passback.ex, lib/oli_web/live/progress/student_resource_view.ex, mix.exs
This PR adds the ability for an instructor to sync one grade, for one student and page. 
It also fixes an issue with the bulk line item sync. 
This was tested locally in my dev env with our Canvas instance, so i have a high degree of confidence that this all works (unlike the last two PRs)
=> [FEATURE] Manual grade sync for one student, one page

lib/oli/grading.ex
This PR ensures that the error object returned from the grade book call results in a sensible error message that can be displayed to a user.
Closes #1895
=> [BUG FIX] Ensure that grade pass back gets a sensible error message

assets/src/adaptivity/rules-engine.ts, assets/src/adaptivity/scripting.ts, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts, assets/src/apps/delivery/components/TextParser.ts, lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex
first on author initial load will reconcile the activitiesRequiredForEvaluation, it will also update as conditions are edited
on the server when evaluating (open & free), if that list is empty will *not* pull state from all the others
the list might contain *some* references to other activities, it will only pull the needed items
=> [Feature] PMP-2264 JAN-1077 eval optimization

lib/oli/authoring/course.ex, lib/oli/authoring/course/project.ex, lib/oli/delivery/sections/blueprint.ex, lib/oli/delivery/sections/section.ex, lib/oli/groups.ex, lib/oli/groups/community.ex, lib/oli/groups/community_visibility.ex, lib/oli_web/live/community_live/associated/index_view.ex, lib/oli_web/live/community_live/associated/new_view.ex, lib/oli_web/live/community_live/associated/table_model.ex, lib/oli_web/live/community_live/new_view.ex, lib/oli_web/live/community_live/show_view.ex, lib/oli_web/router.ex, lib/oli_web/templates/layout/_community_admin_sidebar.html.eex, priv/repo/migrations/20211115144220_create_communities_visibilities.exs, test/oli/course_test.exs, test/oli/delivery/sections/blueprint_test.exs, test/oli/groups_test.exs, test/oli_web/live/community_live_test.exs, test/support/factory.ex
Story: MER-336
Adds the ability to add and remove associations between communities and projects/products.
- Implements a many_to_many within the join table `communities_visibilities`
- Add an index view for the projects/products associated with the community with an action column to remove any of them
- Add an index view for all the projects/products of the system with an action column to add any of them to the community
- The table model is shared between the two indexes, so it supports communities visibilities that have the project or product loaded, or a mixed list of projects and products
=> [FEATURE] [MER-336] Associate Projects and Products to Community

lib/oli/groups.ex, lib/oli_web/live/community_live/account_invitation.ex, lib/oli_web/live/community_live/members_index_view.ex, lib/oli_web/live/community_live/members_table_model.ex, lib/oli_web/live/community_live/show_view.ex, lib/oli_web/router.ex, test/oli/groups_test.exs, test/oli_web/live/community_live_test.exs, test/support/factory.ex
Story: MER-340
This feature allows system and community admins to add and remove members to a community.
Merged MER-366 which adds a members index for system and community admins to see a list and be able to remove any of them.
=> [FEATURE] [MER-340] Add Community Members

assets/src/components/parts/janus-text-flow/quill-utils.ts
Fixes an issue where lists and justifications are lost due to lost newline elements.
=> Fix lost formatting of Quill text when editing

assets/src/adaptivity/scripting.ts, assets/src/apps/delivery/store/features/groups/actions/deck.ts
`activityState` was stripping off `${activityId}|` ... and the other variable for `${activityId}|session.attemptNumber` was overwriting it in the `localizedSnapshot` so the fix was to mod the filter to only do it for `${activityId}|stage.`.
=> [BUGFIX] [PMP-2238 / JAN-1053] Max Attempts

lib/oli/groups.ex, lib/oli/groups/community.ex, lib/oli_web/common/params.ex, lib/oli_web/live/community_live/account_invitation.ex, lib/oli_web/live/community_live/associated/new_view.ex, lib/oli_web/live/community_live/form.ex, lib/oli_web/live/community_live/new_view.ex, lib/oli_web/live/community_live/show_view.ex, test/oli/groups_test.exs, test/oli_web/live/community_live_test.exs
This PR addresses the following bugs, introduced by #1866 ([MER-312](https://eliterate.atlassian.net/browse/MER-312)):
- [MER-490](https://eliterate.atlassian.net/browse/MER-490) Clear flash messages
- [MER-491](https://eliterate.atlassian.net/browse/MER-491) Fix typo
- [MER-492](https://eliterate.atlassian.net/browse/MER-492) Community admins can delete other community admins
- [MER-494](https://eliterate.atlassian.net/browse/MER-494) Community not created when Name is too long
- [MER-496](https://eliterate.atlassian.net/browse/MER-496) Community not created when Key Contact is too long
- [MER-497](https://eliterate.atlassian.net/browse/MER-497) Can create a community with a duplicate name with surrounding whitespaces.
- [MER-498](https://eliterate.atlassian.net/browse/MER-498) Can only …
=> MER-312 Communities bugfixes

assets/src/apps/authoring/Authoring.tsx
read only mode was not waiting to unlock before trying to create initial data
=> [BUGFIX] edit mode failing on new adaptive pages JAN-1126 PMP-2337

lib/oli/publishing.ex, test/oli/publishing_test.exs, test/oli_web/live/project_visibility_test.exs
Closes #1933 
The root case was that the `Publishing.available_publications` impl was pattern matching in a way that did not allow it to accept `nil` for the author.  
This function has been reworked to both:
1. Accept `nil` for either argument
2. Consolidate logic to a single implementation
=> [BUG FIX] Rework available_publications to be more robust

CHANGELOG.md, assets/src/components/editing/models/link/EditLink.tsx
This PR fixes a bug where when there is only one other page in a course, the link editor does not allow a user to "change" pages, thus preventing them from triggering the edit path in the code. The fix here is to simply set the default to be the first selectable page. 
To test, using a course with only two pages, attempt to create an internal link in one page to the other.
=> [BUG FIX] Allow editing of internal links when only one page exists

lib/oli/analytics/datashop/elements/meta.ex, lib/oli/analytics/datashop/messages/context.ex, lib/oli/analytics/datashop/messages/tool.ex, lib/oli/analytics/datashop/messages/tutor.ex
Datashop only anonymizes the `<user_id>` tag, but the `<session_id>` tag used the student's email, so it has been anonymized with a guid.
=> [BUG FIX] Change session id to be anonymous

assets/src/components/parts/janus-text-flow/TextFlow.tsx
@dtiwarATS FYI this will break PMP-2158 again. it seems like we maybe can *only* assume that opaque white really means transparent white for feedbacks. though, I am a little worried there are some other special reasons hiding... I am trying to think of a better way, maybe we can do a one time conversion of all text when we open the author based on those rules and just remove all the legacy palette code instead .... hmmm
=> [BUGFIX] PMP-2289 text flow should not assume opaque white is transparent

assets/src/components/parts/janus-mcq/McqAuthor.tsx, assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx, assets/src/components/parts/janus-mcq/MultipleChoiceQuestionType.ts
Allows the UI to respect the setting "verticalGap" when the layout is set to "verticalLayout"
=> Added vertical gap when set to vertical layout for MCQ component

CHANGELOG.md, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/templates/project/overview.html.eex
Closes #1959 
This PR simply adds a display of the course project and course section slug, referring to them as "IDs".  This is needed for community admin users to copy into external portal systems.
=> [FEATURE] Display slugs as ids

CHANGELOG.md, lib/oli_web/live/delivery/select_source.ex
There was a bug in `select_source.ex` from the LMS-lite branch when it tried find the current author. The live_view was assuming it was in delivery and looking up the author by `user_id` which was throwing an error when used in an authoring context. This only affected admin users.
=> [BUG FIX] Fix Open and Free section creation when done through the admin panel

lib/oli/accounts.ex, lib/oli_web/live/projects/visibility.ex, test/oli/accounts_test.exs, test/oli_web/live/project_visibility_test.exs
[MER-561](https://eliterate.atlassian.net/browse/MER-561)
This PR fixes the bug that currently suggests all the existing authors matching the email substring from the input.
Instead, we want to only list the emails that match exactly with the input string.
=> [BUGFIX] [MER-561] Return exact email results when setting restricted visibility to a project

CHANGELOG.md, lib/oli_web/controllers/delivery_controller.ex
This PR sets the blueprint_id for a course section created from an LMS.  Without this, deferred payments cannot be made, instructors can disable payment settings, etc.
=> [BUG FIX] Set blueprint reference for LMS course section creation from product

lib/oli_web/live/delivery/select_source.ex, lib/oli_web/router.ex, lib/oli_web/templates/delivery/open_and_free_index.html.eex
Came across a couple things that needed tweaked for lms-lite when making the demo video.
The main change here is moving the delivery "link account" routes outside of the `require_lti_params` scope. If You're linking through an LMS it should still work, but it doesn't require you to have LTI params. This is necessary because instructors creating independent sections may never be launching through LTI but still need to be able to access their authored courses.
=> [bug fix] small lms-lite updates

CHANGELOG.md, lib/oli_web/controllers/institution_controller.ex
Fixes an issue where the deployment_id param from a pending registration form may be an empty string if the deployment_id is nil.
Closes #1992
=> [BUG FIX] fix deployment_id empty string

CHANGELOG.md, assets/src/apps/page-editor/PageEditor.tsx, assets/src/data/persistence/AbstractPersistenceStrategy.ts, assets/src/data/persistence/DeferredPersistenceStrategy.ts, assets/src/data/persistence/PersistenceStrategy.ts
Closes #1340 
This PR adds a call to flush any pending saves when a request has been made to remove an activity from the page.  This allows proper handling of the case where this activity was added just prior - but that addition change hasn't been seen by the server due to still being deferred.  
To test:
1. While editing a page, add an activity and IMMEDIATLEY remove it. 
2. Then go to the Publish page.  Without this change you will see that activity listed as being new.  With this change the activity does not appear.
=> [BUG FIX] Flush changes prior to activity removal

CHANGELOG.md, lib/oli_web/templates/delivery/select_project.html.eex
This PR fixes an issue where selection of the actual checkbox in "Select Source" was cause the change to fire twice, ultimately leaving the item unselected.
=> [BUG FIX] fix select source checkbox

CHANGELOG.md, lib/oli_web/live/sections/edit_view.ex, lib/oli_web/live/sections/paywall_settings.ex
This PR adjusts the logic of when a user can edit the payment settings of a course section, now allowing admin users to always edit, and allowing non-admin users the ability to edit these settings when the product that was used is free.
=> [FEATURE] Adjust logic that guards editing of payment settings

lib/oli/grading.ex, test/oli/grading_test.exs
This PR adjusts the approach for how the "max out of" for an adaptive page is determined.  Instead of counting screens or parts, it was determined that we should be simply reading the "totalScore" key that should be present in the content under the "custom" key. 
This impl is done as robust as possible, to guard against any of these keys not being present, or containing bad (or simply unexpected data).
=> [BUG FIX] Adjust logic for adaptive page max score

CHANGELOG.md, lib/oli_web/live/projects/visibility.ex
Closes #1910 
This PR simply updates the visibility UI to make it more clear that one is specifying authoring emails.  
We cannot rely on an approach where instructor emails are specified, as in most cases Torus won't know about those instructors until those instructors have launched from their LMS.  Since that's when the instructors are going to create the course section, it's too late to be specifying them as users.
=> [BUG FIX] Update visibility ui

assets/src/apps/delivery/components/TextParser.ts
.toFixed() converts the exponential value to 0. so all the exponential values are displayed as 0.
=> [JAN-1089 | PMP-2276] variables are not correctly populating

lib/oli/delivery/attempts/page_lifecycle/graded.ex
This PR changes adaptive page finalization logic to utilize the "totalScore" attribute present in the content of the page as the "out_of" of the recorded score.
=> [FEATURE] Use totalScore during finalization

lib/oli/delivery/sections.ex, lib/oli_web/live/users/user_detail_view.ex, lib/oli_web/templates/delivery/open_and_free_index.html.eex, lib/oli_web/templates/layout/_user_account_dropdown.html.eex, lib/oli_web/templates/open_and_free/new.html.eex, lib/oli_web/views/delivery_view.ex, lib/oli_web/views/layout_view.ex
Two changes:
- Remove second (institution instructor) checkbox from the admin panel when enabling delivery users to create lms-lite/independent sections. This was in place originally as a safety measure to work with some code that checked for the "institution instructor" platform role, but I realized it's not needed.
- Add a link in the delivery account dropdown menu to link an authoring account
No changelog since this is an unreleased feature.
Closes #1999
=> [BUG FIX] Remove extra checkbox for enabling LMS-lite section creation

lib/oli/lti/lti_ags.ex
Allows both a 200 + 201 for acceptable responses around LTI AGS.
=> Allow both 200 & 201 for acceptable responses.

lib/oli_web/templates/layout/_account_header.html.eex
This PR addresses an error that is being reported in AppSignal, where some combination of actions leads a user to a route that triggers:
`** (ArgumentError) assign @title not available in template. `
The error indicates it is from `_account_header.html.eex`.  From the AppSignal log and from looking at the code I am unable to pinpoint what is being rendered that doesn't have a template. So as a fallback, I've made this template robust to when the title is not present.
=> [BUG FIX] Change impl to be robust to when title assign is missing

lib/oli_web/controllers/lti_controller.ex
The `email_verified` attribute is from an IMS proctoring LTI extension and will never be reliably received - if ever at all.
When we QA, there is often fictions or non-valid emails however in production the LMS/SIS have typically verified emails or their source, so it's appropriate to trust that they are already verified for LMS integrations.
=> Trust LMS/SIS have verified email prior to Torus.

config/config.exs, config/releases.exs, oli.example.env
[MER-624](https://eliterate.atlassian.net/browse/MER-624)
Make Help Provider a configurable and dynamic env variable.
Ensure `HELP_PROVIDER` env variable is added to each Torus instance with the corresponding value:
- `HELP_PROVIDER=FreshdeskHelp` or `HELP_PROVIDER=EmailHelp` depending on the case.
=> [MER-624] Make help provider a configurable env variable

lib/oli_web/templates/email/_header.html.eex
https://eliterate.atlassian.net/browse/MER-631
Works for relative paths (default) and for absolute paths (as configured in QA env)
=> [BUGFIX] [MER-631] Remove static_url for email header logo src

assets/src/components/cookies/CookieConsent.tsx, assets/src/components/cookies/CookiePreferences.tsx, assets/src/components/cookies/utils.ts, config/config.exs, config/releases.exs, lib/oli_web/templates/layout/_delivery_footer.html.eex, lib/oli_web/templates/layout/_footer.html.eex, oli.example.env
[MER-555](https://eliterate.atlassian.net/browse/MER-555)
Make "Privacy Notice" link a configurable and dynamic env variable.
Ensure `PRIVACY_POLICIES_URL` env variable is added to each Torus instance with the corresponding value:
- `PRIVACY_POLICIES_URL={INSERT A COMPLETE URL HERE}`.
It is important that the url must include the protocol (`https://www.example.com` instead of `www.example.com`) in order to work.
=> [MER-555] Make privacy policies url an env var

lib/oli/delivery/paywall/providers/stripe.ex, test/oli/delivery/paywall/providers/stripe_test.exs
If Torus has an email for the user, it should be passed along to stripe since they will not get a receipt otherwise. As a user with an unverified email this feels bad since I am paying with money.
_Note: Rather than checking for verified emails here - it would be better to not let them end up here without a verified email if we feel that is important. Could be worth discussing and opening alternate ticket if needed._
=> MER-613 If a users email exists, pass to stripe when creating intent.

assets/src/apps/delivery/layouts/deck/LessonFinishedDialog.tsx
MER-666: redirect to the `/overview` page after finishing an ungraded lesson.
=> [BUGFIX] [MER-666] Redirect to Overview page

assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx
Wrong Feedback Messages were displayed as the mcq.numberOfSelectedChoices variable was being set with the wrong value.
=> PMP-2411, PMP-2412, PMP-2414

CHANGELOG.md, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, mix.exs
Performance testing (and perhaps real world usage) shows dramatically long page loads.  Investigation yields the culprit to be the logic that creates the activity and part attempt hierarchy (done one time, upon first page visit).  These inserts were being done in serial, so a large adaptive page with say 100 activities (screens) with 3 parts each would require 300 insertion queries, executed serially and incurring the DB latency requests in aggregate.  
The solution in this PR is to rework this logic to use a constant number of bulk insertion queries.
This should fix MER-683 as well.
=> [BUG FIX] Use bulk insertion queries for attempt hierarchy creation MER-684

config/config.exs, oli.example.env
I was slightly unsure whether this should use the packages custom system option as well, but looking at packages example - doesn't seem instance role applies to region (which makes sense).
https://github.com/ex-aws/ex_aws/blob/main/config/dev.exs
=> Add AWS region as env_variable, but defaults to us-east-1

lib/oli_web/controllers/lti_controller.ex, lib/oli_web/templates/project/_lti_connect_instructions.html.eex
This PR allows a user (canvas admin during LTI integration step) to select whether they wish for torus to be displayed in course navigation by default or not. The option defaults to unchecked, which means torus will *NOT* be disabled by default unless a user explicitly checks the box.
Closes #1444
=> [FEATURE] allow course navigation placement to be disabled by default

lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/page_lifecycle/attempt_state.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli/delivery/attempts/page_lifecycle/ungraded.ex, lib/oli/delivery/page/page_context.ex, lib/oli_web/controllers/page_delivery_controller.ex, test/oli/delivery/attempts_test.exs
Additional perf testing revealed that the full attempt hierarchy retrieval present in `Hierarchy.get_latest_attempts` is yielding huge amounts of data for adaptive pages, and thus taking 20 to 30 seconds to fulfill. 
Upon investigation, the rendering of the adaptive page doesn't actually use much of this fetched information, in fact it explicitly "thins" it out in the controller.  
This PR extends this "thinning" out all the way back to the database call, so that just the minimal amount of information is requested.  
The full hierarchy is fetched still for basic pages, as that rendering requires all that data.
=> [BUG FIX] Optimize attempt state fetch

config/prod.exs, lib/oli_web/controllers/api/health_controller.ex, lib/oli_web/router.ex, lib/oli_web/views/api/health_view.ex, test/oli_web/controllers/api/health_controller_test.exs
Purpose is for liveness, readiness and general monitoring based on kubernetes standard. We could later add  livez and readyz if needed, however this generally works for those as well.
=> MER-679 Add general application + db health check end point.

config/config.exs
Performance tests saw these warnings in the logs:
```
Dec 22 23:06:47 ip-10-8-215-102 oli: 23:06:47.459 [warn] Mnesia(:"oli@ip-10-8-215-102"): ** WARNING ** Mnesia is overloaded: {:dump_log, :write_threshold}
```
A bit of online research at:
https://streamhacker.com/2008/12/10/how-to-eliminate-mnesia-overload-events/
and:
https://stackoverflow.com/questions/24406633/rabbitmq-warning-mnesia-is-overloaded/50113675
The warning indicates that log flushing to disc is being overloaded.  This PR addresses it by increasing the log write threshold via the `:dump_log_write_threshold` parameter.   This will increase the time in between log dumps, thus avoiding this warning.
I verified that this configuration change is picked up correctly by `mnesia` by outputing from a controller (this was …
=> [BUG FIX] Increase mnesia log write threshold

config/dev.exs, config/releases.exs, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/advanced_delivery.html.eex
This PR fixes a couple of things with load testing mode:
1. The `load_testing_mode` configuration param was not being read from environment variables correctly.  This param needs to be set to either the `:enabled` or `:disabled` atoms, yet was being read as a boolean parameter. 
2. The load testing meta-data for finalization URL and activity attempts was not being written into the page that rendered adaptive pages.  Note, though, the activity attempts is being set as an empty list, on purpose, because there is no way (yet) for the load test client tool to exercise adaptive pages. 
I have tested and run this locally to confirm that load tests that encounter adaptive pages work correctly.
=> [BUG FIX] Fix load testing of adaptive pages

lib/oli_web/controllers/api/open_and_free_controller.ex
This PR ensures that the load testing tool only uses open and free sections that allow guest access.  That tool currently does not support creation of actual users, therefore, sections that require enrollment will break a load test.
=> [BUG FIX] Only use sections that allow guests in load testing

CHANGELOG.md, lib/oli_web/views/view_helpers.ex
The table rendering with the "View Enrollments" view is breaking with sections that require payment are displayed.  In those cases, an extra column (the Payment date column) is rendered, and many of those records have `nil` as the payment date, which simply means the student hasn't paid yet. 
This PR makes the `dt` helper function robust to the case that the first arg is `nil`.
=> [BUG FIX] Fix enrollment table rendering problem with nil dates

lib/oli_web/router.ex
Stripe payment failures were being seen in AppSignal.  The root cause is that the pipeline used for these endpoints was not passing through the `SetCurrentUser` plug, which is responsible for setting the `conn.assigns.current_user`.  In digging into this, I also noticed that these endpoints were not POW protected either. 
This PR augments the pipeline for those routes to ensure they are both POW protected and that they set the `current_user` assign.  Note, only the payment provider routes are affected, the API endpoint to create payment codes CANNOT be protected in this way. It's authentication strategy is developer API key based.
=> [BUG FIX] Protect payment routes

CHANGELOG.md, lib/oli/activities/state.ex, lib/oli/activities/transformers.ex, lib/oli/analytics/datashop.ex, lib/oli/analytics/datashop/elements/event_descriptor.ex, lib/oli/authoring/editing/activity_editor.ex, lib/oli/authoring/editing/page_editor.ex, lib/oli/delivery/attempts/activity_lifecycle.ex, lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/core/activity_attempt.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli/delivery/page/activity_context.ex, lib/oli_web/controllers/api/activity_controller.ex, lib/oli_web/controllers/api/attempt_controller.ex, lib/oli_web/views/page_delivery_view.ex, test/oli/activities/transformers_test.exs, test/oli/delivery/attempts_test.exs, test/oli_web/controllers/api/attempt_controller_test.exs
This PR implements an optimization to improve the first attempt rendering of both basic and adaptive pages.  
Performance testing data showed very long query times for the bulk activity attempt insertion query that is now present in `Oli.Delivery.Attempts.PageLifecycle.Hierarchy`.  The reason that even this bulk insertion query can take sometimes 20 seconds to execute is that each and every record in that bulk insert contains one full copy of the corresponding activity's model (to populate the `transformed_model` attribute of the activity attempt).  Some adaptive pages contain hundreds and hundreds of activities and some (most?) of their JSON content can be quite large. 
The solution here is to change the implementation to only store `transformed_model` when it actually needs to. In other …
=> [BUG FIX] Only store and use transformed models when necessary

lib/oli/delivery/attempts/core.ex, lib/oli/delivery/page/page_context.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/controllers/page_delivery_controller.ex, test/oli/delivery/attempts_test.exs, test/oli/delivery/page/page_context_test.exs, test/oli/delivery/submission_test.exs
This PR optimizes the render phase for section overview and page display by reducing the number of queries required. 
Specifically, it:
1. Reworks `Core.track_access` to only require one query, and not two.
2. Reworks `Core.get_latest_resource_attempt` to remove the "after the fact" manual preload.
The above eliminates two queries done during every page visit.
It also eliminates the redundant section fetch done in `PageDeliveryController.index`.
There's good unit test coverage here, and I tested manually in my dev environment, so I have high confidence with this change.
=> [BUG FIX] Reduce the number of queries required for render

CHANGELOG.md, lib/oli/delivery/attempts/page_lifecycle/graded.ex, test/oli/delivery/attempts/graded_test.exs, test/oli/delivery/submission_test.exs
Background:
Many reports of "grade passback" problems were being fielded.  In a video demonstrating this failure, a student attempts to finalize a graded adaptive page but the result is the server rendered "Something went wrong" error page (the `error.html` template rendered from `PageDeliveryController` within the `finalize_attempt` function).   The key piece of information from this video, however, was the score that was sent.  Just as the student clicks to submit the assessment, the UI increments their score from `109` to `110`.  Inspection of the other grades in the gradebook show that the maximum of all other student attempts was `109`. 
So the root cause of this failure is the validation logic present in the `ResourceAccess` schema, where it ensures that the `score` can never exceed …
=> [BUG FIX] Cap score to out of

.github/workflows/deploy.yml, .github/workflows/package.yml
This PR enables the ability to disable automatic deployments on certain targets using the `deploy.config` file.
To disable a deployment for a particular git ref (branch or tag), set the `DISABLE_DEPLOY_ON_REF` config accordingly.
For example, a `deploy.config` with
```
DISABLE_DEPLOY_ON_REF=refs/heads/master
```
Will prevent any deployments triggered by the `master` branch. See oli-torus-production for related deploy.sh changes.
=> [CHORE] Pass in github ref to deploy script for disable checks

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx
remove advanced authoring check from navigation
in POTM there are feedbacks presented that should trigger another check.
this was previously based on the (otherwise unused) "advancedAuthoring" setting found in the custom section (not the one in the model). for some reason this was set to false in POTM, but I'm not sure that we need this check anymore, hoping @dtiwarATS can confirm
=> [BUGFIX] spinner of death fix (percieved)

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/layouts/deck/components/FeedbackContainer.tsx
Problem was due to the way `legacyLessons` did not nest the feedback, history, and nav containers within `checkContainer`. Tested in a few lessons where `isLegacyLesson` is `true`.
=> PMP-2430: fixes history navigation arrows missing, feedback displaced

CHANGELOG.md, lib/oli/delivery/paywall.ex, lib/oli/delivery/paywall/providers/stripe.ex, lib/oli/delivery/sections.ex, lib/oli_web/controllers/payment_providers/stripe_controller.ex, test/oli/delivery/paywall/providers/stripe_test.exs, test/oli/delivery/sections/enrollments_browse_test.exs
This PR accomplishes the following:
1. Fixes the sorting of the "Paid On" column within the Enrollments view.  The browse enrollments query just wasn't handling this field explicitly.  Unit testing has been expanded to verify this.
2. Ensures that in order to initiate a Stripe payment intent, that the user in the session is actually enrolled in the course section.  Running in Prod revealed a case where a user with multiple accounts (one LMS and one Independent) ended up initializing a payment for one section with their wrong user.  
3. Explicitly handle the case that somehow a user initializes a second payment before the first has finalized.  Previous to this PR, it was possible for this to happen, resulting in two Payment records being created.  This impl now will identify this case and …
=> [BUG FIX] Handle multiple payment attempts, fix payment_date sorting CMU-431 CMU-430 CMU-432

config/config.exs, config/dev.exs, config/releases.exs, lib/oli_web/controllers/api/media_controller.ex
This PR fixes an issue where email SES and media uploads not working due to ex_aws configuration issue. The configurations have been move from compile-time to dev.exs and releases.exs.
According to the ex_aws [docs](https://github.com/ex-aws/ex_aws), ExAws by default does the equivalent of:
```
config :ex_aws,
access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]
```
So these values are unnecessary in the config (verified by testing torus without them). In order to support regions, the region config remains configurable via AWS_REGION env variable in dev and release environments.
=> [BUG FIX] fix ex_aws configuration issue

lib/oli_web/controllers/payment_providers/stripe_controller.ex
AppSignal reports:
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for "Payment already finalized" of type BitString. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, Postgrex.Stream, DBConnection.Stream, DBConnection.PrepareStream, Timex.Interval, Floki.HTMLTree, File.Stream, Map, Date.Range, Function, HashSet, Range, IO.Stream, List, MapSet, HashDict, GenEvent.Stream, Stream
```
=> [BUG FIX] Fix error handling in stripe controller finalization

lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, test/oli/delivery/attempts/hiearchy_test.exs
Recent performance tests show that "first attempt renders" of large adaptive pages, particularly under system load, can result in the bulk part attempt creation insert query taking 15-20 seconds.  This, of course, ruins the end user experience and greatly impacts the system under load. 
This PR eliminates the "payload" based insert in favor of a query driven bulk insert.  Testing this out initially via PgAdmin, I see even for an adaptive page with 800 or so part attempts that this insert query takes around `53ms` to execute.
=> [BUG FIX] optimize part attempt creation

lib/oli/delivery/paywall.ex
A problem with Stripe provider has allowed more than one Payment record to exist for one Enrollment.  While this problem has been prevented with an earlier PR, any system with these "double payments" fails the `Paywall.can_access?` check due to the inner `has_paid?` use of `Repo.one`.   This fix makes the `can_access?` more robust, using `Repo.all` inside of `has_paid?`
There is excellent unit test coverage here, so a high degree of confidence that this works and doesn't cause any side effects.
=> [BUG FIX] Make has_paid? more robust AOPS-408

lib/oli/branding.ex, lib/oli_web/templates/email/_header.html.eex, test/oli/branding_test.exs
This PR fixes an issue where the url for the logo isn't fully qualified and therefore doesn't appear in emails
Closes #2118
=> [BUG FIX] Fixes logo in email templates

lib/oli/authoring/clone.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli/utils/db_seeder.ex, priv/repo/migrations/20220119121119_optimization_infra.exs, test/oli/clone_test.exs, test/oli/delivery/attempts/hiearchy_test.exs, test/oli/delivery/attempts/optimized_hiearchy_test.exs, test/oli/delivery/page/page_context_test.exs, test/oli/delivery/submission_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs
This PR streamlines the page attempt hierarchy creation by:
1. Creating and leveraging a materialized view to "cache" the part id to activity mapping.
2. Special case handling of adaptive pages to combine delivery resolution and activity attempt creation into one query-driven INSERT
While I was in here I saw an opportunity to significantly improve the performance of course publishing and course project cloning by migrating parts of these impls to query-driven bulk INSERTS. 
For the full background and more details on this implementation, see:
https://docs.google.com/document/d/1gW_ZEzUyKD0ZyM4xwQfuhCxkMXTfx3vsOHfy94uZVMg/edit#
=> [BUG FIX] (Near) Optimal hierarchy creation

lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, test/oli/delivery/attempts/optimized_hiearchy_test.exs
Something is blowing up with the `UNION` bulk insert activity attempts from the stored procedure.  Until that can be sorted out and reworked, this PR reverts the use of that procedure in favor of the previous activity attempt creation approach.  It keeps the view driven part attempts query in place, as analysis of that query shows that it is of very low compute cost (`34`)
=> [PERFORMANCE] revert use of insert stored procedure

config/config.exs, config/releases.exs
Try the option we haven't tried yet for region.
We've tried two ways of using System.get_env (release vs config) and we've tried this libraries :system function (with instance role option included). This is from readme and how it wants the env variable. Would love for third time to be a charm ❤️
=> Update AWS_REGION w last option from library

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
Temporary measure to dump NodeJS payloads to disk in order to troubleshoot badarg problem. 
The other changes are auto-format changes.
=> [BUG FIX] temporary payload dump to disk HOLD ON MERGE

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
the CSS contains multiple '{' brackets and when the value gets passed to textparser which evaluates the variables in text, was replacing the variables with '' value so fixed that.  The fix will not break anything.
=> PMP-2443 | JAN-1272

lib/oli/branding.ex, lib/oli/utils.ex, test/oli/utils_test.exs
This PR ensures that email logo urls are absolute but only adds the url base if one is not configured.
=> [BUG FIX] only add url base if one is not pre configured

lib/oli/interop/ingest.ex, lib/oli_web/controllers/ingest_controller.ex, lib/oli_web/templates/ingest/error.html.eex, lib/oli_web/templates/ingest/index.html.eex, test/oli/interop/ingest_test.exs
This PR adds some more useful basic error handling to course ingestion. This is the first of a couple PRs related to improving ingestion error handling. Follow-on PRs will address verifying idrefs, adding json validation and introducing resource warning support.
=> [FEATURE] add some basic ingestion error checks

assets/styles/authoring/layout/default.scss, lib/oli_web/templates/layout/default.html.eex
I lost that style when adding the changes here and it's necessary to keep the footer at the bottom when the page is pretty much empty
Original bug: https://eliterate.atlassian.net/browse/MER-672
The changes were reverted in master but adding the `flex-grow: 1` style fixes what those changes break.
=> [BUGFIX] [MER-672] Fix footer overlap

lib/oli_web/common/format_date_time.ex, test/oli/delivery/sections/browse_test.exs, test/oli/delivery/sections/enrollments_browse_test.exs, test/oli_web/live/sections/enrollments_view_test.exs, test/support/test_helpers.ex
This PR adds better handling for naive datetimes when given to the formatter and adds a unit test for enrollments view to guarantee the fix.
=> [BUG FIX] gracefully handle naive datetimes

assets/src/components/activities/ordering/OrderingAuthoring.tsx, assets/src/data/activities/model/list.ts, assets/test/data/activities/model/choices_test.ts, lib/oli/interop/ingest.ex
This PR adds a step during ingestion to handle selections, specifically to rewire the tag reference within them to reflect the database id of the newly created tag. 
Also, I found and fixed a problem in the activities model support code, where `Lists.getOne` does not work for keys that are not numeric. 
Also, in OrderingAuthoring, I removed an n^2 lookup (`Choices.getOne` is linear)
=> [FEATURE] Ingestion support for selections

lib/oli/interop/ingest.ex, test/oli/interop/digest/cata.json, test/oli/interop/digest/mcq.json, test/oli/interop/digest/single_response.json
This PR adds support for ingesting a hierarchy of objectives (at most two levels).
It also expects the `objectives` attr of an activity resource to be populated with a map of part ids to a list of original objective ids.  It replaces those ids with database resource ids. Effectively allowing the parts of an activity that have attached skills to ingest.
=> [FEATURE] Ingest second level objectives (aka 'skills'), process objectives attached to activities

lib/oli_web/controllers/open_and_free_controller.ex, lib/oli_web/live/sections/overview_view.ex, test/oli_web/controllers/open_and_free_controller_test.exs
This fixes an aspect of LMS-Lite corse section creation, where after creation the user is taken to a view that expects an authoring account.  
A better solution is to redirect the user to the "Overview" view for their newly created section.
=> [BUG FIX] Redirect to overview view after creation CMU-441

CHANGELOG.md, lib/oli_web/live/grades/gradebook_table_model.ex, lib/oli_web/live/grades/gradebook_view.ex
Closes #2207 
The fix here was to simply check the `open_and_free` flag on the section.
=> [BUG FIX] Only highlight failures for LMS sections

lib/oli/interop/ingest.ex
This PR restores the original behavior of ingest regarding handling of objectives attached to activities. Previously, the `objectives` attr was assumed to be a list, but recent change now expects it to be a map of the part ids to lists of objective identifiers.  Changing this without backwards compatibility broke existing digest files.  This PR handles both cases: a map and a list.
=> [BUG FIX] Allow previous digests with lists of objectives to still process

assets/package.json, assets/src/components/parts/janus-Carousel/Carousel.css, assets/src/components/parts/janus-Carousel/Carousel.tsx, assets/src/components/parts/janus-popup/Popup.tsx, assets/src/components/parts/janus-popup/PopupWindow.tsx, assets/yarn.lock
- Fixes unresponsive carousel navigation in popups. 
- Fixes incorrect initial carousel slide in popups.
- Upgrades `Swiper.js` to the latest version.
- Enhances focus management for popups.
=> [Bugfix][PMP-2472 / JAN-1304] Image carousel not functioning in popup

lib/oli/branding.ex, lib/oli/utils.ex, test/oli/branding_test.exs, test/oli/utils_test.exs
[MER-762](https://eliterate.atlassian.net/browse/MER-762)
Fix 500 error raised when rendering a Course Section show view, in any of the following cases:
- The brand selected when creating the section has a `nil` `logo_dark`, even though the default brand dark logo is not `nil`.
- Both section `logo_dark` field and default dark logo are `nil`.
=> [BUGFIX] [MER-762] Fix Internal Server Error in Course Section View

lib/oli/accounts/schemas/user.ex, lib/oli_web/pow/user_context.ex, test/oli/accounts_test.exs
If the validation was set, we were breaking the user changeset validations for integrations and non-fronted user creation/updates.
With this change, the age verification (if configured) will only be run in the frontend form account creation.
=> Modify user changeset to just validate age on account frontend creation

lib/oli_web/controllers/cognito_controller.ex, lib/oli_web/router.ex, test/oli_web/controllers/cognito_controller_test.exs
Two notes:
- Created MER-843 and added to our current sprint, while I think this is "ok" - we can make this a little cleaner w small refactoring.
- Also asking Infiniscope to change JWT token parameter to be consistent - either `id_token` or `cognito_id_token`. So will add a future PR for that when they decide what to change it too.
=> MER-837 Add an index action to Cognito controller

CHANGELOG.md, lib/oli_web/live/products/details/edit.ex, lib/oli_web/live/products/details_view.ex, lib/oli_web/live/sections/edit_view.ex
This PR limits paywall settings editing to author admin accounts only. 
This is a relatively low risk change. I've tested it interactively to ensure that only an admin can edit these settings now.
=> [FEATURE] Limit paywall editing to admins MER-840

lib/oli/delivery/sections/section_invites.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/plugs/require_section.ex, lib/oli_web/router.ex, test/oli/section_invites_test.exs, test/oli_web/controllers/delivery_controller_test.exs, test/support/factory.ex
[MER-759](https://eliterate.atlassian.net/browse/MER-759) and [MER-740](https://eliterate.atlassian.net/browse/MER-740)
Fix two issues:
- Section metadata not being stored when attempting to create an account accessing the app through a section invite link
- Render view correctly after invite link is deleted
=> [BUGFIX] [MER-759] [MER-740] Invite section link issues

lib/oli_web/live/system_message_live/index_view.ex, lib/oli_web/live/system_message_live/show_view.ex, test/oli_web/live/system_message_live_test.exs
[MER-853](https://eliterate.atlassian.net/browse/MER-853) & [MER-842](https://eliterate.atlassian.net/browse/MER-842)
Fix the following bugs:
- Internal Server Error being raised when an admin tries to manage system messages and the local timezone is not set (this is a separate issue: [MER-838](https://eliterate.atlassian.net/browse/MER-838)).
- Duplicate flash messages showing up.
=> [BUGFIX] [MER-842] [MER-853] System Message Banner issues

priv/schemas/v0-1-0/activity-reference.schema.json, priv/schemas/v0-1-0/group-content.schema.json, priv/schemas/v0-1-0/structured-content.schema.json
This PR fixes the following issues related to schemas
- reduce constraint to allow integers for group ids
- fix structured content schema id
- formatting
=> [BUG FIX] allow integers for group ids

config/releases.exs
This PR is a result of the prod server setup document where enabling SSL configuration at runtime was not previously possible.
=> [BUGFIX] enable SSL configuration at runtime

CHANGELOG.md, assets/src/hooks/text_input_listener.ts
Student Exceptions feature introduced a regression where it broke the ability to do text searches on the Projects and Users views. This was due to the `event_target` attribute not being handled properly.  In some cases what actually gets pushed down to the Phoenix JS Hook is `"live_view"` and not `":live_view"`.  This impl now handles both, which restores the search functionality.
=> [BUG FIX] Restore search functionality in Projects, Users views MER-889

config/releases.exs, oli.example.env
This PR changes torus configuration to only enable SSL if SSL_CERT_PATH and SSL_KEY_PATH are configured. It fixes a production issue identified where torus raises :eaddrinuse on startup if an SSL termination proxy is already running on the same machine.
=> [BUG FIX] Only enable SSL if SSL_CERT_PATH and SSL_KEY_PATH are configured

lib/oli_web/live/common/text_search.ex
Student exceptions work introduced a regression where the clear button ("X") for the text search component was no longer working in situations where the LiveView needed to handle the event.  The fix here was to bypass the Surface event handler, which must be pinning it to the component (since that component is a stateful component).  This change allows it to work in situations where the LV needs to handle the event 
Tested with various uses (Projects view, Users view, All Sections View) as well as the EnrollmentPicker LiveComponent.
=> [BUG FIX] Allow clearing of text search to work properly MER-889

CHANGELOG.md, lib/oli_web/controllers/delivery_controller.ex, test/oli_web/controllers/delivery_controller_test.exs
This PR fixes a problem that if a student which already has an account, attempts to use a section invite link to a section that either 1) Hasn't started or 2) Has already ended, the "Section Unavailable due to ...." page does not render. Instead, the Enroll view with the recaptcha renders, and when the student attempts to enroll they receive and error. 
The fix here was to simply run the `enroll_independent` endpoint function through the existing `show_enroll` function.  That picks up the logic of checking to see if the section is available prior to rendering the Enroll screen.
=> [BUG FIX] Properly handle unavailable sections MER-865

lib/oli_web/templates/page_delivery/_link_assessment.html.eex, lib/oli_web/templates/page_delivery/_link_container.html.eex, lib/oli_web/templates/page_delivery/_link_page.html.eex, lib/oli_web/templates/page_delivery/_link_shallow_container.html.eex, lib/oli_web/templates/page_delivery/_outline.html.eex, lib/oli_web/templates/page_delivery/container.html.eex, lib/oli_web/templates/page_delivery/index.html.eex, lib/oli_web/views/page_delivery_view.ex
This PR improves the display of the top-level "Course Overview" full tree and the intermediate, single-level "Container" pages. 
It replaces the use of Bootstrap "list-group" and nested `<div>` elements that contain `style` attributes with a calculated margin (to get an indentation effect) with nested `<ol>` elements.  This achieves the same indentation and is more semantically correct. 
Also removes the use of the Bootstrap `page-link` class from all links.  This is a Bootstrap class that is used in pagination displays and was responsible for adding the borders around the outline elements.
The net effect is a much cleaner index display.
=> [BUG FIX] Improve course outline rendering

lib/oli/delivery/attempts/core.ex, lib/oli/delivery/gating/gating_condition.ex, lib/oli/delivery/page/objectives_rollup.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/sections/gating_and_scheduling/form.ex, lib/oli_web/live/sections/gating_and_scheduling/gating_condition_store.ex, lib/oli_web/plugs/maybe_gated_resource.ex, lib/oli_web/templates/page_delivery/advanced_delivery.html.eex, priv/repo/migrations/20220306185035_gating_grading_policy.exs, test/oli/delivery/attempts_test.exs, test/oli_web/plugs/maybe_gated_resource_test.exs
This PR adds the ability for the creator of a gate to determine whether the gate once active, when is guards a graded page, should allow the student to still be able to review already completed attempts for that graded page. 
This work introduces a new `:graded_resource_policy` enumeration attribute on the `GatingCondition` schema. It takes one of the following values:
1. `:allows_nothing` - When selected, an active gate guarding a graded page will not allow the student to start new attempts nor review existing attempts
2. `:allows_review` - When selected, an active gate guarding a graded page will not allow the student to start new attempts, but it will allow the review of already completed attempts.
Description of targeted use cases is here: …
=> [FEATURE] Allow policy driven review of gated graded resources MER-815

lib/oli_web/controllers/page_delivery_controller.ex
This PR fixes an issue where the rendering of adaptive pages that do use application chrome (i.e., they render `page.html.eex` as the root layout) was broken.  The reason was that the new `page_link_url` and `container_link_url` assigns were missing.  Chromeless display doesn't use these, but the chrome based display does (in order to render the "Previous" and "Next" links).
The fix here is to add them. 
Error from AppSignal:
```
** (KeyError) key :container_link_url not found in: %{activity_guid_mapping: "{\"18029\":{\"attemptGuid\":\"3740b4bc-67ce-4a2e-9842-f695583b30e6\",\"deliveryElement\":\"oli-adaptive-delivery\",\"id\":18029},\"18051\":
```
=> [BUG FIX] Fix adaptive page rendering issue MER-906

lib/oli_web/live/sections/invite_view.ex, test/oli_web/live/sections/invite_view_test.exs, test/support/factory.ex
[MER-751](https://eliterate.atlassian.net/browse/MER-751)
When an admin or instructor attempts to create an invitation link for a course section, an error flash message is displayed prohibiting that action if the registration is not open.
=> [MER-751] Prohibit admin and instructors to create invitation links when section registration is not open

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
ensure there are spaces between classes
=> [BUGFIX] PMP-2499 lesson css classes in adaptive player are missing a space

CHANGELOG.md, assets/styles/delivery/purpose.scss
Closes #2270 
Hides purpose type decorations after the first if the same purpose type is used "in a series" for activities on a page. This is only done for activities, not page content items.
It will not hide the decoration if the series is "broken" by a different purpose type. That is, if you have two series of the same purpose type (Purpose Type 1) separated by a different one (Purpose Type 2), the decoration for Purpose Type 1 will show on the first activity in each series.
=> [ENHANCEMENT] Hide subsequent purpose type decorations for activities

CHANGELOG.md, assets/styles/authoring/model-editors.scss, assets/styles/common/elements.scss
Fixes #2271
The issue was that tables didn't have a css option set for `word-wrap`, so when the word was too long for the cell, it overflowed.
Before:
After:
=> [BUG FIX] Fix table styling to break words that overflow bounds

lib/oli/email.ex, lib/oli/help/providers/email_help.ex
We saw this a while back with other emails and we updated them so this makes is consistent + should remove the hackney parsing issue.
=> Make reply-to consistent to avoid hackney parsing issues with bracket / string.

assets/src/adaptivity/operators/contains.ts
if blank values are found in the rule, then there will be an exception trying to trim them (null)
=> [Bugfix] pmp 2610 jan 1463 contains exception

lib/oli_web/live/sections/gating_and_scheduling/gating_condition_store.ex
This PR fixes an issue where only top-level pages could be selected when picking the "source" for a Finished or Started gate. 
The `filter_items_fn` of the `SelectResourceModal` was being used in a way that was filtering out containers (in an attempt to prevent them from being selected).  This lead to the inability for a user to navigate into containers to find and select nested pages. 
Solution here is to remove this filtering from the modal, and ensure that only pages are selected after the user selects something.
=> [BUG FIX] Allow navigation through hierarchy when picking source for Finished, Started gates MER-932

assets/src/utils/common.ts
TS compiler was throwing an error only when compiling the Node library for the rules engine.  
Solution seems to be to just cast as `any` and the compilation now works.
=> [BUG FIX] Cast array to allow flatMap to work

assets/src/components/editing/elements/blockcode/BlockcodeElement.tsx
The introduction of monaco editor added a significant increase to the js bundle size. This PR reconfigures monaco editor in the blockcode editor to code split using webpack and lazy load the javascript for monaco when the component is rendered.
Details on how exactly this works can be found in the react docs https://reactjs.org/docs/code-splitting.html
Closes #2337
=> [BUG FIX] code split and lazy load monaco editor

priv/repo/migrations/20220308142458_attempt_states.exs, priv/repo/migrations/20220317164007_fix_previous_migration.exs
Adds a new migration to address problems from the previous one, when it is used in an existing database it is having problems resolving the "reused" functions from the `alias Oli.Repo.Migrations.OptimizationInfra` migration.
I simply duplicate the needed code from this earlier migration.  
Errors reported look like:
```
[2022-03-17 16:05:56.712] [d-CL7B34SIG][stderr]warning: Oli.Repo.Migrations.OptimizationInfra.create_trigger/1 is undefined (module Oli.Repo.Migrations.OptimizationInfra is not available or is yet to be defined)
[2022-03-17 16:05:56.712] [d-CL7B34SIG][stderr]  oli/lib/oli-0.18.4/priv/repo/migrations/20220308142458_attempt_states.exs:47: Oli.Repo.Migrations.AttemptStates.change/0
[2022-03-17 16:05:56.712] [d-CL7B34SIG][stderr]
[2022-03-17 16:05:56.712] …
```
=> [BUG FIX] Fix migrations, avoid code resuse which is breaking

config/dev.exs
Upon setting up my initial local development environment, I ran into a road-blocker of the SSL listener being forced onto port 443 for the dev environment. 
This change adds the ability to read it in from an env-var HTTPS_PORT, much like the existing HTTP_PORT
In addition, set up the ability to specify the SSL cert/key path SSL_KEY_PATH & SSL_CERT_PATH
=> [CHORE] Ability to set HTTPS port on dev environments via env var.

lib/oli_web/templates/page_delivery/advanced_delivery.html.eex, lib/oli_web/templates/resource/advanced_page_preview.html.eex
this will make it so only the 'oli_adaptive' activity script will be loaded in the advanced delivery and preview;
technically we should determine based on what is used in the page rather than hard coding, but this will gain a small download perf bonus
=> [PERF] only load the adaptive activity for now in advanced pages

lib/oli_web/live/history/details.ex, lib/oli_web/live/history/revision_history.ex, lib/oli_web/router.ex
Introduces support in the Revision History tool to load the history of a resource by its "resource id".  This is very useful in that when looking at the history of a page you often want to dig into the history of a reference activity, but all you have is the activity's resource id.
=> [FEATURE] Allow history navigation via resource_id

lib/oli/delivery/hierarchy.ex, lib/oli/delivery/hierarchy/hierarchy_node.ex, lib/oli/delivery/sections.ex, lib/oli_web/live/delivery/remix_section.ex, test/oli/delivery/hierarchy_test.exs, test/oli/resources/numbering_test.exs, test/oli/sections_test.exs
This PR fixes an issue where remixing content results in incorrect numberings. It also adds a safety net to all hierarchy operations by requiring a finalization step before rebuilding section curriculum, which ensures that the hierarchy numbering is up to date after any modifications.
Closes #2298
=> [BUG FIX] Remix renumbering

assets/src/components/activities/common/authoring/GradingApproachDropdown.tsx, assets/src/components/activities/types.ts, assets/src/hooks/before_unload.ts, assets/src/hooks/index.ts, assets/src/hooks/tooltip.ts, lib/oli/activities/model/part.ex, lib/oli/delivery/attempts/activity_lifecycle.ex, lib/oli/delivery/attempts/core/activity_attempt.ex, lib/oli/delivery/attempts/manual_grading.ex, lib/oli/delivery/attempts/manual_grading/browse_options.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/page/activity_context.ex, lib/oli_web/live/common/paged_table.ex, lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/manual_grading/apply.ex, lib/oli_web/live/manual_grading/filter_button.ex, lib/oli_web/live/manual_grading/filters.ex, lib/oli_web/live/manual_grading/group.ex, lib/oli_web/live/manual_grading/manual_grading_view.ex, lib/oli_web/live/manual_grading/part_scoring.ex, lib/oli_web/live/manual_grading/rendered_activity.ex, lib/oli_web/live/manual_grading/rendering.ex, lib/oli_web/live/manual_grading/score_feedback.ex, lib/oli_web/live/manual_grading/table_model.ex, lib/oli_web/live/manual_grading/tabs.ex, lib/oli_web/live/projects/projects_live.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, test/oli/delivery/attempts/manual_grading_test.exs
This PR introduces the UI allowing an instructor to perform manual scoring for the submitted attempts of their students.
In addition to the LiveView (and components) that implement the UI, there were a few other changes necessary:
1. Introduction of a new `outOf` attribute for parts within an activity model. This attribute specifies the maximum points available for a part, and if not present defaults to `1.0`.  No activities currently allow setting this attribute, so all parts will use the default value (for now).
2. Enable the ability to set the grading approach of the `ShortAnswer` activity. 
3. Add a new `apply_manual_scoring` function to the `ManualGrading` infrastructure context. This function allows the application of an instructor assigned score and feedback to an activity attempt. …
=> [FEATURE] Manual grading UI

lib/oli/delivery/attempts/manual_grading.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, test/oli/delivery/attempts/manual_grading_test.exs
This PR fixes an issue where grading of the last manually graded activity in a graded page was not resulting in the grade rolling up to the resource access.
=> [BUG FIX] Allow manually scored graded attempts to roll up to resource access

lib/oli_web/controllers/delivery_controller.ex
This PR fixes an issue where if an instructor attempted to use grade passback (e.g. to sync line items) in the launch that created the course section, the passback failed. 
The root cause was at section creation time we were not capturing the relevant LTI settings that configure passback.  It was only upon subsequent launches that these four settings were captured.
=> [BUG FIX] Capture grade passback lti params at section creation time MER-961

CHANGELOG.md, lib/oli/delivery/paywall.ex, lib/oli/delivery/paywall/access_summary.ex, lib/oli_web/controllers/payment_controller.ex, lib/oli_web/plugs/enforce_paywall.ex, lib/oli_web/templates/layout/_pay_early.html.eex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/views/layout_view.ex, test/oli/delivery/paywall_test.exs, test/oli_web/controllers/payment_providers/stripe_controller_test.exs
This PR implements the ability for a student that is accessing a paywalled course during the grace period to:
1. See and understand how much time they have left remaining in the grace period
2. Proceed forward with making a payment or applying an access code
The changes here are:
1. Provide a `summarize_access` method in the `Paywall` context that returns a struct that details not only whether or not a user can access a course section, but also the reason why (`:not_paid`, `:within_grace_period`, `:instructor`, etc). 
2. Adjust the `EnforcePaywall` plug to insert the `AccessSummary` struct into the connection assigns for later use in a banner display
3. Add a banner display when the user is accessing the course in the grace period.  
To test this out:
1. Create a paywalled course section, …
=> [ENHANCEMENT] Allow payment during grace period CMU-417

lib/oli/accounts.ex, lib/oli/authoring/clone.ex, lib/oli/authoring/course/project.ex, lib/oli_web/controllers/cognito_controller.ex, lib/oli_web/live/projects/visibility.ex, lib/oli_web/router.ex, lib/oli_web/templates/cognito/index.html.eex, lib/oli_web/views/cognito_view.ex, priv/repo/migrations/20220328192150_allow_projects_duplication.exs, test/oli/accounts_test.exs, test/oli/clone_test.exs, test/oli_web/controllers/cognito_controller_test.exs, test/oli_web/live/project_visibility_test.exs
This PR implements the core functionalities for the [MER-770 Infiniscope Post Launch epic](https://eliterate.atlassian.net/browse/MER-770), which includes:
- [MER-754](https://eliterate.atlassian.net/browse/MER-754): Portal user ability to make a project copy in Torus and log in with an author account.
- [MER-817](https://eliterate.atlassian.net/browse/MER-817): Allow authors control if their projects can be duplicated by non-collaborators.
- [MER-819](https://eliterate.atlassian.net/browse/MER-819): Guide portal instructors when they want to clone a project, to choose between an existing duplicate project or creating a new one.
=> [MER-754][MER-817][MER-819] Author and customize project flow for Portal

assets/src/adaptivity/operators/equality.ts, assets/test/adaptivity/rules_engine_test.ts
The correct trap state has codition 'session.visits.q:1484171837224:1023 = true'. Currently the value of 'session.visits.q:1484171837224:1023' gets set to numeric value i.e. 1; so made changes to fix this. We could compare that with '1==true' but since we are checking with '===', need the code to handle this.
=> PMP-2580 | JAN-1417

assets/src/apps/delivery/components/ActivityRenderer.tsx, assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
This change fixes an issue where the rich text editor in capi iframes were sometimes getting ids set to undefined:undefined in local storage, which allowed them to stomp on each other when retrieving values from local storage.
=> Fixed issue with rich text editor id overlap

CHANGELOG.md, assets/src/components/editing/elements/popup/PopupElement.tsx, lib/oli/rendering/content/html.ex
The problem was calling a react hook to update the model from inside a modal.
When testing the other editors I noticed the image alt text did not display correctly.
Closes #2371
=> [BUG FIX] Fix popup content editing and image alt text rendering

assets/src/components/content/SlateFixer.ts, assets/src/components/content/StructuredContentEditor.tsx
fix content before passing to slate
it looked like an issue already was merged for this, but updating slate did not seem to fix it (we may already be on the updated minor version)
https://github.com/ianstormtaylor/slate/issues/3625
https://github.com/ianstormtaylor/slate/pull/4208
=> [BUGFIX] AOPS-568 Cannot get the start point in the node at the path [16] because it has no start text nod

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
This fixes an issue where in history mode, moving forward in time made the app still think it was in the history, resulting in some components disabling when they shouldn't.
=> Fixed issue with history mode checking request

assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/authoring/components/RightMenu/RightMenu.tsx
This change fixes an issue in authoring where a user would select a question bank, then another layer, and the properties of the question bank would overwrite the data of the other layer they selected.
=> BUGFIX: Fix issue with question bank data overwriting other layers on select

test/oli/sections_test.exs
[MER-1022](https://eliterate.atlassian.net/browse/MER-1022)
Fix flaky test in `sections_test.exs` due to an ordering issue when retrieving enrollments for a given section.
=> [MER-1022] Fix ordering issue in sections test

assets/styles/authoring/layout/workspace.scss, assets/styles/common/user.scss, lib/oli_web/templates/layout/_account_header.html.eex, lib/oli_web/templates/layout/_author_account_dropdown.html.eex, lib/oli_web/templates/layout/_project_header.html.eex, lib/oli_web/templates/layout/_user_account_dropdown.html.eex, lib/oli_web/templates/layout/_workspace_header.html.eex, lib/oli_web/views/authoring_view.ex, lib/oli_web/views/layout_view.ex, test/oli_web/views/layout_view_test.exs
[MER-818](https://eliterate.atlassian.net/browse/MER-818)
This PR adds a new dropdown in the authoring side for consistency. Having a signout and a way to jump into the linked user account.
Also take the opportunity to refactor the user dropdown to make it less repetitive code and clearer. Based on the logic, I ended with:
- Signout is always shown
- A user can edit its account if is independent learner 
- Independent instructors are **not** marked as independent learners by default
- A user can see the My Courses if is independent learner or independent instructor
- A user can see the link account if it's not a student or is independent instructor
- That last part because a user could be potentially both?
^^  Appreciate you let me know your thoughts and if I missed something or you think …
=> [FEATURE] [MER-818] Move between accounts

assets/src/data/persistence/extrinsic.ts, assets/src/utils/common.ts
while debounce provides the desired delay, using async it leaves a lot of unresolved promises; create a batched buffer instead
=> [BUGFIX] previous debounce losing data

lib/oli/institutions.ex, test/oli/institutions_test.exs
This PR fixes an issue where different casings of an institution URL resulted in duplicate institutions being created when the UI says it will be added to an existing institution (the UI javascript already did the right thing here, which is downcase before comparing the url)
Closes #2265
=> [BUGFIX] downcase normalized url to find existing institutions

assets/src/adaptivity/scripting.ts, assets/test/adaptivity/scripting_test.ts
display float number up to 2 decimal points
=> (JAN-1577 | PMP-2729) Multiple lessons - lesson variables display too many digits after decimal

assets/styles/delivery/layout/delivery.scss, assets/styles/global.scss, lib/oli/delivery/sections/browse.ex, lib/oli/delivery/sections/browse_options.ex, lib/oli/delivery/sections/section.ex, lib/oli_web/common/params.ex, lib/oli_web/live/common/listing.ex, lib/oli_web/live/common/paged_table.ex, lib/oli_web/live/projects/projects_live.ex, lib/oli_web/live/sections/sections_view.ex, lib/oli_web/live/sections/table_model.ex, priv/repo/migrations/20220422144507_add_sections_search_indexes.exs, test/oli/delivery/sections/browse_test.exs, test/oli_web/live/sections/admin_index_live_test.exs, test/support/test_helpers.ex
[MER-938](https://eliterate.atlassian.net/browse/MER-938)
Improve the admin sections index so they are able to find them easier (specially if there a lot).
Changes include:
- Added some columns
- Sort by all columns
- Search by some more columns
- Filter by status, type or active by date
Any feedback/suggestion/thought is welcome 😄 
**NOTE: This PR will be marked as "Ready for Review" and can be merged once it has 2 approvals.**
=> [FEATURE] [MER-938] Improve admin sections view

CHANGELOG.md, lib/oli/authoring/editing/page_editor.ex, test/oli/editing/page_editor_test.exs, test/oli/publishing_test.exs
Several times we have seen issues where activities have seemingly "gone missing" and resolution ends up returning `nil`.
The root cause is in the page editor code that deletes and resurrects activities.  It was doing this directly on the revision, which is problematic in the case where a duplicate project is using the same revision.  The safe and correct impl here is to create a new revision, always, against the resolved revision. 
Fixing this exposed a flaw in a related test (publishing_test.exs), which I fixed.  
Closes #2434
=> [BUGFIX] Fix activity deletion issue

lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/plugs/registration_captcha.ex
Bug:
Go to the author registration page: /authoring/registration/new
Fill out the form
Do not check the captcha
Click the register button
Expected: We see a captcha error since it wasn’t filled out
Actual: The user is allowed to register.
=> [BUG] [MER-1100] Author creation ignores captcha

assets/package.json, assets/yarn.lock, lib/oli/activities.ex, lib/oli_web/controllers/api/activity_registration_controller.ex
This PR attempts to fix the docs building by ensuring that the `typedoc-plugin-markdown` package is installed.  
It also adds some logging server-side to the registration process and passes back the specific error to the client code.
=> [BUG FIX] Fix docs build, add detailed logging

.github/workflows/package.yml, test/oli_web/controllers/api/activity_registration_controller_test.exs
Typedocs build step was being invoked at the root, and not within `assets`
=> [BUG FIX] Execute in correct dir

lib/oli_web/api_spec.ex, lib/oli_web/controllers/api/activity_registration_controller.ex, lib/oli_web/controllers/api/payment_controller.ex, lib/oli_web/controllers/api/product_controller.ex
Small developer quality-of-life update:
The api docs at /api/v1/docs for the calls protected by api keys, authentication wasn't set correctly.
Now, you can use that interface to call the API methods by pasting in a base-64 encoded api key. That UI is only available in :dev or :test mix environments.
Example:
=> [ENHANCEMENT] [MER-1113] Fixed auth on swagger docs

CHANGELOG.md, lib/oli_web/templates/layout/_author_account_dropdown.html.eex, lib/oli_web/views/layout_view.ex, mix.exs, test/oli_web/controllers/project_controller_test.exs
This PR fixes an issue related to the discussion in https://github.com/Simon-Initiative/oli-torus/pull/2424#issuecomment-1098317873
The unit test included recreates the problem discussed in the related PR discussion above. To recreate the issue, one must link multiple user accounts (possibly across different LMS) to a single authoring account.
Author accounts can have more than one user account associated with them, and therefore it is not possible have a single "Go to my courses" link from the author account dropdown, due the one:many relationship. This is because a single author account may be used across multiple LMS and independent instructor accounts. This fix is high priority, as it resolves a production issue where this situation crashes the server. A larger discussion will be …
=> [BUG FIX] fix an issue where multiple user accounts linked to an author results in error

assets/src/adaptivity/scripting.ts, assets/test/adaptivity/scripting_test.ts
JAN-1633/PMP-2785: Fixed Recalled text has not spacing between words and added test case
=> JAN-1633/PMP-2785: Fixed Recalled text has not spacing between words

priv/schemas/v0-1-0/content-element.schema.json
This change allows caption attribute to be either a string or an array, so that it can support rich text.
=> [BUG FIX] Allow rich text in captions

assets/src/adaptivity/scripting.ts
This change expands on the checks for whether a value is a math expression.
=> Fixed failed check for Math Expression

lib/oli/authoring/course.ex, lib/oli/authoring/course/project.ex, lib/oli/delivery/sections/section.ex, lib/oli/inventories.ex, lib/oli/inventories/publisher.ex, lib/oli/utils.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/live/publisher_live/form.ex, lib/oli_web/live/publisher_live/show_view.ex, lib/oli_web/live/publisher_live/table_model.ex, priv/repo/migrations/20220418150726_add_publisher_to_projects_and_products.exs, priv/repo/migrations/20220429123205_add_default_to_publishers.exs, test/oli/course_test.exs, test/oli/inventories/publisher_test.exs, test/oli/inventories_test.exs, test/oli_web/live/publisher_live_test.exs, test/support/factory.ex
[MER-1098](https://eliterate.atlassian.net/browse/MER-1098)
This PR does the following changes:
- Allow admins to set/update a default publisher.
- Bugfix for when an admin tries to delete a publisher that has associated projects or products.
=> [MER-1098] Add default field to publishers

lib/oli_web/templates/layout/_pay_early.html.eex
Root cause was the wrong route endpoint was linked from the "Pay Early" message.  Instead of the view that allows the student to pick either "Pay with Credit Card" or "Pay with Code" this view was taking the user directly to the "Pay with Credit Card" view.
=> [BUG FIX] redirect to guard, not the direct payment show MER-1124

lib/oli/authoring/editing/activity_editor.ex, lib/oli/authoring/editing/page_editor.ex, lib/oli/publishing.ex, test/oli/clone_test.exs
This PR improves the logic to guard against edits made in duplicate projects affecting the upstream original. 
The root cause of these ongoing problems is reliance on the lock acquisition result (acquired or updated) to determine if a new revision is needed.  I believe there are cases with the bulk activity edit endpoint in the adaptive page where this strategy falls down. 
Rather than rework this lock based logic, I am replacing this with a much more straightforward approach.  This PR adds a check to see if any other PublishedResource records have the same `revision_id` as the id of the revision that is about to be edited.  For the project that we are editing within, if the only published resource record that contains this same revision id pertains to the "unpublished" publication, we …
=> [BUG FIX] MER-1125 improved guard to force new revision creation

assets/src/apps/authoring/store/app/slice.ts
the screen editor for Feedback and Popups was using a hack on the window object because of the nested web components. this went away when we changed how apps were launched/registered. putting it back for now
=> [BUGFIX] hack the part component types onto the window pending a better fix

CHANGELOG.md, lib/oli_web/templates/project/_lti_connect_instructions.html.eex, mix.exs
This hotfix PR fixes an issue where LTI Get Connected button was not working due to incorrect jquery version. The changes here simply remove the bootstrap collapse component and replace it was regular javascript.
Closes #2339
=> [BUG FIX] Fix publish LTI instructions

lib/oli_web/live/history/revision_history.ex, priv/schemas/v0-1-0/adaptive-activity-content.schema.json, priv/schemas/v0-1-0/adaptive-activity.schema.json
previously the revision history tool was limited to being able to edit a page due to the schema settings; this should enable activities (I honestly only tried adaptive) to be edited as well.
also note in `details.ex` there is another schema reference, but I am not sure how to change that.
```
validate_schema_uri="http://torus.oli.cmu.edu/schemas/v0-1-0/page-content.schema.json"
```
as far as I can tell it will only affect the Monaco client schema validation, not the actual validation.
suggestions on how to do that are welcome :)
=> [BUGFIX] enable activity json to be edited in revision history tool

assets/src/components/parts/janus-dropdown/Dropdown.tsx
Setting the max-width on the dropdown is causing the issue:
Before:
After: (Setting the max-width value to >= 0.98)
=> [JAN-1585/PMP-2737]Updated the maxWidth for the Dropdown

assets/src/apps/delivery/Delivery.tsx, assets/src/apps/delivery/layouts/deck/LessonFinishedDialog.tsx, assets/src/apps/delivery/store/features/page/slice.ts, lib/oli_web/controllers/page_delivery_controller.ex
[MER-1072](https://eliterate.atlassian.net/browse/MER-1072)
The urls that the lessons were redirecting to after finishing them when closing the congrats modal were wrong as they were hardcoded and calculated given the current url of window.
In the use case of reviewing again the lesson and "re-submitting" it, the  `/attempt/${resourceAttemptGuid}` path was being appended twice. 
With this change, the urls are sent from the phoenix app, so no matter where it comes from it will redirect just fine. Also, if tomorrow the path of those route changes, it's not necessary to update anything in the JS code.
=> [MER-1072] Wire lesson finish urls from backend

lib/oli/analytics/datashop.ex
This PR fixes a problem (I think) where adaptive activities that omit "hints" breaks datashop download. 
The hint handling should now be much more robust.
=> [BUG FIX] handle hints in more robust way

lib/oli/delivery/sections.ex, lib/oli/publishing.ex, lib/oli/utils/slug.ex, priv/repo/migrations/20220512182638_add_section_resources_slug_index.exs, test/oli/publishing_test.exs, test/oli/sections_test.exs, test/oli/utils/slug_test.exs
[MER-1117](https://eliterate.atlassian.net/browse/MER-1117)
Some users are experiencing long response times when saving an updated curriculum in the Remix Section Page, even sometimes causing a timeout and the materials not being added.
The main issue was that when creating new section resources, in order to ensure that these have unique slugs, the logic was querying the `section_resources` table `n` times causing very slow responses.
Instead of making `n` queries to ensure the slugs are unique, the logic now creates a set of slug candidates for the section resources that will be created, and makes only one query to reduce this set to only include the candidates that already exist in the db (and therefore aren't unique yet). It repeats this process until all slugs are unique.
This reduced …
=> [BUGFIX][MER-1117] Fix performance issues on remix page

lib/oli_web/live/common/hierarchy/hierarchy_picker.ex, lib/oli_web/live/delivery/remix_section.ex, lib/oli_web/live/delivery/remix_section.html.heex, test/oli_web/live/remix_section_test.exs
[MER-1118](https://eliterate.atlassian.net/browse/MER-1118)
Reverted changes did in https://github.com/Simon-Initiative/oli-torus/pull/2472
Expected
- In remix section view and student section view, order from db is respected
- In add materials modal, units are placed first for all lessons
=> [BUGFIX] [MER-1118] Materials order

assets/src/apps/authoring/components/AdaptivityEditor/InitStateEditor.tsx
This fixes an issue where if the user selects between screens that are part of a layer, the init state value would not update as expected.
=> Fixed initstateeditor to use value instead of defaultValue

lib/oli_web/templates/page_delivery/_link_shallow_container.html.eex, lib/oli_web/templates/page_delivery/container.html.eex, test/oli_web/controllers/page_delivery_controller_test.exs, test/support/test_helpers.ex
[MER-1086](https://eliterate.atlassian.net/browse/MER-1086)
Fixes curriculum item numbering always showing at the item level.
When set to false, numbering doesn't show in the section overview:
However it did show in each unit's overview:
Section overview
Unit overview
=> [MER-1086] Fix curriculum numbering visibility not applied at item level

lib/oli/inventories/publisher.ex, lib/oli/utils.ex, lib/oli_web/live/publisher_live/form.ex, test/support/factory.ex
[MER-1144](https://eliterate.atlassian.net/browse/MER-1144)
Update email regex to be less restrictive and consider emails such as `support@argos.education`.
=> [BUGFIX][MER-1144] Create Publisher field validation too restrictive

assets/src/phoenix/timezone.ts, lib/oli/utils/db_seeder.ex, lib/oli_web/common/format_date_time.ex, lib/oli_web/live/sections/gating_and_scheduling/edit.ex, lib/oli_web/live/sections/gating_and_scheduling/form.ex, lib/oli_web/live/sections/gating_and_scheduling/gating_condition_store.ex, lib/oli_web/live/sections/gating_and_scheduling/new.ex, lib/oli_web/live/system_message_live/index_view.ex, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex, test/oli_web/controllers/static_page_controller_test.exs, test/oli_web/live/sections/gating_and_scheduling_test.exs
[MER-1067](https://eliterate.atlassian.net/browse/MER-1067)
Users create scheduled gating conditions selecting start and end date, but after saving, the times are shifted and inconsistent with what the user selected.
The logic isn't considering the local timezone when saving the datetimes in the database.
1. Before saving the gating condition, convert the input dates to UTC assuming they are in the user local timezone.
2. It is not related to this specific bug, but sometimes happens that the local timezone in the server session gets cleared and out of synch with the one set in the browser session storage, causing the session not to update accordingly. Therefore we may end up in a scenario where the browser has a timezone set but the server doesn't, causing the app to fail in some flows. …
=> [BUGFIX] [MER-1067] Fix timezone issue when saving gating conditions

assets/src/adaptivity/operators/equality.ts, assets/test/adaptivity/rules_engine_test.ts
This fixes an issue where is a fact value is a boolean, but a rule is checking for a string, it would not get past this section of the rules engine.
=> Fixed issue with booleans passed to rules checking strings

assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx
follow up for PMP-2835 JAN-1684 mcq on layers not respecting init state empty array
=> [BUGFIX] MCQ not respecting init state completely when on a parent screen

assets/styles/common/controls.scss, lib/oli_web/live/common/properties/read_only.ex, lib/oli_web/live/sections/overview_view.ex, test/oli_web/live/sections/overview_live_test.exs, test/support/factory.ex
[MER-1171](https://eliterate.atlassian.net/browse/MER-1171)
Show institution name and link under the "Details" section in the Course Overview page.
=> [MER-1171] Display institution link in sections overview page

CHANGELOG.md, assets/src/data/content/utils.tsx
Closes #2505 
Inputs in a multi-input activity were being duplicated.  Root case was code that adding input_refs when they could not be found used a method that explicitly excluded input_refs from being found.
=> [BUG FIX] Allow input refs to be found

lib/oli_web/controllers/lti_controller.ex, test/oli_web/controllers/lti_controller_test.exs
Multiple customers have requested the assignment selection placement to be enabled in Canvas. Eventually this should be updated trigger the Deep Linking flow. Left a note towards that goal.
=> MER-1158 Add assignment selection to developer key

lib/oli_web/live/sections/overview_view.ex, test/oli_web/live/sections/overview_live_test.exs, test/support/test_helpers.ex
[MER-1203](https://eliterate.atlassian.net/browse/MER-1203)
Before these changes, the institution link was appearing for both admins and instructors in the sections overview page, but only admins are allowed to access to an institution page.
With the new behavior:
- Show the section institution name and a link to the institution page when accessing as an **admin**.
- Show only the section institution name when accessing as an **instructor**.
=> [BUGFIX][MER-1203] Institution link must only appear for admins in the sections overview page

lib/oli_web/templates/page_delivery/prologue.html.eex
previously a score of 1000.0 would render as 1.0e3
=> [BUGFIX] don't display scores using scientific notation

CHANGELOG.md, assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts, assets/src/components/activities/file_upload/FileSpecConfiguration.tsx, assets/src/components/activities/file_upload/FileUploadAuthoring.tsx, assets/src/components/activities/file_upload/FileUploadDelivery.tsx, assets/src/components/activities/file_upload/actions.ts, assets/src/components/activities/file_upload/authoring-entry.ts, assets/src/components/activities/file_upload/delivery-entry.ts, assets/src/components/activities/file_upload/manifest.json, assets/src/components/activities/file_upload/schema.ts, assets/src/components/activities/file_upload/utils.ts, assets/src/components/activities/types.ts, assets/src/data/activities/DeliveryState.ts, assets/src/data/activities/utils.ts, assets/src/data/persistence/media.ts, assets/src/data/persistence/state/intrinsic.ts, lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli/delivery/attempts/activity_lifecycle/persistence.ex, lib/oli/delivery/attempts/artifact.ex, lib/oli/delivery/attempts/core/student_input.ex, lib/oli_web/controllers/api/attempt_controller.ex, lib/oli_web/router.ex, test/oli/delivery/submission_test.exs
This PR adds a new activity type, the "File Upload" Activity, which expects a student to upload one or more files as their submission. 
It basically works by allowing files to be uploaded into a folder structure of "section slug" / "activity attempt guid" / "part attempt guid", and recording uploaded file meta data in the part attempt `response` attribute. 
The large bulk of the PR is the client-side impl of the activity, with a new state service endpoint for uploading files. 
Given time constraints, there are a couple of rough edges here that we will eventually want to improve upon. These include:
1. Allowing author to specify a max file size per file (or perhaps as a total quota)
2. An atomic method for uploading files and tracking their state in the student response. Right now these …
=> [FEATURE] File Upload activity

CHANGELOG.md, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/curriculum/entries/options_modal.ex, lib/oli_web/templates/page_delivery/after_finalized.html.eex, lib/oli_web/templates/page_delivery/prologue.html.eex
This PR increases the choices for number of attempts for graded pages, including an "Unlimited" option. 
I also took this opportunity to soften some of the UX language around "graded assessment", using "scored page" instead. 
For some reason there are a bunch of formatting changes here, but mainly the changes were to customize the curriculum editor dropdown for more options, and to handle "unlimited" in a couple of places that students encounter (the prologue view)
=> [ENHANCEMENT] MER-1162 allow unlimited attempts

CHANGELOG.md, lib/oli_web/live/insights/table_header.ex
Closes #2571 
This PR fixes the heading alignment problem.  There were some redundant `<th>` elements being added, I think maybe from a bad merge.  Tested locally and it resolves the problem.
=> [BUG FIX] Remove redundant table header 

CHANGELOG.md, lib/oli/rendering/content/html.ex, test/oli/rendering/content/example_content.json
This PR fixes an issue where table caption rendering throws an internal server error.
The problem here is table is directly rendering the caption content as text and not accounting for a richer content elements such as "p". The solution is to use the caption rendering function already implemented in the module.
Closes #2615
Closes #2562
=> [BUG FIX] fix an issue where table caption rendering throws an error

assets/styles/authoring/image-upload.scss, assets/styles/authoring/index.scss, lib/oli/delivery/sections/section.ex, lib/oli/utils/s3_storage.ex, lib/oli_web/common/source_image.ex, lib/oli_web/controllers/api/product_controller.ex, lib/oli_web/controllers/brand_controller.ex, lib/oli_web/live/common/card_listing.ex, lib/oli_web/live/products/details/image_upload.ex, lib/oli_web/live/products/details_view.ex, lib/oli_web/templates/delivery/enroll.html.eex, lib/oli_web/templates/delivery/open_and_free_index.html.eex, lib/oli_web/views/api/product_view.ex, lib/oli_web/views/delivery_view.ex, priv/repo/migrations/20220524233403_update_sections_add_cover_image.exs, test/oli_web/controllers/api/product_controller_test.exs, test/oli_web/controllers/delivery_controller_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/live/products_test.exs, test/support/factory.ex
[MER-462](https://eliterate.atlassian.net/browse/MER-462)
- Adds an image section in the product overview page, for uploading/updating the product image. At
this moment, this is only available at the product level. New sections inherit the image from the parting product.
- When a user-uploaded image is provided, it replaces the default `/images/course_default.jpg` image.
Default - for all products that have no current image
Once an image is uploaded
=> [MER-462] Add product image upload and make it accesible through API

lib/oli/delivery/paywall.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/products/details/edit.ex, lib/oli_web/live/products/payments/discounts/form.ex, lib/oli_web/live/products/payments/discounts/products_index_view.ex, lib/oli_web/live/products/payments/discounts/show_view.ex, lib/oli_web/live/products/payments/discounts/table_model.ex, lib/oli_web/router.ex, lib/oli_web/templates/institution/show.html.eex, test/oli/delivery/paywall_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/live/discounts_live_test.exs, test/oli_web/live/products_test.exs
[MER-1205](https://eliterate.atlassian.net/browse/MER-1205)
When did the suppress paywall feature, I **wrongly** assumed that a product could only have one discount. This changes fix that, being able to create more than one discount for the same product (but different institution). 
Added an index view to list the discounts for a product, and tweak the discounts show view + form to contemplate this new scenario as well. Also fixed some date format on the enrollments csv export.
=> [BUGFIX] [MER-1205] Product discounts fix

assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts
use the component schema as the source of truth always about the value type of the variable
=> [BUGFIX] adaptive author setting the wrong type in case of invalid value

assets/src/adaptivity/scripting.ts
previously it was thought that 4 decimal places would be fine for a universal rounding when displaying numbers as text in text flows, but this was problematic with things like 1e-10 showing up as 0 . There are other cases, too many, so the best thing to do is *not* do it at all automatically, and require the author to specifically do it when printing using `{round(stage.foo.value, 4)}`
=> [BUGFIX] PMP-2858 JAN-1707 don't auto round any numbers

assets/src/apps/page-editor/PageEditor.tsx, assets/src/components/activity/InlineActivityEditor.tsx, assets/src/components/common/ThreeStateToggle.tsx, assets/src/components/editing/elements/blockcode/BlockcodeElement.tsx, assets/src/components/logic/ActivityTypeSelection.tsx, assets/src/components/misc/DarkModeSelector.tsx, assets/src/components/resource/Tags.tsx, assets/src/components/resource/editors/Editors.scss, assets/src/components/resource/objectives/ObjectivesSelection.tsx, assets/src/data/content/model/elements/factories.ts, assets/src/data/content/model/elements/types.ts, assets/src/data/content/writers/html.tsx, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex
This PR fixes a few different high-priority issues including:
- Code elements were not properly being converted from v1 to v2 model rendering logic did not properly account for existing v1 code element newlines
- We will want to add this sort of logic to the runtime content migration infrastructure once we finally spec out activity schemas
- Some editors may fire an edit event before the PageEditor has initializes the persistence strategy which crashes the page, specifically monaco editor repeating the value it was given on first render. This PR add logic to only allow the update functions to run if editMode is true.
- Torus was using React production libraries in development making it difficult to identify the issue. This re-enables development libraries in Mix.env() == :dev
- …
=> [BUG FIX] Fix v1 codeblocks

CHANGELOG.md, lib/oli/authoring/editing/objective_editor.ex, lib/oli/publishing.ex, test/oli/editing/objective_editor_test.exs
Might close #2625 
This PR adds special handling of cascading an objective deletion to banked activities.   This impl was never updated to account for banked activities when they were introduced.
=> [BUG FIX] Cascade deletion of objectives to banked activities

lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/views/layout_view.ex
Fixes an issue where `Mix.env()` is unavailable in releases to check for dev mode
=> [BUGFIX] fix an issue where mix is unavailable in releases

assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx
for Multiple Selection MCQ, if nothing was selected by default, then undefined was getting set for 'SelectedChoice' & 'SelectedChoiceText'. They should be set to '-1' and '' respectively. 
We were already setting this to  '-1' and '' on props.onInit but later during 'handleMultipleItemSelection()', it was getting overriden.
=> PMP-2860 | JAN-1709

CHANGELOG.md, assets/src/apps/page-editor/PageEditor.tsx
Closes #2628 
This PR fixes the ability to edit the title of the basic page.  Title editing takes a different client-side event path, and also kicks off the save request in a different spot than content editing. Recent changes that added the "version" prop were not being included in this title editing path.
=> [BUG FIX] fix title editing

assets/src/components/editing/editor/Editor.tsx
Closes #2520 
This PR fixes a problem where pasting HTML into activities breaks the editor component in that activity. 
This is a strange issue as pasting some HTML directly into the page often works, but then the exact same clipboard contents pasted into an activity breaks the activity.  For LearnLab, I'm leaning towards simply disabling HTML pasting for the moment until we can fully support it across all components.
=> [BUG FIX] Disable html pasting

lib/oli/activities/realizer/selection.ex, priv/schemas/v0-1-0/activity-bank-selection.schema.json
This PR fixes a problem where one cannot edit selections, due to purpose type being required. 
I've also allowed purpose type to be missing from the server perspective when it attempts to parse an existing one.
=> [BUG FIX] Relax purpose constraint on selections

CHANGELOG.md, assets/src/apps/bank/ActivityBank.tsx, assets/src/apps/page-editor/PageEditor.tsx, assets/src/components/resource/objectives/ObjectivesSelection.tsx, assets/src/components/resource/objectives/sort.ts, lib/oli_web/live/objectives/actions.ex, lib/oli_web/live/objectives/objective_entry.ex
This PR removes the "Break down" feature, allowing sub objectives to be immediately added.   It also improves the UI for attaching, to preserve the tree structure in its rendering. 
Closes #1859
=> [ENHANCEMENT] simplify and improve UX around objectives

assets/src/components/resource/editors/ContentOutline.modules.scss
Closes #2542 
Adjusts the contrast of the innermost portion of the outline toggle button, making it black in light mode, and white in dark mode.
=> [BUG FIX] Adjust contrast of outline toggle

assets/src/components/resource/objectives/ObjectivesSelection.tsx
This PR makes another incremental improvement in the learning objectives picker.  It indents the child objectives, thus removing the need to display the parent label within the child (which is removed also).
The net gain is a much more "tree-like" display:
=> [ENHANCEMENT] Improve lo dropdown

lib/oli/activities.ex, lib/oli/activities/activity_registration.ex, lib/oli_web/controllers/activity_manage_controller.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/activity_manage/index.html.eex, priv/repo/migrations/20220615133201_add_global_visibility.exs
Closes #2632 
This PR introduces a new "Global Visibility" flag for registered activities.  This boolean controls whether or not an activity type is visible to all authors (aka "globally visible") from the list of "Advanced Activities" in an author's Project Overview.  If set to `false` the activity will only be visible to admins. 
With this mechanism, we can hide the "Adaptive Activity", the "OLI Embedded" for all courses.  We can also hide "Image Coding" activity, but allow an admin to perform the "opt-in" and change the availability on a case by case basis.
=> [ENHANCEMENT] introduce activity type visibility

assets/src/components/editing/editor/Editor.tsx, assets/src/components/editing/elements/cite/CiteElement.tsx, assets/src/components/editing/elements/image/ImageSettings.tsx, assets/src/components/editing/elements/inputref/InputrefElement.tsx, assets/src/components/editing/elements/link/LinkElement.tsx, assets/src/components/editing/elements/popup/PopupElement.tsx, assets/src/components/editing/elements/webpage/WebpageSettings.tsx, assets/src/components/editing/elements/youtube/YoutubeElement.tsx, assets/src/components/editing/toolbar/Toolbar.tsx, assets/src/components/editing/toolbar/buttons/DropdownButton.tsx, assets/src/components/editing/toolbar/editorToolbar/EditorToolbar.tsx, assets/src/components/editing/toolbar/editorToolbar/Inlines.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/BlockInsertMenu.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/BlockSettings.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/BlockToggle.tsx, assets/styles/authoring/toolbar.scss
Closes #2613 
This PR introduces vertical orientation support for the popup toolbar infrastructure.  It uses this vertical orientation for the core toolbar, so that when it appears it never hides user content. 
I also detected a bug and fixed the ability to show the "context specific" portion of the toolbar.  For Lists, Headings and CodeBlocks the toolbar was supposed to show more buttons for those items.  That now works again.
=> [ENHANCEMENT] orient toolbar vertically

lib/oli_web/controllers/activity_bank_controller.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/controllers/resource_controller.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/insights/insights.ex, lib/oli_web/live/objectives/objectives.ex, lib/oli_web/live/products/products_view.ex, lib/oli_web/live/qa/state.ex
Closes #2626 
This PR sets the `<head><title/></head>` with text that provides more context, so that browser tabs can be more easily navigable.  
Prior to this change, the following screens used text:
Project Overview: OLI Torus
Objectives: OLI Torus
Activity Bank: OLI Torus
Curriculum: Curriculum
Editing a page: OLI Torus
Review: OLI Torus
Products: Products
Publish: OLI Torus
Insights: OLI Torus
After this change, these use:
Project Overview: Overview | Project Title
Objectives: Objectives | Project Title
Activity Bank: Activity Bank | Project Title
Curriculum: Curriculum | Project Title
Editing a page: Edit | Page Title
Review: Review | Project Title
Products: Products | Project Title
Publish: Publish | Project Title
Insights: Insights | Project Title
=> [ENHANCEMENT] provide more context in tab content

assets/src/components/activities/adaptive/manifest.json, assets/src/components/activities/check_all_that_apply/manifest.json, assets/src/components/activities/file_upload/manifest.json, assets/src/components/activities/image_coding/manifest.json, assets/src/components/activities/likert/manifest.json, assets/src/components/activities/multi_input/manifest.json, assets/src/components/activities/multiple_choice/manifest.json, assets/src/components/activities/oli_embedded/manifest.json, assets/src/components/activities/ordering/manifest.json, assets/src/components/activities/short_answer/manifest.json, assets/src/components/content/add_resource_content/AddActivity.tsx, assets/src/components/content/add_resource_content/AddResourceContent.modules.scss, assets/src/components/content/add_resource_content/AddResourceContent.tsx, assets/src/components/content/add_resource_content/NonActivities.tsx, assets/src/components/content/add_resource_content/ResourceChoice.tsx, assets/src/components/resource/editors/AddResource.tsx, assets/src/data/content/editors.ts, lib/oli/activities.ex, lib/oli/activities/activity_map_entry.ex, lib/oli/activities/activity_registration.ex, lib/oli/activities/manifest.ex, priv/repo/migrations/20220617195405_add_petite_label.exs, test/oli/delivery/attempts_test.exs, test/oli/registrar_test.exs
This PR reworks the popup UI that allows inserting new content items and activities. 
https://user-images.githubusercontent.com/7431756/174826148-fed3920e-07ec-49c4-a45c-c76283242e95.mov
The above is a screen recording of the new UX in action.  On the left-hand side it presents a dedicated space for "non activities", and the right-hand side contains a panel for the activities present.  As the user mouses over the choices, there is some color changing during "hover" and a "tooltip" type string that displays for the "active" item.  This tip resets back to the default some seconds after it is cleared. 
This UX was designed with an eye towards future scalability as we add more and more activities.  When we reach the ability to display more than nine activities, we will augment this UX with a …
=> [ENHANCEMENT] Improve UX for inserting new content items

priv/repo/migrations/20220616184621_add_project_to_snapshots.exs
I verified that analytics queries do not break when `project_id` field contains nil values.  They don't work, but they don't break.
=> [BUG FIX] Remove setting of project_id during migration

config/dev.exs, config/test.exs, lib/oli/publishing.ex, lib/oli/publishing/part_mapping_refresh_adapter.ex, lib/oli/publishing/part_mapping_refresh_async.ex, lib/oli/utils/db_seeder.ex, priv/repo/migrations/20220615201219_remove_part_mapping_refresh_trigger.exs, test/oli/publishing_test.exs, test/support/part_mapping_mock_adapter.ex
[MER-1223](https://eliterate.atlassian.net/browse/MER-1223)
- Reduces significantly the user wait time when publishing a project. The triggers that updated the `part_mapping` materialized view are dropped, in favor of running them asynchronously through spawning in elixir.
This does not completely fix the performance issue in regards to scaling optimizations, since the update will still occur and take the same database execution time. However we decided to fix that separately by tackling how we handle the revision content. 
The user wait time for a publication of a single new graded page goes down from ~ 4000ms to ~ 5ms when ran locally.
=> [MER-1223] Improve publishing a project waiting time

assets/src/components/common/Formula.tsx, assets/src/components/common/MathJaxFormula.tsx, assets/src/components/editing/editor/modelEditorDispatch.tsx, assets/src/components/editing/elements/callout/CalloutElement.tsx, assets/src/components/editing/elements/callout/calloutActions.ts, assets/src/components/editing/elements/formula/FormulaEditor.tsx, assets/src/components/editing/elements/formula/FormulaModal.tsx, assets/src/components/editing/elements/formula/FormulaToolbar.tsx, assets/src/components/editing/elements/formula/formulaActions.tsx, assets/src/components/editing/toolbar/editorToolbar/Inlines.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/blockInsertOptions.ts, assets/src/data/content/model/elements/factories.ts, assets/src/data/content/model/elements/types.ts, assets/src/data/content/model/schema.ts, assets/src/data/content/writers/html.tsx, assets/src/data/content/writers/writer.tsx, assets/styles/authoring/formula.scss, assets/styles/authoring/index.scss, assets/styles/common/elements.scss, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/content/plaintext.ex, lib/oli_web/templates/layout/authoring.html.leex, priv/schemas/v0-1-0/content-element.schema.json, test/oli/rendering/content/example_content.json, test/oli/rendering/content/html_test.exs, test/oli/rendering/content/plaintext_test.exs
Adds the ability to author formulas in the slate editor.
This PR removes the "richtext" formula type and adds a new "callout" element that can be used for the same purpose. This was to make the code less complex and allowed a nicer authoring experience since we can now edit callouts inline in the main editor instead of in a popup window.
To edit formulas:
- Open a core-authoring lesson, place your cursor in the editor
- Choose the insert formula option under either the inline or the block menu
- Click the placeholder formula that appears
- Edit the formula in the popup window in either latex or mathml
To edit callouts
- Open a core-authoring lesson, place your cursor in the editor
- Choose the insert callout option under either the inline or the block menu
- Type and optionally use …
=> [MER-1201] Formula editing

lib/oli_web/controllers/resource_controller.ex
Closes #2732 
Root cause was the feature that added section-level ability to disable numbering did not provide the assign that controls this to the authoring preview template.  Both authoring and delivery leverage a bit of shared infrastructure for rendering (in this case the links for containers).
This was easily reproducible: simply preview as an author a course that contains a container in the curriculum.  Using the 'prev' and 'next' links at the bottom of the previewed page, as soon as you navigate to a container page this error occurs.  Fixed by adding the assign: hardcoding it to `true`, since this is really an instructor feature.  This leaves numbering on for the author, but of course is still toggleable for the instructor in the section.
=> [BUG FIX] Add necessary assign for authoring preview templates

lib/oli_web/live/objectives/objectives.ex
Closes #2673 
Changes sort order allows newly created objectives to appear at top of list
=> [ENHANCEMENT] Change sort order, which changes where new objectives appear

config/config.exs, config/dev.exs
Fixes an issue where refresh adapter was only being configured in dev environment by setting the configuration in `config.exs` so that it is compiled for all environments.
=> [BUG FIX] make refresh adapter config available in prod

lib/oli_web/controllers/payment_controller.ex, test/oli_web/controllers/api/payment_controller_test.exs
[MER-1210](https://eliterate.atlassian.net/browse/MER-1210)
- Fixes section cost updates not being reflected for students. 
Currently the section cost has been ignored, and when paying as a student, the blueprint's cost it's used instead. This changes that to always use the section's cost. (which will be the same as the product's unless updated by an admin).
As discussed with @darrensiegel, this does remove the ability to update all sections' cost at the product level.
However discussing with @jrissler we decided to prioritize this fix, and separately work on a feature to batch-update section costs.
New ticket for implementing a product-wide update of costs: https://eliterate.atlassian.net/browse/MER-1292
=> [MER-1210] Fix section cost changes not updating for students

lib/oli/publishing/part_mapping_refresh_async.ex
[MER-1297](https://eliterate.atlassian.net/browse/MER-1297)
- Attempts to fix the part_mapping view not being refreshed on project publication updates
This replaces `Task.async` for `Task.start`
From the [elixir docs](https://hexdocs.pm/elixir/1.13/Task.html#module-dynamically-supervised-tasks): 
> ..async tasks link the caller and the spawned process. This means that, if the caller crashes, the task will crash too and vice-versa. This is on purpose: if the process meant to receive the result no longer exists, there is no purpose in completing the computation.
>
One reason for the refresh not being executed could be that process running the publication update is finishing before the spawned process that runs the refresh. 
From the[ Task.start …
=> [MER-1297] Attempt fix for part mapping refresh not being executed

lib/oli_web/telemetry.ex, mix.exs
Remove the prometheus reporter to determine if this is indeed causing the memory leak and crashes
=> [PERFORMANCE] Remove prometheus telemetry reporter

priv/repo/migrations/20220629134948_update_snapshots_add_project_ids.exs
[MER-1288](https://eliterate.atlassian.net/browse/MER-1288)
- Updates snapshots table to add `project_id`s
For reference, we're dropping indices and re-creating them after the update, which is faster than having them update on each row update.
However the biggest improvement comes from removing an unnecessary self join on the update query when we first introduced it.
**Previous query**
```
UPDATE snapshots 
SET project_id = sect.base_project_id 
FROM snapshots snap 
LEFT JOIN sections sect ON snap.section_id = sect.id;
```
**New query**
```
UPDATE snapshots
SET project_id = sect.base_project_id
FROM sections sect WHERE sect.id = snapshots.section_id;
```
For a production dump with 14.235.739 records it took ~8 min locally.
=> [MER-1288] Add project ids to snapshots

lib/oli/resources/page_content.ex, lib/oli/utils.ex
This ensures any group id given by the adaptive player is convert to a string for the server side logic/database insertion.
=> [BUG FIX] ensure group id number is a string

assets/src/components/resource/editors/ActivityBankSelectionEditor.scss
Fixes an issue where the activity bank selection editor was wider than other activities in the editor.
=> [BUG FIX] fix activity bank selection width

assets/src/adaptivity/scripting.ts
currently the author is triggering this call on change of a text input for rules, so the moment you type a opening '{' it crashes;
will look into a better solution later;
=> [BUGFIX] throwing an error too harsh (crashes author sometimes)

lib/oli/authoring/editing/page_editor.ex
Simple fix, just use the raw, untransformed content (for now).
=> [BUG FIX] Fix preview when an activity fails to eval

lib/oli_web/controllers/lti_controller.ex, lib/oli_web/controllers/session_controller.ex, lib/oli_web/router.ex
[MER-1312](https://eliterate.atlassian.net/browse/MER-1312)
Fixes an issue where some endpoints are not creating the session with the correct user or author cookie and instead using a generic one, causing issues as the same cookie is used with the wrong pow config.
Added the missing `authoring` and `delivery` plugs that set the correct cookies and made sure all endpoints now have at least one of those two (or the `_protected` ones) when they are necessary.
Also changed the signout logic to log out only the correct account and not all of them (as they are independent).
=> [BUGFIX] Persistent session cookie handling

assets/src/adaptivity/scripting.ts, assets/test/adaptivity/scripting_test.ts
Observation list is an array of object however it is saved as string because that's how Ever App expects the data. The getExpressionStringForValue() was trying to convert the string to array based on the ',' present in the string and after that the ""' were getting replaced with '\\\\'. Due to this the observation had invalid data causing the observation to disappear from the list.
=> PMP-2910 | JAN-1759 | Ever App Observation getting disappear

assets/src/adaptivity/scripting.ts
causing some variables like `app.spr-app-whatever.foo` to register as having multiple prefixes
=> [BUGFIX] needed to escape the dot to include it

lib/oli/utils/db_seeder.ex, lib/oli_web/live/curriculum/container/container_live.ex, test/oli_web/live/curriculum/container_test.exs
[MER-1324](https://eliterate.atlassian.net/browse/MER-1324)
After locking the page and broadcasting the `lock_acquired` message, the `handle_info` in `ContainerLive` was going to the users table with the author id, so if you were other author looking at the same project, you were seeing the user's name that corresponds to the author id. Doesn't even make sense to have that there since it's an author view.
=> [BUGFIX] [MER-1324] Replace get_user to get_author

lib/oli_web/live/projects/projects_live.ex, lib/oli_web/live/projects/table_model.ex, test/oli_web/live/projects_live_test.exs, test/support/factory.ex
[MER-985](https://eliterate.atlassian.net/browse/MER-985)
- Show status column on projects index page to normal authors (like it is shown to admins).
- Display "Show deleted projects" filter to authors.
- Add tests for the ProjectsLive view.
=> [MER-985] Display status to authors on projects page

priv/schemas/v0-1-0/content-element.schema.json
Had a bug in the schema when I implemented the formulas, this cleans it up.
Before any type that matched the formula shape would have been accepted. ie:
```
{
type: 'formulazzzzzz`,
subtype: 'latex',
src: 'hi'
}
```
Now, type has to be formula or formula_inline as intended
=> [MER-1337] Fixed formula schema bug

assets/src/components/editing/editor/modelEditorDispatch.tsx, assets/src/components/editing/elements/callout/calloutActions.ts, assets/src/components/editing/elements/list/listActions.ts, assets/src/components/editing/slateUtils.tsx, assets/src/components/editing/toolbar/editorToolbar/ListStyleToggle.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/BlockSettings.tsx, assets/src/data/content/model/elements/types.ts, assets/src/data/content/writers/html.tsx, assets/styles/common/index.scss, assets/styles/common/list.scss, assets/styles/themes/authoring/default.scss, lib/oli/rendering/content/html.ex, priv/schemas/v0-1-0/content-element.schema.json
Adds ability to set your bullet-style on ordered and unordered lists. While in core-authoring editor, there is a new menu option for lists that opens a sub-menu with the different styles.
The content-model was changed to add a style prop to the list element
```
{
type: 'ul',
style: 'square'
...
}
```
Fixes #2743
Example styles:
Example editor controls:
=> [MER-1308] List styling

lib/oli/delivery/attempts/manual_grading.ex
determines based on the existence of rules, just like in evaluate; 
also update the part records with evaluation status and time during finalization
=> [BUGFIX] MER-1329 adaptive scoring should not be normalized

lib/oli/authoring/editing/activity_editor.ex, lib/oli/authoring/editing/container_editor.ex, lib/oli/resources/resource_type.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/curriculum/entries/actions.ex, test/oli/editing/container_editor_test.exs, test/oli_web/controllers/resource_controller_test.exs, test/oli_web/live/curriculum/container_test.exs
[MER-1216](https://eliterate.atlassian.net/browse/MER-1216)
- Adds ability to duplicate a page within a project, in the curriuculum overview page.
We're running a deepy copy of resources revisoins of the page (and of its embedded activities). 
The option is only enababled for pages, not including adaptive ones, which are going to be worked on separately.
=> [MER-1216] Add duplicate page action in project curriculum

lib/oli_web/live/common/utils.ex, lib/oli_web/live/grades/gradebook_table_model.ex, lib/oli_web/live/progress/page_attempt_summary.ex, lib/oli_web/live/progress/student_resource_view.ex, lib/oli_web/live/progress/student_view.ex, lib/oli_web/templates/page_delivery/page.html.eex, lib/oli_web/views/page_delivery_view.ex, test/oli_web/common/utils_test.exs, test/oli_web/live/gradebook_view_live_test.exs, test/oli_web/live/progress_live_test.exs, test/oli_web/live/student_view_live_test.exs, test/support/test_helpers.ex
[MER-1206](https://eliterate.atlassian.net/browse/MER-1206)
- Formats score for limiting to two decimal points in the displaying of scores in the following pages:
- Student progress view
- Student resource progress view
- Section's Gradebook view
- Attempt review (student and instructor)
When editing a resoure's score manually, a number with N decimals numbers is accepted, but following the same logic as everywhere else, the number get's rounded up and limited to two significant decimals for display.
=> [MER-1206] Display only two decimal points in grading scores

assets/src/components/activities/likert/LikertAuthoring.tsx, assets/src/components/activities/likert/LikertDelivery.tsx, assets/src/components/activities/likert/Sections/LikertTable.tsx, assets/src/components/activities/likert/actions.ts, assets/src/components/activities/likert/schema.ts, assets/src/components/activities/likert/utils.ts
This shows choice value numbers along the footer of the likert table on delivery. Also adds an editable option to allow authors to specify descending numbering from left to right.
=> Add numbering to likert items

CHANGELOG.md, lib/oli/delivery/activity_provider.ex, lib/oli/delivery/activity_provider/result.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli/resources/page_content.ex, mix.exs
This PR restores the ability to create attempts for pages that contain activity bank selections.  The fix here is to provide to the page lifecycle hierarchy creation code a mapping of realized activity resource ids to the original bank selection id. In conjunction, the code in `PageContent.activity_parent_groups` has been updated to look for activity bank selections, and add those as distinct entries (with a special key that won't conflict with resource ids) in the returned map.  With those two changes, the attempt creation code can then properly determine if a realized activity that come from a bank selection was in a group or a survey.
=> [BUG FIX] Fix activity bank selection

lib/oli/analytics/common.ex
Fix #2787 by changing queries for By Objective to aggregate over distinct (user, activity) pairs, which seems to be the desired statistic. Verified it works on test case from issue.
=> [BUG FIX] Correct By Objective analytics (#2787)

CHANGELOG.md, lib/oli/analytics/datashop/elements/meta.ex, lib/oli/utils/db_seeder.ex, lib/oli/utils/seeder/student_attempt_seed.ex, mix.exs, test/oli/analytics/datashop_test.exs, test/oli/delivery/attempts/browse_updates_test.exs, test/oli/delivery/submission_test.exs
Fixes an issue where the user_id for guest users is empty datashop export. This should be set to the unique sub of the user in order to identify the separate events for a single anonymous user.
The bulk of the work here is getting a unit test to prove the fix. The unit test simulates users working through an activity and generating data events.
Closes: #2819
=> [BUG FIX] Datashop missing user id for guest

assets/styles/delivery/page_delivery/page.scss, assets/styles/delivery/variables.scss, assets/styles/themes/delivery/default.scss, lib/oli_web/templates/page_delivery/page.html.eex, test/oli_web/controllers/page_delivery_controller_test.exs
Changes rendering so that pages do not show learning objectives on scored (graded) pages unless in review mode.
Some users commented that the objectives box background color didn't match the rest of the theme, so I tweaked the color here too.
Closes #2853
=> [BUG FIX] Hide learning objectives on scored pages

CHANGELOG.md, assets/src/components/activities/common/delivery/inputs/NumericInput.tsx
Disables the changing of numeric input value using the scroll wheel in certain browsers.
Closes #2852
=> [BUG FIX] disable scroll wheel on numeric input

lib/oli/institutions.ex, lib/oli/institutions/institution.ex, lib/oli_web/controllers/institution_controller.ex, priv/repo/migrations/20220722020459_enable_remove_institution.exs, test/oli/institutions_test.exs, test/oli_web/controllers/institution_controller_test.exs
Fixes an issue where institution deletion may fail due to all the fk constraints. This PR fixes that by allowing a "soft" deletion, simply setting a status flag and hiding the deleted institutions from the manage list.
Closes #2824
=> [BUG FIX] Soft delete institution

assets/src/apps/delivery/components/ActivityRenderer.tsx
hopefully this will help with the race condition, the current activity should not need to get a context change event because it is new and will get the init event instead.
also this will remove the extra call to check complete in history mode
=> [Bugfix] event cleanup JAN-1827

lib/oli/delivery.ex, lib/oli/delivery/paywall.ex, lib/oli/delivery/paywall/providers/stripe.ex, lib/oli_web/controllers/payment_providers/stripe_controller.ex, test/oli/delivery/paywall/providers/stripe_test.exs, test/oli/delivery/paywall_test.exs, test/oli_web/controllers/payment_providers/stripe_controller_test.exs
[MER-1321](https://eliterate.atlassian.net/browse/MER-1321)
When we worked on #2726 and switched from calculating costs from product to always using the section cost, we missed updating the same logic which was duplicated in the Stripe provider. 
In the reported bug, when an admin updated the cost of a section that parts from a product:
- User would see e.g. 25 USD when paying, although Stripe would charge 50 USD
- This happened because `PaymentController.make_payment` used `Section.amount`, and `Stripe.init_payment` was still doing the determine_product + cost calculation to determine the amount.
=> [MER-1321] Fix stripe charging incorrect amount on section payment

lib/oli_web/live/delivery/remix_section.ex, test/oli_web/live/remix_section_test.exs
[MER-611](https://eliterate.atlassian.net/browse/MER-611)
Fixes admin being redirect to a new student/instructor session after saving changes on the section remix page.
=> [MER-611] Fix wrong admin redirection on remix edit save

assets/src/adaptivity/scripting.ts, assets/src/components/parts/janus-input-number/InputNumber.tsx
Additional debugging in this issue has come up with the following observations:
When I'm seeing the bug occur, in defaultGlobalEnv from scripting.ts, the value of the input is set to NaN, and it continues to be NaN long after the initial render, so it doesn't seem to be a case of the component not getting an updated value.
I put some debugging statements into evalScript and we're running this script:
`let {q:1461614198663:472|stage.VolcanicCChange.value} = NaN;`
When the bug occurs, it runs after this script which sets it to the correct value.
`let {q:1461614198663:472|stage.VolcanicCChange.value} = 4.7;`
So something is explicitly setting the value to NaN
Sometimes that script runs before, and sometimes it runs after the debug message:
DECK HANDLE READY (ALL ACTIVITIES DONE INIT) 
I've …
=> [JAN-1827] Fixes one cause a race condition

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
when the history mode flag is triggered it happens before the activity tree is updated, so it tries to re-render the current screen in history mode then the previous, but if there are layers involved it gets messy that way
=> [BUGFIX] history mode flag and state tree out of sync

assets/src/phoenix/keep-alive.ts, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/templates/layout/live.html.leex, lib/oli_web/views/layout_view.ex
[MER-1368](https://eliterate.atlassian.net/browse/MER-1368)
Improves the calls to the keep alive endpoint by:
- Reducing frequency from 1 minute to 15 (default Pow refresh time)
- Moving keep-alive script to liveviews only, instead of loading them on every page.
=> [MER-1368] Persistent session keep alive improvements

lib/oli/delivery/paywall.ex, test/oli/delivery/paywall_test.exs
[MER-1389](https://eliterate.atlassian.net/browse/MER-1389)
Fixes the Paywall.section_cost_from_product/2 query retrieving all discounts for a product instead of limiting to a specific institution.
=> [MER-1389] Fix discounts being applied to all institutions

assets/src/components/activities/DeliveryElement.ts, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx, assets/src/components/activities/types.ts, lib/oli/rendering/activity/html.ex, lib/oli_web/live/manual_grading/rendered_activity.ex, test/oli/rendering/activity/html_test.exs, test/oli/rendering/survey/html_test.exs
when LiveView re-renders the markup the new connected callback was firing before the disconnected callback. also need to make sure that phx-update is set to "ignore". previously it was set to "none" which isn't a valid value. (without ignore it will latch onto any children with an id attribute and try to control its updates)
=> [BUGFIX] MER-992 MER-1332 manual graded activity preview doesn't always render

assets/src/components/editing/elements/blockcode/BlockcodeElement.tsx, assets/src/components/editing/elements/cite/CiteElement.tsx, assets/src/components/editing/elements/formula/FormulaEditor.tsx, assets/src/components/editing/elements/image/block/ImageElement.tsx, assets/src/components/editing/elements/image/block/ImagePlaceholder.tsx, assets/src/components/editing/elements/image/inline/ImageInlineElement.tsx, assets/src/components/editing/elements/link/LinkElement.tsx, assets/src/components/editing/elements/utils.tsx, assets/src/components/editing/elements/video/VideoEditor.tsx, assets/src/components/editing/elements/video/VideoPlaceholder.tsx, assets/src/components/editing/elements/webpage/WebpageElement.tsx, assets/src/components/editing/elements/youtube/YoutubeElement.tsx
Changes onEditModel to useEditModelCallback to be more consistent with hooks naming convention.
=> [CHORE] Change onEditModel to useEditModelCallback

lib/oli/delivery/attempts/core.ex, lib/oli_web/live/grades/gradebook_table_model.ex, lib/oli_web/live/grades/gradebook_view.ex, lib/oli_web/live/progress/student_resource_view.ex, lib/oli_web/live/progress/student_view.ex
This PR adds a feature to the gradebook that allows an instructor to set a student's score, manually, even in situations where the student never visited a page or completed at least one attempt.  
I had to change a join to a left_join to account for the possibility that no resource_attempt records exist.
=> [FEATURE] Set grades manually even for when a student hasn't visited or completed a page

CHANGELOG.md, lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli_web/templates/page_delivery/page.html.eex, test/oli_web/controllers/page_delivery_controller_test.exs
For #2374, change 'Submit Assessment' button label to 'Submit Answers' to avoid grade-related terminology. Use 'Submit Answers" rather than just 'Submit" so existing tests can continue to use presence/absence of unique string on page to distinguish scored assessments.
=> [BUGFIX] Change 'Submit Assessment' to 'Submit Answers' 

config/config.exs, lib/oli/application.ex, lib/oli/publishing.ex, lib/oli/publishing/part_mapping_refresh_async.ex, lib/oli/publishing/part_mapping_refresh_sync.ex, lib/oli/publishing/part_mapping_refresh_worker.ex
[MER-1323](https://eliterate.atlassian.net/browse/MER-1323)
Refactors the part_mapping materialized view refresh, by implementing an Oban worker that limits the amount of processes we trigger to refresh the view. 
In PR #2750 we introduced async tasks to refresh the publication, which could spawn N process at the same time. This implementation works, however since the materialized view is refreshed completely each time, we can improve it by avoiding locking the view with refresh operations that don't actually update the data.
=> [MER-1323] Oban setup for part_mapping view refresh

lib/oli/delivery/activity_provider.ex, lib/oli/delivery/activity_provider/attempt_prototype.ex, lib/oli/delivery/activity_provider/result.ex, lib/oli/delivery/attempts/core/activity_attempt.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli/delivery/page/page_context.ex, lib/oli/resources.ex, lib/oli/resources/revision.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/controllers/resource_controller.ex, priv/repo/migrations/20220802161855_retake_mode.exs, test/oli/delivery/activity_provider_test.exs, test/oli/delivery/attempts/hiearchy_test.exs, test/oli/delivery/attempts/optimized_hiearchy_test.exs, test/oli/delivery/attempts/retake_mode_test.exs, test/oli/delivery/attempts_test.exs, test/oli/delivery/submission_test.exs
This PR introduces the infrastructure to power "Targeted Retake Mode" - the ability for a graded page that allows multiple attempts to "pull forward" the state of activities that were answered correctly from previous attempts into new attempts. Essentially this allows a student that keep taking attempts, but only having to answer the questions that they got wrong in previous attempts. 
A key change here is the introduction of the `AttemptPrototype` module, and a corresponding refactoring of the `ActivityProvider` module, to having it yield its results as attempt prototypes.  The AP can now also take as input a list of existing attempt prototypes that constrain how the AP will realize activities.  Basically this is the mechanism that allows a selection bank to pick the same (partial or …
=> [FEATURE] Targeted retake mode, infrastructure only

assets/src/data/persistence/extrinsic.ts
this helps with an everapp race condition. everapps (observer) that are constantly polling the data previously might have executed a get request while a set request was still processing.
=> [Bugfix] PMP-2988 JAN-1836 user state queue

assets/src/phoenix/app.ts
Increase timeout of live socket to 60 sec so we can render a live view that's running a long query. After working on that query specific and improve it, we can low down again the socket timeout number.
=> Increase live socket timeout to 60 sec

assets/src/components/editing/elements/image/block/ImageElement.tsx, assets/src/data/content/model/elements/types.ts
img elements have a schema that accepts strings or numbers for width.
✔️ Both strings and numbers worked fine when rendered via elixir.
❌ The client side rendering only accepted numbers, and effectively ignored strings.
After this change, string or number widths work in both cases.
=> [MER-1340] Accept string based widths on images

assets/src/components/editing/editor/normalizers/normalizer.ts
These normalizers:
```
spacesNormalize(editor, node, path);
blockNormalize(editor, node, path);
codeNormalize(editor, node, path);
listNormalize(editor, node, path);
tableNormalize(editor, node, path);
```
Would never run on root elements because they were in that else block, I don't think that was intentional.
=> [BugFix] Normalize top level elements.

lib/oli/delivery/attempts/core.ex, lib/oli/grading.ex, lib/oli_web/live/grades/gradebook_view.ex, test/oli/delivery/attempts_test.exs
The query to retrieve the resource access records for all graded pages, for a window of 25 users was taking long enough time to trip the 10 second Phoenix socket timeout during the Gradebook LV init. 
Analyzing the query showed that it had:
```
"Startup Cost": 153.25,
"Total Cost": 270.65
```
This was primarily due to how the query accounted for the specific set of users, given the join through section slug to SPP to PR to revision. 
I simplified and reworked the join approach to lower that to:
```
"Startup Cost": 8.53,
"Total Cost": 41.99
```
=> [PERFORMANCE] Optimize resource_access fetch with gradebook LV

.github/workflows/build.yml, assets/src/components/activities/likert/Sections/LikertTable.tsx
GH actions does not allow PRs from forked repositories to access secrets needed to auto format. Therefore this PR changes the way the CI works so that auto-format job will only run if the necessary secret token is available. This auto-format job is no longer a prerequisite to the ts-build-test because if automatic formatting is performed, then a new job will be kicked off in the CI from the newly created auto-format commit.
=> Fix GH actions build PR for forked repos

lib/oli_web/common/mathjax_script.ex, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/chromeless.html.eex, lib/oli_web/templates/layout/delivery.html.eex
Fixes #2918
A tweak to our mathjax configuration to support the \require command which lets the \cancel command work in this sample formula.
```
\require{cancel}\mathrm{mol}\;\mathrm{HCl}\;\mathrm{produced}\;=\;3\;\cancel{\mathrm{mol}\;{\mathrm H}_2}\;\times\;\frac{2\;\mathrm{mol}\;\mathrm{HCl}}{1\;\cancel{\mathrm{mol}\;{\mathrm H}_2}}\;\;=\;6\;\mathrm{mol}\;\mathrm{HCl}
```
After fix applied:
While at it, I put this config in a phoenix component since it was copy/pasted in 3 different html files.
=> [BUG] [MER-1403] [#2918] MathJax config fix.

assets/styles/authoring/model-editors.scss
Fixes bug #2917 
I believe the real cause of the bug was the menu was in the top right of the entire table instead of the top right of the cell. Now, the menu will be in the cell as expected.
=> [BUG] [MER-1402] [#2917] Table settings menu in th

lib/oli/interop/ingest.ex, lib/oli/resources/page_content.ex, test/oli/interop/digest/31.json, test/oli/interop/digest/43.json, test/oli/interop/ingest_test.exs
This PR fixes a bibliography and citation rewiring bug whereby citation references in course page ingest are not being correctly rewired to point to bibliography entries ingested into the db.
=> [BUG] fix citation ingest rewire bug

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, test/oli/delivery/attempts/page_lifecycle_test.exs
Closes #2933 
This changes graded page finalization logic to only finalize and only roll-up the *latest* attempt for each activity present.  
This was never an issue for basic pages, given that there is no way to ever create a second attempt for an activity within the same page attempt.  Adaptive pages can do this, however.
=> [BUG FIX] Only finalize latest attempt for each activity

lib/oli/authoring/editing/container_editor.ex, lib/oli/resources/page_browse.ex, lib/oli/resources/page_browse_options.ex, lib/oli/resources/revision.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/curriculum/entries/actions.ex, lib/oli_web/live/curriculum/entries/delete_modal.ex, lib/oli_web/live/curriculum/entries/entry.ex, lib/oli_web/live/curriculum/entries/options_modal.ex, lib/oli_web/live/resources/pages_table_model.ex, lib/oli_web/live/resources/pages_view.ex, lib/oli_web/router.ex, lib/oli_web/templates/layout/_project_sidebar.html.eex, test/oli/resources/page_browse_test.exs
This PR adds a new view for authors which allows browsing, searching and filtering across all pages in a course, regardless of where (and if) they live inside of containers.  
This is really just an initial, base implementation.  I suspect we will want to do some/all of the following in future (small) PRs:
1. Add ability to create a new page from this view to allow authors to create pages outside of their curriculum.
2. Add ability to search "content" and not just titles of pages.
3. Add ability to filter by and see "deleted" pages, and undelete them.
4. Add ability to see which author made the most recent edit for all pages.
5. Show which objectives a page has attached to it.  
6. Indicate whether the page does not exist in the curriculum (aka "standalone pages")
=> [FEATURE] Add ability to browse all pages in a course project

assets/src/components/activities/types.ts
Adds optional field to part to hold the "explanation", the answer-revealing final feedback that will serve the function of multiple feedback in legacy OLI.
=> add explanation field to part

assets/src/components/media/manager/MediaManager.tsx, assets/src/components/media/manager/VideoUploadWarning.tsx, assets/src/components/media/manager/upload.ts, assets/src/data/persistence/media.ts, lib/oli_web/endpoint.ex
This increases our max file upload size from 20mb to 350mb, which is the maximum size we can currently do in chrome with our current architecture. Going beyond this would require us to upload the file in multiple parts to get around a string size-limitation in V8.
Mostly Fixes #2929
=> [MER-1409] [GH#2929] Increase max upload size

assets/src/components/resource/editors/Editors.tsx, assets/src/data/editor/PageEditorContent.ts
Fixes an issue where content cant be removed if there is only one top level element. The editor appears to already be resilient to a model with zero items by automatically creating a single structured content element if no elements exist in the model. If all items are removed from a page, a user can still use the insertion menu to add something.
Closes #2810
=> [BUGFIX] fix an issue where content cant be removed

lib/oli/activities/parse_utils.ex, test/oli/activities/parse_utils_test.exs
This PR makes the utility used to detect empty hints more robust. There was a case not detected where the item being considered had an atom-keyed `content` attribute but a string-keyed `model` attribute inside of it.  This case was being tripped by an ingested course. 
Without this fix I saw a handful of MCQs in this course that suggested a hint was available when there really weren't.
=> [BUG FIX] Improve empty hint detection approach

lib/oli/interop/ingest.ex, priv/repo/migrations/20220829172419_fix_part_mapping_refresh.exs, test/oli/publishing/part_mapping_refresh_test.exs
This PR fixes the part_mapping materialized view refresh to properly select the part `id` and `gradingApproach` attributes in a way that keeps them aligned.  The previous attempt at this was very very broken in that it allowed the resulting resultset to "shuffle" the part ids and grading approaches.  This was only detected because a duplicate part id for an activity crept into a Torus instance.  The part refresh query "mismatched" these two part ids with different grading approaches (one manual, one automatic) and attempted to insert this triple (part id, grading approach, revision id) into the part map.  That violated the unique index constraint on the combination of part_id and revision id being a unique combination.  The root cause of the problem was that multiple `jsonb_path_query` …
=> [BUG FIX] Prevent duplicate part ids in ingest, fix part mapping refresh

lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, test/oli/delivery/attempts/retake_mode_test.exs
Retake mode would likely break an adaptive page if enabled. This PR ignores retake mode when the page in question is an adaptive page.
=> [ENHANCEMENT] Ignore retake mode when enabled for adaptive pages

assets/src/components/editing/elements/definition/DefinitionToolbar.tsx, lib/oli/interop/ingest.ex, lib/oli/resources.ex, lib/oli/resources/revision.ex, lib/oli_web/live/history/details.ex, priv/repo/migrations/20220825105222_add_parameters.exs
This PR adds a new `parameters` field to `Revision` - to allow storage of learning objective parameters (for both skill and objective quasi-subtypes).  This PR pairs nicely with https://github.com/Simon-Initiative/course-digest/pull/84
=> [FEATURE] add parameters for objective ingest

lib/oli/delivery/attempts/core.ex, test/oli/delivery/attempts_test.exs
`Core.get_graded_resource_access_for_context/` can return `nil` records due to the structure of the query.  Take the case where no student has visited a graded page.  This query still returns a record for that singular graded page but the ResourceAccess is `nil`.   Lowest risk fix here is to filer out `nil` RAs in the where clause. 
Unit test that was added demonstrates this perfectly.  Without the change to the query, this new unit test fails.
=> [BUG FIX] Filter out nil ResourceAccess records

assets/src/components/common/Figure.tsx, assets/src/components/editing/elements/figure/FigureEditor.tsx, assets/src/data/content/model/elements/factories.ts, assets/src/data/content/model/elements/types.ts, assets/src/data/content/writers/html.tsx, assets/styles/authoring/figure.scss, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/content/plaintext.ex, priv/schemas/v0-1-0/content-element.schema.json, test/oli/rendering/content/example_content.json, test/oli/rendering/content/html_test.exs, test/oli/rendering/content/plaintext_test.exs
This changes the type of the "title" attribute of figure elements from a string to an array of SemanticChildren so we can represent rich-text within that title.
I did restrict the editor to inserting inline elements since that seemed like the intent of figure titles and what we want to encourage authors to use, but the underlying renderers do work with block content if imported content has any.
A couple examples of rendered output:
In editor mode:
Fixes #2960
=> [BUGFIX] Change figure titles from string to richtext.

priv/schemas/v0-1-0/content-element.schema.json
This PR expands the schema for `semantic-element-content` to include tables.  This is primarily so that tables can exist inside of figures.
=> [ENHANCEMENT] Allow tables within figures

assets/src/apps/Components.tsx, assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx, assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/file_upload/FileUploadDelivery.tsx, assets/src/components/activities/likert/LikertDelivery.tsx, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/oli_embedded/OliEmbeddedDelivery.tsx, assets/src/components/activities/ordering/OrderingDelivery.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/components/activities/vlab/VlabDelivery.tsx, assets/src/components/misc/AttemptSelector.tsx, assets/src/data/activities/DeliveryState.ts, assets/src/data/events.ts, lib/oli/activities/state/activity_state.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/page/page_context.ex, lib/oli/rendering/activity/html.ex, lib/oli/rendering/context.ex, lib/oli_web/controllers/api/attempt_controller.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/progress/page_attempt_summary.ex, lib/oli_web/router.ex
This PR adds the ability to review practice pages, including all historical activity attempts. 
The implementation here intentionally avoids any affect or risk to the adaptive page. 
During server side rendering of a page in review mode a new "AttemptSelector" will be rendered for every activitiy (that isn't an adaptive activity).  This allows then the user to see all available historical activity attempts and choose between them.  A fetch of that attempt's state and model is made, then the `initializeState` event for client side activities is used to switch the delivery element to that other attempt.  Client side eventing was needed here as my initial attempt to simply programatically set the `model` and `state` props was triggering a rendering problem that I could not figure out.
=> [FEATURE] Allow review of practice pages

lib/oli/analytics/datashop.ex, lib/oli/utils/db_seeder.ex, test/oli/analytics/datashop_test.exs, test/oli/datashop_test.exs
This PR changes the datashop export to use "date submitted" instead of the part attempt "date inserted" timestamp for ATTEMPT and RESULT pairs.
This does not fix/account for the issue that hints requested do not contain a date timestamp, and therefore hints will continue to use the "date inserted" timestamp (when a student accesses the page/resets the activity) instead of when they actually requested a hint.
=> [BUG FIX] use date submitted for datashop attempt result pairs

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, lib/oli/rendering/content/html.ex
This PR fixes two issues noticed during QA of the chemistry course:
1. Popup definitions were not rendering the term inline with any special markup. I added the `term` class which renders them now the same as regular terms (bold italic and green).
2. The CustomDnD activity was not working due to some underlying changes in how the multipart activity now correctly partitions choices between multiple dropdown components.  The migration tool now preprends the partId and a "_" in front of the choice values to make the overall id unique within the question.  The DnD question has to do this manually, every time on submission because those choice values are separately embedded with the HTML of the layout file.
=> [BUG FIX] fix dnd questions, rendering of popup term

assets/styles/common/elements.scss
This PR fixes a delivery style issue where a images which are represented as centered in authoring were being rendered aligned to the left. The fix here centers the image so that it matches what is displayed in authoring.
Authoring:
Before:
After:
=> [BUG FIX] center a figure-img in delivery

lib/oli/resources.ex
Certain usages of the `Oli.Resources.create_revision_from_previous` trigger a failure as the legacy field is being set as a struct, rather than as a map.  
To trigger this failure (without this PR in place) just try editing the JSON of a revision in the Revision History tool.  
This PR ensures that the previous legacy attr is converted to a map, when necessary.
=> [BUG FIX] Properly set legacy field

priv/repo/migrations/20220920205152_delete_publications_trigger.exs
This PR fixes a problem introduced (by me) back when the refresh mapping query was fixed to account for duplicate part ids and grading approaches.  The migration in that PR (https://github.com/Simon-Initiative/oli-torus/pull/2958) accidentally re-introduced the `published_resources` trigger to invoke the part mapping refresh, which is what is now causing publication to take > 30 seconds. 
I verified this locally by seeing the trigger there in pgAdmin, then deleting it.  The UPDATE... SET query went from taking 2.5 seconds locally to like 11 msec.
=> [PERFORMANCE] Remove trigger, again [MER-1442]

assets/styles/common/purpose.scss, assets/styles/delivery/page_delivery/page.scss, assets/styles/delivery/variables.scss, assets/styles/themes/preview/default.scss, lib/oli_web/templates/page_delivery/_objectives.html.eex
This PR adjusts some page delivery styles to accomplish:
1. Allow content to use a wider portion of the page. (by removing the hardcoded `770px` max width)
2. Remove block styling of examples to match Legacy Chaperone style
3. Use same block styling for attached objectives. 
4. Bump the font size of the content overall slightly bigger.
=> [ENCHANCEMENT] some style tweaks

lib/oli/delivery/attempts/core.ex, lib/oli/delivery/page/page_context.ex, lib/oli_web/controllers/page_delivery_controller.ex, test/oli/delivery/attempts_test.exs
This PR fixes an issue in the server-side rendering code of the adaptive page that used the `assigns.current_user` to get the  id and name of the student that is the current user.  This is the same code that is run for both "visitation" and "reviewing".  In a review mode, the `assigns.current_user` is the logged in instructor (if its an instructor reviewing an attempt) and not the actual student.  Worse, if the logged in user is just an admin, the `assigns.current_user` will be `nil`, which was triggering the "Internal Server Error". 
The fix here is to not rely on the `assigns.current_user` for student information relative to the attempt.  Instead, this PR introduces a new `user` attribute to the `PageContext` which, during review mode, is populated by looking up the student pinned to …
=> [BUG FIX] Allow users logged in strictly as an admin to review adaptive page attempts [MER-1459]

assets/styles/common/utils.scss, lib/oli/rendering/activity/html.ex, lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/manual_grading/rendered_activity.ex, test/oli/rendering/activity/html_test.exs, test/oli/rendering/survey/html_test.exs
this makes the manual grading table show a pointer on selectable items.
also the updates set to ignore actually broke the tabs, moved the ignore to the activity itself which seems to work still
=> [BUGFIX] PMP-3013 JAN-1857 manual grading issues

assets/styles/authoring/layout/workspace.scss, assets/styles/common/index.scss, assets/styles/common/section-views.scss
the manual scoring interface was displaying the adaptive activity in such a way that it would escape the container. this only occurred via LTI and not in direct delivery mode because the css was previously only implemented for authoring mode. when an instructor is accessing via LTI it is in delivery mode.
=> [BUGFIX] JAN-1857 activity preview covers scoring area

assets/src/components/activities/common/choices/delivery/ChoicesDeliveryConnected.tsx, assets/src/components/activities/ordering/OrderingDelivery.tsx
Closes #3021 
Root cause of the failure was the inclusion of `uiState.model` in the `useEffect` dependency.  After removing that, the problem was fixed.  I noticed two other issues, though:
1. Multiple choice and CATA activities were not shuffling their choices upon reset. 
2. Review mode view of the latest Ordering activity - when that latest activity is unsubmitted and has no interact - did not render choices (due to the database student input being empty).  
This PR fixes those two issues as well.
=> [BUG FIX] Fix ordering reset problem.

assets/styles/common/elements.scss
It was reported that latex formulas can overflow a table cell.  See this example:
https://tokamak.oli.cmu.edu/authoring/project/general_chemistry_i_fuwmp/resource/su9xt_laws_of_definite_and_multiple__qes3o
A simple fix here is to use `table-layout: auto` which sizes the columns based on content, allowing the formula to render. Example:
=> [BUG FIX] Use auto layout for tables

lib/oli/rendering/activity/html.ex
this is for "core" pages. I added a couple Single Response activities set to manual scoring and they would fail to render
=> [BuGFIX] JAN-1857 core activities were failing with nil historical_attempts

assets/styles/common/utils.scss, lib/oli/delivery/paywall.ex, lib/oli_web/controllers/payment_controller.ex, lib/oli_web/live/products/payments/create_codes.ex, lib/oli_web/live/products/payments/tabel_model.ex, lib/oli_web/live/products/payments_view.ex, lib/oli_web/router.ex, test/oli/delivery/paywall_test.exs, test/oli_web/controllers/api/payment_controller_test.exs, test/oli_web/live/payments_live_test.exs
[MER-744](https://eliterate.atlassian.net/browse/MER-744)
This PR mainly solves the error that was occurring when adding new payment codes for a product. Now, the payment codes table is updated when adding them.
Also, a button has been added to download newly generated payment codes to a .txt file.
=> [BUGFIX][MER-744] Display payment codes when generated

assets/src/components/activities/common/delivery/submit_button/SubmitButtonConnected.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/test/multiple_choice/mc_delivery_test.tsx
Closes #1584 
Removes the Submit button.  In graded context or in a survey selecting a choice simply saves their state to the server.  In a practice context (and not within a survey) auto submits the response.
=> [ENHANCEMENT] Remove MCQ submit button

assets/src/components/activities/common/delivery/inputs/NumericInput.tsx, assets/src/components/activities/common/delivery/inputs/TextInput.tsx, assets/src/components/activities/common/delivery/inputs/TextareaInput.tsx, assets/src/components/activities/common/delivery/persistence.ts, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/data/content/writers/context.ts, assets/src/data/content/writers/html.tsx, assets/test/short_answer/short_answer_delivery_test.tsx
This PR introduces the same "delay and coalesce" saving logic that we use in Authoring into the Single Response and Multi-Input delivery implementations. This should fix the second most impactful performance that we see in AppSignal (for Proton, at least)
Without this PR, every character that a student types into a text field generates a network request to save the full value of the text of that text field.  So, if the student types:
`My answer to this question contains several important points and demonstrates my complete lack of understanding`
The system would generate 112 network requests to incrementatlly save:
`M`
`My`
`My `
`My a`
`My an`
`My ans`
`My answ`
`My answe`
`My answer`
...and so on.
Depending on how quickly a student types, the number of total network requests with the …
=> [PERFORMANCE] delay and coalesce edits in input questions

assets/src/components/common/Popup.tsx, assets/src/components/editing/elements/common/AudioClipPicker.tsx, assets/src/components/editing/elements/common/InlineAudioClipPicker.tsx, assets/src/components/editing/elements/common/settings/AudioClipPickerSettings.tsx, assets/src/components/editing/elements/popup/PopupContentModal.tsx, assets/src/components/editing/elements/popup/PopupElement.scss, assets/src/components/modal/Modal.tsx, assets/src/components/modal/ModalDisplay.tsx, assets/src/data/content/model/elements/types.ts, assets/src/data/content/writers/html.tsx, assets/src/phoenix/app.ts, assets/styles/authoring/controls.scss, lib/oli/rendering/content/html.ex, priv/schemas/v0-1-0/content-element.schema.json
This adds the ability to add an audio clip to popup elements. That audio clip will play when the popup is displayed, and stop if the popup is dismissed.
Due to some recent changes in the modal infrastructure, I had to modify the audio-picker control to browse the audio files within the already-open popup config modal instead of opening a new one.
=> [Feature] Audio support on popups. [MER-1470]

assets/src/components/editing/elements/page_link/PageLinkEditor.tsx, lib/oli/authoring/editing/container_editor.ex, lib/oli/authoring/editing/util.ex, lib/oli/delivery/hierarchy.ex, lib/oli_web/common/breadcrumb.ex, lib/oli_web/live/common/hierarchy/move_modal.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/curriculum/container/container_live.html.leex, lib/oli_web/live/curriculum/entries/actions.ex, lib/oli_web/live/curriculum/entries/entry.ex, lib/oli_web/live/curriculum/entries/not_empty_modal.ex, lib/oli_web/live/resources/pages_table_model.ex, lib/oli_web/live/resources/pages_view.ex, test/oli/delivery/hierarchy_test.exs
Adds the ability to create a new page directly in the new "All Pages" view
As well as several other related enhancements:
- Ability to move a page from the All Pages view into the curriculum
- Ability to remove a page from the curriculum (without necessarily deleting the page)
- Updates the breadcrumb to show the "All Pages" link (instead of curriculum) if the page being edited does not exist in the curriculum
- Ability to navigate directly from a Page link to the linked page in authoring, so that authors can seamlessly jump into an unconnected page to edit it
=> [ENHANCEMENT] [MER 1468] provide an option to create a new page from the all pages view

assets/src/components/common/Popup.tsx, assets/src/components/content/RichTextEditor.tsx, assets/src/components/editing/editor/Editor.tsx, assets/src/components/editing/elements/common/settings/InlineEditor.tsx, assets/src/components/editing/elements/popup/PopupContentModal.tsx, assets/src/components/editing/toolbar/Toolbar.modules.scss, assets/src/components/editing/toolbar/Toolbar.tsx, assets/src/components/editing/toolbar/buttons/DropdownButton.tsx, assets/src/components/editing/toolbar/editorToolbar/EditorToolbar.tsx, assets/src/data/content/utils.tsx, assets/src/phoenix/app.ts, assets/test/data/content/utils_test.ts, lib/oli/rendering/content/html.ex
Couple issues fixed related to popups here.
Darren fixed an issue with an audio attribute being set, but an empty string on popup elements would cause a JS error in the console.
Added a speaker icon if you have a popup with audio and no text in it.
The editor wasn't displaying formatting options due to some modal-window z-index ordering issues, and when it did, it allowed you to author all kinds of content that didn't actually work inside a popup. Now, we have a fixed-editing toolbar and you're limited to inline formatting options.
=> Fix popup audio

assets/src/components/editing/elements/common/MediaPickerPanel.tsx, assets/src/components/editing/elements/common/SlideOutPanel.tsx, assets/src/components/editing/elements/video/VideoModal.tsx, assets/src/components/media/UrlOrUpload.tsx, assets/styles/authoring/controls.scss
The browse-video and browse-image options in the video settings were broken due to some modal-dialog changes preventing multiple modals visible at the same time.
This change takes that browsing out of a new modal and does an osx-style sheet that slides down from the top of the edit-modal to pick the media.
=> [BUG] Fixed video settings browse dialogs.

assets/src/components/activities/custom_dnd/DragCanvas.tsx
This PR fixes logic intended to restore a students previous state with the DnD activity.
Root cause of failure was that since now the part id is included as part of the response, that part id has to be parsed out to properly identify the droppable whose `input_val` matches.   
Fixes [input_val](https://eliterate.atlassian.net/browse/MER-1488)
=> [BUG FIX] [MER-1488] Properly restore dnd state

assets/src/components/activities/common/authoring/settings/activitySettingsActions.ts, assets/src/components/activities/common/delivery/evaluation/Evaluation.tsx, assets/src/components/activities/common/utils.tsx, assets/src/components/activities/multi_input/MultiInputAuthoring.tsx, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/multi_input/schema.ts, assets/src/components/activities/multi_input/utils.tsx, assets/src/components/activities/types.ts, assets/test/multi_input/multi_input_authoring_test.tsx
This PR adds an author facing option on the MultiInput activity to allow "per part" submission, the same way that Legacy multi-input questions work. 
Tested this in practice, summative, survey and review contexts.  
There will be a corresponding PR in `course-digest` to set the `perPartSubmission` flag to `true` for all multi-input questions in migrated courses.
=> [ENHANCEMENT] [MER-1467] Provide option for Multi-Input to submit parts Legacy style

.yarnrc, assets/src/components/activities/AuthoringElementProvider.tsx, assets/src/components/activities/common/authoring/GradingApproachDropdown.tsx, assets/src/components/activities/common/delivery/inputs/NumericInput.tsx, assets/src/components/activities/custom_dnd/AnswerKey.tsx, assets/src/components/activities/multi_input/sections/AnswerKeyTab.tsx, assets/src/components/activities/multi_input/sections/InputRefToolbar.tsx, assets/src/components/activities/short_answer/ShortAnswerAuthoring.tsx, assets/src/components/activities/short_answer/sections/InputEntry.tsx, assets/src/components/activities/short_answer/sections/MathInput.tsx, assets/src/components/activities/short_answer/sections/NumericInput.tsx, assets/src/components/activities/short_answer/sections/TextInput.tsx, assets/src/components/activities/short_answer/utils.ts, assets/src/components/common/ErrorBoundary.tsx, assets/src/components/misc/Tooltip.tsx, assets/src/data/activities/model/responses.ts, assets/src/data/activities/model/rules.ts, assets/test/activities/rules_test.ts, assets/test/components/activities/short_answer/sections/NumericInput_test.tsx, assets/test/short_answer/short_answer_authoring_test.ts, lib/oli/delivery/evaluation/rule.ex, test/oli/delivery/evaluation/rule_eval_test.exs
Adds support for numeric precision for legacy courses. Configuring a precision will tell the evaluator to check to a specific number of digits in the input response.
This PR also includes a fix to add support for legacy numeric range format: `input like {[151.0,151.3]}`. Though, this addition will result in support for two different range formats in the system. Any creation/edit of numeric input activities will result in the new (or legacy) format as it is more concise and a bit easier to parse.
Finally, there is a bit of refactor around the way torus escapes/unescapes input. These functions were starting to leak into the codebase beyond the parsing layer into activities, it makes much more sense to keep them scope to the parsing step so that activities do not have to worry about this …
=> [FEATURE] [MER 1469] [MER 1487] provide backwards compatible precision support for numeric

assets/src/components/activities/common/choices/delivery/ChoicesDelivery.tsx, assets/src/components/common/CommandButton.tsx
Before, if you had a command button within an MCQ choice, and you clicked it, it would submit the MCQ question. Now, only the command is exectuted.
From bug:
```
Steps to reproduce:
1. Create a multiple choice question
2. Embed a video within the question stem.
3. In one of the choices, embed a command button that sends a message to the video.
4. Preview the question (or deploy it within a course section)
5. Click the button to start/stop the video.
Expected: the video starts and stops.
Actually: the video starts and stops, but the click event bubbles up to the choice and triggers a submission of the activity with that choice selected
```
=> [BUGFIX] Command button was submitting MCQ question [MER-1496]

assets/src/apps/delivery/layouts/deck/LessonFinishedDialog.tsx, assets/src/apps/delivery/layouts/deck/RestartLessonDialog.tsx
getting errors sometimes when students try to finalize an adaptive page; it is suspected that the previous method of using JS to open the window might be triggering some sort of security. switching to a hyperlink instead.
=> [BUGFIX] AOPS-985_AOPS-984 js redirect vs hyperlink is sus

assets/src/components/common/Popup.tsx, assets/src/components/hooks/useAudio.tsx, assets/src/components/video_player/VideoPlayer.tsx
This fixes 4 more components that had the same bug as https://github.com/Simon-Initiative/oli-torus/pull/3066
These all had interactable controls that wanted a learner to click on them, but if they were part of an MCQ choice, that MCQ would receive the input and select the answer prematurely.
- Definition with Pronunciation Audio
- A conjugation table, where one of the cells has an audio file to play on click
- Video Player
- Popups set to activate on “click”
I also tested web pages, youtube, and audio elements since they also have click handlers, but those components were all set as-is.
=> [BUGFIX] Fixes components when in MCQ choices that were causing submissions [MER-1503]

assets/src/components/activities/common/choices/delivery/ChoicesDelivery.modules.scss, assets/src/components/activities/common/choices/delivery/ChoicesDelivery.tsx
There were a series of rendering-issues with certain elements inside the choices of MCQ/CATA questions related to how they would resize vs. the width of the choice container element. Some of these, like Video, Youtube, and Webpage made the component unusable. Some, like in Dialog, introduced minor visual problems.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Tables:
Before:
After:
=> [BUGFIX] Rendering issues inside MCQ/CATA choices [MER-1502]

assets/src/components/editing/elements/audio/audioActions.tsx
Bug:
1. Create a page
2. Add an MCQ item to the page
3. Attempt to add an audio element to an entry inside the MCQ
Expected: A browse dialog for audio files
Actual: A browse dialog for only images
🚨Before merging this, we should think a bit.  I think the original intent was to separate activity code from the "main" page code to make things more extensible via the web-component strategy. This fix ignores that concern. If that's important, there are a whole bunch of places that do media-browsing like this that we should revisit and this becomes a bigger issue.
=> [BUGFIX] Allow audio element authoring in activities [MER-1501]

assets/src/data/content/model/elements/types.ts, assets/src/data/content/writers/html.tsx, lib/oli/rendering/content/html.ex, priv/schemas/v0-1-0/content-element.schema.json
This PR adjusts inline latex formula rendering to respect a new attribute: `legacyBlockRendered`.  If this attr is present and set to `true` the inline formula that contains Latex will render with block level Latex escapes, and not inlines.  This is to account for pages authored by hand in XML where the author did not realize `<formula>` was a mixed element, and thus used it as an inline, but with block level Latex escapes. 
https://eliterate.atlassian.net/browse/MER-1500
=> [FEATURE] Maintain legacy latex block rendering [MER-1500]

lib/oli_web/live/objectives/objectives.ex, test/oli_web/live/objectives_live_test.exs
We are displaying the pages attached to the objective + pages attached to the sub-objectives (and could be the same), so it's needed to do a `uniq_by` slug in order to take each page into account just once.
=> [BUGFIX] Uniq by slug for page attachments in objectives view

lib/oli/delivery/attempts/page_lifecycle.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/prologue.html.eex, test/oli_web/plugs/maybe_gated_resource_test.exs
This PR adjusts the implementation to allow a student to submit additional attempts in graded pages when their previous attempt enters a "submitted" state and is awaiting instructor manual scoring.  The rationale here is that a student should not have to wait for the instructor to manually score previous work in order to start another attempt.
To test this out, do the following:
1. Create a graded page that contains at least one manually scored activity and that allows multiple attempts.
2. Deploy to a course section, access and submit a first attempt as a student.
3. Verify that the attempt shows up in the instructor manual scoring UI.
4. As the student, visit the page again and verify that you see the 'Prologue' page that shows the first attempts is awaiting instructor scoring.
5. …
=> [BUG FIX] Treat submitted graded pages the same as evaluated [AOPS-1021]

assets/src/components/activities/DeliveryElementProvider.tsx, assets/src/components/activities/common/delivery/evaluation/Evaluation.tsx, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/vlab/VlabDelivery.tsx, assets/src/data/content/writers/context.ts, assets/styles/common/elements.scss, assets/styles/delivery/page_delivery/page.scss, assets/test/check_all_that_apply/cata_delivery_test.tsx, assets/test/multiple_choice/mc_delivery_test.tsx, assets/test/ordering/ordering_delivery_test.tsx, assets/test/short_answer/short_answer_delivery_test.tsx, lib/oli/rendering/content/html.ex, lib/oli_web/common/mathjax_script.ex
This PR contains several (mainly) formatting fixes that came from the Chemistry course migration QA effort. 
1. Do not show score and out of in formative evaluation. In a formative the score can be confusing to a student. 
2. Makes definition title font smaller
3. Font for Page Title is now more bold than an h1
4. Changes tables to render in a way similar to Legacy, (not full width). Removes the margin following the last paragraph in a `<td>`
5. Do not display “Pronunciation” label if there isn’t one for Definitions
6. Includes the proper MathML MathJAX configuration to actually render MathML.  
7. Do not render block formula elements with a gray background.
=> [ENHANCEMENT] various formatting fixes from chemistry qa feedback [MER-1505]

assets/src/components/resource/editors/ContentEditor.tsx, assets/src/components/resource/editors/useBlueprints.ts, assets/src/data/content/model/elements/types.ts, lib/oli/authoring/editing/blueprint.ex, lib/oli_web/controllers/api/blueprint_controller.ex, lib/oli_web/router.ex, priv/repo/migrations/20221020142919_add_blueprint_table.exs
Added a new blueprint feature with a single blueprint available that inserts elements that resemble a theorem. In the future, we can use the blueprint feature to adding other template-style items.
Also added to swagger UI if you want a quick way to test the API:
Future improvements to blueprints to consider include user-defined blueprints and discoverability of those between users.
=> [FEATURE] Add blueprints with Theorem as the first one [MER-1415]

assets/src/components/common/DescriptionList.tsx, assets/src/components/editing/editor/modelEditorDispatch.tsx, assets/src/components/editing/elements/description/DescriptionListEditor.tsx, assets/src/components/editing/elements/description/description-list-actions.ts, assets/src/components/editing/toolbar/editorToolbar/blocks/blockInsertOptions.ts, assets/src/data/content/model/elements/factories.ts, assets/src/data/content/model/elements/types.ts, assets/src/data/content/model/schema.ts, assets/src/data/content/writers/html.tsx, assets/src/data/content/writers/writer.tsx, assets/styles/authoring/description-list.scss, assets/styles/authoring/index.scss, assets/styles/common/elements.scss, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/content/plaintext.ex, priv/schemas/v0-1-0/content-element.schema.json
Adds a definition list element to core authoring. They consist of a title followed by a series of terms and definitions which get rendered out in html dl,dd,dt tags.
Example:
A note on implementation: Originally, in the json format, I had the dd/dt tags in the children property of the dl element. I liked that since you had just one editor and it flowed a little nicer. However, I ran into a couple slate JS specific issues with that method that I was unable to resolve with the core problem being that many times, invalid children of the DL would get added and eventually invalid HTML would be rendered.
We have that same issue with our normal lists. For example, if you try to insert an image into a list item, then go preview, you end up with a structure like this which isn't properly formatted …
=> [FEATURE] Add description list element [MER-1507]

assets/src/components/activities/check_all_that_apply/utils.ts, assets/src/components/activities/common/utils.tsx, assets/src/components/activities/common/variables/VariableEditorOrNot.tsx, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/multi_input/utils.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/multiple_choice/utils.ts, assets/src/components/activities/ordering/utils.ts, assets/src/components/activities/types.ts, assets/src/components/activities/vlab/utils.tsx, assets/src/data/activities/DeliveryState.ts, assets/test/multi_input/multi_input_authoring_test.tsx, lib/oli/activities/model/transformations.ex, lib/oli/activities/transformers.ex, lib/oli/delivery/attempts/activity_lifecycle.ex, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/chromeless.html.eex, lib/oli_web/templates/layout/delivery.html.eex, test/oli/delivery/attempts/attempt_reset_test.exs
This adjusts how MCQs work in a practice context:
1. Do not show the "Reset" button, rather, simply allow students to click other choices to reset and submit automatically.
2. Do not shuffle choices - even when shuffle is enabled - after the first attempt.
Task 1 above was straightforward.  Task 2 required extending the "transformation" framework a bit to introduce a `first_attempt_only` attribute on transformation instances.  If any of the transformations present have `:first_attempt_only` set to `true`, then none of the transformations run and the previous attempt's model is used for the new attempt.
I also ran into someweirdness with the CDN that we serve React from.  It was failing due to CORS issues in my dev env.  I switched it over to the CloudFlare CDN (which we use for all …
=> [ENHANCEMENT] Align MCQ behavior with legacy [MER-1523]

lib/oli_web/live/history/revision_history.sface
Fixes the revision history liveview by calling the Table component as an actual surface component instead of live_component.
=> [BUGFIX] fix revision history liveview

assets/src/apps/page-editor/PageEditor.tsx, assets/src/components/common/ErrorBoundary.tsx, assets/src/components/media/UrlOrUpload.tsx
While working on https://github.com/Simon-Initiative/oli-torus/pull/3090 I saw that an error in the media manager resulted in the app completely crashing to a blank screen.
This modifies that behavior.
1. The entire PageEditor is wrapped in an ErrorBoundary now, so we'll get a more friendly error if any of those top level components fail.
2. ErrorBoundary now takes an optional errorMessage param to customize what the user sees
3. The UrlOrUpload component now wraps the MediaManager component with a more locally-scoped error boundary, so if an error occurs there the user can just close the dialog and retry instead of being forced to reload the entire page.
Example dialog with error message:
=> [ENHANCEMENT] Media manager errors are no longer fatal

assets/src/actions/media.ts, assets/src/components/media/UrlOrUpload.tsx, assets/src/components/media/manager/MediaManager.tsx
This fixes two bugs in media-selection for images.
First bug is #3089 - Inability to modify the source of an image previously set.
Second bug:
1. Add an image to a page
2. Choose image button
3. Select “external url” and type in an image url.
4. Close the selection dialog.
5. Edit the source of the image and go to the external url tab.
Expected: the input box has the URL in it  
Actual: the input box is empty
Fixes #3089
=> [BUG] Image selection bugs [MER-1533]

assets/src/components/activities/common/responses/SimpleFeedback.tsx
Fixes an issue with the SimpleFeedback editor (identified in the multi input question) where the editor value changes but react doesnt know to swap the old editor for the new one. The fix here is to add a unique key to the correct/incorrect feedback elements that changes when the selected partId changes.
=> [BUGFIX] MER-1537 fix an issue with multi-input editing

.github/actions/torus-builder/entrypoint.sh, assets/package.json, assets/webpack.config.js, assets/yarn.lock, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/chromeless.html.eex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/templates/layout/lti.html.eex
This PR tweaks our webpack config for more efficient builds. Some results:
| Measurement |  Before PR | After PR |
| --------------- | ------------ | --------- |
| Production Build Time | 91 seconds | 88 seconds |
| Development incremental Build Time after modifying JS file | 10s | 2s |
| Development incremental Build Time after modifying scss file | 10s | 10s |
| Total JS File size in build dir | 118M | 31M |
| Total js resources loaded on core-authoring page | 76.9M | 30.5 |
| Total js resources loaded on development version of core-authoring page | 176M | 36M |
| Total js resources loaded on development version of adaptive-authoring page | 57M | 41M |
| Total js resources loaded on adaptive-authoring page | 25.8M | 23M |
| Total js resources loaded on preview of a core-authoring page | …
=> [Chore] Webpack optimization [MER-1512]

assets/src/apps/authoring/components/RightMenu/RightMenu.tsx
Fixes bug:
1. Create or open up any adaptive page
2. Add a popup
3. Click the edit button in the right hand side panel under the component tab that opens up the JSON
4. Scroll down and click save in the JSON popup
Watch the lesson crash. 
The issue here, was the json editor was editing the model after it had passed through `transformSchemaToModel` when it should have been using the original model value. 
For most components, this doesn't matter, because the user is only editing the id & custom fields. Popup would crash because it's version of `transformSchemaToModel` overwrote `custom`.
=> [BUGFIX] Crash on editing adaptive lesson popup json [MER-1471]

assets/src/apps/authoring/components/AdaptivityEditor/AdaptiveItemOptions.ts, assets/src/apps/authoring/components/AdaptivityEditor/ConditionItemEditor.tsx
Bug:
1. on argos prod, open [Columbia Lesson-6: Calculations, Fall 2022](https://localhost:8043/authoring/project/columbia_lesson6_calculations_)
2. Edit the only page in it
3. Select the `Q5. Breaking Problems into Steps (Again)` screen under "Report a problem -> Back of the envelope calculations" layers
4. Click the Incorrect state on the left
5. Observe the app crashes
Somehow, the incorrect state for that screen had an operator of isNotEquivalentOf set where the correct name would have been notIsEquivalentOf
I don’t know how that would have gotten in there, maybe some sort of import or manual edit?
But now, the software will use reasonable defaults and not crash if it hits an unknown operator there.
=> [BUGFIX] Fixes adaptive author crash on unknown operator. [MER-1544]

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx
The `onSubmit` was closing over the initial state of the `uiState`.  Solution here was to call `getState` within it to guarantee the current state is used.
=> [BUG FIX] Dnd fix [MER-1540]

lib/oli/accounts.ex, test/oli_web/controllers/collaborator_controller_test.exs
Fixes an issue where inviting a collaborator with an email that contains capital letter might fail.
Closes #3097
=> [BUGFIX] MER-1548 ensure email is lowercase before query

assets/src/components/activities/common/delivery/evaluation/Evaluation.tsx, assets/styles/delivery/activity.scss, assets/styles/delivery/variables.scss, assets/styles/themes/delivery/default.scss
The current color schemes for "correct", "incorrect" and "explanation" are green on light green, red on light red, and blue on light blue.  This fails a WCAG compliant color contrast check that Sandy ran.  Changing to more closely mirror legacy: black text.
=> [ENHANCEMENT] adjust color of text to pass accessibility guidelines failure [MER-1538]

lib/oli/interop/ingest/processor/pages.ex
Sets the explanation strategy for pages (slightly different for graded or practice), to allow courses within explanations in activities to appear by default - as opposed to having to manually set these after ingest.
=> [ENHANCEMENT] set explanation strategy on import [MER-1541]

lib/oli/features.ex, lib/oli/features/feature.ex, lib/oli/features/feature_state.ex, priv/repo/migrations/20221103202020_feature_flags.exs, test/oli/features_test.exs
Fixes an issue where feature flags were being reset on every deployment. The underlying issue here was that the flag records were always being recreated as disabled. After digging in, I relized there is no good way to identify and retain a flag's state given the current id field is hardcoded and could be changed/reused upon a code update. I opted to make the label a string primary key instead so that a flag's state can always be identified by this unique label
=> [BUGFIX] MER-1412 Fix feature flags reset on deploy

assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts, assets/styles/themes/delivery/adaptive_themes/default/layout/background.scss, assets/styles/themes/delivery/adaptive_themes/default/light.scss
Lesson background images in the default theme for adaptive lessons were broken as the were displaying as a 0-height image.
This change adds some css to the default theme to fix that, plus it adds media-library browsing to choose the background image. I verified this works in both preview & delivery modes.
=> [FEATURE] Fix adaptive backgrounds and add media browser. [MER-1529]

assets/src/apps/authoring/components/Modal/MediaPickerModal.tsx, assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusAudioBrowser.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusImageBrowser.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusVideoBrowser.tsx, assets/src/components/hooks/useAudio.tsx, assets/src/components/parts/janus-audio/schema.ts, assets/src/components/parts/janus-video/schema.ts
Use the torus media-manager to select audio and video URL's for the audio and video components in adaptive lessons. 
Audio editor allows you to preview audio from the editor.
Example Audio Editor:
Example Video Editor:
=> [FEATURE] Add media-browser support to adaptive video & audio elements [MER-1528, MER-1527]

assets/src/utils/mathmlSanitizer.ts, lib/oli/rendering/content/mathml_sanitizer.ex, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/chromeless.html.eex, lib/oli_web/templates/layout/delivery.html.eex
This PR allows Torus to render MathML that contains the `m` namespace.  Two things were required:
1. Expand the mathml scrubbing configuration to whitelist all elements with that namespace
2. Add the namespace declaration to the root `<html>` element.
=> [BUG FIX] Handle namespaced mathml [MER-1550]

assets/src/components/resource/editors/ActivityEditor.tsx
In some cases children can be undefined so this adds a check to ensure the editor doesn't crash in that case.
=> [BUG FIX] Fix activity editor rendering

config/config.exs, config/test.exs, lib/oli/lti/access_token_adapter.ex, lib/oli/lti/access_token_library.ex, lib/oli/lti/access_token_test.ex, lib/oli_web/live/grades/grades.ex, test/oli_web/live/grades_live_test.exs, test/support/factory.ex, test/support/test_helpers.ex
[MER-1463](https://eliterate.atlassian.net/browse/MER-1463)
This PR adds tests for the GradesLive view.
Connection to the LMS, downloading the gradebook, updating LMS line items and synchronizing grades are tested.
Files are added to be able to handle the execution of the **_fetch_access_token_** function depending on the environment in which it is running. This change has been made as it was failing in the test environment due to the time it takes to execute.
=> [MER-1463] Add tests GradesLive

lib/oli_web/live/history/pagination.ex, lib/oli_web/live/history/pagination_link.ex
Fixes an issue when revision history table is large enough to show pagination controls, the view crashes.
Closes #3117
=> [BUG FIX] MER-1549 fix an issue where revision history table pagination crashes

lib/oli/utils.ex, lib/oli/utils/appsignal.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/templates/project/publish.html.eex, priv/repo/migrations/20221109230029_fix_duplicate_active_publications.exs, test/oli_web/live/objectives_live_test.exs
This PR attempts to close an issue in the system where (infrequently) multiple active publications can occur causing the project to be inaccessible. The root cause is still unknown, but the working theory is that somehow multiple requests to publish the active publication may be occurring simultaneously, possibly by multiple users clicking publish at the same time or accidental double clicks getting past the phoenix button disable. Even though the operation is wrapped in a database transaction somehow the system is allowing multiple active publications to be created.
The fix here is to make the `publish_active` POST request be idempotent, requiring the active_publication_id be supplied so that it can be checked against the actual active publication. It also includes a migration to fix any …
=> [BUG FIX] Fix an issue where multiple active publications can occur

assets/src/components/activities/adaptive/components/common/PartComponent.tsx
There was a bug where a rule in the initial state of a screen that tried to set the customCssClass property of a component couldn't actually set it.
This was due to the lesson state being updated after the initial styles were set up in handleStylingChanges of PartComponent and not being updated after onInit was called.
customCssClass is special because it gets set on the web-component element itself, and not inside that webcomponent.
Note: The bug would have also affected these properties:
stage.${props.id}.IFRAME_frameX
stage.${props.id}.IFRAME_frameY
stage.${props.id}.IFRAME_frameZ
stage.${props.id}.IFRAME_frameWidth
stage.${props.id}.IFRAME_frameHeight
stage.${props.id}.IFRAME_frameCssClass
stage.${props.id}.customCssClass
=> [BUGFIX] Initial state can now modify customCSS of components [MER-1535]

assets/src/components/activities/multi_input/MultiInputDelivery.tsx
This PR adjusts the behavior of the multi input activity to only submit a part if there is actual student input present.  Prior to this PR, if a student (in a submit per part multiinput) clicked into an input to gain its focues then clicked away, that input would submit that part.  Same thing for pressing Enter.  Now, the parts only submit if there is actual student input present.
=> [ENHANCEMENT] Ensure that there is state prior to submit [MER-1558]

lib/oli/authoring/media_library.ex, test/oli/authoring/media_libary_test.exs
Fixes #3114 
Describe the bug
Torus should upload media to S3 as a content addressable storage and not include slug
To Reproduce
Steps to reproduce the behavior:
Upload an item, see that it contains the project slug in the media url
Example url from a local dev instance:
https://torus-media-dev.s3.amazonaws.com/media/14/14A94AA2B771544B9B66CF77A4DB0055/minus-circle.png
=> [FEATURE] Upload media as content addressable storage [MER-1562]

assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx
This PR introduced a bug: https://github.com/Simon-Initiative/oli-torus/pull/3129
When a component in the adaptive editor went into configure mode, it would get re-created as a new component and any internal state would be lost.
This was the cause of MER-1565
- Edit an adaptive lesson
- Add an MCQ question
- Click the edit button
- Click the edit button on an option
Expected: an editor for that option
Actual: An empty window with no editor in it.
Note: There is some kind of bug inside the quill editor as well. It doesn't happen all the time, but sometimes, it doesn't dispatch change events and the individual options aren't changed. I was able to reproduce this on prod, and tracked it down to something inside the editor itself. Pressing space-bar seems to always cause a change to come …
=> [BugFix] Don't recreate the authoring element when configured. [MER-1565]

assets/src/apps/authoring/BottomPanel.tsx, assets/src/apps/authoring/components/AdaptiveRulesList/AdaptiveRulesList.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/InitStateEditor.tsx, assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx, assets/src/apps/authoring/components/ComponentToolbar/ComponentSearchContextMenu.tsx, assets/src/apps/authoring/components/EditingCanvas/AuthoringActivityRenderer.tsx, assets/src/apps/authoring/components/Modal/diagnostics/actions.ts, assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts, assets/src/apps/authoring/components/RightMenu/RightMenu.tsx, assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx, assets/src/apps/authoring/store/activities/actions/saveActivity.ts, assets/src/apps/authoring/store/page/actions/initializeFromContext.ts, assets/src/apps/authoring/store/page/actions/savePage.ts, assets/src/apps/authoring/store/parts/actions/updatePart.ts, assets/src/apps/authoring/store/persistance-options.ts
This bug is for the right-hand panel, but in a lot of places in the adaptive lesson editor, if you:
1.  Edit something
2.  Then edit something else before 1 finishes saving
3.  Your edit to 2 will be reset to data before 1.
**Easiest way I can reproduce this:**
Let’s say I want to change my dimensions from 700x500 to 800x600
I might type in 800, hit tab, type in 600 and expect those values to be there.
In reality what usually happens is I type in 800, hit tab, start typing 600, maybe get one or two characters in, and then it resets to 500 and I finish typing. So on each keypress I might get:
- 500 <- starting
- 6     <- typed 6
- 60   <- typed 0
- 500 <- it resets to the original on it’s own
- 5000 <- I type my last 0
**A similar symptom of the same type of issue:**
- You edit a value.
- …
=> [Bugfix] adaptive data bounce [MER-1561]

assets/src/components/editing/editor/normalizers/root.ts
Fixes bug:
1. Create a core authoring page
2. Insert an image
3. Edit the page in the admin view and make the image the very first element with no paragraph before it.
4. Go back to normal page editor
5. Make any change
You’ll see this warning in the console many times (should only happen once)
react_devtools_backend.js:4026 Normalizing content: Inserted paragraph at start of document
And there will be many empty lines after your image.
Fixes #3082
=> [BUGFIX] Fixes many-paragraph insert normalization bug [MER-1566]

assets/src/components/editing/elements/video/VideoSettings.tsx
1. Create a core authoring page
2. Add a video to the page & set a video.
3. Add an MCQ to the page
4. Now try to edit the video and change the cover image
Expected: Media browser
Actual: Error message
Cause of bug:
Both the PageEditor and the MCQ editor have a `<ModalDisplay />` component.
Those components are in different redux contexts.
The ModalDisplay sets a global window.oliDispatch method.
That oliDispatch will now only work from components that originate in the same redux context as the second ModalDisplay, but the second one overwrote the window.oliDispatch from the first instance of it, so all calls will reference the second one.
This causes the bug in the video-editor because we render the media browser in a panel in the same UI instead of a popup modal which causes the …
=> [BUGFIX] Fix media-browser bug by using local dispatch [MER-1575]

assets/src/components/monaco_lenses/activity_links_lens.ts, assets/src/components/monaco_lenses/index.ts, assets/src/hooks/monaco_editor.tsx, assets/src/utils/surface.ts, lib/oli_web/live/common/monaco_editor.ex, lib/oli_web/live/history/details.ex, lib/oli_web/live/history/revision_history.sface
Adds the ability to open an activity's revision history from an inline monaco code lens link in the page revision history json.
=> [ENHANCEMENT] add code lens link to open activity revision history

CHANGELOG.md, assets/package.json, assets/src/apps/authoring/Authoring.tsx, assets/src/apps/page-editor/PageEditor.tsx, assets/src/components/common/ErrorBoundary.tsx, assets/src/components/parts/janus-image/Image.tsx, assets/src/utils/appsignal.ts, assets/yarn.lock, config/config.exs, lib/oli/authoring/editing/page_context.ex, lib/oli/authoring/editing/page_editor.ex, lib/oli_web/controllers/resource_controller.ex
This adds appsignal support in the core & adaptive authoring environments to report on client side errors.
We'll get a report on:
- An error in the react error-boundary
- An uncaught exception
- An unhandled promise rejection
We'll need to watch the second two of those to see the volume of useful / not-useful reports we get, since sometimes things like browser-extensions can trip them.
On launch, I added a breadcrumb with the projectSlug, resourceSlug and resourceId to help track down issues. Then we also get breadcrumbs for console messages and fetch requests. (All of that only gets logged on an actual error)
We also get a stacktrace
The errors will be in separate appsignal namespaces for the two apps.
The client uses the appsignal API key that the elixir backend uses from the …
=> [ENHANCEMENT] Appsignal support in client authoring apps

config/releases.exs
The appsignal key wasn't being read in on deployed instances. This should read it in at runtime.
I don't know how to test this without doing a full build/deploy, it doesn't do anything when just running locally.
=> [BUGFIX] Configure app signal key during deployments.

CHANGELOG.md, assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx, assets/src/components/activities/common/hints/delivery/HintsDelivery.tsx, assets/src/components/activities/common/hints/delivery/HintsDeliveryConnected.tsx, assets/src/components/activities/file_upload/FileUploadDelivery.tsx, assets/src/components/activities/likert/LikertDelivery.tsx, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/ordering/OrderingDelivery.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/components/activities/vlab/VlabDelivery.tsx, assets/src/data/activities/DeliveryState.ts, lib/oli/delivery/attempts/activity_lifecycle.ex
This updates the hint logic on practice pages:
1. You can request hints before answering
2. You can see hints on incorrect
3. You can request additional hints on incorrect, but that implicitly resets 
4. Hints are hidden on correct
5. Once you see a hint, it remains revealed until you get it correct.
=> Not ready - [ENHANCEMENT] Changed logic for when hints are displayed [MER-1581]

lib/oli/application.ex, lib/oli/delivery/sections.ex, lib/oli/publishing.ex, lib/oli/publishing/publications/diff_agent.ex, lib/oli/publishing/publications/publication_diff.ex
Followup to #3166, this PR adds a diff to the cache when one is generated JIT and also adds a daily cleanup job to remove diffs that are 10 days or older.
=> [ENHANCEMENT] add a cleanup task for publication diffs [MER-1596]

assets/src/apps/delivery/layouts/deck/RestartLessonDialog.tsx, lib/oli/delivery/attempts/activity_lifecycle/persistence.ex
This PR fixes two problems encountered during regression testing:
1. The ability to "Restart" a graded adaptive page was broke.  The root cause here was an incomplete migration to the new POST based finalization API (away from the previous GET based HTML returning endpoint).  The "Ok" button in the popup dialog to confirm and initiate Restart still contained a hyperlink that triggered a GET request, with the URL now being the `/api/v1/page_lifecycle` JSON endpoint.  This triggers the "Not Found" error.    The solution here is to simply remove the `href` from that link and allow the onClick handler `handleRestart` to do its intended job. 
2. While replicating the above error, I stumbled across another regression.  There seem to be certain adaptive screens that when the trigger a check …
=> [BUG FIX] fix lesson restart, eval persistence when no parts need saving [MER-1598]

assets/src/components/activities/common/hints/delivery/HintsDelivery.tsx, assets/src/data/content/model/schema.ts, assets/src/utils/common.ts, lib/oli/activities/parse_utils.ex
This fixes two bugs
1. If you inserted a video into a hint, the video would be sized based on other content in that hint. If there was no other content, it would be very tiny and unusable.
2. If you inserted ONLY a video into a single hint, the "request a hint" link would not show up.
The second one was caused by us filtering out "empty" hints with an improper definition of "empty"
=> [BUG FIX] Videos, youtube unusable when placed in hints or feedback [MER-1602]

assets/src/components/editing/elements/callout/calloutActions.ts, assets/src/components/editing/toolbar/HoverContainer.tsx
Fixes a cursor related bug and also inserting callouts now doesn't clear the selection.
https://user-images.githubusercontent.com/333265/206767114-9cac6aae-fe0f-4f35-9c20-956adcf20b17.mov
=> [BUG FIX] Left arrow cursor navigation does not work properly through all inline types [MER-1603]

assets/src/components/activities/common/hints/delivery/HintsDeliveryConnected.tsx
We were showing hints on graded pages, this removes that.
=> [BUGFIX] Don't show hints on graded pages. [MER-1607]

lib/oli/publishing/publications/diff_agent.ex, test/oli/publishing/publications/diff_agent_test.exs
Fixes an issue where the diff agent cleanup function returns state as filtered list instead of a map.
=> [BUGFIX] [MER-1612] fix a bug where diff agent cleanup returns invalid state

assets/src/components/activities/image_coding/ImageCodingDelivery.tsx
This fixes two things that were broken for unknown time in the image coding activity: 
1. Submit button was not showing. And, after fixing that
2. Evaluation was not showing on submit. 
(1) was for same reason as with #3186: visibility had been conditional on surveyId of undefined but at some point value used there was evidently changed to null without updating code that relied on undefined.
(2) happened because activity was updating score and outOf in its local attemptState but not the attemptState's contained partState for the single part. This must have been sufficient at some time in the past to get it displayed. But the Evaluation React component it uses to render feedback and score -- a component now not used in any other activity -- now draws from that partState only so was finding …
=> [BUGFIX] Fix ImageCoding to show submit button + evaluation [MER-1619]

assets/src/components/editing/elements/popup/PopupElement.scss, assets/styles/common/elements.scss
This makes all the popover text green & bold in both authoring, preview, and delivery.
Authoring:
Preview:
Delivery:
=> [BUGFIX] Make popup text bold/green all the time. [MER-1620]

lib/oli/delivery/sections.ex, lib/oli/utils/seeder/section.ex, test/oli/sections_test.exs
This PR fixes an issue where major updates were changing the hierarchical structure of products. With this fix, only minor changes will be applied to a product during an update.
=> [BUGFIX] [MER-1622] products are receiving major course project updates they should not

lib/oli_web/templates/page_delivery/prologue.html.eex
Fix here is to ignore the attempt_number on the record, and calculate it JIT.  This ignores any previous practice attempts that might exist.
=> [BUG FIX] Attempt numbering can be wrong for pages that switch to graded [MER-1625]

lib/oli/publishing/authoring_resolver.ex, lib/oli/publishing/delivery_resolver.ex, test/oli/publishing/authoring_resolver_test.exs, test/oli/publishing/delivery_resolver_test.exs
Fixes an issue where alternatives options were still showing deleted alternatives groups as an option in the editor.
The underlying issue is that the resolvers `revisions_of_type` were not filtering out deleted revisions.
=> [BUGFIX] [MER-1627] ensure resolvers of type do not return deleted items

assets/src/components/parts/janus-fill-blanks/FillBlanks.scss
From Bug Report:
> The styling for the native janus FITB component is messed up in QA. This is not seen in prod. I have two instances where you can see this. The first is in a new lesson I created that has a custom CSS link used throughout the lesson. The second does not have any custom css. The issue is seen in both instances. 
This was caused by the changes to our webpack config https://github.com/Simon-Initiative/oli-torus/pull/3086
That change moved stuff that was pulled from node_modules from the component chunk into a central vendor chunk. For components utilizing the shadow-dom, this caused any CSS pulled into to stop working.
I did a quick search and it looks like FITB is the only component that both uses shadow-dom, and was importing css from node_modules, so I did a quick & …
=> [BUGFIX] Move FITB css into component chunk. [MER-1608]

lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/_link_assessment.html.eex, lib/oli_web/templates/page_delivery/_link_container.html.eex, lib/oli_web/templates/page_delivery/_link_page.html.eex, lib/oli_web/templates/page_delivery/_link_shallow_container.html.eex, lib/oli_web/templates/page_delivery/_outline.html.eex, lib/oli_web/views/page_delivery_view.ex
[MER-1613](https://eliterate.atlassian.net/browse/MER-1613)
Analyzed the query to build the hierarchy itself and from a SQL perspective there isn't much else to improve as it goes through indices (basically primary keys). One minor improvement we can make is to not retrieve as much data that is being fetched now, since not all of it is needed but would require further investigation.
Instead we look for another approach using the `previous_next_index` field in the section. Calling `retrieve` from `PreviousNextIndex` should be safe enough to always retrieve the correct hierarchy at the moment.
The hierarchy query will only be called when that field is null, but any other time a student enters the index it will just use that data.
=> [MER-1613] Build hierarchy from previous_next_index on course index

assets/src/apps/authoring/components/PropertyEditor/custom/TorusAudioBrowser.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusImageBrowser.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusMediaBrowserWrapper.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusVideoBrowser.tsx
Bug:
1. Create an adaptive page
2. Add a popup to it
3. Edit the content of the popup
4. Add an image, video, or audio element
Expected: the element is added
Actual: the browser crashes.
This is caused by that popup content editor being a part of the popup web component in it's own react context instead of being part of the main authoring react app.
After this fix, you will get the old text-input box to enter the urls for those 3 components. A future update will attempt to re-introduce the media browser.
=> [BUGFIX] Media browser crashing in popup editor [MER-1637]

lib/oli/delivery/sections.ex, lib/oli_web/controllers/page_delivery_controller.ex
This fixes a problem with outline rendering.  The previous impl did not preserve the proper top level ordering - it merely was iterating through the natural map key ordering of `hierarchy`.  This surprisingly works okay for a large majority of cases - but would break as soon as someone would course remix and would top-level reorder.
The source of truth for top-level ordering is the `children` attribute of the `root_section_resource` record.  But those ids are SR ids, not resource_ids. Our cached hierarchy is all in resource ids.  So a fetch of those resource_ids is made and then the top level is mapped thru that ordering to ensure that it is correct.
=> [BUG FIX] maintain proper top-level ordering in outline rendering [MER-1640]

lib/oli_web/controllers/page_delivery_controller.ex, test/oli_web/controllers/page_delivery_controller_test.exs
The fix here was to greatly simplify the code that constructs the hierarchy and to add a unit test that demonstrates that it handles deeply nested containers.
=> [BUG FIX] Fix rendering of deeply nested course hierarchies [MER-1641]

assets/src/phoenix/app.ts, lib/oli/rendering/content/html.ex
There were three places that played audio not inside a react component. Those are:
1. Pronunciation in a definition
2. Pronunciation in a conjugation
3. A table entry in conjugation
All can be seen here:
If you had a long audio file set, there was no way to interrupt the playing of that file. Now you can by clicking the link a second time.
=> [BUGFIX] Ability to stop certain audio when it is playing. [MER-1632]

assets/src/components/editing/elements/youtube/YoutubeElement.tsx, assets/src/components/editing/elements/youtube/YoutubeModal.tsx, assets/src/components/editing/elements/youtube/youtubeActions.tsx
If you tried pasting a youtube URL into the edit modal, it wasn't working. This is because the creation dialog ran some logic turning a url into a video ID that the edit modal didn't.
While in there, I also made it parse out /embed/videoid urls.
=> [BUGFIX] Allow editing youtube by url [MER-1634]

assets/src/components/editing/editor/Editor.tsx, assets/src/components/editing/elements/common/settings/InlineEditor.tsx, assets/src/components/editing/elements/description/DescriptionListEditor.tsx, assets/styles/authoring/description-list.scss
Previously, there was no ability to add definition terms/definitions anywhere except the end of the list. Now you can insert them anywhere in the list.
=> [BUGFIX] Ability to add definition list items anywhere in list [MER-1633]

lib/oli/rendering/group/html.ex
The issue here is that `group/3` specifies a pattern match that fails rendering if either the `id` or the `purpose` attributes are missing.  Handle this by generating and id and setting purpose to `"none"` when they are missing.
=> [BUG FIX] handle missing attrs in group rendering [MER-1644]

assets/src/components/editing/elements/audio/AudioElement.tsx, assets/src/components/editing/elements/audio/AudioSettings.tsx, assets/src/components/editing/elements/video/VideoModal.tsx, assets/src/components/video_player/VideoPlayer.tsx, assets/src/data/content/model/elements/types.ts, assets/src/data/content/writers/html.tsx, assets/styles/authoring/controls.scss, lib/oli/rendering/content/html.ex, priv/schemas/v0-1-0/content-element.schema.json
This exposes alt-text as aria-label attributes on audio and video elements to support people using assistive devices.
I did a mini-redesign of the video settings to break the options up into tabs since that dialog was getting rather long. The new alt-text for that can be found on the accessibility tab.
This also fixes a bug where it was impossible to edit the audio clip after you inserted it because the settings dialog couldn't be opened.
Audio settings:
=> MER-1630 - Alt Text on Video & Audio elements

CHANGELOG.md, lib/oli/activities/transformers/variable_substitution/common.ex, test/oli/activities/transformers/variable_substitution_test.exs
Fixes an issue where JSON special characters in variables breaks the evaluation leaving the unevaluated variable name.
https://eliterate.atlassian.net/browse/MER-1656
[MER-1656]: https://eliterate.atlassian.net/browse/MER-1656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-1656] Escape JSON special chars in variable evaluations

assets/src/data/persistence/extrinsic.ts
This reverts commit 9fb1ca6e97d7dcb52a97466130b1ab491a65afba which was the fix for https://eliterate.atlassian.net/browse/MER-1510
I believe it to be the cause of https://eliterate.atlassian.net/browse/MER-1653
Before reverting, this is the behavior we were seeing:
On a page refresh...
1. We load that global state on startup.
2. For some reason we also save that global state on startup.
3. Then... after loading the global state from 1, we save it again.
In 2... we actually save a blank report because that starts before we've finished 1.  
Luckily, most of the time, 3 happens so we overwrite the blank report with a good one again. But every single load, we corrupt the learner's data and then get lucky that we fix it later.
This is caused because our cache is separated out by top-level key, …
=> Revert "MER-1510 (#3137)"

CHANGELOG.md, lib/oli/activities/transformers/variable_substitution/common.ex, mix.exs, test/oli/activities/transformers/variable_substitution_test.exs
This simply applies the MER-1656 fix that has already landed to `master` to the `hotfix-v0.22.1` branch. It sets up the changelog and ticks the version in `mix.exs` as well
=> [BUG FIX] Apply [MER-1656] to hotfix branch

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli/delivery/attempts/activity_lifecycle/persistence.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex
[MER-1636](https://eliterate.atlassian.net/browse/MER-1636)
Intent to improve finalization of a page attempt by making only one query to update all activity attempts at once. Still need to update the part attempts within an iteration, as is needed to have that in place to have the correct values ​​to update the activity.
We should thoroughly test these changes, as I'm a bit worried this won't break anything else.
Feel free to ask questions or make any suggestions. In fact, we don't have to take these changes if you feel they are not necessary at all.
[MER-1636]: https://eliterate.atlassian.net/browse/MER-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1636] Bulk update activity attempts all at once

lib/oli/interop/ingest/processor/pages.ex, lib/oli/resources/collaboration/collab_space_config.ex
This extends the ingest V2 to allow it to read the `collabSpace` key that can optionally exist as a top-level key in a digest "Page" JSON blob.  
Testing this, convert a course that contains discussions (for example, French 1), then ingest and verify that that end-to-end that a Discussion activity is converted to a practice page with an enabled Collab Space.  You will need this PR to land to `course-digest` first, though: https://github.com/Simon-Initiative/course-digest/pull/120
=> [FEATURE] Allow Collab spaces to ingest [MER-1657]

lib/oli/groups.ex, lib/oli_web/live/community_live/select_member_modal.ex, lib/oli_web/live/community_live/show_view.ex, test/oli/groups_test.exs, test/oli_web/live/community_live_test.exs
[MER-972](https://eliterate.atlassian.net/browse/MER-972)
Allow duplicated user email to be added as member of the community, displaying a modal to select which one the admin wants to add.
We don't support anymore adding more than one email at the same time for members, as that would require a little more of rework.
#
[MER-972]: https://eliterate.atlassian.net/browse/MER-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX] [MER-972] Add duplicate email to community

lib/oli/resources.ex, lib/oli/resources/revision.ex, priv/repo/migrations/20230125131506_update_revisions_add_purpose.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-1671)
I'm not sure what's the best way to handle the update of application pages once a resource gets deleted (if a resource gets deleted and it's related to an application page, the `relates_to` of that page should be updated). Maybe we can ignore it and when we get the related resources of an application page, we can filter deleted resources.
=> [FEATURE] [MER-1646] Add necessary fields for exploration pages

lib/oli/publishing/authoring_resolver.ex, lib/oli/publishing/delivery_resolver.ex, test/oli/publishing/authoring_resolver_test.exs, test/oli/publishing/delivery_resolver_test.exs, test/support/test_helpers.ex
[MER-1673 ](https://eliterate.atlassian.net/browse/MER-1673)
This PR adds two new functions to the delivery and authoring resolvers. 
- `get_by_purpose/2` - Returns the current versions of all page resources whose purpose type matches.
- `targeted_via_related_to/2` - Returns a list of Revisions of all pages that target the given resource id in their "relates_to" attribute.
=> [FEATURE] [MER-1673] Infrastructure for exploration and relates_to resource access

lib/oli/delivery/evaluation/rule.ex, test/oli/delivery/evaluation/rule_eval_test.exs
This impl should not have been taking the absolute value of each operand, just the absolute value of their difference. 
To reproduce this problem, create a numeric input question with correct answer "Equal to"  0.02.
Then in preview or delivery, submit an answer of -0.02
=> [BUG FIX] Adjust float comparison [MER-1747]

assets/src/components/resource/objectives/ActivityLOs.tsx
Fixes a bug found in the activity bank editor (but actually applies to all InlineActivityEditors) for Multi Input questions with a single input where removing/changing an input could cause the partId to be missing from the objectives map, crashing the page.
This fix simply takes the same approach as the above `MultiPartSelection` component and initializes the `ObjectivesSelection` selection prop to empty array `[]` if no partId is found in the objectives map.
=> [MER 1763] activity bank crashes when a single part selection part id is missing

assets/src/data/activities/model/rules.ts
Fix for MER-1760: adjusts regexp in numerical rule matcher in the UI to recognize a number specified using scientific notation and a numeric answer rule. Allows either E or e and optional plus sign. 
This is a client-side UI issue -- the back-end rule engine processes these correctly.
=> [BUGFIX] MER-1760 make UI accept scientific notation in numeric match rule

assets/src/components/activities/multi_input/sections/AnswerKeyTab.tsx, assets/src/components/activities/short_answer/sections/TextInput.tsx, assets/src/data/activities/model/rules.ts
For MER-1762. Adds Equals Exactly and Equals Ignoring Case answer matching options for text input items.
The former maps to the "input equals {text}' rule which already existed. The latter is implemented by translating the pseudo-operator "equalsnocase" appropriately to and from regex-matching rule "input like {(?:i)escapedText}' at the rule level. 
Dealing with this mapping introduces a bit of complexity, but it is not too bad and seems to work as is. Still, code would be simpler and more uniform if an appropriate operator existed in the rule language. 
Note these expose a quirk of the behavior of the rule engine: It appears both equals and regex matches effectively do a "contains" match, satisfying the rule if the pattern appears anywhere in the input string. See MER-1761.
With this …
=> [FEATURE] MER-1762 add Equals Exactly and Equals Ignoring Case text answer matching options

lib/oli/delivery/evaluation/parser.ex, lib/oli/delivery/evaluation/rule.ex, test/oli/delivery/evaluation/rule_eval_test.exs
Add a new `iequals` operator to the rules engine for case-insensitive string comparison
=> [FEATURE] add iequals for case-insensitive string comparison to rules grammar

assets/src/components/activities/short_answer/sections/TextInput.tsx, assets/src/data/activities/model/rules.ts, lib/oli/delivery/evaluation/parser.ex, lib/oli/delivery/evaluation/rule.ex, test/oli/delivery/evaluation/rule_eval_test.exs
For MER-1765: This corrects behavior of the Equals ignoring case match operator to match against the whole input. Did this by recoding to use the newly added iequals rule, making the rule-handling code more uniform with other rules.
=> [BUGFIX] MER-1765 Equals ignoring case should match whole string

assets/src/apps/DeliveryApp.tsx, assets/webpack.config.js
The adaptive delivery mode was broken in two ways.
1. It was using the wrong redux store, and would crash upon launching.
2. The default light theme css (/css/delivery_adaptive_themes_default_light.css) was not being generated, leading to visual issues after 1. was fixed.  Most (all?) real lessons have custom css, so this one was limited in impact.
To reproduce:
1. Create an adaptive page
2. Open it in the editor
3. Attempt to preview the page
=> [BUGFIX] adaptive delivery theme css and redux store.

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/core/resource_access.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/contained_page.ex, lib/oli/delivery/sections/section_resource.ex, lib/oli/publishing.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/controllers/open_and_free_controller.ex, priv/repo/migrations/20230208185959_contained_pages.exs, test/oli/delivery/metrics/progress_test.exs
This PR adds the infrastructure needed to track and compute, efficiently, student progress.  
A new context `Oli.Delivery.Metrics` provides methods for calculating progress:
- For a specific container, in a section, for a specific student. 
- Across a collection of containers in a section for a specific student
- Across a collection of containers in a section for all enrolled students
The above calculations are done in one query, leveraging a new "contained_pages" schema, which always provides an up to date view of the recursively nested pages within all containers of a section.  This allows efficient joining and aggregation of progress that is now stored for a page, at the "resource_access" level. 
While these queries and this infrastructure are designed to be as efficient as possible, …
=> [FEATURE] Analytics infrastructure for progress [MER-1707]

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/custom_dnd/DragCanvas.tsx, assets/src/components/activities/custom_dnd/utils.ts, assets/src/components/activities/short_answer/sections/TextInput.tsx, assets/src/data/activities/model/rules.ts, lib/oli/delivery/evaluation/parser.ex, lib/oli/delivery/evaluation/rule.ex, test/oli/delivery/evaluation/rule_eval_test.exs
This addresses the following problem for converting legacy drag-and-drops to torus. Legacy DND questions are modelled as multi-input questions with a set of inputIDs = partIDs and base choiceIDs. Responses converted for torus come in as choice values of the form partID_choiceID, to represent some draggable being dropped on some target. 
Legacy layout attaches the partIDs to the draggables, and choiceIDs to the target areas, in effect treating each draggable as a question part you have to answer, with your choices for that part being the possible areas on which you can drop it.
The Torus implementation assumed partIDs would be associated with targets and choiceIDs with draggables, and the course-digest goes to some trouble to swap IDs to bring legacy layouts into this form. However, …
=> [ENHANCEMENT] Allow DND partIDs to be on EITHER targets or draggables MER-1749

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/custom_dnd/DragCanvas.tsx, assets/src/data/activities/DeliveryState.ts
This resets appropriate part state whenever an action causes a draggable to be detached from a target to which it had previously been attached (which would have submitted part and caused feedback to show when cell is focused). These are: moving a draggable that has already been dropped into one target (producing feedback) to another cell; moving a draggable out of the target table entirely; and moving a new draggable onto an existing one, bumping the existing one out of the target table. 
Added a new resetPart action to handle this case.
=> [BUGFIX] reset DND part state when draggable detached from target MER-1767

lib/oli/resources/collaboration.ex, lib/oli_web/components/delivery/discussion_board.ex, lib/oli_web/components/delivery/discussion_post.ex, lib/oli_web/components/delivery/nav_sidebar.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/page_delivery/discussion.html.heex, test/oli_web/controllers/page_delivery_controller_test.exs, test/support/test_helpers.ex
[MER-1696](https://eliterate.atlassian.net/browse/MER-1696)
This PR aims to shows a "Discussion" link in the left navigation bar, which when clicked takes the student to a view showing two groups of publications.  
- Summary of all their publications in all collaboration spaces.
- Summary of other students most recent publications in all collaboration spaces. 
We only need to think about some kind of pagination in case we want to show more than x amount of posts. Do you think it could be possible to do it in another ticket maybe @darrensiegel?
[MER-1696]: https://eliterate.atlassian.net/browse/MER-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1696] Student oriented summary view

assets/src/apps/authoring/components/EditingCanvas/AuthoringActivityRenderer.tsx, assets/src/components/activities/AuthoringElement.ts
1. Go into advanced authoring editor
2. Click a component
3. Move or resize the component
4. Click off the component
Expected: Component stays where you left it and is saved.
Actual: Component snaps back to original location / size
With the advanced authoring app being put into a shadow-dom container, a new class of potential bugs has surfaced having to do with how events bubble up. To fix these:
1. Events meant to bubble to the document must be marked as composable (see AuthoringElement.ts below)
2. Event handlers should not expect event.target to point to the element inside the shadow-dom as they get rewritten to the shadow root. (see AuthoringActivityRenderer.tsx below)
Note: the reason for this flow of data outside of normal react conventions is because AuthoringElement lives inside a …
=> [Bugfix] Moving components in advanced authoring was not saving

lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/attempts/page_lifecycle/ungraded.ex, lib/oli/delivery/metrics.ex
One final piece of the progress infrastructure:  
Page attempts are created for ungraded pages in two instances:
1. When a student visits a page for the very first time.
2. When a student returns to a page that they had already visited, but in the interim a new page publication has updated that page.  In this instance, we create a new page attempt for that new content. 
In both cases above, we must update the progress on the page.  That progress should be set to 100% if the page contains no activities, otherwise it should be set to 0%.
We do not want to do this for graded pages.  We want them to enter 100% after submission - and stay in that state even with further attempts are taken.
=> [ENHANCEMENT] update page progress at every ungraded page attempt start

assets/src/apps/delivery/Delivery.tsx, assets/src/apps/delivery/layouts/deck/IdleTimeOutDialog.tsx, config/config.exs, config/releases.exs, lib/oli_web/controllers/page_delivery_controller.ex
During merging the branch in the hotfix, for testing purposes, I lower the screen timeout value so that I can test it and make sure it's working. I forgot to change it to its original value.
=> Screen Idle Time-Out | Timer value issue

test/oli_web/live/admin_live_test.exs, test/oli_web/live/browse_updates_live_test.exs, test/oli_web/live/collaboration_live_test.exs, test/oli_web/live/community_live_test.exs, test/oli_web/live/discounts_live_test.exs, test/oli_web/live/failed_grade_sync_live_test.exs, test/oli_web/live/gradebook_view_live_test.exs, test/oli_web/live/ingest_live_test.exs, test/oli_web/live/institutions_live_test.exs, test/oli_web/live/manage_source_materials_live_test.exs, test/oli_web/live/payments_live_test.exs, test/oli_web/live/products_test.exs, test/oli_web/live/progress/student_resource_view_live_test.exs, test/oli_web/live/progress_live_test.exs, test/oli_web/live/publish_live_test.exs, test/oli_web/live/publisher_live_test.exs, test/oli_web/live/sections/admin_index_live_test.exs, test/oli_web/live/sections/edit_live_test.exs, test/oli_web/live/sections/invite_view_test.exs, test/oli_web/live/sections/overview_live_test.exs, test/oli_web/live/select_source_live_test.exs, test/oli_web/live/student_view_live_test.exs, test/oli_web/live/system_message_live_test.exs, test/oli_web/plugs/redirect_plug_test.exs
This PR reduces `mix test` time by 15% aprox by configuring tests to run concurrently with tests of other modules (see [docs](https://hexdocs.pm/ex_unit/1.13.4/ExUnit.Case.html))
**With concurrency configured:**
**Without concurrency configured:**
=> Improve mix test performance

assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx, assets/src/apps/authoring/components/RightMenu/RightMenu.tsx
The advanced-authoring right menu was getting rather long and abusing react's useEffect hook making it difficult to modify it for the new flowcharting feature. This PR refactors the part property editor.  The only user-visible change being the removal of a couple buttons that had no function.
=> Refactor part property editor

lib/oli/delivery.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/blueprint.ex, lib/oli/delivery/sections/section.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/components/delivery/nav_sidebar.ex, lib/oli_web/controllers/open_and_free_controller.ex, lib/oli_web/plugs/require_exploration_activities.ex, lib/oli_web/templates/layout/page.html.heex, lib/oli_web/templates/page_delivery/discussion.html.heex, lib/oli_web/templates/page_delivery/exploration.html.heex, priv/repo/migrations/20230302190535_contains_explorations.exs, test/oli/delivery_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/live/remix_section_test.exs, test/support/test_helpers.ex
[MER-1774](https://eliterate.atlassian.net/browse/MER-1774)
This PR adds functionality to not show access to "Explorations" when the section does not have any resource of this type. 
When this happens, both the access from the left sidebar and the Windowshade are hidden. 
Also, thanks to the contribution of @nicocirio, this PR includes the fix for the error that happens when the last resource is removed from the content of a section.
[MER-1774]: https://eliterate.atlassian.net/browse/MER-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1774] Section does not show access to Explorations

assets/src/components/common/MathJaxFormula.tsx
Bug:
1. Have a formula in a paragraph that uses the cancel extension.
2. Have a multi-input component below that. In the "explanation" section, add a formula.
Expected: Formula in 1. renders with cancels.
Actual: Formula in 1. renders, but without the cancel extension
Mathjax only supports rendering a single window.MathJax.typesetPromise at a time.
We have a MathJaxFormula component that did some promise-handling to make sure subsequent calls to typesetPromise would wait for the first to finish. 
That code worked fine in a single JS context.
But, it relied on a global variable. If you use web-components, than a MathJaxFormula in the main app doesn't share that global variable space with the web component MathJaxFormula and the synchronization code breaks.
This PR gets rid of the global …
=> [Bugfix] Webcomponents now share the same global mathjax promise. [MER-1782] [MER-1779] 

lib/oli/delivery.ex, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/course_content_panel.ex, lib/oli_web/components/delivery/instructor_dashboard.ex, lib/oli_web/components/delivery/utils.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/common/card_listing.ex, lib/oli_web/live/delivery/instructor_dashboard/manage_live.ex, lib/oli_web/live/delivery/select_source.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/live/delivery/instructor_dashboard/content_live_test.exs, test/oli_web/live/delivery/instructor_dashboard/manage_live_test.exs, test/oli_web/live/delivery/instructor_dashboard/other_live_test.exs, test/oli_web/live/progress_live_test.exs
This PR fixes the following:
- An issue where root_section_resource is nil during section creation from a project
- Changes the "Other" tab to "Manage"
- Remove redundant Manage Section button from course content outline
=> [BUGFIX] Fix root_section_resource nil

assets/styles/common/previous_next_nav.scss, lib/oli_web/components/delivery/learning_opportunities.ex, lib/oli_web/components/delivery/page_delivery.ex, lib/oli_web/components/delivery/up_next.ex, lib/oli_web/components/delivery/utils.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/page.html.heex, test/oli_web/plugs/maybe_gated_resource_test.exs
This PR removes the page read by and time estimate by hiding those elements when they are not provided
=> [ENHANCEMENT] do not show page read by or time estimate when not provided

assets/styles/common/elements.scss
This PR sets table delivery styles to fit a table's width according to its content.
Closes #3323
=> [BUGFIX] size table according to its content

lib/oli/activities/transformers/variable_substitution/common.ex, test/oli/activities/transformers/variable_substitution_test.exs
Handles a case where variables are lists by converting to a pure string representation to allow substitution to succeed.
=> [BUG FIX] handle list (array) values in json [MER-1784]

lib/oli_web/live/resources/pages_view.ex
Root cause was a change in the other spot where this is primarily used did not get applied to this view.  Added a comment instructing developers that future changes need to be synced here.
=> [BUGFIX] Fix display of options modal in all pages view [MER-1816]

lib/oli/publishing.ex, lib/oli_web/live/products/products_view.ex, lib/oli_web/templates/layout/_project_sidebar.html.eex, test/oli_web/live/products_test.exs
Shows a message that products cannot be created until the project is published
=> [MER-1818] Prevent products from being created before a course is initially published

assets/src/components/video_player/VideoPlayButton.tsx
For embedded Videos, the "play / pause" button was designed to change its icon when you click play or pause - to show the other icon. As in, when I'm playing a video I should see the button to "pause" the video, and vice-versa. 
This was only ever showing the pause icon.
Root cause is related to how font awesome replaces the `<i>` element with svg.  React could not update that when the `paused` state changed.  Instead, by assigning a unique `key` to the parent `<button>` we trick React into replacing that entire node, which fixes the problem.
=> [BUG FIX] Fix button toggling in video player [MER-1825]

lib/oli/delivery/page/page_context.ex, lib/oli_web/controllers/page_delivery_controller.ex, test/oli/resources/collaboration_test.exs
Admins were no longer able to view arbitrary student attempts in course sections due to changes in how we are determining the type of user.  Reworked this to expand the `create_for_review` interface to take a fourth argument, `is_admin?`, thus allowing the case for when a user is an admin to be handled correctly (and efficiently, as it avoids the DB call to `get_user_roles`).
Also found a test that had a couple of unused aliases.
=> [BUG FIX] Restore ability for admins to review attempts [MER-1830]

lib/oli_web/router.ex
Root cause was that the scope for the new instructor dashboard routes did not allow admins to access them.
=> [BUG FIX] Allow admins to access new manage section routes [MER-1819]

lib/oli_web/live/common/utils.ex, lib/oli_web/live/sections/enrollments_table_model.ex, lib/oli_web/live/sections/gating_and_scheduling/table_model.ex
Instructors probably shouldn't be creating student exceptions for guest users, but if they do, there was no way to manage that exception (even just to delete it) since the table of exceptions was not rendering a name which allowed the link to be clickable. 
I took this opportunity to adjust how we render names for guest users.  Previously we rendered "Unknown Unknown", now it will read "Guest Student".
=> [BUG FIX] Allow management of guest student gating exceptions [MER-1829]

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/file_upload/FileUploadDelivery.tsx, lib/oli_web/live/progress/page_attempt_summary.ex
Both FileUpload and CustomDND activities had code that was not robust against restoring submissions that were incomplete.   This would throw a client side error and effectively render nothing for these activities while in review mode. 
I also fixed the inability to review an attempt that is in a `submitted` state.  It simply needed to have its contents wrapped in a `<a>` element.
=> [BUG FIX] Allow upload and dnd activities to be reviewable in all cases [MER-1827]

lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/assignments/assignment_card.ex, lib/oli_web/components/delivery/assignments/assignments_list.ex, test/support/test_helpers.ex
A postgrex error `** (Postgrex.Error) ERROR 22007 (invalid_datetime_format) invalid input syntax for type date: "null"` was being thrown when the assignments view attempted to load an assignment that had a gating condition other than type `:scheduled`.  
The solution was restrict the query to only returning gating conditions of type `:scheduled`.  I added unit test support to cover this case. 
Also, I noticed that there was no way to access an assignment from this view.  I changed "Quiz" button (which did nothing) to "Open" which now launches that assignment.
=> [BUG FIX] Fix assignments view rendering when assignment has a non schedule GatingCondition [MER-1839]

lib/oli_web/live/delivery/instructor_dashboard/discussions_live.ex, lib/oli_web/live/delivery/remix_section.ex
The "Approve" and "Reject" buttons were not launching their respective modal confirmation dialogs due to a missing rendering of that modal. 
I also noticed that approving and rejecting did not live update the view of a discussion board.  I added the necessary broadcast message so that after an instructor approves a pending message all students that happen to be on the page see that post appear, without a hard refresh. 
There is a minor tweak here to course remix, to disable the navigation button when the user is at the top-level of the hierarchy.
=> [BUG FIX] Live update after post approvals [MER-1838]

assets/css/app.css, assets/css/table.css, assets/css/text.css, lib/oli/delivery/metrics.ex, lib/oli_web/components/delivery/instructor_dashboard.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/common/paged_table.ex, lib/oli_web/live/common/search_input.ex, lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/common/text_search.ex, lib/oli_web/live/delivery/instructor_dashboard/students_live.ex, lib/oli_web/live/sections/enrollments/enrollments_view.ex, lib/oli_web/live/sections/enrollments_table_model.ex, test/oli/delivery/metrics/progress_test.exs, test/oli_web/live/delivery/instructor_dashboard/students_live_test.exs, test/oli_web/live/publisher_live_test.exs, test/oli_web/live/sections/enrollments_view_test.exs
[Link to ticket](https://eliterate.atlassian.net/browse/MER-1712)
The ticket says:
> Another key change that we need to the existing “Manage enrolled students” view is what view the user is routed to when they click on a student’s name.  Currently, instructors are routed to the “Student progress view”, which is a listing of all course pages and the progress for that student. Instead, we need to route the user to the “Student details view” for that student. 
The Students Details view has not yet been developed, so I left the link unchanged. 
When that view gets developed we will be able to update the link
=> [MER-1712] Instructor portal students view

lib/oli/delivery.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/components/delivery/exploration_card.ex, lib/oli_web/components/delivery/exploration_list.ex, lib/oli_web/components/delivery/exploration_shade.ex, lib/oli_web/templates/layout/page.html.heex
There were a couple things broken with Explorations.
1. The impl did not recognize explorations that lived outside the hierarchy of the course. This is actually going to be the pattern that most courses that use explorations will follow. Fix here was to remove the `numbering_level > 0` portions of relevant queries
2. The rendering of explorations included hard-coded information and did not allow the user to "click to open"
=> [BUG FIX] fix explorations

lib/oli/delivery/snapshots/worker.ex, lib/oli/interop/ingest/processor/activities.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/live/snapshots/snapshots_view.ex, lib/oli_web/router.ex
Snapshot creation fails when there is an activity that duplicates an objective for one part.  This can only happen when an objective is ingested in this state.  
This PR does the following:
1. Makes the snapshot generation code in `worker.ex` robust to duplicates, by deduping the part specific list of objectives, prior to snapshot insertion.
2. Fixes the activity ingest processor to dedupe objective ids
3. Adds a new LiveView "Manage Snapshot Records", which is Admin accessible only, that detects when there are snapshot records missing for a specific course section and then allows these snapshot records to be created. 
To test the LV out end-to-end, the easiest thing to do is to create a course section with a page that have a couple of MCQ questions.  Then, as a guest student, access that …
=> [BUG FIX] Fix snapshot creation when objectives are duplicated

lib/oli_web/common/mathjax_script.ex
Adjusts MathJax configuration to allow the autoload extension to be used to automatically load other tex extensions as needed. This fixes issue seen on the \boldsymbol macro, enabling the macro to trigger autoload the boldsymbol tex extension without use of \require{boldsymbol}. Also the \style macro which should trigger autoload the html extension. 
MathJax documentation suggests the tex-mml-chtml combined component we are using includes the autoload package with it so that \requires are not needed for the macros above. But it seems autoload must still be listed in the configured tex packages list before MathJax will use it.
=>  [BUGFIX] Config MathJax to autoload standard extensions[MER-1863][MER-1869]

assets/css/bootstrap-shims.css, lib/oli/delivery/metrics.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/ingest/ingestv2.ex
- fixes an issue where learner progress was never showing up
- improves the v2 ingest processing messages
- removes disc from page-item <li element
=> [BUG FIX] Learner progress not showing

assets/src/apps/authoring/components/PropertyEditor/custom/AccordionTemplate.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/CustomFieldTemplate.tsx, assets/src/apps/authoring/components/PropertyEditor/schemas/bankScreen.ts, assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts, assets/src/apps/authoring/components/PropertyEditor/schemas/part.ts, assets/src/apps/authoring/components/PropertyEditor/schemas/screen.ts, assets/src/components/activities/adaptive/components/authoring/ScreenAuthor.tsx, assets/src/components/parts/janus-popup/schema.ts
This PR fixes a bunch of minor styling issues with the advanced authoring property panel. Before & After screenshots below.
Screen panel:
Question bank:
Lesson:
Components:
Feedback Editor:
=> [Bugfix] Fixed component panel styling

assets/styles/adaptive/layout/check-container.scss
In delivery mode, the default theme for advanced authoring was not displaying the toolbar correctly.
Before:
After:
=> [Bugfix] Fixed advanced authoring bottom delivery toolbar styles

assets/css/table.css, lib/oli_web/components/delivery/instructor_dashboard.ex, lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex, lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/common/table/column_spec.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/grades/gradebook_table_model.ex, lib/oli_web/live/grades/gradebook_view.ex, test/oli_web/live/delivery/instructor_dashboard/quiz_scores_tab_test.exs, test/support/test_helpers.ex
[MER-1807](https://eliterate.atlassian.net/browse/MER-1807)
This PR adds a list of student quiz scores contained in a course section, within the "Quiz Scores" tab.
Here are listed the student scores obtained in each of the quizzes.
When a student scores less than 50% on any of their quizzes their entry is highlighted in the table.
The Gradebook view is also modified so that it uses the component developed for this tab and respects the same design.
[MER-1807]: https://eliterate.atlassian.net/browse/MER-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1807] Instructor portal quizzes tab

assets/src/apps/authoring/store/app/slice.ts
Bug: Launch advanced authoring.
Expected: It launches
Actual: It crashes with this in the console:
```
Uncaught ReferenceError: Cannot access 'saveActivity' before initialization
at Module.saveActivity (rules.ts:100:12)
at extraReducers (slice.ts:196:21)
at executeReducerBuilderCallback (redux-toolkit.esm.js:554:1)
at createSlice (redux-toolkit.esm.js:618:1)
at ./src/apps/authoring/store/app/slice.ts (slice.ts:115:43)
at __webpack_require__ (bootstrap:19:1)
at ./src/apps/authoring/store/activities/actions/saveActivity.ts (rules.ts:100:12)
at __webpack_require__ (bootstrap:19:1)
at ./src/apps/authoring/BottomPanel.tsx (AuthoringFlowchartPageEditor.tsx:77:21)
at __webpack_require__ (bootstrap:19:1)
```
I'm unsure of the exact cause here, it looks like an odd circular-import causing …
=> [Bugfix] Advanced author crash on startup.

assets/css/table.css, lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/components/helpers.ex, lib/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, lib/oli_web/live/grades/gradebook_table_model.ex, lib/oli_web/live/grades/gradebook_view.ex, test/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab_test.exs
[MER-1808](https://eliterate.atlassian.net/browse/MER-1808)
This PR adds the list of quizzes with their respective scores for a given student to the quiz scores tab on the student's dashboard for the instructor.
This lists the scores obtained for the students in the quizzes they completed.
When a student scores less than 50% on any of their quizzes, their entry is highlighted in the table.
[MER-1808]: https://eliterate.atlassian.net/browse/MER-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1808] Quiz scores tab for student dashboard

lib/oli_web/components/delivery/progress/progress.ex, lib/oli_web/components/delivery/progress/student_progress_table_model.ex, lib/oli_web/live/delivery/student_dashboard/components/progress_tab.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, test/oli_web/live/delivery/student_dashboard/components/progress_tab_test.exs, test/support/test_helpers.ex
[MER-1725](https://eliterate.atlassian.net/browse/MER-1725)
This PR adds a view showing the progress made by a specific student in a course section to the progress tab on the student's dashboard for the instructor.
It lists all pages and grades the student has in the course section.
[MER-1725]: https://eliterate.atlassian.net/browse/MER-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1725] Student progress details tab

assets/src/components/activities/ordering/OrderingDelivery.tsx
This supports the Play All function for ordering questions whose choices contain audio elements. This is used in legacy OLI language courses for questions asking to listen to conversation audio and then put audio clips in from it in correct order. When any choices contain audio, the activity will show a Play All button which when clicked, plays each choice's audio in the current order of choices. While playing it changes to "Stop Playing All" and can be used to interrupt the playback.
=> [ENHANCEMENT] play all function for ordering audio choices [MER-1804]

assets/css/table.css, lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli_web/live/users/user_detail_view.ex, lib/oli_web/live/users/user_enrolled_sections.ex, lib/oli_web/live/users/user_enrolled_table_model.ex, test/oli/sections_test.exs, test/oli_web/live/users/user_detail_view_test.exs
[MER-1907](https://eliterate.atlassian.net/browse/MER-1907)
This PR adds a new section within the user details view, to show the course sections in which a given user is enrolled.
In this section a table is rendered showing the required data. This table is sortable, pageable and has a search field to search by the title of a course section.
The title of each course section listed is a link to the user details view for that specific section.
[MER-1907]: https://eliterate.atlassian.net/browse/MER-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1907] All course sections user enrolled

assets/src/components/ContentTable.tsx, assets/src/components/activities/common/delivery/inputs/DropdownInput.tsx, assets/src/components/editing/elements/list/listActions.tsx, assets/src/data/content/model/elements/factories.ts, assets/styles/common/elements.scss, assets/styles/common/list.scss, assets/styles/delivery/index.scss, assets/styles/delivery/multi-input.scss, lib/oli/interop/rewire_links.ex, lib/oli/rendering/content/html.ex, test/oli/rendering/content/html_test.exs
This fixes 4 of the bugs identified in MER-1941
Unordered lists without a style attribute now follow a pattern of disc, circle, square, for each level of indentation. Furthermore, inserting a new list, now creates a list without the style set so it takes that default behavior for all new lists.
Previously, changing the style of list would change it for all parent & child lists. Now it only affects the single closest ancestor list to the cursor. This allows each level to be customized by the author and provides a much more natural user experience.
In tables with borders turned on, borders between the cells of headers are again present.
In multi-input questions with dropdowns, those dropdowns are now auto-sized based upon their content. Previously they were a fixed 160px wide.  This makes …
=> [MER-1941] Delivery style bugs

lib/oli_web/live/users/user_enrolled_table_model.ex
** (CaseClauseError) no case clause matching: :instructor
Backtrace: lib/oli_web/live/users/user_enrolled_table_model.ex:105 in OliWeb.Users.UserEnrolledTableModel.render_payment_status/3
See the above in AppSignal.  Root case is that payment status is being reported as `:instructor` for users that are instructors in a paid section.  Added a catch all clause to make this future proof.
=> [BUG FIX] Enrolled users table model over constrains payment status pattern

lib/oli/delivery/sections.ex
There is an issue with how the logic clauses were structured in the query to fetch the required student survey.  The final clause needed to be part of an OR.  This issue is causing errors when course projects are duplicated. Their resources are shared across them, which ends up returning more than 1 record.
=> [BUG FIX] Fix query to fetch required survey

assets/src/components/common/Navbar.tsx, lib/oli_web/components/delivery/buttons.ex, lib/oli_web/templates/shared/_help.html.eex, lib/oli_web/templates/shared/_help_button.html.eex
Changes the method to launch the tech support modal, so that recaptcha is properly initialized and the request can be sent.
=> [BUG FIX] Allow tech support window to be initialized correctly

lib/oli_web/live/grades/gradebook_table_model.ex, test/oli_web/live/delivery/instructor_dashboard/quiz_scores_tab_test.exs, test/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab_test.exs
The students and the instructor dashboard "Quiz Scores" tab crash when a student hasn't yet finished the quiz.
This PR fixes that bug.
=> [BUG FIX] Fix Quiz Tab

lib/oli_web/live/delivery/student_dashboard/components/helpers.ex
This PR fixes the avatar size for students without picture.
=> Fix avatar size

assets/src/apps/authoring/components/Flowchart/rules/rule-compilation.ts
1. Create a flowchart based lesson 
2. Author the start & end screens
3. Preview the lesson
4. Progress past the last screen
Expected: End of lesson message is displayed, lesson ends
Actual: Lesson freezes up, next button goes blank
Cause: The end-screen needs a janus rule to navigate to the next screen, which the delivery engine will intercept since there is no next-screen and display the exit message & handle the completion.
=> [MER-2004] [Bugfix] Allow learner to complete flowchart based lessons

lib/oli_web/live/projects/overview_live.ex
Somehow the script url for recaptcha on the overview page got mangled, making it impossible to invite collaborators. This fixes the src field.
=> [BUG FIX] fix recaptcha url

lib/oli_web/components/delivery/assignments/assignment_card.ex, lib/oli_web/components/delivery/assignments/assignments_list.ex, lib/oli_web/controllers/page_delivery_controller.ex
In prepping to demo this, discovered and fixed a few issues:
1. `gate_type` was still being used to determine gate type.  Now only `:scheduling_type` from the SR is needed
2. Percentages were shown as `0.0 %` to `1.0 %`.  Multiplied by `100` to fix
3. DateTimes were not formatted correctly
=> [BUG FIX] Fixes for assignments view rendering problems

lib/oli_web/live/projects/overview_live.ex
Fix a second problem in the overview page where the liveview was rendering over top of the captcha
=> [BUG FIX] ignore captcha in liveview

assets/src/phoenix/finalize.ts, lib/oli/delivery/attempts/page_lifecycle.ex, lib/oli/delivery/attempts/page_lifecycle/finalization_summary.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/attempts/page_lifecycle/ungraded.ex, lib/oli/utils/db_seeder.ex, lib/oli/utils/seeder/attempt.ex, lib/oli_web/controllers/api/page_lifecycle_controller.ex, lib/oli_web/live/ingest/ingestv2.ex, lib/oli_web/templates/page_delivery/page.html.heex, test/oli/delivery/attempts/page_lifecycle_test.exs, test/oli/delivery/submission_test.exs
Adds the ability to reset all activities on an ungraded page by finalizing the resource attempt and creating a new one on subsequent access, similar to how graded pages work except no scores are recorded.
=> [MER-1988] add ability to reset practice page attempt

assets/src/components/editing/editor/handlers/lists.ts, assets/src/components/editing/editor/normalizers/lists.ts, assets/src/components/editing/elements/commands/toggleTextTypes.ts, assets/src/components/editing/elements/image/imageActions.tsx, assets/src/components/editing/elements/list/listActions.tsx, assets/src/components/editing/slateUtils.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/BlockSettings.tsx, assets/src/data/content/model/elements/factories.ts, assets/src/data/content/model/elements/types.ts, assets/src/data/content/model/schema.ts, assets/styles/common/elements.scss, priv/schemas/v0-1-0/content-element.schema.json
This PR allows block elements inside list items.
One important change to note here, is I had to start wrapping text nodes inside list items in a paragraph. That will happen in a normalization pass for any existing content the first time it's edited. I haven't seen any visual differences, but it's a possibility.
Since pressing enter in a LI crates a new list item, an author can now create multiple paragraphs inside an LI by pressing shift-enter. 
I am not currently inserting leading and trailing paragraphs around block items. So if you have some text, then insert a block image, it will be difficult to type in the same list item after that image.  I think this best preserves the visual appearance we want in most scenarios. An author can work around this by typing in the content they want …
=> [MER-1978] Block list items

lib/oli/delivery/paywall.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/enrollment.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, priv/repo/migrations/20230518010722_add_status_in_enrollment.exs, test/oli_web/live/delivery/instructor_dashboard/students_tab_test.exs
[MER-1914](https://eliterate.atlassian.net/browse/MER-1914)
This PR adds a dropdown to filter students on the `students` tab in the instructor dashboard.
This new filter allows filtering students enrolled in the section, as well as users who are not students but are also enrolled in that section.
Also, if the section requires a payment, it allows filtering by those students who have paid, those who have not paid and those who have a grace period.
**_Students enrolled in the section_**
**_Non-students enrolled in the section_**
**_Students who have paid for the section_**
[MER-1914]: https://eliterate.atlassian.net/browse/MER-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1914] Enrolled students filter instructor dashboard

assets/src/components/activities/common/delivery/evaluation/Evaluation.tsx
Removes the "per part" point display, in favor of only the graphic.  This allows the "Points: 0 out of 1" to be less confusing and not redundant.
=> [FEATURE] Remove redundant points display [MER-1986]

lib/oli_web/controllers/api/page_lifecycle_controller.ex
After completing a graded page attempt, the review attempt now displays, not the page that lists all attempt history. 
I preserved in a comment the path for the attempt history, as very soon that will need to be the path used when "review answers" for a page is not allowed.
=> [FEATURE] Redirect to display review attempt page [MER-1999]

lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/browse.ex, test/oli/sections_test.exs
[MER-1913](https://eliterate.atlassian.net/browse/MER-1913)
This PR modifies the `unenroll` function to avoid deleting the record of a specific user in the enrollment table and instead modifying the enrollment status for that user.
The goal is to perform a soft delete and not lose the information of that enrollment.
Also the enrollment status check is added in several queries in which it is necessary to know if the user is enrolled or not in a section.
_*** Please let me know if there is any query that should not have this enrollment status check or if there is any query that does not have it and should have it._
[MER-1913]: https://eliterate.atlassian.net/browse/MER-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1913] Change Unenroll feature to preserve all data

lib/oli_web/live/sections/edit_view.ex, lib/oli_web/live/sections/open_free_settings.ex, lib/oli_web/live/sections/start_end.ex
Moves the UX for editing start and end section dates to a spot in the edit dialog that always displays.
=> [ENHANCEMENT] Ensure editing of start end dates available to both LTI and open and free [MER-1984] [MER-1953]

lib/oli/delivery/attempts/page_lifecycle/ungraded.ex
Root cause was the approach did not use the correct object for calculating how many activities.
=> [BUG FIX] Fix progress calculation when page has no activities [MER-2039]

assets/css/table.css, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/content/content_table_model.ex, lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/components/helpers.ex, lib/oli_web/live/delivery/student_dashboard/initial_assigns.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, lib/oli_web/live/sections/enrollments_table_model.ex
Removes all "Student Engagement" references from UI and code, since we are not moving forward with that analytic
In testing my changes, I caught a bug in how the Learning Objectives tab was populated.  It only showed LO's that were actually attached to pages.  I removed that constraint so that it shows all LOs.
=> [ENHANCEMENT] Remove engagement and fix objectives display bug [MER-1706]

assets/src/components/activities/oli_embedded/OliEmbeddedDelivery.tsx
This is a fix to a bug where, for some content layout settings, the iframe height results in a runaway height growth loop. For these cases, it limits the growth to 700px
=> [BUG FIX] Fix uncontrolled iframe height growth bug

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
While fixing the recent production issue I found out that `activity?.authoring?.parts?` is only available in 'Preview' and not in 'Open & Free'. `activity?.authoring` is null. 
I have tested all the different tickets that are related to this and they all are working fine.
=> MER-1915 | MER-1834

lib/oli_web/live/objectives/objectives.ex
This PR fixes an issue on the objectives page where if a `nil` item exists in an objectives children revisions, then the objectives page reloads infinitely.
=> [BUG FIX] filter out nil children when encountered on objectives

lib/oli/accounts/schemas/user.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/enrollment.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/sections/enrollments/enrollments_view.ex, lib/oli_web/live/sections/enrollments_table_model.ex, test/oli_web/live/delivery/instructor_dashboard/students_tab_test.exs
[MER-1948](https://eliterate.atlassian.net/browse/MER-1948)
This PR adds a column to show the `payment status` for users in the table that is rendered within the `students` tab on the `instructor dashboard`.
In addition, this new column is also shown in the enrollments view for an author/admin.
[MER-1948]: https://eliterate.atlassian.net/browse/MER-1948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1948] Add payment status to enrolled students table

assets/src/apps/scheduler/ScheduleGrid.tsx, assets/src/apps/scheduler/ScheduleLine.tsx, assets/src/apps/scheduler/schedule-reset.ts, assets/test/scheduler/schedule-reset_test.ts
1. You can schedule top-level pages now.
2. The schedule reset functionality now takes the number of pages into account when laying out a schedule to size items more appropriately.
=> [MER-2056] Schedule top-level pages

lib/oli_web/live/delivery/student_onboarding/wizard.ex, test/oli_web/live/delivery/onboarding_wizard/student_onboarding_wizard_test.exs
Removed two chemistry references. Added some variety to the underlying test infra to ensure it is data driven.
=> [BUG FIX] Remove hardcoded chemistry references [MER-2088]

lib/oli/delivery/attempts/core.ex
This original query went thru several joins so that it could only return part attempts from `snapshots` that pertain to a certain project. The field `project_id` was later added directly to the `snapshots` schema, but this query was never updated to take advantage of that. 
`EXPLAIN` shows a halving of the complexity of this query.  From `68` down to around `31` total cost.  There are many intermediate steps that it also removed, including a potentially expensive sort on revisions.
=> [BUG FIX] optimize query knowing that project_id is now part of the snapshot [MER-2090]

lib/oli/delivery/paywall/payment.ex, lib/oli_web/components/delivery/actions/actions.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, priv/repo/migrations/20230530172546_add_bypassed_by_field.exs, test/oli_web/live/delivery/student_dashboard/components/actions_tab_test.exs
[MER-1955](https://eliterate.atlassian.net/browse/MER-1955)
This PR adds the possibility for an admin user to bypass a student's payment. This new functionality is added in the actions tab for the student's dashboard.
If the student has already made a payment the button to bypass payment will be disabled.
[MER-1955]: https://eliterate.atlassian.net/browse/MER-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-1955} Bypass payment for a student

guides/starting/developer.md
**Addressing issue #3611**
Broken link to LTI configuration page on https://simon-initiative.github.io/oli-torus/developer.html
**Proposed Change:**
Changes what looks to be a stale or incorrect link to https://github.com/Simon-Initiative/oli-torus/wiki/Torus-LTI-1.3-Manual-Configuration which does not exist to https://github.com/Simon-Initiative/oli-torus/wiki/Torus-LTI-1.3-Configuration
**Alternatives:**
No other relevant documents seem to exist within the wiki, so the assumption is that the new link was the intended one.
**Verification:**
I used the github online editor to make the change which includes a preview feature to verify that the link points to the existing document.
=> fix: Update developer.md to fix a link #3611

lib/oli_web/router.ex
There were three places in the router where the `maybe_gated_resource` plug was being used that didn't need to exist.  I've removed those.
But in the end, left the plug in place to guard page access as a student, even for instructors. There's a bit too much work to adjust at this point of the release to allow for instructors to bypass hard gates.  Given that they can bypass hard gates to "Access as an instructor" (which is now the default and more prominent option in the course content browser), this is a decent workaround for now.
=> [ENHANCEMENT] Allow preview of gated resources [MER-1921]

assets/src/components/editing/editor/Editor.tsx, assets/src/components/editing/editor/handlers/deleteblock.ts
Previously, it was difficult to delete a table from core authoring. Now, all three of these interactions should work:
1. Place the cursor immediately after the table, press backspace, the table should be removed.
2. Place the cursor immediately before the table, press delete, the table should be removed
3. Internally highlight multiple cells and press delete, the table should be removed
=> [MER-2085] Make it easier to delete tables

lib/oli/delivery/attempts/core.ex, lib/oli/delivery/metrics.ex, lib/oli/delivery/recommended_actions.ex, lib/oli_web/components/delivery/recommended_actions.ex, test/oli/delivery/metrics/progress_test.exs, test/oli_web/live/delivery/instructor_dashboard/overview/recommended_actions_tab_test.exs
Encountered and fixed a few things when prepping for a demo:
1. Course progress calculation breaks on a page that ONLY contains survey activities.  
2. `section_has_scheduled_resources` logic was inverted and reported that no schedule existed when one did exist
=> [BUG FIX] fixes to make demo work

lib/oli_web/components/delivery/exploration_shade.ex, lib/oli_web/components/delivery/section_title.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/layout/page.html.heex, lib/oli_web/templates/page_delivery/assignments.html.heex, lib/oli_web/templates/page_delivery/discussion.html.heex, lib/oli_web/templates/page_delivery/exploration.html.heex, lib/oli_web/templates/page_delivery/index.html.heex, test/oli_web/controllers/page_delivery_controller_test.exs
[MER-2089](https://eliterate.atlassian.net/browse/MER-2089)
This PR adds the course section title for all student views. 
When the view displays the "Your Exploration Activities" top bar the title is added to that bar.
If the view does not contain this component, the course section title is added in the same place with an identical component.
[MER-2089]: https://eliterate.atlassian.net/browse/MER-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-2089] Display course section title student views

assets/src/apps/SchedulerApp.tsx, assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx, assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/custom_dnd/DragCanvas.tsx, assets/src/components/activities/file_upload/FileUploadDelivery.tsx, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/image_hotspot/ImageHotspotDelivery.tsx, assets/src/components/activities/likert/LikertDelivery.tsx, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/oli_embedded/OliEmbeddedDelivery.tsx, assets/src/components/activities/ordering/OrderingDelivery.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/components/activities/vlab/VlabDelivery.tsx, assets/src/data/activities/DeliveryState.ts, assets/src/state/store.ts
This fixes an issue described in MER-1974 / #3506 where, in delivery mode, moving the dropped tile around after the initial drop would sometimes lead to feedback not being triggered.
The root problem was that the custom dnd activity was resetting the part attempt, and then calling resetAndSubmitPart without waiting for the part attempt reset to finish. Most of the time, that would work out just fine. Sometimes, the second call finished before the first. In those cases, the order of the part attempts in the DB would be backwards from what was expected, and the server call to submit the next attempt would fail since it only looks for the latest attempt record.
Preview mode continues to only work for the first drop of each tile. That was the behavior before this fix and I left that as-is …
=> [MER-1974] custom dnd race condition

mix.exs
Marks the master branch as v0.24.0, which is a more accurate representation of the version being developed that will be displayed on QA servers
=> [CHORE] bump version to 24

assets/src/components/editing/editor/Editor.tsx, assets/test/multi_input/multi_input_authoring_test.tsx
Choices in a multiple choice activity which only contain a single image in their content are not editable without completely removing the image first. This is likely because these content blocks need to be wrapped in a higher level content item, such as a paragraph.
Fixed this by forcing a normalization of the doc on opening it in the editor.
=> [MER-2135] Choices migrated with only a single image are not editable in torus

assets/src/components/editing/elements/link/LinkElement.tsx, assets/src/components/editing/elements/link/LinkModal.tsx, assets/src/components/editing/elements/webpage/WebpageModal.tsx, assets/src/components/editing/elements/webpage/WebpageSettings.tsx, assets/src/components/editing/elements/webpage/webpageActions.tsx, assets/src/components/media/UrlOrUpload.tsx, assets/src/data/content/model/elements/types.ts, lib/oli/authoring/media_library.ex, priv/schemas/v0-1-0/content-element.schema.json
Now, both links and webpages (iframes) in core authoring allow you to select a destination from the media library (including uploading files to use)
I modified the media library S3 upload to add a content-type to make viewing uploaded files in iframes work correctly, otherwise it just wants to download them. 
There is a bit of tension between the desire to have a link that downloads a file, vs. a link that opens in a new tab. Here's where I landed:
1. Links to media library uploads from the past will download (undesirable, but reasonable)
2. IFrames to media library uploads from the past will download (undesirable and useless)
3. Links to new media library items will do the browser-default behavior. Generally:
- Images, Videos, Audio, PDF will open in a new browser tab 
- HTML files will …
=> [MER-2075] Links and Iframes from media library

lib/oli_web/templates/page_delivery/_previous_next_nav.html.eex, lib/oli_web/views/page_delivery_view.ex
Link to the story [MER-2113](https://eliterate.atlassian.net/browse/MER-2113)
With these changes, if the user is on a page that is outside of the hierarchy, when they click the "Complete" button, the tab will close
[MER-2113]: https://eliterate.atlassian.net/browse/MER-2113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2113] Fix complete course button for pages outside of the hierarchy

assets/src/hooks/before_unload.ts, lib/oli/delivery/hierarchy/hierarchy_node.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/live/delivery/remix/entry.ex, lib/oli_web/live/delivery/remix_section.ex, lib/oli_web/live/delivery/remix_section.html.heex, lib/oli_web/live/products/details/content.ex, lib/oli_web/router.ex, test/oli_web/live/remix_section_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-1985)
If users modify the curriculum but they don't save the changes, they will get a browser warning when they try to navigate to the "Edit Page" (or any other page)
=> [IMPROVEMENT][MER-1985] Add 'Edit Page' link to pages in customize product content page

lib/oli_web/live/products/payments/tabel_model.ex, lib/oli_web/live/sections/overview_view.ex, test/oli_web/live/payments_live_test.exs, test/oli_web/live/sections/overview_live_test.exs
[MER-1957](https://eliterate.atlassian.net/browse/MER-1957)
This PR adds clickable links to the information in the User and Section columns of the payments table. 
User: Adds the link to the student details view for that student in that section.
Section: Adds the link to access the instructor dashboard for that section.
Also, the base project and product information (if there is one) is shown in the manage section view, in the section details.
Both also have clickable links to access the base project and product details.
[MER-1957]: https://eliterate.atlassian.net/browse/MER-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE][MER-1957] Add clickable links payment management

lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/templates/page_delivery/index.html.heex, test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/live/sections/overview_live_test.exs
[MER-2152](https://eliterate.atlassian.net/browse/MER-2152)
This PR fixes the error that happened when trying to enter a section as a student while being an Admin or an Instructor.
Enter Course as a Student being Admin
https://github.com/Simon-Initiative/oli-torus/assets/16328384/f6d4eca1-d8ad-4886-b27e-c6b85736a8a2
Enter Course as a Student being an Instructor
https://github.com/Simon-Initiative/oli-torus/assets/16328384/71a47be8-35fe-46b6-bf7a-5418e1e02f1b
[MER-2152]: https://eliterate.atlassian.net/browse/MER-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2152] Fix enter course as a student

assets/src/data/content/model/elements/types.ts, lib/oli/interop/rewire_links.ex, priv/schemas/v0-1-0/content-element.schema.json, test/oli/interop/ingest_test.exs, test/oli/interop/rewire_links_test.exs
Legacy xref links are converted into regular 'A' links with an idref set to a page reference by the course-digest tool. Torus had two problems with the ingest of those links. 
1. The ingest process rewrites the idref attributes to a url to an ingested page. It recursively does this through the content, but was only recursively following the 'children' attribute. There can also be links in 'caption', 'pronunciation', and 'translations' of our content model.
2. anchor (new) and target (previously existed) attributes of links with an idref were dropped on ingest.
To test this, you must use the course digest with these changes in it: https://github.com/Simon-Initiative/course-digest/pull/168/files
This has been tested:
* kth - on learns : there is a single xref in this project which is now …
=> [MER-2072] Migrate xref links correctly

assets/src/components/activities/common/delivery/evaluation/Evaluation.tsx
The feedback was laying out paragraphs next to each other instead of stacked. Was caused by an inline-flex applied at the wrong level.
Before:
After:
Fixes #3597
=> [MER-2149] Fix feedback alignment when there are multiple blocks

assets/src/components/activities/common/hints/delivery/HintsDeliveryConnected.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/test/multiple_choice/mc_delivery_test.tsx
[MER-2158](https://eliterate.atlassian.net/browse/MER-2158)
This PR fixes the error that happened when rendering the hints when changing the chosen option in a MC. 
Now, the hints are always visible even if the MC option is changed.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/d18651d7-ae52-4182-9c20-eced11c62872
[MER-2158]: https://eliterate.atlassian.net/browse/MER-2158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2158] Show always hint options

assets/styles/common/elements.scss, lib/oli_web/components/delivery/page_delivery.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/layout/page.html.heex, lib/oli_web/templates/layout/preview.html.heex, lib/oli_web/templates/page_delivery/instructor_page_preview.html.heex, lib/oli_web/templates/page_delivery/page.html.heex, lib/oli_web/templates/resource/page_preview.html.heex
This adds a 900px max width to our content canvas and cleans up some of the resizing that happens at different media sizes. An example of how the page should resize now:
I went with 900 instead of 800 suggested in the ticket to keep it closer to the legacy of 850, but we have a slightly larger font size.
Also, I modified the font size of formulas. With this new page-width, many of the equations in chemistry overflowed the page. The new size doesn't perfectly match the legacy sizing, but comes really close as shown in this image with both overlaid on top of each other. The light-grey is torus and the darker is legacy.
Fixes #3523
=> [Enhancement] Better max-width on learning content

lib/oli/authoring/editing/container_editor.ex, lib/oli_web/live/resources/pages_view.ex, test/oli/editing/container_editor_test.exs
Steps to reproduce:
1. Ingest any project
2. Go to the all-pages of that project
3. Click the (...) menu on a page and select duplicate
Expected: The page duplicates
Actual: No visual change, error in elixir console
Cause of the bug:
Oli.Authoring.Course.create_and_attach_resource eventually calls Resources.create_revision which passes the attributes passed in through a changeset function. If any of the children of those attributes are a struct and not a map, you fail with an ecto error.
This change makes sure the legacy property passed in is a map.
Fixes #3592
=> [Bugfix] Fixes duplicate page on ingested projects

assets/src/components/activities/common/hints/authoring/HintCard.tsx, lib/oli/activities/model/part.ex
While working through MER-2147, I found 2 places where the application would crash on marginally-invalid content.  One was client based related to hints, one was server-based related to part ID's. Not-crashing is preferable to crashing, so some light checks to deal with those. This doesn't actually fix MER-2147
=> [MER-2147] App crashes found on improper content

lib/oli_web/live/products/products_tabel_model.ex, lib/oli_web/live/products/products_view.ex, test/oli_web/live/products_test.exs
[MER-1992](https://eliterate.atlassian.net/browse/MER-1992)
This PR adds the possibility to search also by the title of the base project of the product. 
So, in the search bar it will be possible to search both by product title and by title of the product base project. 
It's also verified that the sorting by date of creation is using the `inserted_at` field of the database.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/63ee6e0e-48ea-4718-941c-8302a556660e
[MER-1992]: https://eliterate.atlassian.net/browse/MER-1992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-1992] Improve product search capability

assets/styles/common/previous_next_nav.scss, lib/oli_web/components/delivery/page_navigator.ex, lib/oli_web/templates/layout/page.html.heex, lib/oli_web/templates/layout/preview.html.heex, lib/oli_web/templates/resource/_preview_previous_next_nav.html.eex, lib/oli_web/views/page_delivery_view.ex
Fixes an issue with the page navigation at the bottom where names were overflowing and not ellipsized
=> [MER-2185]  Fix page name and arrow overflow from the previous page/next page box

lib/oli_web/live/users/author_detail_view.ex, lib/oli_web/live/users/user_detail_view.ex, test/oli_web/live/admin_live_test.exs, test/oli_web/live/users/user_detail_view_test.exs
[MER-1981](https://eliterate.atlassian.net/browse/MER-1981)
This PR allows administrators to edit the first name, last name and email fields for a student or for an author from the individual details view.
- Edit fields for a student
https://github.com/Simon-Initiative/oli-torus/assets/16328384/925b6a96-e4ee-4ac2-a05c-d774350aa28a
- Edit fields for an author
https://github.com/Simon-Initiative/oli-torus/assets/16328384/291fed41-77ef-4569-94a1-d60d86dbf01c
[MER-1981]: https://eliterate.atlassian.net/browse/MER-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE][MER-1981] Permit admins to update name and email fields

lib/oli_web/pow/pow_helpers.ex
This PR reverts [a previous change](https://github.com/Simon-Initiative/oli-torus/pull/3563) that attempted to increase the inactivity timeout, however it set the wrong configuration value to achieve this. After investigating further, it appears the intended change should have adjusted `credentials_cache_store` which specifies how long session credentials remain in the cache store, which actually dictates how much time of inactivity a user is afforded before they will have to re-authenticate. The previously configured value `session_ttl_renewal` configures when a session token becomes stale and a new session ID has to be generated for the user, which is not of much value to the original issue and actually causes problems for long running client apps like the adaptive player. …
=> [BUG FIX] [MER-2179] Fix an issue where adaptive player is timing out due to session_ttl_renewal

assets/src/apps/delivery/layouts/deck/RestartLessonDialog.tsx
Fixes an issue with adaptive pages, when the Display Torus Navigation check box is checked, the user cannot restart the lesson.
https://eliterate.atlassian.net/browse/MER-2200
=> [BUG FIX] [MER-2200] Can't restart adaptive page when torus navigation is present

lib/oli/delivery/attempts/activity_lifecycle.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex, lib/oli/delivery/evaluation/explanation.ex
[MER-1995](https://eliterate.atlassian.net/browse/MER-1995)
This PR fixes the issue that was happening with the explanation strategy in multi inputs that have more than one part and the "submit per part" option enabled. 
In this case, the explanation strategy will be tied to the part attempt number and not to the activity attempt number.
Therefore, the explanation will be displayed for each input separately, in case the answer is incorrect.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/abae10b2-0e9e-487a-b6a0-7687c8e0101e
[MER-1995]: https://eliterate.atlassian.net/browse/MER-1995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-1995] Fix explanation for multi inputs

assets/styles/common/elements.scss
Most of MER-2217 was already fixed when I started on this bug. This PR adjusts sizing on some dropdown elements and it removed a hard coded width from spans to make the sizing on these as intended.
See before image in #3749
After:
=> [MER-2217] Fixed css rule causing extra width on spans.

lib/oli_web/live/sections/table_model.ex, test/oli_web/live/sections/admin_index_live_test.exs
[MER-2206](https://eliterate.atlassian.net/browse/MER-2206)
This PR changes the path that is redirected to when clicking on a section title in the course section listing for the admin view.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/0cb3aa25-3705-4f0d-ba54-90ca524b5e1a
[MER-2206]: https://eliterate.atlassian.net/browse/MER-2206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-2206] Admin sections view link to instructor dashboard

assets/styles/common/elements.scss
This turned out to be a font issue. The superscripts there were encoded using unicode superscript characters. The OpenSans font inside select inputs displayed them as reported. I swapped the select boxes to Arial, and that cleared this up. I would imagine there is a possibility that this could turn into a platform-specific issue.
Here's how a few sample font family / sizes render:
After the change in torus:
Fixes: MER-2215
Fixes: #3747
=> [MER-2215] Fixed superscript characters in select inputs. [Bugfix]

lib/oli_web/components/delivery/utils.ex, test/oli_web/controllers/page_delivery_controller_test.exs
[MER-2219](https://eliterate.atlassian.net/browse/MER-2219)
This PR makes changes to avoid show "Independent" in the logged in user role. 
Instead, the actual role of the user will be rendered as either Student, Instructor or Administrator, regardless of whether the user is LMS or Independent.
- Logged in as Student
https://github.com/Simon-Initiative/oli-torus/assets/16328384/ee5098ab-cd58-464f-980c-656e0bf10415
- Logged in as Instructor
https://github.com/Simon-Initiative/oli-torus/assets/16328384/0b0779af-374e-49dc-885b-1f764fb29aa7
[MER-2219]: https://eliterate.atlassian.net/browse/MER-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2219] Display correctly user roles in account menu

assets/src/data/content/writers/html.tsx
This fixes a problem where block images in activities that had a specific width sets in the XML were not being rendered correctly. 
The fix was to simply set the image `width` attr when present.  Tested locally and it fixes the issue.
=> [BUGFIX] set width when present in model for client rendered block images [MER-2125]

lib/oli_web/live/projects/visibility.ex
[MER-2197](https://eliterate.atlassian.net/browse/MER-2197)
This PR fixes the width of the select input box when you want to set the publication visibility of a project to one or more specific institutions.
[MER-2197]: https://eliterate.atlassian.net/browse/MER-2197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2197] Fix publishing visibility's institution select input box 

CHANGELOG.md, mix.exs
This PR bumps the version number to 0.25.0 for forward development on master
=> [CHORE] Bump to version 25 for forward development

assets/src/components/activities/common/delivery/graded_points/GradedPoints.tsx
[MER-2214](https://eliterate.atlassian.net/browse/MER-2214)
This PR rounds the quiz questions points to 2 decimal places. 
Previously the results were showing 16 decimal places and this did not look good. 
I leave a video showing how it will be displayed from now on.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/14d90252-16dd-4dec-9694-b5e1a15a0797
[MER-2214]: https://eliterate.atlassian.net/browse/MER-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2214] Fix decimals quiz question points

lib/oli/delivery/evaluation/rule.ex, test/oli/delivery/evaluation/rule_eval_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2216)
It seems that [Float.parse/1](https://hexdocs.pm/elixir/1.12.3/Float.html#parse/1) doesn't work with values without leading zeros.
https://github.com/Simon-Initiative/oli-torus/assets/53446634/f216f106-9e34-4a78-9aab-096d531eb70f
=> Add leading zero when necessary

assets/css/app.css, assets/styles/adaptive/adaptive-reset.scss, assets/webpack.config.js, lib/oli_web/templates/layout/chromeless.html.eex
When we added Tailwind, it applied the [tailwind preflight](https://tailwindcss.com/docs/preflight) global styles which broke adaptive player lessons in several places. This PR adds some global resets to the adaptive player to undo those changes and make the adaptive player look like it did before.
For all examples I looked at, the content is now matches pixel-perfect with the previous adaptive player content (some navigation UI has changed)
This fixes all reported issues except BioBeyond Genetic Blueprint, the double dropdown arrows will still appear and I'd suggest fixing this in the lesson itself.
https://eliterate.atlassian.net/browse/MER-2243
https://eliterate.atlassian.net/browse/MER-2207
https://eliterate.atlassian.net/browse/MER-2205
=> [BUG FIX] [MER-2204] [MER-2207] [MER-2243] Adaptive player styling fixes

assets/css/app.css, assets/styles/adaptive/adaptive-reset.scss, assets/webpack.config.js, lib/oli_web/templates/layout/chromeless.html.eex
When we added Tailwind, it applied the [tailwind preflight](https://tailwindcss.com/docs/preflight) global styles which broke adaptive player lessons in several places. This PR adds some global resets to the adaptive player to undo those changes and make the adaptive player look like it did before.
For all examples I looked at, the content is now matches pixel-perfect with the previous adaptive player content (some navigation UI has changed)
This fixes all reported issues except BioBeyond Genetic Blueprint, the double dropdown arrows will still appear and I'd suggest fixing this in the lesson itself.
https://eliterate.atlassian.net/browse/MER-2243
https://eliterate.atlassian.net/browse/MER-2207
https://eliterate.atlassian.net/browse/MER-2205
Cherry picks commits `17cd228.. f695b8d` from …
=> [BUG FIX] [MER-2204] [MER-2207] [MER-2243] Adaptive player styling fixes [TARGET v0.24.0]

lib/oli_web/templates/page_delivery/page.html.heex, test/oli_web/controllers/page_delivery_controller_test.exs
[MER-2213](https://eliterate.atlassian.net/browse/MER-2213)
This PR adds an extra condition in the `if` statement that checks whether or not the timer should be rendered on a page. 
The timer will be rendered if the page is graded, in addition to the other conditions that already exist.
[MER-2213]: https://eliterate.atlassian.net/browse/MER-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2213] Timer sometimes appears on non quiz pages

mix.exs
Somehow it appears the version number 0.25.0 crept into the v0.24.0 branch. This fixes that in the mix file.
=> [CHORE] Fix v24 version number

assets/src/apps/delivery/Delivery.tsx, assets/src/apps/delivery/layouts/deck/IdleTimeOutDialog.tsx, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/router.ex
_New pr to target prerelease branch_
The adaptive player's idle timeout dialog was sending the user to the overview page at the end of the timeout period instead of logging them out as desired. This now works correctly.
In addition, I fixed the visual display of the dialog.
=> [Bugfix] Fixed the advanced author idle timeout dialog [MER-2179]

lib/oli_web/templates/page_delivery/prologue.html.eex
Minor style change.
Before:
After:
=> [Bugfix] Style start attempt button better.

assets/styles/common/elements.scss
Originally, the formulas were set to a 1 REM font size.
On June 27, I had lowered it to 0.8, which fixed most of these issues.
This particular formula is quite long, so I'm going to further reduce the font size to 0.7REM
Fixes #3641
=> [Bugfix] Reduce formula font size. [MER-2131]

lib/oli/rendering/activity/html.ex
1. Add an adaptive activity to a core page
2. Preview it
Expected: View the page without that activity (is this true?)
Actual: 500 error / server crash
The original bug report talked about a rollover inside the stem of a question, but that seems to work fine. I spent some time selectively removing elements from the problematic page to find this as the root cause.
Fixes #3810
=> [Bugfix] crash on preview of core page with adaptive activity [MER-2234]

lib/oli/delivery/attempts/page_lifecycle/ungraded.ex, lib/oli_web/live/sections/overview_view.ex, test/oli_web/live/sections/overview_live_test.exs
Pages that only contain survey activities were not updating their progress.  Since activities within surveys are considered "unscoreable", the system needs to detect when a page *only* has unscoreable activities and mark the page progress as 100% upon visit.
In fixing this, I caught a regression where the "Enter course as a student" link had changed.  I corrected that.
=> [BUG FIX] Correct progress tracking in surveys [MER-2236]

lib/oli_web/live/new_course/new_course.ex
The payment settings and required survey id were not being pulled forward during creation from a product.
=> [BUG FIX] ensure payment settings get captured correctly [MER-2263]

lib/oli_web/live/new_course/new_course.ex, lib/oli_web/live/new_course/table_model.ex, test/oli_web/live/new_course/select_source_test.exs
This PR addresses the core issue pointed in [MER-2095], which is that the "Next" button can be scrolled off of the page, making it confusing for the user to know how to proceed to Step 2.  This PR makes a change to automatically move to Step 2 after the user 'selects' a source. 
This PR also makes a few UI adjustments to simplify some language and reduce the size of the "Select" buttons.
[MER-2095]: https://eliterate.atlassian.net/browse/MER-2095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENHANCEMENT] Improve course creation [MER-2095]

assets/src/apps/authoring/store/activities/actions/objectives.ts, assets/src/apps/authoring/store/activities/actions/saveActivity.ts, assets/src/components/resource/objectives/ActivityLOs.tsx, assets/src/data/persistence/activity.ts
Setting objectives on any multi-part activity was broken
To reproduce: 
1. From course project overview, enable the “Likert” activity
2. Go into the basic page page editor and create a Likert activity
3. Add a second “item” (by clicking the second “Add choice” button link, this really should read “Add item”)
4. From the Learning Objectives attachment dialog for that activity, attempt to attach LOs to each of the different parts
5. Refresh and reload the page
You will see that after reloading, both objectives are attached to the first part.
This was caused by logic meant for only saving adaptive lesson activities being applied to saving all activities.
=> [BUGFIX] Fix setting objectives on multi-part activities. [MER-2270]

lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, test/oli/delivery/metrics/learning_proficiency_test.exs
This PR reworks the arrangement of objectives within the rows of the "Learning Objectives" reports in the instructor dashboard.  
Consider an authored project with the following objectives, noting how `Sub2` is a sub objective that appears under both of the top-level objectives:
```
TOP
--Sub1
--Sub2
TOP2
--Sub2
--Sub3
```
This PR now correctly renders this structure:
Moreover, for the rows where only a top-level objective is shown, the proficiency results are for only when that top-level objective is directly attached to activities.  For the other rows where a sub objective is displayed, the values shown for the "top level" objective are the aggregated results across all sub objectives that appear under that top-level objective.
=> [BUG FIX] Fix top level objectives display in dashboard reports [MER-2267]

assets/css/table.css, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/content/content_table_model.ex, lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex, lib/oli_web/live/grades/gradebook_table_model.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex, lib/oli_web/live/sections/enrollments_table_model.ex, test/oli_web/live/delivery/instructor_dashboard/reports/quiz_scores_tab_test.exs, test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs
[Link ](https://eliterate.atlassian.net/browse/MER-2055)to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/7f8dc1f4-f2de-4254-82f4-608bd6c49fe0
This PR also improves the styling for the quiz scores tab, for the case where we have an x overflow (including dark mode).
https://github.com/Simon-Initiative/oli-torus/assets/74839302/a8192c83-7111-4d4d-a9b4-6d71dfbb7db7
https://github.com/Simon-Initiative/oli-torus/assets/74839302/110140be-3b23-42c4-8b60-6c10d42d4455
Finally, the `instructor_dashboard_th` class was removed from many tables, since it was not defined in any `.css` file and had no effect at all.
=> [MER-2055] Fix student sorting

lib/oli/interop/export.ex
Fixes a problem that is breaking project export:
lib/map.ex:534 Map.get/3 |  
-- | --
lib/oli/interop/export.ex:106 Oli.Interop.Export.rewire_activity_elements/2 |  
lib/oli/interop/export.ex:176 anonymous fn/2 in Oli.Interop.Export.rewire_activity_content/2 |  
lib/enum.ex:1658 Enum."-map/2-lists^map/1-0-"/2 |  
lib/oli/interop/export.ex:173 Oli.Interop.Export.rewire_activity_content/2 |  
lib/oli/interop/export.ex:88 anony
=> [BUG FIX] Fix bad map error [MER-2311]

assets/src/apps/delivery/layouts/deck/RestartLessonDialog.tsx, assets/src/data/persistence/page_lifecycle.ts, lib/oli_web/controllers/api/page_lifecycle_controller.ex
When choosing the restart option on graded adaptive lesson pages, the learner was brought to the review page instead of giving the option to start a new attempt as intended. They will now be sent to the "start attempt" page. (Note: If they have exceeded the maximum number of retries, they can not start a new attempt)
On an ungraded page, the learner is brought to the start of the adaptive lesson with no "start attempt" page as expected.
Also made some minor UI tweaks to the restart dialog:
1. Made it 80% width so it looks like a dialog again
2. Made the entire "ok" button clickable instead of just the text
3. Added "restarting..." feedback since it can take a few seconds and the learner might click "OK" multiple times.
=> [BUGFIX] fix adaptive graded restart [MER-2274]

lib/oli/delivery/settings.ex, lib/oli_web/components/tag.ex, test/oli/delivery/settings_test.exs
This PR fixes the handling of graded pages that have no effective end date whatsoever.  All graded pages without end dates and without a time limit were being marked late, but we had no idea until we actually started rendering the "LATE" badge. 
I noticed something strange in my dev environment when implementing this: The "LATE" badge for me now renders (in light mode) without the red background.  It does not seem to be a problem with the Tailwind CSS.  See https://play.tailwindcss.com/mmOHSRLxN3#:~:text=.../-,mmOHSRLxN3,-v3.3.2
Perhaps it is just something strange locally in my dev environment (It is also correct on argos QA).  Please, who ever reviews this PR, verify that the "LATE" badge renders correctly for you.
=> [BUG FIX] Correctly handle no effective end date cases [MER-2308]

assets/styles/common/elements.scss
This reverts the formula sizing to 0.9REM
Here is a comparison between formula & paragraph sizing:
Some consequences:
Chemistry "Mole Conversions: Multi-step"
At a wide screen width:
At a narrow screen width:
=> [BUGFIX] Revert formula font size [MER-2304]

lib/oli/interop/export.ex, test/oli/interop/digest/22.json, test/oli/interop/digest/23.json, test/oli/interop/ingest/scalable_ingest_test.exs, test/oli/interop/ingest_test.exs
[MER-2209](https://eliterate.atlassian.net/browse/MER-2209)
This PR fixes the issue that happened when ingest a project and build the objectives hierarchy. 
With this fix, the objectives and their sub-objectives added to the ingested project are rendered correctly as their hierarchy specifies.
- **Ingest Project**
https://github.com/Simon-Initiative/oli-torus/assets/16328384/ed0c0a44-f882-4574-b5c5-bffbdb5f943a
- **V2 Ingest Project**
https://github.com/Simon-Initiative/oli-torus/assets/16328384/5b9b2a0a-90a0-432a-bc79-43bfeeb75c4a
[MER-2209]: https://eliterate.atlassian.net/browse/MER-2209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2209] Reingest project does not retain objectives hierarchy

lib/oli_web/components/delivery/user_account_menu.ex, lib/oli_web/live/common/properties/read_only.ex, lib/oli_web/live/new_course/select_source.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, lib/oli_web/templates/delivery/getting_started.html.eex, test/oli_web/live/sections/overview_live_test.exs
There were a couple issues related to manage links to Preview as instructor and Enter course as student around the different roles in the system. This PR attempts to fix those issues by:
1. "Preview as Instructor" always takes Instructors and System Admins to the instructor preview overview
2. Removes "Enter course as student" link, as this was not useful to instructors or system admins
3. Fixes a couple other issues identified through testing:
- Sign out was broken for system admins in instructor dashboard
- Various buttons were siblings with block elements, making margins not render correctly 
As a side note: the copy button does not work inside LTI iframes, as it would require a clipboard permission that, at least when tested in canvas, doesn't have.
=> [BUG FIX] [MER-2312] Enter course as student doesn't work

lib/oli/delivery/attempts/auto_submit/worker.ex, lib/oli/delivery/attempts/page_lifecycle/grade_update_worker.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli/delivery/settings.ex, test/oli/delivery/settings_test.exs
This PR appears to fix a very strange bug, where during the execution of an `Oban` auto submit job, other `Oban` jobs cannot be created.  This PR also fixes two other bugs that I discovered during this work:
1. Auto submission via the delayed Oban auto submit job will still mark the attempt as being "LATE".  Auto submit is executed because the instructor has decided for that assessment to not allow late submissions, therefore, no submissions including auto submitted ones should be marked as late.  The fix here was to take into account `late_submit: :disallow` in `Settings.was_late?`. 
2. `page_delivery_controller.ex` code was still using the max number of attempts from the page revision, instead of the effective settings to determine whether or not to allow a user to start a new attempt. …
=> [BUG FIX] Fix auto submit [MER-2253]

lib/oli_web/live/delivery/manage_source_materials.ex, lib/oli_web/live/delivery/remix/entry.ex, lib/oli_web/live/sections/gating_and_scheduling.ex, lib/oli_web/live/sections/gating_and_scheduling/edit.ex, lib/oli_web/live/sections/gating_and_scheduling/new.ex, lib/oli_web/live/sections/overview_view.ex
This fixes an issue where users would click on "Manage Source Materials" for a specific product and would be taken to a completely different product. 
Root cause was that the LiveView (and a few others) were pulling the section slug from the session, and not from the path parameters.  This is problematic when the user is logged in as both an author and instructor - in that case the section slug in the session can point to the section that they are enrolled in as a student/instructor. 
The fix in `entry.ex` is to allow pages from another project to be added during remix.  I caught this bug while troubleshooting this.
=> [BUG FIX] use the slug from the session [MER-2317]

lib/oli/delivery/sections.ex, priv/repo/migrations/20230712163553_rebuild_contained_pages.exs
This PR adds a DB migration to rebuild the contained_pages relation for all course sections. 
I optimized its impl so that it is pulling far smaller payloads with its internal queries.
=> [BUG FIX] Contained pages rebuild migration [MER-2305]

assets/src/phoenix/dark.ts, assets/styles/common/elements.scss
This was an issue raised in the weekly migration meeting.
Gray caption backgrounds are causing style issues with striped tables and we've received much feedback in the review process that there shouldn't be any sort of background around captions. A lot of migrated images have white backgrounds and when combined with the gray background make courses look noisy. The decision to set this caption background was made early on in torus development and removing is an easy, low risk style fix.
This PR also fixes an issue where dark mode was breaking on page load. The script was attempting to append a meta tag to the document which is not allowed, crashing the listener. This fix now properly adds the meta tag to the head of the document.
https://eliterate.atlassian.net/browse/MER-2323
Some content …
=> [BUG FIX] [MER-2323] image captions render with a gray background

lib/oli_web/templates/payment/guard.html.heex
[MER-2277](https://eliterate.atlassian.net/browse/MER-2277)
This PR modifies slightly the text in the payment wall view as specified in the ticket.
Also, the styling of the 'pay by credit card' button that was covering the text above has already been fixed in this [PR](https://github.com/Simon-Initiative/oli-torus/pull/3867).
[MER-2277]: https://eliterate.atlassian.net/browse/MER-2277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2277] UI issues with payment wall

assets/src/components/editing/toolbar/Toolbar.modules.scss, assets/src/components/editing/toolbar/buttons/DropdownButton.tsx
The dropdowns from the slate editor toolbar had gotten too large and were often offscreen. I've modified them so whenever there is more than 6 items in the dropdown, it uses a multi-column format to fit more on screen.
Examples:
Fewer than 6 items behave as before:
=> [BUGFIX] Component menu offscreen [MER-2315]

lib/oli/interop/export.ex
This PR fixes a bug where a project which contains activity bank questions, upon re-ingest, has those activities no longer appear in the activity bank. 
Root cause was the export code does not output and preserve the `scope` attribute, which indicates whether an activity is `embedded` or `banked`.  The ingest code treats the lack of this attribute with a default of `embedded`
=> [BUG FIX] preserve scope attribute during export

lib/oli/delivery/metrics.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/components/delivery/scored_activities/scored_activities.ex, lib/oli_web/live/delivery/instructor_dashboard/helpers.ex, test/oli/delivery/metrics/avg_score_test.exs, test/oli/delivery/metrics/progress_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2227?focusedCommentId=20740) to the comment on the ticket
```The summary statement in the upper right of this view is off. See screenshot 9. Despite what it says here, 5 students have completed 8 attempts. ``` -> We were filtering by revision and some attempts were from a previous page revision
```And back in Scored Activities, the percentage for Students Completion for the Activity Bank quiz is 120%. Is that correct? It seems like 100% should be the max value here but perhaps I’m missing something about how this gets calculated. See screenshot 10. ``` -> We were considering non-student attempts.
=> [BUG-FIX] Attempt summary and student completion [MER-2227]

assets/css/button.css, lib/oli_web/components/delivery/buttons.ex, lib/oli_web/components/delivery/course_content.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/course_content_live.ex, lib/oli_web/router.ex, test/oli_web/live/delivery/instructor_dashboard/overview/content_tab_test.exs
The content browser (both student and instructor facing) does not handle well courses that *only* contain pages.  These pages appear almost as "units" that the user can navigate between via the left and right arrow, but the user cannot click to access, nor see any page pertinent information such as due dates.  
The PR corrects that by detecting this case and just listing the pages, as pages.
For example:
There is also a change here to handle the root path for the dashboard explicitly and redirect to the "overview" route.  This fixes a bug where an Internal Server Error was being thrown when trying to hit this route directly.
=> [ENHANCEMENT] Adjust content browser for when only pages are present [MER-2319]

lib/oli_web/live/projects/publish_view.ex, lib/oli_web/live/projects/versioning_details.ex, test/oli_web/live/publish_live_test.exs
I kept stumbling into this issue while testing and it was very frustrating. This fixes an issue where clicking the "Automatically push this publication update to all products and sections" would clear the existing description textfield.
I tested this thoroughly, publishing both with and without the checkbox checked and verified the description was still being saved properly.
=> [BUG FIX] [MER-1918] checking automatically push update box erases info in the description field for the update

assets/src/components/editing/elements/webpage/WebpageElement.tsx, assets/src/components/editing/elements/webpage/WebpageModal.tsx, assets/src/components/editing/elements/webpage/WebpageSettings.tsx, assets/src/data/content/model/elements/types.ts, assets/src/data/content/writers/html.tsx, lib/oli/rendering/content/html.ex, test/oli/rendering/content/html_test.exs
Authors can now specify the size of an iframe, this is initially intended to support importing legacy content with those dimensions set, but can actively be used moving forward in new content.
If no size is specified, the previous behavior of a responsive iframe will continue.
New settings dialog:
=> [Feature] Allow iframe sizes to be specified by author [MER-2306]

lib/oli_web/components/delivery/utils.ex
Oddly enough this is not reproducible locally.  This change, though, should fix the error as seen on stellarator, by explicitly handling users of type `%Author{}` upfront - and avoiding the calls to `PlatformRoles.has_roles?`
=> [BUG FIX] Explicitly handle author [MER-2338]

lib/oli_web/components/delivery/discussion_activity/discussion_activity.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/index.html.heex
[Link to the comment](https://eliterate.atlassian.net/browse/MER-2310?focusedCommentId=20788) in the ticket
See video attached in the comment
https://github.com/Simon-Initiative/oli-torus/assets/74839302/7a5420fd-fe02-4a5f-8e14-0cc6324d7c5e
While working on the ticket, another bug was found; the collab space config was not being applied correctly for students in the Discussion component of the home section, so their posts were being directly approved (as if they were instructors). In the following videos, the course has the following collab space config:
https://github.com/Simon-Initiative/oli-torus/assets/74839302/cfdb69ca-e872-407c-8ff8-f975f04208ac
https://github.com/Simon-Initiative/oli-torus/assets/74839302/a3107e9f-07f1-4162-aa17-d1f64bd72af6
=> [BUG FIX] Fix approve two posts [MER-2310]

assets/src/apps/delivery/layouts/deck/LessonFinishedDialog.tsx, lib/oli_web/components/delivery/actions/actions.ex, lib/oli_web/controllers/api/page_lifecycle_controller.ex, lib/oli_web/controllers/page_delivery_controller.ex
Fix two open issues:
1. [MER-2248] The "cancel" button did nothing in the confirmation step for "Unenroll".  Could not get this to work correctly, so I removed it.  The "X" button does work and closes the dialog
2. [MER-1999] The LessonFinishedDialog was using the wrong URL for redirect after lesson completion. It needs to be using the URL in the response from finalization (which for Adaptive is now always going to be the 'prologue' page)
[MER-2248]: https://eliterate.atlassian.net/browse/MER-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-1999]: https://eliterate.atlassian.net/browse/MER-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] Fix cancel button, fix finish page for adaptive [MER-2248] [MER-1999]

assets/src/apps/delivery/layouts/deck/RestartLessonDialog.tsx
This is a minor change to the restart dialog to constrain it's max width and look a little nicer in default CSS.
The bug referenced in MER-2321 looks like it was fixed in lesson specific css.
Before:
After:
=> [BUGFIX] Minor styling fix to adaptive restart dialog [MER-2321]

lib/oli/delivery/sections.ex
There must be some mangled, old course sections which trip out the `Sections.rebuild_contained_pages_helper`.  This PR improves the robustness of that function by explicitly handling (and filtering out) bad data.
=> [BUG FIX] Contained pages robustness [MER-2348] [MER-2345]

lib/oli_web/live/common/cancel_modal.ex, lib/oli_web/live/delivery/remix_section.ex, lib/oli_web/live/delivery/remix_section.html.heex, test/oli_web/live/remix_section_test.exs
[MER-2302](https://eliterate.atlassian.net/browse/MER-2302)
This PR fixes the issue that happened when clicking the cancel button in the Customize Curriculum view. 
Now, when we have added some element to the curriculum and press the cancel button we have 2 options: 
- `Cancel` option has no action. Just close the modal. 
- `Ok` option will redirect the user to the Section Overview. 
https://github.com/Simon-Initiative/oli-torus/assets/16328384/04680f80-f10d-4857-be4d-4281ae128931
[MER-2302]: https://eliterate.atlassian.net/browse/MER-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2302] Fix cancel button customize curriculum

lib/oli/utils.ex, lib/oli_web/live/common/properties/group.ex, lib/oli_web/live/common/show_section.ex, lib/oli_web/live/sections/start_end.ex, test/oli_web/live/sections/edit_live_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-1953)
This should fix similar issues with gating condition data and system messages because they also make use of `validate_dates_consistency/2`
=> [BUGFIX][MER-2261] Verify section start and end dates before saving

assets/src/components/editing/elements/inputref/InputRefEditor.tsx, assets/styles/common/elements.scss
This PR fixes an issue where input refs in multi-input author do not properly reflect the size set on them.
This fix seems to high risk and low priority for v24 at this point, but I already tracked down and fixed the issue so I am targeting for v25
Closes #3956
=> [BUG FIX] [MER-2363] fix an issue where input refs don't reflect their actual size

lib/oli/delivery/sections.ex, lib/oli/delivery/sections/scheduling.ex, lib/oli_web/components/delivery/up_next.ex, lib/oli_web/controllers/page_delivery_controller.ex
Fixes two problems:
1. Identically scheduled resources can seemingly be "randomly" picked for the UpNext display. This is due to lack of secondary sorting to sort by course positioning. 
2. UpNext was not rendering date in user's local timezone
=> [BUG FIX] Fix UpNext date display, fix sorting on identifical end_dates

assets/src/components/editing/elements/link/LinkModal.tsx
The link modal UI was inappropriately adding "http://" to links to pages within the course, making them break in delivery. We now check what type of link before applying that change.
=> [Bugfix] Do not add protocol to page links [MER-2377]

lib/oli/delivery/sections/scheduling.ex, lib/oli_web/controllers/api/scheduling_controller.ex, test/oli_web/controllers/api/scheduling_controller_test.exs
1. Open scheduler for a course section that has some practice pages
2. Manually schedule a page for "Suggested By" for today, 7/20/23
3. Save the changes
4. Refresh the page
5. View that same practice page
Expected: the practice page says 7/20/23
Actual: the practice page says 7/21/23
The api sends a date with no time component back and forth, such as  `end_date: "2023-07-20"`.  The save call would convert that to "2023-07-20 11:59:59" in the user's timezone (America/New_York for this example), then convert to UTC (2023-07-21 3:59:59) and save it. 
The retrieval API call would later grab that (2023-07-21 3:59:59) strip the time (2023-07-21) and send it to the front end, effectively giving the date in UTC instead of the user's local time.
=> [Bugfix] scheduler date drift [MER-2378]

assets/src/components/editing/toolbar/Toolbar.modules.scss, assets/src/components/editing/toolbar/buttons/DropdownButton.tsx
Dark mode wasn't working for the component dropdown menus. Now they look like this:
And lightmode still looks like:
=> [Bugfix] Dark mode component menu [MER-2335]

lib/oli_web/live/objectives/objectives.ex
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2381)
This fixes the issue, but I couldn't figure out why there's a `nil` item in the `objective.children` list
=> [BUGFIX][MER-2381] Objectives deletion fix

assets/styles/delivery/page_delivery/collab_space.scss, lib/oli_web/components/delivery/buttons.ex, lib/oli_web/live/collaboration_live/active_users.ex, lib/oli_web/live/collaboration_live/collab_space_view.ex, lib/oli_web/live/collaboration_live/posts/list.ex
Fixes two issues related to discussions:
1. Replies were unreadable in dark mode #3995
2. Guest users show up as blank green dot in discussions #3985
Closes #3995 #3985
=> [BUG FIX] [MER-2382] discussions card unreadable in dark mode

lib/oli_web/live/ingest/ingestv2.ex, test/oli_web/live/ingest_live_test.exs, test/support/digests/digest_4/_hierarchy.json, test/support/digests/digest_4/_project.json, test/support/digests/digest_5/_media-manifest.json, test/support/digests/digest_5/_project.json, test/support/digests/digest_6/_hierarchy.json, test/support/digests/digest_6/_media-manifest.json, test/support/test_helpers.ex
[MER-2334](https://eliterate.atlassian.net/browse/MER-2334)
This PR fixes the issue that happened when ingesting a project that does not contain the `media-manifest` file in V2 Ingest Project. 
It also adds some tests for different cases where you try to digest a project with missing files.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/c52b3ca0-6f13-4fc5-8030-ffdc0c280ff6
[MER-2334]: https://eliterate.atlassian.net/browse/MER-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-2334] V2 ingest report invalid zip

test/oli_web/live/sections/edit_live_test.exs
This PR removes an `open_browser` in a test
=> remove open_browser
