LICENSE.md, README.md
=> change badge to production

assets/src/components/editor/EditorTest.tsx, assets/src/components/editor/editors.tsx, assets/src/components/editor/editors/YouTube.tsx
This PR adds ER1 level youtube video support. 
Closes #12
=> youtube support

assets/src/components/editor/Editor.tsx, assets/src/components/editor/EditorTest.tsx, assets/src/components/editor/editors.tsx, assets/src/components/editor/editors/Lists.tsx
This PR adds core list (ordered and unordered) support. 
Features include:
-Creation as a new list or wrapping existing selected content
-Indent via Tab
-Outdent via Shift-Tab
-List termination pressing Enter on empty list item
=> Ds add list support

assets/src/components/editor/Editor.tsx, assets/src/components/editor/EditorTest.tsx, assets/src/components/editor/editors.tsx, assets/src/components/editor/editors/Blockquote.tsx
This PR adds ER1 level blockquote support. 
Closes #15
=> Ds blockquote

assets/src/components/editor/EditorTest.tsx, assets/src/components/editor/editors.tsx, assets/src/components/editor/editors/Audio.tsx
PR to incorporate ER1 level audio editing
=> add audio editing support

assets/src/components/editor/Editor.tsx, assets/src/components/editor/EditorTest.tsx, assets/src/components/editor/Toolbars.tsx, assets/src/components/editor/commands.ts, assets/src/components/editor/editors.tsx, assets/src/components/editor/editors/Link.tsx, assets/src/components/editor/editors/Popover.tsx, assets/src/components/editor/editors/interfaces.ts, lib/oli_web/templates/layout/app.html.eex
PR to add basic hyperlink creation
Closes #20
=> hyperlinks

lib/oli/accounts.ex, lib/oli_web/controllers/auth_controller.ex, lib/oli_web/controllers/institution_controller.ex, lib/oli_web/plugs/protect.ex, lib/oli_web/plugs/set_user.ex, lib/oli_web/templates/institution/index.html.eex, lib/oli_web/templates/layout/app.html.eex, lib/oli_web/templates/page/index.html.eex, test/oli_web/controllers/auth_controller_test.exs, test/oli_web/controllers/institution_controller_test.exs, test/oli_web/controllers/lti_controller_test.exs, test/oli_web/views/navigation_view_test.exs
Converts session from using a single current_user to using current_author and current_user for the separate cases
=> convert current_user to current_author and current_user

lib/oli/db_seeder.ex, lib/oli/publishing.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/project/curriculum.html.eex, lib/oli_web/templates/project/publish.html.eex, test/oli/publishing_test.exs
This PR adds the publishing UI.
- Go to publish, click Publish to create first publication
- Make some changes then go back to Publish to see changes. Click Publish again to create a new publication
=> add publishing ui

lib/oli/delivery/lti/hmac_sha1.ex
This PR adjusts the encoding approach used to allow signatures to be verified correctly. 
Closes #120
=> change encoding strategy

lib/oli/authoring/editing/objective_editor.ex, lib/oli_web/templates/project/_objective_form.html.eex, lib/oli_web/templates/project/_objective_render.html.eex, lib/oli_web/templates/project/_objectives_list.html.eex
PR to fix objective hierarchy issues; side effect from resource model refactoring. Also adds ability to render arbitrary nested objective tree.
=> fixed objective hierachy and rendering

assets/js/app.js, assets/package-lock.json, assets/package.json, assets/yarn.lock, lib/oli/application.ex, lib/oli_web/endpoint.ex, lib/oli_web/router.ex, lib/oli_web/templates/layout/app.html.eex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/templates/layout/live.html.eex, lib/oli_web/templates/layout/preview.html.eex, lib/oli_web/templates/layout/root.html.leex, lib/oli_web/templates/layout/workspace.html.eex
I finally tracked down a problem with our LiveView configuration that had prevented us from using session support in LiveViews - the browser pipeline has the protect from forgery plug disabled - which was interfering with CSRF LV session setup. 
I also upgraded our LV setup to match how it ships now in phoenix 1.5:
1. Cleaned up our layouts to reflect the new approach
2. Added in a dependency for showing progress on LV form submits.
=> fix LiveView session support, update other 1.5 LV facilities

assets/css/app.css, lib/oli_web/templates/layout/_project_sidebar.html.eex, lib/oli_web/templates/layout/_workspace_sidebar.html.eex, lib/oli_web/templates/layout/root.html.leex
Fixes an issue where the footer wasn't sticking to the bottom on scroll
=> fix footer

assets/src/components/activity/ActivityEditor.tsx, assets/src/components/activity/PartObjectives.tsx, assets/src/components/resource/Objectives.tsx, assets/src/components/resource/ResourceEditor.tsx, lib/oli/authoring/editing/activity_editor.ex, lib/oli/resources/utils.ex
This PR adds a UI to allow attaching of learning objectives to activity parts. 
:TODO: sync part-objectives list to part editing/removal
=> Objective attach

lib/oli/authoring/editing/activity_editor.ex, lib/oli_web/live/history/details.ex
Adds missing slug to id translation for attached objectives.
Also adds display of objectives blob in revision history tool
=> added missing translation of slugs to ids

assets/src/components/activities/short_answer/sections/Feedback.tsx
This PR restores a lost local edit which allowed the correct answer in a SA activity to be edited.
=> allow editing of correct answer in short answer activity

assets/src/components/activities/short_answer/ShortAnswerAuthoring.tsx
PR to incorporate media library into SA activity, similar to how it is integrated into MCQ activity.
=> integrate media library

lib/oli/qa/uri_validator.ex
Make the validation of URLs more robust.
=> Robust validation

lib/oli/authoring/editing/activity_editor.ex, lib/oli/delivery/attempts.ex, lib/oli/delivery/attempts/scoring.ex, lib/oli/utils/db_seeder.ex, test/oli/delivery/attempts/scoring_test.exs, test/oli/delivery/submission_test.exs
This PR implements the scoring strategies used in part attempt to activity attempt rollup and in resource attempt to resource access rollup. 
Closes #167
=> Scoring strategies

config/dev.exs
Allow setting host, port and force_ssl through environment configuration for development environment
=> add ability to specify host, port and force_ssl in dev

lib/oli_web/templates/project/overview.html.eex
This PR adds capability to rename a project.
I cleaned up the UI a bit by placing the project details first, then the collaborators.  
Closes #241
=> allow renaming of project

assets/src/components/resource/Outline.tsx, assets/src/data/content/utils.tsx
This PR fixes the outline preview logic to ensure that it handles cases of link and empty blocks. 
I removed the display of purpose type as well. 
Closes #231
=> Outline cleanup

lib/oli/publishing.ex, lib/oli/utils/db_seeder.ex
fix available courses query for open and free listing and make seed course open and free
Closes #279
=> fix available courses query for open and free listing

assets/src/components/editor/editors/Settings.tsx
Restore the popover's children as a function.
=> fix apparent mis-merge

assets/src/components/activity/ActivityEditor.tsx, assets/src/components/activity/PartObjectives.tsx, assets/src/components/resource/Objectives.tsx, assets/src/components/resource/ResourceEditor.tsx, assets/src/data/persistence/objective.ts, assets/styles/authoring/custom.scss, assets/styles/authoring/react-typeahead.scss, lib/oli_web/controllers/resource_controller.ex, lib/oli_web/router.ex, test/oli_web/controllers/resource_controller_test.exs
Adds the ability to create objectives directly from the objective selection dropdown by typing an objective name that does not currently exist.
=> implement on-the-fly objective creation

lib/oli_web/live/qa/qa_live.ex, lib/oli_web/live/qa/state.ex, test/oli_web/live/qa_logic_test.exs
Closes #299
This PR incorporates filter and selection state into the browser history for the QA / Review view
=> preserve filter and selection state

lib/oli/accounts/schemas/author.ex, lib/oli_web/controllers/auth_controller.ex, test/oli/accounts_test.exs
Fix and issue where social media login changes system role
Closes #330
=> Fix and issue where social media login changes system role

lib/oli_web/live/insights/insights.ex, lib/oli_web/live/insights/table_row.ex
Fixes the links in the insights view
Closes #336
=> use common link impl

assets/src/components/editor/Editor.tsx, assets/src/data/content/resource.ts
Fixes an issue where default structured content is a single space on creation.
Closes #345
=> fix an issue where default structured content is a single space

assets/src/components/editor/editors/Table.tsx, assets/src/components/resource/Editors.tsx, assets/styles/authoring/editors.scss
Fixes an issue where table dropdowns weren't working
Closes #361
=> Table dropdown controls broken

lib/oli_web/templates/delivery/getting_started.html.eex
Small PR to temporarily disable the account creation / open and free links for learn lab using css pointer events
=> disable account creation/open and free for learnlab

assets/src/components/activities/multiple_choice/actions.ts, assets/src/components/activities/multiple_choice/schema.ts, assets/src/components/activities/multiple_choice/utils.ts, assets/src/components/activities/short_answer/actions.ts, assets/src/components/activities/short_answer/schema.ts, assets/src/components/activities/short_answer/utils.ts, assets/src/components/content/AddResourceContent.tsx, assets/src/components/misc/EditLink.tsx, assets/src/components/resource/AbbreviatedActivity.scss, assets/src/components/resource/AbbreviatedActivity.tsx, assets/src/components/resource/Editors.tsx, assets/src/components/resource/ResourceEditor.tsx, assets/src/data/content/resource.ts, assets/src/data/content/text.ts, assets/src/data/content/utils.tsx, assets/test/utils/multiple_choice_test.ts, assets/test/utils/short_answer_test.ts, lib/oli/authoring/editing/activity_editor.ex, lib/oli/authoring/editing/page_editor.ex
This PR incorporates a read-only, condensed display of an activity from the page editor.  
Closes #416
=> show condensed, read-only activities in page editor

lib/oli_web/live/history/details.ex, lib/oli_web/templates/shared/_admin_edit_banner.html.eex
Now this is my kind of bug
Closes #379
=> fix horizontal scroll in admin rev history, remove underline from link

lib/oli_web/templates/workspace/account.html.eex
=> prevent rename unless email login

assets/src/components/editor/editors/Settings.tsx, assets/src/components/editor/editors/YouTube.tsx, assets/src/utils/params.ts
Closes #439 
Closes #369 
I ported the URL parsing logic from Echo.
=> modal youtube selection step

assets/src/components/activity/ActivityEditor.tsx, assets/src/components/resource/ResourceEditor.tsx, lib/oli/authoring/locks.ex, test/oli/editing/page_editor_test.exs, test/oli/locks_test.exs
Displays a message banner of the current edit lock owner if different new user trying same edit
=> Message on locked page

lib/oli_web/templates/activity/edit.html.eex
Allows activity editor to render.
=> base 64 encode activity editing context

assets/src/components/content/StructuredContentEditor.tsx, assets/src/components/editor/Editor.tsx, assets/src/components/editor/RichTextEditor.tsx, assets/src/components/editor/Toolbars.tsx, assets/src/components/resource/Editors.scss, assets/src/components/resource/Editors.tsx, assets/styles/authoring/controls.scss, assets/styles/authoring/toolbar.scss
This PR changes the way the fixed toolbar is shown so that it floats above content until scrolling to prevent it from covering up content.
Closes #440
=> Fixed content toolbar

assets/src/components/content/AddResourceContent.scss, assets/src/components/editor/editors/Audio.tsx, assets/src/components/editor/editors/Code.scss, assets/src/components/editor/editors/Code.tsx, assets/src/components/editor/editors/Image.tsx, assets/src/components/editor/editors/Settings.tsx, assets/src/components/editor/editors/Table.tsx, assets/src/components/editor/editors/YouTube.tsx, assets/src/components/resource/ResourceEditor.tsx, assets/styles/authoring/main.scss, assets/styles/authoring/variables.scss, assets/styles/delivery/main.scss, lib/oli/rendering/content/html.ex, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex, test/oli/rendering/content/html_test.exs
This PR addresses some of the delivery cleanup part 2 #292 tasks including:
- fix an issue with add content z index
- add labels to element options buttons
- fix a issue where image wasn't centered
- add code syntax highlighting
- add codeblock highlighting and quote styling
=> Cleanup delivery styles

config/config.exs, config/releases.exs
=> removed default from config

assets/src/components/activity/ActivityEditorApp.tsx, assets/src/components/resource/ResourceEditorApp.tsx, assets/src/utils/decode.ts, assets/test/utils/decoding_test.ts
Closes #472 
This PR adjusts the decoding approach to support UTF-8 encoded characters.
=> decode in a way that supports UTF-8 encoded characters

assets/src/components/editor/normalizer.ts
Closes #456 
This PR adds a normalization step to insert paragraphs in between contiguous blocks - if the blocks are of certain types.
=> insert paragraphs in between certain block types

assets/src/components/editor/editors/Audio.tsx, assets/src/components/editor/editors/Code.tsx, assets/src/components/editor/editors/Image.tsx, assets/src/components/editor/editors/Link.tsx, assets/src/components/editor/editors/Settings.tsx, assets/src/components/editor/editors/Table.tsx, assets/src/components/editor/editors/YouTube.tsx
Closes #326 
Pressing the Enter key now applies the changes in all Settings popups.  It also works in the context of modal link and youtube creation.
=> on keypress enter applies settings changes

lib/oli_web/live/qa/qa_live.ex, lib/oli_web/live/qa/warning_summary.ex
=> Keyboard nav for QA warning list items

assets/styles/authoring.scss, assets/styles/delivery.scss, assets/styles/delivery/main.scss
This PR fixes an issue where content scrolls outside main layout in safari
Closes #396
=> fix an issue where content scrolls outside main layout in safari

test/oli_web/controllers/institution_controller_test.exs
This PR resolves a broken unit test that somehow slipped into master. Any PR build without this fix will fail CI.
=> Fix broken unit test on master

assets/src/components/content/AddResourceContent.tsx, test/oli_web/controllers/institution_controller_test.exs
This PR makes add content or activity button tab navigable
Closes #521
=> Make add content or activity button tab navigable

assets/src/components/editor/editors/Blockquote.tsx, assets/src/components/editor/editors/Code.scss, assets/src/components/editor/editors/Code.tsx, assets/src/components/resource/ResourceEditor.scss, assets/src/components/resource/ResourceEditor.tsx, assets/styles/authoring/editors.scss, assets/styles/authoring/main.scss, assets/styles/delivery/main.scss, assets/styles/themes/authoring/dark/custom.scss, assets/styles/themes/authoring/dark/variables.scss, assets/styles/themes/authoring/light/variables.scss, assets/styles/themes/delivery/dark/custom.scss, assets/webpack.config.js, lib/oli/rendering/content/html.ex, lib/oli_web/templates/activity/edit.html.eex, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/templates/resource/edit.html.eex
This PR fixes an issue where dark mode styles blended font colors with background. It also add other dark mode styling improvements including:
- fix blockquote styling
- fix code block
- fix objectives and multiselects
Closes #548
**Risk**: Moderate. Adjusts some core styles, but shouldn't have much functional risk
**Stability**: Tested, seems stable
=> Dark mode text blending in with background

lib/oli/analytics/datashop/elements/event_descriptor.ex, lib/oli/analytics/datashop/elements/skills.ex
1) Look inside `model` key when parsing feedback
2) Handle missing skills without addressing root cause
=> Datashop bug stopgap solution

lib/oli/qa/reviewers/pedagogy.ex, lib/oli_web/live/qa/utils.ex, lib/oli_web/live/qa/warning_details.ex, lib/oli_web/live/qa/warning_filter.ex, lib/oli_web/live/qa/warning_summary.ex, test/oli/rendering/content/html_test.exs
=> change warning text for graded pages

lib/oli/authoring/editing/container_editor.ex, lib/oli_web/live/curriculum/activity_delta.ex, lib/oli_web/live/curriculum/container.ex, lib/oli_web/live/curriculum/rollup.ex, test/oli_web/live/curriculum/activities_delta_test.exs, test/oli_web/live/curriculum/container_test.exs, test/oli_web/live/curriculum/rollup_test.exs
This represents the very first step in Torus hierarchy implementation. 
See: https://docs.google.com/document/d/12c57lT9NbrMv3uMIaD2hT1F-FmwlQVWtgRyWrAamTCk/edit?usp=sharing for the full description of what needs to be done.
This is PR is some necessary refactoring and creation of unit tests for the page, activity and learning objective "rollup" functionality.
=> Curriculum "rollup calculation" refactor

lib/oli/release.ex
Fixes an issue where seed task wasn't working correctly on deployment.
Requires that the latest from production repo be pulled to the production servers.
=> Fix seed on deploy

lib/oli/lti_1p3/key_generator.ex, mix.exs
Removes the ExCrypto dependency and uses :public_key api directly
=> Fix deployment issue with ExCrypto

devmode.sh, lib/oli/lti_1p3.ex, lib/oli/lti_1p3/launch_validation.ex, test/oli/lti_1p3_test.exs, test/oli_web/controllers/delivery_controller_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/live/curriculum/container_test.exs, test/oli_web/live/objectives_test.exs
This PR fixes an issue where updating lti_params failed silently
Closes #616
=> Fix lti params caching

lib/oli_web/templates/institution/index.html.eex
Removes the current users name from "no institutions" message
=> remove user name from "no institutions" message

README.md, docs/LTI1.3.md
Fix spelling and wording in some documents
=> fix spelling

assets/src/components/resource/resourceEditor/ResourceEditor.scss
Could not reproduce the issue on tokamak or proton. This PR is a simple style fix for the page width issue.
Closes #624
=> fix an issue with page preview styling

config/config.exs, lib/oli/accounts.ex, lib/oli/accounts/schemas/author.ex, lib/oli/accounts/schemas/user.ex, lib/oli/grading.ex, lib/oli/utils.ex, lib/oli_web/controllers/workspace_controller.ex, lib/oli_web/live/curriculum/entries/details.ex, lib/oli_web/live/curriculum/entries/entry.ex, lib/oli_web/live/projects/table.ex, lib/oli_web/pow/user_identities_context.ex, lib/oli_web/templates/delivery/getting_started.html.eex, lib/oli_web/templates/layout/_delivery_header.html.eex, lib/oli_web/templates/project/_tr_collaborator.html.eex, lib/oli_web/templates/static_page/index.html.eex, lib/oli_web/templates/workspace/account.html.eex, lib/oli_web/views/layout_view.ex, priv/repo/migrations/20201020142621_pow.exs, priv/repo/seeds.exs
This PR finalizes the changes required to push the latest pow changes to production. The migration script has been tested on tokamak and verified it works in production-like environment.
=> Migrate user accounts

assets/styles/authoring/main.scss
=> fix an issue with contenteditable not being selectable in safari

config/test.exs, lib/oli_web/controllers/collaborator_controller.ex, lib/oli_web/controllers/invite_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/email/invitation_new_user.html.eex, lib/oli_web/templates/invite/index.html.eex, lib/oli_web/templates/layout/_admin_sidebar.html.eex, lib/oli_web/templates/project/overview.html.eex, lib/oli_web/views/invite_view.ex, test/oli_web/controllers/collaborator_controller_test.exs, test/oli_web/controllers/invite_controller_test.exs
This PR adds reCaptcha to collaboration invite
It also adds general author invite for admins
=> Invite recaptcha

CHANGELOG.md
=> add initial changelog

assets/src/data/content/writers/html.ts
Extra character in table row logic
=> Fix table creation adding extra apostrophe in front-end

CHANGELOG.md, assets/src/components/resource/editors/ObjectivesList.tsx
=> fix broken link

CHANGELOG.md, lib/oli/institutions.ex, lib/oli_web/templates/layout/help_email.text.eex, test/oli/institutions_test.exs
Use the first existing institution if multiple institutions with similar urls exist
Closes #764
=> Use the first existing institution if multiple institutions with similar urls exist

.gitignore, Dockerfile, assets/package-lock.json, docker-compose.yml, oli.example.env, supervisord.conf
This PR updates the docker setup for quick start instructions.
=> Update docker dev

assets/src/components/activities/image_coding/Evaluator.ts, assets/src/components/activities/image_coding/ImageCodingAuthoring.tsx, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/image_coding/actions.ts, assets/src/components/activities/image_coding/authoring-entry.ts, assets/src/components/activities/image_coding/delivery-entry.ts, assets/src/components/activities/image_coding/manifest.json, assets/src/components/activities/image_coding/schema.ts, assets/src/components/activities/image_coding/scripts/image_coding-edx.js, assets/src/components/activities/image_coding/scripts/image_coding-table-edx.js, assets/src/components/activities/image_coding/scripts/image_coding_view.js, assets/src/components/activities/image_coding/sections/Feedback.tsx, assets/src/components/activities/image_coding/utils.ts, assets/src/components/resource/TestModeHandler.tsx, test/oli/registrar_test.exs
Initial working implementation of image coding activity used in KTH programming course, with authoring, delivery and client-side evaluation of graded exercises.
=> KTH image coding

assets/src/components/activities/image_coding/Evaluator.ts, assets/src/components/activities/image_coding/ImageCodingAuthoring.tsx, assets/src/components/activities/image_coding/ImageCodingDelivery.tsx, assets/src/components/activities/image_coding/actions.ts, assets/src/components/activities/image_coding/schema.ts, assets/src/components/activities/image_coding/utils.ts, assets/src/components/media/manager/MediaManager.tsx, lib/oli/institutions.ex, test/oli/delivery/attempts_test.exs
This adds support for the table programming problems using csv files with grading by matching text output to an author-specified regular expression. With this addition, the activity should be able to support every problem in the KTH course. 
This makes effectively two types of coding problems: image problems, which are graded by comparing solution-code generated image to the user-code generated image with a specified tolerance; and all others (including but not limited to table problems), which are graded by matching a regular expression to the student code's text output. Any problem that uploads an image when authoring is considered an image problem. The authoring allows uploading either images or spreadsheets (csv) but not both.
=> KTH table problem support

lib/oli_web/templates/shared/_cookie_consent.html.eex
PR to fix cookie preferences toggle button with underlying model stored as cookie
=> sync cookie prefs

CHANGELOG.md, assets/src/components/activities/image_coding/ImageCodingAuthoring.tsx, assets/src/components/editing/commands/AudioCmd.tsx, assets/src/components/editing/commands/ImageCmd.tsx, assets/src/components/editing/models/image/commands.tsx, assets/src/components/media/UrlOrUpload.tsx, assets/src/components/media/manager/MediaManager.controller.ts, assets/src/components/media/manager/MediaManager.tsx, lib/oli_web/controllers/media_controller.ex
This PR adds the ability to change an image.
Closes #958
=> Change images

CHANGELOG.md, assets/styles/authoring/main.scss, assets/styles/authoring/variables.scss, assets/styles/common/previous_next_nav.scss, assets/styles/delivery/footer.scss, assets/styles/delivery/layout/delivery.scss, assets/styles/delivery/main.scss, assets/styles/delivery/page_delivery/elements.scss, assets/styles/delivery/page_delivery/page.scss, assets/styles/delivery/purpose.scss, assets/styles/delivery/variables.scss, assets/styles/themes/delivery/dark/variables.scss, lib/oli/rendering/activity.ex, lib/oli/rendering/activity/html.ex, lib/oli/rendering/content/html.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/layout/_delivery_footer.html.eex, lib/oli_web/templates/layout/page.html.eex, lib/oli_web/templates/page_delivery/advanced_delivery.html.eex, lib/oli_web/templates/page_delivery/page.html.eex, lib/oli_web/templates/resource/page_preview.html.eex, test/oli/rendering/activity/html_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs
This PR fixes some delivery style issues related to light/dark mode, tables and images. The course preview work mostly fixed any discrepancies between preview and delivery but part of this task was running through content in both preview and delivery to make sure it matched exactly.
Closes #964
Closes #962
=> Preview delivery cleanup

CHANGELOG.md, lib/oli_web/router.ex
Closes #979 
This PR disables OpenAPI docs in prod
=> disable openapi docs in prod

assets/package.json, assets/src/apps/delivery/components/PartComponent.tsx, assets/src/apps/delivery/formats/adaptive/ActivityRenderer.tsx, assets/src/components/parts/customElementWrapper.ts, assets/src/components/parts/janus-image/Image.tsx, assets/src/components/parts/janus-image/authoring-entry.ts, assets/src/components/parts/janus-image/delivery-entry.ts, assets/src/components/parts/janus-image/manifest.json, assets/src/components/parts/janus-text-flow/TextFlow.tsx, assets/src/components/parts/janus-text-flow/authoring-entry.ts, assets/src/components/parts/janus-text-flow/delivery-entry.ts, assets/src/components/parts/janus-text-flow/manifest.json, assets/src/components/parts/partsApi.ts, assets/webpack.config.js, config/config.exs, lib/oli/activities/part_component_manifest.ex, lib/oli/activities/part_component_map_entry.ex, lib/oli/activities/part_component_registration.ex, lib/oli/activities/part_component_registration_project.ex, lib/oli/authoring/course/project.ex, lib/oli/part_components.ex, lib/oli/registrar.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/advanced_delivery.html.eex, priv/repo/migrations/20210421162709_create_part_component_registrations.exs, priv/repo/seeds.exs, test/oli/part_components_test.exs, test/support/test_helpers.ex
sets things up for "part components" similar to how activities are registered but representing a different set of custom elements that are used in adaptive (and future) activities
=> [FEATURE] Parts Components

lib/oli_web/endpoint.ex, oli.example.env
This PR includes some configuration changes for proper deployments
=> Deploy fix

CHANGELOG.md, assets/styles/delivery/main.scss, assets/styles/delivery/page_delivery/prologue.scss, lib/oli_web/templates/page_delivery/_link_assessment.html.eex, lib/oli_web/templates/page_delivery/_link_page.html.eex, lib/oli_web/templates/page_delivery/container.html.eex
This PR fixes some styling issues introduced by a previous style fix.
Fixes rounded corners and missing bottom border.
It also includes a fix for delivery assessment prologue in dark mode.
=> [BUG FIX] Overview style inconsistencies

assets/src/components/hooks/usePrevious.ts, assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx, assets/src/components/parts/janus-mcq/MultipleChoiceQuestionType.ts, assets/src/components/parts/janus-mcq/authoring-entry.ts, assets/src/components/parts/janus-mcq/delivery-entry.ts, assets/src/components/parts/janus-mcq/manifest.json, assets/src/components/parts/types/parts.ts, priv/repo/seeds.exs
-- Janus-MCQ as part component
--added type definition for MCQ
-- added UsePrevious hooks
=> [Feature] Janus mcq part component

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
-- added changes in trigger check result
-- checked-in initial changes for handling mutation
-- initial changes for calling props.init when a activity changes but the SIM remains the same
=> [FEATURE] SIM Issues fix

assets/src/adaptivity/rules-engine.ts, assets/src/apps/delivery/components/ActivityRenderer.tsx, assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
-- added code for updating scripting data when session variables are updated on trigger check. They were only getting updated in the store
-- added mutate logic in CAPI. still need to add the props.notify in all the part components
=> [Feature] mutate state support

CHANGELOG.md, config/config.exs, config/test.exs, lib/oli/branding.ex
Fixes an issue where the torus logo doesn't display properly in dark mode.
Maybe closes #1120
=> [BUG FIX] fix dark logo config

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx, assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx, assets/src/components/parts/janus-text-flow/Markup.tsx
-- added a fix for KIP Reset and hint button issue
-- added trigger check handle for the navigation button
-- fixed pop-up not displaying all the content
=> [BugFix] sim issues

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx, assets/src/apps/delivery/store/features/groups/actions/deck.ts, assets/src/apps/delivery/store/features/groups/actions/navUtils.ts, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx, assets/src/components/parts/janus-dropdown/Dropdown.tsx
-- contains a fix for Janus-dropdown part component
-- phases of Moon bug fix
-- timeout issue when rendering an activity without any part component.
-- overriding configData value with Init trap state configuration
=> [Bugfix] phases of moon bugfix

assets/styles/preview.scss, assets/styles/preview/preview-tools-reset.scss, assets/styles/preview/preview-tools.scss
prevents 3rd party styles from impacting the preview tools
=> PMP-1429: Preview Mode Bootstrap is impacting the Lesson Presentation in Torus

config/config.exs, config/dev.exs, config/releases.exs, mix.exs, oli.example.env
This PR fixes a deployment issue with mnesia persistent sessions by adding mnesia to extra_applications config
=> Fix mnesia dependency

assets/src/apps/delivery/Delivery.tsx, assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx, assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/apps/delivery/store/features/groups/actions/deck.ts, assets/src/apps/delivery/store/features/page/actions/loadInitialPageState.ts, assets/src/apps/delivery/store/features/page/slice.ts, assets/src/components/parts/janus-dropdown/Dropdown.tsx
-- added support for variables and global variables.
-- changes for applying layer custom classes to its child screens
-- Check if the first screen is a Layer or QB
-- implement reset activity on initial load
=> [Bugfix] Delivery Player Hardening

.github/workflows/deploy.yml, .github/workflows/package.yml
This PR updates the deployment port used in the CD jobs. Tested on tokamak and works as expected.
=> [CHORE] Update deployment job ports

assets/src/apps/authoring/AdaptivityEditor.tsx, assets/src/apps/authoring/BottomPanel.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/src/apps/authoring/components/HeaderNav.tsx, assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx, assets/styles/authoring/advanced-authoring.scss
added tooltips to advanced authoring ui
=> Advanced Authoring Tooltips

assets/package.json, assets/src/components/parts/janus-Carousel/Carousel.css, assets/src/components/parts/janus-Carousel/Carousel.tsx, assets/src/components/parts/janus-Carousel/manifest.json, assets/src/components/parts/janus-fill-blanks/FillBlanks.css, assets/src/components/parts/janus-fill-blanks/FillBlanks.tsx, assets/src/components/parts/janus-fill-blanks/FillBlanksType.ts, assets/src/components/parts/janus-fill-blanks/Quill.css, assets/src/components/parts/janus-fill-blanks/authoring-entry.ts, assets/src/components/parts/janus-fill-blanks/delivery-entry.ts, assets/src/components/parts/janus-fill-blanks/manifest.json, assets/src/components/parts/janus-slider/Slider.scss, assets/src/components/parts/janus-slider/Slider.tsx, assets/src/components/parts/types/types.d.ts, lib/oli_web/templates/layout/chromeless.html.eex, priv/repo/migrations/20210614145546_removeJanusCarouselPartRegistrations.exs, priv/repo/seeds.exs
-- contains changes for 3 part components
-- contains bug fixes for alignment issues in slider and FIB
=> [FEATURE] FIB-Carousel-Slider Part Component

lib/oli_web/templates/layout/chromeless.html.eex
Add the externalized React and ReactDom script includes to the layout that powers adaptive player
=> apply externalized react to chromess layout

assets/src/components/parts/janus-dropdown/Dropdown.tsx, assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx
-- formatting in MCQ component
-- fix for PMP-1480
=> [BUGFIX] PMP-1480

assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx
-- contains fix for Red Rocks 81114: Cannot proceed after Max Attempts: Screen 64
=> [BUG] PMP-1499

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
-- contains fix for progress bar not working in multiple lessons
=> [BUG] SIM issue - Progress bar 

assets/src/components/parts/janus-Carousel/Carousel.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx, assets/src/components/parts/janus-fill-blanks/FillBlanks.tsx, assets/src/components/parts/janus-input-number/InputNumber.scss, assets/src/components/parts/janus-input-number/InputNumber.tsx, assets/src/components/parts/janus-input-text/InputText.tsx, lib/oli_web/templates/layout/chromeless.html.eex
-- contains fix for PMP-1509
-- fixed .css file missing issue for Janus Carousel part component
=> [BUG] Plate Tectonics bug fixes

CHANGELOG.md, assets/src/phoenix/activity_bridge.ts
This PR fixes an issue where to image coding activity was broken in preview.
=> [BUG FIX] Submit evaluations preview fix

CHANGELOG.md, assets/styles/authoring/curriculum.scss, assets/yarn.lock, lib/oli_web/live/curriculum/entries/entry.ex
This PR adjusts the UI of the curriculum editor to more clearly delineate the actions of "navigate within the hierarchy" from the action of "edit this page".  It does so by adding a new "Edit" link just to the right of the page title. 
I experimented with a few different approaches: using a button, right-alignment, etc.  But this approach visually seems the cleanest.
=> [FEATURE] Clearly separate navigation vs edit actions in curriculum editor

priv/repo/migrations/20210709161013_change_scope.exs
This PR fixes a bad previous migration.
=> fix scope attr

Dockerfile, configure-env-for-compose.sh, docker-compose.yml
* add dockerfile to build torus application
* update docker compose such that both the database and the application can be spun up in a single command.
* add a new script that sets up env files for docker-compose environment.
It can be tested locally with
```sh
./configure-env-for-compose.sh
docker-compose up
```
=> [FEATURE] dockerize application

lib/oli/accounts.ex, lib/oli/activities/realizer/logic.ex, lib/oli/activities/realizer/query/builder.ex, lib/oli_web/controllers/api/activity_bank_controller.ex, lib/oli_web/router.ex, test/oli_web/controllers/api/activity_bank_controller_test.exs
The main goal of this PR is to introduce `OliWeb.Api.ActivityBankController` which implements a POST endpoint for allowing soon to be developed front-end code to search, page, filter through the activities in a course project's activity bank.
=> [FEATURE] Implement REST endpoint for retrieval from bank

assets/src/apps/authoring/BottomPanel.tsx, assets/src/apps/authoring/components/Accordion/ContextAwareToggle.tsx, assets/src/apps/authoring/components/RightMenu/RightMenu.tsx, assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx, assets/styles/authoring/advanced-authoring.scss
=> PMP-1506: Rendering in Hierarchy Menu

assets/src/components/activities/check_all_that_apply/actions.ts, assets/src/components/activities/common/hints/authoring/hintActions.ts, assets/src/components/activities/common/responses/responseActions.ts, assets/src/components/activities/image_coding/ImageCodingAuthoring.tsx, assets/src/components/activities/image_coding/actions.ts, assets/src/components/activities/multiple_choice/actions.ts, assets/src/components/activities/ordering/actions.ts, assets/src/components/activities/types.ts, assets/src/utils/common.ts, assets/src/utils/undo.ts, assets/test/utils/undo_test.ts
This PR reapplies undo operations to all activities, given the latest set of changes to activity impls. This work was originally on another branch where it became too complicated to resolve conflicts.
=> [FEATURE] Implement remaining undos

.github/actions/phoenix-builder/Dockerfile, .github/actions/phoenix-builder/entrypoint.sh, .github/workflows/build.yml
Fixes the build system by using yarn instead of npm install.
=> Yarn build fix

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx, assets/src/apps/delivery/store/features/groups/actions/deck.ts, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
-- only change is in External activity
-- rest are just commenting out the console.log
=> [BUG] PMP-1592

lib/oli/delivery/attempts/core.ex, test/oli/datashop_test.exs
No changelog, I figure this falls into the previous bug fix commit.
=> [BUG FIX] Filter out unevaluated part attempts from datashop code

CHANGELOG.md, assets/src/components/activities/common/choices/authoring/ChoicesAuthoring.scss, assets/src/components/common/DraggableColumn.scss, assets/src/components/resource/Editors.scss, assets/src/components/resource/editors/ObjectivesList.scss, assets/src/components/tabbed_navigation/Tabs.tsx, lib/oli_web/live/insights/insights.ex, lib/oli_web/live/insights/table_header.ex, lib/oli_web/live/insights/table_row.ex, lib/oli_web/live/objectives/breakdown_modal.ex
Fix some firefox issues and some other ui weirdness. See changelog.
=> [BUG FIX] Small but annoying UI problems

lib/oli/features.ex, lib/oli/qa.ex, lib/oli/qa/reviewers/equity.ex, lib/oli_web/live/qa/state.ex, test/oli/features_test.exs, test/oli_web/live/qa_logic_test.exs
Enables a prototyped "Equity check" for QA mode.  This is for demo purposes only and thus is hidden behind a feature flag.
=> [FEATURE] Equity checker

CHANGELOG.md, lib/oli_web/templates/delivery/research_consent.html.eex
This PR updates the research consent form, to include Norm's name instead of Joel Smith.
=> [BUG FIX] updated research consent form

assets/src/components/parts/janus-popup/Popup.tsx
-- context mode was not getting passed on from pop-up to part component renderer
=> [BUG] PMP-1654

assets/src/apps/delivery/components/PartComponent.tsx
I am not sure if this solution has any hidden impact, but as far as i have tested it with couple of lessons, adding display block to the part components tag, hasnt showed any UI related changes. 
Let me know if this approach has any possible issues.
=> [Bug] PMP-1496: Feedback not displaying all content

assets/src/apps/authoring/components/PropertyEditor/schemas/screen.ts
Remove the Screen Button Label and Check Box
=> [Bug] PMP-1662: Remove the Screen Button Label and Check Box

CHANGELOG.md, assets/src/components/editing/models/blockcode/Blockcode.scss, assets/src/components/editing/models/blockcode/Editor.tsx, assets/src/components/editing/models/youtube/Editor.tsx, assets/src/components/editing/toolbars/common.tsx, assets/src/components/editing/toolbars/insertion/Toolbar.tsx, assets/src/data/content/writers/html.ts, assets/src/data/content/writers/writer.ts, assets/styles/authoring/model-editors.scss, assets/styles/delivery/layout/delivery.scss, assets/styles/delivery/page_delivery/elements.scss, assets/test/writer/writer_test.ts, lib/oli/rendering/content/html.ex, test/oli/rendering/content/html_test.exs
- Fix iframe rendering when elements contain captions (webpage, youtube)
- Fix iframe rendering in activities
- Escape activity content item attributes
- ~~**Add max-width for all content in delivery mode** (maybe controversial, but I find it to be too hard to read the pages with as wide as they are)~~
- Remove extra styles not being used now that all images/embeds are "block only" (and can't be floated)
=> [BUG FIX] Fix some delivery mode rendering issues

assets/src/components/parts/janus-dropdown/Dropdown.tsx
-- contains fixes for PMP-1581 & PMP-1671
-- fixed some other issues related to drop down where we see a blank option in the dropdown which was not in SS
=> [BUG] Dropdown begins with option selected - Multi Lesson Issue

CHANGELOG.md, assets/styles/authoring/layout/workspace.scss, assets/styles/authoring/variables.scss, assets/styles/display.scss, assets/styles/themes/authoring/torus/dark.scss, lib/oli_web/live/common/table/sortable_table.ex, lib/oli_web/live/curriculum/container/container_live.html.leex, lib/oli_web/live/features/features_live.ex, lib/oli_web/live/objectives/objectives.ex, lib/oli_web/live/projects/projects_live.ex, lib/oli_web/live/qa/qa_live.ex, lib/oli_web/templates/activity_manage/index.html.eex, lib/oli_web/templates/ingest/index.html.eex, lib/oli_web/templates/invite/index.html.eex, lib/oli_web/templates/layout/_account_header.html.eex, lib/oli_web/templates/layout/_admin_sidebar.html.eex, lib/oli_web/templates/layout/_project_header.html.eex, lib/oli_web/templates/layout/_workspace_header.html.eex, lib/oli_web/templates/project/insights.html.eex, lib/oli_web/templates/project/publish.html.eex, lib/oli_web/templates/shared/_not_found.html.eex
This PR fixes some style quirks with the workspace header colors and font size. It also makes padding more consistent across pages in the workspace.
=> Fix header styles and padding

assets/src/apps/authoring/BottomPanel.tsx, assets/src/apps/authoring/components/HeaderNav.tsx, assets/styles/authoring/advanced-authoring.scss
few other minor styles for component tab collapsible .
=> Panel to be slightly wider

assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx, assets/styles/authoring/advanced-authoring.scss
– fixed context menu from getting cutoff
– cleaned up context menu templating
=> [PMP-1678] Adaptivity: Can not Rename or Delete the Last adaptivity Rules

assets/src/apps/authoring/BottomPanel.tsx, assets/src/apps/authoring/components/AdaptiveRulesList/AdaptiveRulesList.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/styles/authoring/advanced-authoring.scss
– adds ability to disable default correct rule 
– removes ability to add conditions to default wrong rule
– removes ability to toggle default rules correct/incorrect
=> [PMP-1714] Ability to Disable Default Correct State

assets/src/components/parts/janus-popup/Popup.tsx, assets/src/components/parts/janus-slider/Slider.tsx
-- passed snapshot to pop-up component
-- contains fix for PMP-1651 as well
=> [BUG] PMP-1739

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
-- previous change for another fix broke few things like each from SIM was getting fired twice and due to that the few functionalities were not working.
-- changed the approach now and it is working fine now
=> [BUG] PMP-1732

assets/src/apps/authoring/Authoring.tsx, assets/styles/authoring/advanced-authoring.scss
added loading screen for advanced authoring
=> [PMP-1685] Authoring Loading Screen

assets/src/apps/authoring/BottomPanel.tsx, assets/src/apps/authoring/components/AdaptiveRulesList/AdaptiveRulesList.tsx
- adds adaptive rule reordering functionality
- insert new rules after the currently selected rule
=> [PMP-1606] Adaptivity: Reordering of Rules

assets/src/apps/authoring/components/AdaptivityEditor/ConditionsBlockEditor.tsx
fixes nested condition group not deleting
=> [PMP-1742] Adaptivity: Deleting a Group does not work in the trap state conditions

config/releases.exs, oli.example.env
This PR fixes a runtime configuration issue preventing the server from starting.
=> [BUG FIX] fix runtime log level config

assets/src/components/parts/janus-text-flow/Markup.tsx, assets/src/components/parts/janus-text-flow/QuillEditor.tsx, assets/src/components/parts/janus-text-flow/TextFlowAuthor.tsx, assets/src/components/parts/janus-text-flow/quill-utils.ts
still known to not work quite right:
fonts
links
adaptivity toolbar item
dragging after edit reverts
=> [JAN-215, PMP-751] advanced authoring text editing

CHANGELOG.md, lib/oli_web/live/projects/cards.ex, lib/oli_web/live/projects/projects_live.ex, lib/oli_web/live/projects/state.ex, lib/oli_web/live/projects/table.ex
This PR implements ability for an admin to hide deleted projects in the projects view.
=> [FEATURE] Allow an admin to hide deleted projects

assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityPartInheritance.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts
updates were made to the wrong resourceId, clobbering the page with the activity
=> [BUGFIX] activity bulk edit impl

assets/src/apps/authoring/components/EditingCanvas/AuthoringActivityRenderer.tsx, assets/styles/authoring/advanced-authoring.scss
Adds ability to scroll the stage area
=> [BUGFIX] Stage scrolling

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/components/parts/janus-popup/Popup.tsx
-- this PR contains a workaround fix for small world - open and free issue. Once Beagle app  functionality is integrated into the Torus, we can remove the code
=> PMP-1724 | JAN-553

assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx, assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx, assets/src/components/parts/janus-input-number/InputNumber.tsx, assets/src/components/parts/janus-input-number/InputNumberAuthor.tsx, assets/src/components/parts/janus-input-number/schema.ts, assets/src/components/parts/janus-navigation-button/NavButtonAuthor.tsx, assets/src/components/parts/janus-navigation-button/schema.ts, assets/src/components/parts/janus-slider/Slider.tsx, assets/src/components/parts/janus-slider/SliderAuthor.tsx, lib/oli_web/templates/layout/authoring.html.leex
preview fixes for input number, nav button, slider
=> JAN-634 JAN-635 / PMP-1804 PMP-1802 author previews

assets/src/adaptivity/operators/contains.ts
-- updated contains operator logic
=> PMP-1793 | JAN-614

assets/src/components/parts/janus-navigation-button/NavigationButton.tsx, assets/src/components/parts/janus-slider/Slider.scss, assets/src/components/parts/janus-slider/SliderAuthor.tsx
slider and nav button sizing issues
=> [BUGFIX] authoring preview adjustments

assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx, assets/src/components/activities/adaptive/components/common/PartComponent.tsx
also updates some missing deps in callbacks and optimistically updates the local state for better responsiveness when deleting
=> [BUGFIX PMP-1833 / JAN-667] hide toolbar after delete

assets/src/apps/authoring/components/RightMenu/RightMenu.tsx, assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx, assets/src/components/activities/adaptive/components/common/PartComponent.tsx, assets/src/components/parts/janus-text-flow/QuillEditor.tsx, assets/src/components/parts/janus-text-flow/TextFlowAuthor.tsx, assets/src/components/parts/janus-text-flow/quill-utils.ts
area too sensitive for accidentally closing the modal when editing text, created a small buffer around it.
saving position changes from the side bar wasn't working for textflow and perhaps others
editing multiple texts were clobbering each other due to stale state stuck in event handlers
=> [BUGFIX] PMP-1814 JAN-676 PMP-1842 JAN-658 text flow issues

assets/src/components/parts/janus-capi-iframe/CapiIframeAuthor.tsx, assets/src/components/parts/janus-capi-iframe/schema.ts
--Initial changes for CAPI Authoring Support
=> PMP-1857 | JAN-672

CHANGELOG.md, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/delivery/manage_section.ex, lib/oli_web/live/delivery/manage_updates.ex, lib/oli_web/templates/layout/_project_sidebar.html.eex, lib/oli_web/templates/layout/_workspace_sidebar.html.eex, lib/oli_web/templates/open_and_free/show.html.eex, lib/oli_web/templates/page_delivery/index.html.eex, lib/oli_web/templates/page_delivery/updates.html.eex, lib/oli_web/views/delivery_view.ex, lib/oli_web/views/layout_view.ex, lib/oli_web/views/page_delivery_view.ex, lib/oli_web/views/view_helpers.ex, mix.exs
This PR fixes a number of authorization issues based on LTI platform and context role, mainly around not sufficiently checking all applicable roles. It also refactors some of the authorization logic to be more standardized and readable.
=> [BUG FIX] fix and cleanup authorizations

assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx, assets/src/components/parts/janus-popup/authoring-entry.ts, assets/src/components/parts/janus-popup/schema.ts, assets/src/components/parts/janus-text-flow/authoring-entry.ts, assets/src/components/parts/janus-text-flow/schema.ts, assets/src/components/parts/types/parts.ts
setup a capability api for configuring the toolbar and drag per part type; start of the feature that will enable popup and others to configure more about what toolbar capabilities are available.
=> [FEATURE] PMP-1841 popup

.github/actions/phoenix-builder/entrypoint.sh, assets/package.json
This PR fixes an issue during deployment where packaging webpack assets exceeds JS heap memory space.
=> [Chore] Increase webpack heap space

assets/src/apps/delivery/components/preview-tools/inspector/AutoDetectInput.tsx, assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx, assets/src/components/parts/janus-capi-iframe/CapiIframeAuthor.tsx, assets/src/components/parts/janus-capi-iframe/CapiVariablePicker.tsx, assets/src/components/parts/janus-capi-iframe/authoring-entry.ts, assets/src/components/parts/janus-capi-iframe/schema.ts
-- contains changes for CAPI - variable modal dialog
-- loading existing SIM
-- Saving changes
=> [FEATURE] CAPI Authoring support contd..

assets/src/components/parts/janus-Carousel/Carousel.tsx, assets/src/components/parts/janus-Carousel/CarouselAuthor.tsx, assets/src/components/parts/janus-Carousel/delivery-entry.ts, assets/src/components/parts/janus-Carousel/schema.ts
clean up schema; refactor to use json model; remove custom css; change custom css class to match;
=> [BUGFIX] Carousel Issues PMP-1881 JAN-696

assets/src/apps/authoring/components/AdaptivityEditor/ActionMutateEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptiveItemOptions.ts, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ConditionItemEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/InitStateEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/VariablePicker.tsx
**This PR includes** work for the following sub-tasks:
* PMP-1852: Init & Mutate State - Limit to the Current Screen
* PMP-1853: Dropdown for Init And Mutate: Filter out Add for non numbers
* PMP-1855: Fix the Screen Ids and Pipes - when picking IDs from other screens needs to be a pipe then variable
**Remaining work** (future PR) to close PMP-1559 / JAN-332:
* PMP-1854: Dropdown should limit selection to valid combinations
=> [FEATURE] [PMP-1559 / JAN-332] Adaptivity: Variable Picker

assets/src/adaptivity/scripting.ts, assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx, assets/src/apps/delivery/store/features/groups/actions/deck.ts, assets/test/adaptivity/scripting_test.ts
not actually a bug fix more just code to defend against errors made by the author
=> [BUGFIX] PMP-1785 JAN-606

assets/src/apps/authoring/components/AdaptivityEditor/VariablePicker.tsx, assets/src/components/parts/janus-capi-iframe/CapiIframeAuthor.tsx, assets/src/components/parts/janus-capi-iframe/authoring-entry.ts, assets/src/components/parts/janus-capi-iframe/schema.ts
-- fixes "config" click and save glitches
-- code clean-up
-- variable picker support for CAPI
=> [FEATURE] CAPI Authoring Contd. JAN-672 | JAN-674

assets/src/apps/delivery/layouts/deck/components/FeedbackRenderer.tsx
multiple feedbacks are supposed to render individually.
applying some styles to get closer to SS defaults of most themes.
applying other "screen" settings that were previously ignored.
=> [BUGFIX] Feedback Rendering

CHANGELOG.md, assets/styles/authoring/layout/workspace.scss
Fixes an issue where footer styles overlap content in workspace.
=> [BUGFIX] fix footer placement

assets/package.json, assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/yarn.lock
Fixes the issue where the `<PropertyEditor />` would not save changes on checkbox toggle without first focusing / blurring a text input.
=> [BUGFIX] [PMP-1927 / JAN-739]: Clicking Check Boxes is not saving the change

CHANGELOG.md, config/config.exs, oli.example.env
This PR adds some release documentation for paywall support
=> [CHORE] update release docs

assets/src/apps/authoring/components/RightMenu/RightMenu.tsx
force property editor to refresh per part id
=> [BUGFIX] cannibal parts

assets/src/components/parts/janus-fill-blanks/authoring-entry.ts
=> [BUGFIX] [PMP-1958] Fix FIB CSS bleeding into Authoring Env

assets/src/components/parts/janus-fill-blanks/authoring-entry.ts, assets/src/components/parts/janus-fill-blanks/schema.ts
adds missing dynamic variables from FIB to variable picker
=> [BUGFIX] [PMP-1916] FIB Missing Variables in Variable Picker

assets/src/components/parts/janus-popup/authoring-entry.ts, assets/src/components/parts/janus-popup/schema.ts
Adds the missing adaptivitySchema for the popup component
=> [Bugfix] [PMP-1917] Pop Up component missing from Variable Picker

assets/src/apps/authoring/components/AdaptivityEditor/ActionFeedbackEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ActionMutateEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ActionNavigationEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ConditionItemEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/InitStateEditor.tsx
Adds more delete confirmation modals to the following: 
* Init State rules
* Navigation actions
* Mutate actions
* Individual rule conditions
=> [Feature] [PMP-1995 / JAN-792] More Delete Confirmations in Adaptivity

assets/src/components/parts/janus-text-flow/Markup.tsx
revert this as it breaks stuff
=> [BUGFIX] text line height

assets/styles/themes/delivery/adaptive_themes/default/activities/mcq.scss
changed the width of input to a square
=> PMP-1754 -mcq

assets/styles/themes/delivery/adaptive_themes/default/activities/mcq.scss
Added the remaining tweaks needed for MCQ
=> Pmp 1754 mcq

lib/oli/delivery/gating.ex, lib/oli/delivery/gating/gating_condition.ex, lib/oli/delivery/gating/gating_condition_data.ex, lib/oli/delivery/gating/gating_condition_evaluator.ex, lib/oli/delivery/gating/strategies/schedule.ex, lib/oli/delivery/gating/strategies/strategy.ex, priv/repo/migrations/20211103123520_create_gating_conditions.exs, test/oli/delivery/gating/strategies/schedule_test.exs, test/oli/delivery/gating_test.exs
This PR contains the first pieces of work toward gating and scheduling:
1. add migration for gating conditions
2. add schema and context
3. implement query by resource_ids
4. implement gating condition evaluator interface
=> [FEATURE] PR1 for gating and scheduling

lib/oli_web/controllers/workspace_controller.ex
This PR restores the workspace preferences api functions that are still used by the client.
=> [BUG FIX] restore preferences api functions

lib/oli_web/controllers/api/product_controller.ex, lib/oli_web/views/api/product_view.ex, test/oli_web/controllers/api/product_controller_test.exs
In product API, returns nil for amount when product does not require payment.
=> MER-394 Returns nil amount for non-required payment product in API

CHANGELOG.md, assets/src/apps/delivery/store/features/attempt/actions/savePart.ts, assets/src/apps/delivery/store/features/attempt/slice.ts, assets/src/apps/delivery/store/features/groups/selectors/deck.ts, config/config.exs, lib/oli/rendering/activity.ex, lib/oli/rendering/activity/html.ex, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/context.ex, lib/oli/rendering/page.ex, lib/oli/utils.ex, lib/oli_web/controllers/collaborator_controller.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/controllers/lti_controller.ex, test/oli/rendering/activity/html_test.exs, test/oli/rendering/content/html_test.exs, test/oli/rendering/page/html_test.exs, test/oli_web/controllers/collaborator_controller_test.exs
This PR improves error logging and adds some error logging to the lti controller. It also fixes a typo Activty -> Activity
=> [CHORE] Improve error telemetry

assets/src/components/activities/adaptive/AdaptiveDelivery.tsx, assets/src/components/parts/customElementWrapper.ts
web components were not properly firing unmount
=> [BUGFIX] issues uncovered while troubleshooting everapp

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx
I have tested the changes with 'Open and Free' as well and it is working as expected.
=> PMP-1996 | JAN-793

assets/src/apps/delivery/components/ActivityRenderer.tsx, assets/src/apps/delivery/layouts/deck/EverAppContainer.tsx, assets/src/apps/delivery/layouts/deck/EverApps.ts, assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx, assets/src/components/parts/customElementWrapper.ts, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
everapps now will use the full activity API and the observer works in sonoran desert
=> [BUGFIX] Everapps

assets/styles/themes/delivery/adaptive_themes/default/activities/fill-blanks.scss, assets/styles/themes/delivery/adaptive_themes/default/activities/image-carousel.scss, assets/styles/themes/delivery/adaptive_themes/default/activities/image.scss, assets/styles/themes/delivery/adaptive_themes/default/activities/mcq.scss, assets/styles/themes/delivery/adaptive_themes/default/activities/popup.scss, assets/styles/themes/delivery/adaptive_themes/default/activities/slider.scss, assets/styles/themes/delivery/adaptive_themes/default/activities/text-flow.scss, assets/styles/themes/delivery/adaptive_themes/default/light.scss
This is a big PR. A few highlights are:
- Updated the light.scss file by adding imports of new style files
- Added a image.scss file in case I need it late. I may not though.
- Addressed margins in text-flow.scss for when you have multiple <p> elements within one text-flow activity
- Worked on popup.scss and figured out how to display popup buttons and the close button for the popup window.
- Styled the image-carousel.scss. This one _should_ be good to go. 
- Styled the FITB activity. Still working on the correct/incorrect states of the dropdowns. The fill-blanks.scss file is just a reference file since the style needs to be minified and placed into the activity's JSON.
- I haven't touched slider.scss much
=> Pmp 1421 text flow

assets/src/components/parts/janus-video/Video.tsx
Created a separate PR for Janus-Schema - https://github.com/ETX-ASU/janus-schema/pull/79
=> PMP-1869 | JAN-685

assets/styles/themes/delivery/adaptive_themes/default/layout/check-container.scss
Formatted to Sass, updated feedback so that it behaves as expected again.
https://jira.unicon.net/jira/browse/PMP-1960
=> PMP-1960 Formatted to Sass, updated feedback

assets/styles/themes/delivery/adaptive_themes/default/activities/fill-blanks.scss
improved correct and incorrect dropdown states
https://jira.unicon.net/jira/browse/PMP-2035
=> PMP-2035 fill in the blanks

assets/styles/themes/delivery/adaptive_themes/default/activities/image-carousel.scss
Formatted for sass and added focus style for pagination.
https://jira.unicon.net/jira/browse/PMP-2036
=> PMP-2036 Formatted for sass

assets/styles/themes/delivery/adaptive_themes/default/activities/mcq.scss
formatted to SASS, added some hover styles, and removed unnecessary styles and !important tags
https://jira.unicon.net/jira/browse/PMP-1783
=> PMP-1783 formatted, hover/focus styles added, streamlined.

CHANGELOG.md, lib/oli_web/templates/page_delivery/advanced_delivery.html.eex
Fixes an issue where advanced authoring next prev links caused a 500 internal server error
=> [BUG FIX] Fix advanced authoring next prev links

assets/src/apps/authoring/components/AdaptivityEditor/AdaptiveItemOptions.ts, assets/src/apps/authoring/components/AdaptivityEditor/ConditionItemEditor.tsx, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts, assets/src/apps/delivery/store/index.ts
condition fact types were inferred from the value alone, need to check the operator in the case that it's something like isNaN which is for numbers, but the value is `true`
=> [Bugfix] PMP-2219 JAN-1035 authoring condition types

lib/oli_web/live/grades/grades.ex
Add the title and breadcrumbs assigns
=> [BUGFIX] Add title and breadcrumbs assigns

assets/src/apps/delivery/layouts/deck/components/FeedbackContainer.tsx, assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx
MCQ wasn't recording selections properly
Feedback wasn't getting latest state anymore
=> [Bugfix] seasons multiple issues

assets/styles/authoring/advanced-authoring.scss, assets/styles/authoring/layout/workspace.scss
fixes misaligned adaptive page authoring UI caused by [FEATURE] [MER-312] Community and admin CRUD (#1866)
[MER-312]: https://eliterate.atlassian.net/browse/MER-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX] [NOJIRA] Fix Misaligned Adaptive Page Authoring UI

CHANGELOG.md, lib/oli/analytics/datashop/elements/event_descriptor.ex, mix.exs
Add support for parsing student input based on activity type, so a readable student selection appears in the datashop download.
=> [BUG FIX] Datashop activity selection inputs

assets/src/components/parts/janus-audio/Audio.tsx, assets/src/components/parts/janus-audio/schema.ts
Fixes `exposureInSeconds`, `exposurePercentage`, `totalSecondsWatched` and `currentTime` not working properly.
=> [BUGFIX] [PMP-2062 / JAN-854] Audio Player Issues

assets/src/components/parts/janus-dropdown/Dropdown.tsx
fixes `selectedIndex` and `selectedItem` for initial and mutate states
=> [BUGFIX] [PMP-2074 / JAN-866] Dropdown Issues

assets/src/components/parts/janus-text-flow/Markup.tsx
visibility: hidden for handling the hyphen issue should be set for the span tag only not every tag.
=> images were hidden

assets/src/components/parts/janus-fill-blanks/FillBlanks.tsx, assets/src/components/parts/janus-fill-blanks/schema.ts
Fixes FIB issues with `showCorrect`, `showHints`, and `attempted` properties in various places (variable picker, inspector, model props and states).
=> [BUGFIX] [PMP-2077 / JAN-869]: FIB Issues

assets/src/components/parts/janus-input-text/InputText.tsx, assets/src/components/parts/janus-input-text/InputTextAuthor.tsx, assets/src/components/parts/janus-multi-line-text/MultiLineTextInput.tsx, assets/src/components/parts/janus-multi-line-text/MultiLineTextInputAuthor.tsx
Fixes an issue where the fontSize set during authoring was not being reflected in the course (or even while authoring).
=> Fixed fontSize in text inputs

assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx
Fixed an issue in firefox where user is unable to select component by
=> Fix for selecting component in Firefox browser

assets/src/components/parts/janus-video/Video.tsx, assets/src/components/parts/janus-video/schema.ts
Video component bugfixes (`startTime`, `endTime`, `autoPlay`, and `exposurePercentage`).
=> [BUGFIX] [PMP-2066 / JAN-858]: Video component 

assets/src/apps/authoring/Authoring.tsx, assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx, assets/src/apps/authoring/components/HeaderNav.tsx, assets/src/apps/authoring/components/Modal/DiagnosticsWindow.tsx, assets/src/apps/authoring/components/RightMenu/RightMenu.tsx, assets/src/apps/authoring/store/activities/actions/saveActivity.ts, assets/src/apps/authoring/store/app/slice.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityPartInheritance.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts, assets/src/apps/authoring/store/parts/actions/addPart.ts, assets/src/apps/authoring/store/parts/actions/updatePart.ts, assets/src/apps/delivery/store/features/groups/actions/sequence.ts
this adds a "Lesson Diagnostics" window which right now just does a part ID validation for duplicates and problematic ids with an option to fix them from the window
=> [Feature] Advanced Author Lesson Diagnostics

assets/src/apps/authoring/components/Accordion/ContextAwareToggle.tsx, assets/src/apps/authoring/components/Modal/DiagnosticsWindow.tsx, assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx
expand the sidebar with screen selection
clear part selection before changing id
=> [Feature] Enhance AA Diagnostics

lib/oli/groups.ex, lib/oli/groups/community.ex, lib/oli/groups/community_institution.ex, lib/oli/institutions.ex, lib/oli/institutions/institution.ex, lib/oli_web/live/community_live/form.ex, lib/oli_web/live/community_live/invitation.ex, lib/oli_web/live/community_live/show_view.ex, priv/repo/migrations/20211202142939_create_communities_institutions.exs, test/oli/groups_test.exs, test/oli/institutions_test.exs, test/oli_web/live/community_live_test.exs, test/support/factory.ex
[MER-500](https://eliterate.atlassian.net/browse/MER-500)
This feature allows system and community admins to add and remove institutions to a community.
[MER-500]: https://eliterate.atlassian.net/browse/MER-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MER-500 Add institution to community

lib/oli/authoring/course.ex, lib/oli/delivery/sections/blueprint.ex, lib/oli_web/live/common/sortable_table/table_handlers.ex, lib/oli_web/live/community_live/associated/index_view.ex, lib/oli_web/live/community_live/associated/new_view.ex, lib/oli_web/live/community_live/members_index_view.ex
Fix some issues found when testing https://eliterate.atlassian.net/browse/MER-336
=> [BUGFIXES] [MER-336]

assets/src/apps/authoring/Authoring.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptiveItemOptions.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts
condition types now will first choose from adaptivity schema before anything else
corrected bug in init that was calling initializeFromContext multiple times
=> [BUGFIX] PMP-2273 JAN-1086 condition operators wrong

assets/src/apps/authoring/components/AdaptivityEditor/ActionNavigationEditor.tsx
Fixed next screen being marked as invalid
=> Fixed next screen being marked as invalid

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/store/features/page/actions/loadInitialPageState.ts
This reverts commit 91ad8da6fac96473e88f61f526dcbf5da8a1f583.
=> Revert "[Bugfix] everapp state (#2031)"

CHANGELOG.md, lib/oli_web/live/progress/student_view.ex
Fixes an issue that AppSignal was reporting:
```
** (KeyError) key :local_tz not found in: %{__changed__: %{__context__: true, __surface__: true, breadcrumbs: true, page_nodes: true, resource_accesses: true, section: true, table_model: true, text_search: true, title: true, user: true}, __context__: %{}, __surface__: %{}, breadcrumbs: [%OliWeb.Common.Breadcrumb{action_descriptions: [], full_title: "Section Overview", link: "/sections/anita_test_course_bb_setup_fhdis", phx_click: nil, phx_value: nil, short_title: "Section Overview", slug: nil}, %OliWeb.Common.Breadcrumb{action_descriptions: [], full_title: "Student Progress", link: nil, phx_click: nil, phx_value: nil, short_title: "Student Progress", slug: nil}], flash: %{}, live_action: nil, page_nodes: …
```
=> [BUG FIX] Fix missing assign error

config/config.exs, config/releases.exs, lib/oli_web/templates/layout/_delivery_footer.html.eex, lib/oli_web/templates/layout/_footer.html.eex, oli.example.env
https://eliterate.atlassian.net/browse/MER-656
Make footer configurable and dynamic by env variables.
Ensure the following environment variables are added to each Torus instance with the corresponding values:
- `FOOTER_TEXT`
- `FOOTER_LINK_1_LOCATION`
- `FOOTER_LINK_1_TEXT`
- `FOOTER_LINK_2_LOCATION`
- `FOOTER_LINK_2_TEXT`
=> [FEATURE] [MER-656] Add custom footer text and links

lib/oli/email.ex
[MER-612] Simplifying address format for Bamboo SES Adapter.
[MER-612]: https://eliterate.atlassian.net/browse/MER-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Help form fixes

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts
I already have a PR (https://github.com/Simon-Initiative/oli-torus/pull/2025) that will fix this automatically (i.e. related to slowness issue - we have removed the handleParentChildActivityVariableSync() function). However, we are waiting on Ben to come back and approve the PR so in the mean time, I think we can merge this PR for now.
=> PMP-2416 | JAN-1237

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/apps/delivery/store/features/groups/actions/deck.ts, assets/src/components/parts/janus-Carousel/delivery-entry.ts, assets/src/components/parts/janus-audio/delivery-entry.ts, assets/src/components/parts/janus-capi-iframe/delivery-entry.ts, assets/src/components/parts/janus-dropdown/delivery-entry.ts, assets/src/components/parts/janus-fill-blanks/delivery-entry.ts, assets/src/components/parts/janus-input-number/delivery-entry.ts, assets/src/components/parts/janus-input-text/delivery-entry.ts, assets/src/components/parts/janus-mcq/delivery-entry.ts, assets/src/components/parts/janus-multi-line-text/delivery-entry.ts, assets/src/components/parts/janus-navigation-button/delivery-entry.ts, assets/src/components/parts/janus-popup/delivery-entry.ts, assets/src/components/parts/janus-slider/delivery-entry.ts, assets/src/components/parts/janus-video/delivery-entry.ts
this removes the old way to sync variables by duplicating the values in favor of leveraging the binding system
=> PMP-2416 JAN-1237 sync approach using bindings

assets/package.json, assets/src/components/parts/janus-popup/Popup.tsx, assets/yarn.lock
isOpen was triggering loop changes
=> [BUGFIX] PMP-2258 JAN-1072 sim stuck

assets/package.json, assets/src/adaptivity/scripting.ts, assets/src/apps/delivery/components/TextParser.ts, assets/src/apps/delivery/store/features/groups/actions/deck.ts, assets/yarn.lock
update scripting; change sync vars to anchors; error in parseText
=> [BUGFIX] PMP-2422 JAN-1243 sync vars messing up config init

lib/oli/accounts.ex
This PR fixes a column sorting issue with linked author account. I made a pass through and checked other tables, including the ones in the linked issue which seem to behave as expected.
Closes #1697
=> [BUG FIX] fix sort by linked author in user accounts

lib/oli/accounts.ex, lib/oli_web/live/common/paging.ex, lib/oli_web/live/common/sortable_table/table_handlers.ex, lib/oli_web/live/common/table/sortable_table_model.ex, lib/oli_web/live/community_live/index_view.ex, lib/oli_web/live/users/author_detail_view.ex, lib/oli_web/live/users/authors_view.ex, lib/oli_web/live/users/user_detail_view.ex, lib/oli_web/live/users/users_view.ex, test/oli/locks_test.exs, test/oli_web/live/admin_live_test.exs, test/oli_web/live/community_live_test.exs, test/support/factory.ex
https://eliterate.atlassian.net/browse/MER-687
The goal of this PR is to continue increasing the unit test coverage of the app (which increased by about 3% for now)
With that, the following minor changes were made:
- Do not use `Oli.Repo` in views, use the corresponding context instead
- Handle some failing scenarios
=> Add some tests on the admin dashboard

lib/oli_web/views/page_delivery_view.ex
The previous work that optimizes the rendering of Adaptive pages broke the ability for the load testing tool to visit these pages.  The reason being was that the shape of the `@latest_attempts` assign in the `page.html.eex` template changed.  For adaptive pages that is now a map of activity ids to maps containing minimal attempt information (as opposed to basic pages where this assign is a map of activity ids to two element tuples of activity attempts and part attempt maps).
The fix here leaves the `__ACTIVITY_ATTEMPTS__` load testing variable set as an empty list for adaptive pages. This is acceptable because the load testing tool cannot do anything with those attempts anyways.  It only exercises a small set of Torus activity types (see `lib/oli/utils/load_testing.ex` for those details)
=> [BUG FIX] Restore load testing of adaptive pages

lib/oli_web/live/products/details_view.ex
This PR fixes an issue where any instructor with a linked authoring account can access and edit *ANY* product, regardless of whether they are the original author of that product. 
The fix here is to incorporate the use of the reusable `Mount.for` which encapsulates this logic and provides error handling for routing to a `Access Denied` page.
=> [BUG FIX] Secure access to product editing MER-686

assets/src/apps/authoring/components/AdaptivityEditor/VariablePicker.tsx, assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts
This change fixes validation to cover a broader range of possible targets, including lesson variables and everapps.
=> PMP-2357: Fixed validation for more targets

lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex
This PR further optimizes the two bulk attempt insertion queries by taking advantage of index parameter support in Postgres, and Ecto "placeholder" support.  The idea here is that for columns that have all the same value we can specify that value one time in the query.
Here is the first part of an activity bulk insertion SQL (prior to this change):
```
INSERT INTO "activity_attempts" ("attempt_guid","attempt_number","inserted_at","resource_attempt_id","resource_id","revision_id","scoreable","transformed_model","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9),($10,$11,$12,$13,$14,$15,$16,$17,$18) 
...
```
And here is the same portion of the query with this optimization in place:
```
INSERT INTO "activity_attempts" ("attempt_guid","attempt_number","inserted_at","resource_attempt_id","resour …
```
=> [BUG FIX] Use placeholders during bulk insertion

assets/src/apps/authoring/components/AdaptivityEditor/ConditionsBlockEditor.tsx
This change fixes an issue where the radio buttons were not being updated when the rule type changed.
=> Fixed issue with rule condition type toggling between rules

assets/src/apps/authoring/components/ComponentToolbar/ComponentSearchContextMenu.tsx, assets/styles/authoring/controls.scss
This addition allows component parts to be reordered in the find component drop down menu.
=> PMP-2395: Allow components to be reordered

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts
screen visits were not getting persisted to the extrinsic state until the second time
=> [Bugfix] POTM issues

assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts
Adds a check for a screen id in front of the component id to better determine if component exists.
=> PMP-2357: Fixed validation for screen/component name combination

assets/src/adaptivity/rules-engine.ts, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts, assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
authoring pre determine required variables for evaluation so that the payload sent to nodejs can be significantly smaller
=> [PERF] reduce payload sent to node

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts
should increase visits on fresh visit AFTER first check
=> [BUGFIX] PMP-2446 JAN-1275

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
This has served its purpose and just needs to be removed.
=> [BUG FIX] Remove debug file dumping

assets/src/apps/authoring/store/activities/actions/createNew.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityPartInheritance.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts, assets/src/apps/authoring/store/parts/actions/addPart.ts, assets/src/apps/authoring/store/parts/actions/updatePart.ts
do not record text & images as parts needing responses; should cut down on the number of part attempts significantly
=> [PERF] remove text & images from the parts list

assets/src/apps/delivery/components/ActivityRenderer.tsx, assets/src/apps/delivery/layouts/deck/components/EverappContainer.tsx
corrected issue with get data
min width not set for apps
=> [BUGFIX] PMP-2452 JAN-1282, PMP-2394 JAN-1213

lib/oli/delivery/gating/gating_condition_data.ex, lib/oli/delivery/sections/section.ex, lib/oli/utils.ex, lib/oli_web/live/common/delete_modal_no_confirmation.ex, lib/oli_web/live/sections/gating_and_scheduling/form.ex, lib/oli_web/live/sections/gating_and_scheduling/gating_condition_store.ex, test/oli_web/live/sections/gating_and_scheduling_test.exs, test/support/factory.ex
https://eliterate.atlassian.net/browse/MER-622
https://eliterate.atlassian.net/browse/MER-554
=> [BUGFIXES] [MER-622] [MER-554] Gating conditions improvements

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/layouts/deck/components/FeedbackContainer.tsx
Fixes misaligned feedback window in certain legacy lessons. Tested with multiple lessons, both legacy and non-legacy.
=> [BUGFIX] [PMP-2206 / JAN-1022]: Feedback Alignment

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
make sure iframe always has the latest reference
=> [BUGFIX] PMP-2466 PMP-603 JAN-1298 JAN-529

.tool-versions, lib/oli/interop/ingest.ex, test/oli/interop/ingest_test.exs
This PR adds ingest idref validation and also upgrades local node version to fix missing binary error when running yarn.
=> [FEATURE] add ingest idref validation

assets/src/apps/authoring/components/PropertyEditor/custom/VariableEditor.tsx, assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts
This addition adds a more intuitive editor for modifying/creating variables defined at the lesson level and enforces the structure of those variables better than a JSON input field.
=> PMP-1926: Added editor for lesson variables

assets/src/apps/authoring/store/parts/actions/updatePart.ts
by omitting text and images encountered a null ref
=> [BUGFIX] PMP-2483 JAN-1323

lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/delivery.html.eex
This PR fixes an issue where Mix is not available in a production environment and therefore crashes.
=> [BUG FIX] fix an issue where Mix.env is not available in production

lib/oli/interop/ingest.ex, lib/oli/resources/page_content.ex, lib/oli_web/live/admin/admin_view.ex
This PR fixes some issues with project ingest including:
1. Fix an issue with idref and children access
2. Make ingest more robust against invalid activity refs
=> [BUG FIX] fix an issue with idref and children access

assets/src/adaptivity/rules-engine.ts, assets/src/apps/authoring/store/activities/actions/saveActivity.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityPartInheritance.ts, assets/src/components/parts/janus-dropdown/Dropdown.tsx, lib/oli/groups.ex, lib/oli_web/controllers/cognito_controller.ex, lib/oli_web/router.ex, test/oli/groups_test.exs, test/oli_web/controllers/cognito_controller_test.exs, test/support/factory.ex
Competes initial Infiniscope Cognito requirements.
Next features for this start almost immediately where a suggested enhancement will be to move most of the JWK auth into a plug or shared module to streamline this controller.
=> MER-700 Infiniscope Cognito

config/config.exs, config/releases.exs, lib/oli_web/templates/pow/registration/user_new.html.eex, oli.example.env
https://eliterate.atlassian.net/browse/MER-791
=> [FEATURE] [MER-791] Add age verification checkbox configurable by env var

assets/src/components/activities/oli_embedded/OliEmbeddedDelivery.tsx
This PR fixes a bug where changes in iframe content size continue to grow after user interaction. The fix ensures a reset of the html element on each iframe resize call
=> [BUG] Oli embedded fix

lib/oli/accounts/schemas/user.ex, lib/oli/utils.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/live/users/user_detail_view.ex, lib/oli_web/pow/user_context.ex, lib/oli_web/templates/pow/registration/user_edit.html.eex, lib/oli_web/templates/pow/registration/user_new.html.eex, priv/repo/migrations/20220214143811_update_users_tables_age_verified.exs, test/config/age_verification_config.exs, test/config/config.exs, test/oli/accounts_test.exs, test/oli_web/live/admin_live_test.exs, test/oli_web/pow/pow_test.exs, test/support/factory.ex
https://eliterate.atlassian.net/browse/MER-813
Make age verification field persistent on the user.
Add the following env var: `IS_AGE_VERIFICATION_ENABLED=true`
=> [BUGFIX] [MER-813] Persistent age check

lib/oli_web/controllers/cognito_controller.ex, lib/oli_web/controllers/open_and_free_controller.ex, lib/oli_web/router.ex, test/oli_web/controllers/cognito_controller_test.exs, test/oli_web/controllers/open_and_free_controller_test.exs
Adds project support to open and free controller and thus Cognito integration.
=> MER-826 Add ability to use projects with Cognito integration.

assets/src/apps/authoring/components/AdaptivityEditor/InitStateEditor.tsx
allow blank spaces in init fields
=> [BUGFIX] PMP-2522 button showing up in images

lib/oli_web/templates/layout/_header.html.eex, lib/oli_web/templates/pow/registration/user_new.html.eex, lib/oli_web/templates/pow/session/user_new.html.eex, test/oli_web/controllers/static_page_controller_test.exs, test/oli_web/pow/pow_test.exs
[MER-805](https://eliterate.atlassian.net/browse/MER-805) and [MER-806](https://eliterate.atlassian.net/browse/MER-806)
=> [FEATURE] [MER-805] [MER-806] Some text updates for user sign in

assets/static/images/icons/google-icon.svg, assets/styles/common/box-form-container.scss, assets/styles/themes/authoring/torus/dark.scss, assets/styles/themes/authoring/torus/light.scss, assets/styles/themes/delivery/torus/dark.scss, assets/styles/themes/delivery/torus/light.scss, lib/oli_web/pow/pow_helpers.ex, test/oli_web/pow/pow_test.exs
[MER-802](https://eliterate.atlassian.net/browse/MER-802)
Update auth providers styling in order to comply with [Google requirements](https://developers.google.com/identity/branding-guidelines#top_of_page).
=> [MER-802] Update Google SSO button to comply with Google requirements

lib/oli_web/templates/open_and_free/form.html.eex, test/oli_web/controllers/open_and_free_controller_test.exs
https://eliterate.atlassian.net/browse/MER-810
=> [BUGFIX] [MER-810] Make section form field names consistent

assets/src/apps/authoring/store/activities/actions/saveActivity.ts, assets/src/apps/authoring/store/history/actions/undo.ts, assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx
Fixes the undo action for creating new parts/components
=> Bugfix: Fixed undo for creating parts

lib/oli/delivery/sections.ex, lib/oli_web/live/sections/edit_view.ex, lib/oli_web/live/sections/main_details.ex, lib/oli_web/live/sections/overview_view.ex, test/oli_web/live/admin_live_test.exs, test/oli_web/live/sections/edit_live_test.exs, test/oli_web/live/sections/gating_and_scheduling_test.exs, test/oli_web/live/sections/overview_live_test.exs, test/support/factory.ex
[MER-809](https://eliterate.atlassian.net/browse/MER-809)
Taking the opportunity to add some missing test files for section overview and edit views.
=> [BUGFIX] [MER-809] Section edit wrong default branding

.github/workflows/deploy.yml, .github/workflows/package.yml
This PR adds some deployment info output to CI for Argos Jira integration
=> [CHORE] CI deployment info

assets/styles/authoring/advanced-authoring.scss
Added style to allow scrolling of component search popover
=> Fixed css for popover scrolling

assets/package.json, assets/yarn.lock
update janus-script version to take fix for decimals
=> [BUGFIX] PMP-2587 JAN-1424 error in CC trap states

lib/oli/delivery/sections/section.ex, lib/oli_web/live/delivery/select_source.ex, lib/oli_web/live/sections/open_free_settings.ex, lib/oli_web/live/sections/overview_view.ex, test/oli_web/live/sections/edit_live_test.exs, test/oli_web/live/sections/overview_live_test.exs
[MER-807](https://eliterate.atlassian.net/browse/MER-807)
Replace every part of the code where it says "LMS-Lite" with "Direct Delivery".
=> [MER-807] Rename LMS-Lite to Direct Delivery

lib/oli/delivery/attempts/core/resource_access.ex, test/oli_web/live/progress_live_test.exs
[MER-844](https://eliterate.atlassian.net/browse/MER-844)
[AppSignal issue](https://appsignal.com/argos-education/sites/619e9fbb7ccda672352971d3/exceptions/incidents/110/samples/619e9fbb7ccda672352971d3-477208838546314286516466682601?incident_tab=host)
=> [BUGFIX] [MER-844] Fix Internal Server Error when clicking an unscored lesson

lib/oli/accounts/schemas/user.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/section.ex, lib/oli/grading.ex, lib/oli_web/live/common/delete_modal_no_confirmation.ex, lib/oli_web/live/sections/gating_and_scheduling/gating_condition_store.ex, lib/oli_web/live/sections/overview_view.ex, priv/repo/migrations/20220216163315_add_on_delete_to_section_associations.exs, test/oli/sections_test.exs, test/oli_web/live/sections/overview_live_test.exs, test/support/factory.ex
[MER-743](https://eliterate.atlassian.net/browse/MER-743)
Add button in the Sections Overview page to delete (if there's no student associated data) a section or archive it.
=> [MER-743] Add ability to delete a section

lib/oli_web/templates/email/_footer.html.eex, lib/oli_web/templates/layout/email.html.eex
[MER-787](https://eliterate.atlassian.net/browse/MER-787)
Remove `VENDOR_PROPERTY_COMPANY_ADDRESS` or  change `VENDOR_PROPERTY_COMPANY_ADDRESS=""`
=> [MER-787] Display learn more link if no address in account confirmation email

lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/chromeless.html.eex, lib/oli_web/templates/layout/delivery.html.eex, lib/oli_web/templates/layout/lti.html.eex, test/oli_web/live/progress_live_test.exs
https://eliterate.atlassian.net/browse/MER-868
https://eliterate.atlassian.net/browse/MER-869
https://eliterate.atlassian.net/browse/MER-870
Played a bit with parts of the app where jquery is used and everything seems good.
=> [BUGFIX] [MER-868, MER-869, MER-870] Upgrade jquery slim cdns to 3.5.0

priv/schemas/v0-1-0/activity.schema.json, priv/schemas/v0-1-0/content-group.schema.json
Fixes an issue where the activity schema is overconstrained by removing the tags requirement
=> [BUG FIX] remove activity schema tags requirement

lib/oli_web/live/community_live/members_index_view.ex, test/oli_web/live/community_live_test.exs
Some users won't have a name, account for that in this admin UI.
=> MER-862 Account for users with no name in community members admin page.

lib/oli_web/templates/layout/chromeless.html.eex
upgrade libs on chromeless page to resolve errors
=> [BUGFIX] jquery version 3.5.0 is not fully compatible with bootstrap 4.1.3

lib/oli/activities.ex, lib/oli_web/templates/resource/advanced.html.eex
only load the adaptive activity for advanced authoring
=> [PERF] optimize activity loading for advanced author

assets/src/adaptivity/rules-engine.ts
don't allow errors through to values
=> [BUGFIX] AOPS-544 error with contains trap states with arrays

assets/src/components/parts/janus-fill-blanks/FillBlanks.tsx, assets/src/components/parts/janus-fill-blanks/delivery-entry.ts
FIB component (native) was going into a infinite loop when init state was applied.
also switched to external JSON parsing and cleaned up some effects and hooks a bit to improve perf and make sure it was getting all the correct data.
=> [BUGFIX] PMP-2620 JAN-1473 FIB loop

assets/src/adaptivity/operators/contains.ts, assets/src/utils/common.ts, assets/test/adaptivity/rules_engine_test.ts
cleaned up and split out the logic in contains so that it is easier to reason about
added some more tests for it to hopefully put an end to the issues :)
=> [BUGFIX] PMP-2610 JAN-1463 rules engine contains operator failing under certain circumstances

lib/oli_web/live/ingest/faq.ex, lib/oli_web/live/ingest/ingest.ex, lib/oli_web/live/ingest/ingest.sface, priv/schemas/v0-1-0/activity-reference.schema.json, priv/schemas/v0-1-0/content-block.schema.json, priv/schemas/v0-1-0/content-element.schema.json, priv/schemas/v0-1-0/purpose-type.schema.json
This PR includes the following changes to support course migration effort:
- Update schemas to support activity links
- Add processing phx-disable-with to ingest button
- Move faq to separate component
=> [BUG FIX] update schemas to support activity links

lib/oli/accounts.ex, lib/oli/groups.ex, lib/oli/groups/community_account.ex, lib/oli_web/controllers/cognito_controller.ex, lib/oli_web/plugs/validate_id_token.ex, lib/oli_web/router.ex, lib/oli_web/views/view_helpers.ex, test/oli/accounts_test.exs, test/oli_web/controllers/cognito_controller_test.exs
[MER-941](https://eliterate.atlassian.net/browse/MER-941)
- Move the cognito id token validation logic to a plug.
- Some refactoring
=> [MER-941] Refactor Cognito integration

lib/oli_web/templates/cognito/index.html.eex
https://eliterate.atlassian.net/browse/MER-978
=> [MER-978] Text updates on prompt page for customize flow

assets/src/adaptivity/operators/contains.ts, assets/test/adaptivity/rules_engine_test.ts
not contains any of bugs;
Not Contains Any Of is not the Opposite of Contains Any Of
=> [BUGFIX] PMP-2610 JAN-1463 contains rules issues

lib/oli/delivery/sections/section.ex, lib/oli_web/live/sections/open_free_settings.ex, lib/oli_web/pow/user_context.ex, lib/oli_web/pow/user_routes.ex, lib/oli_web/templates/open_and_free/form.html.eex, priv/repo/migrations/20220328163119_update_sections_table_confirm_students_on_creation.exs, priv/repo/migrations/20220331182821_update_sections_table_skip_email_verification.exs, test/oli_web/pow/pow_test.exs
https://eliterate.atlassian.net/browse/MER-753
=> [FEATURE] [MER-753] Student omit email verification

priv/schemas/v0-1-0/content-element.schema.json
relax image content to be able to use numbers for size
=> [BUGFIX] Schema is too strict 

assets/styles/themes/authoring/default.scss
This PR fixes a style issue where pagination has a green background in dark mode
=> [BUG FIX] fix green pagination buttons in dark mode

assets/src/apps/delivery/components/PreviewTools.tsx, assets/styles/preview/preview-tools.scss, assets/webpack.config.js
remove old dark mode way from preview tools; fix delivery theme;
=> [BUGFIX] Adaptive CSS Issues

lib/oli/accounts.ex, lib/oli_web/pow/messages.ex, lib/oli_web/pow/pow_helpers.ex, test/oli/accounts_test.exs, test/oli_web/pow/pow_test.exs, test/support/factory.ex
[MER-741](https://eliterate.atlassian.net/browse/MER-741)
=> [MER-741] Notify LTI user to login from LMS when logging directly into Torus

assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts, assets/src/apps/delivery/store/features/activities/slice.ts, assets/test/advanced_authoring/diagnostics/diagnostics_mocks.ts, assets/test/advanced_authoring/diagnostics/diagnostics_test.ts
at least bad ids and duplicate ids were broken;
also updating typings and cleaning up logic and adding unit tests
=> [BUGFIX] Adaptive Authoring diagnostics crashing under certain scenarios

lib/oli_web/live/manual_grading/manual_grading_view.ex, lib/oli_web/live/progress/student_resource_view.ex, lib/oli_web/live/progress/student_view.ex, test/oli_web/live/progress_live_test.exs
https://eliterate.atlassian.net/browse/MER-976
https://eliterate.atlassian.net/browse/MER-966
=> [BUGFIX] [MER-976] Add some section management missing breadcrumbs

assets/src/apps/delivery/layouts/deck/DeckLayoutHeader.tsx
return to overview in a section
back to authoring in preview mode
=> [FEATURE] MER-793 add a back button

assets/src/apps/authoring/components/AdaptiveRulesList/AdaptiveRulesList.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx
This changes fixes an issue with two separate calls made to saveActivity causing a race condition where one would overwrite the other. The fix merges the code for the two calls into one.
=> BUGFIX: Mutate state race condition

assets/src/apps/delivery/layouts/deck/DeckLayoutHeader.tsx
Adjusts the style of the back button to be larger by default.
=> [FEATURE] MER-793: Back button style adjustment

lib/oli_web/templates/layout/_author_account_dropdown.html.eex
https://eliterate.atlassian.net/browse/MER-1057
Added wrong route on the author dropdown in https://github.com/Simon-Initiative/oli-torus/pull/2424, my bad 🙏🏼
=> [BUGFIX] [MER-1057] Fix author signout route on dropdwon

assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx
Fixed issue with nested arrays of variables to check
=> Bugfix: Disconnected variables

assets/src/apps/authoring/components/Modal/DiagnosticsWindow.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/VariableEditor.tsx, assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts
Variable Editor -->
Diagnostics Tool -->
=> Diagnostics Tool | Variables Parsing Check

CHANGELOG.md, assets/src/components/activities/ordering/OrderingDelivery.tsx, assets/src/components/activities/ordering/sections/ResponseChoices.tsx, assets/src/components/common/DraggableColumn.modules.scss, assets/src/components/common/DraggableColumn.tsx
=> [BUG FIX] Fix ordering activity reorder after submission, background style, grab handle style

lib/oli_web/live/common/hierarchy/hierarchy_picker.ex, lib/oli_web/live/delivery/remix_section.ex, lib/oli_web/live/delivery/remix_section.html.heex, test/oli_web/live/remix_section_test.exs
https://eliterate.atlassian.net/browse/MER-947
=> [MER-947] Order curriculum items equal to add materials

lib/oli/authoring/clone.ex, lib/oli/authoring/course.ex, lib/oli/authoring/course/project.ex, lib/oli/delivery/sections/blueprint.ex, lib/oli/delivery/sections/section.ex, lib/oli/inventories.ex, lib/oli/inventories/publisher.ex, lib/oli/utils.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/live/products/details/edit.ex, lib/oli_web/live/products/details_view.ex, lib/oli_web/live/products/products_view.ex, lib/oli_web/live/publisher_live/form.ex, lib/oli_web/live/publisher_live/show_view.ex, lib/oli_web/templates/project/overview.html.eex, priv/repo/migrations/20220418150726_add_publisher_to_projects_and_products.exs, test/oli/clone_test.exs, test/oli/course_test.exs, test/oli/delivery/paywall/providers/stripe_test.exs, test/oli/delivery/paywall_test.exs, test/oli/delivery/sections/blueprint_test.exs, test/oli/inventories/publisher_test.exs, test/oli/inventories_test.exs, test/oli_web/controllers/project_controller_test.exs, test/oli_web/live/publisher_live_test.exs, test/support/factory.ex
[MER-923](https://eliterate.atlassian.net/browse/MER-923)
[MER-1033](https://eliterate.atlassian.net/browse/MER-1033)
This PR makes the following changes:
- Add publisher association to projects and products.
- Make publisher required for projects and products.
- Define a default publisher
- Add default publisher to all existing projects and products
- Add email validation to publishers
**DON'T MERGE THIS PR UNTIL IT HAS AT LEAST TO APPROVALS**
=> [MER-923] Add publisher to products and projects

CHANGELOG.md, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts, lib/oli_web/live/insights/insights.ex, lib/oli_web/live/insights/table_header.ex
=> [BUG FIX] Insights - add tooltips, keyboard nav

assets/src/adaptivity/scripting.ts, assets/src/utils/common.ts
The issues was occurring because of the changes made in [PR](https://github.com/Simon-Initiative/oli-torus/pull/2465/files) . Added a separate function to format the numbers with different scenarios
=> PMP-2788 | JAN-1636

assets/src/adaptivity/scripting.ts, assets/src/components/parts/janus-popup/Popup.tsx, assets/src/components/parts/janus-popup/PopupWindow.tsx
We send the environment object as part of  props.onInit result to all the parts but this was not sent when we render the pop-ups. So added the code to send the environment object.
=> PMP-2755 | JAN-1603

lib/oli/utils/db_seeder.ex, test/hound/login_test.exs
This PR fixes an issue where db seeder doesn't have access to test factories which is breaking the package step in the build.
=> [BUG FIX] fix an issue where db seeder doesnt have access to test factories

lib/oli/inventories/publisher.ex, lib/oli_web/controllers/api/product_controller.ex, lib/oli_web/controllers/api/publisher_controller.ex, lib/oli_web/plugs/validate_product_api_key.ex, lib/oli_web/router.ex, lib/oli_web/views/api/product_view.ex, lib/oli_web/views/api/publisher_view.ex, test/oli_web/controllers/api/product_controller_test.exs, test/oli_web/controllers/api/publisher_controller_test.exs
[MER-1081](https://eliterate.atlassian.net/browse/MER-1081) & [MER-1082](https://eliterate.atlassian.net/browse/MER-1082)
Add new publisher show and index endpoints to V1 API and update current products endpoint to include `publisher_id`.
=> [MER-1081] [MER-1082] Add publisher endpoints and update products v1 api endpoint

assets/styles/authoring/admin.scss, lib/oli/delivery/sections/browse.ex, lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/sections/sections_view.ex, lib/oli_web/live/sections/table_model.ex, test/oli_web/live/admin_live_test.exs, test/oli_web/live/community_live_test.exs, test/oli_web/live/sections/admin_index_live_test.exs
[MER-1099](https://eliterate.atlassian.net/browse/MER-1099)
Improvements:
- Some styling and labels for the table
- How the instructors are being rendered
- Search functionality to cover more cases
=> [BUGFIX] [MER-1099] Admin sections improvements

assets/styles/authoring/model-editors.scss
This PR fixes an issue where table options dropdown is hidden within the table element.
Closes #2345
=> [BUG FIX] fix table dropdown visibility

test/oli_web/live/admin_live_test.exs, test/oli_web/live/community_live_test.exs, test/support/factory.ex
[MER-1121](https://eliterate.atlassian.net/browse/MER-1121)
What does it change?
- Fixes flaky community and admin unit tests due to sorting
=> [MER-1121] Fix flaky community live tests

assets/src/adaptivity/rules-engine.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts
in case the value of a condition or action is an actual array, then check each part of the array for activity references
=> [BUGFIX] notEqualWithTolerance not evaluating values from other screens (Intro 8 Astrobiology) AOPS-673

lib/oli_web/live/grades/updates_table_model.ex, test/oli_web/live/browse_updates_live_test.exs, test/support/factory.ex
[MER-1172](https://eliterate.atlassian.net/browse/MER-1172)
Update LMS grade updates page to order by most recent by default.
Add new test file for this page.
=> [MER-1172] Fix ordering in LMS grade updates page

assets/src/apps/delivery/layouts/deck/components/HistoryNavigation.tsx, assets/src/apps/delivery/layouts/deck/components/HistoryPanel.tsx
history was not ordered properly; also was able to click "next" outside of history mode; (because order was wrong, but I've blocked it completely now)
=> [BUGFIX] adaptive history mode wrong

assets/src/apps/delivery/store/features/attempt/actions/savePart.ts
was overwriting part responses instead of merging
=> [BUGFIX] AOPS-685 R* 2 unable to complete

assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts
still the author would kill the operator if the type was wrong, which is the wrong priority for murder
=> [BUGFIX] adaptive author was killing condition operators under certain conditions

lib/oli/predefined.ex, test/oli_web/controllers/institution_controller_test.exs
Adds D2L (desire2learn) as a LTI configuration option. Will be deployed with several other PR's around supporting D2L.
=> MER-1237 Add D2L as a registration option.

lib/oli_web/plugs/authorize_section.ex, test/oli_web/live/admin_live_test.exs, test/oli_web/live/community_live_test.exs, test/oli_web/live/publisher_live_test.exs
[MER-1231](https://eliterate.atlassian.net/browse/MER-1231)
=> [MER-1231] Relax current user and author in authorize section plug

lib/oli_web/plugs/authorize_section.ex
Another minor fix for MER-1231.
When tested prior fix yesterday, didn't reach out this code because I think I was logged in as author at the same time 😭, 100% my bad sorry 🙏🏼
=> [MER-1231] Fix key type for conn params in authorize section

assets/src/apps/delivery/components/ActivityRenderer.tsx, assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx
This reverts commit b0656a955a676f4cd4b6ed52541ef94b7925e1c0.
=> Revert "PMP-2864|JAN-1713 Fixed re-check after submission (#2687)"

assets/src/apps/authoring/components/AdaptivityEditor/ActionMutateEditor.tsx
Fixed issue where actions not update when toggled between adaptivity rules
=> PMP-2865|JAN-1714 Actions not update when toggled between rules

assets/src/apps/delivery/layouts/deck/components/EverappRenderer.tsx, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
JAN-1606 JAN-1688 JAN-1704 send handshake after same screen init
=> [Bugfix] sim issues multiple

assets/src/apps/authoring/store/activities/actions/saveActivity.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/validate.ts
also tossed in minor part cleanup
=> [BUGFIX] Adaptive author diagnostics not finding all duplicate ids

lib/oli/delivery/paywall.ex, lib/oli/delivery/paywall/discount.ex, lib/oli/utils.ex, lib/oli_web/live/products/payments/discounts/form.ex, test/oli/delivery/paywall_test.exs
[MER-1227](https://eliterate.atlassian.net/browse/MER-1227) and [MER-1236](https://eliterate.atlassian.net/browse/MER-1236)
- Fix percentage discount. Admin would enter a number between 0 and 100
- Rename label `Fixed amount` to `Fixed price`
=> [BUGFIX] [MER-1227] [MER-1236] Discount fixes

assets/src/components/resource/objectives/ObjectivesSelection.tsx
=> [BUG FIX] Change placeholder text for LO selection and attachment to be more general

lib/oli/institutions/institution.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/live/admin/institutions/research_consent_view.ex, lib/oli_web/router.ex, lib/oli_web/templates/institution/show.html.eex, priv/repo/migrations/20220627135700_add_reserach_consent_to_institutions.exs, test/oli/institutions_test.exs, test/oli_web/controllers/delivery_controller_test.exs, test/oli_web/live/institutions_live_test.exs, test/support/factory.ex
[MER-1271](https://eliterate.atlassian.net/browse/MER-1271)
- Add `research_consent` field to institutions and add view for admins to be able to edit it
- Apply logic based on field for show/not show the form
=> [FEATURE] [MER-1271] Add ability to disable research consent form

lib/oli_web/live/products/payments/discounts/table_model.ex, test/oli_web/live/discounts_live_test.exs
[MER-1236](https://eliterate.atlassian.net/browse/MER-1236)
=> [MER-1236] Rename fixed amount label where missing

assets/src/adaptivity/rules-engine.ts, assets/src/adaptivity/scripting.ts, assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts, assets/src/data/persistence/activity.ts, assets/test/adaptivity/scripting_test.ts
authoring wasn't able to bulkEdit anymore due to biblio change and immutable references;
referenced variables and activities needed for evaluation had flawed complex logic that failed in some cases
inRange and notInRange operators not properly evaluating the expected array
=> [BUGFIX] references were not updating correctly JAN-1702 PMP-2853

lib/oli_web/controllers/lti_controller.ex, lib/oli_web/controllers/session_controller.ex
It autoformatted line 289, there is no change there other than the line break.
=> [ENHANCEMENT] remove linked author autologin

assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx, assets/src/apps/authoring/components/EditingCanvas/StagePan.tsx, assets/styles/authoring/advanced-authoring.scss
This change gives an author the ability to click and drag the stage around.
=> PMP-2862|JAN-1711 Added ability to pan stage around

assets/src/apps/authoring/components/EditingCanvas/StagePan.tsx
only pan the editing area if the user clicks on the screen or the background JAN-1711
=> [BUGFIX] JAN-1711 resolves issues with dragging components and panning

CHANGELOG.md, mix.exs
Integrates changes from hotfix 0.20.1 into master branch
=> [CHORE] Integrate 0.20.1

lib/oli/delivery/paywall.ex, test/oli/delivery/paywall_test.exs
[MER-1322](https://eliterate.atlassian.net/browse/MER-1322)
- Fixes paywall cost calculation returning discount amount instead of total minus discount
=> [MER-1322] Fix paywall percentage discount calculation

assets/src/apps/delivery/store/features/adaptivity/slice.ts, assets/src/apps/delivery/store/features/groups/actions/deck.ts
sometimes context changed (check complete) would happen before all the parts were initialized.
=> [Bugfix] PMP-2978 JAN-1827 race conditon

assets/src/apps/delivery/components/ActivityRenderer.tsx
apply notify context useCallback to hotfix
=> [BUGFIX] JAN-1827 ensure context method has latest values

CHANGELOG.md, assets/src/components/content/RichTextEditor.tsx
Enables all content element types in question stem, choices and feedback.
Closes #2835
=> [BUG FIX] enable all content element types in question stem, choices and feedback

CHANGELOG.md, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex
Fixes an issue where underlined and strikethrough text were not being rendered at all.
Closes #2844
=> [BUG FIX] restores the rendering functionality for certain formatted text entities

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
when visiting an activity it always needs to init, especially in history mode or "new" attempts
=> [BUGFIX] init sync issues

config/dev.exs, lib/oli_web/controllers/legacy_logs_controller.ex, lib/oli_web/controllers/legacy_superactivity_controller.ex
This PR tweaks OLI superactivity webcontent URL to map a new proxy setup in the Torus fronting haproxy
=> [CHORE] proxy superactivity webcontent

assets/src/apps/delivery/components/PreviewTools.tsx
PMP-2955|JAN-1804 Fixed issue with history mode navigation not creating timestamps
=> PMP-2955|JAN-1804 Fixed issue with history mode navigation not creating timestamps

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
@bsparks I was able to semi-reliably reproduce the race-condition bug on my local machine. Did a bunch of debugging, and saw that here, inside handleActivityReady sometimes getLocalizedStateSnapshot ends up returning NaN for one or more of the stage.XXXX.value and that trickles through the system eventually causes the input field to be empty.
I went through this component and fixed all the dependencies in all the useCallback and useEffect calls.
After doing that, I haven't been able to reproduce the bug at all.
I'm unclear on specifically why this (maybe) fixes the bug, and hate fixes that can't be clearly explained as to what was wrong.
Ways I was able to reproduce the bug:
1. Every time I went through keeping balance lesson, there would be some missing "starting C02" values sprinkled …
=> Don't Merge - [Refactor] Clean up hooks in DeckLayoutView

assets/.eslintrc.json, assets/package.json, assets/src/apps/authoring/components/EditingCanvas/AuthoringActivityRenderer.tsx, assets/src/apps/delivery/store/features/groups/actions/sequence.ts, assets/src/components/common/TimeAgo.tsx, assets/src/components/editing/elements/utils.tsx, assets/yarn.lock
This adds the "plugin:react-hooks/recommended" eslint rules to our config and makes the minimal changes necessary so that a `yarn run lint` will succeed.
This is one of the default create-react-app eslint rulesets that facebook develops and recommends for react projects.
=> [CHORE] Add react-hooks/recommended to eslint config

.github/workflows/log-deployment.yml
This parameterized file allows a Jira webhook to integrate deployment info into Jira tickets and dashboards
=> log-deployment.yml to allow for Jira integration

.github/workflows/build.yml
Fixes github workflow prettier/lint step
=> [CHORE] fix prettier parser error

.github/workflows/build.yml, assets/src/components/activities/likert/Sections/LikertTable.tsx
This fixes a CI issue where the build may remain in "Waiting for status" forever because the lint commit was not being built.
=> [CHORE] Update CI auto format to separate step to fix waiting for status issue

.github/actions/torus-builder/Dockerfile, .github/actions/torus-builder/action.yml
Updates torus-builder image to use latest version
=> [INFRA] Fix torus builder

priv/schemas/v0-1-0/content-element.schema.json
An adjustment to the `list-item` schema definition to allow inline images to be included in a list item. Without this, my attempt to locally ingest chem1 fails, due to usage of inline images within a list item.
=> [BUG FIX] List item content

CHANGELOG.md, assets/src/components/editing/editor/modelEditorDispatch.tsx, assets/src/components/editing/elements/marks/toggleMarkActions.ts, assets/src/data/content/model/text.ts, assets/src/data/content/writers/html.tsx, assets/styles/common/elements.scss, lib/oli/rendering/content/html.ex
This PR adds authoring and delivery support for "term" inline markup.  Renders with the exact same style as legacy OLI.
=> [FEATURE] Add support for term

lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/plugs/authorize_section.ex, lib/oli_web/plugs/authorize_section_preview.ex, lib/oli_web/router.ex, test/oli/delivery/attempts_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs, test/support/test_helpers.ex
[MER-1355](https://eliterate.atlassian.net/browse/MER-1355)
Refactor instructor preview to make it work for all pages and add couple of tests to cover that functionality.
=> [FEATURE] [MER-1355] Instructor preview refactor

assets/src/components/common/Figure.tsx, assets/src/components/editing/editor/modelEditorDispatch.tsx, assets/src/components/editing/editor/normalizers/spaces.ts, assets/src/components/editing/editor/normalizers/tables.ts, assets/src/components/editing/elements/callout/calloutActions.ts, assets/src/components/editing/elements/definition/DefinitionInlineEditor.tsx, assets/src/components/editing/elements/definition/DefinitionToolbar.tsx, assets/src/components/editing/elements/definition/definitionActions.tsx, assets/src/components/editing/elements/figure/FigureEditor.tsx, assets/src/components/editing/elements/figure/figureActions.ts, assets/src/components/editing/elements/utils.tsx, assets/src/components/editing/slateUtils.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/blockInsertOptions.ts, assets/src/data/content/model/elements/factories.ts, assets/src/data/content/model/elements/types.ts, assets/src/data/content/model/schema.ts, assets/src/data/content/utils.tsx, assets/src/data/content/writers/html.tsx, assets/src/data/content/writers/writer.tsx, assets/styles/authoring/figure.scss, assets/styles/authoring/index.scss, assets/styles/common/elements.scss, assets/styles/delivery/variables.scss, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/content/plaintext.ex, priv/schemas/v0-1-0/content-element.schema.json
Adds a new `figure` element consisting of a title & a body of content enclosed within a box.
Demo:
https://user-images.githubusercontent.com/333265/186738061-076ed9af-4ed4-4769-bcd5-7a824370200c.mp4
=> [MER-1414] [GH#889] Add Figure element

assets/src/components/Dialog.tsx, assets/src/components/editing/editor/modelEditorDispatch.tsx, assets/src/components/editing/editor/normalizers/spaces.ts, assets/src/components/editing/elements/dialog/DialogEditor.tsx, assets/src/components/editing/elements/dialog/DialogInlineEditor.tsx, assets/src/components/editing/elements/dialog/DialogToolbar.tsx, assets/src/components/editing/elements/dialog/dialogActions.tsx, assets/src/components/editing/elements/video/videoActions.tsx, assets/src/components/editing/elements/youtube/YoutubeElement.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/blockInsertOptions.ts, assets/src/data/content/model/elements/factories.ts, assets/src/data/content/model/elements/types.ts, assets/src/data/content/model/schema.ts, assets/src/data/content/writers/html.tsx, assets/src/data/content/writers/writer.tsx, assets/styles/authoring/dialog.scss, assets/styles/authoring/index.scss, assets/styles/authoring/variables.scss, assets/styles/common/elements.scss, assets/styles/delivery/variables.scss, assets/styles/themes/authoring/default.scss, assets/styles/themes/delivery/default.scss, lib/oli/rendering/content.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/content/plaintext.ex, priv/schemas/v0-1-0/content-element.schema.json, test/oli/rendering/content/example_content.json, test/oli/rendering/content/html_test.exs, test/oli/rendering/content/plaintext_test.exs
Adds a new conversation/dialog element.
Demo:
https://user-images.githubusercontent.com/333265/187427499-55b3e58a-6158-4bdf-80d6-b2f8ce7997ab.mp4
=> [MER-1416] [GH#889] New dialog element

CHANGELOG.md, assets/src/data/activities/DeliveryState.ts
Re-base of #2966 to be included in hot fix 0.21.5.
Closes #2950
=> [BUG FIX] Survey reset hotfix

assets/src/adaptivity/scripting.ts, assets/src/apps/delivery/store/features/page/actions/loadInitialPageState.ts, assets/test/adaptivity/scripting_test.ts
* PMP-3023 | JAN-1866
patch to the hotfix
=> PMP-3023 | JAN-1866 (#2968)

CHANGELOG.md, assets/src/data/activities/DeliveryState.ts, lib/oli/delivery/evaluation/parser.ex, mix.exs, test/oli/delivery/evaluation/parser_test.exs
Integrate changes from 0.21.5 into master
=> [CHORE] Hotfix 0.21.5

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
* PMP-3006 | MER-1423 | JAN-1853
* delaying the handshake response
=> PMP-3006 | MER-1423 | JAN-1853 (#2980)

guides/design/misc.md, guides/lti/config.md, lib/oli/predefined.ex
[MER-1367](https://eliterate.atlassian.net/browse/MER-1367)
=> [MER-1367] Change auth server default for canvas

assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx, assets/src/components/activities/common/utils.tsx, assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/file_upload/FileUploadDelivery.tsx, assets/src/components/activities/likert/LikertDelivery.tsx, assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx, assets/src/components/activities/ordering/OrderingDelivery.tsx, assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx, assets/src/components/misc/AttemptSelector.tsx, assets/src/data/activities/utils.ts
Fixes an issue where the activity delivery component expects an authoring property to exist but it does not
=> [BUG FIX] fix an issue where the activity delivery component expects an authoring property

assets/src/components/activities/multi_input/sections/AnswerKeyTab.tsx, assets/src/components/activities/multiple_choice/utils.ts
This PR adjusts logic within the MC and MultiInput authoring components to handle cases of questions with no correct answers.
=> [ENHANCEMENT] Handle legacy questions with no correct choices

priv/repo/migrations/20220921174148_really_delete_trigger.exs
=> [PERFORMANCE] Really delete the trigger

assets/src/components/activities/likert/LikertDelivery.tsx
Fixes a style issue where likert feedback is inline instead of block
Closes #3009
=> [BUG FIX] Fix a style issue where likert feedback is inline instead of block

assets/src/apps/delivery/store/features/page/actions/loadInitialPageState.ts
when resuming / refreshing a lesson in progress, the `session.tutorialScore` value should be reset to the total score of all evaluated attempts. that value is stored in the page state, though not used to actually calculate the final score, it is used to display the score at the top and in some cases it is used in trap states to alter the current question score. using a restored value is therefore not ideal because the current activity that we are resuming to may have already been fiddling with it via trap states (negative attempts).
=> [BUGFIX] AOPS-988 scores using session.tutorialScore could be wrong

assets/src/components/activities/DeliveryElementProvider.tsx, assets/src/components/activities/common/choices/delivery/ChoicesDeliveryConnected.tsx, assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/custom_dnd/FocusedFeedback.tsx, assets/src/components/activities/types.ts
Fixes showing feedback in graded context and also fixes another issue where restoring dnd state crashes page.
Closes #3008
=> [BUG FIX] Fix Dnd feedback in graded context and state restore crashes page

assets/src/apps/delivery/store/features/page/actions/loadInitialPageState.ts
sessionState was made read only at this point, caused exception that was swallowed by redux
=> [BUGFIX] MER-1462 resume mode not working

lib/oli/authoring/editing/activity_editor.ex, lib/oli/authoring/editing/page_editor.ex
JSON schema validation is a performance bottleneck for page editing. As soon as a table is added to a page the time it takes to validate goes way up, and with each additional table it keeps climbing.  On tokamak I had a page which contained 10 tables take 12 seconds to save.  
Until we can figure out a performant way to validate during save this PR removes that step.  I'd rather risk introducing bad data into a page revision, which will end up getting caught at rendering time, than have this performance issue.
=> [PERFORMANCE] Remove JSON validation step during edits

assets/src/components/editing/elements/common/MediaPickerPanel.tsx, assets/src/components/editing/elements/video/VideoEditor.tsx, assets/src/components/editing/elements/video/VideoModal.tsx, assets/src/components/editing/elements/video/VideoSettings.tsx, assets/src/components/media/manager/MediaManager.tsx, assets/src/components/video_player/ClosedCaptionButton.tsx, assets/src/components/video_player/VideoPlayer.tsx, assets/src/components/video_player/video-react.d.ts, assets/src/data/content/model/elements/types.ts, assets/styles/authoring/controls.scss, assets/styles/common/video.scss, priv/schemas/v0-1-0/content-element.schema.json
Adds closed caption  / subtitle support to the video element.
Fixes #3036 
A couple minor changes included:
- The media-picker panel didn't have a way to cancel if you didn't want to pick something, so added that.
- I made the settings button on videos always visible, some change along the way made it really hard to show up.
- 
Demo:
https://user-images.githubusercontent.com/333265/195880884-a8857f58-1adf-4552-a1a6-da7f53770a96.mp4
=> [FEATURE] Added closed caption support to video player. [MER-1498]

.github/workflows/package.yml
=> [ENHANCEMENT] update version in docs build

lib/oli/delivery/paywall.ex, lib/oli_web/live/common/hierarchy/hierarchy_picker.ex, lib/oli_web/live/common/hierarchy/move_modal.ex, lib/oli_web/live/common/modal.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/curriculum/entries/delete_modal.ex, lib/oli_web/live/curriculum/entries/options_modal.ex, lib/oli_web/live/delivery/manage_updates.ex, lib/oli_web/live/resources/pages_view.ex, lib/oli_web/live/sections/enrollments/enrollments_view.ex, lib/oli_web/live/sections/gating_and_scheduling.ex, test/oli_web/controllers/api/payment_controller_test.exs, test/oli_web/live/ingest_live_test.exs
Fixes some remaining issues related to the liveview upgrade and modal changes.
=> [BUG FIX] fix some remaining issues with live view modals

lib/oli_web/live/resources/pages_view.ex
Fixes the Options, Move and Delete modals in the All Pages view.
Closes #3094
=> [BUGFIX] Fix modals in the All Pages View [MER-1536]

lib/oli/rendering/content/html.ex
Fixes the returned list to add a fourth string to match properly the expected pattern
=> [BUG FIX] fix failing pattern match [MER-1547]

assets/src/apps/authoring/components/Modal/ImagePickerModal.tsx, assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusImageBrowser.tsx, assets/src/apps/authoring/components/RightMenu/RightMenu.tsx, assets/src/apps/authoring/store/index.ts, assets/src/apps/authoring/store/rootReducer.ts, assets/src/components/activities/adaptive/components/common/PartComponent.tsx, assets/src/components/hooks/useToggle.ts, assets/src/components/media/UrlOrUpload.tsx, assets/src/components/media/manager/MediaManager.tsx, assets/src/components/parts/janus-image/schema.ts, assets/styles/authoring/controls.scss
Use the torus media-manager to select image URL's for the image component in adaptive lessons.
Demo:
https://user-images.githubusercontent.com/333265/200407758-534a6b15-b79d-425b-9048-d7b688ed9bf9.mp4
=> [FEATURE] Torus media-manager support for adaptive images. [MER-1526]

lib/oli/delivery.ex, lib/oli/delivery/delivery_setting.ex, lib/oli/delivery/page/page_context.ex, lib/oli/resources.ex, lib/oli/resources/collaboration.ex, lib/oli/resources/collaboration/collab_space_config.ex, lib/oli/resources/collaboration/post.ex, lib/oli/resources/resource_type.ex, lib/oli/resources/revision.ex, priv/repo/migrations/20221031135344_add_collaborative_spaces.exs, priv/repo/migrations/20221101195230_add_posts_table.exs, priv/repo/migrations/20221103162115_add_delivery_settings.exs, test/oli/delivery/page/page_context_test.exs, test/oli/delivery_test.exs, test/oli/resources/collaboration_test.exs, test/oli_web/controllers/delivery_controller_test.exs, test/support/factory.ex
[MER-1514](https://eliterate.atlassian.net/browse/MER-1514)
Add some infra for collaborative spaces feature.
=> [FEATURE] [MER-1514] Collaborative Spaces Infra

assets/src/components/misc/PaginationControls.tsx, assets/styles/delivery/page_delivery/page.scss, lib/oli/authoring/editing/page_editor.ex, lib/oli/delivery/page/activity_context.ex, lib/oli/delivery/page/page_context.ex, lib/oli/rendering/activity/activity_summary.ex, lib/oli/rendering/activity/html.ex, lib/oli_web/controllers/resource_controller.ex, lib/oli_web/live/manual_grading/rendering.ex
This PR adds question (activity) numbering during graded page rendering.  This numbering also shows up in page preview, for only graded pages.
=>  [FEATURE] Activity numbering in graded pages [MER-1541]

lib/oli/authoring/editing/page_context.ex, lib/oli/authoring/editing/page_editor.ex, lib/oli/delivery.ex, lib/oli/delivery/page/page_context.ex, lib/oli/resources/collaboration.ex, lib/oli/resources/collaboration/collab_space_config.ex, lib/oli/resources/revision.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/controllers/resource_controller.ex, lib/oli_web/live/collaboration_live/collab_space_config_view.ex, lib/oli_web/templates/page_delivery/instructor_preview.html.eex, lib/oli_web/templates/resource/edit.html.eex, test/oli/delivery_test.exs, test/oli/resources/collaboration_test.exs, test/oli_web/live/collab_space_config_live_test.exs
[MER-1515](https://eliterate.atlassian.net/browse/MER-1515)
Add support to allow authors to config collab spaces for each page. Also allow instructors to start from there and override the settings.
Author side:
Instructor side:
=> [FEATURE] [MER-1515] Collab spaces config views

assets/src/components/resource/editors/AlternativesEditor.modules.scss, lib/oli/interop/ingest/processor/pages.ex, lib/oli/interop/ingest/processor/project.ex, lib/oli/interop/ingest/processor/rewiring.ex, priv/schemas/v0-1-0/content-alternatives.schema.json
Adds support for alternatives ingest.
https://github.com/Simon-Initiative/course-digest/pull/114
=> [FEATURE] add alternative ingest support

lib/oli/resources/collaboration.ex, lib/oli_web/live/admin/admin_view.ex, lib/oli_web/live/collaboration_live/admin_table_model.ex, lib/oli_web/live/collaboration_live/index_view.ex, lib/oli_web/live/collaboration_live/instructor_table_model.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, test/oli/resources/collaboration_test.exs, test/oli_web/live/collaboration_live_test.exs, test/support/factory.ex
[MER-1517](https://eliterate.atlassian.net/browse/MER-1517)
Add an index for admins to search all collab spaces in the system, and for instructors to search all collab spaces that belongs to a section.
Admin:
Instructor:
=> [FEATURE] [MER-1517] Admin and Instructor Collaborative Spaces Index

lib/oli/delivery/attempts/manual_grading.ex
There's a lot of formatting changes here, but the only change of substance is line 328 of `manual_grading.ex` where I corrected the pattern that was attempting to be matched in the function definition of `maybe_initiate_grade_passback`.  
The results of `Oli.Delivery.Attempts.PageLifecycle.Graded.roll_up_resource_attempts_to_access` were being piped into `maybe_initiate_grade_passback`, yet `maybe_initiate_grade_passback` was trying to match `{:ok, %ResourceAttempt{}}` as the first argument when in actuality it is a `{:ok, %ResourceAccess{}}` that is being passed in.   Since there was a catch all function definition also, this case was never being hit, and thus passback never initiated.
=> [BUG FIX] Allow grade passback to occur after manual scoring [MER-1460]

CHANGELOG.md
Updates the change log to reflect most recent unreleased changes.
=> [CHORE] Update change log

lib/oli_web/templates/project/overview.html.eex
The save button got accidentally moved to the wrong location.
=> [BUG FIX] Move save button [MER-1586]

lib/oli/delivery/snapshots/worker.ex
This PR reworks the snapshot worker to have it issue one and only one bulk insert query.
=> [PERFORMANCE] execute one insert for all part attempt snapshots [MER-1591]

lib/oli/delivery/attempts/activity_lifecycle/persistence.ex
Reworks bulk update approach to place all values into parameters, for SQL escaping/protection, etc
=> [BUG FIX] Rework bulk edit approach [MER-1595]

lib/oli_web/views/view_helpers.ex, test/oli_web/controllers/brand_controller_test.exs
Fixes an issue where brand page crashes if there are any brands present.
Closes #3173
=> [BUG FIX] Fix manage brands error [MER-1601]

assets/src/components/editing/elements/formula/formulaActions.tsx
=> [Bugfix] Fix label of inline formula menu

lib/oli/authoring/clone.ex
This PR fixes the issue where project attributes, labels, and activity selections are not copied when the project is duplicated
=> Duplicate project attributes, labels and activity selections when project is duplicated [MER-1624]

assets/src/components/editing/elements/list/listActions.ts
Bug: List type (bullet vs ordered) apply to all lists when a list is nested. For example, Create an unordered list with three items. Indent the third to create a sublist. With your cursour active in the sublist item, change its type to Ordered. It changes both the top level and the sublist to Ordered.
=> [BUGFIX] Allow formatting sub-lists [MER-1631]

assets/src/apps/delivery/components/ActivityRenderer.tsx, assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx, assets/src/apps/delivery/layouts/deck/components/HistoryNavigation.tsx, assets/src/apps/delivery/store/features/groups/actions/deck.ts, assets/src/components/activities/DeliveryElement.ts, assets/src/components/activities/adaptive/AdaptiveDelivery.tsx
[screen-recorder-thu-dec-22-2022-15-06-32.webm](https://user-images.githubusercontent.com/70621864/209104751-90b14e23-b66e-4cbb-be77-5681ec36ffa2.webm)
=> MER-1593 | Support continuing advanced lessons on browser refresh

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx
There was a bug in the system where the mutate state values were not getting sent back to the server. The scripting was updated with the values, but it didn't get saved in DB.
=> Saving mutate state value to server.

.github/workflows/deploy.yml, .github/workflows/package.yml
use var instead of secret for AUTO_DEPLOY_ENABLED
=> add stellarator to deploy targets

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
[MER-1643](https://eliterate.atlassian.net/browse/MER-1643)
Don't persist in the db the part attempts submission when evaluating an activity in an adaptive page. Instead, update the list in memory and use that updated list in subsequent functions.
I understand this is only used to get a correct result when calling `determine_activity_rollup_fn`, so the change shouldn't be too risky, but I'd still spend some time testing that nothing is broken or that we don't need that data persisted elsewhere.
[MER-1643]: https://eliterate.atlassian.net/browse/MER-1643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-1643] Do not persist part attempts submission when evaluating an adaptive activity

assets/src/apps/delivery/layouts/deck/LessonFinishedDialog.tsx, assets/src/apps/delivery/layouts/deck/RestartLessonDialog.tsx
I actually haven't been able to reproduce in O&F, need to double check that it fails in a section. The logic still looked flawed however, so opening this tentative to some more testing.
=> SOJ-427 section restart not happening, fix inverted graded logic

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli/delivery/attempts/activity_lifecycle/persistence.ex, lib/oli/delivery/attempts/core.ex, lib/oli/delivery/attempts/page_lifecycle/graded.ex, test/oli/delivery/attempts/latest_attempts_test.exs, test/oli/delivery/submission_test.exs
Changes graded page finalization logic to only consider evaluated activity attempts when an adaptive page is being finalized.
=> [BUG FIX] Adaptive eval fixes

assets/css/app.css, lib/oli_web/components/delivery/learning_opportunities.ex, lib/oli_web/components/delivery/up_next.ex
This PR fixes a small style issue introduced by #3246
=> [BUG FIX] Restore btn link style

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts
We should not create a new attempt if the check result contains a wrong trap state and has a navigation to another screen.
=> Wrong Trap State | Refactored New Attempt Creation Logic

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts
=> prevent attempts being created when incorrect and navigating

assets/package.json, assets/tailwind.config.js, assets/yarn.lock, lib/oli_web/components/delivery/exploration_card.ex, lib/oli_web/components/delivery/exploration_shade.ex, lib/oli_web/plugs/require_exploration_activities.ex, lib/oli_web/router.ex, lib/oli_web/templates/layout/page.html.heex, lib/oli_web/templates/page_delivery/index.html.heex, test/oli_web/controllers/page_delivery_controller_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-1670?atlOrigin=eyJpIjoiODZhY2I2MGU3YzczNDM4NmI3MDFmMGQxYjJhMDE0MjQiLCJwIjoiaiJ9)
=> [FEATURE] [MER-1675] Exploration shade content

assets/src/phoenix/app.ts
Improves the topbar animation as explained [in this article](https://fly.io/phoenix-files/make-your-liveview-feel-faster/) and in the [official Phoenix LiveView docs](https://hexdocs.pm/phoenix_live_view/installation.html#progress-animation)
=> Improve progress bar animation

assets/css/app.css, assets/src/apps/authoring/Authoring.tsx, assets/src/apps/authoring/components/Accordion/ContextAwareToggle.tsx, assets/src/apps/authoring/components/AdaptiveRulesList/AdaptiveRulesList.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ActionFeedbackEditor.tsx, assets/src/apps/authoring/components/AdvancedAuthoringModal.tsx, assets/src/apps/authoring/components/Modal/DeleteConfirmationModal.tsx, assets/src/apps/authoring/components/Modal/DiagnosticsWindow.tsx, assets/src/apps/authoring/components/Modal/ScoringOverview.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/CompJsonEditor.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/LearningObjectivesModal.tsx, assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx, assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx
This fixes 4 bugs introduced from torus styling infrastructure changes.
1. Fixed lack of styling in react-bootstrap modals
2. Fixed tooltip styling bug - The tooltips were missing a background, making them hard to see.
3. The component toolbar for delete wasn't working.
4. Fixed left menu collapsing on it's own on add - on adding a screen or rule, that section of the left-menu would automatically collapse when it shouldn't.
Before:
After:
=> [Bugfix] Fixed advanced authoring styling bugs.

assets/package.json, assets/src/components/common/Navbar.tsx, assets/src/components/delivery/CourseContentOutline.tsx, assets/src/hooks/click_outside.ts, assets/src/hooks/media_query.ts, assets/yarn.lock, lib/oli_web/components/delivery/nav_sidebar.ex, lib/oli_web/templates/layout/page.html.heex
Adds additional styling and animation to the course content outline. Also adds some more advanced state management for showing and collapsing the popout menu.
=> [ENHANCEMENT] Improve navbar content outline animation and styles

assets/css/bootstrap-shims.css, assets/css/bs/popover.css, assets/src/apps/bibliography/BibEntryEditor.tsx, assets/src/apps/page-editor/PageEditor.tsx, assets/src/components/common/UserAccountMenu.tsx, assets/src/components/misc/Paging.tsx, assets/src/components/modal/Modal.tsx, assets/src/components/resource/editors/AddResource.tsx, assets/styles/common/elements.scss, assets/tailwind.theme.js, lib/oli_web/live/common/filter_box.ex, lib/oli_web/live/common/paging.ex, lib/oli_web/live/objectives/delete_modal.ex, lib/oli_web/live/objectives/listing.ex, lib/oli_web/live/objectives/objectives.ex
This PR addresses several UI issues including:
- Objectives styles and modal, stats hard to read
- Activity bank pagination broken when > 9 pages
- Bibliography styles, cannot see input field borders
- User menu shouldn't show "Link Account" option for guest learner
- Authoring insertion menu and preview button styles
=> [BUGFIX] Several UI fixes

assets/tailwind.theme.js
This PR changes the delivery primary color from purple to blue, which more closely resembles the OLI branding.
=> [ENHANCEMENT] Change primary color from purple to blue

lib/oli/interop/ingest/processor/bib_entries.ex
This PR addresses a regression issue where course content ingests for bibliography entries were missing a specialized mapper capable of ensuring all content was ingested.
=> [BUG-FIX][MER-1770] Fix blank citation reference 

lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/assignments/assignment_card.ex, lib/oli_web/components/delivery/assignments/assignments_list.ex, lib/oli_web/components/delivery/nav_sidebar.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/router.ex, lib/oli_web/templates/page_delivery/assignments.html.heex, test/oli/delivery/sections/graded_pages_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs, test/support/test_helpers.ex
[Link to the story](https://eliterate.atlassian.net/browse/MER-1735)
=> [MER-1735] Assignments view

assets/src/apps/delivery/layouts/deck/DeckLayoutHeader.tsx, assets/styles/preview/preview-tools.scss, lib/oli_web/templates/layout/chromeless.html.eex
Fixes an issue where bootstrap styles were not being included in advanced page delivery.
=> [MER-1820] restore bootstrap styles in advanced delivery

assets/css/app.css, assets/src/components/activities/adaptive/components/authoring/ScreenAuthor.modules.scss, assets/src/components/activities/adaptive/components/authoring/ScreenAuthor.tsx, assets/styles/authoring/advanced-authoring.scss
Fixes the variable picker UI and Popup config modal in the advanced authoring tool.
This PR address #1 and #3 in the ticket https://eliterate.atlassian.net/browse/MER-1821. #2 will be addressed at some point in the future when bootstrap is removed from the advanced author and styles are converted over to a pure tailwind/css approach.
=> [MER-1821] Fix advanced authoring UI issues
