Simon-Initiative/oli-torus

lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/assignments/assignment_card.ex, lib/oli_web/components/delivery/assignments/assignments_list.ex, lib/oli_web/live/curriculum/entries/options_modal.ex, test/oli_web/controllers/page_delivery_controller_test.exs, test/support/test_helpers.ex
[Link to the story](https://eliterate.atlassian.net/browse/MER-1734?atlOrigin=eyJpIjoiNTVlYzRhNzYxZjU4NDA2YWFmMzQ4OGU3M2YwZmJjYWQiLCJwIjoiaiJ9)
https://user-images.githubusercontent.com/53446634/226444538-6503018a-0c4c-40e6-aec5-e3db8d363a12.mov
=> [MER-1734] Assigments related practice

assets/styles/common/elements.scss
Fixes inline formula to be rendered vertically inline with surrounding text.
https://eliterate.atlassian.net/browse/MER-1836
=> [MER-1836] fix inline mathjax styles

lib/oli_web/templates/page_delivery/page.html.heex, lib/oli_web/templates/page_delivery/prologue.html.eex
Fixes an issue where attempt results column is too narrow
https://eliterate.atlassian.net/browse/MER-1841
=> [BUG FIX] [MER-1841] fix attempt column size

lib/oli_web/live/grades/gradebook_table_model.ex, lib/oli_web/live/progress/page_attempt_summary.ex, test/oli_web/live/progress_live_test.exs
https://eliterate.atlassian.net/browse/MER-1840
=> [BUG FIX] [MER-1840] fix an issue where cells in gradebook were not readable

assets/styles/common/elements.scss
Fixes an issue where bulleted lists should default to disc style
=> [MER-1859] fix an issue where bulleted lists should default to disc style

assets/css/app.css, assets/src/apps/authoring/AuthoringContainer.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ActionMutateEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/AdaptivityEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ConditionItemEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ConditionsBlockEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/InitStateEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/VariablePicker.tsx, assets/styles/preview/preview-tools.scss, lib/oli_web/templates/layout/authoring.html.leex, lib/oli_web/templates/layout/chromeless.html.eex, lib/oli_web/templates/layout/lti.html.eex
This PR removes the shadow DOM isolation layer and bootstrap styles from the adaptive author in favor of a unified tailwind approach. Shadow DOM was causing unexpected bugs related to how the adaptive author is constructed and this PR will unify development experience for both authoring systems.
I suspect there will be a couple of minor style related issues we uncover which we can fix as we discover them going forward.
=> [ENHANCEMENT] Remove Shadow DOM from Adaptive Author

CHANGELOG.md, lib/oli_web/live/products/products_view.ex, mix.exs
Fixes an issue where products view throws a server error in some cases
=> [BUG FIX] fix products view

lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/enrollment_context_role.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/content/content_table_model.ex, lib/oli_web/components/delivery/discussion_activity/discussion_activity.ex, lib/oli_web/components/delivery/instructor_dashboard.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, test/oli/delivery/metrics/progress_test.exs, test/oli_web/live/delivery/instructor_dashboard/content_tab_test.exs, test/oli_web/live/delivery/instructor_dashboard/students_tab_test.exs
This PR addresses[ this ticket](https://eliterate.atlassian.net/browse/MER-1713) and updates the students tab to handle filtering by page_id in the url params.
=> [MER-1713] Instructor dashboard content view

lib/oli/delivery/sections.ex
After the PR that added "required student survey" support landed, it was necessary to augment the logic that calculates, and effectively prunes, unreachable pages in the course section so that the survey would not be pruned.
=> [ENHANCEMENT] Ensure we do not prune the survey

lib/oli/delivery/metrics.ex, lib/oli_web/components/delivery/student_dashboard.ex, lib/oli_web/live/delivery/student_dashboard/components/content_tab.ex, lib/oli_web/live/delivery/student_dashboard/components/helpers.ex, lib/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab.ex, lib/oli_web/live/delivery/student_dashboard/components/progress_tab.ex, lib/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab.ex, lib/oli_web/live/delivery/student_dashboard/initial_assigns.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, lib/oli_web/live/sections/enrollments_table_model.ex, lib/oli_web/router.ex, lib/oli_web/templates/layout/delivery_student_dashboard.html.heex, test/oli_web/live/delivery/student_dashboard/components/content_tab_test.exs, test/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab_test.exs, test/oli_web/live/delivery/student_dashboard/components/progress_tab_test.exs, test/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab_test.exs, test/oli_web/live/delivery/student_dashboard/student_dashboard_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1721) to the ticket.
Components for each required tab were created that will be developed/expanded in [future tickets of the EPIC](https://eliterate.atlassian.net/browse/MER-1720) (so far they have a "Not yet developed" placeholder)
Left some TODO comments that depend on other tickets
=> [MER-1721] Student Dashboard

lib/oli/authoring/course.ex, lib/oli/delivery.ex, lib/oli/delivery/sections.ex, lib/oli_web/controllers/session_controller.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/plugs/force_required_survey.ex, lib/oli_web/router.ex, test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/controllers/session_controller_test.exs, test/oli_web/live/sections/overview_live_test.exs, test/support/test_helpers.ex
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-1730)
In order to dev qa this ticket, you need to edit the survey page and add some activity to it. For this, you need to check the slug of the survey's revision, go to `/authoring/project/#{project_slug}/resource/#{survey_slug}` and add some multiple choice question or something. Then you need to publish the changes, apply them to the section and check if the user gets redirected to the survey.
=> [FEATURE][MER-1730] Redirect students to course survey

lib/oli/delivery/metrics.ex, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/content/content_table_model.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/components/content_tab.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, test/oli_web/live/delivery/student_dashboard/components/content_tab_test.exs, test/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab_test.exs, test/oli_web/live/delivery/student_dashboard/components/progress_tab_test.exs, test/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab_test.exs, test/oli_web/live/delivery/student_dashboard/student_dashboard_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1724) to the ticket
=> [MER-1724] Content tab for student dashboard

lib/oli/delivery/sections.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, test/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1723) to the ticket
=> [MER-1723] Learning objectives tab for student dashboard

lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/up_next.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/templates/page_delivery/index.html.heex, test/oli_web/controllers/page_delivery_controller_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-1702)
=> [FEATURE][MER-1702] Add "Up Next" view to student dashboard

assets/css/table.css, lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/sections/enrollments_table_model.ex, test/oli/delivery/metrics/last_interaction_test.exs, test/oli_web/live/delivery/instructor_dashboard/students_tab_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1935) to the ticket
=> [MER-1935] Students last interacted column

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
While working on another bug, I found this issue which was introduced during the fix of MER-1834. The text recall feature was not working correctly in some use cases.
=> MER-1915 | MER-1834

assets/src/components/common/Navbar.tsx, lib/oli_web/components/delivery/buttons.ex, lib/oli_web/templates/shared/_help.html.eex, lib/oli_web/templates/shared/_help_button.html.eex
The help modal was being shown without the initialization, which is what sets up Recaptcha.
Closes #3487
=> [BUG FIX] Fix Tech Support modal initialization

lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, test/oli/delivery/metrics/last_interaction_test.exs, test/oli/delivery/metrics/learning_mastery_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1705) to the ticket
**Pending:**
=> [MER-1705] Learning Mastery calculation

lib/oli/authoring/course.ex, lib/oli_web/live/projects/overview_live.ex, lib/oli_web/live/projects/required_survey.ex, lib/oli_web/live_session_plugs/set_project.ex, test/oli_web/live/projects/overview_live_test.exs, test/oli_web/live/sections/overview_live_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-1936)
=> [FEATURE][MER-1729] Add "Edit survey" button in project overview

lib/oli/delivery/evaluation/rule.ex, lib/oli/utils.ex, test/oli/delivery/evaluation/rule_eval_test.exs, test/oli/utils_test.exs
Normalizes all whitespace to single spaces and trims during rule evaluation
=> [FEATURE] normalize whitespace during rule evaluation [MER-1983]

lib/oli_web/live/curriculum/entries/options_modal.ex
Simple UI change to remove constraint. Tested and works to allow a page to be both.
=> [ENHANCEMENT] Allow page to be both graded and exploration [MER-2040]

assets/src/apps/scheduler/ScheduleGrid.tsx, lib/oli/delivery/sections/scheduling.ex, lib/oli_web/controllers/api/scheduling_controller.ex, test/oli/delivery/sections/scheduling_test.exs
Changes the scheduling UX to:
1. Use full width available on screen. 
2. Allow schedule to be set in user's local timezone, stored in UTC, then shown to student in their local timezone
=> [BUG FIX] Schedule updates

assets/css/button.css, lib/oli_web/components/delivery/content/content_table_model.ex, lib/oli_web/components/delivery/instructor_dashboard.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, test/oli_web/live/delivery/instructor_dashboard/content_tab_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-2059)
https://github.com/Simon-Initiative/oli-torus/assets/53446634/cf96f48c-50c5-49bd-a117-2322e29bfa72
=> [FEATURE][MER-2059] Add container details page

lib/oli/delivery/recommended_actions.ex, lib/oli/resources/collaboration.ex, lib/oli_web/components/delivery/course_content.ex, lib/oli_web/components/delivery/recommended_actions.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/course_content_live.ex, test/oli_web/live/delivery/instructor_dashboard/overview/recommended_actions_tab_test.exs, test/support/test_helpers.ex
[Link to the story](https://eliterate.atlassian.net/browse/MER-1709)
=> [FEATURE][MER-1709] Add recommended actions tab for instructor dashboard overview

lib/oli/delivery/attempts/core.ex
This adds the DataShop query optimization to the v0.22.6 hotfix branch
=> [PERFORMANCE] Add datashop optimization

assets/css/table.css, lib/oli/delivery/settings.ex, lib/oli/delivery/settings/combined.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/live/sections/assessment_settings/settings_live.ex, lib/oli_web/live/sections/assessment_settings/settings_table.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, test/oli_web/live/sections/assessment_settings/settings_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1944) to the ticket
[Link ](https://docs.google.com/spreadsheets/d/1uEPyPyWxMAanRPB_9fl71nGvHezN9JgU1vC5Y3RlQvg/edit#gid=0) to the UX design
=> [MER-1944] Instructor level assessments settings

assets/css/table.css, lib/oli/delivery/sections.ex, lib/oli/publishing.ex, lib/oli_web/live/common/hierarchy/hierarchy_picker.ex, lib/oli_web/live/common/hierarchy/hierarchy_picker_table_model.ex, lib/oli_web/live/common/paged_table.ex, lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/delivery/remix/add_materials_modal.ex, lib/oli_web/live/delivery/remix_section.ex, test/oli_web/live/remix_section_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2086)
https://github.com/Simon-Initiative/oli-torus/assets/53446634/f0011508-70e2-4ca0-b516-960628805038
=> [FEATURE][MER-2086] Support adding unordered pages to sections and products

assets/css/table.css, lib/oli/delivery/experiments/experiment_builder.ex, lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/content/content_table_model.ex, lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex, lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, lib/oli_web/live/sections/enrollments_table_model.ex, test/oli/delivery/metrics/learning_proficiency_test.exs, test/oli_web/live/delivery/instructor_dashboard/reports/content_tab_test.exs
[Link ](https://eliterate.atlassian.net/browse/MER-2098)to the ticket
This PR also enabled sorting the learning objectives table by student_proficiency_obj and student_proficiency_subobj
=> [MER-2098] Rename learning mastery

lib/oli_web/live/common/card_listing.ex
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-1990) and [Github issue](https://github.com/Simon-Initiative/oli-torus/issues/3463)
=> [BUGFIX][MER-1990] Fix project title trim in source selection

lib/oli/rendering/activity/html.ex, lib/oli/rendering/alternatives/html.ex, lib/oli/rendering/content/html.ex, lib/oli/rendering/context.ex, lib/oli/rendering/elements/html.ex, lib/oli/rendering/survey/html.ex, lib/oli_web/common/react.ex, lib/oli_web/live/delivery/student_onboarding/survey.ex
[Link to the story](https://eliterate.atlassian.net/browse/MER-2097)
=> [BUGFIX][MER-2097] Submit survey button not rendered

lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, lib/oli_web/templates/page_delivery/index.html.heex, test/oli_web/live/sections/overview_live_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-2112)
=> [BUGFIX][MER-2112] Fix manage section links for instructor

assets/css/table.css, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex, lib/oli_web/components/delivery/progress/progress.ex, lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/common/hierarchy/hierarchy_picker.ex, lib/oli_web/live/common/search_input.ex, lib/oli_web/live/delivery/publications_table_model.ex, lib/oli_web/live/delivery/remix/add_materials_modal.ex, lib/oli_web/live/delivery/remix_section.ex, lib/oli_web/live/sections/assessment_settings/settings_table.ex, lib/oli_web/live/users/user_enrolled_sections.ex, test/oli_web/live/remix_section_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2087)
=> [Improvement][MER-2087] Add pagination to add materials modal

lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex, lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/live/delivery/instructor_dashboard/helpers.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/router.ex, test/oli_web/controllers/delivery_controller_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-1964)
=> [FEATURE][MER-1964] Add csv download for instructor dashboard tables

lib/oli/delivery/sections.ex
Fixes an issue where progress calculation throws arithmetic error
=> Fixes an issue where progress calculation throws arithmetic error

lib/oli/delivery/metrics.ex, lib/oli_web/components/delivery/course_content.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/delivery/student_dashboard/initial_assigns.ex, test/oli/delivery/metrics/progress_test.exs
Fixes progress metrics calculation and standardize api. Attempt number 2 to try and fix server error thrown
=> [BUGFIX] Fix progress metrics calculation and standardize api (Part 2)

assets/css/table.css, lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex, lib/oli_web/components/delivery/scored_activities/activities_table_model.ex, lib/oli_web/components/delivery/scored_activities/assessments_table_model.ex, lib/oli_web/components/delivery/scored_activities/scored_activities.ex, lib/oli_web/components/delivery/scored_activities/scored_activities_table_model.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/sections/assessment_settings/settings_live.ex, lib/oli_web/live/sections/assessment_settings/settings_table.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex, lib/oli_web/live/sections/enrollments_table_model.ex, lib/oli_web/live/users/user_enrolled_sections.ex, lib/oli_web/router.ex, test/oli_web/controllers/delivery_controller_test.exs, test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs, test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2060) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/44eb773f-feda-46f0-aa00-a212a33ca2fe
=> [MER-2060] Add summative assessment item analytics

lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/page_delivery.ex, lib/oli_web/components/delivery/page_navigator.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/plugs/maybe_gated_resource.ex, lib/oli_web/router.ex, lib/oli_web/templates/layout/page.html.heex, lib/oli_web/templates/page_delivery/_previous_next_nav.html.heex, lib/oli_web/templates/page_delivery/instructor_page_preview.html.heex, lib/oli_web/templates/page_delivery/page.html.heex, lib/oli_web/views/page_delivery_view.ex, test/oli_web/controllers/page_delivery_controller_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2160)
I had to use a bunch of JS. We should move this view to a Phoenix LiveView in the future.
https://github.com/Simon-Initiative/oli-torus/assets/53446634/e9df406b-f702-4ba4-869a-e20fcb282b6d
=> [FEATURE][MER-2160] Add index based navigation for course pages

lib/oli_web/components/delivery/scored_activities/scored_activities.ex
This PR replaces `Surface.LiveComponent` with `Phoenix.LiveComponent`, as discussed in [this PR](https://github.com/Simon-Initiative/oli-torus/pull/3706#discussion_r1236931051)
=> [MER-2060v2] Use Phoenix.LiveComponent :smile::heart:

lib/oli_web/live/common/stepper/stepper.ex, lib/oli_web/live/delivery/student_onboarding/wizard.ex, lib/oli_web/live/new_course/new_course.ex, test/oli_web/live/delivery/onboarding_wizard/student_onboarding_wizard_test.exs, test/oli_web/live/new_course/name_course_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-2175)
=> [BUGFIX][MER-2175] Fix "Cancel" button in student onboarding wizard

assets/src/components/activities/common/delivery/inputs/DropdownInput.tsx, assets/src/components/activities/common/delivery/inputs/MathInput.tsx, assets/src/components/activities/common/delivery/inputs/NumericInput.tsx, assets/src/components/activities/common/delivery/inputs/TextInput.tsx, assets/src/components/activities/multi_input/MultiInputDelivery.tsx, assets/src/components/activities/multi_input/actions.ts, assets/src/components/activities/multi_input/schema.ts, assets/src/components/activities/multi_input/sections/InputRefToolbar.tsx, assets/src/components/activities/multi_input/sections/QuestionTab.tsx, assets/src/components/activities/vlab/utils.tsx, assets/src/components/common/MathLive.modules.scss, assets/src/components/editing/elements/inputref/InputRefEditor.tsx, assets/src/data/content/writers/html.tsx, assets/styles/common/elements.scss
Add authoring and delivery support for user defined input sizes in multi input questions.
Part of: https://github.com/Simon-Initiative/course-digest/pull/169
=> [MER-2165] add authoring and delivery support for user defined input sizes

CHANGELOG.md
Updates the change log with all the work going into v24
=> [CHORE] update change log for v24

lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, lib/oli_web/live/sections/assessment_settings/settings_live.ex, test/oli_web/live/sections/assessment_settings/settings_live_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2171)
=> [Improvement][MER-2171] Add breadcrumbs navigation to assessments settings

assets/src/components/activities/adaptive/AdaptiveDelivery.tsx
I already fixed this issue as part of `hotfix-v0.22.6` (https://github.com/Simon-Initiative/oli-torus/commit/8f980bdad5a01c2b5b1bdbe338ec3e58301a6a7a).
I am not sure why it's not there in the main branch.
=> [BUGFIX] [MER-2224] Answer inputs not carrying over to next screen properly.

assets/src/hooks/submit_form.ts, lib/oli_web/live/new_course/course_details.ex, lib/oli_web/live/new_course/name_course.ex, lib/oli_web/live/new_course/new_course.ex, lib/oli_web/live/new_course/table_model.ex, test/oli_web/live/new_course/course_details_test.exs, test/oli_web/live/new_course/name_course_test.exs, test/oli_web/live/new_course/select_source_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2181)
=> [BUGFIX][MER-2181] Various bug fixes in create course modal

lib/oli/delivery/sections/browse.ex, lib/oli/institutions.ex, lib/oli_web/live/admin/institutions/sections_and_students_view.ex, lib/oli_web/live/sections/edit_view.ex, lib/oli_web/live/sections/main_details.ex, lib/oli_web/live/sections/table_model.ex, lib/oli_web/live/users/users_table_model.ex, lib/oli_web/router.ex, lib/oli_web/templates/institution/index.html.eex, test/oli_web/live/admin/institutions/sections_and_students_view_test.exs, test/oli_web/live/sections/edit_live_test.exs
[Link ](https://eliterate.atlassian.net/browse/MER-1956?filter=10069)to the ticket
=> [MER-1956] View course sections by institution

test/oli_web/live/admin/institutions/sections_and_students_view_test.exs
This PR fixes two flaky tests found by inspecting [this broken build](https://github.com/Simon-Initiative/oli-torus/actions/runs/5425318527/jobs/9865916933?pr=3814)
=> Fix 2 flaky tests

lib/oli/delivery/sections.ex, test/oli/delivery/sections/graded_pages_test.exs, test/support/test_helpers.ex
[Link](https://eliterate.atlassian.net/browse/MER-2211) to the ticket
=> [MER-2211] Unordered pages in assignment tab

lib/oli/delivery/attempts/auto_submit/worker.ex
Root cause of failure to pass back grade to LMS after auto-submit was simply that the passback job was not created.
=> [BUG FIX] kick off grade passback job when graded [MER-2253]

lib/oli/delivery/metrics.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/components/delivery/scored_activities/scored_activities.ex, test/oli/delivery/metrics/progress_test.exs, test/oli_web/live/delivery/instructor_dashboard/reports/content_tab_test.exs, test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2227) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/b2e4d41b-da10-4d71-95e2-39b55e007e50
This PR also addresses [this other ticket](https://eliterate.atlassian.net/browse/MER-2228)
=> [MER-2227] Fix activity bank in scored activities

lib/oli_web/components/delivery/assignments/assignment_card.ex, lib/oli_web/components/delivery/assignments/assignments_list.ex, lib/oli_web/components/delivery/course_content.ex, lib/oli_web/components/delivery/nav_sidebar.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/delivery/student_dashboard/course_content_live.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, lib/oli_web/templates/page_delivery/index.html.heex, test/oli_web/live/delivery/student_dashboard/course_content_live_test.exs, test/oli_web/live/sections/overview_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1973) to the ticket
This PR also added the missing links in the nav_sidebar for preview mode, and fixed content and assignments "open" buttons to open in preview mode.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/0a07a3f5-fe4d-4b5f-bda6-4e742266416a
=> [MER-1973] Fix preview as instructor and enter as student

CHANGELOG.md, assets/src/hooks/index.ts, assets/src/hooks/live_modal.ts, lib/oli_web/components/modal.ex, lib/oli_web/live/sections/assessment_settings/settings_table.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex, mix.exs, test/oli_web/live/admin/institutions/sections_and_students_view_test.exs, test/oli_web/live/sections/assessment_settings/settings_live_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-2210)
https://github.com/Simon-Initiative/oli-torus/assets/53446634/35202c37-fd5f-4448-9ad6-4f12f9eac05c
=> [IMPROVEMENT][MER-2110] Allow due date edition from assessments settings

lib/oli/publishing.ex, lib/oli_web/live/common/hierarchy/hierarchy_picker.ex, lib/oli_web/live/common/hierarchy/hierarchy_picker_table_model.ex, test/oli_web/live/remix_section_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2087)
=> [IMPROVEMENT][MER-2087] QA feedback fixes in add materials modal

CHANGELOG.md, assets/src/apps/authoring/components/Flowchart/paths/path-options.ts, assets/src/apps/authoring/components/Flowchart/rules/create-generic-rule.ts, assets/src/apps/authoring/components/Flowchart/screens/screen-factories.ts, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartTopToolbar.tsx, assets/src/apps/authoring/components/ScreenList/AddScreenModal.tsx, assets/src/components/parts/janus-input-number/schema.ts, assets/src/components/parts/janus-mcq/schema.ts, assets/styles/adaptive/adaptive-reset.scss, assets/webpack.config.js, lib/oli/delivery/evaluation/rule.ex, lib/oli_web/templates/layout/chromeless.html.eex, mix.exs, test/oli/delivery/evaluation/rule_eval_test.exs, test/oli_web/live/admin/institutions/sections_and_students_view_test.exs
Fixed 5 bugs in the flowchart feature that came up during some user testing.
1. Change title of "Blank Screen" to "Instructional Screen"
2. Removed inoperable font size option from MCQ questions
3. Fixed MCQ error when adding an option
4. Changed empty response prompt
5. “Always go to” should always be available
=> [BUGFIX] flowchart feature bug fixes [MER-2254]

assets/src/components/parts/janus-mcq/MultipleChoiceQuestion.tsx, assets/styles/adaptive/flowchart/mcq.scss
_New PR to target prerelease branch_
The horizontal layout on adaptive MCQ questions in flowchart mode was wrapping to a second line, this fixes that.
=> [Bugfix] Fixed horizontal MCQ question layout [MER-2254] 

lib/oli/delivery/metrics.ex, test/oli/delivery/metrics/avg_score_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2176) to the ticket
=> [MER-2176] FIX average score for student

lib/oli/publishing/delivery_resolver.ex, lib/oli_web/live/sections/assessment_settings/settings_live.ex, lib/oli_web/live/sections/assessment_settings/settings_table.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, test/oli_web/live/sections/assessment_settings/settings_live_test.exs
[Link to the story](https://eliterate.atlassian.net/browse/MER-2252)
=> [IMPROVEMENT][MER-2252] Change assessments settings order

lib/oli/delivery/metrics.ex, lib/oli_web/live/delivery/instructor_dashboard/helpers.ex, test/oli/delivery/metrics/learning_proficiency_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2238) to the ticket
=> [MER-2238] Fix student proficiency in content tab

lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex
This PR ensures that unordered pages are shown in both the Student Progress view and in the Quiz Scores view.
=> [BUG FIX] Show all pages [MER-2237]

assets/styles/adaptive/adaptive-reset.scss
This fixes the 4 new issues with Kepler’s Laws - The Celestial Jukebox reported in this ticket. They were all related to how input controls are sized on the page.
=> [Bugfix] Round 2 infiniscope css [MER-2207]

lib/oli_web/components/delivery/actions/actions.ex, lib/oli_web/templates/payment/guard.html.heex
This fixes two problems related to payment processing:
1. [MER-1955]: The "bypass payment" feature implementation did not set the `application_date` field when it created the payment record.  This was leading to a date formatting error when attempting to display this students payment status in the Instructor Dashboard
2. [MER-2264] Some text within the payment guard screen overlapped the pay by credit card button.
So that the payment guard screen works on smaller screens, I also reoriented the two side-by-side divs in the payment guard screen so that they are vertically stacked, instead of horizontal.  
[MER-1955]: https://eliterate.atlassian.net/browse/MER-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-2264]: …
=> [BUG FIX] payment fixes [MER-2264] [MER-1955]

lib/oli/delivery/sections.ex
This PR implements the determination of "Unit Title / Module Title" in a more robust and more efficient manner.
=> [BUG FIX] Avoid bad map [MER-2266]

lib/oli_web/components/delivery/utils.ex, test/oli_web/controllers/delivery_controller_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2219) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/3bd61853-8fc0-4686-bb86-abc781692ab0
=> [MER-2219] Fix user role in account menu

lib/oli/delivery/metrics.ex, lib/oli_web/components/delivery/scored_activities/scored_activities.ex
This fixes the issues with the counts documented in https://eliterate.atlassian.net/browse/MER-2227
The counts of attempts never should have actually been the count of activity attempts, it should have simply been the count of the page (aka 'assessment') attempts. Tested this with an assessment that contains bank selections, works correctly. 
This also fixes a subtle error where the `get_activities` joined through to the ResourceAttempt on the revision id of the latest published revision.  This would lead to the dropping of results whenever this assessment gets revised, and has attempts tied to two (or more) different revisions.
=> [BUG FIX] Fix counts [MER-2227]

lib/oli/resources/collaboration.ex
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2240)
I think that the page times out so it reloads the current tab the user is on. I suspect that the query that fetches the posts for an instructor is the cause of the timeout because it seems to use the [nested loop strategy](https://postgrespro.com/blog/pgsql/5969618#:~:text=one%20cost%2Dwise.-,Nested%20loop%20join,the%20second%20(inner)%20set.) for joining the posts with the other stuff so when the query starts, it loops through all the rows in the outer join (the posts) and then joins with the other rows of the next inner joins. 
Selecting from the section, makes the rows in the outer join much smaller (only one because it's just one section) so it should make the query a lot faster.
=> [BUGFIX][MER-2240] Fix recommended actions tab

lib/oli/delivery/recommended_actions.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
This is the second attempt to fix [MER-2240](https://eliterate.atlassian.net/browse/MER-2240)
[MER-2240]: https://eliterate.atlassian.net/browse/MER-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-2240] Recommended actions fix

assets/src/components/editing/elements/cite/CitationEditor.tsx
This PR fixes the citation (bib entry) picker for insertion and changing an existing citation reference.  Root cause was the original Bootstrap CSS just didn't render correctly. I replaced it with a Tailwind equivalent, which now renders it like:
=> [BUG FIX] Fix citation picker [MER-2322]

lib/oli_web/components/delivery/nav_sidebar.ex, lib/oli_web/templates/layout/page.html.heex
[Link to the story](https://eliterate.atlassian.net/browse/MER-2310)
=> [BUGFIX][MER-2310] Fix unusable modals in collab space

assets/src/components/common/UserAccountMenu.tsx
The popover menu is being hidden behind the side navbar
=> [BUG FIX] Fix popover menu [MER-2333]

lib/oli_web/components/delivery/instructor_dashboard.ex, lib/oli_web/components/delivery/scored_activities/scored_activities.ex, lib/oli_web/components/delivery/user_account_menu.ex
[Link](https://eliterate.atlassian.net/browse/MER-2320) to the ticket
=> [BUG FIX] Scored activities clicking issues [MER-2320]

lib/oli/delivery/metrics.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, test/oli/delivery/metrics/learning_proficiency_test.exs
[Link ](https://eliterate.atlassian.net/browse/MER-2325)to the ticket
=> [BUGFIX] Fix student dashboard proficiency metric [MER-2325]

lib/oli/delivery/metrics.ex
The `Metrics.avg_score_for` joins through ContainedPage records, even when calculating progress for an entire page.  This query approach excludes unordered pages.  
The fix here is to handle the case of `container_id` being `nil` by using a separate query that fetches all `ResourceAccess` records for the requested student(s)
=> [BUG FIX] Avg score fix [MER-2347]

assets/styles/common/controls.scss, lib/oli_web/live/common/properties/group.ex, lib/oli_web/live/common/properties/read_only.ex, lib/oli_web/live/projects/overview_section.ex, lib/oli_web/live/projects/visibility.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/templates/error/500.html.heex
Fixes an issue with checkboxes and radio buttons in dark mode. Also addresses some other dark mode issues I found while testing the radio/checkbox change and removes the unnecessary error page language.
Closes [3958](https://github.com/Simon-Initiative/oli-torus/issues/3958)
=> [BUG FIX] [MER-2364] dark mode it is hard to tell if you checked a box or not

lib/oli_web/live/sections/assessment_settings/settings_live.ex, lib/oli_web/live/sections/assessment_settings/settings_table.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex, test/oli_web/live/sections/assessment_settings/settings_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2367) to the ticket
Enter a password, then bulk apply, then edit it, and finally remove it
https://github.com/Simon-Initiative/oli-torus/assets/74839302/4fc308a7-f044-496c-9a08-303eaf40fce5
Enter a password, then edit it, and finally remove it.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/d5365baa-85c1-4cac-82b5-d555758e57f5
=> [MER-2367] Password on assessment settings

lib/oli/delivery/attempts.ex
Root cause was the assumption that the `transformed_model` is always present as the source for the `"choices"`.  When an author disables choice shuffling for an MCQ that ends up removing the only transform (the "shuffle" transform), resulting in the `transformed_model` being `nil`.  This is a space saving optimization because many, many activities will have no transforms.  
So, the fix here is to check the `transformed_model` and if `nil` use the original (aka "raw") model.  
Also, I noticed the code to extract the text from the choices is somewhat brittle - and it if fails it would break the ability to view the entire student details view (like this bug did).  I wrapped that code in a `try - rescue` to guarantee that it will not break. 
I've tested these changes out locally and they fix …
=> [BUG FIX] Use correct model [MER-2372]

lib/oli_web/live/new_course/select_source.ex, test/oli_web/live/new_course/select_source_test.exs
[Link ](https://eliterate.atlassian.net/browse/MER-2279)to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/13609873-5283-4a44-96ab-10ba5ba1fea9
https://github.com/Simon-Initiative/oli-torus/assets/74839302/c17caea9-a0bb-4a71-9c24-79bc228f0563
=> [MER-2279] Fix search on new open and free

lib/oli_web/common/format_date_time.ex, lib/oli_web/common/session_context.ex, lib/oli_web/components/delivery/course_content.ex, lib/oli_web/components/delivery/discussion_activity/discussion_activity.ex, lib/oli_web/components/delivery/learning_opportunities.ex, lib/oli_web/components/delivery/page_delivery.ex, lib/oli_web/components/delivery/up_next.ex, lib/oli_web/components/delivery/utils.ex, lib/oli_web/live/collaboration_live/instructor_table_model.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, lib/oli_web/live/delivery/student_dashboard/course_content_live.ex, lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex, lib/oli_web/live/projects/overview_live.ex, lib/oli_web/live/sections/enrollments_table_model.ex, lib/oli_web/templates/page_delivery/page.html.heex, lib/oli_web/templates/resource/page_preview.html.heex, test/oli_web/live/delivery/student_dashboard/course_content_live_test.exs
Fixes an issue where some date times were not properly being localized to a user's timezone based on their session context.
=> [BUG FIX] [MER-2376] some date times are not being localized properly

lib/oli_web/components/delivery/scored_activities/assessments_table_model.ex, lib/oli_web/components/delivery/scored_activities/scored_activities.ex, test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs, test/oli_web/live/sections/edit_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2235) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/42a3b89e-b493-4a4f-b24d-03ca8957bc32
=> [MER-2235] Link for assessments in scored activities tab

lib/oli_web/live/grades/export.ex, lib/oli_web/live/grades/grade_sync.ex, lib/oli_web/live/grades/line_items.ex
[Link](https://eliterate.atlassian.net/browse/MER-2365) to the ticket
=> [MER-2365] Buttons covering text

lib/oli_web/live/users/users_table_model.ex, test/oli_web/live/admin_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1976) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/ea2924b4-93ba-4e7b-9ac7-7a83b994b246
=> [MER-1976] User link to linked-author's detailed view

lib/oli_web/live/users/author_detail_view.ex, lib/oli_web/live/users/author_projects.ex, lib/oli_web/live/users/author_projects_table_model.ex, test/oli_web/live/sections/edit_live_test.exs, test/oli_web/live/users/author_detail_view_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-1954) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/bb7f8758-01bf-4a88-b772-ccd56549f4d7
=> [MER-1954] Author projects on details view

CHANGELOG.md, lib/oli/delivery/sections.ex, lib/oli/utils/seeder/section.ex, mix.exs, test/oli/delivery/sections_test.exs, test/oli_web/live/sections/gating_and_scheduling_test.exs, test/support/test_helpers.ex
Fixes an issue where student home instructor preview crashes when gate doesn't have end date specified.
https://eliterate.atlassian.net/browse/MER-2399
Closes #4019
=> [BUG FIX] [MER-2399] student home instructor preview crashes when gate doesn t have end date specified

lib/oli_web/live/common/sortable_table/table.ex, lib/oli_web/live/common/table/column_spec.ex, lib/oli_web/live/common/table/sortable_table.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex, lib/oli_web/live/sections/assessment_settings/tooltips.ex
This PR adds tooltips for the Assessment Settings view, specifically for each table header, explaining what each setting does and how to use it.
=> [ENHANCEMENT] Tooltips for assessment settings table headers [MER-2374]

lib/oli_web/live/delivery/student_onboarding/explorations.ex, lib/oli_web/live/delivery/student_onboarding/intro.ex, test/oli_web/live/delivery/onboarding_wizard/student_onboarding_wizard_test.exs
Adjusts the language and adds image. 
Yes, we know this image does not make sense for all courses that eventually might use Explorations.
=> [ENHANCEMENT] Adjust explorations intro for student onboarding [MER-2404]

lib/oli/delivery/recommended_actions.ex, test/oli_web/live/delivery/instructor_dashboard/overview/recommended_actions_tab_test.exs
[Link ](https://eliterate.atlassian.net/browse/MER-2416)to the ticket
=> [MER-2416] Fix activities due soon

lib/oli_web/live/sections/assessment_settings/settings_table.ex, test/oli_web/live/sections/assessment_settings/settings_live_test.exs
[Link ](https://eliterate.atlassian.net/browse/MER-2340?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug,%20Story)%20AND%20status%20in%20(%22In%20Progress%22,%20PR,%20Ready,%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20priority%20DESC,%20status%20ASC,%20created%20DESC)to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/efb97aac-efb5-41e4-9ae4-d37c7b3c8149
=> [MER-2340] View Feedback dropdown menu not displaying Schedule option

lib/oli_web/live/sections/assessment_settings/settings_table.ex, lib/oli_web/live/sections/assessment_settings/settings_table_model.ex, test/oli_web/live/sections/assessment_settings/settings_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2415) to the ticket
=> [MER-2415] Fix due date on assessment settings

assets/src/apps/authoring/components/Flowchart/rules/create-three-try-workflow.ts, assets/src/components/parts/janus-dropdown/schema.ts, assets/styles/adaptive/flowchart/mcq.scss, assets/styles/adaptive/flowchart/text-input.scss
Four small bug fixes to the advanced author flowchart mode:
- Change default empty response feedback to “Please answer the question."
- Remove font-size from options for the dropdown control.
- Fixed line-height of the multi line text when using a larger font size.
- Fixed horizontal MCQ layout
=> [Bugfix] Adaptive authoring flowchart mode fixes [MER-2413]

lib/oli/delivery/sections.ex, lib/oli/delivery/sections/blueprint.ex, lib/oli/utils/slug.ex, test/oli/utils/slug_test.exs
This is a duplicated for [#4006](https://github.com/Simon-Initiative/oli-torus/pull/4006) to see if this fixes the test failing in the CI
=> [IMPROVEMENT][MER-2332] Improve product and section creation

lib/oli/delivery/sections/blueprint.ex, lib/oli_web/live/new_course/new_course.ex, test/oli/delivery/sections/blueprint_test.exs, test/oli_web/live/new_course/course_details_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2428)
=> [BUGFIX][MER-2429] Fix section creation from product

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx, assets/src/components/activities/custom_dnd/DragCanvas.tsx
This fixes two bugs related to custom drag and drop.
Both are reproducible in the dnd on the only page in this project:
https://proton.oli.cmu.edu/authoring/project/pc_sw/overview
1. Drag all three placeholders up in any order
2. Click Reset
3. Drag a placeholder to the wrong spot
4. Drag that placeholder back to the bottom
5. Drag the placeholder to the right spot
Expected: You can drag to the correct spot and get correct feedback
Actual: No feedback, question is in broken state going forward.
This was caused by the rootDropHandler inside DragCanvas not being updated when the activity attempt guid changed.
1. Open your network dev tools and throttle the network with a high amount of latency
2. Rapidly drag elements around.
3. Feedback stops appearing, error in console, question is in …
=> [Bugfix] Two custom drag and drop bugs [MER-2440]

assets/css/button.css, assets/src/hooks/email_list.ts, assets/src/hooks/index.ts, lib/oli/accounts.ex, lib/oli/accounts/schemas/user.ex, lib/oli/delivery/sections.ex, lib/oli/email.ex, lib/oli_web/components/email_list.ex, lib/oli_web/components/live_modal.ex, lib/oli_web/controllers/invite_controller.ex, lib/oli_web/live/sections/enrollments/enrollments_view.ex, lib/oli_web/live/sections/enrollments_table_model.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/pow/user_routes.ex, lib/oli_web/router.ex, lib/oli_web/templates/email/enrollment_invitation.html.eex, lib/oli_web/templates/email/enrollment_invitation.text.eex, test/oli/accounts_test.exs, test/oli/sections_test.exs, test/oli_web/controllers/invite_controller_test.exs, test/oli_web/live/sections/enrollments_view_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-1912)
https://github.com/Simon-Initiative/oli-torus/assets/53446634/9ed80ef9-154e-4cc5-8bab-ed5bda893ba2
=> [FEATURE][MER-1912] Add ability to enroll users

lib/oli/delivery/sections.ex, test/oli/sections_test.exs, test/oli_web/controllers/page_delivery_controller_test.exs, test/support/test_helpers.ex
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2434)
=> [BUGFIX][MER-2434] Only return pages for upcoming activities

lib/oli/activities/realizer/selection.ex, lib/oli/qa/reviewers/selection_worker.ex
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2463)
=> [BUGFIX] MER-2463 Fix course content audit for activity banks

lib/oli/delivery/sections.ex, lib/oli_web.ex, lib/oli_web/live/delivery/remix_section.ex, test/oli_web/live/remix_section_test.exs, test/support/conn_case.ex
[Link](https://eliterate.atlassian.net/browse/MER-2488) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/f31ff48c-5dce-48df-a068-b8672a228920
=> [MER-2488] Save multiple new units when remixing curriculum

lib/oli_web/live/collaboration_live/collab_space_view.ex, lib/oli_web/live/collaboration_live/posts/list.ex, lib/oli_web/live/collaboration_live/posts/show.ex, test/oli_web/live/collaboration_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2313) to the ticket
No changes were made here.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/3194e05d-f554-4d1c-a450-b5de58fdf7ed
An `archived` badge is added, posts are grayed, and users can still sort and see replies, but the UI for adding new posts, and editing/replying to existing ones is not shown.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/a4b8fce6-ea20-4e61-a6c6-d54f9111e2bc
=> [MER-2313] Issues with archived discussions

lib/oli_web/live/projects/required_survey.ex
PR tweaks misleading wording for required surveys.
=> [MER-2462] Updated required survey wording

lib/oli/delivery/attempts/page_lifecycle/graded.ex, lib/oli_web/templates/page_delivery/page.html.heex
This PR allows a student to complete an assessment with no activities. A score of 1 out of 1 is assigned to the completed attempts.
=> [MER-2506] Evaluate assessment with empty activities

lib/oli/resources/collaboration.ex, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex, lib/oli_web/live/common/custom_labels_form.ex, lib/oli_web/live/common/delete_modal.ex, lib/oli_web/live/common/hierarchy/hierarchy_picker.ex, lib/oli_web/live/community_live/index_view.ex, lib/oli_web/live/community_live/invitation.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/curriculum/container/container_live.html.heex, lib/oli_web/live/curriculum/entries/actions.ex, lib/oli_web/live/curriculum/entries/details.ex, lib/oli_web/live/curriculum/entries/entry.ex, lib/oli_web/live/curriculum/entries/learning_summary.ex, lib/oli_web/live/delivery/open_and_free_index.ex, lib/oli_web/live/grades/export.ex, lib/oli_web/live/grades/grade_sync.ex, lib/oli_web/live/grades/grades.ex, lib/oli_web/live/grades/line_items.ex, lib/oli_web/live/grades/test_connection.ex, lib/oli_web/live/insights/insights.ex, lib/oli_web/live/insights/table_header.ex, lib/oli_web/live/insights/table_row.ex, lib/oli_web/live/objectives/objectives.ex, lib/oli_web/live/resources/pages_table_model.ex, lib/oli_web/live/sections/enrollments/enrollments_view.ex, test/oli/sections_test.exs, test/oli_web/live/delivery/instructor_dashboard/discussions/discussions_tab_test.exs, test/oli_web/live/grades_live_test.exs, test/oli_web/live/system_message_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2520) to the ticket
This PR also fixes a flaky test.
=> [MER-2520] Fix warnings in tests

lib/oli_web/live/sections/sections_view.ex, test/oli_web/live/sections/admin_index_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2522) to the ticket
This PR also increases the width of the select inputs as their values are not fully readable
https://github.com/Simon-Initiative/oli-torus/assets/74839302/b2fe66b5-17e4-4c74-94fb-5b91806cb80d
=> [MER-2522] Add pagination to browse course sections

lib/oli/delivery/sections.ex, lib/oli/interop/export.ex, lib/oli/publishing.ex, test/oli/interop/ingest_test.exs, test/oli_web/controllers/project_controller_test.exs, test/support/test_helpers.ex
[MER-2391](https://eliterate.atlassian.net/browse/MER-2391)
This PR includes the products contained in a project when exporting this project. 
It excludes those products that have remixed materials from other projects in their curriculum.
[MER-2391]: https://eliterate.atlassian.net/browse/MER-2391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE][MER-2391] Include products related project during project export

lib/oli/predefined.ex, test/oli_web/live/ingest_live_test.exs
Updates the default D2L auto fill suggested values for an LTI registration.
=> [ENHANCEMENT] [MER-2527] Update D2L Suggested Registration form values

lib/oli_web/live/grades/gradebook_table_model.ex
[Link](https://eliterate.atlassian.net/browse/MER-2526) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/4ea811b8-c2e0-422d-8775-dbe997baf6ff
https://github.com/Simon-Initiative/oli-torus/assets/74839302/8d44335b-87fd-49f5-b200-23223e5b0423
=> [MER-2526] Fix covered students name in quizz scores tab

lib/oli_web/controllers/delivery_controller.ex, test/oli_web/controllers/delivery_controller_test.exs
[MER-2026](https://eliterate.atlassian.net/browse/MER-2026)
This PR aims to prevent a guest user from enroll in a course when this course requires enrollment.
Thus, if the course has the `requires enrollment` option enabled and the user try to access to the course as a guest user, he/she will be redirected to the login view so that must log in before proceeding to enroll in that course section.
[MER-2026]: https://eliterate.atlassian.net/browse/MER-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2026] Fix unknown enrollments delivery course sections

.github/actions/torus-builder/README.md, .github/actions/torus-builder/action.yml, .github/actions/torus-builder/entrypoint.sh, .github/workflows/package.yml, assets/src/components/editing/markdown_editor/markdown_util.ts, assets/src/data/content/model/elements/factories.ts, assets/test/data/content/factories_test.ts
There was a build issue causing resulting builds to be unusable. That issue was silently ignored by our current build process. This PR fixes both of those issues.
**Note:** The final step in testing this PR will be to merge to master and verify the resulting build actually works on tokamak.
=> [Chore] Build issue [MER-2543] 

assets/tsconfig.sdk.json
Fixes an issue resulting in failed builds of sdk-docs
=> [CHORE] Fix an issue where sdk-docs build was failing

assets/src/apps/authoring/components/Flowchart/rules/create-all-correct-workflow.ts, assets/src/apps/authoring/components/Flowchart/rules/create-cata-choice-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-multiple-choice-rules.ts, assets/src/apps/authoring/components/PropertyEditor/custom/AdvancedFeedbackNumberRange.tsx, assets/src/components/parts/janus-input-number/InputNumberAuthor.tsx, assets/src/components/parts/janus-input-text/InputTextAuthor.tsx, assets/src/components/parts/janus-multi-line-text/MultiLineTextInputAuthor.tsx, assets/styles/adaptive/flowchart.scss, assets/styles/adaptive/flowchart/popup.scss
Fixes four bugs related to the advanced author flowchart feature.
[MER-2542] Typo in "Greater" advanced feedback.
[MER-2538] Popup styling bugs
[MER-2537] Could not drag multi line text control
[MER-2513] Fixed empty answer on "always correct"
[MER-2542]: https://eliterate.atlassian.net/browse/MER-2542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-2538]: https://eliterate.atlassian.net/browse/MER-2538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-2537]: https://eliterate.atlassian.net/browse/MER-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-2513]: https://eliterate.atlassian.net/browse/MER-2513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> [BUGFIX] Flowchart feature bugfixes [MER-2542] [MER-2538] [MER-2537] [MER-2513] 

lib/oli_web/components/common.ex, lib/oli_web/components/delivery/scored_activities/scored_activities.ex, lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex, test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2571)
=> [BUGFIX][MER-2571] Fix error when assessment doesn't exist in scored activities tab

lib/oli/utils.ex, lib/oli_web/controllers/pow/registration_html/new.html.heex
[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2565)
=> [BUGFIX][MER-2565] Fix user's full name length

assets/src/apps/page-editor/PageEditor.tsx, assets/src/components/content/TitleBar.tsx, assets/src/components/messages/Banner.tsx, assets/src/components/resource/editors/ContentOutline.modules.scss
Fixes some issues uncovered when testing around the floating titlebar such as z-index, floating over top collaboration space and duplicate floating messages
=> [BUG FIX][MER-2613] floating titlebar z index bounds and sticky messages

lib/oli_web/live/resources/pages_view.ex
[Link](https://eliterate.atlassian.net/browse/MER-2642?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug,%20Story)%20AND%20status%20in%20(%22In%20Progress%22,%20PR,%20Ready,%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20priority%20DESC,%20status%20ASC,%20created%20DESC) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/dfe618c5-e860-49d2-834c-9970a6bbadf1
=> [MER-2642] Search box crashes on clear

.github/actions/torus-builder/action.yml, .github/workflows/build.yml, .github/workflows/package.yml, .github/workflows/torus-builder.yml, config/runtime.exs
Updates runtime config to only start https server in prod if cert paths are specified. Also separates out the torus-builder image build step, since caching didn't seem to be reliably working
=> [CHORE] update runtime config

.github/workflows/package.yml
Automatically package the nextgen-ux branch so that it can be deployed
=> [CHORE] add nextgen-ux branch to package CI

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .gitignore
This PR adds configuration for a devcontainer, allowing torus dev environment to be run in a container. This is useful for quickly reviewing PRs without having to clean the entire repo directory between branches with different deps and also running a dev environment in codespaces
=> [CHORE] add devcontainer configuration

lib/oli_web/components/delivery/content/content.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/live/delivery/instructor_dashboard/helpers.ex, test/oli_web/controllers/delivery_controller_test.exs, test/support/test_helpers.ex
[MER-2686](https://eliterate.atlassian.net/browse/MER-2686)
This PR fixes two issues in the 'Download CSV' feature in the Instructor and Student dashboards (only in the Content tab):
1. Unexpected `Loading...` value in the proficiency column.
2. Filter by units and modules not reflecting on the resulting CSV.
**Before changes:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/c6f19fa9-63a4-4d6f-944f-cfc65b305174
**After changes:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/b738fe11-eec9-4c0f-bf19-88f3f0089887
[MER-2686]: https://eliterate.atlassian.net/browse/MER-2686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-2686] Fix download CSV issues

test/oli_web/controllers/page_delivery_controller_test.exs, test/oli_web/live/delivery/open_and_free_index_test.exs
[MER-2691](https://eliterate.atlassian.net/browse/MER-2691)
Fix flaky tests on
- `test/oli_web/controllers/page_delivery_controller_test.exs:1267`
- `test/oli_web/live/delivery/open_and_free_index_test.exs:68`
[MER-2691]: https://eliterate.atlassian.net/browse/MER-2691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-2691] Fix flaky tests

lib/oli_web/live/resources/pages_view.ex
This PR handles the case where, from the "All Pages" view, an author uses the "Move to..." feature on a page that does not exist within the course hierarchy.  This is a primary use case of "Move to..." since authors can create pages in this view (and thus exist outside of the hierarchy) and then "move" them into the hierarchy at a later point. 
The root cause was the reliance on UUIDs mapped to hierarchy nodes, and `find_in_hierarchy` as well as a bad pattern match for `handle_event` for "MoveModal.move_item" variant.    This PR fixes this by providing a less constrained pattern match that only hits when the user attempts to move an unordered page (there is no `"from_uuid"` key present in that case).  This PR also tracks the most recent page which had its "Actions" menu invoked.  That is …
=> [BUG FIX] Handle unordered move

lib/oli/accounts.ex, lib/oli_web/controllers/pow/registration_html/new.html.heex, lib/oli_web/pow/messages.ex, lib/oli_web/pow/pow_helpers.ex, mix.exs, mix.lock, test/oli_web/pow/pow_test.exs
This pull request includes several modifications to the appearance of the login and register pages. Please refer to the description at: https://github.com/Simon-Initiative/oli-torus/issues/4222 for more details. Additionally, certain functions in 'pow_helpers' have been refactored.
=> Mer 2581 simplified presentation of direct delivery account creation

assets/src/apps/delivery/store/features/page/actions/loadInitialPageState.ts
Hey @bsparks, could you please look at it and approve it. Thanks.
=> [BUG] [MER-2678] | Refresh/Returning to an Advanced Page brings student to a different screen.

assets/src/components/parts/janus-capi-iframe/CapiIframeAuthor.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
Hey @bsparks Could you please look at this and approve it. Thanks!!
=> [ENHANCEMENT] [MER-2735] | Add a line in the Author for the TourIt group to iframe their product

assets/yarn.lock, lib/oli_web/live/curriculum/entries/actions.ex
Fixes the position of the container entry action menu
Before:
After:
=> [BUG FIX] fix action menu placement

assets/src/components/activities/directed-discussion/DirectedDiscussionAuthoring.tsx, assets/src/components/activities/directed-discussion/discussion/DirectedDiscussion.tsx, assets/src/components/activities/directed-discussion/discussion/DiscussionParticipationAuthoring.tsx, assets/src/components/activities/directed-discussion/discussion/DiscussionSearchResults.tsx
Fixes:
MER-2816 - DD Activity - Search button is sometimes hidden
MER-2817 - DD Activity - Hints not available for students
Also:
Fixed typo in "Participation" label.
Made post search case-insensitive
=> [BUG FIX] [MER-2816] [MER-2817] Directed Discussion Fixes

assets/src/components/activities/common/delivery/evaluation/Evaluation.tsx, assets/styles/common/elements.scss
Videos and youtube should now show up in feedback items correctly.
=> [BUG FIX] [MER-2783] Fixed videos in feedback messages

lib/oli/analytics/datashop/elements/event_descriptor.ex, lib/oli/analytics/summary/response_label.ex, lib/oli_web/components/delivery/practice_activities/practice_activities.ex, lib/oli_web/components/delivery/surveys/surveys.ex
This PR completes the missing backend support features for the response-multi activity.
=> [FIX][MER-2647] add missing backend support features for response-multi

assets/src/components/content/Popup.tsx
It was impossible to click on links in popups because the popup would close before you could get to the link with the cursor.
Now:
- The popup stays open for 1 second after mousing off the text anchor
- Mousing onto the popup keeps it open
=> Wait a second before closing a popup [MER-2777]

lib/oli/authoring/clone.ex, lib/oli/delivery/sections/blueprint.ex
[MER-2767](https://eliterate.atlassian.net/browse/MER-2767?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug%2C%20Story)%20AND%20status%20in%20(%22In%20Progress%22%2C%20PR%2C%20Ready%2C%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20assignee%20ASC%2C%20status%20ASC%2C%20priority%20DESC%2C%20created%20DESC)
This PR clones the products associated with the project that is being cloned
[MER-2767]: https://eliterate.atlassian.net/browse/MER-2767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MER-2767-Allow-Products-to-be-duplicated-when-a-course-project-is-cloned

assets/src/components/editing/SlateOrMarkdownEditor.tsx, assets/src/components/editing/elements/commands/commandFactories.ts, assets/src/components/editing/elements/commands/interfaces.ts, assets/src/components/editing/elements/heading/headingActions.tsx, assets/src/components/editing/elements/image/imageActions.tsx, assets/src/components/editing/elements/list/listActions.tsx, assets/src/components/editing/elements/paragraph/paragraphActions.tsx, assets/src/components/editing/elements/table/commands/insertTable.tsx, assets/src/components/editing/elements/youtube/YoutubeElement.tsx, assets/src/components/editing/toolbar/buttons/ButtonContent.tsx, assets/src/components/editing/toolbar/editorToolbar/EditorSettingsMenu.tsx, assets/src/components/editing/toolbar/editorToolbar/EditorToolbar.tsx, assets/src/components/editing/toolbar/editorToolbar/ListStyleToggle.tsx, assets/src/components/editing/toolbar/editorToolbar/UndoRedoToolbar.tsx, assets/src/components/editing/toolbar/editorToolbar/blocks/BlockInsertMenu.tsx
Makes 4 enhancements to the editor toolbar:
1. Adds tooltips to the top level icons
2. Adds an undo button
3. Adds a redo button
4. Moves the text-direction and markdown options from a dropdown menu into the top level toolbar.
=> Feature/toolbar enhancements [MER-2884 MER-2885 MER-2896 MER-2882]

assets/src/components/common/Tooltip.tsx, assets/src/components/resource/editors/ContentOutline.tsx
Small change to add tooltip to button.
=> [Feature] Adding tooltip to sidebar [MER-2886]

lib/oli/resources/page_browse.ex, lib/oli/resources/revision.ex, lib/oli_web/live/resources/pages_table_model.ex, lib/oli_web/live/resources/pages_view.ex
This PR adds an indicator for each page of whether or not the page is in the curriculum.
=> [FEATURE][MER-2889] All Pages View show whether or not pages are in curriculum

lib/oli_web/live/delivery/student/learn_live.ex, test/oli_web/live/delivery/student/learn_live_test.exs
[Link ](https://eliterate.atlassian.net/browse/NG23-54)to the ticket
=> [NG23-54] Add missing progress bar for learn view

lib/oli_web/live/delivery/student/lesson_live.ex, lib/oli_web/live/delivery/student/review_live.ex, lib/oli_web/live/delivery/student/utils.ex, lib/oli_web/router.ex, test/oli_web/live/delivery/student/lesson_live_test.exs, test/oli_web/live/delivery/student/review_live_test.exs
[NG23-42](https://eliterate.atlassian.net/browse/NG23-42)
This pull request adds and implements the new Review live view for the NG23 effort.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/e56a4156-c4fd-4b2f-bc28-970115a8e953
[NG23-42]: https://eliterate.atlassian.net/browse/NG23-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NG23-42] Lesson Review view

lib/oli/authoring/editing/container_editor.ex, lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/curriculum/container/container_live.html.heex
This PR implements the following UI improvement to the curriculum page.
=> [MER-2892] Improve curriculum page UI

assets/src/components/editing/elements/table/TableDropdownMenu.tsx, assets/src/components/editing/elements/table/table-util.ts
1. Modified the table menu so there are two columns, making it easier to access all the options.
2. Modified the delete-column and delete-row functionality to take into account the visually displayed grid instead of just the table structure.
Demo:
https://github.com/Simon-Initiative/oli-torus/assets/333265/c08d71a5-0125-446d-b779-9ded53654cab
=> [Bugfix] Deleting rows/columns improvement [MER-2500]

assets/src/apps/delivery/layouts/deck/DeckLayoutHeader.tsx
[Link](https://eliterate.atlassian.net/browse/NG23-61) to the ticket
The tooltip text was also fixed.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/2046e5b1-08c1-4787-97c2-e558dad75411
https://github.com/Simon-Initiative/oli-torus/assets/74839302/40eb3011-dc92-4df7-be88-f2bdf0d26926
=> [NG23-61] Fix back button to explorations for adaptive pages

lib/oli/accounts.ex, lib/oli/accounts/schemas/user.ex, lib/oli_web/live/users/user_detail_view.ex, test/oli_web/live/admin_live_test.exs, test/oli_web/live/users/user_detail_view_test.exs
Ticket: [MER-2843](https://eliterate.atlassian.net/browse/MER-2843).
This PR addresses the validation required to update an email from the admin view.
[MER-2843]: https://eliterate.atlassian.net/browse/MER-2843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [2843] Add changeset, function context and modify view to update user email data

lib/oli/delivery/sections/scheduling.ex, lib/oli/delivery/sections/section_resource.ex, lib/oli_web/components/delivery/schedule.ex, lib/oli_web/live/delivery/student/index_live.ex, lib/oli_web/live/delivery/student/schedule_live.ex
[NG23-63](https://eliterate.atlassian.net/browse/NG23-63)
Add links to pages in the Schedule and Index views for NG23.
[NG23-63]: https://eliterate.atlassian.net/browse/NG23-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NG23-63] Make page titles clickable in the course schedule view

lib/oli_web/live/delivery/student/learn_live.ex, lib/oli_web/live/delivery/student/lesson_live.ex
[Link](https://eliterate.atlassian.net/browse/NG23-69) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/89b3a8de-edbb-4894-9758-a12dbb785c5a
https://github.com/Simon-Initiative/oli-torus/assets/74839302/dad0271f-fe41-40b2-b9d1-75efb29079b6
https://github.com/Simon-Initiative/oli-torus/assets/74839302/81f7db71-cf90-4c86-989b-c3001ac1c40a
=> [NG23-69] Fix exploration pages navigation on learn page

lib/oli_web/templates/layout/app.html.eex
[MER-2761](https://eliterate.atlassian.net/browse/MER-2761) this pr remove sticky from flash messages 
[MER-2761]: https://eliterate.atlassian.net/browse/MER-2761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MER-2761-Sticky-flash-messages-look-wrong

lib/oli/delivery/sections.ex, test/oli_web/live/delivery/student_dashboard/course_content_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-2867?filter=10069&jql=labels%20%3D%20wyeworks%20ORDER%20BY%20resolution%20DESC,%20priority%20DESC,%20status%20ASC,%20created%20DESC) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/ae39d182-e531-40da-98a4-261da98776a1
=> [MER-2867] Student exception extended due date displays incorrectly 

lib/oli_web/live/datashop/table_model.ex
This PR adds a product column to the datashop export table.
=> [MER-2931] Add product column to datashop export table

lib/oli_web/components/delivery/scored_activities/scored_activities.ex
[MER-2994](https://eliterate.atlassian.net/browse/MER-2994)
This RP fixes bugs caused by displaying details of the results of `multi input` type activities. 
With these changes the details of each of the possible input types such as `Text`, `Numeric` or `Dropdown` are displayed correctly.
These changes were already implemented in the Surveys and Practice Activities tabs, and with this PR they are also implemented in the `Scored Activities` tab.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/3c358579-e9c8-46dd-bc0d-ee3b0c759a83
[MER-2994]: https://eliterate.atlassian.net/browse/MER-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-2994] Fix multi input activities in scored activities tab

assets/src/hooks/video_player.ts
[NG23-74](https://eliterate.atlassian.net/browse/NG23-74)
Before:
https://github.com/Simon-Initiative/oli-torus/assets/26532202/b1e04507-2868-41e3-8027-9f20f49fbbf4
After:
https://github.com/Simon-Initiative/oli-torus/assets/26532202/6874335f-3b24-44a4-9357-76691eb81d09
[NG23-74]: https://eliterate.atlassian.net/browse/NG23-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NG23-74] Remove YouTube suggestions at the end of the video

config/test.exs, lib/oli/open_ai/client.ex, lib/oli/search/embedding_worker.ex, lib/oli/search/embeddings.ex, lib/oli_web/live/projects/publish_view.ex, test/oli/search/embedding_worker_test.exs, test/oli/search/embeddings_test.exs, test/oli_web/live/publish_live_test.exs, test/support/factory.ex, test/support/test_helpers.ex
[Link](https://eliterate.atlassian.net/browse/NG23-18) to the ticket
=> [NG23-18] Embeddings Recalculation

assets/src/apps/authoring/components/AdaptivityEditor/ActionFeedbackEditor.tsx, lib/oli/publishing.ex, lib/oli_web/controllers/api/media_controller.ex, lib/oli_web/live/new_course/new_course.ex
This PR addresses an issue where, when logged in as a student and admin in the same browser and creating a course section as admin, the student is added as an instructor to the new course.
=> [MER-2356] student added as instructor

assets/src/components/parts/janus-text-flow/Markup.tsx
Hey @bsparks, could you please look at the PR and approve it. Thanks
=> [BUGFIX] [MER-3056] | Adaptive Page Link doesn't open in a new tab

lib/oli/analytics/by_activity.ex, lib/oli/analytics/by_objective.ex, lib/oli/analytics/by_page.ex, lib/oli/analytics/raw_analytics_export_worker.ex, lib/oli/publishing.ex, lib/oli/publishing/publications/publication.ex, lib/oli_web/live/common/multi_select.ex, lib/oli_web/live/common/multi_select_options.ex, lib/oli_web/live/insights/insights.ex, logfile, test/oli/delivery/analytics/analytics_test.exs
this pr [MER-2932](https://eliterate.atlassian.net/browse/MER-2932?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug%2C%20Story)%20AND%20status%20in%20(%22In%20Progress%22%2C%20PR%2C%20Ready%2C%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20assignee%20ASC%2C%20status%20ASC%2C%20priority%20DESC%2C%20created%20DESC) add two multiselect dropdowns, one to filter by sections an the other one to filter by products
[MER-2932]: https://eliterate.atlassian.net/browse/MER-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MER-2932]-filter-insights-by-product-course-section

assets/src/apps/authoring/components/AdaptiveRulesList/AdaptiveRuleContextMenu.tsx, assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx
Hey @bsparks, please review. Thanks!
=> [BUGFIX] [MER-3050] | Drop down menu for trap states gets cut off

lib/oli/delivery/sections.ex, lib/oli_web/live/delivery/student/learn_live.ex, test/oli_web/live/delivery/student/learn_live_test.exs
[NG23-52](https://eliterate.atlassian.net/browse/NG23-52)
Extend the Learn view to support sections and sub-sections.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/52dda07c-c7b4-42d5-b5ae-d6535f6e0b80
[NG23-52]: https://eliterate.atlassian.net/browse/NG23-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NG23-52] Add support to the Learn view for sections and sub sections

lib/oli/delivery/sections/post_processing.ex, lib/oli_web/components/delivery/layouts.ex, lib/oli_web/components/layouts/page.html.heex, lib/oli_web/components/layouts/student_delivery.html.heex, lib/oli_web/live/delivery/student/learn_live.ex, test/oli_web/live/delivery/student/learn_live_test.exs
[Link](https://eliterate.atlassian.net/browse/NG23-102) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/0319cca8-b257-493d-9c2b-d5de85d9252f
https://github.com/Simon-Initiative/oli-torus/assets/74839302/d706a8d9-5f63-48bd-b221-554920a5cf44
=> [NG23-102] Left navbar conditional links

lib/oli/delivery/sections.ex, lib/oli_web/live/delivery/student/learn_live.ex, test/oli_web/live/delivery/student/learn_live_test.exs
[Link](https://eliterate.atlassian.net/browse/NG23-51) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/659e4901-4a13-4597-8eb9-3ae2f1066c19
https://github.com/Simon-Initiative/oli-torus/assets/74839302/108cfa64-6625-4ff6-a2e2-4ca4171135b0
=> [NG23-51] Add support into Learn view for top level pages

assets/src/components/editing/toolbar/Toolbar.modules.scss, assets/src/components/editing/toolbar/buttons/CommandButton.tsx, assets/src/components/editing/toolbar/editorToolbar/UndoRedoToolbar.tsx
This PR enables or disables the undo or redo buttons to match the slate editor
=> [MER-2885]-[MER-2896] disable undo and redo

lib/oli/utils.ex, lib/oli_web/live/delivery/student/learn_live.ex, test/oli_web/live/delivery/student/learn_live_test.exs
[NG23-117](https://eliterate.atlassian.net/browse/NG23-117)
https://github.com/Simon-Initiative/oli-torus/assets/26532202/2141cf2d-9ef4-4754-ad54-eeca58bc56f0
[NG23-117]: https://eliterate.atlassian.net/browse/NG23-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NG23-117] Allow to show and hide completed pages within a module

lib/oli/authoring/course/project_attributes.ex, lib/oli_web/live/projects/overview_live.ex, lib/oli_web/live/projects/publish_view.ex, test/oli_web/live/projects/overview_live_test.exs, test/oli_web/live/publish_live_test.exs, test/support/factory.ex
[Link](https://eliterate.atlassian.net/browse/NG23-121) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/53f5e4fb-92d1-4f44-9752-ed7dbb43131e
=> [NG23-121] Add project setting to enable and disable embeddings calculation on publish

assets/src/hooks/point_markers.ts, lib/oli/resources/collaboration.ex, lib/oli_web/live/delivery/student/lesson/annotations.ex, lib/oli_web/live/delivery/student/lesson_live.ex
https://eliterate.atlassian.net/browse/NG23-82
Adds the capability for a student to reply to a Class Note
=> [FEATURE] [NG23-82] User replies to an existing note

assets/src/phoenix/activity_bridge.ts, lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex, lib/oli_web/controllers/api/attempt_controller.ex
[MER-3000](https://eliterate.atlassian.net/browse/MER-3000)
This PR aims to show an error message if a student would like to make an attempt at an activity that has already been submitted or evaluated.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/400e0287-28f3-4163-b124-c1ce22e38999
[MER-3000]: https://eliterate.atlassian.net/browse/MER-3000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX][MER-3000] Lost quiz answers second tab

.github/workflows/deploy.yml
Adds a new deployment target to GH actions menu for new staging server
=> [DEVOPS] add new deployment target

assets/src/components/parts/janus-slider/Slider.scss
Hey @bsparks , please look at this PR and approve it. Thanks
=> [BUGFIX] [MER-3143] | Simple Author Slider: Prompt text size too small

lib/oli_web/components/delivery/students/students.ex, test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs
this pr correct the sorting by last_interaction [MER-3001](https://eliterate.atlassian.net/browse/MER-3001) 
[MER-3001]: https://eliterate.atlassian.net/browse/MER-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-3001] Fix  incorrect sorting in student reports

lib/oli/analytics/by_activity.ex, lib/oli/analytics/by_objective.ex, lib/oli/analytics/by_page.ex, lib/oli/publishing/delivery_resolver.ex, lib/oli_web/live/insights/insights.ex, test/oli/delivery/analytics/analytics_test.exs
This pr [MER-2932](https://eliterate.atlassian.net/browse/MER-2932) correct the filter by section and product and solve the tab by page.
[MER-2932]: https://eliterate.atlassian.net/browse/MER-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENHANCEMENT] [MER-2932] Filter insights by product course section

lib/oli_web/controllers/delivery_controller.ex
This PR addresses an issue where, when linking an authoring account, the "Create and Link Account" option is used, the account will be created, and a user will be automatically created and logged in without requiring email authentication. The fix deletes the author login session for a newly created linked authoring account.
=> [BUG FIX] [MER-2370] create and link account doesn't require email confirmation until reauth

assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx, assets/styles/adaptive/flowchart/slider.scss
This also contains fix for [MER-3143 |  Simple Author Slider: Prompt text size too small](https://eliterate.atlassian.net/browse/MER-3143)
Hey @bsparks could you please look at this PR? Thanks
=> [BUG FIX] [MER-3144] Simple Author/Advanced Author: Changes in component panel lost

assets/src/apps/authoring/components/PropertyEditor/custom/TorusImageBrowser.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusVideoBrowser.tsx
Hey @darrensiegel , please look at this PR. The changes are in `TorusImageBrowser.tsx` and `TorusVideoBrowser.tsx` generic files.
**Before:**
**After:**
=> [BUG FIX] [MER-3145] Simple Author/Flowchart & Advanced Author: Add clickable link or button to upload/link image or video

assets/css/app.css, assets/src/hooks/index.ts, assets/src/hooks/toggle_read_more.ts, assets/tailwind.theme.js, lib/oli_web/components/delivery/student.ex, lib/oli_web/live/delivery/student/learn_live.ex, test/oli_web/live/delivery/student/learn_live_test.exs
[Link](https://eliterate.atlassian.net/browse/NG23-124) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/8c980625-68a3-4abf-889e-0b9f6ac7bbea
https://github.com/Simon-Initiative/oli-torus/assets/74839302/9ba63100-6a83-4b32-b9af-7a45c87f9466
=> [ENHANCEMENT] [NG23-124] Improve list of contents in a module

assets/src/apps/authoring/store/groups/layouts/deck/actions/addSequenceItem.ts
=> [BUG FIX] [MER-3157] Adding a new screen after a layer places the screen before the layer in Preview

lib/oli_web/live/experiments/experiments_live.ex, test/oli_web/live/experiments_live_test.exs
[MER-3095](https://eliterate.atlassian.net/browse/MER-3095)
This PR modifies the existing `Experiments` view to match the requirements specified in the ticket. 
[MER-3095]: https://eliterate.atlassian.net/browse/MER-3095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-3095] Create experiments page

assets/src/components/activities/logic_lab/LogicLabAuthoring.tsx, assets/src/components/activities/logic_lab/LogicLabDelivery.tsx, assets/src/components/activities/logic_lab/LogicLabModelSchema.tsx
Improves handling of unset environment variable.  It also removes the default url, thus requiring the environment variable to be set to use LogicLab.
Adds nice error message if the lab server is unreachable in the delivery context.
=> [BUG FIX] [MER-3201] LogicLab activity: adds improved error detection and handling of missing URL.  #4744 

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
=> [BUG FIX] [MER-3026] New Behavior in Advanced Pages: Sub screens return user to top of page

lib/oli_web/live/delivery/student/explorations_live.ex, test/oli_web/live/delivery/student/explorations_live_test.exs
[Link to the comment](https://eliterate.atlassian.net/browse/NG23-70?focusedCommentId=22653) in the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/bb21bdda-a494-47db-8a40-4ec3ba157884
https://github.com/Simon-Initiative/oli-torus/assets/74839302/d0ec9da2-b10e-4341-ac57-60c96e4beef0
=> [BUG FIX] [NG23-70] Link explorations to new learn page

priv/repo/migrations/20240503133916_disable_assistant_in_existing_sections.exs
[NG23-94](https://eliterate.atlassian.net/browse/NG23-94)
[NG23-94]: https://eliterate.atlassian.net/browse/NG23-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENHANCEMENT] [NG23-94] Turn off assistant for existing sections

lib/oli/delivery/attempts/core.ex, lib/oli/delivery/hierarchy.ex, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/schedule.ex, lib/oli_web/live/delivery/student/index_live.ex, lib/oli_web/live/delivery/student/learn_live.ex, test/oli/delivery/analytics/analytics_test.exs, test/oli/delivery/sections_test.exs, test/oli_web/live/delivery/student/index_live_test.exs
[NG23-136](https://eliterate.atlassian.net/browse/NG23-136)
This PR is the foundation for several improvements on the Home page of a course.
It includes:
- Display a hero banner that allows the student to easily start the course if he hasn't started, or continue an unfinished lesson.
- Display the student's progress in the course.
- Small improvements on the Upcoming Agenda.
This page will be updated with additional information as more PRs are made.
**NOTE**:
The course intro message that appears when the student first joins and visits the course, is stored in the `intro_content` field of the root container. However, this field can not be set on the author's side yet and needs to be implemented to customize the message.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/b58747ff …
=> [FEATURE] [NG23-136] Home page redesign

lib/oli_web/live/curriculum/container/container_live.ex, test/oli_web/live/curriculum/container_test.exs
This PR addresses [this](https://eliterate.atlassian.net/browse/NG23-105?focusedCommentId=22715) and [this](https://eliterate.atlassian.net/browse/NG23-106?focusedCommentId=22716) comment.
The bug was introduced with [this PR](https://github.com/Simon-Initiative/oli-torus/pull/4719), when the feature of setting an intro content for containers was developed.
The problem is that when we edit a container or a page, the backend shares the same "save-options" handle event. In the container case, an `intro_content` field is provided that gets parsed correctly. But in the page case, the form params do not contain the intro_content field, so the app crashes in the "save-options" handle_event when trying to parse a non-existent field.
The handle event was extended to support both containers and …
=> [BUG FIX] [NG23-105] Create input for poster image - part 2

assets/src/data/content/resource.ts, lib/oli/utils/purposes.ex
this pr [MER-3239](https://eliterate.atlassian.net/browse/MER-3239) add a new label to Group activities
[MER-3239]: https://eliterate.atlassian.net/browse/MER-3239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-3239] need-prior-knowledge-check-container-name-added-to-list

lib/oli_web/components/delivery/schedule.ex
[[NG23-182]](https://eliterate.atlassian.net/browse/NG23-182)
[NG23-182]: https://eliterate.atlassian.net/browse/NG23-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [NG23-182] Page icons merge conflict

lib/oli_web/live/delivery/student/discussions_live.ex, lib/oli_web/live/delivery/student/lesson/annotations.ex, lib/oli_web/live/delivery/student/lesson_live.ex, test/oli_web/live/delivery/student/lesson_live_test.exs
https://eliterate.atlassian.net/browse/NG23-166
Only show class notes in lesson view and discussion view when user is enrolled in a course as an instructor.
=> [FEATURE] [NG23-166] only show class notes to instructor

lib/oli_web/live/delivery/student/lesson/annotations.ex
Fixes an issue where the anonymous checkbox was not showing in class notes
=> [BUG FIX] [NG23-78] fix an issue where anonymous checkbox isn't showing in class notes

lib/oli_web/live/grades/gradebook_table_model.ex
[Link](https://eliterate.atlassian.net/browse/NG23-184) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/d81c5cc6-ba5f-4562-9fdb-d0c5d7930424
=> [BUG FIX] [NG23-184] Improve readability on quiz scores

assets/src/components/parts/janus-Carousel/Carousel.css, lib/oli_web/templates/layout/chromeless.html.heex
=> [BUG FIX] [MER-3140] Advanced Author Carousel Widget CSS

lib/oli_web/live/sections/edit_view.ex, test/oli_web/live/sections/edit_live_test.exs
Ticket: [MER-3252](https://eliterate.atlassian.net/browse/MER-3252)
This PR fixed a bug where editing a section as an instructor also altered the payment status to false. This happened because a field called `disabled` was being sent to the changeset, which tried to cast it as if it were part of the fields. To solve this, we now verify that only admins can perform this check whenever we call the changeset.
Note: I left a couple of asserts with `==` with the intention of emphasizing the comparison. For instance: `assert section.requires_payment == true`.
https://github.com/Simon-Initiative/oli-torus/assets/47334502/35c88580-8f38-4514-8de1-16e141fe0a04
https://github.com/Simon-Initiative/oli-torus/assets/47334502/b3bc25ac-8ef8-43b0-93a3-c915a355f7b6
[MER-3252]: …
=> [BUG FIX] [MER-3252] Fix bug when instructor edit a section and a side effect changes payment status

assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx, assets/src/apps/authoring/components/ComponentToolbar/UndoRedoToolbar.tsx, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx, assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx, assets/src/hooks/useKeyDown.tsx
Hey @bsparks, please look at the PR. Thanks
=> [FEATURE] [MER-3146] Advanced Author and Simple Author/Flowchart: Keyboard Shortcuts Request on Canvas

lib/oli_web/components/modal.ex, lib/oli_web/live/delivery/student/utils.ex, test/oli_web/live/delivery/student/lesson_live_test.exs
[Link](https://eliterate.atlassian.net/browse/NG23-157) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/44678ea7-01b0-461b-a368-0277bf4354e5
=> [FEATURE] [NG23-157] Learning proficiency explanation modal

assets/styles/adaptive/flowchart/text-flow.scss
Hey @bsparks  / @darrensiegel  please look at the PR. Thanks
=> [BUG FIX] [MER-3256] Simple Author: Matching editor to preview for Headers 4, 5, and Normal

assets/src/hooks/countdown.ts, assets/src/hooks/index.ts, assets/tailwind.theme.js, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/student.ex, lib/oli_web/live/delivery/student/home/components/schedule_component.ex, lib/oli_web/live/delivery/student/index_live.ex, lib/oli_web/live/delivery/student/utils.ex, test/oli/delivery/sections_test.exs, test/oli_web/live/delivery/student/index_live_test.exs, test/oli_web/live/delivery/student/utils_test.exs, test/support/factory.ex
[NG23-185](https://eliterate.atlassian.net/browse/NG23-185)
Add new "My Assignments" box in the student's Homepage (`/sections/{SECTION_SLUG}`)..
https://github.com/Simon-Initiative/oli-torus/assets/26532202/4ae6635e-442c-4f6b-bc38-6ba8cf8bd5bf
[NG23-185]: https://eliterate.atlassian.net/browse/NG23-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [NG23-185] My assignments in Homepage

assets/src/apps/delivery/layouts/deck/components/FeedbackContainer.tsx, assets/src/apps/delivery/layouts/deck/components/FeedbackRenderer.tsx
Hey @bsparks / @darrensiegel, could you please review the PR. Thanks
=> [BUG FIX] [MER-3230] Adaptive Page Feedback can't be read by screen reader

assets/src/apps/authoring/components/Flowchart/rules/create-multiple-choice-rules.ts
=> [BUG FIX] [MER-3288] Simple Author/Flow Chart: MCQ + "Incorrect:[specific response]" gives wrong feedback

lib/oli_web/live/new_course/new_course.ex
https://eliterate.atlassian.net/browse/NG23-205
Fixes an issue where course creation redirects instructor to student landing page after course creation. Also fixes the loading spinner which was not showing when creating section from LMS.
=> [BUG FIX] [NG23-205] Redirects to student interface after course creation

assets/src/apps/authoring/components/ComponentToolbar/UndoRedoToolbar.tsx, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx
Hey @bsparks could you please review it one last time :).
I thought `Cntrl + Shift +Z` is only for mac and it should not do anything for windows, but they requested it to work for both so making some changes and fixed an issue that broke for `cntrl/cmd + Z`
=> [BUG FIX] [MER-3146] Advanced Author and Simple Author/Flowchart: Keyboard Shortcuts Request on Canvas

lib/oli_web/live/experiments/experiments_live.ex, test/oli_web/live/experiments_live_test.exs
When an authoring user wants to create a new option for an experiment and that option already exists, do not allow and display an error message.
See: https://eliterate.atlassian.net/browse/MER-3101
=> [ENHANCEMENT] [MER-3101] Disallow duplicate options for experiments

assets/src/components/parts/janus-input-number/InputNumber.tsx, assets/src/components/parts/janus-input-number/InputNumberAuthor.tsx
Hey @bsparks / @darrensiegel please review the PR. Thanks.
=> [BUG FIX] [MER-3337] Hitting backspace in many places in adaptive pages causes delete popup

assets/src/components/content/add_resource_content/NonActivities.tsx
This PR updates the A/B menu item's tooltip.
=> [ENHANCEMENT] [MER-3106] Updates ab testing hover menu tip

lib/oli_web/live/grades/grades.ex
https://eliterate.atlassian.net/browse/MER-3125
This PR changes the "Update LMS Line Items" function to create and update graded line items in the order they appear in the hierarchy, and append all non-hierarchical pages to the end.
This is a stop-gap implementation in order to fix the issue short term of gradebook columns appearing in a seemingly random order. Other improvements to be made here in the future are:
1. Store the page ordering at the database level or in a reachability data structure so that the hierarchy doesn't need to be built in memory for pages to be sorted
2. Use a reachability data structure to properly sort non-hierarchical pages, instead of just appending them to the end
This was tested using a Canvas instance on the Chem course and behaved as expected, but it would …
=> [ENHANCEMENT] [MER-3125] sort line item creation by hierarchy ordering

assets/src/apps/authoring/components/AdaptivityEditor/ActionFeedbackEditor.tsx, assets/src/components/parts/janus-dropdown/DropdownAuthor.tsx
=> [BUG FIX] [MER-3255] Text in feedback not saving - Advanced Author

assets/src/apps/authoring/components/AdaptivityEditor/ActionFeedbackEditor.tsx, lib/oli/delivery/experiments.ex
Down merge master into prerelease v0.28
=> Down merge master into prerelease v0.28

lib/oli/delivery/metrics.ex, lib/oli_web/components/delivery/student.ex, test/oli/delivery/metrics/avg_score_test.exs, test/oli_web/live/delivery/student/learn_live_test.exs
Same PR as [this one](https://github.com/Simon-Initiative/oli-torus/pull/4883), but for prerelease v0.28
=> [BUG FIX] [NG23-174] Scoring inconsistency (for prerelease v0.28.0)

assets/src/apps/authoring/components/Flowchart/FlowchartComponent.tsx, assets/src/apps/authoring/components/Flowchart/FlowchartEditor.tsx, assets/src/apps/authoring/components/Flowchart/chart-components/ScreenNode.tsx
Hey @bsparks / @darrensiegel could you please look at the PR. Thanks
I am targeting it to V0.28 because we wants this to be part of version 0.28 release.
=> [BUG FIX] [MER-3038] Simplified Authoring Lesson - Page Unresponsive Error

lib/oli_web/components/footer.ex, lib/oli_web/templates/layout/email.html.eex
Cherry-picked bug fix from master (https://github.com/Simon-Initiative/oli-torus/pull/4898) to ensure the issue is resolved in v28.
=> [BUG FIX] [MER-3227] V28: Remove cookie preferences and version number in email footer

lib/oli_web/components/delivery/student.ex, lib/oli_web/live/delivery/student/utils.ex, test/oli_web/live/delivery/student/lesson_live_test.exs
[NG23-221](https://eliterate.atlassian.net/browse/NG23-221)
**Before:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/65b2b6a9-a4a1-4202-9111-7346b08f3219
**After:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/bbb1968e-62ad-4210-afd2-8cee5d1a8630
[NG23-221]: https://eliterate.atlassian.net/browse/NG23-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [NG23-221] Remove Duration Minutes if not set in Lesson View

lib/oli_web/components/delivery/surveys/surveys.ex
https://eliterate.atlassian.net/browse/NG23-258
This PR implements a stop-gap measure to restore functionality to the surveys view in the chemistry course. However, there is likely more rework that needs to be done here in order to get this view working for all courses in a performant way. Currently any survey with a large amount of data has the possibility of crashing the browser page and this fix does not necessarily account for all the different activity types.
We also will likely want to rework some of the patterns in this LiveView so that instead of tacking on data to the content or transformed model to generate the rendered views using this `Access.key!(:transformed_model)` pattern, we are creating a new struct or data structure to capture all the information needed to generate the …
=> [BUG FIX] [NG23-258] survey errors on stellarator server

assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx
Hey @bsparks , could you please look at the PR. Thanks
=> [BUG FIX] [MER-3420] Using keyboard shortcut (ctrl-v) to paste after a component has been copied causes issues

lib/oli_web/components/layouts/student_delivery_lesson.html.heex, lib/oli_web/live_session_plugs/init_page.ex, test/oli_web/live/delivery/student/lesson_live_test.exs, test/oli_web/live/delivery/student/prologue_live_test.exs
[Link](https://eliterate.atlassian.net/browse/NG23-264) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/cd0e45c0-0c76-49fd-85d6-0cda9a3db7d3
=> [BUG FIX] [NG23-264] Add back offline detector

lib/oli_web/live/delivery/student/lesson_live.ex, lib/oli_web/live/delivery/student/utils.ex, lib/oli_web/live_session_plugs/init_page.ex, test/oli_web/live/delivery/student/lesson_live_test.exs
[NG23-261](https://eliterate.atlassian.net/browse/NG23-261)
Add missing bibliography references to practice and graded page views.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/47478e0e-746e-4453-94dc-193369d20158
[NG23-261]: https://eliterate.atlassian.net/browse/NG23-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [NG23-261] Fix Pages References List

lib/oli_web/backgrounds.ex, lib/oli_web/components/footer.ex, lib/oli_web/controllers/pow/session_html.ex, lib/oli_web/controllers/pow/session_html/new.html.heex, lib/oli_web/icons.ex, lib/oli_web/pow/pow_helpers.ex, lib/oli_web/templates/layout/default.html.heex, test/oli_web/pow/pow_test.exs
[MER-3292](https://eliterate.atlassian.net/browse/MER-3292)
This PR implements changes to redesign the `Student` login view. 
Different backgrounds are applied depending on the environment in which the application is running.
Additionally, some adjustments are made to make the design as responsive as possible.
- Proton (default)
- Tokamak
- Stellarator
[MER-3292]: https://eliterate.atlassian.net/browse/MER-3292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-3292] Direct delivery student sign in

assets/src/components/activities/likert/LikertAuthoring.tsx
https://eliterate.atlassian.net/browse/MER-3434
Temporarily removes the likert visualization from the instructor surveys view. The current visualization doesn't make sense and causes confusion.
We will want to eventually follow this up with another ticket to reintroduce a better likert visualization, such as https://vega.github.io/vega-lite/examples/layer_likert.html
=> [BUG FIX] [MER-3434] Remove likert visualization from instructor surveys view

assets/src/hooks/countdown_timer.ts, assets/src/hooks/end_date_timer.ts, lib/oli_web/live/delivery/student/lesson_live.ex
[MER-3393](https://eliterate.atlassian.net/browse/MER-3393)
This PR adds checks necessary for the countdown on a graded page to work as expected. 
Necessary changes were made so that if the student exits the page and re-enters the page, the countdown or grace period status is maintained.
In addition, it adds the grace period time that is executed once the countdown of the set time limit for that page is over. 
Finally, we fix the bug that existed when the page was refreshed and the page submit was executed automatically.
[MER-3393]: https://eliterate.atlassian.net/browse/MER-3393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-3393] Time restricted assessments no longer work rework

lib/oli_web/live/curriculum/container/container_live.ex, lib/oli_web/live/curriculum/container/container_live.html.heex, lib/oli_web/live/curriculum/entries/options_modal.ex, lib/oli_web/live/delivery/student/utils.ex, lib/oli_web/live/resources/pages_table_model.ex, lib/oli_web/live/resources/pages_view.ex, lib/oli_web/live/sections/overview_view.ex
https://eliterate.atlassian.net/browse/MER-3380
Changes all references to "Graded" to scored outlined in this document https://docs.google.com/document/d/1ZnMnzFmmvyrPmMyzOjE8EANnd4p4SkYWZgO_EMOqJ7k/edit?usp=sharing
=> [ENHANCEMENT] [MER-3380] change all references from graded to scored

assets/src/apps/delivery/Delivery.tsx
Hey @bsparks  / @eliknebel  / @darrensiegel Could you please look at the PR? Thanks
=> [FEATURE] [MER-3523] Add "dark" mode to adaptive pages

.github/workflows/build.yml
Change `docker-compose` to `docker compose`
=> [BUG FIX] [MER-3300] Error in test runner: docker-compose command not found

lib/oli_web/live/grades/grades.ex
https://eliterate.atlassian.net/browse/MER-3566
Removes the grade pass back optimization to filter out students that are no longer enrolled in the LMS course.
=> [BUG FIX] [MER-3566] Grade Passback Bad Sync Issue

lib/oli/delivery/paywall.ex, lib/oli_web/components/layouts/student_delivery.html.heex, lib/oli_web/components/layouts/student_delivery_lesson.html.heex, lib/oli_web/live/sections/paywall_settings.ex, lib/oli_web/live_session_plugs/set_paywall_summary.ex, lib/oli_web/router.ex, test/oli/delivery/paywall_test.exs, test/oli_web/controllers/api/payment_controller_test.exs, test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs, test/oli_web/live/delivery/student/index_live_test.exs, test/oli_web/live/delivery/student/learn_live_test.exs, test/oli_web/live/delivery/student/lesson_live_test.exs, test/oli_web/live/delivery/student/utils_test.exs, test/oli_web/live/payments_live_test.exs, test/oli_web/live/products_test.exs, test/oli_web/live/users/user_detail_view_test.exs, test/support/test_helpers.ex
[Link](https://eliterate.atlassian.net/browse/MER-3572) to the ticket
https://github.com/user-attachments/assets/f858fa56-a074-40bb-935b-5b86578b23f0
=> [BUG FIX] [MER-3572] Delivery student grace period pay banner

lib/oli/delivery/metrics.ex, lib/oli/delivery/sections.ex, lib/oli_web/components/delivery/students/students.ex, test/oli/analytics/summary/metrics_v2_test.exs, test/oli/delivery/metrics/learning_proficiency_test.exs, test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs
https://eliterate.atlassian.net/browse/MER-3573
This PR adjusts the way proficiency is calculated by requiring a minimum of 3 total number of first attempts before showing a proficiency or either "Low", "Medium", or "High" and otherwise returning "Not enough data".
=> [BUG FIX] [MER-3573] torus learning proficiency algorithm leads to undesired results

assets/src/components/parts/janus-dropdown/DropdownAuthor.tsx
Hey @bsparks  / @eliknebel  / @darrensiegel  please look at the PR. Thanks.
=> [BUG FIX] [MER-3284] Simple Author/Flowchart: Can't click on dropdown bar when moving dropdown component

lib/oli_web/backgrounds.ex
Link to [the comment](https://eliterate.atlassian.net/browse/MER-3304?focusedCommentId=23938) in the ticket
=> [BUG FIX] [MER-3304] Adjust course author sign in background for light mode

lib/oli_web/live/sections/paywall_settings.ex, lib/oli_web/views/layout_view.ex, test/oli_web/live/delivery/student/index_live_test.exs, test/oli_web/live/delivery/student/learn_live_test.exs, test/oli_web/live/delivery/student/lesson_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-3587) to the ticket
=> [ENHANCEMENT] [MER-3587] Fix spelling and grammatical errors

lib/oli/interop/export.ex, test/oli/interop/export.exs
Apply fixes from https://github.com/Simon-Initiative/oli-torus/pull/4902 to `hotfix-v0.28.3` branch
=> [BUG FIX] [MER-3626] Fix exporting project breaking if revision is nil

lib/oli_web/backgrounds.ex, lib/oli_web/live/workspace/instructor.ex
This PR addresses [this comment](https://eliterate.atlassian.net/browse/MER-3298?focusedCommentId=23889).
https://github.com/user-attachments/assets/f27dd25b-0d9b-4ebd-a6ea-cfabf58582ee
https://github.com/user-attachments/assets/fc7995a7-b49a-443a-857d-091ddd95d825
=> [ENHANCEMENT] [MER-3298] Workspace nav bar and new instructor dashboard - part 3

assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/delivery/Delivery.tsx
This PR also contains fix for [Add "dark" mode to adaptive pages ](https://eliterate.atlassian.net/browse/MER-3523)
Hey @bsparks / @eliknebel  / @darrensiegel please look at the PR.
=> [BUG FIX] [MER-3500] When editing feedback if a component is selected when using the backspace on the keyboard it will try to delete the component

lib/oli/delivery/page/page_context.ex, lib/oli_web/live/delivery/student/lesson_live.ex, lib/oli_web/live_session_plugs/init_page.ex
Same PR as [this one](https://github.com/Simon-Initiative/oli-torus/pull/5040), but targeted to hotfix v0.28.4
=> [BUG FIX] [MER-3670] Every page is loaded twice - for hotfix v0.28.4

lib/oli_web/live/delivery/student/lesson_live.ex
[Link](https://eliterate.atlassian.net/browse/MER-3671) to the ticket
https://github.com/user-attachments/assets/ef95dbde-f7c9-4ffb-b7a9-70ae424fcb6f
https://github.com/user-attachments/assets/910026ee-5d79-41ca-88d9-eca0e3e3409d
=> [BUG FIX] [MER-3671] Adaptive page styles broken after lesson publishing

lib/oli_web/controllers/activity_bank_controller.ex
Ticket: [MER-3673](https://eliterate.atlassian.net/browse/MER-3673)
This PR adds missing keys to the preview function in the ActivityBankController. Without these keys, the layout could not find the required values, resulting in a page crash.
https://github.com/user-attachments/assets/982570a8-a231-47e3-9eb1-86311c32f6e9
@eliknebel Please note that the pagination section behaves oddly, as it's possible to click on the arrows even though they should be disabled. I think we need to open a ticket for that.
[MER-3673]: https://eliterate.atlassian.net/browse/MER-3673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-3673] Add missing keys to activity bank preview

lib/oli/delivery/experiments.ex, lib/oli/delivery/experiments/log_worker.ex, lib/oli/delivery/snapshots/worker.ex
This PR handles the three highest reporting AppSignal errors, listed in the MER ticket.
=> [BUG FIX] [MER-3683] Address appsignal errors

lib/oli_web/live/delivery/student/utils.ex
Disregard the number of activities, always show "Reset Answers"
=> [BUG FIX] [MER-3753] Always show reset

lib/oli_web/live/workspaces/utils.ex
Ticket: [MER-3299](https://eliterate.atlassian.net/browse/MER-3299)
This PR fixes the colors used in the submenu mentioned in [this](https://eliterate.atlassian.net/browse/MER-3299?focusedCommentId=24041) comment.
[MER-3299]: https://eliterate.atlassian.net/browse/MER-3299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-3299] Adjust submenu colors for selected and hovered states

lib/oli/delivery/sections.ex, test/oli/delivery/sections_test.exs, test/oli_web/live/workspace/course_author/bibliography_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-3785) to the ticket
Latest enrolled course is listed first
https://github.com/user-attachments/assets/3d3329a9-113e-4f44-acaa-8f97cb61472b
Latest created course is listed first
https://github.com/user-attachments/assets/c4fd67b4-7f05-4b09-b923-1174a3717f77
=> [FEATURE] [MER-3785] Extend instructor dashboard query

priv/repo/migrations/20240917111312_add_lifecycle_index.exs
Adds a partial index on `:lifecycle_state` for the values `"submitted"`
=> [PERFORMANCE] [MER-3820] Speed up manual scoring queries

assets/src/apps/authoring/components/Flowchart/onboard-wizard/OnboardWizard.tsx, assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts, assets/src/apps/authoring/components/PropertyEditor/schemas/part.ts, assets/src/apps/delivery/Delivery.tsx, assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx, assets/src/components/parts/janus-capi-iframe/schema.ts, assets/src/components/parts/janus-text-flow/schema.ts
Hey @bsparks could you please look at this PR. Thanks
This PR contains the changes for the following tickets:
1. [Edit wording for Simple vs Advanced Author selection](https://eliterate.atlassian.net/browse/MER-3746)
2. [Add Aira Label/Description on iframes](https://eliterate.atlassian.net/browse/MER-3737)
3. [Simple Author/Flowchart Tool: Text component border radius/border width error while changing number](https://eliterate.atlassian.net/browse/MER-3370)
4. [Add Warning Popup for Adaptive Page Refreshes](https://eliterate.atlassian.net/browse/MER-3816)
=> [BUG FIX] [MER-3370] Simple Author/Flowchart Tool: Text component border radius/border width error while changing number

assets/src/components/parts/janus-text-flow/Markup.tsx, assets/src/components/parts/janus-text-flow/QuillEditor.tsx, assets/src/components/parts/janus-text-flow/QuillImageUploader.tsx, assets/src/components/parts/janus-text-flow/TextFlow.tsx, assets/src/components/parts/janus-text-flow/quill-utils.ts
Hey @bsparks, please look at the PR. Thanks
=> [FEATURE] [MER-3736] Add Alt Text field for images in MCQs

lib/oli_web/live/products/details/image_upload.ex, lib/oli_web/live/sections/details/image_upload.ex, lib/oli_web/live/sections/overview_view.ex
This PR supports changing the section cover image in the course section's delivery interface.
=> [FEATURE] [MER-3703] Add cover image editing at the section level

lib/oli_web/components/layouts/workspace.html.heex, lib/oli_web/components/project/async_exporter.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/live/workspaces/course_author/overview_live.ex, lib/oli_web/live/workspaces/course_author/overview_table_model.ex, lib/oli_web/live/workspaces/instructor/index_live.ex
[MER-3778](https://eliterate.atlassian.net/browse/MER-3778)
This PR aims to adjust the color of some texts which were being incorrect. 
The fixes are for both light and dark mode, including the hover effect of them. 
- All Projects and Project Overview
https://github.com/user-attachments/assets/ecf40e93-42a5-4c49-a768-6686ea329e74
- Course Section Manage
https://github.com/user-attachments/assets/54b7742a-64d8-4e13-bdf8-f2051ae953d5
- Instructor Workspace
https://github.com/user-attachments/assets/eae61258-5c00-4ac5-a1d5-bde1d1cdca04
[MER-3778]: https://eliterate.atlassian.net/browse/MER-3778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-3778] Fix dark mode texts contrast

lib/oli_web/live/delivery/student/lesson/components/one_at_a_time_question.ex
[Link to the comments](https://eliterate.atlassian.net/browse/MER-3640?focusedCommentId=24482) in the ticket
https://github.com/user-attachments/assets/3252d2ca-22cf-4872-aaf1-368bd0815467
=> [FEATURE] [MER-3640] Additional UX - part 2

assets/src/apps/authoring/components/ScreenList/AddScreenModal.tsx, assets/styles/authoring/addscreenmodal.scss, assets/styles/authoring/advanced-authoring.scss
Hey @bsparks could you please look at this PR. Thanks
=> [ENHANCEMENT] [MER-3417] Make it more intuitive to name screens in simple author/flowchart tool

assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx, assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx, assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx, assets/src/apps/authoring/store/app/slice.ts
=> [FEATAURE] [MER-3414] Update locations of new components added to adaptive pages

assets/src/apps/authoring/store/activities/actions/saveActivity.ts
=> [BUG FIX] [MER-3369] Simple Author/Flowchart: Selecting undo, redo, undo kicks user out of editing screen

lib/oli_web/components/layouts/workspace.html.heex, lib/oli_web/components/project/overview.ex, lib/oli_web/live/workspaces/course_author/overview_live.ex, lib/oli_web/live/workspaces/course_author/pages_live.ex, lib/oli_web/live/workspaces/utils.ex, test/oli_web/live/workspaces/course_author_test.exs
Ticket: [MER-3865](https://eliterate.atlassian.net/browse/MER-3865)
This PR setup the spacing over the resource content.
On the left, the banner (with a pink background) extends fully to both the top-left and top-right corners. On the right, there are gaps in those areas.
[MER-3865]: https://eliterate.atlassian.net/browse/MER-3865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENHANCEMENT] [MER-3865] UX UI improvements to new tokamak UI

assets/css/app.css, lib/oli_web/components/delivery/layouts.ex, lib/oli_web/live/workspaces/utils.ex
[Link](https://eliterate.atlassian.net/browse/MER-3864) to the ticket
This PR fixes the scrollbar issue on some browsers and OS, and focuses the scrolling to the submenu items (instead of all the sidebar)
=> [BUG FIX] [MER-3864] Hide scrollbar + allow scrolling on submenu

lib/oli_web/pow/user_context.ex
Note: **Do not squash**. Select "Merge Commit" when merging
=> [CHORE] [MER-0000] Integrate v0.28.11

lib/oli_web/components/common.ex, lib/oli_web/live/common/sortable_table/table_handlers.ex, lib/oli_web/live/curriculum/container/container_live.html.heex, lib/oli_web/live/curriculum/entries/actions.ex, lib/oli_web/live/objectives/listing.ex, lib/oli_web/live/objectives/objectives.ex, lib/oli_web/live/workspaces/course_author/curriculum_live.html.heex, lib/oli_web/live/workspaces/course_author/objectives/listing.ex, lib/oli_web/live/workspaces/course_author/objectives_live.ex, lib/oli_web/live/workspaces/utils.ex, lib/oli_web/live_session_plugs/assign_active_menu.ex, test/oli_web/live/objectives_live_test.exs, test/oli_web/live/workspaces/course_author/objectives_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-3870) to the ticket
This PR also addresses ticket [MER-3871](https://eliterate.atlassian.net/browse/MER-3871) and other minor bugs found.
https://github.com/user-attachments/assets/8686fa39-7327-4bfe-951a-d34f67292446
[MER-3871]: https://eliterate.atlassian.net/browse/MER-3871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-3870] Reveal workspace sub items on hover

assets/src/apps/authoring/components/AdaptivityEditor/ConditionItemEditor.tsx, assets/src/apps/authoring/components/AdaptivityEditor/ConditionsBlockEditor.tsx
Hey @bsparks, could you please look at the PR. Thanks
=> [BUG FIX] [MER-3585] Deleting group condition in Advanced Author causes error

assets/src/apps/authoring/components/Flowchart/rules/create-cata-choice-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-dropdown-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-multiple-choice-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-number-input-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-slider-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-text-input-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-three-try-workflow.ts, assets/src/apps/authoring/components/PropertyEditor/schemas/screen.ts
[Link](https://eliterate.atlassian.net/browse/MER-3881) to the ticket
This reverts commit 377128946939abef23bda6d7e59726905c1cf623.
=> [FEATURE] [MER-3881] Revert MER-3415

assets/styles/authoring/layout/workspace.scss, lib/oli_web/common/breadcrumb.ex, lib/oli_web/common/links.ex, lib/oli_web/components/delivery/layouts.ex, lib/oli_web/components/layouts/workspace.html.heex, lib/oli_web/live/breadcrumb/breadcrumb_trail_workspace_live.ex, lib/oli_web/live/breadcrumb/breadcrumb_workspace_live.ex, lib/oli_web/live/workspaces/course_author/curriculum/entry.ex, lib/oli_web/live/workspaces/course_author/curriculum_live.ex, lib/oli_web/live/workspaces/course_author/curriculum_live.html.heex, test/oli_web/live/workspaces/instructor_test.exs
Ticket: [MER-3876](https://eliterate.atlassian.net/browse/MER-3876)
This PR added breadcrumbs to Curriculum.
https://github.com/user-attachments/assets/ef632606-9417-4d82-8e8f-22a256ca72bc
[MER-3876]: https://eliterate.atlassian.net/browse/MER-3876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-3876] Add breadcrumbs to Curriculum

lib/oli_web/controllers/pow/session_html/new.html.heex, lib/oli_web/controllers/project_plugs.ex, lib/oli_web/plugs/authorize_project.ex, lib/oli_web/plugs/community_admin.ex, lib/oli_web/pow/author_routes.ex, test/oli_web/live/collaboration_live_test.exs, test/oli_web/live/community_live_test.exs, test/oli_web/live/history/revision_history_test.exs, test/oli_web/live/insights/insights_test.exs, test/oli_web/live/objectives_live_test.exs, test/oli_web/live/payments_live_test.exs, test/oli_web/live/publish_live_test.exs, test/oli_web/live/resources/alternatives_editor_test.exs, test/oli_web/pow/pow_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-3887) to the ticket
https://github.com/user-attachments/assets/7ba5633c-a97b-430f-b9cd-d59c7dc3d432
https://github.com/user-attachments/assets/846d5a0c-e7f7-4dad-95fd-5a89b49f4f31
=> [BUG FIX] [MER-3887] Take author to new workspace after login

assets/src/apps/authoring/components/Flowchart/onboard-wizard/LeftArrow.tsx, assets/src/apps/authoring/components/Flowchart/onboard-wizard/OnboardWizard.tsx, assets/src/apps/authoring/components/Flowchart/onboard-wizard/RightArrow.tsx, assets/styles/authoring/onboard-wizard.scss
[MER-3416](https://eliterate.atlassian.net/browse/MER-3416)
https://github.com/user-attachments/assets/013ae537-4429-4f80-a57a-bfc268ad2b9a
[MER-3416]: https://eliterate.atlassian.net/browse/MER-3416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENHANCEMENT] [MER-3416] Make it more intuitive to name adaptive pages

assets/src/apps/authoring/components/Flowchart/flowchart-actions/add-screen.ts, assets/src/apps/authoring/components/Flowchart/flowchart-actions/verify-flowchart-lesson.ts, assets/src/apps/authoring/components/Flowchart/rules/create-cata-choice-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-dropdown-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-multiple-choice-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-number-input-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-slider-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-text-input-rules.ts, assets/src/apps/authoring/components/Flowchart/rules/create-three-try-workflow.ts, assets/src/apps/authoring/components/PropertyEditor/schemas/screen.ts
Hey @bsparks could you please look at this PR? Thanks
FYI - I already created a PR for the same ticket https://github.com/Simon-Initiative/oli-torus/pull/5157 which was already approved and merged into the Maon branch. However, due to 1 follow-up issue related to special handling of max attempt = 1, we reverted back these changes from Main branch because we had code freeze for v29.
=> [FEATURE] [MER-3415] Changing number of attempts available in simple author/flowchart tool

lib/oli_web/live/products/products_table_model.ex, lib/oli_web/live/products/products_view.ex
See: https://eliterate.atlassian.net/browse/MER-3539
=> [BUG FIX] [MER-3539] Fix incorrect sorting of products by required payment amount

lib/oli_web/controllers/pow.ex, lib/oli_web/live/users/author_detail_view.ex, lib/oli_web/live/users/user_actions.ex, lib/oli_web/live/users/user_detail_view.ex, test/oli_web/live/users/author_detail_view_test.exs, test/oli_web/live/users/user_detail_view_test.exs, test/oli_web/pow/pow_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-3921) to the ticket
https://github.com/user-attachments/assets/a37adddc-3c76-4ea1-9b2a-39e9fea5423b
This PR also fixes the password reset link generator for an author (the page was crashing when clicking on "Generate")
https://github.com/user-attachments/assets/b59a88ef-3a80-4352-ab61-7e98db581e9a
https://github.com/user-attachments/assets/5ee42ee8-5d84-4715-abf0-af9f9e140693
=> [BUG FIX] [MER-3921] Send reset password email

lib/oli_web/plugs/header_size_logger.ex
https://eliterate.atlassian.net/browse/MER-3942
An issue was encountered during a deployment of a PR that uses `Application.compile_env`. This fix opts to use Application.get_env` in a function call instead.
Tested by deploying to tokamak and fixes the issue
=> [BUG FIX] [MER-3942] Deployment error from runtime/compile time config mismatch

assets/src/apps/authoring/components/Flowchart/rules/create-three-try-workflow.ts
=> [BUG FIX] [MER-3415] Changing number of attempts available in simple author/flowchart tool

assets/src/apps/authoring/components/ScreenList/AddScreenModal.tsx, assets/src/apps/authoring/components/ScreenList/ScreenList.tsx
=> [BUG FIX] [MER-3906] Clicking backspace causes the Delete Component modal to pop up

assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx, assets/src/components/parts/janus-image/ImageAuthor.tsx, assets/src/components/parts/janus-image/authoring-entry.ts, assets/src/components/parts/janus-image/schema.ts
Hey Ben, could you please look at the PR. Thanks
=> [FEATURE] [MER-3412] Image component has fixed aspect ratio based on image dimensions

assets/src/components/parts/janus-multi-line-text/schema.ts
Hey @bsparks please review the PR. Thanks
=> [BUG FIX] [MER-3915] Simple Author - Multiline Text Input - Font Size setting should be removed

assets/src/components/activities/common/delivery/evaluation/Submission.tsx
[MER-3938](https://eliterate.atlassian.net/browse/MER-3938)
[MER-3938]: https://eliterate.atlassian.net/browse/MER-3938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENHANCEMENT] [MER-3938] Replace submission text

lib/oli/delivery/paywall.ex, lib/oli/delivery/paywall/payment.ex, lib/oli_web/components/delivery/actions/actions.ex, lib/oli_web/components/delivery/actions/transfer_enrollment.ex, priv/repo/migrations/20241021182426_add_invalidated_by_user_id.exs, test/oli/delivery/paywall_test.exs, test/oli_web/live/delivery/student_dashboard/components/actions_tab_test.exs, test/support/factory.ex
[Link](https://eliterate.atlassian.net/browse/MER-3905) to the ticket
https://github.com/user-attachments/assets/c53330bc-4bd0-4eb9-835b-d8aab0672bdf
=> [FEATURE] [MER-3905] Admin manage student payment status from paid to unpaid

assets/src/components/parts/janus-image/ImageAuthor.tsx
Hey @bsparks, could you please look at this PR. Thanks
=> [BUG FIX] [MER-3412] Image component has fixed aspect ratio based on image dimensions

assets/src/apps/authoring/components/PropertyEditor/custom/ColorPickerWidget.tsx, assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx, assets/src/components/activities/adaptive/AdaptiveAuthoring.scss, assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx
Hey @bsparks could you please look at the PR.Thanks
https://github.com/user-attachments/assets/20cf4548-17fa-4d4b-8c7a-708bbce70953
=> [BUG FIX] [MER-3966] Color Picker Modal Usability Issue

assets/src/components/activities/image_hotspot/ImageHotspotDelivery.tsx
The image hotspot activity was showing a submit/reset button to submit an answer after selection and reset after submission. For single-selection hotspot questions, this is inconsistent with the behavior on other torus questions like multiple choice questions, which auto-submit immediately on choice selection on practice pages, and allow selecting a new choice to automatically reset and submit. This changes single-selection hotspots to autosubmit on selection in non-graded/non-survey contexts as multiple choice questions do.
This also includes a tweak to disable the hotspot selection on reviewing scored pages. 
Multiple selection hotspots behave like CATA questions. These require a submit button to show when selection is complete. So these are unchanged.
=> [ENHANCEMENT] [MER-3850] make single-selection hotspot autosubmit like MCQ

assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts, assets/src/apps/delivery/Delivery.tsx
=> [ENHANCEMENT] [MER-4014] Add Dark Mode Toggle Option for Adaptive Pages in Lesson Panel

assets/src/apps/authoring/components/Flowchart/onboard-wizard/OnboardWizard.tsx, assets/styles/authoring/onboard-wizard.scss
Hey @gastonabella, can you please review this one.
The CSS changes done for the ticket [MER-3416](https://eliterate.atlassian.net/browse/MER-3416) in [PR](https://github.com/Simon-Initiative/oli-torus/pull/5184) were causing some alignment issues at Step 3 so I just made sure that the CSS gets applied to Step 1 only.
**_After changes_**
https://github.com/user-attachments/assets/6497cfa5-fed2-4e7c-afdb-3021ef4baa6a
[MER-3416]: https://eliterate.atlassian.net/browse/MER-3416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-3958] Formatting issue when creating an Advanced author lesson

lib/oli_web/live/delivery/student/index_live.ex, lib/oli_web/live/delivery/student/utils.ex, test/oli_web/live/delivery/student/index_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-3970) to the ticket
https://github.com/user-attachments/assets/c0c5c33f-05ac-4f6a-a92e-bd7f806e2482
=> [FEATURE] [MER-3970] Add my assignments link to my assignments component

assets/src/apps/authoring/components/AdaptivityEditor/VariablePicker.tsx, assets/src/components/parts/janus-capi-iframe/CapiIframeAuthor.tsx, assets/src/components/parts/janus-capi-iframe/CapiVariablePicker.scss, assets/src/components/parts/janus-capi-iframe/CapiVariablePicker.tsx
Hey @bsparks, could you please look at the PR. Thanks
https://github.com/user-attachments/assets/51368d10-01bf-441b-9212-68c2b9f6768e
https://github.com/user-attachments/assets/12b735d0-2103-412c-bf60-cadeae30c9eb
=> [ENHANCEMENT] [MER-3991] Display Nested CAPI Properties in Rule Editor and Config Modal

lib/oli_web/live/admin/admin_view.ex, lib/oli_web/live/collaboration_live/index_view.ex, lib/oli_web/live/sections/overview_view.ex, lib/oli_web/router.ex, test/oli_web/live/admin_live_test.exs, test/oli_web/live/collaboration_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-3961) to the ticket
https://github.com/user-attachments/assets/330da72e-0d80-424a-9512-7dd7008342b1
=> [FEATURE] [MER-3961] Remove Admin `Browse collab spaces`

lib/oli_web/live/delivery/student/prologue_live.ex, lib/oli_web/live/delivery/student/review_live.ex, lib/oli_web/live/delivery/student/utils.ex, test/oli_web/live/delivery/student/prologue_live_test.exs, test/oli_web/live/delivery/student/utils_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4016) to the ticket
https://github.com/user-attachments/assets/2a86cde9-074b-4bdb-9e51-14569eb395d5
=> [FEATURE] [MER-4016] Add more parameters to assignment launch page

assets/src/apps/authoring/components/ScreenList/ScreenList.tsx, assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx
=> [BUG FIX] [MER-4051] Delete Component window pops up with backspace

lib/oli_web/live/delivery/student/lesson/components/outline_component.ex, test/oli_web/live/delivery/student/lesson/components/outline_component_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4091) to the ticket
https://github.com/user-attachments/assets/915106cd-32fc-4861-870c-c4d653adb96a
co-authored: @simonchoxx @gastonabella 🤒
=> [BUG FIX] [MER-4091] Fix course navigation sidebar

lib/oli_web/live/delivery/student/utils.ex, test/oli_web/live/delivery/student/prologue_live_test.exs
Ticket: [MER-4105](https://eliterate.atlassian.net/browse/MER-4105)
This PR removed any reference to autosubmit on assessment terms displayed to student.
This PR also apply the appropriate format to display time limit.
[MER-4105]: https://eliterate.atlassian.net/browse/MER-4105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-4105] Remove any reference to autosubmit on assessment terms displayed to student

assets/src/apps/authoring/components/PropertyEditor/custom/TorusImageBrowser.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/TorusMediaBrowserWrapper.tsx, assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx, assets/src/components/activities/adaptive/AdaptiveAuthoring.scss, assets/src/components/parts/janus-Carousel/CarouselAuthor.tsx, assets/src/components/parts/janus-Carousel/schema.ts
=> [ENHANCEMENT] [MER-3989] Updates to advanced author image carousel

assets/src/apps/delivery/layouts/deck/RestartLessonDialog.tsx, assets/src/apps/delivery/layouts/deck/components/HistoryNavigation.tsx, assets/src/apps/delivery/layouts/deck/components/OptionsPanel.tsx
=> [ENHANCEMENT] [MER-4019] Update "Restart Lesson" Button Text for Scored Assignments in Student Mode

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts, assets/src/apps/delivery/store/features/groups/actions/deck.ts
Hey @bsparks, could you please look at the PR. Thanks.
Ticket#->  [MER-4117](https://eliterate.atlassian.net/browse/MER-4117)
**Root Cause:**
It appears that the server is now preventing the client from creating more attempts than the maximum allowed, as defined in the activity configuration, which is the correct behavior. For example, if an activity has a maximum attempt limit of 5, the server returns an error when the client tries to create a 6th attempt. This results in an undefined value being assigned to the attempt variable in the triggercheck.tsx page, causing the student to become stuck on the screen.
**Note:** I believe this issue has always existed, but it only became apparent now because the server has started enforcing the restriction.
**Use Case:**
Activity A has max attempt …
=> [BUG FIX] [MER-4117] Infinite loading and errors thrown on adaptive pages

assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx, assets/src/apps/authoring/components/Modal/ShowInformationModal.tsx
=> [BUG FIX] [MER-4109] Able to add more than one question component per screen using copy/paste Standard Author (Argos Stage).

lib/oli_web/live/delivery/student/utils.ex, test/oli_web/live/delivery/student/prologue_live_test.exs
[MER-4118](https://eliterate.atlassian.net/browse/MER-4118)
https://github.com/user-attachments/assets/a4a7ff09-cf2d-476a-8ef8-e156a35387ae
[MER-4118]: https://eliterate.atlassian.net/browse/MER-4118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-4118] Improve Student Assessment Submit Terms

assets/src/apps/authoring/components/PropertyEditor/custom/DropdownOptionsEditor.tsx
The issues reported related to Image component was already fixed in -> https://github.com/Simon-Initiative/oli-torus/pull/5296
=> [BUG FIX] [MER-4116] Delete Component Window Pop-up

assets/src/apps/authoring/components/PropertyEditor/custom/AdvancedFeedbackNumberRange.tsx
=> [BUG FIX] [MER-3919] Simple Author - Slider - Decimals not allowed in custom values in Advanced Feedback

assets/src/components/activities/adaptive/AdaptiveAuthoring.scss, assets/src/components/parts/janus-audio/schema.ts, assets/src/components/parts/janus-dropdown/Dropdown.tsx
=> [BUG FIX] [MER-3559] Issue in Audio Component Panel in Simple Author/Flowchart

lib/oli_web/plugs/require_authenticated.ex
[Link](https://eliterate.atlassian.net/browse/MER-3507) to the ticket
https://github.com/user-attachments/assets/98761999-08d6-4c58-9aa6-5844e1cda41c
=> [BUG FIX] [MER-3507] Require instructor login when accessing course section information as account admin

mix.exs
=> [CHORE] [MER-0000] bump version number 0.30.0

lib/oli/delivery/sections/section.ex, lib/oli_web/components/layouts/workspace.html.heex, lib/oli_web/live/certificates/certificate_settings_component.ex, lib/oli_web/live/certificates/certificate_settings_live.ex, lib/oli_web/live/collaboration_live/index_view.ex, lib/oli_web/live/products/details_view.ex, lib/oli_web/live/workspaces/course_author/certificate_settings_live.ex, lib/oli_web/live/workspaces/course_author/products/details_live.ex, lib/oli_web/router.ex, test/oli_web/live/certificates/certificate_settings_component_test.exs, test/oli_web/live/certificates/certificate_settings_live_test.exs, test/oli_web/live/workspaces/certificate_settings_live_test.exs
[MER-4086](https://eliterate.atlassian.net/browse/MER-4086)
https://github.com/user-attachments/assets/fc948d72-35a5-4746-8f1c-3a88fe19e40f
[MER-4086]: https://eliterate.atlassian.net/browse/MER-4086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4086] Add link to go to the page that enables certificates

lib/oli_web/controllers/invite_controller.ex
[Link](https://eliterate.atlassian.net/browse/MER-4068?focusedCommentId=25207) to the ticket
=> [BUG FIX] [MER-4068] Reimplement users invite functionality - part 3

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx
This is the same PR https://github.com/Simon-Initiative/oli-torus/pull/5342 that was approved but landed in Master. This one, we are doing it in hotfix.
=> [BUG FIX] [MER-4131] | Dig into chem labs simulations

assets/src/apps/bank/ActivityBank.tsx, assets/src/data/persistence/activity.ts, lib/oli/authoring/editing/activity_editor.ex, lib/oli_web/controllers/api/activity_controller.ex, lib/oli_web/router.ex, test/oli_web/controllers/activity_controller_test.exs
This PR addresses issues identified during the previous PR as incomplete. 
Issues:
1. There is no undo function as described in the ticket
2. The user must refresh the tab in order to navigate through more pages of the activity bank
=> [BUG FIX] [MER-3366] adds undo and refresh features

lib/oli_web/controllers/delivery_controller.ex
This PR fixes an issue where guest user account creation results in the creation of two accounts
=> [BUG FIX] [MER-4140] fixes creation of two guest accounts

assets/src/components/activities/common/triggers/TriggerActions.tsx, assets/src/components/activities/common/triggers/TriggerAuthoring.tsx, assets/src/components/activities/common/triggers/TriggerUtils.tsx, assets/src/components/activities/multi_input/MultiInputAuthoring.tsx, assets/src/components/activities/response_multi/ResponseMultiInputAuthoring.tsx, assets/src/components/tabbed_navigation/Tabs.tsx
This completes basic implementation of the Activity Trigger Authoring UI by adding better styling, primarily addressing reasonable inter-element spacing. 
Note this includes an adjustment to inter-tab padding in the Tab Navigation component used in activity authoring to enable the DOT Tab to fit without overflowing onto the next line. 
This also corrects handling of multi-input questions to properly render based on currently selected part, including part number in the header info.
For items in the select action dropdown menu whose text descriptions were truncated to fit, this adds a tooltip with the complete plain text. 
The add trigger mode includes an expandable element to optionally display a static list of helpful prompts, as sketched in the design. Used grey colors with variants for …
=> [FEATURE] [MER-4205] Style activity trigger authoring UI

assets/src/apps/Components.tsx, assets/src/apps/app.tsx, assets/src/components/editing/elements/audio/AudioSettings.tsx, assets/src/components/editing/elements/video/VideoModal.tsx, assets/src/components/editing/elements/video/VideoSettings.tsx, lib/oli_web/components/layouts/workspace.html.heex, lib/oli_web/live/workspaces/course_author/activity_bank_live.ex, lib/oli_web/live/workspaces/course_author/bibliography_live.ex, lib/oli_web/templates/layout/workspace.html.heex, test/oli_web/live/workspaces/course_author/activity_bank_live_test.exs
https://eliterate.atlassian.net/browse/MER-4075
This is a follow-up to fix issues uncovered as a result of https://github.com/Simon-Initiative/oli-torus/pull/5374.
The approach here is to revert all changes made in the previous PR and instead take a more limited approach to the fix. This fix takes a similar approach to other fixes that have been made in the past to resolve modal and missing store issues. Instead of trying to resolve the root cause of the component not being under the umbrella of a parent provider, and new provider is simply used by instantiating a new store.
While this works to resolve the immediate issue, it is just a bandaid on the larger issue that we are using global references to dispatch actions and calling `configureStore` in multiple different components (50+ …
=> [BUG FIX] [MER-4075] Cant access video settings (Part 2)

lib/oli/analytics/datasets.ex, lib/oli/analytics/datasets/emr_serverless.ex
=> [ENHANCEMENT] [MER-4127] add debug logging

lib/oli/delivery/certificates.ex, lib/oli/utils.ex, lib/oli_web/components/delivery/buttons.ex, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/delivery/content/progress.ex, lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex, lib/oli_web/components/delivery/students/students.ex, lib/oli_web/icons.ex, lib/oli_web/live/certificates/certificate_settings_component.ex, lib/oli_web/live/certificates/certificate_settings_live.ex, lib/oli_web/live/delivery/student/learn_live.ex, lib/oli_web/live/workspaces/course_author/certificate_settings_live.ex, test/oli/delivery/certificates_test.exs, test/oli/delivery/sections/certificate_test.exs, test/oli_web/live/certificates/certificate_settings_component_test.exs, test/support/factory.ex
[MER-4085](https://eliterate.atlassian.net/browse/MER-4085)
https://github.com/user-attachments/assets/6160b30e-3334-4896-a496-10433dc4e863
[MER-4085]: https://eliterate.atlassian.net/browse/MER-4085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4085] Certificates Threshold Tab

cloud/generate-pdf-certificate/README.md, cloud/generate-pdf-certificate/lambda_function.py
Add the code for the lambda function that generates PDF certificates and stores them in S3.
See: https://eliterate.atlassian.net/browse/MER-4151
=> [FEATURE] [MER-4151] Certificate PDF Generation using AWS Lambda

lib/oli/analytics/datasets.ex
Copy and paste error preventing jobs other than datashop from working.
=> [ENHANCEMENT] [MER-4250] Fix staging for non datashop jobs

assets/src/apps/authoring/components/PropertyEditor/schemas/lesson.ts
=> [BUG FIX] [MER-4218] Advanced Authoring: Unable to de-select "refresh warning pop up"

assets/src/apps/delivery/Delivery.tsx, lib/oli_web/controllers/page_delivery_controller.ex
This PR is continuation of https://github.com/Simon-Initiative/oli-torus/pull/5362
We have added code to make the inspector tool available for Admin / Author / Instructor users.
Hey @gastonabella, I added your changes in this PR. Could you please look at it and approve it? Thanks
=> [ENHANCEMENT] [MER-4065] Adding CAPI visibility in Review mode

lib/oli/analytics/datasets.ex, lib/oli_web/live/workspaces/course_author/dataset_details_live.ex
This PR adds download support for the JSON lookup data file that gets created for each and every dataset.
=> [ENHANCEMENT] [MER-4253] Add lookup data link and explanation

lib/oli_web/live/workspaces/course_author/datasets_live.ex
=> [BUG FIX] [MER-4240] Fix spelling

assets/src/components/parts/janus-image/schema.ts
=> [ENHANCEMENT] [MER-4297] Add lock aspect ration button to image component in Simple Author

assets/src/apps/delivery/components/preview-tools/Inspector.tsx
=> [BUG FIX] [MER-4300] Error thrown and can't see inspector on some screens - Advanced Author

assets/src/apps/authoring/components/PropertyEditor/custom/CompJsonEditor.tsx, assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx
The issues reported related to Image component was already fixed in -> https://github.com/Simon-Initiative/oli-torus/pull/5296
=> [BUG FIX] [MER-4301] delete window popping up in JSON modal - advanced author

lib/oli_web/live/delivery/student/index_live.ex, test/oli_web/live/delivery/student/index_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4287) to the ticket
https://github.com/user-attachments/assets/fb0fba5d-dc71-437b-92ed-b62ee4ce6e46
=> [FEATURE] [MER-4287] Show certificate card on students first visit

assets/src/apps/page-editor/PageTriggerEditor.tsx
Updates the page trigger editor to say "Page" instead of "Activity".  Shows the example prompt dropdown.
=> [FEATURE] [MER-4042] Page level trigger updates

lib/oli/delivery/granted_certificates.ex, lib/oli/delivery/sections.ex, lib/oli/delivery/sections/certificates/email_templates.ex, lib/oli/delivery/sections/certificates/workers/generate_pdf.ex, lib/oli/delivery/sections/certificates/workers/mailer.ex, lib/oli_web/components/delivery/students/certificates/email_notification_modals.ex, lib/oli_web/components/delivery/students/certificates/state_approval_component.ex, lib/oli_web/components/delivery/students/students.ex, test/oli/delivery/certificates/certificate_renderer_test.exs, test/oli/delivery/granted_certificates_test.exs, test/oli/delivery/sections/certificates/workers/generate_pdf_test.exs, test/oli/delivery/sections/certificates/workers/mailer_test.exs, test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs
Ticket: [MER-4107](https://eliterate.atlassian.net/browse/MER-4107)
This PR completes the integration of everything with the mailer worker.
[MER-4107]: https://eliterate.atlassian.net/browse/MER-4107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4107] Bare-bones Email Notifications

assets/src/components/editing/elements/trigger/TriggerEditor.tsx
This PR changes the language to use "Paragraph" instead of "Activity" for the content block trigger.  It also switches the icon to the DOT trigger icon.  These changes now render:
=> [FEATURE] [MER-4046] Authoring paragraph level trigger updates

assets/src/apps/authoring/components/Flowchart/rules/create-hub-spoke-rules.ts, assets/src/apps/authoring/components/PropertyEditor/custom/SpokeOptionsEditor.tsx, assets/src/apps/authoring/store/parts/actions/updatePart.ts, assets/src/components/parts/janus-hub-spoke/HubSpoke.tsx, assets/src/components/parts/janus-hub-spoke/schema.ts, assets/styles/authoring/flowchart-component-panels.scss, assets/styles/authoring/template.scss
This PR contains changes for some follow-up bugs and some enhancement suggested in the comment to improve the component features.
=> [BUG FIX] [MER-3418] Add a hub and spoke component to simple author/flowchart

assets/src/apps/authoring/components/Flowchart/chart-components/FlowchartIcon.tsx, assets/src/apps/authoring/components/Flowchart/screen-icons/HubSpokeIcon.tsx, assets/src/apps/authoring/components/Flowchart/toolbar/HubSpokeIcon.tsx, assets/static/images/icons/icon-part-hub-spoke.svg
This PR only contains the changes for the new icon for the hub component.
=> [ENHANCEMENT] [MER-3418] Add a hub and spoke component to simple author/flowchart

lib/oli/delivery/certificates.ex, lib/oli_web/live/delivery/student/index_live.ex, test/oli_web/live/delivery/student/index_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4369) to the ticket
This PR also addresses [MER-4371](https://eliterate.atlassian.net/browse/MER-4371)
[MER-4371]: https://eliterate.atlassian.net/browse/MER-4371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4369] Student certificate awaiting instructor approval

lib/oli_web/live/certificates/components/design_tab.ex
https://github.com/user-attachments/assets/32720107-ef4f-4244-a4bb-6d9b6b831af6
See: https://eliterate.atlassian.net/browse/MER-4365
=> [ENHANCEMENT] [MER-4365] Display if any errors occur when uploading a certificate logo

assets/src/apps/authoring/components/Flowchart/flowchart-actions/add-screen.ts, assets/src/apps/authoring/components/Flowchart/paths/path-options.ts, assets/src/apps/authoring/components/Flowchart/sidebar/FlowchartSidebar.tsx, assets/src/apps/authoring/components/Flowchart/sidebar/PathEditor.tsx, assets/src/apps/authoring/components/Flowchart/sidebar/PathsEditor.tsx, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartTopToolbar.tsx, assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/SpokeCompletedOption.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/SpokeOptionsEditor.tsx, assets/src/apps/authoring/store/parts/actions/updatePart.ts, assets/src/components/parts/janus-hub-spoke/schema.ts, assets/styles/authoring/flowchart.scss
This PR contains further changes requested in the ticket comment as well minor changes for - [minor issues with flowchart screen selector view (Simple Author)](https://eliterate.atlassian.net/browse/MER-4376)
=> [FEATURE] [MER-3418] Add a hub and spoke component to simple author/flowchart

mix.exs
Bump master branch version number to `0.31.0` for forward development
=> [CHORE] [MER-0000] Bump master to v31

lib/oli_web/router.ex
Fixes another issue uncovered related to omit student email verification. Some of the required API routes such as attempts and user state were missing the necessary plug.
This PR adds the `require_section` and `maybe_skip_email_verification` to any remaining student facing routes that include a `:section_slug` parameter.
=> [BUG FIX] [MER-4243] checkbox for omit student email verification not being honored

lib/oli_web/live/delivery/student_onboarding/intro.ex, test/oli_web/live/delivery/onboarding_wizard/student_onboarding_wizard_test.exs
https://eliterate.atlassian.net/browse/MER-4407
Fixes a typo on the welcome wizard.
=> [ENHANCEMENT] [MER-4407] Fix typo shape learning experience

lib/oli_web/components/delivery/layouts.ex, lib/oli_web/components/layouts/workspace.html.heex, lib/oli_web/live/workspaces/course_author/overview_live.ex, test/oli_web/components/delivery/layouts_test.exs, test/oli_web/live/workspaces/course_author/overview_live_test.exs
See: https://eliterate.atlassian.net/browse/MER-4398
=> [BUG FIX] [MER-4398] Display resource_title if available

lib/oli_web/live/delivery/student_onboarding/intro.ex, test/oli_web/live/delivery/onboarding_wizard/student_onboarding_wizard_test.exs
Ticket: [MER-4422](https://eliterate.atlassian.net/browse/MER-4422)
Change "A 5 minute survey" to "A short survey"
[MER-4422]: https://eliterate.atlassian.net/browse/MER-4422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-4422] Correct typo in survey text

lib/oli_web/components/delivery/activity_helpers.ex
[MER-4392](https://eliterate.atlassian.net/browse/MER-4392)
This PR fixes an issue with the Likert visualization, specifically the dot sizes on the chart, which represent answer frequency among students.
A recent database optimization in [PR #5455](https://github.com/Simon-Initiative/oli-torus/pull/5455) altered the structure of the response data used by this chart. The changes on this PR update the data passed to the Likert to align with the new format.
https://github.com/user-attachments/assets/4e8ac4a1-707c-434b-bf08-191f452a9e2b
[MER-4392]: https://eliterate.atlassian.net/browse/MER-4392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-4392] Likert Visualization Broken

assets/src/apps/authoring/components/PropertyEditor/custom/AdvancedFeedbackNumberRange.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/MCQCustomErrorFeedbackAuthoring.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/OptionsCustomErrorFeedbackAuthoring.tsx, assets/src/apps/authoring/components/PropertyEditor/custom/SpokeCustomErrorFeedbackAuthoring.tsx, assets/src/components/parts/janus-dropdown/schema.ts, assets/src/components/parts/janus-hub-spoke/schema.ts, assets/src/components/parts/janus-input-number/schema.ts, assets/src/components/parts/janus-input-text/schema.ts, assets/src/components/parts/janus-mcq/schema.ts, assets/src/components/parts/janus-multi-line-text/schema.ts, assets/src/components/parts/janus-slider/schema.ts
=> [ENHANCEMENT] [MER-4387] Update Single-line feedback to Multi line feedback input in Simple Author

assets/css/app.css, lib/oli/delivery/hierarchy.ex, lib/oli_web/components/delivery/utils.ex, lib/oli_web/icons.ex, lib/oli_web/live/delivery/student/discussions_live.ex, lib/oli_web/live/delivery/student/learn/components/view_selector.ex, lib/oli_web/live/delivery/student/learn_live.ex, lib/oli_web/live/delivery/student/lesson/annotations.ex, test/oli/delivery/hierarchy_test.exs, test/oli_web/live/delivery/student/learn_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4097) to the ticket
https://github.com/user-attachments/assets/0f14a17e-866b-4180-a93a-bffc51b58bb1
=> [FEATURE] [MER-4097] Student outline view search and expand features

assets/src/apps/authoring/components/Flowchart/screens/screen-factories.ts, assets/src/apps/authoring/components/Flowchart/screens/screen-utils.ts, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx
=> [ENHANCEMENT] [MER-3577] Prevent Adding Question Components to the End Screen in Simple Author

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/scripts/init.sh
This PR fixes some issues with the devcontainer setup.
In cases where we want to have an easily-deployable developer environment without having to configure a machine manually, devcontainers make a lot of sense.
We already have most of the configs in place, there are just a few tweaks required here to fix this and reduce any friction for quickly getting up and running with a torus dev instance.
Here are the instructions for getting up and running. We should verify these and the add them to the wiki once this PR lands:
Prerequisites:
- Docker
- VS Code
1. Clone oli-torus repository
2. Open repository in VS Code.
3. If prompted in the bottom right, click "Reopen in Container". Otherwise, using the command palette (Cmd+Shift+P), search for and select "Reopen in container". Alternatively, you …
=> [CHORE] [MER-0000] Devcontainer fixes

assets/src/hooks/expand_containers.ts, assets/src/hooks/index.ts, assets/src/hooks/scroller.ts, lib/oli_web/live/delivery/student/learn_live.ex, test/oli_web/live/delivery/student/learn_live_test.exs
Ticket: [MER-4098](https://eliterate.atlassian.net/browse/MER-4098)
This PR adds the functionality to scroll down in the outline view when returning from a visited page.
[MER-4098]: https://eliterate.atlassian.net/browse/MER-4098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4098] Add scrolling functionality to the outline view

lib/oli/delivery/settings.ex, lib/oli_web/live/delivery/student/utils.ex, test/oli/delivery/settings_test.exs, test/oli_web/live/delivery/student/prologue_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4490) to the ticket
The reason for the bug is explained in the ticket's description.
=> [BUG FIX] [MER-4490] Fix date comparison and submit page term

assets/src/components/parts/janus-image/Image.tsx, assets/src/components/parts/janus-image/ImageAuthor.tsx, assets/src/components/parts/janus-image/schema.ts
=> [ENHANCEMENT] [MER-4418] Adding image link to the right side panel to directly add the image URL

lib/oli_web/controllers/api/trigger_point_controller.ex, lib/oli_web/controllers/project_controller.ex, lib/oli_web/router.ex
Ticket: [MER-4493](https://eliterate.atlassian.net/browse/MER-4493)
This PR changes the banner message after enabling AI Activation Points
[MER-4493]: https://eliterate.atlassian.net/browse/MER-4493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUG FIX] [MER-4493] Change the text on the banner after enabling AI activation points (rework 2)

mix.exs
=> [CHORE] [MER-0000] Bump version 0.30.1

lib/oli/logger_truncator.ex
This PR makes the logger filter more robust by catching any exceptions, since if an exception is thrown, the Logger permanently removes the filter.
=> [ENHANCEMENT] [MER-4511] More robust logger filter

assets/src/apps/authoring/components/ScreenList/ScreenList.tsx
=> [BUG FIX] [MER-4414] Simple Author in Screen Panel view icons are green for unvalidated screens 

assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx, assets/src/apps/authoring/components/ExpertHeaderNav.tsx, assets/src/apps/authoring/components/Modal/DiagnosticsWindow.tsx, assets/styles/authoring/advanced-authoring.scss
This PR contains some CSS changes to handle the alignment of the part component toolbar. It does not have any impact on existing flow.
https://github.com/user-attachments/assets/d995b340-d52b-4497-bc3f-4bb09edb092d
=> [BUG FIX] [MER-3586] Resizing window will cause component icons to not appear in Advanced Author

assets/styles/authoring/flowchart.scss
=> [BUG FIX] [MER-4417] Switching from Flowchart view to Screen Panel view causes the canvas to be off centered

assets/src/apps/delivery/layouts/deck/components/HistoryPanel.tsx
=> [BUG FIX] [MER-4423] Ensure "Submit Attempt" is correctly displayed in scored adaptive pages for student mode.

lib/oli/lti/platform_external_tools.ex, lib/oli_web/live/admin/external_tools/details_view.ex, lib/oli_web/live/admin/external_tools/form.ex, lib/oli_web/live/admin/external_tools/new_external_tool_view.ex, lib/oli_web/live/admin/external_tools/table_model.ex, lib/oli_web/router.ex, test/oli/lti/platform_external_tools_test.exs, test/oli_web/live/admin/external_tools/details_view_test.exs
[MER-4400](https://eliterate.atlassian.net/browse/MER-4400)
Add new Details page for LTI External Tools.
https://github.com/user-attachments/assets/31961d93-6368-48ce-8a2d-fac5e4a30012
[MER-4400]: https://eliterate.atlassian.net/browse/MER-4400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4400] Admin Edit LTI Tool Details

assets/src/hooks/conditional_toggle.js, assets/src/hooks/index.ts, lib/oli/lti/platform_external_tools.ex, lib/oli_web/components/common.ex, lib/oli_web/components/modal.ex, lib/oli_web/live/admin/external_tools/details_view.ex, lib/oli_web/live/admin/external_tools/form.ex, test/oli/delivery/response_multi_test.exs, test/oli/lti/platform_external_tools_test.exs, test/oli_web/live/admin/external_tools/details_view_test.exs
[MER-4294](https://eliterate.atlassian.net/browse/MER-4294)
Allows enabling and disabling an LTI External Tool for projects and course sections use.
https://github.com/user-attachments/assets/fe2c4587-04b0-4859-a037-da43bcae4344
[MER-4294]: https://eliterate.atlassian.net/browse/MER-4294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4294] Enable and Disable LTI Tool at System Level

lib/oli_web/live/delivery/student/lesson_live.ex, lib/oli_web/live/delivery/student/prologue_live.ex, lib/oli_web/live/delivery/student/utils.ex, lib/oli_web/live_session_plugs/init_page.ex, lib/oli_web/router.ex, test/oli_web/live/delivery/student/lesson_live_test.exs, test/oli_web/live/delivery/student/prologue_live_test.exs, test/oli_web/plugs/maybe_gated_resource_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4346) to the ticket
https://github.com/user-attachments/assets/29fefe14-a869-42ae-910f-93c7b4f4076a
https://github.com/user-attachments/assets/0f1a4a90-abd5-4f7c-813c-9926e27cd1f4
=> [FEATURE] [MER-4346] Update UI for pages with advanced gating

lib/oli/lti/platform_external_tools.ex, lib/oli/lti/platform_external_tools/browse_options.ex, lib/oli_web/live/admin/external_tools/details_view.ex, lib/oli_web/live/admin/external_tools/external_tools_view.ex, lib/oli_web/live/admin/external_tools/table_model.ex, test/oli/lti/platform_external_tools_test.exs, test/oli_web/live/admin/external_tools/details_view_test.exs, test/oli_web/live/admin/external_tools/external_tools_view_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4399?focusedCommentId=28408) to the comment in the ticket
https://github.com/user-attachments/assets/f319c563-7b51-49fe-b48a-ff3afed1d52c
=> [FEATURE] [MER-4399] Rework: Admin soft delete external tool

lib/oli_web/live/sections/lti_external_tools.ex
[Link](https://eliterate.atlassian.net/browse/MER-4314?focusedCommentId=28553) to the comment in the ticket
=> [BUG FIX] [MER-4314] Rework instructor LTI tool overview page

assets/src/components/parts/janus-hub-spoke/HubSpoke.tsx, assets/src/components/parts/janus-hub-spoke/HubSpokeAuthor.tsx, assets/src/components/parts/janus-hub-spoke/schema.ts
Hey @bsparks, could you please look at the PR> Thanks
This PR contains some CSS changes for aligning the button text.
https://github.com/user-attachments/assets/8c246396-b532-420f-a781-ab1e6a9ec137
=> [BUG FIX] [MER-4573] Text is not properly aligned in Hub and spoke component 

assets/src/apps/authoring/components/Flowchart/paths/path-options.ts, assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx
=> [BUG FIX] [MER-4572] Cannot paste static components onto screens with question components

assets/src/apps/scheduler/PageScheduleLine.tsx, assets/src/apps/scheduler/ScheduleLine.tsx
This PR addresses QA re-work request to fix the background color for rows representing deleted schedule items.
=> [ENHANCEMENT] [MER-4344] Fixes dark mode schedule item deleted background color

lib/oli_web/live/workspaces/course_author/curriculum/entry.ex, test/oli_web/live/workspaces/course_author/curriculum_live_test.exs
[Link](https://eliterate.atlassian.net/browse/MER-4585) to the ticket
https://github.com/user-attachments/assets/6042b941-b97b-4d65-b122-58d9f8c4c82c
https://github.com/user-attachments/assets/40c1d9dd-5258-4b4d-bf00-3b36a727b89e
=> [BUG FIX] [MER-4585] Edit advanced author page

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx, assets/src/apps/delivery/store/features/groups/actions/deck.ts
=> [BUG FIX] [MER-4662] Opening a student's attempt as an admin returns them to first screen

lib/oli/accounts/schemas/user.ex, lib/oli/delivery/sections.ex, lib/oli/grading.ex, lib/oli/grading/gradebook_score.ex, lib/oli/utils.ex, lib/oli/utils/db_seeder.ex, lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/controllers/page_delivery_controller.ex, lib/oli_web/live/delivery/student/utils.ex, test/oli/grading_test.exs, test/oli_web/live/grades_live_test.exs
[MER-4609](https://eliterate.atlassian.net/browse/MER-4609)
Update Gradebook report according to new requirements:
- Display new columns (such as `Enrollment Status` `LMS ID`).
- Add a `Percentage` column for each assessment, as well as the `Points Possible` and `Points Earned`.
- Order rows alphabetically and assessments hierarchically.
https://github.com/user-attachments/assets/9dbea814-db02-4070-97e4-b819f9ffcf44
[MER-4609]: https://eliterate.atlassian.net/browse/MER-4609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENHANCEMENT] [MER-4609] Update Downloadable Gradebook Report

assets/src/apps/scheduler/ScheduleGrid.tsx
[Link](https://eliterate.atlassian.net/browse/MER-4269?focusedCommentId=28479) to the comment in the ticket
https://github.com/user-attachments/assets/9ee58edc-8c85-48d0-bef7-58e7bdee4873
https://github.com/user-attachments/assets/76051818-d228-4df5-b00f-d7c6b1d67b04
=> [BUG FIX] [MER-4269] Rework: fix button colors

assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx, assets/styles/authoring/advanced-authoring.scss
The changes are done to make sure the border, and the background color of the canvas remains the same even if there aren't any parts added to the activity.
https://github.com/user-attachments/assets/148301b1-5ad3-499d-8d04-8055b7a03afa
=> [BUG FIX] [MER-4251] Persistent screen outline in Simple and Advanced Author.

assets/src/apps/authoring/components/Flowchart/rules/create-hub-spoke-rules.ts
=> [BUG FIX] [MER-4760] Issue with incorrect attempt in Hub and Spoke component

assets/src/components/parts/janus-input-number/InputNumber.tsx, assets/src/components/parts/janus-input-number/schema.ts, assets/src/utils/common.ts
=> [ENHANCEMENT] [MER-4428] Update Num Input component to include Significant Figures capi property

assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
=> [BUG FIX] [MER-4302] CSS displays abnormally in Real Chem Unit 4 Exploration

assets/src/apps/authoring/components/Modal/ScoringOverview.tsx, assets/styles/authoring/advanced-authoring.scss, assets/styles/authoring/flowchart.scss
This PR contains changes for the following tickets:
1. [Text and Icons are difficult to see in Dark Mode](https://eliterate.atlassian.net/browse/MER-4196)
2. [Scoring Overview text not visible in dark mode](https://eliterate.atlassian.net/browse/MER-4202)
3. [Conditions' text not visible in dark mode](https://eliterate.atlassian.net/browse/MER-4221)
=> [BUG FIX] [MER-4196] Text and Icons are difficult to see in Dark Mode

assets/src/components/parts/janus-input-number/InputNumber.tsx
=> [BUG FIX] [MER-4428] Update Num Input component to include Significant Figures capi property

lib/oli_web/controllers/activity_bank_controller.ex, test/oli_web/controllers/activity_bank_controller_test.exs
- Fix `KeyError` in ActivityBankController's preview by adding `has_scheduled_resources?` key to template assigns
- Add test suite for `ActivityBankController`
See: https://eliterate.atlassian.net/browse/MER-4815
=> [BUG FIX] [MER-4815] Fix 500 error when previewing activity bank as instructor

assets/css/table.css, assets/src/hooks/copy_to_clipboard.ts, assets/src/hooks/index.ts, assets/tailwind.config.js, assets/tailwind.plugins.js, assets/tailwind.tokens.js, lib/oli_web/components/delivery/content/content.ex, lib/oli_web/components/layouts/student_delivery.html.heex, lib/oli_web/components/layouts/workspace.html.heex, lib/oli_web/live/common/sortable_table/striped_table.ex, lib/oli_web/live/delivery/student/lesson/components/outline_component.ex, lib/oli_web/live/dev/tokens_live.ex, lib/oli_web/live/workspaces/course_author/overview_live.ex, lib/oli_web/router.ex, test/oli_web/live/delivery/instructor_dashboard/insights/content_tab_test.exs
[MER-4765](https://eliterate.atlassian.net/browse/MER-4765)
This PR introduces the initial implementation of design tokens to define color values based on the Figma design system.
The tokens are defined in the `tailwind.tokens.js` file, where each token includes both its light and dark mode variants. If you need to add or update a token, this file should be modified directly.
In this PR, I started replacing hardcoded color values in tailwind classes with the newly defined semantic tokens, as part of the effort to move toward a more consistent and scalable design system.
Additionally, I added an internal page at [/dev/tokens](http://localhost/dev/tokens), which provides an easy way to browse available tokens and copy their names or hexadecimal values.
[MER-4765]: …
=> [FEATURE] [MER-4765] Implement color tokens

assets/css/table.css, lib/oli_web/components/delivery/content/multi_select.ex, lib/oli_web/components/delivery/content/progress.ex
[MER-4693](https://eliterate.atlassian.net/browse/MER-4693)
This PR fixes minor errors in the size of filter texts and the color of texts in the `Order` column of the table.
[MER-4693]: https://eliterate.atlassian.net/browse/MER-4693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEATURE] [MER-4693] Insights content table UI - Rework 2

assets/src/components/parts/janus-capi-iframe/manifest.json, priv/repo/migrations/20250811145546_updateCapiPartRegistrations.exs
@gastonabella, as part of this PR, I had to execute a update statement on DB ->` part_component_registrations` table. I haven't done that but looking at the migration script, I thought this is the right place to put the update script. Let me know your thoughts.
=> [ENHANCEMENT] [MER-4835] Change the tool tip info contents of the CAPI Iframe component in advanced author

assets/src/components/parts/janus-text-slider/SliderTextAuthor.tsx
=> [BUG FIX] [MER-4809] Slider Text Component does not delete

assets/src/components/activities/oli_embedded/OliEmbeddedAuthoring.tsx, assets/src/components/activities/oli_embedded/utils.ts, assets/src/components/media/manager/upload.ts, assets/src/data/persistence/media.ts, assets/src/utils/xmlPretty.ts, lib/oli_web/controllers/legacy_superactivity_controller.ex, lib/oli_web/router.ex
This PR introduces two key updates to improve authoring and file handling workflows:
- Automatically formats Superactivity XML content for improved readability in the authoring interface.  
- Enhances clarity and maintainability for content authors working with structured XML.  
- Updates file/media upload process to S3 to leverage the bundled course ingest tool feature.  
- Ensures files tied to a package are uploaded into a dedicated, package-specific folder.  
- Moves away from the default flat file system, reducing risk of file collisions and improving content organization.
=> [ENHANCEMENT] [MER-4825] tech debt: Improve superactivity authoring

assets/tailwind.tokens.js, lib/oli/authoring/course.ex, lib/oli_web/live/projects/projects_live.ex, lib/oli_web/live/projects/table_model.ex
[MER-4669](https://eliterate.atlassian.net/browse/MER-4669)
This PR introduces a set of improvements to the `Browse Projects` table for admin users.
Some existing columns were updated to improve clarity and consistency, while new ones were added to expose commonly used information in a more accessible way.
The layout and visual changes follow the latest Figma design.
Additionally, a new column called Tags was included in the layout, though its functionality will be implemented in upcoming tickets.
New columns added
- Collaborators
- Institution
- Published
- Visibility
- Tags (not functional yet)
Updated columns
- Title (now also shows the Project ID/Slug)
- Created by (now links to the author’s profile)
https://github.com/user-attachments/assets/c245f2a2-2cc1-4eb7-808a-14af01b76ea7 …
=> [FEATURE] [MER-4669] Browse All Projects information

assets/src/components/parts/janus-image/ImageAuthor.tsx, assets/src/components/parts/janus-image/schema.ts
After the discussion with team, we are removing the image source from the right panel.
=> [BUG FIX] [MER-4763] Complexities with two ways to add image links in advanced author

assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx
https://github.com/user-attachments/assets/c2730962-424c-4f87-beff-735808d16d34
=> [BUG FIX] [MER-4837] Cannot move canvas if no components present

assets/src/components/parts/janus-image/ImageAuthor.tsx
Hey @bsparks, could you please review the PR? Thanks
As part of this PR, I am bringing back the changes done in https://github.com/Simon-Initiative/oli-torus/pull/5231 && https://github.com/Simon-Initiative/oli-torus/pull/5228 as well added some code to prevent unnecessary saves.
=> [BUG FIX] [MER-4884] SA and AA - Images are no longer resizing to keep aspect ratio

lib/oli_web/live/workspaces/course_author/overview_live.ex
https://appsignal.com/open-learning-initiative/sites/618539ab2cf81d7e3cd051ca/exceptions/incidents/302/samples/618539ab2cf81d7e3cd051ca-688004869511640336417557992001
```
** (KeyError) key :accepted not found in: %{}
```
```
lib/oli_web/live/workspaces/course_author/overview_live.ex:291 anonymous fn/3 in OliWeb.Workspaces.CourseAuthor.OverviewLive.render/1
lib/phoenix_live_view/diff.ex:391 Phoenix.LiveView.Diff.traverse/7
lib/phoenix_live_view/diff.ex:532 anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
lib/enum.ex:2531 Enum."-reduce/3-lists^foldl/2-0-"/3
lib/phoenix_live_view/diff.ex:389 Phoenix.LiveView.Diff.traverse/7
lib/phoenix_live_view/diff.ex:532 anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
lib/enum.ex:2531 Enum."-reduce/3-lists^foldl/2-0-"/3 …
```
=> [BUG FIX] [MER-4898] AppSignal: Handle nils in collaborators

lib/oli_web/live/sections/table_model.ex, test/oli_web/live/sections/sections_table_model_test.exs
Rework for https://eliterate.atlassian.net/browse/MER-4671
https://github.com/user-attachments/assets/a1d45825-a091-40df-8d25-a403cd3d4d17
=> [ENHANCEMENT] [MER-4671] Make institution name clickable in Browse Sections table

assets/src/components/parts/janus-input-number/InputNumber.tsx, assets/src/components/parts/janus-input-number/schema.ts
=> [ENHANCEMENT] [MER-4912] Add option to disable scrollable input fields 

assets/styles/adaptive/activities/mcq.scss
=> [BUG FIX] [MER-4915] Circle for selected MCQ is offset in QA for AA

.github/workflows/pr-cleanup.yml, .github/workflows/pr-deploy.yml, devops/docker-compose.yml
This PR fixes an issue with PR deployments where the app image url was not fully resolved to ghcr.io. It also adds the capability to deploy and cleanup any branch manually using Github actions.
=> [ENHANCEMENT] [MER-4885] fix app image url

lib/oli_web/controllers/delivery_controller.ex, lib/oli_web/live/user_registration_live.ex, lib/oli_web/plugs/require_enrollment.ex
Part 2 of https://github.com/Simon-Initiative/oli-torus/pull/5882
See: https://eliterate.atlassian.net/browse/MER-4936
=> [BUG FIX] [MER-4936] Redirect to appropriate page when following invite link and using SSO Sign Up

assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx, assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx
**Advanced mode: Fix focus loss & debounce updates**
- Changes applied only in Expert Mode (`isExpertMode=true`)
- Wrapped the form inside a parent `<div>` to intercept and handle Backspace key presses
- Prevented focus loss when typing in inputs
- Delayed save calls with 500ms debounce for smoother updates while typing
- Backspace-triggered deletes now save only on blur instead of mid-typing
- Preserved existing behavior for Basic Mode (no changes)
=> [BUG FIX] [MER-4914] focus is reset and user is kicked out of input when typing in AA component panel

lib/oli_web/live/components/tags/tags_component.ex
[Link](https://eliterate.atlassian.net/browse/MER-4668?focusedCommentId=33691) to the comment in the ticket
https://github.com/user-attachments/assets/c4b9942f-a7ef-49bb-af4c-997816dc8fd6
=> [FEATURE] [MER-4668] Browse all table tags - rework

assets/src/apps/page-editor/PageTriggerEditor.tsx, assets/src/components/editing/elements/trigger/TriggerEditor.tsx
[Link](https://eliterate.atlassian.net/browse/MER-4844) to the ticket
=> [BUG FIX] [MER-4844] Grammar corrections

assets/src/components/content/Popup.tsx, assets/src/components/hooks/useAudio.tsx, assets/src/hooks/use_pointer_capability.ts, assets/test/components/content/popup_test.tsx
[Link](https://eliterate.atlassian.net/browse/MER-4464) to the ticket
https://github.com/user-attachments/assets/642cb5e4-51b4-45c2-9cd7-fd87625df71c
https://github.com/user-attachments/assets/5da8e940-5180-4721-8c54-b1b29a097136
https://github.com/user-attachments/assets/d1e70a72-8606-43e1-8f21-ac15e6e5278a
=> [FEATURE] [MER-4464] Key notion content popup

assets/src/components/video_player/VideoPlayer.tsx
This is the fix that @codex suggested to allow HTML5 videos to ignore spacebars when clicked inside a text input or text area.  I was unable to test this locally as I don't have an understanding of how to use minio and I could not override it to use the real AWS S3 dev bucket. 
We need a dev to verify that this this indeed fixes the problem.  To do this, create a page with multiple HTML5 video elements on it.  Also include a couple of single response questions.  Verify that from the actual student interface that you can type into the text inputs the spacebar and it does NOT cause the videos on the page to play or pause (if they are playing).  
Disable this and verify that the above steps DO lead to videos being played and paused.
=> [BUG FIX] [MER-5013] Fix spacebar in input

lib/oli_web/live/admin/restore_user_progress.ex
This PR adjusts the existing Admin facing merge tool developed to address a Namtech specific issue, making it more broadly usable as a "merge the progress of two enrollments in the same course section into one enrollment" tool. 
All the existing progress merging logic from the original tool remains as-is, the only changes here are to the UI to allow the input of two enrollment DB ids, then some changes in queries to fetch their relevant info (user, resource_accesses)
I tested this locally and it is indeed now working as designed.
=> [ENHANCEMENT] [MER-5015] merge tool changes
