lib/oli_web/live/common/hierarchy/hierarchy_picker_table_model.ex
test/oli_web/live/remix_section_test.exs
test/oli_web/live/sections/edit_live_test.exs

[Link to the ticket](https://eliterate.atlassian.net/browse/MER-2298)
The issue is not because of the double click. It's because the sorting by published date wasn't being handled. I removed the ability to sort by this attribute because all revisions for a given publication are going to have the same publication date so it doesn't make sense to sort them by it.

[BUGFIX][MER-2298] Disable sort by published date in add materials modal

---

assets/src/components/media/manager/MediaManager.tsx
lib/oli/authoring/media_library.ex
lib/oli_web/controllers/api/media_controller.ex
test/oli/authoring/media_libary_test.exs

There was some confusing behavior around uploading duplicate files (either in filename or in content) that this PR addresses.
Before:
> If you tried to upload a file with the same name but different content as one in the media library, you got an error.
Now:
> You are allowed to upload that second file. Both appear in your media list as expected
Before:
> If you tried to upload a file with the same name and the same content, it would give you an error.
Now:
> The existing item will be selected and a small message telling you what happened.
Before:
> If you tried to upload a file with a different name, but the same content, it would silently select the existing item.
Now:
> You get a small message telling you what happened.
Example message:
It will dissapear after 5 seconds, or if you …

[Feature] Better handling of duplicate content uploads [MER-2373]

---

assets/src/components/activities/common/choices/delivery/ChoicesDelivery.modules.scss
assets/src/components/activities/common/choices/delivery/ChoicesDelivery.tsx
assets/src/components/activities/common/stem/delivery/StemDelivery.tsx
assets/src/components/content/Popup.tsx
assets/styles/common/elements.scss
assets/styles/common/purpose.scss
assets/styles/delivery/page_delivery/page.scss
lib/oli/rendering/group/html.ex

Fixes some style inconsistencies across different element types.
1. Add proper line height and paragraph spacing to groups (example, learn by doing, etc...), lists and activity delivery stems
2. Remove x padding on groups, which can compound making content width unreasonable
3. Fix an issue where popups were hidden behind side navbar
I went through about 50 pages and verified the style changed looked reasonable.

[BUG FIX] [MER-2394] styling inconsistencies between normal text and examples

---

assets/styles/common/elements.scss

This PR removes use of color altogether, leaving the standard light and dark mode.  In Dark Mode, this looks like this now:

[BUG FIX] remove dialog colors [MER-2398]

---

lib/oli/delivery/sections.ex

Fix an issue where course overview crashes when student exceptions gating conditions have null start or end date
Closes #4038

[BUG FIX] [MER-2403] fix course overview crash related to student exceptions gating conditions

---

assets/src/components/editing/elements/dialog/CursorInput.tsx
assets/src/components/editing/elements/dialog/DialogEditor.tsx
assets/src/components/editing/elements/dialog/DialogInlineEditor.tsx

*Describe the bug*
When editing a speaker label in a dialog element, the cursor always jumps to the end of the textfield.
*To Reproduce*
Steps to reproduce the behavior:
1. Go to dialog on basic page
2. Edit a speaker label from the middle of the label
3. See cursor jump to end of textfield

[Bugfix] Maintain cursor position in dialog editor [MER-2283]

---

assets/src/components/activities/file_upload/FileSpecConfiguration.tsx

*Describe the bug*
File upload in activity bank allows changing filetype while it is read-only, but it doesnt get persisted (as expected). This could be confusing as a use could forget to click "Edit" and try to change this without realizing their changes arent being saved.
*To Reproduce*
Steps to reproduce the behavior:
1. Go to Activity Bank editor
2. Add file upload activity
3. Click the Allowed files tab and select a type while the editor is read-only

[Bugfix] Don't allow type change in read only file upload [MER-2355]

---

assets/src/components/media/manager/MediaManager.scss
assets/src/components/media/manager/MediaManager.tsx

1. New Feature: The media manager will remember if you were in list or grid view, store that in local storage, and give you the same view next time you use it.
2. Made some tweaks to the grid view so you can see more of the filename, and moved where the ellipses are so you can see the end of the filename. It should also be noted that you can view the full filename after selecting an item and before confirming your selection below the grid.
4. Fixed: The list view can scroll again
5. In the list view, the time is now in your local time zone instead of UTC
Fixes #3710

[Bugfix] Media manager UI fixes [MER-2195]

---

lib/oli_web/components/delivery/exploration_card.ex
lib/oli_web/components/delivery/exploration_list.ex
lib/oli_web/templates/page_delivery/exploration.html.heex

1. Preview course as instructor
2. click on explorations
3. click on the name of an adaptive activity exploration
Expected: Activity is opened in preview mode with the instructor tools available.
Actual: Activity is opened in student mode with no tools.

[Bugfix] Respect preview_mode in exploration preview [MER-2411]

---

assets/src/components/activities/common/hints/authoring/HintsAuthoringConnected.tsx
assets/src/components/activities/custom_dnd/HintsEditor.tsx
assets/src/components/activities/multi_input/sections/HintsTab.tsx
assets/src/data/activities/model/hints.ts
assets/test/activities/hints_test.ts

Utility function Hints.removeHint used by hint editing components was not coded to handle multi-part items, causing bad behavior on author deletion of a hint from any multi-part activity. This recodes it to take partId parameter and use appropriate JSON path operations to operate on the specified part's hint list only.

[BUGFIX]  fix deletion of hints on multipart activities [MER-2432]

---

assets/src/components/editing/editor/normalizers/lists.ts
assets/src/data/content/model/elements/factories.ts
assets/src/data/content/model/elements/types.ts
assets/test/editor/normalize_list_test.ts

If a list item has multiple inline elements as direct children, then content within that list item may be lost the next time the document is edited.
Example of problematic content:
```
{
type: 'li',
children: [
{text ""},
{type: "popup", ...more content here... },
{text ""},
]
}
```
Previously, the normalizers run, see that first text node, wrap it in a paragraph, and then run another round of normalization.
However, that left us with block elements next to inline elements, which is invalid content. So those two extra inline elements would be deleted by slate and data gets lost.
Sample page the problem occurs on:
[OLI Torus](https://proton.oli.cmu.edu/authoring/project/spanish_for_beginners_level_a1/resource/por_vs_para)

[Bugfix] Prevent data loss in list items [MER-2448]

---

CHANGELOG.md
assets/src/components/activities/multi_input/MultiInputDelivery.tsx
assets/src/data/activities/utils.ts
mix.exs

Fixes an issue with multi input questions in review mode of an assessment where only the first word in a text input was being rendered.

[BUG FIX] [MER-2450] multi input text inputs on graded pages restoring only first word

---

assets/src/components/activities/common/authoring/AuthoringCheckbox.tsx
assets/src/components/activities/common/responses/ResponseCard.tsx
assets/src/components/activities/common/responses/TargetedFeedback.tsx
assets/src/components/activities/common/responses/responseActions.ts
assets/src/components/activities/custom_dnd/AnswerKey.tsx
assets/src/components/activities/multi_input/sections/AnswerKeyTab.tsx
assets/src/components/activities/ordering/sections/TargetedFeedback.tsx
assets/src/components/activities/short_answer/ShortAnswerAuthoring.tsx

This adds the ability for an author to specify multiple correct answers. It works by adding a checkbox labeled "Correct" to the ResponseCard component used to display a response when adding targeted feedback. Value is bound by code to the "score" attribute of the response, with non-zero score being correct, anything else incorrect. Checking the box on a previously incorrect response sets a score of 1.
Note score was preserved through migration tool, so migrated courses may have multiple correct responses, though this fact was invisible on the interface. 
Adds a simple AuthoringCheckbox[Connected] component wrapping a checkbox; "connected" version picks up the editMode from the authoring context. Modeled on AuthoringButton.

[ENHANCEMENT] author multiple correct answers [MER-2294]

---

lib/oli/rendering/content/html.ex
test/oli/rendering/content/html_test.exs

Tables without a `caption` attribute, which also exist inside of a paged group of content end up rendering weirdly with an apparent extra column.  The extra column is in fact due to some weird CSS effect that the outer paged group has on causing the table to render full width and padding it with a right aligned border. 
The fix here ensures that all server rendered tables are wrapped in a `<figure class="responsive-embed">` element, which then correctly renders the table. There is some conditional logic to wrap in a figure without a caption, or a figure with a caption, depending on whether or not a non-empty caption exists.   We do not want to render "empty captions" as empty `<figcaption>` elements, as this has a less than ideal interaction with screen readers. 
This fix also removes the …

[BUG FIX] Fix table rendering when missing caption and inside of paged content [MER-2484]

---

lib/oli/activities/model/part.ex
lib/oli/delivery/attempts/core.ex
lib/oli/delivery/paywall.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/snapshots.ex
lib/oli/delivery/transfer.ex
lib/oli_web/components/delivery/actions/actions.ex
lib/oli_web/components/delivery/actions/sections_to_transfer_table_model.ex
lib/oli_web/components/delivery/actions/students_to_transfer_table_model.ex
lib/oli_web/components/delivery/actions/transfer_enrollment.ex
lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex
test/oli/delivery/paywall_test.exs
test/oli/sections_test.exs
test/oli_web/live/delivery/student_dashboard/components/actions_tab_test.exs
test/support/test_helpers.ex

[MER-1908](https://eliterate.atlassian.net/browse/MER-1908)
This PR adds the possibility for an admin user to transfer the enrollment of a student from one course section to another course section.
This functionality can be found in the `actions` tab within the `student dashboard`.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/aeed67db-71e4-4bc1-8fdb-2575e8a631fa
[MER-1908]: https://eliterate.atlassian.net/browse/MER-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-1908] Transfer student data to another section

---

lib/oli_web/components/delivery/students/students.ex
lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/live/sections/enrollments_table_model.ex
test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs

[MER-2477](https://eliterate.atlassian.net/browse/MER-2477)
This PR adds a column to show the `email` of the students in the enrollments table that shows the list of students enrolled for a section, necessary for the instructor. 
It also adds the email field when downloading the information in .csv format.
[MER-2477]: https://eliterate.atlassian.net/browse/MER-2477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2477] Manage student enrollment view email address

---

assets/src/components/activities/vlab/VlabDelivery.tsx

Vlab activity code has the same bug as MER-2450: when initializing inputs from saved state, it was using a utility function, safelySelectInputs, that splits the persisted string representation of the input into an array at spaces. This splitting is useful for activities representing student input as singleton or multiple selection id lists, and harmless where input is a single number, but is inappropriate for free text input that may contain multiple words, such as "Carbon Dioxide", in which case the visible effect will be to restore the first word of the saved input only. This replaces with the variant utility function safelySelectStringInputs which does not apply the split transformation.

[BUGFIX] Vlab: don't split text input on restoring saved state [MER-2509]

---

lib/oli_web/components/delivery/user_account_menu.ex

[MER-2489](https://eliterate.atlassian.net/browse/MER-2489)
This PR fixes the bug when logged in as an Author/Admin and accessing the instructor dashboard. The author name, role and photo were not being displayed correctly in the top bar.
[MER-2489]: https://eliterate.atlassian.net/browse/MER-2489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2489] Fixs user account menu logged in as author/admin

---

lib/oli/grading.ex
lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex
test/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab_test.exs

[MER-2339](https://eliterate.atlassian.net/browse/MER-2339)
This PR fixes a bug that happened when accessing the quiz scores tab within a student's dashboard and the student was in suspended status in that section. 
Now, when accessing the quiz scores tab for a specific student who is suspended in that section, a text is rendered indicating that there are no quiz scores to show.
[MER-2339]: https://eliterate.atlassian.net/browse/MER-2339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2339] Fix error quiz score tab in suspended student

---

lib/oli/delivery/attempts/core.ex
lib/oli/delivery/sections.ex

This PR fixes an issue where deleted or archived sections show incorrect progress results
Closes #4114

[BUGFIX][MER-2508] Fix incorrect progress result in archived sections

---

lib/oli_web/templates/layout/authoring.html.leex
lib/oli_web/templates/layout/lti.html.eex

[[MER-2387]]
After Bootstrap was removed in favor of Tailwind, the `typeahead` function was implicitly removed too since it was part of the library.
However, it is now available separately and can be imported as a new plugin.
**Solution:**
Import `typeahead` library only for the contexts where it is being used (authoring and lti layouts).
https://github.com/Simon-Initiative/oli-torus/assets/26532202/9f028157-c04a-4500-a0cf-f17482c87618
[MER-2387]: https://eliterate.atlassian.net/browse/MER-2387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2387] Fix institution name suggestion

---

assets/src/components/editing/elements/list/listActions.tsx
assets/src/components/editing/toolbar/editorToolbar/blocks/BlockToggle.tsx

The list menu wasn't always appearing correctly.
Steps to reproduce:
1. Type some text on a single line
2. Convert it into a list.
3. Change it to a numeric ordered list
Expected: List menu is visible.
Actual: List menu is not visible.
Fixes: #4123

Bugfix: Numeric lists didn't have correct menu [MER-2523]

---

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx

After recent  change to add a "working..." message, DND hints can obscure feedback as shown in screenshot. This PR
moves feedback after hints, as is standard for other actvities, to avoid this problem.
Also simplifies by eliminating the div introduced around the WorkingMessage-or-Feedback area of the display. That div was apparently intended to prevent activity size from changing frequently as "Working" message comes and goes, but it did not actually reserve a fixed height large enough to accommodate either of Message or Feedback, so did not accomplish that, and generally does not seem necessary.

 [BUGFIX] Stop DND hint from obscuring feedback [MER-2515]

---

lib/oli_web/live/sections/overview_view.ex
test/oli_web/live/sections/overview_live_test.exs

[MER-2496](https://eliterate.atlassian.net/browse/MER-2496)
This PR changes the text of the link from `customize curriculum` to `customize content` in the manage section view to match the text in the breadcrumb view for customize content.
[MER-2496]: https://eliterate.atlassian.net/browse/MER-2496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2496] Changes customize curriculum link text

---

lib/oli/delivery/evaluation/rule.ex
test/oli/delivery/evaluation/rule_eval_test.exs

Fixes a problem where a range matches fail when the range is specified with scientific notation which omits the decimal point (e.g. `4e-8`)
The problem was in the exact location suggested by @andersweinstein 
The fix here is to check for either `.` or `e-`.  This correctly identifies `4e-9` as being a floating point number, but leaves `4e9` as an integer. The unit test shows that it works.  Without the code change, that updated unit test fails.

[BUG FIX] Allow for no decimal point, only e in floats

---

assets/src/apps/scheduler/PageScheduleLine.tsx
assets/src/apps/scheduler/schedule-reset.ts
assets/src/components/editing/editor/paste/onHtmlPaste.ts

The end-time of a due-by schedule item was sometimes lost.
1. Go into the scheduler interface
2. Change an entry to have a due-date with a time other than 11:59
3. Save the schedule.
4. Click the icon (not the name in the left column) of the item
Expected: see the date/time set, and no pending modifications to save.
Actual: See the date & 11:59 set, and a pending modification to save.
Alternatively, for (4), you could have dragged that item in the timeline instead of just clicking it, the same bug occurred.
Now, if you set a time on a due-by item, that time will stick as you click or drag the item in the timeline view.
While fixing this, I noticed a small bug with the reset-schedule functionality when an item represented a very small portion of the overall timeline. That's been fixed as …

Bugfix - due by end time bug [MER-2521]

---

lib/oli_web/controllers/api/page_lifecycle_controller.ex
test/oli_web/controllers/page_delivery_controller_test.exs

[MER-2535](https://eliterate.atlassian.net/browse/MER-2535)
This PR aims to avoid completed graded pages from having update workers if the course section containing them has its `grade_passback_enabled` attribute set to `false`.
[MER-2535]: https://eliterate.atlassian.net/browse/MER-2535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2535] Unnecessary grade update jobs being created

---

lib/oli/delivery/sections.ex
test/oli/sections_test.exs

The various `insert_all` invocations meant to upsert SectionResource records during application of new course project publications had a conflict strategy that resulted in many attributes getting reset to default values.  This was trivial to reproduce manually, just change some assessment settings, apply an update, and check to see that they reverted. 
The fix here was to exclude the necessary settings.  The unit test proves they remain unchanged.

[BUG FIX] Preserve assessment settings during course update application

---

lib/oli_web/components/delivery/actions/transfer_enrollment.ex

This PR is just to fix a typo in the modal of the transfer enrollment

[BUGFIX] Fix typo in transfer enrollment

---

CHANGELOG.md
assets/webpack.config.js
config/config.exs
config/dev.exs
config/releases.exs
lib/oli/application.ex
lib/oli/log_incomplete_request.ex
oli.example.env

Adds a configuration env variable `HTTP_MAX_VALUE_HEADER_LENGTH` for Cowboy http server max header value length. Configuring to a larger value should resolve some of the HTTP 431 errors being returned for users.
If no value is set, then a value of 4096 will be used, which is the default value listed in the Cowboy docs https://ninenines.eu/docs/en/cowboy/2.5/manual/cowboy_http/

[MER-2541] [ENHANCEMENT] Allow configurable max header value length

---

assets/src/components/activities/oli_embedded/OliEmbeddedDelivery.tsx

This PR sets the height of a superactivity iframe by reading the activity XML and using the “height” attribute configured in those XML files, and if that is not set, use a default of 500px.

[BUGFIX][MER-2545] superactivity iframe size

---

lib/oli/delivery/settings.ex
lib/oli/delivery/settings/combined.ex
lib/oli/delivery/settings/student_exception.ex
lib/oli/utils.ex
lib/oli_web/common/format_date_time.ex
lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live/common/utils.ex
lib/oli_web/live/sections/assessment_settings/settings_table.ex
lib/oli_web/live/sections/assessment_settings/settings_table_model.ex
lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex
lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex
lib/oli_web/live/sections/assessment_settings/tooltips.ex
priv/repo/migrations/20230904155403_add_start_date_to_delivery_settings.exs
test/oli/delivery/settings_test.exs
test/oli/utils_test.exs
test/oli_web/common/utils_test.exs
test/oli_web/controllers/page_delivery_controller_test.exs
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

[MER-2525](https://eliterate.atlassian.net/browse/MER-2525)
This PR adds the following changes:
- Add available date to both **Assessment Settings** and **Student Exceptions** pages.
- If both Available and Due dates are already defined and one of them is inconsistently updated (i.e. `due_date < available_date`), both dates are updated to keep the time distance. (See Video 1)
- If the Available Date is set but the Due Date **is not** and the instructor attempts to set it, the datetime select does not allow dates before or equal to the Available Date. The reason is that we cannot calculate a time distance in this scenario. (See Video 2)
- If the Due Date is set but the Available Date **is not** and the instructor attempts to set it, the datetime select does not allow dates after or equal …

[MER-2525] Add available date to assessment settings

---

assets/src/apps/scheduler/PageDragBar.tsx
assets/src/apps/scheduler/PageScheduleLine.tsx
assets/src/apps/scheduler/ScheduleGrid.tsx
assets/src/apps/scheduler/SchedulerSaveBar.tsx
assets/src/apps/scheduler/date-utils.tsx
assets/src/apps/scheduler/schedule-reset.ts
assets/src/apps/scheduler/scheduler-slice.ts
assets/src/apps/scheduler/scheduling-thunk.ts
assets/test/scheduler/schedule-reset_test.ts
lib/oli_web/controllers/api/scheduling_controller.ex

This PR adds the ability to set the availability date for assessments in the graphical scheduler interface. If an assessment has both an availability date, and a Due or Suggested by date, a graphical representation of the span will also appear.
Also changed some icons & colors and added a legend to help make the visual display more understandable.

[Feature] Added availability date in scheduler [MER-2536]

---

lib/oli_web/router.ex

Fixes a typo in the download_codes route. This functionally works because routes in phoenix are typically based off the function atom which is spelled correctly. This just fixes the spelling for the actual route itself.

fix a typo in the download_codes route

---

lib/oli_web/live/sections/assessment_settings/settings_table.ex
lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex

Sorting by `student`, `available date` and `due date` was not working for Student Exceptions table.
The same was happening for `available date` and `due date` in Assessment Settings table.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/369d231c-9aa2-4496-b3e6-c2ba9a694ced
https://github.com/Simon-Initiative/oli-torus/assets/74839302/f1f354f0-5154-4181-bd6f-da2e92acdd6f

Fix sorting in assessment settings

---

lib/oli/analytics/summary.ex
test/oli/analytics/summary/upsert_test.exs

When doing an upsert to the resource_part_responses table after submitting a page with more than one activity, the responses and labels did not match the activity resource_id they belong to (they were being inserted the other way round)
activity 1 -> response 1
activity 2 -> response 2
activity 1 -> response 2
activity 2 -> response 1
activity 1 -> response 1
activity 2 -> response 2

Fix insert resource part responses

---

lib/oli/delivery/attempts/page_lifecycle/graded.ex

This PR fixes an issue where instructor graded assignments circumvent the call to score `rollup` where the call to "mark progress completed" resides. Moving the call to on `submitted` resolves the issue.

[BUGFIX][MER-2559] mark graded assessment completed on submit

---

lib/oli_web/controllers/lti_controller.ex

The route that users were being redirected to after an institution registration request no longer exists

[BUGFIX] Fix route path for LTI institution registration

---

lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
test/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-2568) to the ticket
In all appsignal reports, the user was trying to access an invalid tab (~normalize.css)
`/sections/ux_design_for_effective_instru_t4ifr/instructor_dashboard/reports/~normalize.css/normalize.css`
And since we handled the tab name by converting its value into an existing atom, the app was crashing.
If the user enters an invalid tab in the URL, we will rescue the `String.to_existing_atom` error and assign a default valid tab instead.

[MER-2568][BUGFIX] invalid utf8 encoding

---

lib/oli/publishing.ex
lib/oli_web/live/common/hierarchy/hierarchy_picker_table_model.ex
test/oli_web/live/remix_section_test.exs

[MER-2298](https://eliterate.atlassian.net/browse/MER-2298)
This PR adds the option to sort by `Published on` column in the table of all pages within the `Add Materials` modal to customize the content of a course section.
[MER-2298]: https://eliterate.atlassian.net/browse/MER-2298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2298] Add published_date sort in add materials modal

---

config/config.exs
lib/mix/tasks/create_contained_objectives.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/contained_objective.ex
lib/oli/delivery/sections/contained_objectives_builder.ex
lib/oli/delivery/sections/section.ex
priv/repo/migrations/20230913183242_create_contained_objectives.exs
priv/repo/migrations/20230913190657_add_v25_migration_to_sections.exs
test/mix/tasks/create_contained_objectives_test.exs
test/oli/delivery/sections/contained_objective_test.exs
test/oli/delivery/sections/contained_objectives_builder_test.exs
test/support/factory.ex
test/support/test_helpers.ex

[MER-2573](https://eliterate.atlassian.net/browse/MER-2573)
This PR is the first of three parts to create and use the new `ContainedObjectives` table. Similar to `ContainedPages`, this works as a quick way of knowing which objectives are attached to activities within a specific container.
As part of this pull request:
- New `contained_objectives` table and new `v25_migration` field under `sections` that states if the contained objectives were built for a section.
- A new [Mix Task](https://hexdocs.pm/mix/1.12.3/Mix.Task.html) is created for building all the contained objectives for the existing sections. You can run it with `mix create_contained_objectives` in the console.
The remaining two PRs will include the changes for automatically building the contained objectives when a section …

[MER-2573] Task to create contained objectives for existing sections

---

lib/oli_web/controllers/page_delivery_controller.ex

This is a minor change to the error message that admin's get when trying to preview an adaptive lesson.
Before:
After:

[Enhancement] Changed error message wording on admin adaptive preview

---

lib/oli/institutions.ex
lib/oli_web/live/admin/institutions/index_live.ex
test/oli/institutions_test.exs
test/oli_web/live/admin/institutions/index_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-2410?focusedCommentId=21238) to the ticket's comment
https://github.com/Simon-Initiative/oli-torus/assets/74839302/9e565066-19b9-474f-b525-b3f4a2e68efc
https://github.com/Simon-Initiative/oli-torus/assets/74839302/d7723246-602d-4824-84bc-0343285f8a21
I also checked that, after the registration is approved, the user is being redirected to the section creation wizard when launching Argos from the Canvas course, as expected:
https://github.com/Simon-Initiative/oli-torus/assets/74839302/c9b31fe8-1b3e-493c-9ca9-3546797fc891
I found that the modal's cancel button was not working, so this PR also fixes that bug.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/147d8bbc-6a54-419e-9d33-19f392afc762 …

[BUGFIX][MER-2410] New Institution not being created after approving registration

---

assets/src/apps/scheduler/PageDragBar.tsx
assets/src/apps/scheduler/PageScheduleLine.tsx
assets/src/apps/scheduler/date-utils.tsx

Steps to reproduce:
1. Have a section with a short duration, just a couple weeks
2. Use the scheduler
3. Set an available & due date for an item
Expected: the blue bar goes between the icons
Actual: The blue bar extends past the end date.
This was because the bar was being drawn to the end of the due-date instead of the start of the due date. On schedules that span large amounts of time, it was not noticeable. On schedules spanning only a few weeks, it looked very wrong.
After:
Also fixed:
1. Have your computer clock set to a month with 30 days
2. Try to drag to the 31st day in a month with 31 days
Expected: You can drag to the 31st day
Actual: It goes to the 1st day of the month you dragged to
This was caused by us setting the day of a date before the month. The internal date object …

[Bugfix] Render bar between dates correctly

---

lib/oli/delivery.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/contained_objectives_builder.ex
lib/oli_web/controllers/open_and_free_controller.ex
lib/oli_web/live/new_course/new_course.ex
test/oli/delivery/sections/contained_objectives_builder_test.exs
test/oli/delivery/sections_test.exs
test/oli/delivery_test.exs
test/oli_web/controllers/open_and_free_controller_test.exs
test/support/test_helpers.ex

[MER-2574](https://eliterate.atlassian.net/browse/MER-2574)
This is the second of a series of three PRs to setup and use contained objectives on Torus.
The new `contained_objectives` table will be used as a support for optimizing queries and finding which objectives are attached to a container in an easier way.
This PR adds the creation of contained objectives in the following three scenarios:
1. When a section is created.
2. When a project update is applied to a section.
3. When a section is remixed.
[MER-2574]: https://eliterate.atlassian.net/browse/MER-2574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2574] Calculate contained objectives on section actions

---

lib/oli/accounts.ex
test/oli/accounts_test.exs
test/oli_web/pow/pow_test.exs

Function `Oli.Accounts.is_lms_user?/1` incorrectly assumed that email addresses are unique across all users.  They are only unique for **non LMS users**.  This PR reworks that implementation.

[BUG FIX] fix cardinality assumption in Accounts.is_lms_user?/1 [MER-2576]

---

lib/oli/delivery/metrics.ex

The scored activities view impl specialized the counting of page attempts for V2 sections incorrectly.  It was counting total activity attempts, when all that we want is just total page attempts.

[BUG FIX] Fix attempt count [MER-2616]

---

assets/styles/authoring/layout/workspace.scss

Fixes an issue where Titlebar zindex was greater than the sidebar menu.

[MER-2620] z-index issue between the page title and the create menu modal

---

assets/styles/common/elements.scss

Adjusts the code block font size to be more readable.
Before:
After:

[MER-2617] Codeblock text appears too small

---

lib/oli/institutions/pending_registration.ex

If values entered into the LTI registration form contain leading or trailing spaces, this can result in a 500 error from torus. These spaces can be hard to identify when approving a request, therefore this PR trims the values given so that these fields are guaranteed to not have this issue.

[BUG FIX] [MER-2619] Hidden spaces in LTI Registration form values can cause 500 error on launch

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section_resource.ex
lib/oli_web/live/sections/assessment_settings/settings_table_model.ex

[MER-2612](https://eliterate.atlassian.net/browse/MER-2612)
This PR fixes the default scoring strategy shown on the Assessment Settings page when an assessment has no scoring strategy set.
Since there was not an option in the select for when the scoring strategy is not set (is `nil`), the select was taking the first option (`Average`) as the default one.
[MER-2612]: https://eliterate.atlassian.net/browse/MER-2612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2612] Scoring in assessment settings defaulting to average

---

lib/oli/rendering/content/selection.ex

[MER-2570](https://eliterate.atlassian.net/browse/MER-2570)
Fixed a couple of bugs when rendering the project preview. 
- Error when calling `DeliveryResolver` instead of calling `AuthoringResolver`. This was failing when you have one selection criteria for an activity bank by objective and there is no objective added in the activity banks.
- Error when applying a selection criteria by item type and there is no such activity in the activity bank.
[MER-2570]: https://eliterate.atlassian.net/browse/MER-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2570] Fix error accessing project preview

---

assets/src/components/activities/common/hints/delivery/HintsDeliveryConnected.tsx

Changed the ordering of the checks within the `HintsDeliveryConnected` component to ensure that if we are in a graded page that we do not show hints.

[BUG FIX] never show hints in graded context [MER-2624]

---

lib/oli_web/live/sections/enrollments_table_model.ex

Due to some very specific logic in the table model, a few columns were not rendering if the user had an active authoring session.  I've removed that logic, allowing "Last Interacted" and all the other columns to always render.

[BUG FIX] Remove author specific columns [MER-2623]

---

lib/oli/utils/slug.ex
test/oli/utils/slug_test.exs

If a title of a revision only contains non-alphanumeric characters, the slug generated was the empty string, which was downstream breaking assertions about uniqueness.  This edge case is handled by generating a random slug.

[BUG FIX] Empty slugs [MER-2625]

---

lib/oli/resources/collaboration.ex
lib/oli_web/live/collaboration_live/collab_space_view.ex
lib/oli_web/live/collaboration_live/instructor_table_model.ex
test/oli_web/live/collaboration_live_test.exs
test/oli_web/live/delivery/instructor_dashboard/discussions/discussions_tab_test.exs

This PR addresses [MER-2639](https://eliterate.atlassian.net/browse/MER-2639) and [MER-2640](https://eliterate.atlassian.net/browse/MER-2640)
A flash message is only shown to the user that triggers the action (the post creation for example). 
https://github.com/Simon-Initiative/oli-torus/assets/74839302/deffa160-32d7-43aa-a820-cb208f574a40
While working on the ticket I realized a similar bug occurred when another user left the collab-space, or when an instructor approved a post, etc.
All bugs had the same root cause; while handling the broadcast message in the `handle_info` callbacks, we were not indicating the user that triggered the action in order to prevent showing the flash message to other users connected to the same collab-space. …

[MER-2639] Post created flash appears in all active user windows

---

lib/oli/activities/realizer/logic/expression.ex
lib/oli/delivery/activity_provider.ex
lib/oli/qa/reviewers/selection_worker.ex
lib/oli_web/controllers/activity_bank_controller.ex
lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live/qa/qa_live.ex
lib/oli_web/live/qa/warning_details.ex
lib/oli_web/live/qa/warning_summary.ex

[Link](https://eliterate.atlassian.net/browse/MER-2550?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug,%20Story)%20AND%20status%20in%20(%22In%20Progress%22,%20PR,%20Ready,%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20priority%20DESC,%20status%20ASC,%20created%20DESC) to the ticket, that complements the work done at [MER-2570](https://github.com/Simon-Initiative/oli-torus/pull/4244)
This ticket was asked for V0.26 (that's why it targets to `master` branch). Maybe we should implement it for V0.25 (and target it to `prerealase-v0.25.0` branch) as it complements the work done by Santi for v0.25.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/f3712bf8-4f4f-4962-90ab-40ba51f5238c
https://github.com/Simon-Initiative/oli-torus/assets/74839302/9c …

[MER-2550] Preview with activity bank shows error

---

lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
lib/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab.ex
lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex
priv/repo/migrations/20221020142919_add_blueprint_table.exs
test/oli_web/live/delivery/instructor_dashboard/reports/learning_objectives_tab_test.exs
test/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab_test.exs

[MER-2575](https://eliterate.atlassian.net/browse/MER-2575)
This is the last of the series of three PRs that create contained objectives for optimizing queries and reimplement the "Filter by Module" feature in the Learning Objectives tab, either from the Instructor Dashboard or from the Students Dashboard. There are two different scenarios. The first one considers a section that has contained objectives caused by the migration script being run or because it is a newly created section. The second is an old section that has no contained objectives yet.
**Scenario 1:** Section migrated with contained objectives.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/e141f45b-dd2f-4e35-b3ea-520161e3fa53
**Scenario 2:** Legacy section without contained objectives yet. …

[MER-2575] Implement Filter By Module in Learning Objetives tab

---

CHANGELOG.md
lib/oli/institutions.ex
lib/oli_web/templates/institution/show.html.eex
lib/oli_web/templates/layout/live.html.leex
lib/oli_web/templates/registration/show.html.eex

Fixes an issue where admin attempting to create a new institution when an existing registration with the same issuer and client_id crashes.
I tested simply dropping the index constraint but unfortunately it does not resolve the issue. While it does allow the new institution and registration to be created, it creates a new issue on LTI launch where the system expects only a single registration with issuer and client_id to exist. A code change is required to fix this.
The new approach taken here is for the system to check on institution creation if a registration already exists for a given issuer client_id and if so, continue to create the new institution but reuse the existing registration. The system was already doing this in a previous code path but the enhancements made to allow …

[BUG FIX] [MER-2643] Creating new institution with same issuer and client_id fails

---

assets/src/components/delivery/CourseContentOutline.tsx
lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/nav_sidebar.ex

This PR adds default "module," "unit," "section," or custom labels to the student delivery course left navigation menu. It also renders index or page numbers in the navigation UI.

[FEATURE][MER-2142] Add labels to course navigation

---

assets/src/components/activities/custom_dnd/CustomDnDAuthoring.tsx
assets/src/components/activities/custom_dnd/utils.ts

This adjusts the custom Drag-and-Drop stylesheet used for newly authored DnDs by setting text color style of black on the initiators to ensure the text remains visible against the yellow background in dark mode.
This has no effect on migrated or previously authored DnDs. It is just for newly created ones. 
Also includes slight adjustments to on-screen messages shown to author. In particular, removed the implication that part IDs are associated with targets which is now incorrect: on any newly created DnD, it is the initiators that carry part IDs.  Older  DnDs might have used the targets-as-parts model, so simply avoid saying which element carries part Id.

 [ENHANCEMENT] Style new DnDs so text remains legible in dark mode [MER-2652]

---

lib/oli/delivery/attempts/core.ex
lib/oli/delivery/attempts/core/resource_attempt.ex
lib/oli/delivery/attempts/page_lifecycle.ex
lib/oli_web/controllers/page_delivery_controller.ex
test/oli/delivery/attempts/was_late_test.exs
test/oli/delivery/attempts_test.exs
test/oli/delivery/evaluation/explanation_test.exs
test/oli/delivery/submission_test.exs
test/oli_web/controllers/page_delivery_controller_test.exs
test/support/test_helpers.ex

Fixes an issue where multiple attempts with same attempt_number were being created, possibly when user uses browser back/forward,  simultaneous requests to 'Start Attempt'.
The addition of a unit test and the changes required to support the new transaction SQL statement in the test infra are more invasive than the change itself. It might be worth considering if the test is even worth it in terms of changes required or not. The functionality and tests are split between 2 commits so it would be easy to remove them if we decide they are not.

[BUG FIX] [MER-2633] Duplicate Quiz X results in a stuck attempt so student cannot start another attempt

---

.github/actions/torus-builder/action.yml
.github/workflows/torus-builder.yml
CHANGELOG.md

This PR adds a note to the change log to indicate required infrastructure changes so that we remember to apply them. It also re-add the ability to tag the torus-builder image.
After landing this PR, torus-builder action should be run with the tag `1.3.2`

[CHORE] Add a note to changelog indicating required infrastructure changes

---

lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/controllers/pow/session_html/new.html.heex
lib/oli_web/pow/user_routes.ex
lib/oli_web/templates/delivery/enroll.html.heex
test/oli_web/controllers/delivery_controller_test.exs
test/oli_web/pow/pow_test.exs
test/support/test_helpers.ex

[MER-2592](https://eliterate.atlassian.net/browse/MER-2592)
Addresses https://github.com/Simon-Initiative/oli-torus/issues/4174
When a student or instructor tries to enroll in a section via an invitation link and is not logged in yet, it redirects to the Sign In page without showing the Author Sign-in box.
Before:
After:
[MER-2592]: https://eliterate.atlassian.net/browse/MER-2592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2593] Hide author sign in box when coming from invitation link as student/instructor

---

lib/oli/delivery/sections.ex

[MER-2676](https://eliterate.atlassian.net/browse/MER-2676)
Split the section resources creation in chunks to avoid hitting the Postgres max params limit.
[MER-2676]: https://eliterate.atlassian.net/browse/MER-2676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2676] Section creation from product fails when product exceeds certain size

---

lib/oli_web/controllers/page_delivery_controller.ex

This PR fixes the sorting of the submitted attempts by using `DateTime.before?/2` instead of directly comparing the two datetimes.

[BUGFIX] Sort attempts by date submitted

---

lib/oli/delivery/paywall.ex
lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/actions/actions.ex
lib/oli_web/components/modal.ex
lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex
test/oli_web/live/delivery/student_dashboard/components/actions_tab_test.exs
test/oli_web/live/delivery/student_dashboard/student_dashboard_live_test.exs

[MER-2589](https://eliterate.atlassian.net/browse/MER-2589)
Addresses https://github.com/Simon-Initiative/oli-torus/issues/4158
Allow instructors to re-enroll previously suspended students. The Actions tab in the Student Dashboard is no longer hidden for instructors when a student is suspended. Instead, it now has a **"Re-enroll"** button.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/e8ad8698-7f32-4e90-b0b6-c5a0d88d490a
This also fixes an issue on the Modal function component whose css classes were not properly set on Dark mode.
Modal before the fix:
[MER-2589]: https://eliterate.atlassian.net/browse/MER-2589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2589] Re-enroll students from Student Dashboard

---

lib/oli/resources/collaboration.ex
lib/oli_web/live/collaboration_live/collab_space_config_view.ex
lib/oli_web/live/projects/overview_live.ex
lib/oli_web/live/sections/overview_view.ex
test/oli/resources/collaboration_test.exs
test/oli_web/live/collaboration_live_test.exs
test/oli_web/live/sections/overview_live_test.exs

Link to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/b23600a1-1630-4f7b-af9f-ce0664482550
https://github.com/Simon-Initiative/oli-torus/assets/74839302/d596c1a2-53d7-438e-a410-c9bfd8287059
Note that the confirmation modal renders a form to provide the collab space configuration that will be bulk-applied to all pages.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/616b14eb-6b10-4ada-9273-339e8d332a71
https://github.com/Simon-Initiative/oli-torus/assets/74839302/7bc6209b-fe67-4518-8143-583e2f81f2fc

[MER-2595] Enable discussion activity for all pages

---

lib/oli_web/controllers/lti_controller.ex
test/oli_web/controllers/lti_controller_test.exs

[MER-2591](https://eliterate.atlassian.net/browse/MER-2591)
Addresses https://github.com/Simon-Initiative/oli-torus/issues/4169
Update JSON configuration on the `developer_key_json` LTI endpoint for Canvas:
1. Modify the Canvas JSON integration so OLI Torus does not appear in the navigation menu by default.
2. Ensure OLI Torus links always open in a new browser tab.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/2c14ea0d-8cca-42ae-96d6-64facc8edd27
[MER-2591]: https://eliterate.atlassian.net/browse/MER-2591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2591] Update Canvas JSON for new integrations

---

assets/src/components/activities/AuthoringElementProvider.tsx
assets/src/data/activities/model/responses.ts

This bug was intermittent and presented in different ways. The most reliable way I was able to get it to occur:
1. Add an MCQ to a basic page
2. Go to the answer key
3. Start a metronome @ 62BPM
4. Every beat, type 4 or 5 characters by quickly rolling across the keyboard.
Usually, around beat 15, you will get a console error message
```
{
"name": "AssertionError",
"actual": false,
"expected": true,
"operator": "==",
"message": "obj needs to be an object",
"generatedMessage": false
}
```
At this point, the application would still be functioning correctly.
After another 10 or so beats of typing, you would start getting that error every single keypress. It's at this point that the editor became unresponsive.
The error occurs in the internals of jsonpath called from responses.ts around line …

[Bugfix] editor lockup [MER-2682]

---

lib/oli/delivery/attempts/page_lifecycle/graded.ex

Adds back in the call to `mark_progress_completed` which got removed as part of hotfix v0.25.1
This was causing graded pages which roll up to be `:evaluated` to not have their progress set to 100%

[BUG FIX] Restore progress setting

---

assets/src/components/editing/editor/Editor.tsx
assets/test/editor/validate_editor_content_test.ts

There was some content that had an extra model object in the content hierarchy. Upon examining torus, I couldn't figure out where it was coming from. The current theory is that this content actually came from a bad import ~11 months ago. To fix this, we will now detect & fix this type of content.
A hint from current software:
```
{
"content": [
{
"children": [
{
"text": ""
}
],
"id": "2852515758",
"type": "p"
}
],
"editor": "slate",
"id": "2322934457"
}
A hint from that lesson:
{
"content": {
"model": [
{
"children": [
{
"text": ""
}
],
"type": "p"
}
]
},
"id": "1862042623"
}
```

[Bugfix] activity editor crash [MER-2689]

---

config/config.exs
config/runtime.exs
oli.example.env

This PR add an environment variable `APPSIGNAL_ENABLE_LOGGING` to enable logging to appsignal for easier production debugging
https://docs.appsignal.com/logging/platforms/integrations/elixir.html

[CHORE] allow option to enable appsignal logging

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section.ex
lib/oli_web/live/products/details/content.ex
priv/repo/migrations/20231023142303_add_apply_major_updates_to_sections.exs
test/oli/sections_test.exs
test/oli_web/live/products_test.exs

[MER-2680](https://eliterate.atlassian.net/browse/MER-2680)
Add a new `apply_major_updates` field to sections that can be toggled from the Products Overview page, and controls how updates are applied to a course section created from a Product. 
https://github.com/Simon-Initiative/oli-torus/assets/26532202/46771284-3969-4d61-9e0c-f8e13baac3f8
[MER-2680]: https://eliterate.atlassian.net/browse/MER-2680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2680] Allow product setting for receipt of major updates

---

lib/oli/lti/registration.ex
lib/oli/utils.ex
test/oli/institutions_test.exs

[MER-2619](https://eliterate.atlassian.net/browse/MER-2619)
Trim registration fields on edit.
**Before changes:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/e721f1d8-8b84-4b8a-a7eb-915395ed747a
**After changes:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/45f99f0d-4f47-4845-8294-525fce4c8414
[MER-2619]: https://eliterate.atlassian.net/browse/MER-2619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2619] Fix registration changeset function to trim editable fields

---

lib/oli_web/components/delivery/instructor_dashboard.ex
lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/delivery/user_account_menu.ex
lib/oli_web/components/header.ex
lib/oli_web/live/delivery/student_dashboard/components/helpers.ex
lib/oli_web/router.ex
priv/repo/migrations/20231010144119_add_prompt_templates.exs

Deploying to stellarator indicated that the DB application user does not have sufficient privileges in RDS to enable certain extensions so this must be enabled manually by a super user. This PR removes the `CREATE EXTENSION vector` SQL statement from the migration so that when RDS blocks this call the entire migration does not fail. We will have to add this to the list of manual steps required for `nextgen-ux` when deploying.
This statement must be run manually by a database superuser:
```
execute "CREATE EXTENSION IF NOT EXISTS vector"
```
I also uncovered an issue trying to access the new `/ng23/...` route related to sessions. There were a bunch of unnecessary plugs being invoked and so I pared this down to only the minimum required ones, using the LiveSessionPlugs to dictate all …

[CHORE] add try rescue around extension

---

lib/oli_web/live/common/paged_table.ex
lib/oli_web/live/resources/pages_table_model.ex
lib/oli_web/live/resources/pages_view.ex

[MER-2695](https://eliterate.atlassian.net/browse/MER-2695)
Fix the `Move to` functionality in the All Pages view, causing duplicate pages when trying to move a page from one container to another.
This PR also fixes a styling issue that was causing the 'Actions' dropdown to be hidden.
**Before changes:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/6a85406e-1d5e-4510-bcbb-e668e0f5af54
**After changes:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/5f234616-d441-48de-b84a-14856ed9701b
[MER-2695]: https://eliterate.atlassian.net/browse/MER-2695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2695] Fix 'Move to' functionality on All Pages view

---

assets/css/app.css
assets/css/ng23.css
assets/src/hooks/index.ts
assets/src/hooks/scroll_to_target.ts
lib/oli_web/components/delivery/utils.ex
lib/oli_web/live/delivery/student/content_live.ex

This is the first PR for the student's course content page. 
https://github.com/Simon-Initiative/oli-torus/assets/74839302/c5d51361-0253-4247-a7b6-9c3354a3da19
Ingested project: 
[chemisty_general1_trunk-out.zip](https://github.com/Simon-Initiative/oli-torus/files/13180635/chemisty_general1_trunk-out.zip)
CSV to ingest to project (slugs must be replaced with the ones of the project csv export):
[chem_csv_custom_ok.csv](https://github.com/Simon-Initiative/oli-torus/files/13180642/chem_csv_custom_ok.csv)
In future PRs we have to:
* Render a video (from youtube or by the provided URL in the revision)
* Cache the section hierarchy in a new field of that table
* Show real student progress and already visited pages
* Implement Dark Mode
* Add tests

[NG23-11] Course content

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/deploy.yml

This PR fixes an issue with dev-container initialization and also adds the new server to CD deploy targets

[CHORE] Fix dev-container initialization and update deploy targets

---

lib/oli_web/live/delivery/student/content_live.ex
test/oli_web/live/delivery/student/content_live_test.exs

This PR allows the student to expand more than one module from different units, to match the behaviour of the Figma designs.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/0d0a69d8-ff03-4de6-8e3d-0ca3e37995af
https://github.com/Simon-Initiative/oli-torus/assets/74839302/c3867df5-9ccc-499b-a66c-f62bba98fd83

[NG23] Course content: allow to expand multiple modules

---

lib/oli_web/templates/layout/live.html.leex
test/oli_web/live/collaboration_live_test.exs

[MER-2651](https://eliterate.atlassian.net/browse/MER-2651)
This PR fixes the bug in flash messages when they appear. 
They had a sticky class applied to them and were fixed at the top level of the view causing interposition of elements.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/5f7f6747-8c96-42b1-9068-fbefdd44bedc
https://github.com/Simon-Initiative/oli-torus/assets/16328384/c1aa12db-64d7-49b4-8ad6-f280555ac6fb
[MER-2651]: https://eliterate.atlassian.net/browse/MER-2651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2651] Fix sticky flash message

---

config/config.exs
lib/oli/delivery/sections.ex
lib/oli_web/controllers/api/scheduling_controller.ex
lib/oli_web/live/delivery/rebuild_full_hierarchy_worker.ex
test/oli/sections_test.exs
test/oli_web/controllers/api/scheduling_controller_test.exs

This PR adds an Oban Worker to allow rebuilding full_hierarchy async.
This rebuild_full_hierarchy in async mode is used when the instructor re-schedules the course:

[NG23] Trigger rebuild full hierarchy on section re schedule

---

assets/tsconfig.json
assets/yarn.lock

This reverts commit 9f1db3dd02b21fe2c220137b6cd7ef17d195d54c.

Revert "Bump browserify-sign from 4.2.1 to 4.2.2 in /assets (#4364)"

---

assets/src/components/common/DeliveryElementRenderer.tsx
assets/src/data/content/writers/renderer.tsx
lib/oli/rendering/content.ex
lib/oli/rendering/content/html.ex
lib/oli/rendering/content/plaintext.ex
test/oli/editing/page_editor_test.exs
test/oli/rendering/alternatives/html_test.exs
test/oli/rendering/page/html_test.exs

There were three issues:
1. The `<div dir="rtl">` tag was being logically inserted at the wrong level of abstraction.
2. The popup element was being rendered as a block element instead of inline
3. The new div with the direction, was causing content within paragraph elements to be styled incorrectly

RTL text bug fixes [MER-2703]

---

lib/oli_web/live/sections/gating_and_scheduling.ex
lib/oli_web/live/sections/overview_view.ex
test/oli_web/live/sections/gating_and_scheduling_test.exs
test/oli_web/live/sections/overview_live_test.exs

[MER-2694](https://eliterate.atlassian.net/browse/MER-2694)
This PR removes access to the `Gating and Scheduling` view from the Manage Section view. 
Also, descriptions provided in the ticket describing the intended use cases are added.
**Light Mode**
**Dark Mode**
[MER-2694]: https://eliterate.atlassian.net/browse/MER-2694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE][MER-2694] Add description to advanced gating scheduling ux

---

.github/actions/torus-builder/Dockerfile
assets/src/adaptivity/scripting.ts

The issue was a typescript related compilation error.
```
ERROR in /app/assets/src/adaptivity/scripting.ts
./src/adaptivity/scripting.ts 13:46-88
[tsl] ERROR in /app/assets/src/adaptivity/scripting.ts(13,47)
TS2569: Type 'IterableIterator<string>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
ts-loader-default_8e11959e0762e3a1
@ ./src/adaptivity/rules-engine.ts 72:18-40
@ ./src/adaptivity/rules.ts 3:21-46
webpack 5.76.0 compiled with 1 error in 10896 ms
```
This issue was outlined in https://github.com/Microsoft/TypeScript/issues/8856. There are a few solutions proposed. One is compiling with the `--downlevelIteration` flag as the error message indicates, but this can cause adverse performance effects. I ultimately …

[CHORE] Fixes the CI package build step

---

lib/oli/delivery/paywall.ex
lib/oli/delivery/sections/blueprint.ex
lib/oli_web/live/common/text_search.ex
lib/oli_web/live/products/payments/table_model.ex
lib/oli_web/live/products/payments_view.ex
lib/oli_web/live/products/products_tabel_model.ex
lib/oli_web/live/products/products_view.ex
lib/oli_web/live/projects/projects_live.ex
priv/repo/migrations/20231107183704_add_crockford_base32_encode_function.exs
test/oli/delivery/paywall_test.exs
test/oli/delivery/sections/blueprint_test.exs
test/oli_web/live/payments_live_test.exs
test/oli_web/live/products_test.exs

[MER-2556](https://eliterate.atlassian.net/browse/MER-2556)
Refactor payment and product views to use a browsing approach, so that all the records are not loaded in memory.
With these changes every time a user performs any operation on these tables, it executes a DB query only to retrieve the desired rows.
**Payments view:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/e4783229-a899-4cc9-9379-f8a807194bef
**Products view:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/69cf1dfc-ec91-4dec-ac1a-af1c07f64bb5
[MER-2556]: https://eliterate.atlassian.net/browse/MER-2556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2556] Convert products and payments views to use DB powered tables

---

lib/oli/delivery.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/blueprint.ex
lib/oli/delivery/sections/section.ex
lib/oli/resources/revision.ex
lib/oli/utils/db_seeder.ex
lib/oli_web/components/delivery/deliberate_practice_card.ex
lib/oli_web/components/delivery/deliberate_practice_list.ex
lib/oli_web/components/delivery/nav_sidebar.ex
lib/oli_web/controllers/open_and_free_controller.ex
lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live/curriculum/entries/options_modal.ex
lib/oli_web/live/new_course/new_course.ex
lib/oli_web/router.ex
lib/oli_web/templates/page_delivery/deliberate_practice.html.heex
priv/repo/migrations/20231112194542_add_has_practice.exs

This PR adds a new page purpose type "Deliberate Practice".  This new purpose type works almost the same as "Explorations": any page designated as "Deliberate Practice" will show up in a list when the student accesses the navbar "Practice" menu.

[FEATURE] Deliberate practice purpose type and impl [MER-2720]

---

lib/oli/utils/database.ex

Fix here is to handle both `nil` and actual lists being returned from `Repo.insert_all`
Tested locally with REAL CHEM GATES and does allow pushing of major updates

[BUG FIX] Allow processing of large, major updates [MER-2738]

---

config/config.exs
lib/oli_web/live/admin/admin_view.ex
lib/oli_web/live/features/features_live.ex

This PR adds an Admin UI which allows the changing of the system logging level at runtime. 
The rationale here is that we likely should be running production with a higher logging level (i.e. logging less information) and only when we are trying to trouble shoot a problem will we increase the verbosity, temporarily.  This is to counter cases where the Logging process within the system becomes overwhelmed and begins queuing log messages in memory.

[FEATURE] allow runtime log level changing [MER-2742]

---

assets/src/components/activities/short_answer/sections/NumericInput.tsx
lib/oli/delivery/evaluation/rule.ex
test/oli/delivery/evaluation/rule_eval_test.exs

[MER-2557](https://eliterate.atlassian.net/browse/MER-2557)
This PR modifies the way to check the precision of an activity input result.
To check the precision, we take the definition of `precision` given in the stack overflow link in the [ticket description](https://eliterate.atlassian.net/browse/MER-2557).
- As an example, the correct result for the following activity should be 0.36, with a precision of 2.
- Activity resolution.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/5cd56647-1de4-4baa-a8fa-ad3ed14a10fe
[MER-2557]: https://eliterate.atlassian.net/browse/MER-2557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2557] Precision not working as expected

---

lib/oli/analytics/datashop.ex
lib/oli/analytics/datashop_export_worker.ex
lib/oli/authoring/course.ex
lib/oli/delivery/sections/blueprint.ex
lib/oli/delivery/sections/browse.ex
lib/oli/delivery/sections/browse_options.ex
lib/oli_web/components/project/async_exporter.ex
lib/oli_web/live/admin/institutions/sections_and_students_view.ex
lib/oli_web/live/datashop/analytics_live.ex
lib/oli_web/live/datashop/table_model.ex
lib/oli_web/live/projects/overview_live.ex
lib/oli_web/live/sections/sections_view.ex
lib/oli_web/router.ex
test/oli/delivery/sections/browse_test.exs
test/oli_web/controllers/cognito_controller_test.exs
test/oli_web/live/datashop/analytics_live_test.exs
test/oli_web/live/ingest_live_test.exs
test/oli_web/live/projects/overview_live_test.exs

[MER-2730](https://eliterate.atlassian.net/browse/MER-2730)
Part 1 of a series of 2 PRs to improve the Datashop Export experience.
Introduced changes:
- Move the Datashop Export functionality to a new LiveView
- Allow generating a project Datashop export for only a specific subset of sections based on that project.
The rest of the changes will be addressed on a separate PR ([MER-2731](https://eliterate.atlassian.net/browse/MER-2731))
https://github.com/Simon-Initiative/oli-torus/assets/26532202/64b9bec5-ad1f-4c9e-afea-72b16d55ee39
[MER-2730]: https://eliterate.atlassian.net/browse/MER-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-2731]: https://eliterate.atlassian.net/browse/MER-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

[MER-2730] Create new Datashop Analytics view

---

lib/oli_web/components/delivery/instructor_dashboard.ex
lib/oli_web/live/delivery/student_dashboard/components/helpers.ex

This PR adds the `aria-label` attribute to allow users of screen readers to understand the purpose of the help icon button.

[ENHANCEMENT] add aria-label to help buttons [MER-2726]

---

config/config.exs
config/runtime.exs
lib/oli/analytics/datashop.ex
lib/oli/analytics/datashop_export_worker.ex
lib/oli/application.ex
lib/oli/authoring/broadcasting/broadcaster.ex
lib/oli/authoring/broadcasting/messages.ex
lib/oli/authoring/broadcasting/subscriber.ex
lib/oli/datashop_cache.ex
lib/oli_web/components/project/async_exporter.ex
lib/oli_web/live/common/sortable_table/table.ex
lib/oli_web/live/datashop/analytics_live.ex
test/oli_web/live/datashop/analytics_live_test.exs

[MER-2731](https://eliterate.atlassian.net/browse/MER-2731)
Second PR for improving the Datashop export feature (first PR https://github.com/Simon-Initiative/oli-torus/pull/4459)
It introduces the following changes:
- Process the Datashop export process in batches, showing the number of batches processed in real time.
- Use a Cache for storing intermediate data.
- Some UI/CSS improvements.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/46d4d78c-4699-4bec-8a49-59c0d499625e
[MER-2731]: https://eliterate.atlassian.net/browse/MER-2731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2731] Remove max limits on Datashop download and add caching

---

lib/oli_web/components/delivery/nav_sidebar.ex
lib/oli_web/templates/layout/page.html.heex

This PR fixes footer positioning when rendered within nav sidebar layout above "lg" breakpoint.
**The issue**
The layout's content slot has 200px of left-padding to accommodate the sidebar. The footer has absolute position to make it sit over its container's (seemingly unnecessary) bottom padding. That same container was missing `position: relative`, so the footer's `left: 0` was at the layout's left border - underneath the sidebar.
Before:
After:
[EDIT]: This does not seem related to [issue 3635](https://github.com/Simon-Initiative/oli-torus/issues/3635) after all. That issue concerns Project Overview page, which uses a different layout (also, I wasn't able to replicate it, so maybe it got fixed).
**Note**
In the long term, my recommendation would be to make the layout responsible for …

[FIX] Footer positioning within nav_sidebar layout

---

assets/styles/common/purpose.scss
assets/tailwind.theme.js

This PR adjusts styles of purpose groups ("Example", "Did I get this?" etc). New icons come from Font Awesome Free, so I've just replaced the char codes.
**Before:**
**After (dark):**
**After (light):**

[Fix] UX audit - Purpose group rendering

---

assets/css/bootstrap-shims.css
assets/styles/delivery/multi-input.scss
assets/tailwind.theme.js

This PR adjusts input styles - colors, spacings and text overflow. I tried to keep splash damage to a minimum, so some changes are limited to `.multi-input-activity`.
**Before:** <sub>(yes, I know - sulphur is not a compound)</sub>
**After (light):**
**After (dark):**

[Fix] UX audit - Input styles

---

assets/src/components/common/Navbar.tsx
assets/src/components/content/Popup.tsx
assets/styles/common/elements.scss
assets/styles/common/previous_next_nav.scss
assets/tailwind.theme.js

This PR makes a few tweaks to tooltip (popover) styles and primary color:
- tooltips should have max width
- tooltips (stems included) should have proper light/dark colors
- tooltip frame should no longer have pointer interactions - this fixes a hilarious edge case where mousing over an anchor from above would appear to not trigger the popup (this was caused by the frame getting between the cursor and the anchor, causing `mouseLeave` event)
- tooltip stems should now be rendered above frame box shadows (z-index-wise)
- `--color-delivery-primary` should have light and dark variants to help with contrast in some situations (I've added a new-ish shade of blue to the theme - called it "azure" to avoid name conflicts)
**Before (dark - note the box shadow on the tooltip stem):**
**Before (light …

[Fix] UX audit - Tooltip styles

---

assets/src/components/activities/custom_dnd/utils.ts

This PR aims to solve the problem of light/dark mode in the context of drag-and-drop activities. Right now, the draggable bits are utterly unreadable in dark mode. As I understand it, the styles for them are part of each lesson's configuration, so the actual fix would be to use the authoring environment to edit said styles. An additional complication is that DnD has its own shadow DOM - one has to take it into account when writing styles. My proposition is to provide better defaults that will also serve as a hint (because `:host-context()` is not a pseudoselector one uses every day - I know I don't).
An alternative approach would be to inject a prop (`mode: Mode`) into all custom elements like DnD and let them handle it as they see fit.

[Chore] UX audit - Drag-and-drop styles

---

lib/oli_web/components/delivery/students/students.ex
test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs

[MER-2674](https://eliterate.atlassian.net/browse/MER-2674)
This PR introduces two changes on the `Instructor Dashboard > Students tab` page:
1. Fix the sort by progress feature on the Students tab.
2. Sort by progress and student last name as secondary sort criteria.
**Note:**
The Manage Enrollments page as described in the ticket description does not exist anymore, since it was removed on https://github.com/Simon-Initiative/oli-torus/pull/4360
https://github.com/Simon-Initiative/oli-torus/assets/26532202/7210b915-794d-4eb6-bec4-546cf1560ad4
[MER-2674]: https://eliterate.atlassian.net/browse/MER-2674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2674] Fix sort by progress on the Students Tab

---

lib/oli/delivery/experiments/log_worker.ex

Return {:ok, :nothing_to_do} to prevent oban warning message

[BUG FIX] Fix logging spam from worker

---

assets/webpack.config.js
lib/oli_web/components/delivery/practice_activities/practice_activities.ex
test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs
test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs

It seems there are multiple dependencies using multiple versions of the JS library `phoenix_html` tripping up the webpack license check. This fixes the issue by adding the specific version to whitelist

[CHORE] fix webpack license check

---

assets/src/components/common/MathJaxFormula.tsx
lib/oli/rendering/content/html.ex

MathJax 3 doesn't handle embedded LaTeX newline `\\` unless wrapped in `\displaylines{...}` or certain other wrapping constructs. This is expected to be fixed in MathJax 4. Because embedded newlines are used extensively in migrated Chem courses to show multiline derivations in feedback (instances in the hundreds, too numerous to easily fix manually), this PR works around the MathJax 3 defect by rewriting newline-containing LaTeX formulas to wrap in `\displaylines` just before rendering. 
To avoid rewriting when not necessary, applies only when double-backslash followed by some other character (to ignore newlines at end of formula, which occur frequently in Chem instances, perhaps as a result of some auto-generating procedure). Also ignores if formula wrapped in …

[ENHANCEMENT] work around MathJax 3 bug handling LaTeX newlines [MER-2791]

---

lib/oli/delivery/sections.ex

Fixes an issue where the ingest process would crash during product creation if a child resource id was not found in published resources. The temporary workaround was to disable product processing in the ingest pipeline, but that is not a feasible solution in production.
I'm not really sure what the root cause here is so I just put in logic to handle this case gracefully so that the ingest doesn't crash.
Steps to recreate:
1. Export a recent chemistry digest
2. Import the digest and see the ingest process fail without an error message
https://eliterate.atlassian.net/browse/MER-2792

[BUG FIX] [MER-2792] Fix an issue where the ingest process would crash

---

lib/oli_web/live/resources/pages_view.ex

Fixes an issue where "Move to" from all pages view was not working.

[BUG FIX] [TOR-9] [MER-2793] Fix move_item event handling in PagesView

---

assets/src/data/activities/model/rules.ts

Code was sorting answer range rule bounds into low-to-high order on creation/updating. When dynamic variables were used, this wound up sorting them alphabetically, regardless of the order in which they were entered. That could prevent the rule from working since torus rule evaluation requires lower-to-higher numerical order. This PR protects against that case.

[BUGFIX] don't sort range bounds using variables [MER-2819]

---

lib/oli/application.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section_cache.ex
lib/oli_web/live/delivery/student/discussions_live.ex

One of the queries on the explorations, practice and discussions pages `Sections.get_ordered_container_labels` was taking a while to run on load and slowing down responsiveness. This PR adds a JIT caching mechanism for section related data, specifically in this case ordered container labels.

[ENHANCEMENT] [NG23-34] Fix explorations and practice page performance issue

---

assets/css/bootstrap-shims.css

A recent style change makes inputs with the legacy boostrap `form-control` class look disabled. This PR reverts that system-wide style change.
If we want this style to be applied to delivery content, we can create another PR that is more targeted.
Before:
After:

[BUG FIX] [MER-2822] Revert bg change for inputs

---

lib/oli/delivery/sections.ex
lib/oli/utils/seeder/project.ex
test/oli/delivery/sections_test.exs

[MER-2807](https://eliterate.atlassian.net/browse/MER-2807)
This PR fixes the sorting error when getting graded pages. 
The sorting is given first by the schedule date of the assignments and then by the hierarchy order of the assignments themselves.
Feel free to test the functionality to make sure it's what we are looking for.
[MER-2807]: https://eliterate.atlassian.net/browse/MER-2807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2807] Assignments with identical due date are not being sorted correctly

---

lib/oli_web/live/sections/assessment_settings/settings_table.ex
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

[MER-2824](https://eliterate.atlassian.net/browse/MER-2824)
This PR fixes the pagination error that was happening in the `Assignments Settings` view. 
It seems to be conflicting with events that are executed within the same table.
The solution was to move the paging component outside the form that wrap the table to avoid such conflicts.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/57bf3116-dcd2-4555-b862-d3bc603953ed
[MER-2824]: https://eliterate.atlassian.net/browse/MER-2824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2824] Pagination is broken in manage section assignments view

---

lib/oli/delivery/settings.ex
lib/oli_web/controllers/page_delivery_controller.ex
test/oli/delivery/settings_test.exs

[MER-2763](https://eliterate.atlassian.net/browse/MER-2763) 
- When the method **check_settings_before_attempt** in the module page_delivery_controller on the **with** when call **Settings.check_password/2** received_password == **nil**, not allow the student to start the attempt
[MER-2763]: https://eliterate.atlassian.net/browse/MER-2763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-2805] Do not allow an student to start an attempt without a password

---

lib/oli_web/components/delivery/surveys/surveys.ex
lib/oli_web/live/common/paged_table.ex
test/oli_web/live/delivery/instructor_dashboard/overview/surveys_tab_test.exs

[MER-2821](https://eliterate.atlassian.net/browse/MER-2821)
This PR modifies the text displayed when section has no surveys to list in the `surveys` tab of the instructor dashboard. 
[MER-2821]: https://eliterate.atlassian.net/browse/MER-2821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2821] Incorrect message when section has no surveys

---

lib/oli/branding/custom_labels.ex
lib/oli/delivery/hierarchy.ex
lib/oli/delivery/sections.ex
lib/oli/publishing/authoring_resolver.ex
lib/oli/publishing/delivery_resolver.ex
lib/oli/resources/numbering.ex
lib/oli_web/components/delivery/course_content.ex
lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live/projects/customization.ex
lib/oli_web/live/sections/edit_view.ex
test/oli/resources/numbering_test.exs
test/oli_web/controllers/page_delivery_controller_test.exs
test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs
test/oli_web/live/delivery/student_dashboard/course_content_live_test.exs

[MER-2622](https://eliterate.atlassian.net/browse/MER-2622)
Several Students' and Instructors' views did not respect the custom labels set for projects and sections.
The views that were fixed include:
- Course Content Browser
- Scored Activities tab
- Container Preview
[MER-2622]: https://eliterate.atlassian.net/browse/MER-2622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2622] Use custom labels for sections on instructor and student views

---

lib/oli_web/live/common/stepper/stepper.ex
lib/oli_web/live/new_course/new_course.ex
test/oli_web/live/new_course/course_details_test.exs

[MER-2808](https://eliterate.atlassian.net/browse/MER-2808?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug%2C%20Story)%20AND%20status%20in%20(%22In%20Progress%22%2C%20PR%2C%20Ready%2C%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20assignee%20ASC%2C%20status%20ASC%2C%20priority%20DESC%2C%20created%20DESC) 
- The function responsible for creating a section in the new_course module has been placed in a Task.Supervisor. This ensures that when the user leaves the page, the process continues to work in the background, ensuring the successful creation of the section
- In step 3, the 'Create Section' button is disabled while the event is running. A spinner is displayed on the button during the process. Once the process is complete, the system redirects to the …

[MER-2808] - Chem failing to create new course section

---

assets/src/hooks/scroller.ts
assets/src/hooks/slider_scroll.ts
lib/oli/delivery/hierarchy.ex
lib/oli/delivery/sections.ex
lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-36) to the ticket
This PR allows the navigation to a specific resource in the Learn page by providing the "target_resource_od" URL param.
This feature will be used within the page view, to allow the student "go back" and experience an oriented navigation to a specific resource. Also, it will be used to navigate to the next module in the Learn page when the user clicks "next" in the latest resource of a module/unit.
Depending on the resource type, students will experience 4 types of navigations with autoscrolling and pulse animations:
A Y autoscrolling will be triggered until the given unit is focused, and finally, a pulse animation will be shown.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/1a9f3024-25a3-4399-8fe6-14e555c0 …

[NG23-36] Navigate to resource through url params

---

lib/oli/rendering/content/html.ex
test/oli_web/controllers/resource_controller_test.exs

[MER-2778](https://eliterate.atlassian.net/browse/MER-2778)
This PR aims to fix the error that happens when accessing a `hyperlink` from the preview page of a page in a curriculum.
The change fixes the URL that is generated when adding a hyperlink to another section of the course. 
https://github.com/Simon-Initiative/oli-torus/assets/16328384/f35301dc-3568-4e26-8eda-96ebec2ba975
[MER-2778]: https://eliterate.atlassian.net/browse/MER-2778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2778] Fix hyperlink to another page

---

assets/src/hooks/email_list.ts
lib/oli_web/components/delivery/students/students.ex
lib/oli_web/components/email_list.ex
test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs

This PR should fix the bug reported in [MER-2839](https://eliterate.atlassian.net/browse/MER-2839) and others.
The list of bugs found are:
1. When an email is duplicate in the list
2. When an email is added, deleted and added it again
3. When triggering the Role dropdown
These can be tested on the UI.
Another bug that can only be seen on the backend or using the devs tool on a browser is sending 2 `add_enrollments_update_list` events for conditions 1 and 2 from the previous list.
[MER-2839]: https://eliterate.atlassian.net/browse/MER-2839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MER-2839 adding repeated email addresses crash enrollment invitation modal

---

assets/src/components/delivery/CourseContentOutline.tsx
lib/oli_web/components/delivery/nav_sidebar.ex

[MER-2765](https://eliterate.atlassian.net/browse/MER-2765)
This PR aims to fix the issue caused when an instructor modifies the option `Display curriculum item numbers`, so, if this option is enabled, the curriculum items should be displayed numbered and if it is disabled, they should not be displayed numbered. 
It happened that in the sidebar, when the course content menu was displayed, this functionality did not work.  
https://github.com/Simon-Initiative/oli-torus/assets/16328384/ca6ba364-6e02-4fbe-aa11-d1d35e38e8a9
[MER-2765]: https://eliterate.atlassian.net/browse/MER-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2765] Module and unit numbers still displayed after hiding them

---

assets/src/hooks/select_listener.ts
lib/oli_web/live/sections/gating_and_scheduling.ex
lib/oli_web/live/sections/gating_and_scheduling/form.ex
test/oli_web/live/sections/gating_and_scheduling_test.exs

[MER-2776](https://eliterate.atlassian.net/browse/MER-2776)
This PR fixes the error that happened in the **create gating condition** view.
When changing the dropdown type to `Finished` the page would crash. 
Also changed the title, breadcrumb and the message that is passed to the paged table when there is nothing to display.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/308a06e0-b0b3-4e67-9aa7-97c6642c4d93
[MER-2776]: https://eliterate.atlassian.net/browse/MER-2776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2776] Cannot create finished gate as instructor

---

assets/src/components/editing/elements/table/table-util.ts
assets/test/editor/table/table_cell_merge_test.ts

If you had a table with 4 columns and 3 rows, then you merge-down the entire first column, and then attempt to merge-down the entire second column, you would mysteriously get an extra column added at the end.
This was due to a bug in the implementation of the `getVisualGrid` function which was supposed to calculate what the visual grid of a table looks like taking into account colspan and rowspan attributes but failed in scenarios like this.
I ended up rewriting the function from scratch using a different algorithm. Luckily, we had a pretty good set of unit tests for this function already.
Video of bug:
https://github.com/Simon-Initiative/oli-torus/assets/333265/0130ca40-7eab-4c67-b2ce-2563453b974d

[BUG FIX] [TOR-63] [MER-2857] Merging table cells not working in some cases

---

lib/oli/delivery/sections.ex
lib/oli_web/live/new_course/new_course.ex

The query that extracted the "contained objectives" from within `Sections.build_contained_objectives` was far too complex (a total cost of over 760 according to the postgres explain).  When run locally in dev environments with little data, the query executed quickly, but when run against realistic data sets (tokamak, heliotron) and over large courses (chem) this query was taking several minutes to execute.  On tokamak, it took 7 minutes. 
This PR breaks apart that single query into individual queries.  One to fetch the section id, one to fetch current contained pages, another to fetch the page-to-activity mapping, and a fourth to fetch the activity-to-objectives mapping.  The two that we really care about are the last two, and now on Tokamak these run very quickly:
```
Dec 20 13:06:22 …
```

[PERFORMANCE] Optimize contained objectives creation

---

lib/oli/accounts.ex
lib/oli_web/components/delivery/students/students.ex
lib/oli_web/controllers/invite_controller.ex
lib/oli_web/router.ex
test/oli_web/controllers/invite_controller_test.exs
test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs

This PR covers the bug reported in ticket [MER-2758](https://eliterate.atlassian.net/browse/MER-2758) where students cannot be enrolled by an instructor/admin.
The endpoint `post("/:section_slug/enrollments", InviteController, :create_bulk)` was moved from an admin scope to the `/sections/:section_slug/instructor_dashboard` one, otherwise only admins can do the operation and an instructor might not have that type of role.
I would like to understand more the role of the `invited_by_id` field. The current implementation does not have that field set up. It would be helpful to know the function of this field to know best how to set it up. Do they want/need to know whether it was another user or an author? Is it a requirement to identify either the category (user or author) or the specific …

Mer 2758 cannot add enrollment of a student

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery.html.heex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/components/utils.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/page_live.ex
lib/oli_web/live_session_plugs/init_page.ex
lib/oli_web/router.ex
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[NG23-35](https://eliterate.atlassian.net/browse/NG23-35)
This PR lays the foundation for the new lesson view, which will handle a section page rendering and interactions in its final version.
Now it does not render a lesson content but displays the general layout (back button, navigation between pages).
In the following iteration, it will consider the recent changes in the content view, so that it focuses on the right page, unit, or module while navigating back or between pages.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/88b1f1b3-2a8b-407d-a9de-c3a272a5d467
[NG23-35]: https://eliterate.atlassian.net/browse/NG23-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NG23-35] Lesson view with navigation

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/components/utils.ex
test/oli_web/live/delivery/student/lesson_live_test.exs

[NG23-38](https://eliterate.atlassian.net/browse/NG23-38)
Include changes introduced in https://github.com/Simon-Initiative/oli-torus/pull/4520, in a way that when navigating through the lesson view footer and the next or previous page is a container, it redirects to the learn view targeting that unit or module.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/203beace-dbf9-4603-a795-50a1b9c2d862
[NG23-38]: https://eliterate.atlassian.net/browse/NG23-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NG23-38] Lesson view navigation improvements

---

assets/src/components/common/ErrorBoundary.tsx
assets/src/components/editing/SlateOrMarkdownEditor.tsx
assets/src/components/editing/elements/image/block/ImageElement.tsx

Before, if a component in the slate editor threw an error, the editor would crash with an error message and the user might end up being stuck with unrecoverable content.
Now, when this happens, there is a new revert option to go back a step in the editing process.
Demo:
https://github.com/Simon-Initiative/oli-torus/assets/333265/bdd03096-b947-45bf-bf7f-fcf0ad4d8253

[Feature] Editor error boundary improvements [MER-2847]

---

lib/oli/delivery/sections.ex
lib/oli_web/common/format_date_time.ex
lib/oli_web/components/delivery/layouts.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live_session_plugs/init_page.ex
test/oli/delivery/sections_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-39) to the ticket
This PR renders the page content (for non-graded pages) with its corresponding header.
To render the content correctly I had to replace the "navigate" with the common "href" in the navigation links.  With this change, we lost the speed of live navigation within a live_session, but the change was needed to correctly render the different components of the raw page HTML content.
On the other hand, an optimization was made to load only the activity scripts needed for the current page (in the previous page delivery controller version all scripts were loaded without checking which ones were needed, and each script is ~1.5 MB). This optimization compensates (in part) for the speed we lost when removing live_session navigation. …

[NG23-39] Lesson page: render content

---

lib/oli_web/components/delivery/course_content.ex
test/oli_web/live/delivery/student_dashboard/course_content_live_test.exs

[MER-2765](https://eliterate.atlassian.net/browse/MER-2765)
This PR is to fix the bug that was persisting when displaying the course content in the student view. 
With these changes, if the section does not have the option to display item numbering enabled, the resources should not display the numbering mentioned above.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/c91ff196-83e0-4d1b-9f7f-35167c9722d5
[MER-2765]: https://eliterate.atlassian.net/browse/MER-2765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2765] Module and unit numbers still displayed after hiding them in course content

---

lib/oli/analytics/datashop.ex

[MER-2717](https://eliterate.atlassian.net/browse/MER-2717) 
This pull request removes a filter in the 'count' function that contains a query. 
This allows the generation of a export datashop without learning objectives.
[MER-2717]: https://eliterate.atlassian.net/browse/MER-2717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MER-2717-Improve-DataShop-download-feature

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section_resource.ex
test/oli/delivery/sections/blueprint_test.exs
test/support/test_helpers.ex

This PR fixed ticket [MER-2827](https://eliterate.atlassian.net/jira/software/c/projects/MER/issues/MER-2827) where some values were not inherited after creating a section from a product. 
In [these lines](https://github.com/Simon-Initiative/oli-torus/blob/f11379eb4ad9f52aa8060c616f7ebc3e7583ec3d/lib/oli/delivery/sections/section_resource.ex#L113-L128) some values were excluded such as `max_attempts`, `retake_mode` and so on. By doing that, those values were not passed to the created section.
[MER-2827]: https://eliterate.atlassian.net/browse/MER-2827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mer 2827 products assessment settings arent being honored in course setup

---

test/oli_web/live/new_course/course_details_test.exs
test/support/test_helpers.ex

Ticket: [MER-2898](https://eliterate.atlassian.net/browse/MER-2898)
This PR fixes some flaky tests when running the `OliWeb.NewCourse.CourseDetailsTest` module. It looks like there was a race between the execution of [this Task](https://github.com/Simon-Initiative/oli-torus/blob/cfd475aad89d1c363dec46bf311cfaf315225268/lib/oli_web/live/new_course/new_course.ex#L265) and the events happening inside --check [this](https://github.com/Simon-Initiative/oli-torus/blob/cfd475aad89d1c363dec46bf311cfaf315225268/lib/oli_web/live/new_course/new_course.ex#L297) and [this](https://github.com/Simon-Initiative/oli-torus/blob/cfd475aad89d1c363dec46bf311cfaf315225268/lib/oli_web/live/new_course/new_course.ex#L301) and [this](https://github.com/Simon-Initiative/oli-torus/blob/cfd475aad89d1c363dec46bf311cfaf …

HotFix Flaky tests coming from the CourseDetailsTest module

---

lib/oli_web/live/curriculum/container/container_live.html.heex
lib/oli_web/live/resources/pages_view.ex
test/oli_web/live/all_pages_live_test.exs
test/oli_web/live/curriculum/container_test.exs
test/support/test_helpers.ex

[MER-2891](https://eliterate.atlassian.net/browse/MER-2891)
This PR adds buttons to navigate from the `Curriculum` view on the author side to the view that shows `All Pages` of the project and vice versa.
- Curriculum view: Added a button to go to the `All Pages` view.
- All pages view: Added a button to go to the `Curriculum` view.
Also, added some basic tests for the All Pages view.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/02390f95-eeae-4109-bf1d-e508fcbdc1e7
[MER-2891]: https://eliterate.atlassian.net/browse/MER-2891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE][MER-2891] Add link on curriculum page to all pages and vice versa

---

lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
lib/oli_web/templates/layout/page.html.heex
lib/oli_web/templates/page_delivery/index.html.heex

This PR fixes two issues:
1. The student facing "Content Browser", on the home screen, was conditionally being rendered for **only open and free sections**.  It needs to be exist for LMS sections as well. This PR removes the `<%= if @independent_learner do %>` which guarded the rendering of it. 
2. AppSignal has been reporting many instances of a `** (ArgumentError) cannot perform Ecto.Repo.get/2 because the given value is nil` error.  The stack trace points to a problem during the mount of the `CollabSpaceView`, where both `current_user_id` and `current_author_id` attributes of the LV session are `nil`.  My theory is that these session attributes aren't getting populated in certain usage patterns where the user **first** visits a rendered page.  The page rendering comes from a standard …

[BUG FIX] [MER-2907] Show Content Browser for LMS sections, fix CollabSpace rendering issue

---

assets/src/components/content/add_resource_content/AddResourceContent.modules.scss
assets/src/components/content/add_resource_content/AddResourceContent.tsx
assets/src/components/resource/objectives/ObjectivesSelection.tsx

This makes two small usability changes to authoring and fixes one bug.
1. The objectives editor has different placeholder text depending on the situation.
Basic page with no objectives:
Basic page with existing objectives:
Adaptive page either way (they can't be added here):
2. The very last add-content control on a basic page is now always visible. Before, it only appeared when you hovered over it. 
Bugfix:
If you add an objective to an adaptive screen, then delete that objective, the adaptive editor would crash the next time you tried to edit the objectives for that screen.

[Feature] Insert content, and objectives improvements [MER-2888] [MER-2887]

---

lib/oli/interop/export.ex
lib/oli/interop/ingest.ex
lib/oli/interop/ingest/processor/hierarchy.ex
lib/oli/interop/ingest/processor/project.ex
test/oli/interop/digest/_project.json
test/oli/interop/export.exs
test/oli/interop/ingest_test.exs

[MER-2641](https://eliterate.atlassian.net/browse/MER-2641)
This PR aims to add support for exporting a project to include the `attributes` and `customizations` fields. 
Within the `attributes` field the `learning language` feature will be included if the author made changes to it. 
In addition, `customizations` will include any changes to the customisation of labels for containers, **_units_**, **_modules_** and _**sections**_.
Also, support is added to be able to include these project features(attributes and customizations) when ingesting a project(in both versions of the ingest functionality) and have them reflected in the new imported project.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/036cb1d0-9688-41c3-8283-8c888107d34f
[MER-2641]: …

[BUGFIX][MER-2641] Project export-import does not preserve language and custom labels

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-59) to the ticket
Instead of using the Tailwind's `bg-[url(...)]` [arbitrary value](https://tailwindcss.com/docs/background-image#arbitrary-values) (that [sometimes does not work](https://stackoverflow.com/questions/63658218/tailwind-css-backgroundimage-doesnt-work-for-me)), I used [CSS `background-image` property](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) and applied it as `style` directly to the div.
The same module card fix was applied to intro video cards as well.

[NG23-59] Learn poster images not rendering

---

lib/oli/delivery.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/post_processing.ex
lib/oli/delivery/sections/section.ex
lib/oli/delivery/sections/section_resource.ex
lib/oli_web/components/delivery/nav_sidebar.ex
lib/oli_web/live/collaboration_live/collab_space_config_view.ex
priv/repo/migrations/20240109143456_add_contains_discussions_column.exs
test/oli/delivery/sections_test.exs
test/support/test_helpers.ex

Reference: [MER-1886](https://eliterate.atlassian.net/browse/MER-1886)
This PR added the ability to show/hide the discussion part from the navbar. The logic that controls it is based on the `status` field on the `collab_space_config` column in the `section` table.
The flag is trigger by 3 cases: creation of a section, remix of a project or defined by an instructor.
[MER-1886]: https://eliterate.atlassian.net/browse/MER-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mer 1886 discussions remove them from student view if the feature is not turned on

---

lib/oli/rendering/content/html.ex

This corrects code that attempted to apply a workaround for MathJax 3 limitation handling multi-line LaText formulas to correctly escape the initial backslash in the prepended string.

[BUGFIX] correct latex newline workaround [MER-2926]

---

lib/oli_web/live_session_plugs/set_ctx.ex
lib/oli_web/live_session_plugs/set_current_author.ex
lib/oli_web/live_session_plugs/set_current_user.ex
test/oli_web/live/new_course/course_details_test.exs
test/support/test_helpers.ex

[Link](https://eliterate.atlassian.net/browse/MER-2920) to the ticket
Both AppSignal errors had similar root causes. In both cases, the used live plugs were expecting a `current_user/author_id`, but were not handling cases where those values were not yet in the session. So, the fix was to handle those cases and redirect the user to the login page.
On the other hand, the SetCtx plug was incorrectly assuming there was already a user set in the assigns and, if this plug is not used after the SetCurrentUser plug, the mentioned assigned may not exist. 
The SetCtx module docs were expanded to explain this case.

[MER-2920] Extend live session plugs

---

lib/oli/utils/appsignal.ex

[MER-2904](https://eliterate.atlassian.net/browse/MER-2904)
This PR aims to get and send a more accurate error message to AppSignal if an error occurs in the execution flow when editing an activity.
After analyzing the code, and trying to force all the errors that can happen in this flow, I found that it can be sent in the `send_error` function of the `AppSignal` module, as metadata a tuple, but the function `Appsignal.Span.set_attribute` does not allow this type of data (only allows data types such as String, integer, boolean or float), so I think it would not be receiving correctly. 
https://hexdocs.pm/appsignal/2.7.10/Appsignal.Span.html#set_attribute/3
Feel free to add any comments in order to get better options for logging errors in AppSignal in a more efficient and clear way. …

[FEATURE] [MER-2904] Add missing error logging for activity editing error

---

priv/repo/migrations/20240118214656_oban_12.exs

A previous PR bumped the Oban version, but didn't realize that the new version required a migration (to add an "oban_peers" table, among other changes).  This PR adds that migration.

[BUG FIX] Add missing migration

---

assets/src/components/activities/common/responses/responseActions.ts
assets/src/components/activities/response_multi/actions.ts
assets/src/components/activities/response_multi/rules.ts
assets/src/components/activities/response_multi/sections/PartsTab.tsx
assets/src/components/activities/response_multi/sections/ResponseTab.tsx
assets/src/components/activities/response_multi/sections/RulesTab.tsx
assets/src/components/activities/response_multi/utils.tsx
assets/src/components/activities/types.ts
assets/src/data/activities/model/responses.ts
assets/src/data/activities/model/rules.ts
assets/test/response_multi/response_multi_authoring_test.tsx

This batches fixes and enhancements for several issues in the new response_muti activity, primarily in the authoring interface:
- Fixes errors in parsing rules, e.g. not handling ids with underscores (used in Logic and Proofs course) Rule parsing functions now centralized in a new file, rules.ts using a quasi-type of "InputRule".  
- Fixes to generate legally parenthesized torus rules which do not allow n-ary conjunction/disjunction without parens. 
- Allows for multiple rules for dropdown choices when type is disjunctive (used in Logic and Proofs), showing as multi-select checkboxes in this case. 
- Shows feedback for incorrect answer (catchall) so it can be modified, as in multi_input, multiple choice, etc.
- Uses labels "Input 1", "Input 2" in add rule dropdown and rule display to help …

[BUG] Response_multi fixes MER-2935,MER-2936,MER-2937,MER-2938,MER-2939,MER-2940,MER-2941

---

assets/src/components/resource/objectives/ObjectivesSelection.tsx

When searching for objectives, the list was previously case-sensitive. Now it's case insensitive.
When testing, also note that when you search for a parent objective, it returns the children objectives for it. This appears to be intentional.

Make the objectives search case insensitive

---

assets/styles/authoring/layout/workspace.scss
lib/oli_web/templates/layout/_admin_sidebar.html.eex
lib/oli_web/templates/layout/_community_admin_sidebar.html.eex
lib/oli_web/templates/layout/_project_sidebar.html.eex
lib/oli_web/templates/layout/_workspace_sidebar.html.eex

Fixes two accessibility issues with the left hand toolbar.
1. They can now be navigated to via keyboard and there is new a focus-outline around them.
2. The aria-labels have been cleaned up and set to be more useful to users with screenreaders.

[Buffix] fixed accessibility issues in left sidebar [MER-2799]

---

assets/package.json
assets/test/utils/date_utils_test.ts
assets/yarn.lock

The epoq library we were using was not working correctly if you used the numeric based constructor with a january date. I've fixed the bug in a fork and temporarily published a fixed package which this PR switches to.
See actual fix here: https://github.com/bbsimonbb/epoq/pull/3
If/when that PR is merged, we can go back to using the official epoq library.
This was preventing us from choosing dates in january for suggested-by or in-class-activity-on dates.

[Bugfix] Switched to a patched version of epoq library [MER-2927]

---

assets/tailwind.theme.js
lib/oli_web/live/common/stepper/stepper.ex
lib/oli_web/live/delivery/student_onboarding/explorations.ex
lib/oli_web/live/delivery/student_onboarding/intro.ex
lib/oli_web/live/delivery/student_onboarding/survey.ex

[Link](https://eliterate.atlassian.net/browse/NG23-53) to the ticket
I could not reproduce the appearance of the scrollbar in the white container (I tried in 4 different browsers with different combinations of screen sizes and resolutions).
So I worked on adapting the image size, the padding, and the margins to prioritize the text content of the white container, reducing the possibility of the scrollbar need. Some custom breakpoints in the horizontal and vertical directions were defined to achieve this.
This does not guarantee that the scrollbar will appear in some cases, for example, if the onboarding wizard has a survey step where the survey content is very long. But in those cases having a scrollbar makes sense.
Finally, I also worked on a mobile version adapting the background sizes …

[NG23-53] Welcome page images fix for guest account

---

lib/oli_web/live/delivery/student_dashboard/components/helpers.ex

[MER-2604](https://eliterate.atlassian.net/browse/MER-2604) This pull request addresses the second point of the ticket; now, the student's email is exposed below the profile photo 
[MER-2604]: https://eliterate.atlassian.net/browse/MER-2604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MER-2604-student-emails-never-exposed

---

lib/oli/delivery/gating.ex
lib/oli_web/live/sections/gating_and_scheduling.ex
test/oli_web/live/sections/gating_and_scheduling_test.exs

[MER-2441](https://eliterate.atlassian.net/browse/MER-2441)
This PR modifies the default sorting of the Gating Conditions when accessing the view. 
So, the elements will now be sorted depending on the order the elements have in the course section.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/5f6b5d23-0b83-47de-bfb1-615e7eb8df86
[MER-2441]: https://eliterate.atlassian.net/browse/MER-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2441] Sort gating by sequence/appearance in course

---

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx

This issue was coming due the changes requested for https://eliterate.atlassian.net/browse/MER-2735. The iFrame was applying the permission policy thus preventing the Unity SIM to load.

[BUGFIX] [MER-2947] | Into the Cell Error: Failed to execute 'getGamepad()'

---

assets/src/hooks/video_player.ts
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/import/csv_import_view.ex

[NG23-60](https://eliterate.atlassian.net/browse/NG23-60)
Add support for YouTube links on the Learn page.
Clear Sections cache when importing a CSV with project assets.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/eb6f7f6e-0cc6-491f-be45-724a02f7cba5
[NG23-60]: https://eliterate.atlassian.net/browse/NG23-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NG23-60] Support YouTube links on Learn page

---

lib/oli/publishing/delivery_resolver.ex

[MER-2912](https://eliterate.atlassian.net/browse/MER-2912?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug%2C%20Story)%20AND%20status%20in%20(%22In%20Progress%22%2C%20PR%2C%20Ready%2C%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20assignee%20ASC%2C%20status%20ASC%2C%20priority%20DESC%2C%20created%20DESC) This pr changes the ordering criteria of the practice activities by numbering index
[MER-2912]: https://eliterate.atlassian.net/browse/MER-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MER-2912-practice-activity-pages-displayed-in-random-order-in-navigation

---

assets/src/hooks/video_player.ts
lib/oli_web/live/common/utils.ex
lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[NG23-67](https://eliterate.atlassian.net/browse/NG23-67)
When a YouTube intro video is set for a Course Unit, use the video preview image as the poster image of the Unit.
It also fixes a small bug where background images on cards were not fitting into the specified area.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/639a2043-233b-47e2-a0ca-bdcc14a9a076
[NG23-67]: https://eliterate.atlassian.net/browse/NG23-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NG23-67] Display video thumbnail for Youtube links

---

lib/oli/delivery.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section.ex
lib/oli/delivery/sections/section_cache.ex
lib/oli/publishing/delivery_resolver.ex
lib/oli/utils/seeder/project.ex
lib/oli/utils/seeder/utils.ex
lib/oli_web/live/delivery/student/discussions_live.ex
priv/repo/migrations/20240125210747_remove_resource_to_container_map.exs
test/oli/delivery/sections_test.exs
test/oli_web/live/delivery/student/discussions_live_test.exs

Fixes a couple of different issues related to the ordering of explorations and practice pages and categorization of which containers they are in:
1. Original ordering determination using a single database query and numbering index and level was flawed. In order to properly sort according to the hierarchy, the hierarchy structure must be loaded and used for sorting. Because this code path still makes use of a section level caching mechanism, this cost only needs to be paid a single time for a course section (and whenever the section is remixed, updated, etc.)
2. The key being used to cache the labels was not matching up with the key expected by the SectionCache module and therefore was not being properly cleared as expected. I fixed that and added a guard so that any key used must match a …

[NG23-65] ordering of exploration pages is not correct

---

lib/oli_web/components/delivery/deliberate_practice_card.ex
lib/oli_web/live/delivery/student/explorations_live.ex

Fixes an issue where explorations and practice pages weren't rendering intro content description.

[NG23-66] intro content for explorations and practice pages is not displaying

---

lib/oli/delivery/experiments.ex
lib/oli/publishing.ex
priv/repo/migrations/20240125204755_fix_revision_parts.exs

This PR is part 1 of the complete fix for the dreaded "part attempt bloat" publishing problem.   Part 2 likely will target 26.3.
What this PR does:
1. Adds a migration which recreates the `revision_parts` table, but by excluding duplicate values.  Tested locally by adding a bunch of duplicate values, then ran the migration and the new `revision_parts` table has deduped them.
2. Changes the `INSERT` statement that upserts `revision_parts` records to use "automatic" in place of `NULL` values. 
With those two fixes above, all future part attempts created during page attempt creation will be done with the correct number of part attempts. 
After getting some feedback from the Upgrade team, I snuck in one minor change to the value of `groupUniqueifier` which is supposed to be a timestamp.  I …

[BUG FIX] Fix 1 for part attempt bloat: stop creating unnecessary part attempt records [MER-2950]

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

Improves the colors and title readability of module cards on the learn live view. These became more apparent once we actually loaded in images.
From
To

[NG23-68] improve module card colors and readability

---

priv/repo/migrations/20240125204755_fix_revision_parts.exs

This updates that latest migration (which has only been applied to garbage heliotron) to account for a case of bad data as seen on ETX QA DB.
Basically there is a situation where for a handful of `part_id` and `revision_id` combinations there is one record with a `NULL` grading approach and another record with a non `NULL` grading approach (i.e. "manual" or "automatic").  This should have never been possible, and was probably due to an old bug that was fixed a while ago.  But this data situation prevents the unique index from being re-added (after we change all `NULL` values to "automatic").  
The solution is to add a step which identifies all pairs of revision_id and part_id which have more than 1 record.  Because of the previous indices, and the fact that we have deduped in the first …

[BUG FIX] Handle quasi dupes during migration [MER-2954]

---

assets/src/components/activities/check_all_that_apply/CheckAllThatApplyDelivery.tsx
assets/src/components/activities/common/delivery/SubmitReset.tsx
assets/src/components/activities/common/delivery/reset_button/ResetButtonConnected.tsx
assets/src/components/activities/common/delivery/submit_button/SubmitButtonConnected.tsx
assets/src/components/activities/file_upload/FileUploadDelivery.tsx
assets/src/components/activities/image_hotspot/ImageHotspotDelivery.tsx
assets/src/components/activities/likert/LikertDelivery.tsx
assets/src/components/activities/multi_input/MultiInputDelivery.tsx
assets/src/components/activities/ordering/OrderingDelivery.tsx
assets/src/components/activities/response_multi/ResponseMultiInputDelivery.tsx
assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx
assets/src/components/activities/vlab/VlabDelivery.tsx

On practice pages many activities have a submit button.
Before this change, the submit button would dissapear and a reset button would appear in the same location.
A learner who accidently double-clicked might submit and then mistakenly reset the activity.
This change moves us to a model where the submit & reset buttons are always visible, however they are disabled when they shouldn't be used.
This affects:
- Check all that apply
- Short Answer
- LikerT
- Multi Input
- Ordering
- File Upload
- Image Hotspot
- Response Multi Input
- VLab

[Enhancement] Submit/Reset button UI changes [MER-2512]

---

assets/src/apps/scheduler/PageScheduleLine.tsx
assets/src/apps/scheduler/scheduler-slice.ts

If today's date has a date-part that's bigger than the number of days in the target month, you could not set the schedule to that date because of the way the Date object validates dates.
Explanation of bug:
const d = new Date();  // ex: Date is 1/30/2024
d.setFullYear(2025) // Date is now 1/30/2025
d.setMonth(2); // Date tries to be 2/30/2025, which doesn't exist, and rolls over to 3/1/2025
d.setDate(15); // Date is now 3/15/2025 instead of 2/15/2025 as expected

[Bugfix] Fix date-handling bug when today's date is later than the target month

---

lib/oli_web/components/delivery/utils.ex
test/oli/delivery/sections_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-64) to the ticket
Weeks were being counted starting on the section start date as the first day of the week instead of starting on a Sunday.
This made some assessments from the previous week were being listed (for example, if the Up Next was being visited on a Monday and the Section start date was not a Sunday).

[NG23-64] Up next showing wrong week

---

assets/css/bootstrap-shims.css

Added an 0.5rem padding to table headers (not inside a thead), to match table cells.
Before:
After:

[Enhancement] Header padding [MER-2956] 

---

lib/oli/accounts.ex
lib/oli/accounts/schemas/user.ex
lib/oli/utils.ex
lib/oli_web/components/common.ex
lib/oli_web/live/users/user_detail_view.ex
test/oli/accounts/user_test.exs
test/oli_web/live/admin_live_test.exs
test/oli_web/live/users/user_detail_view_test.exs

Ticket: [MER-2953](https://eliterate.atlassian.net/browse/MER-2953)
This PR upgrades the form used to change user information from an admin account. The advantage of this upgrade is that now the admin get immediate feedback the interacting with the form and something goes wrong, like having an empty field.
The `update_changeset_for_admin` changeset was also changed to avoid extra casting.
[MER-2953]: https://eliterate.atlassian.net/browse/MER-2953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2953] Upgrade user edit form to be a form component

---

assets/src/components/activities/directed-discussion/ParticipationInput.tsx
assets/src/components/activities/directed-discussion/actions.ts

Before, you could set the number of required posts or replies higher than the max number of posts or replies allowed, making the activity impossible to complete. Now, if you try to do that, the max-replies number is automatically adjusted.
Also: 
1. You can no longer specify a negative value for any of these inputs
2. The step has been set to 1 from 0.1, so the up/down controls make sense.

[Bugfix] Max posts can't be less than required posts [MER-2809]

---

lib/oli_web/components/delivery/scored_activities/scored_activities.ex
test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs

[MER-2916](https://eliterate.atlassian.net/browse/MER-2916)
This PR adds support to show response details for rendered activities in the `Scored Activities` tab. 
Activity response details are added for `Multi input activity` and `Likert activity`. 
- Multi Input Activity
- Likert Activity
[MER-2916]: https://eliterate.atlassian.net/browse/MER-2916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2916] Instructor view no additional activity summarization for scored activities

---

assets/styles/common/purpose.scss

The table-menu would get clipped when it tried to overflow a group. Made the simplest fix to change overflow:hidden to overflow:visible of groups during authoring time.

[Bugfix] Allow tablemenu to overflow groups [MER-2957]

---

lib/oli_web/pow/author_context.ex
test/oli_web/live/admin_live_test.exs

Ticket: [MER-2875](https://eliterate.atlassian.net/browse/MER-2875)
When an Author is logged in the application, our cache is triggered storing its data in the session in order to save future extra DB calls. If an Admin tries to lock/unlock that author, a DB call changes the `locked_at` field but it doesn't delete the cache (if any). This makes an Author (potentially blocked by an Admin) able to navigate on the app.
This PR also tackled the issue mentioned in the ticket. An Admin can locked and then unlocked an Author and the Author should be able to log in.
[MER-2875]: https://eliterate.atlassian.net/browse/MER-2875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2875] Fix admin cannot lock/unlock an author

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/minimal_hierarchy.ex

The fix here was to add a step before the final full hierarchy "refetch" which “cleans” the `children` attribute of all section resource records, removing any SR id which no longer maps back to a currently published, non-deleted project resource.
Because it was not possible to reproduce locally this bug, the plan to verify this bug fix is to test it out on a copy of the production DB running on Heliotron, before we merge this to 26.3
UPDATE: I verified that these changes fix the problem faced by the affected course section (https://heliotron.oli.cmu.edu/sections/test_cmu_98179_student_taught_/instructor_dashboard/manage) on a Feb 1 copy of Prod.

[BUG FIX] Ensure deleted resources in major publications are removed from section resources [MER-2987]

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/dialogue/window_live.ex
lib/oli_web/live/sections/overview_view.ex
priv/repo/migrations/20240129151601_add_section_assistant_enable.exs
test/oli_web/live/sections/overview_live_test.exs

Adds the ability to enable/disable the ai agent for a section in the manage view.

[NG23-62] ai agent enable toggle at section level

---

config/config.exs

[MER-2988](https://eliterate.atlassian.net/browse/MER-2988)
This PR adds configuration to Oban to prevent error messages from being displayed when running application tests. 
**image after apply config**
[MER-2988]: https://eliterate.atlassian.net/browse/MER-2988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2988] Adds manual testing to Oban config

---

lib/oli/delivery/metrics.ex
lib/oli/publishing/delivery_resolver.ex
lib/oli_web/components/delivery/practice_activities/practice_assessments_table_model.ex
lib/oli_web/live/delivery/instructor_dashboard/helpers.ex
test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs

Ticket [MER-2918](https://eliterate.atlassian.net/browse/MER-2918)
This PR addressed 2 issues:
1. Fixed the ordering for the practice activities listing page.
2. Removed the dependency over average score data to display student progress, otherwise the student progress data might renders a dash if its average score is nil.
[MER-2918]: https://eliterate.atlassian.net/browse/MER-2918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MER 2918 instructor role incorrect sorting of practice activities

---

assets/src/apps/page-editor/PageEditor.tsx
assets/src/data/editor/PageEditorContent.ts
assets/test/editor/page_editor_content_test.ts

1. Create a group
2. Add an activity bank inside the group
3. Click the add-expression button
Expected: An expression is added
Actual: Nothing is added
Cause of bug: When we save the page, we pass it through PageEditor::adjustContentForConstraints before sending it to the server to make sure we don't have any invalid expressions.
That call to adjustContentForConstraints should have been an immutable operation that generated a new object with any changes. There was a bug in PageEditorContent::updateAll that caused a mutation of the original object instead of purely returning a new one. This caused the expression to be stripped out in-memory as well as in the version we sent to the server, which was not wanted. See notes in the new unit test for clarity

[Bugfix] Could not "add expression" to activity banks in groups [MER-2913]

---

assets/src/phoenix/activity_bridge.ts
lib/oli/delivery/attempts/activity_lifecycle.ex
lib/oli_web/components/delivery/practice_activities/practice_activities.ex
lib/oli_web/controllers/api/attempt_controller.ex
test/oli_web/controllers/api/attempt_controller_test.exs

[MER-2915](https://eliterate.atlassian.net/browse/MER-2915)
This PR seeks to correct the error mentioned in the ticket above. 
To do so, it was necessary to add to the actions that are executed when pressing the `Reset` button (to reset the activity) the `survey_id` information that ends up propagating to the Activity Attempts table in the database. 
It's necessary to set the `survey_id` whenever the activity is reset as this data must be added to the records created for that activity in the `Activity Attempts` table.
This change was necessary because the `Practice Activities` tab should NOT show the details of the activities that are contained within a survey.
[MER-2915]: https://eliterate.atlassian.net/browse/MER-2915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …

[BUGFIX] [MER-2915] Additional activity summarization only visible when answering more than once

---

assets/src/components/activities/multi_input/schema.ts
assets/src/components/activities/multi_input/sections/QuestionTab.tsx
lib/oli_web/components/delivery/practice_activities/practice_activities.ex
lib/oli_web/components/delivery/surveys/surveys.ex
test/oli_web/live/delivery/instructor_dashboard/overview/surveys_tab_test.exs

[MER-2917](https://eliterate.atlassian.net/browse/MER-2917?filter=10069&jql=project%20%3D%20MER%20AND%20issuetype%20in%20(Bug%2C%20Story)%20AND%20status%20in%20(%22In%20Progress%22%2C%20PR%2C%20Ready%2C%20%22To%20Do%22)%20AND%20labels%20%3D%20wyeworks%20ORDER%20BY%20assignee%20ASC%2C%20status%20ASC%2C%20priority%20DESC%2C%20created%20DESC)
This pr modify the code in practice activities and surveys to show corretly the dropdown, numeric and text type of multi input activities in practice_activities and surveys modules.
[MER-2917]: https://eliterate.atlassian.net/browse/MER-2917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MER-2917-instructor-view-incorrect-additional-activity-summarization-in-multi-input-activities

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/delivery/schedule.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/review_live.ex
lib/oli_web/live/delivery/student/schedule_live.ex
lib/oli_web/live/delivery/student/utils.ex
lib/oli_web/live_session_plugs/set_request_path.ex
lib/oli_web/router.ex
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs
test/oli_web/live/delivery/student/review_live_test.exs

[NG23-72](https://eliterate.atlassian.net/browse/NG23-72)
Fix the back button in the Lesson and Review pages to allow different request paths.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/b34194d9-40ae-4981-b88a-e647e9a3375d
[NG23-72]: https://eliterate.atlassian.net/browse/NG23-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NG23-72] Fix back button on the Lesson view to consider different request paths

---

lib/oli/delivery/attempts/core/activity_attempt.ex
lib/oli/delivery/attempts/part_attempt_cleaner.ex
lib/oli_web/controllers/spot_check_controller.ex
lib/oli_web/router.ex
priv/repo/migrations/20240129162557_add_cleanup_state.exs

This PR changes the part cleaner implementation in two ways:
1. It now records in the `cleanup` field the number of deleted part attempt records
2. The "fetch next id" step was proving to be the bottleneck in performance. This PR adds in an in-memory queue of size 1000
Also, this adds the "spot check" route to make it easier to review page attempts of affected activity attempts

[CHORE] Track deleted parts during cleaning, batch the activity id fetching, spot check [MER-2951]

---

assets/src/components/activities/likert/actions.ts
assets/src/components/activities/multi_input/actions.ts
assets/src/components/activities/response_multi/actions.ts
assets/src/components/activities/vlab/actions.ts
assets/src/data/activities/model/list.ts

Authors found deleting a choice in a migrated MCQ would remove all choices, breaking the question model, preventing further authoring. This was due to the JSON path filter expression used in the removeOne list operation used to delete choices. It never happened on torus-authored MCQs because they carry generated id strings consisting of numbers, and the id filter predicate inadvertently wound doing a comparison against a numeric value when matching ids of this form, which apparently worked against id strings that can be coerced to numbers. But migrated courses frequently have choice ids of the form "A", "B" "C" (perhaps echo-generated), so the removeOne operation was failing on these.
Other List operations used the ID_PATH definition which correctly quoted the id argument, so have always …

[BUGFIX] Correctly delete migrated MCQ choices w/non-numeric id strings [MER-2998]

---

lib/oli_web/controllers/api/attempt_controller.ex

This PR https://github.com/Simon-Initiative/oli-torus/pull/4628 added "survey_id" as a param to the `:new_activity` endpoint.  But the adaptive player also uses this endpoint and does not provide it, so every call to it results in a `400` error due to the failed pattern match. 
This adds back in a `new_activity` endpoint that does not pattern match for "survey_id" in the params, leaving the other one in place for the basic page.  Tested locally and this restores adaptive player functionality.

[BUG FIX] Restore survey-less reset endpoint [MER-3013]

---

assets/src/apps/scheduler/scheduler-slice.ts

For items with a due-date, the scheduler was not taking into account the time component of the date when displaying it on the grid. This caused it to be visually off by a day on the grid.
If left alone, this had no practical effect on the system, it was just a slight visual difference.
However, if a user then clicked on the icon in the grid, and released the mouse button without moving the item, that incorrect position would get saved to the due-date.

Fixed date handling for due-date items

---

config/config.exs
config/test.exs
lib/oli/delivery/sections.ex
test/oli/sections_test.exs

Ticket: [MER-2984](https://eliterate.atlassian.net/jira/software/c/projects/MER/issues/MER-2984)
This PR optimized the `get_resources_scheduled_dates_for_student/2` function. Now instead of making 4 queries every time we want the resource's end_dates we only make one.
This PR also moved the `testing: :manual` Oban configuration to the testing env. It looks more appropiate.
[MER-2984]: https://eliterate.atlassian.net/browse/MER-2984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mer 2984 mer 2984 optimize get resources scheduled dates for student function

---

assets/src/components/media/manager/MediaManager.tsx
assets/src/components/media/manager/delete.ts
assets/src/data/persistence/media.ts
lib/oli/authoring/media_library.ex
lib/oli_web/controllers/api/media_controller.ex
lib/oli_web/router.ex
test/oli/authoring/media_libary_test.exs

The following changes have been implemented in this PR to provide support for archiving media items from the media library:
1. Authors can now label a media item as “archived” which will remove it from the media library.
2. When an author tries to archive a media item in the library, there will be a prompt asking them to confirm the process. The prompt will inform them that archived media items will no longer be available in the media library and the archiving process is not reversible.
3. The archived media item will still remain in the database and can be used for reference in older sections.
4. Once the media item has been archived, the author can upload a new media item with the same name.

[MER-2163] archive media items

---

.gitignore
lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/live/delivery/student/lesson/notes.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/review_live.ex
lib/oli_web/live/dialogue/window_live.ex

https://eliterate.atlassian.net/browse/NG23-76
Adds the annotations panel to the side of a page allowing a student to open/close the panel.
Currently it just contains placeholder controls and content

[NG23-76] user opens and closes notes panel

---

lib/oli_web/components/delivery/scored_activities/scored_activities.ex
test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs

Ticket: [MER-2980](https://eliterate.atlassian.net/browse/MER-2980)
This PR fixed the sorting issue mentioned on the aforementioned ticket (see commit [1](https://github.com/Simon-Initiative/oli-torus/pull/4646/commits/23195d168edd0d27515d8f009b8d66a7189275ad) and [2](https://github.com/Simon-Initiative/oli-torus/pull/4646/commits/1bf5fddb7292de27c2ae74a3d80299e6de6b075c)). There is also a refactor over the `ScoreActivies` module to improve readability (see commit [3](https://github.com/Simon-Initiative/oli-torus/pull/4646/commits/8bfd93f5b36d400cc8c44eabc6382402784afb85) and [4](https://github.com/Simon-Initiative/oli-torus/pull/4646/commits/464608c355904f93f7e09229b203463cd41555af)).
[MER-2980]: https://eliterate.atlassian.net/browse/MER-2980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

Mer 2980 incorrect sorting in due date for scored activities

---

lib/oli_web/live/grades/grade_sync.ex
lib/oli_web/live/grades/grades.ex
test/oli/delivery/attempts_test.exs
test/oli_web/controllers/page_delivery_controller_test.exs
test/oli_web/live/delivery/instructor_dashboard/reports/quiz_scores_tab_test.exs
test/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab_test.exs
test/oli_web/live/grades_live_test.exs
test/oli_web/live/progress/student_resource_view_live_test.exs
test/support/test_helpers.ex

Ticket [MER-3016](https://eliterate.atlassian.net/browse/MER-3016)
This PR fixed an incorrect handle event called with an incorrect attribute when trying to select another graded page. It was added a test covering selecting other that the default --the first one--. 
[First commit](https://github.com/Simon-Initiative/oli-torus/pull/4655/commits/2772f95ba67429ea10b824a395d27c76e8d256e2) is the **actual fix** for the reported bug.
[Second commit](https://github.com/Simon-Initiative/oli-torus/pull/4655/commits/0b563b81752c43207af734234c1214c85c39f377) is the test above fix.
[Third commit](https://github.com/Simon-Initiative/oli-torus/pull/4655/commits/dba89b00a0b8d99a5425500b0e1d3cf0b649f25a) fixes some broken tests when developing the above test.
[MER-3016]: …

Mer 3016 unable to select assignment for lms synchronize grades tool

---

assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx

Hey @bsparks can you please look at this PR.
I have tracked down the commit where this change was made (way back in Janus) and it looks like, it was added to fix "[PMP-1249 | BLOCKED: Phases of the Moon 112892: User stuck on screen 2 after validation](https://jira.unicon.net/jira/browse/[PMP-1249](https://jira.unicon.net/jira/browse/PMP-1249)) ". We don't need this to controlled based on the "EnableHistory". 
It should be based on the whether "currentActivity?.custom?.showCheckBtn" is available on the screen.

[BUGFIX] [MER-3024] | Advanced Author Next button behaves differently in different lessons

---

assets/src/components/activities/AuthoringElementProvider.tsx

Bug: 
1. Insert a video inside an activity (such as MCQ stem)
2. Click the video settings button
Expected: Settings window appears
Actual: Nothing happens
This was caused by the activity introducing a redux-container that did not have the modal logic built in.

[MER-3014] Video settings button

---

assets/styles/common/elements.scss
assets/styles/common/purpose.scss
assets/styles/delivery/activity.scss

Bug: Exceptionally long formulas would get truncated in the display.
I went through a ton of examples and found a few more than reported. Unfortunately, there wasn't a single global fix for this one, so there may be undiscovered combinations of formatting that still cause this to happen.
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:

[Bugfix] Cut off formulas [MER-2961]

---

assets/styles/common/elements.scss

Authors noted excessive padding around inline formulas in the body of text, causing an odd appearance when formulas interspersed in body of text, particularly when formula for symbols are followed immediately by punctuation. This change removes the 0.5em horizontal padding applied to formula-inline. Examples:
Current:
New:

[ENHANCEMENT] remove horizontal padding on inline formulas [MER-3052]

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[NG23-43](https://eliterate.atlassian.net/browse/NG23-43)
Fix the current Learn view numbering to match the original numbering in Torus.
**Notes:**
I had to make some decisions not specified in the ticket regarding handling the numbering of cards corresponding to pages on a module level (not within a module). Details are specified in the ticket comments.
**Before:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/7b9e6486-f8fb-4caa-b758-689f46a0f7fc
**After:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/b6748cf1-c352-4267-9a2a-624b16ab91ab
[NG23-43]: https://eliterate.atlassian.net/browse/NG23-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NG23-43] Fix Learn view numbering

---

assets/src/components/activities/multi_input/schema.ts
assets/src/components/activities/multi_input/sections/QuestionTab.tsx
lib/oli_web/components/delivery/scored_activities/scored_activities.ex

[MER-2994](https://eliterate.atlassian.net/browse/MER-2994)
This PR fixes the aditional activity summarization when there are activities multi input with numeric and text inputs.
With these changes, when an input is selected, only its answers are shown and not the answers of the whole activity.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/ff710f72-fa93-45f4-b613-baeafc413c1f
[MER-2994]: https://eliterate.atlassian.net/browse/MER-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2994] Fix additional activity summarization

---

lib/oli/delivery/sections/section.ex
test/oli/delivery/sections/section_test.exs
test/oli_web/live/dialogue/window_live_test.exs
test/oli_web/live/sections/overview_live_test.exs

[NG23-94](https://eliterate.atlassian.net/browse/NG23-94)
Update the default value of the `assistant_enabled` field in the Section schema to `false`.
Add changeset tests to the Section schema.
**Note:**
The AC states: _"Also, only an Admin should be able to access the UX to enable and disable the Agent. "_.
However, that is the current behavior according to https://github.com/Simon-Initiative/oli-torus/blob/nextgen-ux/lib/oli_web/live/sections/overview_view.ex#L411. No changes should be required here.
[NG23-94]: https://eliterate.atlassian.net/browse/NG23-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NG23-94] Change assistant enabled default value

---

lib/oli/publishing/delivery_resolver.ex
lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/controllers/launch_controller.ex
lib/oli_web/router.ex
lib/oli_web/templates/delivery/enroll.html.heex
test/oli_web/controllers/launch_controller_test.exs

[MER-2985](https://eliterate.atlassian.net/browse/MER-2985)
This PR implements two new routes to enter a course section faster and with fewer clicks. 
A new controller is created that handles two endpoints needed to speed up this process. 
With this implementation, authenticated and non-authenticated users (guest users) of the application will be able to enroll in a course in a more direct way being redirected to the first page of the course section.
- Enroll as non-authenticated user (Guest)
https://github.com/Simon-Initiative/oli-torus/assets/16328384/1300e927-9f51-4e6d-8233-b3e8fa1a2d3a
- Enroll as authenticated user
https://github.com/Simon-Initiative/oli-torus/assets/16328384/61503580-ccbf-43c1-9200-08a9c13fdbfc
[MER-2985]: https://eliterate.atlassian.net/browse/MER-2985?atlOrigin=eyJ …

[FEATURE][MER-2985] Reduce number of clicks to launch lesson

---

assets/src/components/activities/common/responses/TargetedFeedback.tsx

Migrated courses erroneously included the correct choice in targeted feedback mapping for multiple choice and multi-input dropdown items. This provides a path for author to delete the correct answer in authoring by deleting that targeted feedback, which puts the question in an invalid state, blocking any further editing. This change defends against that for already-migrated courses by filtering the correct response from the targeted feedback display. 
This check is added in the common `<TargetedFeedback>` component which is used in authoring of Multiple Choice, CATA, Multi-input, Image Hotspot, Ordering, and Likert activities.

[ENHANCEMENT] ignore correct choice in mcq targeted feedback list [MER-3034]

---

lib/oli_web/templates/layout/live.html.heex
lib/oli_web/templates/page_delivery/index.html.heex
test/oli_web/controllers/static_page_controller_test.exs
test/oli_web/live/delivery/student_dashboard/course_content_live_test.exs

[MER-2761](https://eliterate.atlassian.net/browse/MER-2761)
This PR fixes the bug where the flash message is shown twice when updating the timezone as student.
The problem that caused this is that the flash message was displayed both in the controller view and in the liveview that renders the course content. This prevents the message from being displayed for the liveview.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/bcc416fb-eeb3-4b46-bc5e-3cdc0814397d
[MER-2761]: https://eliterate.atlassian.net/browse/MER-2761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2761] Sticky flash messages look wrong after update timezone

---

lib/oli/delivery/attempts/page_lifecycle/graded.ex

The logic that was added to be able to score basic pages which contain zero activities did not take into account the fact that adaptive page evaluation only looks at "non active" activities.  So, if a user submits an attempt on the first screen in an adaptive page, that page attempt will contain zero "non active" activities and thus trip this case and get scored 1 out of 1.  Instead, we always want adaptive pages to go thru the standard scoring flow where it will likely get a content driven score override.

[BUG FIX] [MER-3055] Restrict zero activity score override to basic pages

---

lib/oli/authoring/course.ex
lib/oli_web/live/common/utils.ex
lib/oli_web/live/progress/attempt_history.ex
lib/oli_web/live/progress/page_attempt_summary.ex
lib/oli_web/live/progress/student_resource_view.ex
test/oli_web/live/progress_live_test.exs

[MER-3008](https://eliterate.atlassian.net/browse/MER-3008)
This PR fixes the order of the list of student attempts in the resource progress view. 
For this, the resource attempts are obtained and ordered by attempt number, and then displayed in order when they are rendered.
[MER-3008]: https://eliterate.atlassian.net/browse/MER-3008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-3008] Attempts sort out of order

---

assets/styles/common/elements.scss

“Term” is available in Torus as an inline style like underline, strikethrough, etc. When used within definitions, terms are styled in green, heavy-weight and slightly larger font. But term-tagged text was not being styled in other contexts.  Legacy course Logic and Proofs makes frequent use of term styling to highlight technical terms when they are introduced in text content.
This styles terms in content in the same green and bold as in definitions, though it keeps the normal size. Sample showing terms outside and inside a definition:

[BUGFIX] style terms distinctively in text content [MER-3066]

---

lib/oli_web/components/delivery/recommended_actions.ex
test/oli_web/live/delivery/instructor_dashboard/overview/recommended_actions_tab_test.exs

[MER-2433](https://eliterate.atlassian.net/browse/MER-2433)
This PR fixes the route that has the access to `Approve Pending Posts` within the `Recommended Actions` tab in the instructor dashboard view. 
The issue was that this element was redirected to a student route, in a wrong way.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/d2b5b82d-c20f-43b0-b54e-c027fe40c4b8
[MER-2433]: https://eliterate.atlassian.net/browse/MER-2433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2433] Fixes recommended action link to approve pending posts 

---

lib/oli/delivery/sections/browse.ex
test/oli_web/live/sections/admin_index_live_test.exs

This pr [MER-3002](https://eliterate.atlassian.net/browse/MER-3002?filter=-1) add a subquery to only count the number of student enrollments
[MER-3002]: https://eliterate.atlassian.net/browse/MER-3002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-3002] Number Enrolled Should be Students Only

---

lib/oli/authoring/clone.ex
lib/oli/authoring/course.ex
lib/oli/delivery/page/page_context.ex
test/oli/course_test.exs

This PR addresses an issue where the query to fetch a project license results in multiple results where one is expected. It also addresses an issue where cloning a project fails when a license is added to it.

[MER-3068] Bug fix where accessing course material give a 500 error

---

assets/package.json
assets/yarn.lock

This change moves us to use our forked Slate library, one that attempts to eliminate thrown errors due to DOM and internal slate model divergences.

[BUG FIX] [MER-3069] Suppress slate errors

---

config/runtime.exs
lib/oli/analytics/datashop_export_worker.ex

https://eliterate.atlassian.net/browse/MER-3071
This is a fix for the datashop generation error related to database connection timing out on large courses. There are 2 changes here:
1. Add the ability to configure this timeout system-wide with an environment variable
2. Set the specific datashop query transaction timeout to infinity, thereby using as much time as needed to generate.
When tested on heliotron with the Chemistry course with ~300 enrollments, this operation took about 3 hours. While this effectively consumes a database connection for that period, we can limit the number of simultaneous datashop jobs that run at a time so that the system doesn't starve itself of database connections (currently, the `datashop_export` queue is configured to 3).
These changes were tested against …

[MER-3071] Fix datashop export database timeout issue

---

assets/src/components/content/TitleBar.tsx
lib/oli_web/live/breadcrumb/breadcrumb_live.ex
lib/oli_web/templates/layout/_workspace_header.html.eex
lib/oli_web/templates/shared/_help_button.html.eex
test/oli_web/controllers/project_controller_test.exs
test/oli_web/controllers/resource_controller_test.exs

[MER-2986](https://eliterate.atlassian.net/browse/MER-2986)
This PR performs some styling changes on elements of the edit view of a project curriculum page. 
- Remove the `sticky` class so that the page title is not always fixed at the top of the view.
- Added a `truncate` class to the view title so that ellipses are added to the page title if it is too long.
- A`truncate` class is added to the page breadcrumb title so that ellipses are added to the title if it is too long.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/7f259458-c07f-48a8-9bd3-f32819720fe3
[MER-2986]: https://eliterate.atlassian.net/browse/MER-2986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MER-2986] Formatting difficult

---

lib/oli_web/components/delivery/practice_activities/practice_activities.ex
lib/oli_web/components/delivery/surveys/surveys.ex
test/oli_web/live/delivery/instructor_dashboard/overview/surveys_tab_test.exs

[MER-2917](https://eliterate.atlassian.net/browse/MER-2917)
This PR fixes the bug that is happening in both text and numeric response inputs in the `Practice Activities` and `Surveys` tabs. 
With these changes, the students' answers are displayed correctly.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/1b7800ab-5d06-4389-b245-c5f2df1d816a
[MER-2917]: https://eliterate.atlassian.net/browse/MER-2917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-2917] Fix additional activity summarization in practice and surveys activities

---

lib/oli/accounts/schemas/vr_user_agent.ex
lib/oli/application.ex
lib/oli/vr_lookup_cache.ex
lib/oli/vr_user_agents.ex
lib/oli_web/live/admin/admin_view.ex
lib/oli_web/live/admin/vr_user_agents_view.ex
lib/oli_web/plugs/set_vr_agent_value.ex
lib/oli_web/router.ex
lib/oli_web/templates/layout/chromeless.html.eex
lib/oli_web/templates/layout/delivery.html.heex
lib/oli_web/templates/layout/delivery_from_payment.html.heex
priv/repo/migrations/20240306095920_create_vr_user_agents_table.exs
test/oli/vr_user_agents_test.exs
test/oli_web/live/vr_user_agents_view_test.exs
test/support/factory.ex

Ticket: [MER-2859](https://eliterate.atlassian.net/jira/software/c/projects/MER/issues/MER-2859)
This PR added the ability to control the addition of the polyfill.io script depending on a list of user agent stored in the DB/cache.
A UX view was implemented in order to add/delete user agents from the DB/cache.
Endpoint used to interact with vr_user_agents data: `localhost/admin/vr_user_agents`
The cache was implemented using a `Agent`.
[MER-2859]: https://eliterate.atlassian.net/browse/MER-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mer 2859 captcha fix for tour it vr users support

---

lib/oli/interop/export.ex

Export function crashes on any migrated course with image hotspots because migration tool writes them as choices without content, but the reference rewiring process searches choices in activities and is not prepared for them to lack content.  This change has the relevant function ignore activity elements without a content attribute, returning them unchanged.

[BUGFIX] Prevent export crashes on migrated image hotspots [MER-3076]

---

lib/oli/authoring/course/project_attributes.ex

Adds directive to derive Jason.Encoder for License now included in Project Attributes. Without this, export function crashes on attempt to write project file.

[BUG] provide Jason.Encoder for License [MER-3075]

---

lib/oli_web/components/delivery/scored_activities/assessments_table_model.ex
lib/oli_web/components/delivery/scored_activities/scored_activities.ex
test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs

[MER-2980](https://eliterate.atlassian.net/browse/MER-2980)
This PR aims to fix the issue sorting the table by due date column for the `Scored Activities` tab.
Also, it's included the case when the resource has a **scheduling type = due by** and their **end date is nil** (border case)
https://github.com/Simon-Initiative/oli-torus/assets/16328384/bf5bc02e-f848-49de-b368-e61479064c22
[MER-2980]: https://eliterate.atlassian.net/browse/MER-2980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2980] Fix due date sorting for scored activities

---

assets/src/components/editing/editor/normalizers/root.ts
assets/test/editor/normalize_root_test.ts

https://eliterate.atlassian.net/browse/NG23-97
Fixes an issue where paragraphs created in the editor have duplicate identifiers. This fix, along side the publishing fix, is required for the social annotation to work properly.
The solution here is to add another slate normalizer at the editor root which builds a set of ids from all block level nodes and checks the set for any duplicates. If a dup is found, then a new id is issued for the duplicate node.

[NG23-97] fix a bug where paragraphs created in editor have identical ids

---

lib/oli_web/live/projects/overview_live.ex
lib/oli_web/plugs/set_license.ex
lib/oli_web/router.ex
lib/oli_web/templates/layout/_delivery_footer.html.eex
lib/oli_web/views/layout_view.ex
test/oli_web/live/admin/vr_user_agents_view_test.exs
test/oli_web/views/layout_view_test.exs

Ticket: [MER-2748](https://eliterate.atlassian.net/browse/MER-2748)
This PR fixed 3 bugs:
- License is only render for _learning pages_.
- License renders a URL for custom licenses.
- Two tests were sharing the same name and a warning appeared in the console when running the test suite.
Related PR: [4671](https://github.com/Simon-Initiative/oli-torus/pull/4671)
[MER-2748]: https://eliterate.atlassian.net/browse/MER-2748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Mer 2748 fix bug render license in pages different from learning pages

---

lib/oli_web/components/delivery/students/students.ex
test/oli_web/live/delivery/instructor_dashboard/reports/students_tab_test.exs

Pulled from https://github.com/Simon-Initiative/oli-torus/pull/4715 into v27
Original ticket: https://eliterate.atlassian.net/browse/MER-3072
* fix inviter type initialization for author-only case
* update add enrollment test
* comment test & make consistent

[BUGFIX] fix crash on author/admin add enrollment [MER-3072] (#4715)

---

assets/src/components/activities/multi_input/sections/AnswerKeyTab.tsx

Targeted feedback authoring display for multi-inputs conditionally shows either:
- a "Correct" checkbox (default);
or, if custom scoring is set on the question,
-  a "Score" box to enter custom score points for this response.
However, once custom scoring was checked for the question, the score box for targeted feedbacks was not reverting to checkbox when question scoring reset to default scoring. 
This fixes by conditionalizing the display on the question-wide customScoring flag.

[BUGFIX] Fix multi-input custom score display on resetting default [MER-3117]

---

lib/oli/resources/collaboration.ex
lib/oli/resources/collaboration/post.ex
lib/oli/resources/collaboration/user_reaction_post.ex
lib/oli_web/live/delivery/student/lesson/annotations.ex
lib/oli_web/live/delivery/student/lesson_live.ex
priv/repo/migrations/20240328190716_user_reaction_posts.exs

**NOTE:** Changes are currently based on [NG23-82 branch](https://github.com/Simon-Initiative/oli-torus/pull/4721) and includes those changes as well
https://eliterate.atlassian.net/browse/NG23-81
Implements the ability for a user to react to an existing note. Currently the only supported reaction is "like" however this could be expanded to other reaction types in the future.

[NG23-81] user reacts to an existing note

---

assets/src/apps/delivery/layouts/deck/LessonFinishedDialog.tsx
assets/src/apps/delivery/layouts/deck/components/ReviewModeHistoryPanel.tsx

Hey @bsparks, could you please look at the PR. Thanks

[BUGFIX] [MER-2487] | BB Unit 8: Launch Simulator - finishedDialog in Launch Simulator is seemingly obscured, preventing the 'x' from being shown.

---

.github/workflows/deploy.yml

Adds neutron to the list of deployment targets.
Github CI requires the config to be present in the branch you are trying to deploy.

[DEVOPS] Add new deployment target

---

lib/oli_web/live/resources/pages_view.ex

`ContainerEditor.add_new` changed its interface, but wasn't updated here in AllPages

[BUG FIX] Fix all pages page creation [MER-3128]

---

lib/oli/activities/realizer/query/builder.ex

This pr [MER-3028](https://eliterate.atlassian.net/browse/MER-3048) correct the filter by does_not_equal in Activity Bank

MER-3048-objective-filter-in-activity-bank-works-incorrectly

---

lib/oli/delivery/settings.ex
lib/oli_web/live/delivery/student/learn_live.ex
test/oli/delivery/settings_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-118) to the ticket. See also [comments](https://eliterate.atlassian.net/browse/NG23-113?focusedCommentId=22404) left on parent ticket
When all pages of a given due date are completed the whole group is hidden.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/1c73effb-6b00-42b9-a3b3-5c4f874aaf4d
They collapse/expand independently of other date-groupers. Ex, if the same subsection is grouped in more than one due date, they can be collapsed independently and the collapsed "state" persists after toggling completed pages
https://github.com/Simon-Initiative/oli-torus/assets/74839302/348c4749-90a2-462b-b61e-5029ad7b2077
https://github.com/Simon-Initiative/oli-torus/assets/74839302/f573f868-8474-4bbf-a7eb-4d612070cbbc …

[NG23-118] Group module content by due date

---

lib/oli/groups.ex
lib/oli_web/live/community_live/invitation.ex
lib/oli_web/live/community_live/show_view.ex
test/oli_web/live/community_live_test.exs

[MER-2614](https://eliterate.atlassian.net/browse/MER-2614)
This PR modifies the input used to add an institution to a community in the community overview view. 
it changes that input making it dropdown, to allow users to choose among the available institutions that have already been created.
If an institution has already been added to a community, it will be shown as disabled in the dropdown list so that the user cannot add it again.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/6613f445-0f39-453c-a618-b7f0f314166c
[MER-2614]: https://eliterate.atlassian.net/browse/MER-2614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX][MER-2614] Trying to add an institution to community fails

---

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
lib/oli_web/controllers/api/attempt_controller.ex

Reverts the changes from MER-3000 as this causes problems for adaptive pages.
Note, in `evaluate.ex` the only real change is the removal of the outermost `if...then`, to remove:
```
if activity_attempt.lifecycle_state in [:submitted, :evaluated] do
Logger.info(
"These changes could not be saved as this attempt may have already been submitted"
)
{:error, :already_submitted}
else
```
The rest of the diff is unfortunately just simply whitespace change. 
To verify this change:
**Without this fix in place**
1. Ingest the attached course project, publish and create an Open and Free course
2. As a student, visit the adaptive page that is in the course section (the only one).
3. Visit any screen, then use Table Of Contents to navigate back to first screen. Click another screen.
Expect: View …

[BUG FIX] [MER-3152] Remove prevention of submission on already submitted attempts

---

lib/oli/delivery/evaluation/rule.ex
test/oli/delivery/evaluation/rule_eval_test.exs

This makes range answer evaluation independent of the order in which the bounds are listed in the rule. While torus authoring sorts range bounds values into low, high order when they are constants, it cannot do this when dynamic variables are used. In this case the order of bounds could depend on randomly selected values. It would be possible for authors to handle this by including jasvascript code to sort bound values in the dynamic variable generation script, but there is no reason to put this burden on authors and allow unexpected errors when the system can easily handle bounds in any order.

[ENHANCEMENT] [MER-3134] make range checking order independent

---

lib/oli_web/components/delivery/layouts.ex

[Link ](https://eliterate.atlassian.net/browse/NG23-145)to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/36ff04e1-3280-4ba4-8930-72841dc277a1
https://github.com/Simon-Initiative/oli-torus/assets/74839302/28bac693-1bd3-4279-9262-9f97126e66f3

[BUG FIX] [NG23-145] Back arrow on pages does not work

---

assets/src/components/activities/multi_input/sections/QuestionTab.tsx
lib/oli_web/components/delivery/practice_activities/practice_activities.ex
lib/oli_web/components/delivery/surveys/surveys.ex
test/oli_web/live/delivery/instructor_dashboard/overview/surveys_tab_test.exs

[MER-2917](https://eliterate.atlassian.net/browse/MER-2917)
This PR fixes a bug that happening when displaying students' text and numeric responses for `Multi Input` activities in the `Scored Activities` and `Surveys` tabs.
It happened that if 2 or more students answered the same thing, the answers were displayed as many times as the total number of answers for all students.
With these changes, the answers made by the students will be displayed, but without specifying the number of times they were answered by each of the students.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/5e8520d1-6f4e-49bd-822d-00af9b195d91
[MER-2917]: https://eliterate.atlassian.net/browse/MER-2917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-2917] Fix duplicated answers

---

assets/src/phoenix/app.ts
assets/src/phoenix/session_timeout.tsx
assets/styles/authoring/advanced-authoring.scss
lib/oli_web/plugs/put_session_expiration_time_cookie.ex
lib/oli_web/router.ex
lib/oli_web/templates/layout/authoring.html.leex
lib/oli_web/templates/layout/chromeless.html.heex
lib/oli_web/templates/layout/delivery.html.heex
lib/oli_web/templates/layout/delivery_from_payment.html.heex
lib/oli_web/templates/layout/error.html.eex
lib/oli_web/templates/layout/lti.html.eex

Ticket [MER-2629](https://eliterate.atlassian.net/jira/software/c/projects/MER/issues/MER-2629)
This PR introduces the logic for displaying session timeouts. The expiration time is retrieved directly from Pow via its Genserver MnesiaCache. Subsequently, this expiration time is transmitted to the client as a cookie. On the client side, a JavaScript code segment is executed to manage the rendering of two messages: a countdown warning set to activate 5 minutes before expiration, and a modal that appears upon expiration. The modal includes a "Close" button, which when clicked, reloads the page, redirecting the user to the Login page.
[MER-2629]: https://eliterate.atlassian.net/browse/MER-2629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-2629] timeout loss of authentication messaging

---

lib/oli/delivery/attempts/core.ex
lib/oli/delivery/attempts/page_lifecycle/ungraded.ex
lib/oli/delivery/metrics.ex
lib/oli_web/controllers/api/page_lifecycle_controller.ex
test/oli_web/controllers/api/page_lifecycle_controller_test.exs

This adds a page lifecycle transition action to allow the client side adaptive player to mark the progress on a page to be complete.  This only adds the server side, the client side work will follow up in another PR.

[ENHANCEMENT] [MER-3181] Allow progress to be set from client

---

assets/css/app.css
assets/src/hooks/scroller.ts
lib/oli/resources/collaboration.ex
lib/oli/resources/collaboration/post.ex
lib/oli_web/live/delivery/student/lesson/annotations.ex
lib/oli_web/live/delivery/student/lesson_live.ex
test/oli/resources/collaboration_test.exs

https://eliterate.atlassian.net/browse/NG23-83
Implements the ability for a user to search their notes and posts in the sidebar. When a search result it clicked, the point block that contains the note is selected and the replies for the particular post are loaded.
This PR also includes some changes specified by the designers to allow a bubble to be deselected, showing all notes for a page regardless of point block annotations, however a block must be selected in order to create a note. Seen in the mockup video below.
https://github.com/Simon-Initiative/oli-torus/assets/6248894/64cb0c9f-c258-404d-af24-7f1cb4aa04fa
It's worth mentioning this PR does not pre-compute an index column for the ts_vector used by postgres to facilitate search. This can be added later if performance becomes a …

[FEATURE] [NG23-83] user searches within notes panel

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live_session_plugs/redirect_adaptive.ex
lib/oli_web/router.ex
test/oli_web/live/delivery/student/lesson_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-145) to the ticket
This ticket complements the work done on [this PR](https://github.com/Simon-Initiative/oli-torus/pull/4746) by fixing the back button for adaptive pages.
It also fixes the size of the brand icon that was too big in the adaptive pages template.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/0561c5c5-d995-4161-8321-7ab4352de173
https://github.com/Simon-Initiative/oli-torus/assets/74839302/1a3cd446-0331-46fa-b619-b862a52d923a

[BUG FIX] [NG23-145] Back arrow on adaptive pages does not work

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[NG23-164](https://eliterate.atlassian.net/browse/NG23-164)
In the Learn view we currently allow to hide/show sections and subsections in two different ways:
1) Hide/Show Completed pages
2) By clicking a specific section or subsections.
This PR disables 2.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/7101a826-6bab-4726-b9c8-d583a0f0901b
[NG23-164]: https://eliterate.atlassian.net/browse/NG23-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [NG23-164] Remove ability to collapse specific sections and subsections

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

While working on [NG23-124](https://github.com/Simon-Initiative/oli-torus/pull/4758) I did a small refactor that introduced a small bug: the clock icon was not being shown for graded pages.
On the other hand, slider fade background color was updated to match the new page background color.
[NG23-124]: https://eliterate.atlassian.net/browse/NG23-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-124] Render clock icon for graded pages

---

lib/oli_web/templates/layout/_project_sidebar.html.eex

[MER-3094](https://eliterate.atlassian.net/browse/MER-3094)
This PR adds `Experiments` menu item in the left sidebar to be accessed by an author or admin user, which redirects to the `Experiments` view.
[MER-3094]: https://eliterate.atlassian.net/browse/MER-3094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3094] Create experiments menu item

---

lib/oli_web/templates/layout/default.html.heex

Ticket: [MER-3218](https://eliterate.atlassian.net/browse/MER-3218)
This PR added the correct footer to the login page so that it can show the version information on the bottom-right corner.
[MER-3218]: https://eliterate.atlassian.net/browse/MER-3218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3218] Fix incorrect footer call

---

lib/oli/authoring/course/project.ex
lib/oli/delivery/paywall.ex
lib/oli_web/live/products/details/actions.ex
lib/oli_web/live/products/details_view.ex
lib/oli_web/live/products/products_to_transfer_codes.ex
lib/oli_web/live/projects/overview_live.ex
lib/oli_web/live/projects/transfer_payment_codes.ex
priv/repo/migrations/20240426181431_allow_transfer_payment_codes.exs
test/oli/delivery/paywall_test.exs
test/oli_web/live/products_test.exs
test/oli_web/live/projects/overview_live_test.exs

[MER-3160](https://eliterate.atlassian.net/browse/MER-3160)
This PR adds the functionality to transfer payment codes from one product to another product of the same project. 
On the one hand, an author/admin will be able to enable or disable this functionality from the overview view of a project. 
Also, from the overview view of a product, another product of the same project can be selected to transfer the payment codes of the current product. 
- Project overview
- Product overview
[MER-3160]: https://eliterate.atlassian.net/browse/MER-3160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3160] Flexibility payment code infrastructure

---

assets/src/phoenix/activity_bridge.ts
lib/oli/delivery/attempts/activity_lifecycle.ex
lib/oli_web/controllers/api/attempt_controller.ex
test/oli_web/controllers/api/attempt_controller_test.exs

[MER-3153](https://eliterate.atlassian.net/browse/MER-3153)
This PR adds checks to see if an activity or part has already been submitted or evaluated at the time of saving. 
A message will be displayed to the student if this happens.
Feel free to suggest any changes to the texts shown to the student in case he/she tries to submit or save an activity or part that has been previously submitted or evaluated, as well as suggest other test cases.
[MER-3153]: https://eliterate.atlassian.net/browse/MER-3153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3153] Re-implement lost quiz answers second tab

---

lib/oli/resources/collaboration.ex
lib/oli_web/live/delivery/student/lesson/annotations.ex
lib/oli_web/live/delivery/student/lesson_live.ex
test/oli/delivery/analytics/analytics_test.exs
test/oli/resources/collaboration_test.exs

https://eliterate.atlassian.net/browse/NG23-165
Fixes an issue where the "my notes" query would return all notes for all users in a particular section and resource.
"My Notes" are intended to be private. This PR fixes the query so that when visibility is :private, only the notes for the current user are returned.
This PR also fixes an issue where search results within replies for an anonymous user/guest would crash the view.

[BUG FIX] [NG23-165] My notes filter not working correctly

---

lib/oli/resources/collaboration.ex
lib/oli_web/live/delivery/student/discussions_live.ex
lib/oli_web/live/delivery/student/lesson/annotations.ex
lib/oli_web/live/delivery/student/lesson_live.ex
test/oli_web/live/delivery/student/discussions_live_test.exs

https://eliterate.atlassian.net/browse/NG23-86
https://eliterate.atlassian.net/browse/NG23-88
Adds the ability for a user to search course discussions and private notes no the discussions page.

[FEATURE] [NG23-86] [NG23-88] user can search course discussions in discussion menu

---

.github/workflows/build.yml
test/oli_web/live/grades_live_test.exs

https://eliterate.atlassian.net/browse/NG23-179
While updating the ci/cd config, a new environment called ci-build-test was added to easily setup the oli.env for ci build test jobs. But because of the way Github injects this environment variable (includes '\r' characters), using this method made it unnecessarily difficult to process. As a result, the build jobs are simply using the example env file in the repository and the environment is no longer used.
However, this environment is now cluttering the deployment grid in Jira. This ticket is to just remove this environment for now.
Once this lands, we can remove the environment from Github

[CHORE] [NG23-179] remove unnecessary ci environment

---

lib/oli/resources/collaboration.ex
lib/oli/resources/collaboration/post.ex
lib/oli_web/live/delivery/student/discussions_live.ex
lib/oli_web/live/delivery/student/lesson/annotations.ex
lib/oli_web/live/delivery/student/lesson_live.ex
test/oli_web/live/grades_live_test.exs

Adds a "Go to Page" link to notes that links to the page where a note was created. Also adds a virtual field to facilitate link creation and updates the queries used to populate the new field.
This feature adds a bit of overhead to the simplified queries to gather the necessary slug in order to facilitate link creation. Now these queries must also join through the section resource, spp, published resource to revision records. This query however, is similar to the queries that were already in place before the social annotation work.

[FEATURE] [NG23-89] add a link to go to a content page from a post

---

lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

[MER-3234](https://eliterate.atlassian.net/browse/MER-3234)
This PR fixes the pagination error that was happening in the `Student Exceptions` view.
It seems to be conflicting with events that are executed within the same table.
The solution was to move the paging component outside the form that wrap the table to avoid such conflicts.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/10daacf4-df25-4c12-a82a-741aba50caaa
_**The paging limit was set to 2 elements per page for demonstration purposes._ 
[MER-3234]: https://eliterate.atlassian.net/browse/MER-3234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3234] Pagination back to first page student exceptions

---

lib/oli/authoring/editing/resource_editor.ex
lib/oli/authoring/experiments.ex
lib/oli/publishing/authoring_resolver.ex
lib/oli_web/live/experiments/experiments_live.ex
lib/oli_web/live/resources/alternatives_editor.ex
lib/oli_web/router.ex
test/oli/authoring/experiments_test.exs
test/oli_web/live/experiments_live_test.exs
test/oli_web/live/resources/alternatives_editor_test.exs

Ticket: [MER-3096](https://eliterate.atlassian.net/browse/MER-3096)
This PR introduces the capability to enable/disable A/B testing. When enabled for the first time, a revision is created. Subsequent actions on the checkbox only toggle the ability to edit the content of the revision.
Endpoint: 
`http://localhost/authoring/project/__SOME_PROJECT__/experiments`
https://github.com/Simon-Initiative/oli-torus/assets/47334502/575ac111-d7d1-476c-829a-48bbb001e3cf
Note: A significant portion of code was copied and adapted for the OliWeb.Resources.AlternativesEditor module. I recognize that some refactoring could reduce complexity. However, I refrained from doing so as this PR is currently blocking others.
[MER-3096]: https://eliterate.atlassian.net/browse/MER-3096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

[FEATURE] [MER-3096] User enables AB testing with Upgrade

---

lib/oli_web/live/experiments/experiments_live.ex
test/oli_web/live/experiments_live_test.exs

Ticket: [MER-3098](https://eliterate.atlassian.net/jira/software/c/projects/MER/issues/MER-3098)
This PR added 2 buttons to the experiment page. However, there is no functionality triggered by them yet, as per the instructions of the ticket.
Endpoint:
`http://localhost/authoring/project/__SOME_PROJECT__/experiments`
https://github.com/Simon-Initiative/oli-torus/assets/47334502/d8ce1051-7b93-4d2c-b42d-ed08d8109fe1
Note: This PR has been branched off from [PR-4788](https://github.com/Simon-Initiative/oli-torus/pull/4788).
[MER-3098]: https://eliterate.atlassian.net/browse/MER-3098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3098] Add download buttons to experiments

---

lib/oli/analytics/event_emitter.ex
lib/oli/analytics/summary/xapi/page_viewed.ex
lib/oli/delivery/snapshots/s3_uploader_worker.ex
lib/oli_web/live/delivery/student/lesson_live.ex

This PR instruments the LessonLive view to emit a new "Page Viewed" xAPI event to S3 event storage.  This is critical to get into place so that starting post V28 some interested parties can do some analysis involving the complete history of all page views. 
There will be a follow on piece of work in MER-3251 that will replace the current event emitting approach with an optimized impl

[ENHANCEMENT] [MER-3246] Emit the new page_viewed xapi event

---

assets/src/phoenix/activity_bridge.ts
lib/oli/delivery/attempts/activity_lifecycle.ex
lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
lib/oli_web/controllers/api/attempt_controller.ex
test/oli_web/controllers/api/attempt_controller_test.exs

[MER-3253](https://eliterate.atlassian.net/browse/MER-3253)
This PR roll back the changes made in [MER-3000](https://eliterate.atlassian.net/browse/MER-3000) and [MER-3153](https://eliterate.atlassian.net/browse/MER-3153), in order to ensure that adaptive pages do not break when browsing them.
I have skipped some tests, as they may be needed when we re-implement MER-3000 requirements.
[MER-3253]: https://eliterate.atlassian.net/browse/MER-3253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-3000]: https://eliterate.atlassian.net/browse/MER-3000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-3153]: https://eliterate.atlassian.net/browse/MER-3153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

[BUG FIX] [MER-3253] implements necessary rollback

---

lib/oli_web/components/delivery/deliberate_practice_card.ex
lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live/delivery/student/explorations_live.ex
oli.example.env
test/oli_web/controllers/legacy_superactivity_controller_test.exs
test/oli_web/controllers/page_delivery_controller_test.exs
test/oli_web/live/collaboration_live_test.exs
test/oli_web/live/delivery/student/explorations_live_test.exs
test/oli_web/plugs/maybe_gated_resource_test.exs

Changes the links in the Deliberate Practice view to link to the new lesson LiveView, as opposed to the old page delivery view.
Also updates the page_delivery_controller `:page` route to redirect to the new lesson live view and fixes tests where it makes sense and skips other now obsolete tests.
A followup task to reconcile these obsolete tests with tests in the new lesson liveview has been created https://eliterate.atlassian.net/browse/NG23-195

[NG23-187] Practice pages links lead to old page layout

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/live/delivery/student/index_live.ex

This PR softens the colors to increase contrast and readability in light mode.
**Before:**
**After:**
**Before:**
**After:**

[ENHANCEMENT] [NG23-183] soften the colors to increase contrast and readability in light mode

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/review_live.ex
lib/oli_web/live_session_plugs/init_page.ex
lib/oli_web/live_session_plugs/redirect_adaptive.ex
lib/oli_web/router.ex
test/oli_web/live/delivery/student/lesson_live_test.exs
test/oli_web/live_session_plugs/redirect_adaptive_test.exs
test/support/factory.ex

[Link](https://eliterate.atlassian.net/browse/NG23-160) to the ticket
The problem was that adaptive pages with no attempts in progress were redirected by the `RedirectAdaptiveChromeless` live session plug to another prologue view that was not correctly handling LiveView events (for instance, the "begin_attempt" event, or even the user menu interaction).
I split the `init_page` live_session plug and refactored the `RedirectAdaptiveChromeless` one to only redirect to the adaptive pages route when the attempt is in progress. All other page progress states are not redirected, so the student ends up seeing the "common" prologue page (the same that is used for graded pages that handles LiveView events correctly). 
Besides handling LiveView events correctly, now the prologue page for adaptive …

[BUG FIX] [NG23-160] Lesson does not launch when clicking begin attempt

---

lib/oli_web/components/delivery/instructor_dashboard.ex
lib/oli_web/components/layouts/instructor_dashboard.html.heex
test/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live_test.exs

Ticket [MER-3179](https://eliterate.atlassian.net/browse/MER-3179).
This PR put the navigation menu bar at the top of the page even when scrolling down.
https://github.com/Simon-Initiative/oli-torus/assets/47334502/ccf5832d-a548-4922-80b2-c9773160f0e8
[MER-3179]: https://eliterate.atlassian.net/browse/MER-3179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-3179] Set navigation menu bar at the top of the page on vertical scroll

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

Link to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/5bb8dc14-3ec9-4b3d-8bfc-3472f630b958
https://github.com/Simon-Initiative/oli-torus/assets/74839302/59f68c80-c825-4211-a6ff-9b0f4de260f4

[FEATURE] [NG23-201] Remove the intro and LO pop-up for modules

---

lib/oli/delivery/gating/condition_types.ex
lib/oli/delivery/gating/condition_types/progress.ex
lib/oli/delivery/gating/gating_condition.ex
lib/oli_web/live/sections/gating_and_scheduling/form.ex
lib/oli_web/live/sections/gating_and_scheduling/gating_condition_store.ex
lib/oli_web/live/sections/gating_and_scheduling/table_model.ex
test/oli/delivery/gating/strategies/progress_test.exs
test/oli_web/live/sections/gating_and_scheduling_test.exs

[MER-3219](https://eliterate.atlassian.net/browse/MER-3219)
This RP adds a new type of `Gating Condition` so that it can be defined in a product.  
It adds a `Progress` type that will evaluate the progress of a source resource of type `Practice Page`.
This will evaluate the progress that is stored in ResourceAccess for the source resource to determine if the learner has access to a target resource defined in the Gating Condition.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/40476b49-f340-437e-81ed-17e1068fd562
[MER-3219]: https://eliterate.atlassian.net/browse/MER-3219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3219] Allow page progress trigger practice gating

---

.gitignore
config/test.exs
lib/oli/analytics/xapi.ex
lib/oli_web/components/delivery/user_account.ex
lib/oli_web/live/delivery/student/index_live.ex

This PR restores the color changes made in NG23-183 that were lost in a recent merge to master.
While I was in here I also addressed [NG23-202](https://eliterate.atlassian.net/browse/NG23-202), an issue where they entire header color changes in light mode when opening the user menu
[NG23-202]: https://eliterate.atlassian.net/browse/NG23-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR also includes some fixes related to Broadway tests that were failing the CI build

[ENHANCEMENT] [NG23-183] [NG23-202] Fix light mode style issues and restore styles lost in prev merge

---

lib/oli_web/pow/author_context.ex
lib/oli_web/pow/user_context.ex

[MER-3129](https://eliterate.atlassian.net/browse/MER-3129)
This PR aims to ensure that the URLs to the `login` and `password reset` views that are added in the email that a learner or author receives when trying to create an existing account are absolute paths. 
This would ensure a link to a known path in `Torus`, regardless of the environment where the application is running.
[MER-3129]: https://eliterate.atlassian.net/browse/MER-3129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3129] Ensure absolute URLs

---

lib/oli/delivery/sections.ex
test/oli_web/live/delivery/instructor_dashboard/insights/learning_objectives_tab_test.exs
test/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab_test.exs

https://eliterate.atlassian.net/browse/NG23-226
This PR addresses Part 1 outlined in https://eliterate.atlassian.net/browse/TRIAGE-641 by removing the inner join clause and making a separate query to gather the contained objectives for a section. Then these two results are combined as a post processing step.
This should fix the LO not displaying problem, however the "Filter by Module" issue still remains and will need to be followed up in another PR.
This has not been tested on with any significant amount of data yet.

[BUG FIX] [NG23-226] remove inner join to contained_objectives and process in two separate queries

---

assets/src/apps/scheduler/ScheduleGrid.tsx

[NG23-216](https://eliterate.atlassian.net/browse/NG23-216)
Fix text styling for dark mode in the Legend section of the Scheduling page (`/sections/{SECTION_SLUG}/schedule`).
**Before**:
**After:**
[NG23-216]: https://eliterate.atlassian.net/browse/NG23-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-216] Fix dark mode in Scheduling page

---

lib/oli_web/live/delivery/student/utils.ex
lib/oli_web/live_session_plugs/init_page.ex

Attempts to follow links to "loose" pages not in the hierarchy were triggering an exception. Such linked pages are used frequently in migrated courses. This PR implements a provisional fix that prevents the exception and allows these pages to be rendered without error so that testing of these courses can continue. However, a smarter solution might be desired in the longer term.
The error arose because:
- LiveView assigns `current_page, next_page, prev_page` are initialized from the PreviousNextIndex in`lib/oli_web/live_session_plugs/init_page.ex`
- When following link to a "loose" page (one not in the curriculum) these wind up all nil because loose pages are not in the PreviousNextIndex, which is derived from the flattened hierarchy.
- The page rendering templates in` …

[BUG FIX] [MER-3293] avoid error on linked pages not in hierarchy

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[NG23-208](https://eliterate.atlassian.net/browse/NG23-208)
Fix the missing logo on the Lesson view.
Fix the display of the brand logo on the Learn view.
https://github.com/Simon-Initiative/oli-torus/assets/26532202/f56df330-f990-48e9-9f51-5b969b711398
[NG23-208]: https://eliterate.atlassian.net/browse/NG23-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-208] Fix brand logo issue on Learn and Lesson views

---

lib/oli/delivery/evaluation/rule.ex
test/oli/delivery/evaluation/rule_eval_test.exs

Torus answer rule evaluation was incorrectly parsing numbers in e-notation with positive exponent, but no decimal point. For example, a number entered as 5e35 or 5e+35 would be parsed and evaluated as the integer 5, both in author answer specs and in answers typed by student. This led to errors evaluating answers in Chemistry II course using large values specified that way. For example, if the answer range was specified as [4e35, 6e35], torus evaluation would reject an answer of 4.1e35 as incorrect, but accept 5e36 or simply 5 as correct. 
This also corrects errors processing exponential notation using capital E, which can arise from migration and also lead to evaluation errors in Chemistry II. Capital E is quite standard and is allowed in the torus authoring interface. But code in rule …

[BUG FIX] [MER-3286] [MER-3315] Fix evaluation of e-notation with positive exponent, no decimal point

---

assets/package.json
assets/yarn.lock
lib/oli_web/live/delivery/student/learn/components/view_selector.ex
lib/oli_web/templates/layout/authoring.html.leex
lib/oli_web/templates/layout/delivery.html.heex

https://eliterate.atlassian.net/browse/NG23-194
Adds the new tabler icon webfont link to authoring and delivery and modifies the learn page view selector icon to use the new library.
For other future icon variations which are custom or do not directly exist in the webfont or React library, the SVG should be copied in the Icons module (or JSX) and used that way.

[ENHANCEMENT] [NG23-194] Icons visual improvements

---

lib/oli/analytics/by_activity.ex
lib/oli/analytics/by_objective.ex
lib/oli/analytics/by_page.ex
lib/oli/analytics/common.ex
lib/oli/publishing/delivery_resolver.ex
lib/oli_web/live/insights/insights.ex

This PR [MER-2932](https://eliterate.atlassian.net/browse/MER-2932) fixes the filter by section by adding a new argument to the analytics_by_activity function in the Common module. 
The new argument specifies the section to filter in the query. 
Additionally, the courses for the product are obtained using Oli.Publishing.DeliveryResolver.get_sections_for_products, and these are passed to the function to filter all analytics.
[MER-2932]: https://eliterate.atlassian.net/browse/MER-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-2932] filter-insights-by-product-course-section

---

lib/oli_web/live/delivery/student/lesson_live.ex

https://eliterate.atlassian.net/browse/NG23-212
https://eliterate.atlassian.net/browse/NG23-213
This PR fixes 2 issues that were identified related to the initial load of a graded page:
1. Graded page activities weren't loading on first visit after attempt creation. A reload of the page would resolve the issue
2. The system would throw an error when trying to emit a page viewed event
Both of these issues were caused by the socket not being updated with the latest page context and crashing before proceeding with the remaining logic during the start attempt phase.

[BUG FIX] [NG23-212] [NG23-213] fix an issue where graded pages fail to load activities on first visit

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-111?focusedCommentId=22963) to the ticket comment
As confirmed in the [last demo](https://youtu.be/hP8K9WcJMg0?list=PLxXjewniGhOtUH5fW079AcQdw_JRSx8tA&t=553), the page icon on the cards should not be there.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/3d627dfd-c4a2-49f6-a5d3-29f5e93850f4
https://github.com/Simon-Initiative/oli-torus/assets/74839302/5fd9b9d6-f72d-4ec0-aa4d-27f7ea3c2558
https://github.com/Simon-Initiative/oli-torus/assets/74839302/088be8c2-3c72-40a6-8101-de39a86a6fce
https://github.com/Simon-Initiative/oli-torus/assets/74839302/8f7c88ef-1c31-415e-ac91-c2c99b64d1c4
https://github.com/Simon-Initiative/oli-torus/assets/74839302/78876238-6e01-48d2-ad77-1fc97a695c84 …

[BUG FIX] [NG23-111] Module tiles and cards improvements learn page - part 2

---

lib/oli_web/live/delivery/student/discussions_live.ex

This PR fixes an issue with the "Load more posts" function for discussions and note where applying a sort would break the ability to load more notes due to this assign not properly being reset.

[BUG FIX] [NG23-90] fix an issue where offset was not being properly reset on sorting change

---

lib/oli_web/live/delivery/student/lesson_live.ex

https://eliterate.atlassian.net/browse/NG23-212
This PR fixes an issue where beginning an attempt tried to load all activity scripts, which ultimately fails and shows an error message to the user because of another issue which was identified and captured in https://eliterate.atlassian.net/browse/NG23-233
The fix here is to actually be smarter about which scripts are being loaded when beginning an attempt. By assigning only the scripts required by the page when starting the attempt, we can avoid the error and optimize the assets being loaded.

[BUG FIX] [NG23-212] fix an issue where loading all activity scripts when beginning attempt crashes page

---

lib/oli/delivery/metrics.ex
lib/oli_web/components/delivery/content/card_highlights.ex
lib/oli_web/components/delivery/content/content.ex
lib/oli_web/components/delivery/students/students.ex
lib/oli_web/icons.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
test/oli_web/live/delivery/instructor_dashboard/insights/content_tab_test.exs
test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs

[MER-3182](https://eliterate.atlassian.net/browse/MER-3182)
This PR adds cards to the `Content` and `Student` views in the instructor dashboard, which will allow to filter the content of the tables by different metrics. 
Each of the cards corresponds to a different metric and they can be selected and deselected in order to filter the content of the table showing the data corresponding to each tab.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/096bca4d-b96f-4737-ada4-ea5039071702
[MER-3182]: https://eliterate.atlassian.net/browse/MER-3182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3182] Summary card highlights filter content - Part 1

---

assets/src/apps/delivery/layouts/deck/DeckLayoutHeader.tsx
assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
lib/oli_web/live_session_plugs/init_page.ex
test/oli_web/live/delivery/student/lesson_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-159) to the ticket
With this fix, the adaptive page's back button redirects the student to the page from which they accessed the adaptive page.
Before the fix the student was always redirected to the explorations page, not considering that an adaptive page may not necessarily be an exploration.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/77ca1491-3089-49a8-a454-89cf31b19c36
_**Note:**_ It may lead to confusion that when accessing the page we read at the center of the screen a title that says "Climate Exploration" and we were supposed to be accessing an adaptive page that was **not** an exploration. The reason is that I built an adaptive page (not an exploration) by grabbing the "Climate Exploration" page and changing its …

[BUG FIX] [NG23-159] Adaptive pages back button

---

lib/oli_web/live/delivery/student/utils.ex

[Link](https://eliterate.atlassian.net/browse/NG23-156?focusedCommentId=23052) to the comment in the ticket
I could not reproduce the issue reported in any browser (tried Chrome, Firefox, Safari and Arc).
Anyway, this PR improves the responsiveness of the tooltip by rendering the text in more than one line in case the text overflows the tooltip width. So, although I couldn't reproduce the reported error in my local env, this improvement should have fixed it.
To test it, I hardcoded some longer texts in my local dev to validate the tooltip's expected behavior with different text lengths, as shown in the following video:
https://github.com/Simon-Initiative/oli-torus/assets/74839302/953a2b1b-90f9-4acb-b18a-08571d164379
**notice that the texts do not match the proficiency icons, as I tweaked …

[BUG FIX] [NG23-156] Create in context learning proficiency - part 2

---

lib/oli_web/live/curriculum/container/container_live.ex
lib/oli_web/live/curriculum/entries/options_modal.ex
lib/oli_web/live/resources/pages_view.ex
test/oli_web/live/curriculum/entries/options_modal_content_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-167) to the ticket
This feature allows an author to set an intro content to a page (both from the curriculum or the page view).
https://github.com/Simon-Initiative/oli-torus/assets/74839302/92d6f4d4-5654-41de-8eaf-2c548292f805
Some minor bugs were found and fixed while working on the ticket
A validation in the form was not correctly being done, so the form didn't allowed the user to save it
https://github.com/Simon-Initiative/oli-torus/assets/74839302/f9289a10-d486-44e6-b5a8-72bcacc6bf40
https://github.com/Simon-Initiative/oli-torus/assets/74839302/b0042999-4dc0-448c-9ae2-b7d0bce7eda9
When changing any form input, an intro video (with no content at all) appeared.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/9c101c5e-d84c-4 …

[FEATURE] [NG23-167] Intro content input for explorations and practice pages

---

lib/oli_web/components/delivery/student.ex
lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[NG23-221](https://eliterate.atlassian.net/browse/NG23-221)
Do not show the duration in minutes for a resource when it is not set.
**Before:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/8daae256-561c-461e-b4be-c92fd2ce9fd8
**After:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/a5c09f2d-c78f-424b-a1c1-0b1bcf48341d
[NG23-221]: https://eliterate.atlassian.net/browse/NG23-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [NG23-221] Do not show ? when duration time is not set on resource

---

assets/src/components/activities/multi_input/MultiInputDelivery.tsx
assets/src/components/activities/response_multi/ResponseMultiInputDelivery.tsx
assets/src/components/activities/vlab/VlabDelivery.tsx

Request hint lightbulb icon was being shown on graded pages for multi-input, response multi, and vlab questions, though hints do not show on clicking.  This hides it on graded pages for those activity types.

[BUG FIX] [MER-3173] hide hint icon on graded page for multi-input/response-multi/vlab

---

assets/src/apps/authoring/components/ComponentToolbar/UndoRedoToolbar.tsx
assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx
assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx
assets/src/hooks/useKeyDown.tsx

There was a request to handle some shortcuts specific to Mac and Windows:
1. On Mac,` cmd+y` works but it also opens chrome history, so it makes it unusable, can we remove this keyboard control for Mac?
2. Implement `cmd+shift+z` is the “traditional” redo on Mac

[BUG FIX] [MER-3146] Advanced Author and Simple Author/Flowchart: Keyboard Shortcuts Request on Canvas

---

lib/oli_web/components/common.ex
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
test/oli_web/live/delivery/instructor_dashboard/insights/learning_objectives_tab_test.exs

[MER-3187](https://eliterate.atlassian.net/browse/MER-3187)
This PR adds a multi select input filter to the `Learning Objectives` view within the `Instructor Dashboard`. 
It can be selected by one or more proficiency types (Low, Medium and High) and the data in the table showing the learning objectives will be filtered.
In addition, a button is added to clear all applied filters in this view.
- Light Mode
https://github.com/Simon-Initiative/oli-torus/assets/16328384/84ea65eb-42bc-4891-9692-bac172555d12
- Dark Mode
https://github.com/Simon-Initiative/oli-torus/assets/16328384/79962236-3a52-4b02-8427-48a3902f4e32
[MER-3187]: https://eliterate.atlassian.net/browse/MER-3187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3187] Instructors custom filters learning objectives report

---

lib/oli/delivery/previous_next_index.ex
lib/oli_web/components/delivery/layouts.ex
lib/oli_web/live_session_plugs/init_page.ex
test/oli/delivery/previous_next_index_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[NG23-178](https://eliterate.atlassian.net/browse/NG23-178)
Set the following as a lesson navigation rule:
1. If the next or previous page is a **module**, redirect the student to the Learn view (`/sections/{SECTION_SLUG}/learn`), highlighting the container.
2. Otherwise, redirect to the specified resource view (`/sections/{SECTION_SLUG}/lesson/{RESOURCE_SLUG}`) (page or unit).
3. Remove sections and subsections from the footer navigation.
**Before:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/a373d684-a4b9-4a0c-ac28-333e7129a995
**After:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/11919794-4f30-4956-9b11-6719c93453bf
[NG23-178]: https://eliterate.atlassian.net/browse/NG23-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …

[ENHANCEMENT] [NG23-178] Improve navigation when prev or next resource is a section or subsection

---

lib/oli_web/components/delivery/content/card_highlights.ex
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
test/oli_web/live/delivery/instructor_dashboard/insights/learning_objectives_tab_test.exs

[MER-3186](https://eliterate.atlassian.net/browse/MER-3186)
This PR adds cards in `Learning Objectives` tab in the instructor dashboard, which will allow to filter the content of the tables by different metrics.
Each of the cards corresponds to a different metric and they can be selected and deselected in order to filter the content of the table showing the data corresponding to each card.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/70b2d37a-2418-43e4-a14a-e80c710b057d
[MER-3186]: https://eliterate.atlassian.net/browse/MER-3186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3186] Instructors summary highlights filter learning objectives report

---

lib/oli_web/live/experiments/experiments_live.ex
test/oli_web/live/experiments_live_test.exs

Link the existing buttons in the experiments page to the experiments controller endpoints, so when a user clicks “Download Segment JSON” or “Download Experiment JSON” buttons, the JSON file should be downloaded to their computer.
See: https://eliterate.atlassian.net/browse/MER-3110

[ENHANCEMENT] [MER-3110] Download Segment and Experiment JSON files

---

lib/oli_web/live/resources/alternatives_editor.ex

The “Manage Alternatives” page should not show decision points or the “New decision point” button. This PR addresses that issue.

[ENHANCEMENT] [MER-3367] Removes the display of upgrade experiment on alternatives editor

---

lib/oli/analytics/by_activity.ex
lib/oli/analytics/by_objective.ex
lib/oli/analytics/by_page.ex
lib/oli/delivery/sections.ex
lib/oli/publishing.ex
lib/oli/publishing/delivery_resolver.ex
lib/oli_web/controllers/project_controller.ex
lib/oli_web/live/common/multi_select.ex
lib/oli_web/live/common/multi_select_options.ex
lib/oli_web/live/insights/insights.ex
lib/oli_web/router.ex
lib/oli_web/templates/layout/_project_sidebar.html.eex
lib/oli_web/templates/project/insights.html.eex
test/oli/delivery/sections_test.exs
test/oli_web/controllers/project_controller_test.exs
test/oli_web/live/insights/insights_test.exs

This PR finishes the work done in a series of PRs ([PR1](https://github.com/Simon-Initiative/oli-torus/pull/4643), [PR2](https://github.com/Simon-Initiative/oli-torus/pull/4725), [PR3](https://github.com/Simon-Initiative/oli-torus/pull/4777), [PR4](https://github.com/Simon-Initiative/oli-torus/pull/4845)), by fixing the latest bugs reported in [the ticket](https://eliterate.atlassian.net/browse/MER-2932?focusedCommentId=23199)
https://github.com/Simon-Initiative/oli-torus/assets/74839302/1a92b036-0c15-49eb-901a-04897ed7383f
https://github.com/Simon-Initiative/oli-torus/assets/74839302/eb779bc2-ab97-49ee-bf43-c0f0a09d5174
- The multiselect `live_component` was refactored to handle its own state (as suggested in the [docs](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html)) …

[BUG FIX] [MER-2932] Filter insights by product course section - part 2

---

assets/src/components/activities/logic_lab/LogicLabDelivery.tsx
assets/src/components/activities/logic_lab/LogicLabModelSchema.tsx
assets/src/components/activities/logic_lab/authoring-entry.ts

Externally written LogicLab was batching the entire large activity CreationContext object into the activity model for convenience. This is inappropriate, it bloats the object and includes a very large and unnecessary data structure, for example including everything else on the page, that will be noise on viewing its JSON or web page inspection. The only info used is the activity title (as it was at activity creation time)
This PR changes to only extract the info used, currently the title. 
This should not change the behavior in any way.

[CHORE] [MER-3172] Make LogicLab not include full CreationContext in model

---

lib/oli/delivery/metrics.ex

Got division by zero errors from a proficiency query in `Oli.Delivery.Metrics.proficiency_per_student_across/2` . Such an error prevents display of the Students page, and probably other displays showing proficiencies.  
This PR adds NULLIF guards around proficiency calculation denominators using `ResourceSummary.num_first_attempts` to prevent possible division by zero.  
The source of the error is not understood. The queries evidently were written on the assumption they will never get a 0 valued sum of `num_first_attempts` (though might get null). The error suggests some resource is unexpectedly causing an explicit 0 to be recorded in `num_first_attempts` in the resource summary table, rather than leaving it null. 
The error was observed in a somewhat unusual situation: a client-side …

[BUG FIX] [MER-3176] guard against division by zero in proficiency queries

---

assets/src/components/activities/common/authoring/actions/multipleChoiceActions.ts
assets/src/components/activities/common/authoring/actions/scoringActions.ts
assets/src/components/activities/common/responses/ActivityScoring.tsx
assets/src/components/activities/multi_input/MultiInputScoringMethod.tsx
assets/src/components/activities/multi_input/sections/AnswerKeyTab.tsx
assets/src/components/activities/response_multi/ResponseMultiInputScoringMethod.tsx
assets/src/components/activities/response_multi/sections/PartsTab.tsx
assets/src/data/activities/model/responses.ts

Migrated legacy questions may carry non-standard point values for correct responses and partial credit scores for incorrect responses. These get used by torus in scoring. However, since custom score editing was added to torus authoring, these migrated questions have problems because they do not include the flags being used by the newer torus authoring code to detect custom scoring:
- They display in authoring incorrectly as using default scoring when in fact they carry custom scores. So authors can't tell accurately what points are being assigned. This has been a problem for instructors in one class who add new questions to a quiz (picking up default 1 or 0 scoring) and have them mixed with migrated questions that have invisible non-default point values, so not all questions have equal …

[ENHANCEMENT] [MER-3368] make score authoring handle implicit custom scoring on migrated questions

---

lib/oli/delivery/metrics.ex
lib/oli_web/components/delivery/student.ex
test/oli/delivery/metrics/avg_score_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-174) to the ticket
The issue was that we were getting the raw average score for a page (`score` and `out_of`) from the `resource_summary` table instead of the `resource_attempt`
https://github.com/Simon-Initiative/oli-torus/assets/74839302/652ad83f-5c01-404d-b01f-989350dc2380
https://github.com/Simon-Initiative/oli-torus/assets/74839302/ba566faf-d0fe-4943-a585-586e6eeb1bd5

[BUG FIX] [NG23-174] Scroring inconsistency

---

lib/oli_web/router.ex
test/oli_web/live/delivery/student/learn_live_test.exs

Ticket: [NG23-248](https://eliterate.atlassian.net/browse/NG23-248)
This PR fixes a bug where a user hits a 500 error page when trying to open a section in Preview Mode and clicks on the Notes page. The issue was due to a typo when calling the corresponding module.
[NG23-248]: https://eliterate.atlassian.net/browse/NG23-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-248] Fix incorrect module namespace call

---

lib/oli_web/components/footer.ex
lib/oli_web/templates/layout/email.html.eex

Remove the Cookie Preferences link and version/build number from the email templates.
Before:
Now:
Other fixed email templates:

[BUG FIX] [MER-3227] Remove cookie preferences and version number in email footer

---

lib/oli/rendering/content/html.ex

Previewing expository pages containing video was causing 500 error due accessing nil resource_attempt. This prevents, using same code from following `ecl `rendering routine.

[BUG FIX] [MER-3375] prevent exception previewing pages with video

---

lib/oli_web/live/delivery/student_dashboard/initial_assigns.ex
test/oli_web/live/delivery/student_dashboard/student_dashboard_live_test.exs

Ticket: [NG23-231](https://eliterate.atlassian.net/browse/NG23-231)
This PR fixed an incorrect URL link when navigating back to the Student Reports from the Student Dashboard Content page.
Endpoint: `/sections/__SECTION_SLUG__/student_dashboard/__STUDENT_ID__/content`
[NG23-231]: https://eliterate.atlassian.net/browse/NG23-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX][NG23-231] Ng student reports link fails

---

assets/css/table.css
lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex
lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex

Ticket: [MER-3126](https://eliterate.atlassian.net/browse/MER-3126)
This PR added a note above the table of Student Exceptions (commit 361febd3c8200538a613f57381a1f08a584f947d) and fixed a bug where the **Available Date** and **Due Date** exceptions were not highlighted when they should have been (commit: bb2d880e637232013fad102164af45a7b1f6d8be).
https://github.com/Simon-Initiative/oli-torus/assets/47334502/e18f9888-2807-4e51-9844-1659e969d68d
[MER-3126]: https://eliterate.atlassian.net/browse/MER-3126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-3126] Removing availability date for student exception doesnt make assignment available

---

lib/oli/interop/export.ex
test/oli/interop/export.exs

[MER-3155](https://eliterate.atlassian.net/browse/MER-3155)
This PR try to fix the bug that is happening when a project that contain nil revisions is exported. 
We want to check if the revisions exist at the time of creating the hierarchy file, although I'm not sure these changes is what will fix the issue and if it's the best way to fix it
As mentioned in the ticket, this would be happening in a specific project within the Proton environment.
Looking at the AppSignal logs, I deduce that the cause of this problem may be what I'm trying to fix with this PR.
[MER-3155]: https://eliterate.atlassian.net/browse/MER-3155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3155] Prevents nil revision exporting project

---

assets/src/hooks/countdown.ts
lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/student.ex
lib/oli_web/live/delivery/student/home/components/schedule_component.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/schedule_live.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/home/components/schedule_component_test.exs
test/oli_web/live/delivery/student/index_live_test.exs
test/oli_web/live/delivery/student/utils_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-230) to the ticket
https://github.com/Simon-Initiative/oli-torus/assets/74839302/0706647a-bdb7-4bcf-9d2f-3852ea05704b
https://github.com/Simon-Initiative/oli-torus/assets/74839302/7624ca2c-10de-488a-a5f3-3b6d27191c6f
https://github.com/Simon-Initiative/oli-torus/assets/74839302/4f886ee5-aef9-4f84-814b-4d92c3ea2f8b
https://github.com/Simon-Initiative/oli-torus/assets/74839302/5893ed63-3b96-4750-ae7a-67861989d08e
https://github.com/Simon-Initiative/oli-torus/assets/74839302/6ae7b6c4-55e7-4116-8d6b-fbc5acf88cd1
https://github.com/Simon-Initiative/oli-torus/assets/74839302/d4792d36-ab7d-48aa-ae53-b4c4c6fa00dc

[FEATURE] [NG23-230] Correctly display time remaining on assignment card

---

lib/oli_web/live/delivery/student/discussions_live.ex
test/oli_web/live/delivery/student/discussions_live_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs

https://eliterate.atlassian.net/browse/NG23-206
Adds a tabbed interface for My Notes and Course Discussion. When course discussion is disabled, only the notes tab is displayed.

[FEATURE] [NG23-206] User enables/disables both Notes and Course Discussions

---

lib/oli/interop/ingest/processor/activities.ex

All ingested activities were getting a hardcoded default scoring strategy of "average". This caused unexpected and undesired behavior on multi-input questions in migrated/ingested courses. For example, on a two-part question with the default 1 point per part, the score for two correct answers would be 1 out of 1, when instructors expect 2 out of 2. This PR corrects the code to set the "total" scoring strategy on ingested activities, which is the natural default. That is also the default applied elsewhere in the code, for example to newly created activities and on updates setting default scoring strategy (see `maybe_update_scoring_strategy`). 
The main is use for ingestion of migrated courses.  The strategy remains changeable after ingestion through custom scoring interface in the unlikely …

[BUG FIX] [MER-3202] change ingested activity scoring strategy to "total", not "average"

---

lib/oli_web/components/delivery/recommended_actions.ex
test/oli_web/live/delivery/instructor_dashboard/overview/recommended_actions_tab_test.exs

[MER-3324](https://eliterate.atlassian.net/browse/MER-3324)
This PR addresses an issue with the `Remind Students of Deadline` link in the Instructor Insights → Recommended Actions section. 
Previously, clicking this link resulted in a “Page Not Found” error due to a change in the URL structure. The URL was changed from `instructor_dashboard/overview/scored_activities` to `instructor_dashboard/insights/scored_activities`.
https://github.com/Simon-Initiative/oli-torus/assets/16328384/591281c5-f783-4c47-9051-b78cf12ea41f
[MER-3324]: https://eliterate.atlassian.net/browse/MER-3324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3324] Recommended action remind students of deadline link breaks

---

lib/mix/tasks/create_contained_objectives.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/contained_objectives_builder.ex
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
priv/repo/migrations/20240621171337_create_get_activity_references_function.exs
test/mix/tasks/create_contained_objectives_test.exs
test/oli/delivery/sections/contained_objectives_builder_test.exs
test/support/test_helpers.ex

[NG23-227](https://eliterate.atlassian.net/browse/NG23-227)
Fixes the issue where many contained objectives records were not inserted when running the Contained Objectives creation task or remixing a course section.
The cause was a bad assumption of the page's content structure: the logic assumed that objects with the `activity-reference` type were only at the top level of the model, and they could be at any level.
The bugfix consists of a recursive function written in PostgreSQL, that receives a `jsonb` representing a page's content and recursively iterates over the nested structure to find all the activity ids. Another solution could be to implement the same function in Elixir, which would force the query to load all the page contents for a course in memory, and in big courses that …

[BUG FIX] [NG23-227] Fix Contained Objectives Builder

---

lib/oli/delivery/metrics.ex
lib/oli/publishing/delivery_resolver.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/prologue_live.ex
lib/oli_web/live/delivery/student/review_live.ex
test/oli/delivery/metrics/learning_proficiency_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-252) to the ticket.
Take into account that this PR points to `NG23-246-content-on-page-is-not-visible-on-begin-attempt` instead of `prerelease-v0.28.0` because the target branch has changes applied to the lesson and prologue view that was needed for this ticket (to prevent future merge conflicts)

[BUG FIX] [NG23-252] Learning objective proficiency at page does not consider child learning objective

---

lib/oli_web/live/delivery/student_onboarding/wizard.ex
lib/oli_web/views/view_helpers.ex

Ticket: [NG23-208](https://eliterate.atlassian.net/browse/NG23-208)
This PR fixes two issues:
1. A missing branding logo on the wizard page
2. A glitch that displays the default torus logo instead of the branded one.
[NG23-208]: https://eliterate.atlassian.net/browse/NG23-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-208] branding not working properly part 2

---

assets/src/components/video_player/InitialPlayButton.tsx
assets/styles/common/video.scss

This adjusts the colors and borders of the initial play button shown in the middle of the video player to ensure visibility against both white and black video backgrounds, so that students will be sure to see an affordance for playing. 
Old: button is there but nvisible against white background
New:

[ENHANCEMENT] [NG23-234] Style initial video play button to ensure visibility

---

lib/oli/datetime.ex
lib/oli_web/live/delivery/student/home/components/schedule_component.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/home/components/schedule_component_test.exs
test/oli_web/live/delivery/student/index_live_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/utils_test.exs
test/support/test_helpers.ex

[NG23-222](https://eliterate.atlassian.net/browse/NG23-222)
Fixes how the Due Date description is calculated on the student's homepage.
There was an edge case where a resource's end date and the current date were on the same day in the UTC timezone, but in the user's timezone, they were not. With the fix, we now consider the user's timezone for the calculation. 
[NG23-222]: https://eliterate.atlassian.net/browse/NG23-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-222] Fix Due Date in Homepage

---

lib/oli_web/components/delivery/instructor_dashboard.ex
lib/oli_web/views/view_helpers.ex

[NG23-256](https://eliterate.atlassian.net/browse/NG23-256)
Add missing brand logo image when not logged in.
**Before:**
**After:**
[NG23-256]: https://eliterate.atlassian.net/browse/NG23-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-256] No branding when not in a section

---

lib/oli_web/live/delivery/student_onboarding/explorations.ex

[NG23-251](https://eliterate.atlassian.net/browse/NG23-251)
Fix exploration gif width when joining a course as a student.
**Before:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/e9d1ac2f-e9a7-473b-aee1-bd0306346bfe
**After:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/3b374fc9-0490-40e1-aa07-9b6b2e2f9db3
[NG23-251]: https://eliterate.atlassian.net/browse/NG23-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-251] Fix Exploration Image on Course Entry

---

lib/oli_web/live/delivery/open_and_free_index.ex
test/oli_web/live/delivery/open_and_free_index_test.exs

This PR fixes an issue where hitting the enter button after typing text in the course search field reloads the instructor dashboard without applying the search criterion.

[BUG FIX] [MER-3401] Fixes instructor course search bug

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery.html.heex
lib/oli_web/live/delivery/student/discussions_live.ex
lib/oli_web/live_session_plugs/set_sidebar.ex
test/oli_web/live/delivery/student/learn_live_test.exs

https://eliterate.atlassian.net/browse/NG23-206
Fixes an issue where Notes tab still shows even when both notes and discussions are disabled.
- Only show notes tab when either notes are enabled for a single page or course discussions are enabled
- Load notes_enabled and discussions_enabled as live plug
- Add handle_params to discussions to prevent crash if params change

[BUG FIX] [NG23-206] user enables disables notes

---

lib/oli/interop/ingest.ex
lib/oli/publishing.ex
lib/oli/publishing/publications/publication.ex
lib/oli/publishing/unique_ids.ex
lib/oli/resources.ex
lib/oli/resources/revision.ex
lib/oli/utils/db_seeder.ex
lib/oli/utils/seeder/project.ex
priv/repo/migrations/20240624202150_revision_ids_added.exs
test/oli/publishing/unique_ids_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/publish_live_test.exs
test/support/factory.ex

https://eliterate.atlassian.net/browse/NG23-228
This PR fixes an issue where social annotation point markers were not showing up for some pages, specifically identified in the chemistry course.
The root cause of the issue was due to the `ids_added` attribute on the publication not taking into account pages which may not have been processed as part of the publication process when ids were fixed, leading to the possibility that certain pages added in after the fact may not have been processed to ensure these ids exist.
The fix here is to remove the `ids_added` attribute from the publication record and instead add it to the revision record, and run the `ensure_ids` logic on every publish. Once a revision has been processed and has this flag set, it no longer needs to be processed going …

[BUG FIX] [NG23-228] social annotation point blocks not working for some pages

---

lib/oli_web/components/delivery/layouts.ex

Ticket: [NG23-254](https://eliterate.atlassian.net/browse/NG23-254)
This ticket fixes the overlapping between the back button and the content.
https://github.com/Simon-Initiative/oli-torus/assets/47334502/fb231045-e08d-4f87-aeea-77aa12c20728
https://github.com/Simon-Initiative/oli-torus/assets/47334502/fcde0055-582b-4b8b-b2d5-038f7dfc4e76
[NG23-254]: https://eliterate.atlassian.net/browse/NG23-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [NG23-254] Fix back button overlaps content

---

lib/oli_web/controllers/delivery_controller.ex
test/oli_web/controllers/delivery_controller_test.exs

https://eliterate.atlassian.net/browse/NG23-205
Fixes an issue where instructor would be redirected to student view on subsequent launches. Now when an instructor launches, they will be directed to the instructor dashboard view.

[BUG FIX] [NG23-205] ng dumps lti new instructors into student interface after course creation

---

assets/src/data/activities/utils.ts

Fixes an issue where activities with multiple part inputs were not being reinitialized past the first part input.
The issue here was the `defaultPartInputs` being calculated is used to derive the actual part inputs from the `activityState`. However, this initialization was hard coded to only generate a default part input for the first part in an activity, an assumption that was likely baked in before activities with multiple parts (such as Likert) existed.
The fix here generates default part inputs from all parts in the activity state.

[BUG FIX] [NG23-263] likert activity not restoring state beyond first item

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section_cache.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/utils.ex
lib/oli_web/live/sections/edit_view.ex
test/oli/delivery/section_cache_test.exs
test/oli/delivery/sections_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-259) to the ticket
With this fix container labels are correctly shown on the Learn Page. 
https://github.com/Simon-Initiative/oli-torus/assets/74839302/01a813fc-95e9-4b7d-9c7d-55e39baea407
I also checked that all the other pages -Home, Schedule, etc- display container labels correctly.
While working on the ticket I realized that when the instructor changed the container labels, the new values weren't updated on the student delivery pages (I needed to restart the server to see the updated values). This was because some section fields, including the labels, are cached. To fix this the SectionCache module was updated to clear the desired cache keys.
**Suggestion:** 
Instructors can edit labels for "Unit", "Module" and "Section". Since our …

[BUG FIX] [NG23-259] Custom container labels not honored on Learn Page

---

assets/tailwind.theme.js
lib/oli_web/components/header.ex
lib/oli_web/templates/layout/default.html.heex
lib/oli_web/templates/shared/_help.html.heex
test/oli_web/controllers/static_page_controller_test.exs

Ticket [MER-3291](https://eliterate.atlassian.net/browse/MER-3291)
This PR adds new styling corresponding to the epic mentioned in the ticket.
Two colors were defined in `tailwind.theme.js` for future use --`high-24` & `primary-24`.
The following video shows the new styling on the sign-in pages; otherwise, the style remains the same.
https://github.com/Simon-Initiative/oli-torus/assets/47334502/749775e1-5c16-4c1f-9946-76970151cf06
[MER-3291]: https://eliterate.atlassian.net/browse/MER-3291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-3291] Style direct delivery header

---

lib/oli/delivery/settings.ex
lib/oli/delivery/settings/settings_changes.ex
lib/oli_web/components/layouts/instructor_dashboard.html.heex
lib/oli_web/live/sections/assessment_settings/settings_live.ex
lib/oli_web/live/sections/assessment_settings/settings_table.ex
priv/repo/migrations/20240620202825_create_settings_changes.exs
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

[MER-3065](https://eliterate.atlassian.net/browse/MER-3065)
This PR implements a tracking of all changes made in the `Assessment Settings` view, both for the individual changes of each setting and for the existing bulk apply option.
This new functionality will store the changes in a new table called `settings_changes` in the database.
[MER-3065]: https://eliterate.atlassian.net/browse/MER-3065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3065] Track assessment settings audit log

---

lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/schedule.ex
lib/oli_web/live/delivery/student/home/components/schedule_component.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/utils.ex

This PR displays student exceptions in schedule instead of the primary schedule at the following locations:

[ENHANCEMENT] [MER-3078] Where present, show student exceptions in schedule instead of the primary schedule

---

lib/oli_web/live/products/details_view.ex
lib/oli_web/live/projects/overview_live.ex
lib/oli_web/live/sections/edit_view.ex

Editing project details, e.g. title, from the Authoring Project Overview UI was failing in cases where the welcome title was unset, the usual initial default. In this case, seems empty string gets sent in update message as value for welcome title, which is neither nil nor JSONified rich content structure. Code was not checking for this case and was passing it to Poison.decode, which throws an error since empty string is not valid JSON. This change recodes to check for empty string before parsing, treating empty string as equivalent to nil to prevent rendering welcome title in this case.

[BUG FIX] [MER-3422] Fix failure editing overview details when welcome title blank

---

lib/oli_web/live/delivery/student/lesson/annotations.ex
lib/oli_web/live/delivery/student/lesson_live.ex
test/oli_web/live/delivery/student/lesson_live_test.exs

[Link](https://eliterate.atlassian.net/browse/NG23-266) to the ticket
The bug was introduced in [NG23-253](https://github.com/Simon-Initiative/oli-torus/pull/4929), where some values needed for the annotation features were accidentally erased from the socket (the mentioned PR temporarily assigned the `page_context` into the socket).
The fix involved assigning to the socket those needed values, to handle all the user interaction with the annotations panel correctly.
https://github.com/Simon-Initiative/oli-torus/assets/74839302/f792dadc-d341-467f-9649-fc73d147f6b4
While working on the fix another bug was found, where after clearing a note search the notes rendered didn't match the selected tab. The steps to reproduce the bug are:
1. Search for some text while being on "My notes".
2. Switch …

[BUG FIX] [NG23-266] Unable to create a notes from learn page

---

config/config.exs
config/runtime.exs
lib/oli_web/backgrounds.ex
lib/oli_web/controllers/pow/session_html/new.html.heex
oli.example.env
test/oli_web/pow/pow_test.exs

[MER-3292](https://eliterate.atlassian.net/browse/MER-3292)
This PR modifies the way the background color is set for a student's login view.
Changes are made to take the color from an environment variable declared on the server.
An environment variable called `STUDENT_SIGNIN_BACKGROUND_COLOR` whose value is a color value in hex format must be declared.
The colors for the different environments should be: 
Proton (default) -> #FF82E4
Tokamak -> #54E5A4
Stellarator -> #DB6C1E
[MER-3292]: https://eliterate.atlassian.net/browse/MER-3292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3292] Fetch background color from an environment variable

---

lib/oli/authoring/course.ex
lib/oli_web/components/common.ex
lib/oli_web/live/projects/overview_live.ex
test/oli_web/live/projects/overview_live_test.exs

[MER-3422](https://eliterate.atlassian.net/browse/MER-3422)
This PR fixes an issue on the project's overview page. When updating some fields in the edit form, and then changing the Welcome Title, the previous changes were ignored and changed back to their original values.
**Before:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/bbf847eb-8364-4552-8409-1d10e91769df
**After:**
https://github.com/Simon-Initiative/oli-torus/assets/26532202/a30740f3-cff2-413b-9216-6deb482f05b4
[MER-3422]: https://eliterate.atlassian.net/browse/MER-3422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3422] Anomaly when editing overview info

---

lib/oli_web/components/header.ex

Ticket: [MER-3291](https://eliterate.atlassian.net/browse/MER-3291)
This PR swapped the tabs on the navbar. This bug was reported in the ticket during QA.
[MER-3291]: https://eliterate.atlassian.net/browse/MER-3291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3291] Swap tabs in header

---

lib/oli_web/live/sections/enrollments/invalid_section_invite_view.ex
lib/oli_web/plugs/require_section.ex
lib/oli_web/router.ex
test/oli_web/live/sections/enrollments/invalid_section_invite_view_test.exs

Ticket: [MER-3295](https://eliterate.atlassian.net/browse/MER-3295)
This PR modifies the text message shown when an enrollment course link is invalid or expired. It also moves the invalid enrollment link endpoint to avoid an unnecessary account check-in. Additionally, it includes a refactor of the `RequireSection` module to improve readability.
https://github.com/Simon-Initiative/oli-torus/assets/47334502/fbb0a031-c7c3-4dc1-bcf3-88913f65bc94
[MER-3295]: https://eliterate.atlassian.net/browse/MER-3295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3295] Course enrollment error

---

assets/src/apps/authoring/components/AdaptiveRulesList/AdaptiveRulesList.tsx
assets/src/apps/authoring/components/AdaptivityEditor/ConditionItemEditor.tsx
assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx
assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx
assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx
assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx
assets/src/apps/authoring/components/PropertyEditor/custom/MCQCustomErrorFeedbackAuthoring.tsx
assets/src/apps/authoring/components/PropertyEditor/custom/MCQOptionsEditor.tsx
assets/src/apps/authoring/components/RightMenu/PartPropertyEditor.tsx
assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx
assets/src/apps/authoring/store/parts/slice.ts
assets/src/apps/delivery/components/NotificationContext.tsx
assets/src/components/activities/adaptive/AdaptiveAuthoring.tsx
assets/src/components/activities/adaptive/components/authoring/LayoutEditor.tsx

Hey @bsparks Could you please look at this PR.
This PR contains fix for the following things:
1. [Using keyboard shortcut (ctrl-v) to paste after a component has been copied causes issues](https://eliterate.atlassian.net/browse/MER-3420)
2. [Using keyboard shortcut (ctrl-del) to delete after a component has been copied causes issues](https://eliterate.atlassian.net/browse/MER-3423)
Apart from this, I also fixed the original request to delete a selected component when user press `'Delete / Backspace'` keys. In the past, there were issues related to `'Delete / Backspace'` so we used `'Cntrl + Delete / Backspace'` but now I have fixed all the issues and now we can use `'Delete / Backspace'` to delete a component.
I had to handle the `'Delete / Backspace'` key press at all the places in the …

[BUG FIX] [MER-3423] Using keyboard shortcut (ctrl-del) to delete after a component has been copied causes issues

---

config/config.exs
config/runtime.exs
lib/oli/authoring/broadcasting/broadcaster.ex
lib/oli/authoring/broadcasting/messages.ex
lib/oli/authoring/broadcasting/subscriber.ex
lib/oli/authoring/course.ex
lib/oli/authoring/course/project.ex
lib/oli/authoring/project_export_worker.ex
lib/oli_web/components/project/async_exporter.ex
lib/oli_web/controllers/project_controller.ex
lib/oli_web/live/projects/overview_live.ex
lib/oli_web/router.ex
priv/repo/migrations/20240709205804_async_project_export.exs
test/oli/analytics/xapi/pipeline_test.exs
test/oli_web/controllers/project_controller_test.exs

https://eliterate.atlassian.net/browse/MER-3396
This PR fixes an issue with exporting very large courses where the export processing takes longer than a browser connection (and default Phoenix/cowboy) can handle, resulting in a Gateway Timeout error and no way to download the export for a course.
Adjusting the HAProxy setting to a longer time window did not fix the issue on stellarator, so this required a code fix.
Now the export process is handled as a asynchronous background job using the existing AsyncExporter module. It will be important that users understand that in order to get the latest version of their project, they must first "Regenerate" before clicking the download button. This is likely not the best UX, but will work for the short term and unblocks the ability to download …

[ENHANCEMENT] [MER-3396] Async project export to fix gateway timeout

---

lib/oli/delivery.ex
lib/oli/delivery/research_consent.ex
lib/oli/institutions.ex
lib/oli_web/components/delivery/user_account.ex
lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/live/features/features_live.ex
lib/oli_web/router.ex
lib/oli_web/templates/delivery/research_consent.html.eex
priv/repo/migrations/20240711170055_create_research_consent.exs
test/oli/analytics/xapi/pipeline_test.exs

https://eliterate.atlassian.net/browse/MER-3503
Adds support for accessing research consent form from the user menu in delivery.
System admin can configure whether or not to use the consent form for direct delivery at the system level under Feature Flags. LTI users consent form will still be driven by the institution-specific setting.
If enabled, a "Research Consent" link will show in the user menu, which takes the user to the consent form where the previous set value for the user selection is shown. If not set, the value will default to "I Agree".
I tested the different scenarios including direct delivery student, LTI launch from Canvas as both instructor and student.

[ENHANCEMENT] [MER-3503] Add support for accessing research consent form

---

lib/oli/activities/reports/providers/OliLikert.ex
lib/oli/delivery/attempts/core.ex

This PR addresses two issues:
- Resetting and retaking a survey likert causes the report to throw an internal server error.
- If you miss an answer in the Likert, the report throws an internal server error.

[BUG FIX] [MER-3010] fixes sparse likert and multiple likert attempts

---

lib/oli_web/live/products/products_view.ex

This PR fixes an issue where, when the Include archived Products checkbox is checked, the archived products show up, but they disappear after going to another page, searching for a product, and sorting the products.

[BUG FIX] [MER-3116] fixes archived product disappearing bug

---

lib/oli_web/templates/delivery/enroll.html.heex
test/oli_web/controllers/delivery_controller_test.exs

Add `Sign up` button in enrollment page.
User flow preview:
https://github.com/Simon-Initiative/oli-torus/assets/5324858/695d0478-8ab8-456e-ad31-7797b419beec
See: https://eliterate.atlassian.net/browse/MER-3294

[ENHANCEMENT] [MER-3294] User can create an account through a course enrollment link

---

config/config.exs
config/runtime.exs
lib/oli/vendor_properties.ex
lib/oli_web/templates/layout/authoring.html.leex
lib/oli_web/templates/static_page/index.html.eex
test/oli_web/controllers/static_page_controller_test.exs

[MER-3305](https://eliterate.atlassian.net/browse/MER-3305)
This PR introduce information about course enrollment in the student's login view following figma designs.
A link to the FAQ document is displayed and also a button to contact support if it's necessary.
https://github.com/user-attachments/assets/2da902c2-decf-45d1-8a87-693fefd5621b
[MER-3305]: https://eliterate.atlassian.net/browse/MER-3305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3305] Direct delivery student sign in course enrollment info

---

lib/oli_web/live/delivery/student/prologue_live.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

https://eliterate.atlassian.net/browse/MER-3516
**NOTE** Targeted to prerelease-v0.28.0 branch since that is the base (in order to properly see diffs for PR review), but we may want to target to master or a different hotfix branch.
Fixes an issue where re-accessing a manually graded page summary throws 500 when an attempt in in the "submitted" state and not "evaluated" yet.

[BUG FIX] [MER-3516] 500 error when-re-accessing a manually graded assessment

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/browse.ex
priv/repo/migrations/20240719181530_enrollments_context_roles_unique_index.exs

https://eliterate.atlassian.net/browse/MER-3390
https://github.com/user-attachments/assets/0522b298-aa39-43f4-989b-4c76d8d8673f
This PR fixes 2 separate issue regarding enrollment counts outlined in the ticket.
1. First, the browse sections query was modified to only count enrollments with status of `enrolled` (excluding `suspended`) which fixes an issue where the count was including "unenrolled" students
2. Second, when adding a duplicate enrollment, most of the operations were taking into account the possibility that a duplicate, or already enrolled, student may have been entered again, and upserting user and enrollment records in that case, However, there was a gap here were duplicate `enrollments_context_roles` records were being created, which was affecting the count being returned …

[BUG FIX] [MER-3390] Only include enrolled students in section enrollment count

---

lib/oli/accounts.ex
lib/oli/accounts/schemas/author.ex
lib/oli/email.ex
lib/oli_web/controllers/cognito_controller.ex
lib/oli_web/templates/email/infiniscope_invitation.html.heex
lib/oli_web/templates/email/infiniscope_invitation.text.eex
test/oli/accounts_test.exs
test/oli_web/controllers/cognito_controller_test.exs

[MER-3307](https://eliterate.atlassian.net/browse/MER-3307)
This PR enhances the current functionality for the use case when a user enters Torus from Infiniscope via SSO for the first time. In addition to creating an instructor account, it now also creates and links an authoring account to the instructor. Furthermore, it sends an email to the new author to set up the password.
https://github.com/user-attachments/assets/1d829b3e-c39a-471f-befb-3023d80e5456
[MER-3307]: https://eliterate.atlassian.net/browse/MER-3307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3307] infiniscope: First time user enters Torus through SSO

---

lib/oli_web/live/delivery/open_and_free_index.ex
test/oli_web/live/delivery/open_and_free_index_test.exs

When a user is only enrolled in open and free sections as a student, they are taken to the student-enrolled courses page, and the sidebar is hidden.
The sign-in flow remains unchanged for all other users.
See: https://eliterate.atlassian.net/browse/MER-3300
https://github.com/user-attachments/assets/633811dc-4fa2-4c43-84b2-2212dfedb8f4

[ENHANCEMENT] [MER-3300] Open and Free sections: If student, hide sidebar and display student workspace

---

lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/live_session_plugs/set_request_path.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

Ticket: [MER-3506](https://eliterate.atlassian.net/browse/MER-3506)
This PR adds a fix for an issue that occurred after completing a lesson where the back arrow didn't work. The problem was that it failed to consider cases when the `request_path` was `""`. After completing an adaptive page, React called an endpoint in our backend that redirects twice to different endpoints, and we never filled out the `request_path`. The back link wasn't prepared for this scenario.
[MER-3506]: https://eliterate.atlassian.net/browse/MER-3506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3506] After completing a lesson the back arrow does not work

---

assets/src/apps/authoring/Authoring.tsx
assets/src/apps/bank/ActivityBank.tsx
assets/src/apps/bibliography/Bibliography.tsx
assets/src/apps/page-editor/PageEditor.tsx
assets/src/components/activities/AuthoringElementProvider.tsx
assets/src/components/editing/elements/formula/FormulaEditor.tsx
lib/oli_web/templates/layout/chromeless.html.heex
lib/oli_web/templates/layout/workspace.html.eex
lib/oli_web/templates/shared/_help.html.heex
test/oli/analytics/xapi/pipeline_test.exs

https://eliterate.atlassian.net/browse/MER-3156
The issue this PR addresses is an intermittent one where trying to edit LaTeX code in the modal sometimes does not work properly. The ticket outlines a solution to replace the Monaco editor with a simple text editor, however I believe the root cause of this issue is related to multiple instances of the ModalDisplay component being rendered on a given page.
The ModalDisplay component is a singleton that is intended to only exist as a single instance on a given page. By rendering it one or more times on a page results in a indeterminate stacking effect where there are multiple versions of the same modal being rendered, which while related to a limitation of the monaco editor, I believe the multiple modals were actually the root case of this …

[BUG FIX] [MER-3156] Fix an issue with LaTeX wonkiness and modals

---

lib/oli_web/controllers/pow/session_html/new.html.heex

[MER-3296](https://eliterate.atlassian.net/browse/MER-3296)
This PR fixes some bugs found during the QA process. 
- The backgrounds of the login views are fixed. There were errors in resizing the backgrounds so they were showing cut off when changing the resolution. 
- Colours used in some elements which were erroneous are corrected.
https://github.com/user-attachments/assets/b932f37a-8f45-4d28-afe5-05e982d087e6
[MER-3296]: https://eliterate.atlassian.net/browse/MER-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3296] Course author signin fixes

---

lib/oli/delivery/hierarchy.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section_resource.ex
lib/oli_web/live/delivery/remix/actions.ex
lib/oli_web/live/delivery/remix/entry.ex
lib/oli_web/live/delivery/remix/hide_resource_modal.ex
lib/oli_web/live/delivery/remix_section.ex
priv/repo/migrations/20240716154202_add_hidden_field_to_section_resources.exs
test/oli_web/live/delivery/student/index_live_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/remix_section_test.exs

[MER-3320](https://eliterate.atlassian.net/browse/MER-3320)
This PR allows authors and instructors to show and hide materials from the hierarchy during the course remix.
Materials that are hidden should not be accessible by students within a course. 
_*If you think there is somewhere else where access to hidden materials should be restricted, please let me know._
https://github.com/user-attachments/assets/461928bb-441a-4c7d-a38f-c73b2fd0bd97
[MER-3320]: https://eliterate.atlassian.net/browse/MER-3320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3320] Hide content during course remix

---

lib/oli_web/templates/brand/show.html.eex

https://eliterate.atlassian.net/browse/MER-3119
Fixes an issue where branding favicons were not being rendered quite right within the table.
Before:
After:

[BUG FIX] [MER-3119] Favicons table row in Brands looks wrong

---

lib/oli_web/live/delivery/student/utils.ex
test/oli/analytics/xapi/pipeline_test.exs
test/oli_web/live/delivery/student/utils_test.exs

https://eliterate.atlassian.net/browse/MER-3553
This PR addresses an issue where `FormatDateTime.maybe_localized_datetime` might return `{:not_localized, ...}` which then gets piped into `DateTime.to_date()` and crashes the page.

[BUG FIX] [MER-3553] Lesson end date formatting breaks ability to load Home screen

---

lib/oli_web/controllers/delivery_controller.ex
mix.exs
test/oli/analytics/xapi/pipeline_test.exs

https://eliterate.atlassian.net/browse/MER-3557
Fixes an issue where the redirection logic during LTI launch didn't match the authorization logic.
If a student had the Platform Instructor role, they were redirected to the instructor dashboard however the authorization logic redirected to an unauthorized message. Ultimately, the authorization logic was correct here, so the platform instructor role was remove from the list of "allowed to manage section" roles so that a student isn't incorrectly redirected.

[BUG FIX] [MER-3557] Not authorized message displayed to student on LTI launch

---

lib/oli/delivery/sections/section.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/sections/overview_view.ex
priv/repo/migrations/20240731170918_add_agenda_flag_to_section.exs
test/oli_web/live/delivery/instructor_dashboard/manage/manage_tab_test.exs
test/oli_web/live/delivery/student/index_live_test.exs

[MER-3550](https://eliterate.atlassian.net/browse/MER-3550)
This PR adds an `agenda` field to the sections table in order to enable or disable the display of a section agenda to students. 
On the other hand, it adds logic to render the agenda in the student home screen of a course section, depending on the value of this new field.
_Feel free to suggest changes or improvements to the code or functionality._
https://github.com/user-attachments/assets/b55a161a-5afc-485e-93bf-38e2e7d7dc6f
[MER-3550]: https://eliterate.atlassian.net/browse/MER-3550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3550] Hide agenda home screen

---

lib/oli/analytics/xapi.ex

https://eliterate.atlassian.net/browse/MER-3556
This PR guards against an XAPI query possibly returning multiple resource attempts when only one is expected by adding a desc sort on the attempt number and limiting the results to 1 record.

[BUG FIX] [MER-3556] XAPI event emitting error

---

lib/oli_web/live/sections/enrollments/invalid_section_invite_view.ex
lib/oli_web/templates/delivery/enroll.html.heex
test/oli_web/controllers/delivery_controller_test.exs
test/oli_web/live/sections/enrollments/invalid_section_invite_view_test.exs

Fixed the Sign-In link when following an enrollment link to ensure students are directed to the Student sign-in page instead of the Instructor sign-in page.
https://github.com/user-attachments/assets/95809ec0-12cd-47d5-8148-32f513979ccf
See: https://eliterate.atlassian.net/browse/MER-3294?focusedCommentId=23742

[BUG FIX] [MER-3294] Enrollment link redirects to new Student Sign-In page

---

.github/workflows/build.yml
lib/oli_web/components/layouts/workspace.html.heex
lib/oli_web/live/workspace/student.ex
lib/oli_web/live_session_plugs/set_sidebar.ex
test/oli_web/live/workspace/instructor_test.exs
test/oli_web/live/workspace/student_test.exs

Do not show sidebar for users that are only enrolled as students
---- 
https://github.com/user-attachments/assets/8a018ef2-d9e1-40bb-b66f-cecf24bc7c65
_In the video above we first log-in with a user that is a student and instructor and can see the sidebar. Then we log in with a user that is only enrolled as a student and the sidebar is not displayed._
---
See: https://eliterate.atlassian.net/browse/MER-3300

[ENHANCEMENT] [MER-3300] Don't show sidebar after login if user is only enrolled as student

---

lib/oli_web/controllers/pow/session_html/new.html.heex
lib/oli_web/controllers/static_page_controller.ex

[MER-3297](https://eliterate.atlassian.net/browse/MER-3297)
This PR fixes some bugs found during the QA process.
- Colors of some texts have been fixed.
- User config is used to show login providers for students correctly (Github and Google).
In the different environments where this code is deployed, the following environment variables must be set correctly:
`USER_GITHUB_CLIENT_ID`
`USER_GITHUB_CLIENT_SECRET`
_**I think that in Tokamak they are not set correctly so the login link to Github for students and instructors is not being displayed.**_
[MER-3305]: https://eliterate.atlassian.net/browse/MER-3305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-3297]: https://eliterate.atlassian.net/browse/MER-3297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

[BUG FIX] [MER-3297] Instructor sign in fixes

---

assets/src/apps/scheduler/SchedulerSaveBar.tsx

Ticket: [MER-3131](https://eliterate.atlassian.net/browse/MER-3131)
This PR fixes a bug that occurred when trying to change the date in the Scheduling page. The issue was caused by our date picker being triggered with every change to the date input, which attempted to parse the date prematurely. To avoid this behavior, we changed the onChange event to the onBlur event. This allows the user to complete entering the date before it is parsed.
[MER-3131]: https://eliterate.atlassian.net/browse/MER-3131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3131] Change onChange to onBlur to avoid unnecessary parsing that breaks the date-time picker

---

.github/workflows/build.yml
assets/src/components/activities/DeliveryElement.ts
assets/src/components/activities/DeliveryElementProvider.tsx
assets/src/components/activities/directed-discussion/discussion/MockDiscussionDeliveryProvider.tsx
assets/src/data/content/writers/context.ts
assets/src/data/content/writers/html.tsx
assets/test/check_all_that_apply/cata_delivery_test.tsx
assets/test/multiple_choice/mc_delivery_test.tsx
assets/test/ordering/ordering_delivery_test.tsx
assets/test/short_answer/short_answer_delivery_test.tsx
assets/test/writer/writer_test.ts
lib/oli/rendering/activity/html.ex
lib/oli/rendering/content/html.ex
lib/oli/rendering/context.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli/rendering/content/html_test.exs

[MER-3565](https://eliterate.atlassian.net/browse/MER-3565)
Fixes Internal Server Error when launching assessments from page links. This PR considers links handling for both activity-rendered and page-rendered links. It also fixes the back button when visiting an assessment via a link.
https://github.com/user-attachments/assets/7fab519c-cdac-4475-b3ac-ac33cfd5bf1d
[MER-3565]: https://eliterate.atlassian.net/browse/MER-3565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3565] 500 error when launching assessments from a page link

---

lib/oli/grading.ex

https://eliterate.atlassian.net/browse/MER-3567
This PR fixes an issue with the query that powers the quiz scores view. The issue appears to be that `resource_accesses` records that are JOINed in were being pulled from all sections, as opposed to the single particular section being queried.
The results in the quiz scores view now match the values in the gradebook and scores exports, which was how the issue (discrepancy) was originally identified.

[BUG FIX] [MER-3567] Quiz Scores are incorrect

---

lib/oli/resources/explanation_strategy.ex
lib/oli_web/live/curriculum/container/container_live_helpers.ex
lib/oli_web/live/curriculum/entries/options_modal.ex

This PR fixes an issue where, when an author tries to set the Explanation Strategy for a page in authoring, the inputs disappear when a value is input.

[BUG FIX] [MER-3571] fixes explanation strategy ui fields bug

---

lib/oli_web/controllers/invite_controller.ex
test/oli_web/controllers/invite_controller_test.exs

This PR is the first part of ensuring that when a user is sent an email invitation (whereas that user is existing or new), the link directs to the correct page (if new, to the sign up page, if existing to the section enroll).
Before this fix, the email invites links directed to the create author account page.
https://github.com/user-attachments/assets/def7d6dc-ceef-4a29-9b1b-e3468841bc57
See: https://eliterate.atlassian.net/browse/MER-3543

[BUG FIX] [MER-3543] Invite students via email link sends user to sign-up/enroll page (part 1)

---

devmode.sh
docker-compose.yml

Torus source includes a utility script, devmode.sh, for use by developers to launch a containerized version locally. This updates the script for more recent docker versions, in which it was giving an error for using `docker-compose` now replaced by `docker compose`.

[CHORE] [MER-3605] update devmode script for recent docker versions

---

lib/oli_web/live/sections/overview_view.ex

See: https://eliterate.atlassian.net/browse/MER-3627

[BUG FIX] [MER-3627]  Change "Preview Course as Instructor" to "Preview Course as Student" typo

---

lib/oli/delivery/page/objectives_rollup.ex
test/oli/delivery/page/objectives_rollup_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-3624) to the ticket
As the ticket explained, the fix filters out any nil values returned by the objectives resolver call.

[BUG FIX] [MER-3624] Page objectives :resource_id not found in: nil

---

lib/oli/analytics/by_activity.ex
lib/oli/analytics/by_page.ex
lib/oli/delivery/page/objectives_rollup.ex
lib/oli/delivery/sections.ex
lib/oli/publishing/delivery_resolver.ex
lib/oli/utils/db_seeder.ex
test/oli/delivery/analytics/analytics_test.exs
test/oli/delivery/page/objectives_rollup_test.exs
test/oli_web/live/delivery/instructor_dashboard/insights/content_tab_test.exs
test/oli_web/live/remix_section_test.exs

https://eliterate.atlassian.net/browse/MER-3630
Fixes an issue where delivery resolver was not properly including all required resources remixed into a section, such as objectives and nested activities. This was resulting in resolver failures in delivery, cause 500 errors for students.
The fix here is to revert commit https://github.com/Simon-Initiative/oli-torus/commit/32498051478aaab4ccd54d27525b2a10899cc336
Once deployed, an admin will have to take the additional step of "remixing" the affected course section(s). It is sufficient to drag/move an item around, then move it back and click "Save" which will trigger the required rebuild_section_resources step and resolve the issue.
Finally, this PR reverts the changes made in https://eliterate.atlassian.net/browse/MER-3624 since they are no …

[BUG FIX] [MER-3630] ensure all required non hierarchical resource records are created when remixing

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

Fixes the following error happening in proton:
`** (FunctionClauseError) no function clause matching in OliWeb.Delivery.Student.LearnLive.scroll_to_target_resource/4`
If an invalid `selected_view` parameter is received, use the default view mode.
Related:
- https://github.com/Simon-Initiative/oli-torus/pull/5018 (Fix for master)
- https://eliterate.atlassian.net/browse/MER-3591
- https://appsignal.com/open-learning-initiative/sites/618539ab2cf81d7e3cd051ca/exceptions/incidents/62

[BUG FIX] [MER-3591] (v0.28.3) Error no function clause matching in `OliWeb.Delivery.Student.LearnLive.scroll_to_target_resource/4`

---

lib/oli_web/templates/open_and_free/form.html.eex
lib/oli_web/templates/open_and_free/show.html.eex
test/oli_web/controllers/open_and_free_controller_test.exs

https://eliterate.atlassian.net/browse/MER-3631
Fixes a rendering issue with cognito workflow in the open and free routes, resulting in 500 error. I added some basic test coverage here around these routes as well.
I suspect some of the `resources` routes that exist for `/sections/independent` such as `:show` and `:edit` are now obsolete with the new system workflows, as section viewing/editing now takes place from the instructor dashboard live view. I left these in for now but we likely want to remove them in the future.

[BUG FIX] [MER-3631] Fix rendering issues with cognito/open and free routes

---

lib/oli_web/templates/open_and_free/form.html.eex
lib/oli_web/templates/open_and_free/show.html.eex
test/oli_web/controllers/open_and_free_controller_test.exs

**Re-targeted to v0.28.4**
https://eliterate.atlassian.net/browse/MER-3631
Fixes a rendering issue with cognito workflow in the open and free routes, resulting in 500 error. I added some basic test coverage here around these routes as well.
I suspect some of the resources routes that exist for /sections/independent such as :show and :edit are now obsolete with the new system workflows, as section viewing/editing now takes place from the instructor dashboard live view. I left these in for now but we likely want to remove them in the future.

[BUG FIX] [MER-3631] Fix rendering issues with cognito/open and free routes (Re-targeted to v0.28.4)

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

Fixes the following error happening in proton:
`** (FunctionClauseError) no function clause matching in OliWeb.Delivery.Student.LearnLive.scroll_to_target_resource/4`
If an invalid `selected_view` parameter is received, use the default view mode.
Related:
- https://eliterate.atlassian.net/browse/MER-3591
- https://appsignal.com/open-learning-initiative/sites/618539ab2cf81d7e3cd051ca/exceptions/incidents/62

[BUG FIX] [MER-3591] Error `no function clause matching in OliWeb.Delivery.Student.LearnLive.scroll_to_target_resource/4`

---

lib/oli_web/live/sections/overview_view.ex

This PR changes the attempt to hard delete a course section to the soft delete mechanism.

[BUG FIX] [MER-3666] Mark as deleted instead of trying to hard delete course section

---

lib/oli/authoring/clone.ex
lib/oli/delivery/sections/blueprint.ex
test/oli/clone_test.exs

[MER-3635](https://eliterate.atlassian.net/browse/MER-3635)
This PR fixes the error happening when an user creates a section from a product which is contained in a cloned project.
We found two issues that have been fixed: 
- publication_id when a product is cloned. 
- project_id is fixed when section_resources for the new product are created.
@eliknebel we also noticed that when new materials are added, published, and then those updates are applied in the cloned product, the updates do not appear. This is a potential issue that we might need to follow up on.
[MER-3635]: https://eliterate.atlassian.net/browse/MER-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3635] Fix 500 error copied project source materials

---

lib/oli_web/templates/static_page/index.html.eex

[MER-3292](https://eliterate.atlassian.net/browse/MER-3292)
This PR fixes the color of the `Forgot password` and `Sign In` buttons in the `Student` login view. 
This is consistent with the other login views for **Instructors** and **Authors.** 
[MER-3292]: https://eliterate.atlassian.net/browse/MER-3292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3292] Fix color of buttons in student sign in

---

lib/oli_web/live/datashop/analytics_live.ex
test/oli_web/live/datashop/analytics_live_test.exs

This PR adjusts how the `selected_sections` is updated and passed down to the sortable table model for the DataShop section selection view.  Given that the table model was being recreated, it triggered a sort on first selection, which was leading users to select incorrect (or "unintended") subsequent sections.   This fix is to simply update the `data` attribute directly while preserving the rest of the state of the table model.   I tested this interactively and it fixes the problem.

[BUG FIX] [MER-3632] Fix sorting glitch in Datashop section selection view

---

lib/oli/authoring/clone.ex
lib/oli/delivery/sections/blueprint.ex
lib/oli/utils/seeder/section.ex
test/oli/clone_test.exs

https://eliterate.atlassian.net/browse/MER-3631
This PR fixes an issue with section creation from product by reverting some of the changes made in https://eliterate.atlassian.net/browse/MER-3635 (#5034)
The issue was blueprint duplication logic was attempting to duplicate/create create section_project_publication records, but the project id being used was not quite correct which was violating the uniqueness constraint of spp section_id and project_id.
This was resulting in an inability to create a new section from a Product with multiple other sibling products. This was apparent when testing the cogito/independent open and free section creation bug fixes by ETX.
The fix here is to identify the case where the spp record project_id equals the original base project id, and update the spp …

[BUG FIX] [MER-3631] Trying to create a section from a product fails in certain cases

---

lib/oli/delivery/page/page_context.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live_session_plugs/init_page.ex

[Link](https://eliterate.atlassian.net/browse/MER-3670) to the ticket
When a liveview is mounted the `mount` callback is called twice; one time when the HTTP request is received and then when the websocket connection is established (see [docs](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-life-cycle)).
So, to avoid triggering the access track twice, I adapted the logic to do it when the HTTP request is first received.
https://github.com/user-attachments/assets/091cae4c-3b2c-4419-a2ca-3fabdcd0d839
https://github.com/user-attachments/assets/e0baa8ca-8478-4b64-834f-c1ceb745658f
While working on the ticket I found that we were having a similar issue with the XAPI Events being sent twice. To fix this I wrapped the execution of that function in the `connected?(socket)` …

[BUG FIX] [MER-3670] Every page is loaded twice

---

lib/oli_web/live_session_plugs/redirect_adaptive.ex
lib/oli_web/live_session_plugs/redirect_to_lesson.ex
test/oli_web/live_session_plugs/redirect_adaptive_test.exs
test/oli_web/live_session_plugs/redirect_to_lesson_test.exs

[Link to the comment](https://eliterate.atlassian.net/browse/MER-3671?focusedCommentId=24029) in the ticket
https://github.com/user-attachments/assets/8d2d38f3-046b-4a63-bb39-f6852fa19e22
https://github.com/user-attachments/assets/3e1bb083-26fa-441b-b628-bc9b72ca1fd3
The issue was identified after editing and publishing a page. So, when that event occurs, all active attempts of the edited page change their state from `:in_progress` to `revised`.
Since the `RedirectAdaptiveChromeless` livesession plug was not considering `:revised` states to perform the redirect, the user ended up in the `/lesson` route instead of the `/adaptive_lesson` one. Both layout templates for those routes are very similar, but the first one includes a modal, and that hidden modal was the one preventing the click …

[BUG FIX] [MER-3671] Adaptive page styles broken after lesson publishing - part 2

---

lib/oli_web/live/delivery/student/learn_live.ex

https://eliterate.atlassian.net/browse/MER-3669
Fixes an issue where date groupings were not being localized causing inconsistent due dates.
When grouping pages and assignments by due dates in the module index, the grouping was being determined by a non-localized datetime -> date conversion, losing the timezone information in the process. This resulted in some dates rendering off by a day, effectively rendering the UTC date, when actually it should have matched the other dates being displayed, rendered in the localized timezone.
The fix here is to localize the datetime before converting to naive date for grouping such that date groupings accurately match the actual dates being rendered on the page.

[BUG FIX] [MER-3669] date groups do not match the dates rendered on the page

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/live/workspaces/course_author/objectives/actions.ex
lib/oli_web/live/workspaces/course_author/objectives/attachments.ex
lib/oli_web/live/workspaces/course_author/objectives/delete_modal.ex
lib/oli_web/live/workspaces/course_author/objectives/form_modal.ex
lib/oli_web/live/workspaces/course_author/objectives/listing.ex
lib/oli_web/live/workspaces/course_author/objectives/select_existing_sub_modal.ex
lib/oli_web/live/workspaces/course_author/objectives/selections.ex
lib/oli_web/live/workspaces/course_author/objectives/table_model.ex
lib/oli_web/live/workspaces/course_author/objectives_live.ex
lib/oli_web/live_session_plugs/authorize_project.ex
test/oli_web/live/workspace/course_author/objectives_live_test.exs
test/oli_web/live/workspace/course_author_test.exs

[MER-3593](https://eliterate.atlassian.net/browse/MER-3593)
This PR migrates the `Objectives` liveview to be accessible from the new menu for the course author.
Also, it fixes an overflow bug where the `Exit Project` button was hidden in the sidebar if you expand the course author menu items. 
https://github.com/user-attachments/assets/9b0576a4-b7e1-435a-989e-75933f044c15
[MER-3303]: https://eliterate.atlassian.net/browse/MER-3303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-3593]: https://eliterate.atlassian.net/browse/MER-3593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3593] Migrate objectives liveview

---

assets/src/apps/Components.tsx
lib/oli_web/live/workspaces/course_author/activity_bank_live.ex
test/oli_web/live/workspace/course_author_test.exs

Do not merge until https://github.com/Simon-Initiative/oli-torus/pull/5025 is merged
[MER-3594](https://eliterate.atlassian.net/browse/MER-3594)
This PR migrates the `Activity Bank` liveview to be accessible from the new menu for the course author workspace. 
The React component that was previously rendered from the `ActivityBank` controller is kept, but in this case it is called from a new liveview.
https://github.com/user-attachments/assets/11ce66df-6580-4c46-9b4b-08c8cd92652e
[MER-3594]: https://eliterate.atlassian.net/browse/MER-3594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3594] Migrate activity bank liveview

---

lib/oli_web/components/layouts/workspace.html.heex
lib/oli_web/live/workspaces/utils.ex
test/oli_web/live/workspace/instructor/dashboard_live_test.exs

Ticket: [MER-3299](https://eliterate.atlassian.net/browse/MER-3299)
This PR handled a rework based on [feedback](https://eliterate.atlassian.net/browse/MER-3299?focusedCommentId=24041) from QA:
1. Both the title of a course section and the title of a project now follow the Figma-designed color: #757682. 
2. Two missing sub-items were added: "Quiz Scores and Recommended Actions". 
Also, a commit: e3ab1f89ac4a8f7910a2516544444c364b632c7a was added to remove default values for the `course_author` hierarchy tree.
[MER-3299]: https://eliterate.atlassian.net/browse/MER-3299?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3299] Instructor dashboard course view Rework 1

---

lib/oli/authoring/clone.ex
lib/oli/delivery/sections/blueprint.ex
test/oli/clone_test.exs

https://eliterate.atlassian.net/browse/MER-3681
Fixes two issues:
1. When cloning a blueprint (creating a section from a product or cloning a project with products) all `section_resource` records were incorrectly being assigned the base project id
2. `section_project_publication` records were not properly updating the publication id when cloning products, resulting in an odd state where these records pointed to a publication that belonged to the old project and not the new one. This manifested as showing a persistent update available, but would crash when attempting to update
This is a high risk change that affects section creation from products and project duplication

[BUG FIX] [MER-3681] 500 error accessing course sections with customized content

---

lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/utils.ex

This PR handles case where lesson end date might be nil when the start by date is set to some point in the future. The results was a 500 crash on the main student index page.

[BUG FIX] [MER-3686] Student index_live crashes when lesson end date is not set (nil)

---

lib/oli/delivery/sections.ex
lib/oli_web/live/delivery/student/index_live.ex
test/oli/delivery/sections_test.exs
test/oli_web/live/delivery/student/index_live_test.exs

`Sections.get_ordered_containers_per_page/2` ran an expensive query in order to fetch a list of "page to ordered containers" for all (or a subset) of page ids in a course hierarchy.  This function was being used inside of the code that calculates the full ordered schedule, which means it gets called in both the "Schedule" view and the "Home" view (when the Agenda is enabled).  It is also called directly from the `IndexLive` module of the "Home" view.   So, that means for the "Home" view with "Agenda" enabled we call this expensive query *twice*.     There are numerous examples within AppSignal of the Home screen taking 1-2 *seconds* to load, where these two queries comprise around 90% of the total time. 
Worse, everything that is needed to calculate the list of "page to ordered …

[PERFORMANCE] [MER-3691] Improve schedule assembly speed by eliminating expensive ancestral query

---

lib/oli_web/components/hierarchy_selector.ex

https://eliterate.atlassian.net/browse/MER-3170
The cause of the issue here was "validation-options" event being fired in the HierarchyPicker LiveComponent. While it's not exactly clear to me why this was happening, handling this event with a NoOp seems to resolve the issue and restore correct function of the form.
The only downside to this approach is that HierarchyPicker now seems to have some implementation details from it's parent components leaking into it, but this should not cause any harm.
Longer term we should try to investigate why this is occurring and consider refactoring this view and component so that the HierarchyPicker can remain implementation agnostic to the parent components that are using it.

[BUG FIX] [MER-3170] cannot change certain assessment options

---

lib/oli/delivery/attempts/manual_grading.ex
lib/oli_web/live/sections/overview_view.ex

AppSignal shows many instances of slow loading times for the "Manage Section" view of the Instructor Dashboard.  The culprit is the query that counts the number of manually scored activity attempts that are awaiting the instructors' attention to manually score.  This PR optimizes this query by converting it to an "exists" style query, which necessitated moving away from including the count in the badge on the Manage Section view.  For now, a simple "*" is present in the badge.

[PERFORMANCE] [MER-3692] Improve "Manage Section" view loading

---

lib/oli_web/controllers/cognito_controller.ex

[MER-3307](https://eliterate.atlassian.net/browse/MER-3307)
Add missing URL prefix on Infiniscope invitation email.
Introduced in https://github.com/Simon-Initiative/oli-torus/pull/4975.
[MER-3307]: https://eliterate.atlassian.net/browse/MER-3307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3307] Add missing url prefix on Infiniscope invitation email

---

assets/src/components/activities/multi_input/sections/AnswerKeyTab.tsx
assets/src/components/activities/short_answer/actions.ts

This adds the UI component for setting manual vs automatic grading to the authoring interface for multi-input text or numeric parts, just as is already done for single part short answer questions. Manually graded multi-input questions are used in migrated French course to evaluate translation questions with multiple free text inputs in a tabular presentation. The instructor manual grading interface already allows for multiple parts so the only issue was exposing the setting on the authoring interface.

[ENHANCEMENT] [MER-3705] allow manual grading on multi-input text/numeric parts

---

lib/oli/delivery/attempts/page_lifecycle.ex
lib/oli/delivery/attempts/page_lifecycle/graded.ex
lib/oli/delivery/attempts/page_lifecycle/ungraded.ex
lib/oli/delivery/page/activity_context.ex
lib/oli/delivery/page/page_context.ex
lib/oli/utils.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/utils.ex
lib/oli_web/live_session_plugs/set_brand.ex
lib/oli_web/live_session_plugs/set_notification_badges.ex
lib/oli_web/live_session_plugs/set_paywall_summary.ex
lib/oli_web/live_session_plugs/set_user.ex

This PR adds Appsignal instrumentation so that some key event timelines are annotated with pointers back to the code.  This will make troubleshooting and future optimization work much easier.  
Docs for this: https://docs.appsignal.com/elixir/instrumentation/instrumentation.html
This current impl will more fully annotate the timeline as compared to the following screenshot, but at least you can get the idea of what these changes will do:

[PERFORMANCE] [MER-3710] Add AppSignal instrumentation for event timeline details

---

lib/oli_web/live/workspaces/course_author/qa/state.ex
lib/oli_web/live/workspaces/course_author/qa/utils.ex
lib/oli_web/live/workspaces/course_author/qa/warning_details.ex
lib/oli_web/live/workspaces/course_author/qa/warning_filter.ex
lib/oli_web/live/workspaces/course_author/qa/warning_summary.ex
lib/oli_web/live/workspaces/course_author/review_live.ex
test/oli_web/live/workspace/course_author/qa_logic_test.exs
test/oli_web/live/workspace/course_author_test.exs

[MER-3600](https://eliterate.atlassian.net/browse/MER-3600)
This PR migrates the `Review` liveview to be accessible from the new menu for the course author workspace.
In addition to the liveview, the necessary components used by the main liveview are migrated, as well as the existing logic tests.
https://github.com/user-attachments/assets/6d5935e7-3901-4860-9216-b8c84670b800
[MER-3600]: https://eliterate.atlassian.net/browse/MER-3600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3600] Migrate Review liveview

---

lib/oli/resources/activity_browse.ex
lib/oli_web/live/workspaces/course_author/activities/activities_table_model.ex
lib/oli_web/live/workspaces/course_author/activities/activity_review_live.ex
lib/oli_web/live/workspaces/course_author/activities_live.ex
lib/oli_web/router.ex
test/oli_web/live/workspace/course_author_test.exs

[MER-3599](https://eliterate.atlassian.net/browse/MER-3599)
This PR migrates the `All Activities` liveview to be accessible from the new menu for the course author workspace.
In addition, the browse activities query is modified to be able to filter the table by the `petite_label` field (e.g. MCQ, Input, CATA, etc). 
So far, this query was filtering by the title of the revision, but it was not in accordance with the labels shown in the `type` column of the table. 
https://github.com/user-attachments/assets/9e2b32f0-99d6-4709-8e14-a7efa3556743
[MER-3599]: https://eliterate.atlassian.net/browse/MER-3599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3599] Migrate All Activities liveview

---

lib/oli_web/common/links.ex
lib/oli_web/live/curriculum/entries/entry.ex
lib/oli_web/live/workspaces/course_author/curriculum_live.ex
lib/oli_web/live/workspaces/course_author/curriculum_live.html.heex
lib/oli_web/router.ex
test/oli_web/live/workspace/course_author/curriculum_live_test.exs

Migrate authoring Curriculum LiveView to new workspace layout.
See: https://eliterate.atlassian.net/browse/MER-3597
https://github.com/user-attachments/assets/0864d97c-9ff7-4bfe-a1f2-82f05894a81e

[FEATURE] [MER-3597] Migrate Curriculum to new author workspace

---

lib/oli_web/live/workspaces/course_author/bibliography_live.ex
lib/oli_web/live_session_plugs/authorize_project.ex
lib/oli_web/live_session_plugs/set_project.ex
test/oli_web/live/workspace/course_author/bibliography_test.exs

Ticket: [MER-3596](https://eliterate.atlassian.net/browse/MER-3596)
This PR migrated the authoring bibliography page to LiveView for use as part of the course author space.
[MER-3596]: https://eliterate.atlassian.net/browse/MER-3596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3596] Migrate authoring bibliography live view to new workspace layout and live session

---

assets/src/hooks/evaluate_mathjax_expressions.ts

28.6 hotfix added a new spot of MathJAX typesetting, but didn't honor the requirement that the same global promise is used (as was fixed in https://eliterate.atlassian.net/browse/MER-1782?atlOrigin=eyJpIjoiYjdlOGFmMDhhYTRhNGNlMzk4MjMxZTNmY2E5YTAzNzQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
This PR applies the same logic in this new phoenix liveview hook

[BUG FIX] [MER-3716] Ensure same promise is used for all MathJax typesetting

---

lib/oli/rendering/content/html.ex

This PR fixes delivery view of popups that are inline to paragraphs.  The internal phoenix_react needed to have `:receiver_tag` specified as `:span` to override the default `:div`

[BUG FIX] [MER-3733] Fix popup rendering

---

lib/oli/delivery/attempts/page_lifecycle/ungraded.ex
lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

This PR does two things:
1. Removes the logic clause that automatically triggers in practice pages a "move forward" to a new available published revision of the page.  Students will be pinned to the original revision for the lifetime of that page attempt.  They can still click "reset answers" - which will move them forward to the latest revision in the new page attempt.
2. Removes the logic that required a "page to have been visited" to show the green check.  This was just bad impl, as it relied on Revision ID and not resource ID.  But it is enough to only require 100% progress.

[BUG FIX] [MER-3740] Suppress revised state change

---

lib/oli_web/common/links.ex
lib/oli_web/live/workspaces/course_author/curriculum/entry.ex
lib/oli_web/live/workspaces/course_author/curriculum_live.ex

Ensure that when accessing curriculum links to sections from the old-style view, we link to the old-style section/containers and not the ones in the course author workspace
See: https://eliterate.atlassian.net/browse/MER-3597

[ENHANCEMENT] [MER-3597] Curriculum workspace migration links backwards compatibility

---

assets/styles/delivery/activity.scss
assets/tailwind.theme.js

The default tailwind table styles were leading to illegible results for tables in the feedback context, particularly in dark mode. This adds custom styles to tables within feedback to ensure visibility of borders and text against the colored feedback background, and also ensure no dark mode changes (since feedback background/text color doesn't change). 
In theory the table text and borders should use css variables to render with the same color as text in the feedback context. Currently different css color variables are defined in `tailwind.theme.js` that would allow for potentially different text colors in correct, incorrect, and explanation feedback. Keeping to that model would require different table styles for each of these contexts as well. But currently these text colors are all just …

[BUG FIX] [MER-3711] Style tables within feedback to ensure legibility

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-3704) to the ticket
With this fix, we now list pages grouped by scheduling type (`:due_by` or `:read_by`) and end date. 
This fix still supports grouping pages that are not scheduled and hiding completed ones.
https://github.com/user-attachments/assets/6c0b511f-f1ea-4153-959f-615767e5d313

[BUG FIX] [MER-3704] Wrong scheduling type label on pages

---

lib/oli/delivery/previous_next_index.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/updates.ex
lib/oli/delivery/updates/worker.ex
test/oli/sections_test.exs

Large course sections (like REAM CHEM) can take 5-10 seconds to apply an update.  The root cause is in the cost of creating and deleting all of the `SectionResource` records.  The original course section update logic deletes and then recreates **all** of the non-hierarchical SR records, regardless of if they were changed or not.  So in a course like REAL CHEM where there are maybe 3000 non-hierarchical SR records (all activities, tags, objectives) we are deleting and recreating 3000 records even in the case where the publication update simply changed the content of 1 single page. 
This rewrite of the update logic (into a new module `Oli.Delivery.Sections.Updates`) eliminates this wasteful step.  It also cleans up the code to make it more readable and approachable for future editing. 
This …

[PERFORMANCE] [MER-3709] Streamline course section update application

---

lib/oli/delivery/settings.ex
lib/oli/delivery/settings/combined.ex
lib/oli_web/common/format_date_time.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[Link ](https://eliterate.atlassian.net/browse/MER-3704?focusedCommentId=24248)to the comment in the ticket
This PR extends [the same fix implemented on the "Learn" page](https://github.com/Simon-Initiative/oli-torus/pull/5078) into page headers.
https://github.com/user-attachments/assets/876ac494-a5a8-4680-ab74-863207028bcf

[BUG FIX] [MER-3704] Wrong scheduling type label on page header

---

assets/src/apps/Components.tsx

Ticket: [MER-3596](https://eliterate.atlassian.net/browse/MER-3596)
This PR addresses the issue discovered during QA, where the Bibliography page failed to load. The root cause seems to be that the necessary component wasn't correctly imported when rendering the Bibliography page. Adding the component to Components.tsx appears to resolve the problem.
[MER-3596]: https://eliterate.atlassian.net/browse/MER-3596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3506] Register Bibliography in Components

---

lib/oli_web/live/workspaces/course_author/bibliography_live.ex

Ticket: [MER-3596](https://eliterate.atlassian.net/browse/MER-3596)
This PR adds a catch-all `handle_params` callback to manage the sidebar collapser. The collapser triggers a `JS.patch`, which in turn invokes `handle_params`, as specified in the [documentation](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#push_patch/2):
> When navigating to the current LiveView, handle_params/3 is immediately invoked to handle the change of params and URL state.
[MER-3596]: https://eliterate.atlassian.net/browse/MER-3596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3596] Add handle_params to Bibliography

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[Link to the comment](https://eliterate.atlassian.net/browse/MER-3704?focusedCommentId=24270) in the ticket
https://github.com/user-attachments/assets/42fd7908-e953-43e9-a56c-c2a2ddd37ea2

[BUG FIX] [MER-3704] Wrong scheduling type label on graded pages and top level pages

---

config/runtime.exs

This PR exposes the DBConnection library (which `Ecto` uses) config values for `queue_target` and `queue_interval`. 
The default value of `50` (milliseconds) for `queue_target` is how long a request for a connection from the pool will queue before it times out and throws the dreaded error: 
```
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 101ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
1. Ensuring your database is available and that you can connect to it
2. Tracking down slow queries and making sure they are running fast enough
3. Increasing the pool_size (although this increases resource consumption)
4. Allowing requests to wait longer by increasing …
```

[CHORE] [MER-3786] Allow setting of the interval and target for db_connection

---

assets/src/components/editing/elements/youtube/YoutubeElement.tsx
assets/src/components/youtube_player/YoutubePlayer.tsx
assets/src/data/content/writers/html.tsx
lib/oli/rendering/content/html.ex
lib/oli_web/controllers/api/xapi_controller.ex

When a Youtube video was present in the page (as opposed to being in an activity) it was NOT correctly emitting XAPI events from the front end for play, pause, stop, etc.  It was missing the page attempt guid, which broke the bundle creation on the server and prevented the XAPI bundle from going to S3. 
This PR fixes the problem by mirroring the solution present for HTML5 video (which does work), namely to simply specify and pass down the attempt guid as a React param.

[BUG FIX] [MER-3797] Fix Youtube XAPI emitting 

---

lib/oli/delivery/settings.ex
test/oli/delivery/attempts/was_late_test.exs
test/oli/delivery/settings_test.exs

Ticket: [MER-3330](https://eliterate.atlassian.net/browse/MER-3330)
This PR fixes a bug where an activity set to 'Suggested By' with a past date was incorrectly blocking attempts to that activity.
[MER-3330]: https://eliterate.atlassian.net/browse/MER-3330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3330] students see deadline message with suggested by dates

---

assets/styles/adaptive/activities/dropdown.scss
assets/styles/adaptive/activities/popup.scss
assets/styles/adaptive/activities/text-input.scss
assets/styles/preview/preview-tools.scss

This PR contains the change for the following tickets:
1. [Popup component remains dark](https://eliterate.atlassian.net/browse/MER-3763)
2. [Dropdown/Num/Text Input Components contain dark background](https://eliterate.atlassian.net/browse/MER-3762)
3. [Inspector text/background visibility in Dark Mode](https://eliterate.atlassian.net/browse/MER-3760)

[BUG FIX] [MER-3763] Dropdown/Num/Text Input Components contain dark background

---

lib/oli/delivery/sections/updates.ex

Clears the section cache for the section that has just applied the update. 
This is placed outside of the transaction to guarantee that there are no race conditions. There is a subtle race condition here if we did this clearing inside the transaction.  Consider the steps to do this during the transaction:
1. Transaction begins to apply update
2. All the code runs to apply the update
3. As a final step we clear the cache
4. Transaction ends
The race condition is that between steps 3 and 4, any call from another process to the `SectionCache.get_or_compute` would see that the cache is empty and it could reinitialize it to the old entries.   Instead, we do this:
1. Transaction begins to apply update
2. All the code runs to apply the update
3. Transaction ends
4. We clear the cache

[BUG FIX] [MER-3814] Clear section cache

---

lib/oli_web/live/grades/grade_sync.ex
lib/oli_web/live/grades/grades.ex
test/oli_web/live/grades_live_test.exs

[MER-3682](https://eliterate.atlassian.net/browse/MER-3682)
This PR addresses an issue and mitigates the risk of another when synchronizing course grades with an LMS:
1. Resolves and eliminates LiveView-related console errors in the browser (see attached gif).
2. Lowers the likelihood of encountering a Rate Limit Error when fetching an LMS access token. This is achieved by disabling grade passback when already in progress, removing unnecessary access token requests, and applying a throttle to the relevant button.
[MER-3682]: https://eliterate.atlassian.net/browse/MER-3682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUGFIX] [MER-3613] Grade Passback Issue

---

assets/src/components/activities/common/delivery/inputs/NumericInput.tsx
assets/src/components/activities/short_answer/sections/NumericInput.tsx
assets/src/utils/number.ts
assets/styles/delivery/activity.scss
assets/test/utils/number_test.ts

Converts the input from type `number` to type `text` and adds in regex based validation that what the user has entered is a number.  When it is not a number, displays a red border around the input to indicate the validation value.   In all cases, whatever they have entered into the input will round trip to the server and save.

[BUG FIX] [MER-3823] Convert numeric to text input

---

lib/oli/accounts.ex
lib/oli_web/pow/messages.ex
lib/oli_web/pow/user_context.ex
lib/oli_web/pow/user_identities_context.ex
lib/oli_web/templates/email/account_already_exists.html.eex

https://eliterate.atlassian.net/browse/MER-3619
This PR fixes 2 issues related to LTI and direct delivery accounts being intermingled if they have the same email address.
The issue is that the system is not properly constraining the existing account checks to `independent_learner: true` in 2 important places in the code:
- `lib/oli_web/pow/user_context.ex`
- `lib/oli_web/pow/user_identities_context.ex`
This is preventing torus from creating a new account when one already exists in the LTI domain with the same email.
~~Further, my suspicion is that the callback to user_identities_context is being triggered during an LTI launch. This callback pattern matches on “email_verified: true” assuming that only social login providers can meet that condition, however on LTI launch this email_verified …

[BUG FIX] [MER-3619] Fix an issue where account creation silently fails in certain cases

---

lib/oli_web/templates/layout/chromeless.html.heex
lib/oli_web/templates/layout/delivery.html.heex
lib/oli_web/templates/layout/delivery_from_payment.html.heex
lib/oli_web/templates/payment_providers/stripe/index.html.heex

[Ticket](https://eliterate.atlassian.net/browse/MER-3717)
This changes the URLs from which polyfill.js script is loaded from the now insecure polyfill.io to the cloudflare cdn, which implements a compatible service.

[CHORE] [MER-3717] Load polyfill script from cloudflare cdn 

---

lib/oli_web/live/new_course/new_course.ex
test/oli_web/live/new_course/course_details_test.exs

This corrects the new section form to convert user-entered start and end date/times from the user's time zone to UTC before storing.  This issue appears to be handled correctly in the edit section details view which allows for modifying the dates after creation. Failure to convert the dates on creation was leading to the initial times being treated as UTC times. Then these appeared adjusted to the user's time zone in the later editing form. 
Note two validation failures can occur on this step of the new section creation form: missing one or both of the date/times, or having the start and end date be the same (regardless of times).

[BUG FIX] [MER-3683] convert start/end dates to UTC before storing

---

lib/oli_web/live/insights/insights.ex

[MER-3792](https://eliterate.atlassian.net/browse/MER-3792)
This PR fixes the search bar that filters the results table in the `Insights` liveview.
https://github.com/user-attachments/assets/2c2ab2bc-f32c-46b1-b288-65d49d41d266
[MER-3792]: https://eliterate.atlassian.net/browse/MER-3792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3792] FIx Insights search bar

---

lib/oli/delivery/sections/updates.ex

There were four other settings not being pulled forward from the revisions during course section update application.

[BUG FIX] [MER-3832] Preserve other revision settings

---

lib/oli/delivery/sections/updates.ex

Adds in a missing step of updating the `numbering_index` and `numbering_level` attributes of the section resource records, in the case of a `:major` update.  
This missing step is what was causing a number of issues specified in https://eliterate.atlassian.net/browse/TRIAGE-998

[BUG FIX] [MER-3826] Update numbering index and level in SectionResource records during major update

---

lib/oli/delivery/previous_next_index.ex
lib/oli/delivery/sections.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/schedule_live.ex
test/oli/delivery/sections_test.exs
test/oli_web/live/delivery/student/home/components/schedule_component_test.exs

This eliminates 3 out of 4 queries mentioned in the original ticket. 
It also ensures that for `IndexLive` and `ScheduleLive` that we only run the meaty part of `on_mount` one time.

[PERFORMANCE] [MER-3821] Eliminate extra queries in IndexLive.mount/3

---

assets/src/apps/page-editor/PageEditor.tsx
lib/oli_web/live/workspaces/course_author/curriculum/entry.ex
lib/oli_web/live/workspaces/course_author/editor_live.ex
lib/oli_web/router.ex
test/oli_web/live/workspaces/course_author/editor_live_test.exs

Migrate the revision edit page to a new liveview under the `workspaces/course_author` scope.
https://github.com/user-attachments/assets/d5ea507e-7922-40ad-ae6e-2080f0d25a09
Related: https://eliterate.atlassian.net/browse/MER-3598
Note: The background for each edition block must be changed in `assets/styles/authoring/model-editors.scss` once there is a design for it .

[FEATURE] [MER-3598] Revision Editor Liveview

---

lib/oli_web/controllers/static_page_controller.ex
lib/oli_web/icons.ex
lib/oli_web/templates/static_page/index_logged_in.html.heex
test/oli_web/controllers/static_page_controller_test.exs

[MER-3535](https://eliterate.atlassian.net/browse/MER-3535)
This PR implements a new view used when a student is logged into the application, but visits the login screen again. 
Depending on whether the user is an `Independent Student` or an `LMS Student` we will show different information to the user. 
- View for already logged in user who is an independent student
- View for already logged in user who is an LMS student
[MER-3535]: https://eliterate.atlassian.net/browse/MER-3535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3535] Student logged in visits index home page

---

lib/oli_web/live/delivery/student/utils.ex

The LessonLive migration in V28 lost the setting of `project_slug` for rendering context, which is necessary for the DecisionPointStrategy to enroll students into Upgrade experiments.  I verified this fixes the issue by running an experiment locally in my dev env.

[BUG FIX] [MER-3837] Restore Upgrade integration

---

assets/src/components/activities/common/delivery/inputs/NumericInput.tsx
assets/src/components/activities/common/delivery/persistence.ts
assets/src/components/activities/multi_input/MultiInputDelivery.tsx
assets/src/components/activities/response_multi/ResponseMultiInputDelivery.tsx
assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx
assets/src/components/activities/short_answer/sections/NumericInput.tsx
assets/src/components/editing/elements/youtube/YoutubeElement.tsx
assets/src/components/youtube_player/YoutubePlayer.tsx
assets/src/data/content/writers/html.tsx
assets/src/hooks/delayed_submit.ts
assets/src/hooks/index.ts
assets/src/utils/number.ts
assets/styles/delivery/activity.scss
assets/test/utils/number_test.ts
config/runtime.exs
lib/oli/accounts.ex
lib/oli/rendering/content/html.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/controllers/api/xapi_controller.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/pow/messages.ex
lib/oli_web/pow/user_context.ex
lib/oli_web/pow/user_identities_context.ex
lib/oli_web/templates/email/account_already_exists.html.eex

**DO NOT SQUASH**: Select "Merge Commit" when merging
I'm not sure how it got past CI, but it seems one of the hotfix changes broke a test (and also introduced a bug). Commit [19a16d9](https://github.com/Simon-Initiative/oli-torus/pull/5125/commits/19a16d93610ae1beb84612a619d9b74f845a04e7) fixes the issue. We'll likely need to make this change in the next v28 hotfix branch as well.

[CHORE] [MER-0000] Integrate v0.28.10

---

lib/oli_web/icons.ex
lib/oli_web/templates/static_page/index_logged_in.html.heex

[MER-3535](https://eliterate.atlassian.net/browse/MER-3535)
This PR fixes the styling of hovering over the `Access my courses` text in the login view when a student is already logged into the application, so that the blue underline of the link containing that text is not shown. 
As the text and the arrow are separate components, both have their own styling when hovering over the element. 
[MER-3535]: https://eliterate.atlassian.net/browse/MER-3535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3535] Fixes text style on hover

---

lib/oli_web/live/workspaces/utils.ex
lib/oli_web/live_session_plugs/assign_active_menu.ex

Ticket: [MER-3299](https://eliterate.atlassian.net/browse/MER-3299)
This PR addresses the comment regarding the display of long text in the submenu (see [here](https://eliterate.atlassian.net/browse/MER-3299?focusedCommentId=24291)). Instead of showing it in a single line, it is now displayed across multiple lines based on the text length. See the "Recommended Actions" in the images below.
Note: Commit 33a18dba3996b383c8c3134df161d876ba4bf67f is a refactor made to the `AssignActiveMenu` live plug. For some weird reason when working on this ticket, the `String.to_existing_atom(active_view_string)` was failing to convert the view. As a workaround, we now validate against `valid_views_for_instructor` before attempting the conversion. This should avoid creating more atoms other than the …

[BUG FIX] [MER-3299] Adjust long text in submenu

---

lib/oli/delivery/attempts/scoring.ex
test/oli/delivery/attempts/scoring_test.exs

The comments in the code explain what this PR does - but essentially it strengthens the guarantee that we take the "most recently evaluated page attempt" for the `most_recent` scoring strategy.

[BUG FIX] [MER-3847] Sort attempts by date_evaluated

---

lib/oli_web/live_session_plugs/set_sidebar.ex

[MER-3715](https://eliterate.atlassian.net/browse/MER-3715)
This PR tries to fix the error that occasionally happens in the `set_sidebar` plugin, when trying to match a nil value. 
This seems to be an edge case and apparently happens when in the session structure we have a value for the `section_slug` key for which no root container is found. 
The changes introduced try to avoid the case mentioned above, by handling more securely values that may be nil.
[MER-3715]: https://eliterate.atlassian.net/browse/MER-3715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3715] Fix sidebar nil error

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/icons.ex
lib/oli_web/live/workspaces/student.ex
lib/oli_web/live_session_plugs/set_sidebar.ex

Ticket: [MER-3848](https://eliterate.atlassian.net/browse/MER-3848)
This PR fixes the bug that occurs when toggling the sidebar and then switching to another workspace. The connection was halted in that scenario, but the only condition for a halt should be when it is in the same workspace. Triggering a halt when moving to another workspace interrupts the LiveView lifecycle, as mentioned in the documentation.
> Note that halting from a hook will halt the entire lifecycle stage. This means that when a hook returns {:halt, socket} then the LiveView callback will not be invoked. This has some implications.
This PR also adds a separator line between the workspace menu and the submenu, see commit 44942cfb0b8569734b7bd13ee95b1612ae23219d.
[MER-3848]: …

[BUG FIX] [MER-3848] anomaly when alternating between tabs in the expanded contracted sidebar

---

lib/oli/delivery/attempts/scoring.ex
test/oli/delivery/attempts/scoring_test.exs

Fix an issue uncovered from the last set of commits: namely that the `translate_nils` function in the `Scoring` module inadvertently was stripping out all attributes besides `out_of` and `score`. 
This changes preserves the mapping being done in `translate_nil`, but while preserving all the other attributes (which the "most_recent" strategy depends on)

[BUG FIX] [MER-3847] Preserve attrs during scoring strategy application

---

lib/oli_web/components/common.ex

[Link](https://eliterate.atlassian.net/browse/MER-3857) to the ticket
The bug was introduced in [MER-3639](https://github.com/Simon-Initiative/oli-torus/pull/5119); when I extended the progress_bar component to support different colors and styling (height, rounded-corners, etc) I accidentally swapped the default color values.
[MER-3639]: https://eliterate.atlassian.net/browse/MER-3639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3857] Fix progress bar color

---

lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/templates/static_page/index.html.eex
test/oli_web/controllers/delivery_controller_test.exs
test/oli_web/controllers/static_page_controller_test.exs

On the student sign in page, display 'Create an Account' link if from_invitation_link? param is set to true
https://github.com/user-attachments/assets/55c0f799-c6eb-4dd4-bc6a-e0c99677020f
See: https://eliterate.atlassian.net/browse/MER-3294

[ENHANCEMENT] [MER-3294] Create an Account link in Student Sign In page when following enrollment link

---

lib/oli_web/controllers/project_controller.ex
lib/oli_web/live/workspaces/course_author/alternatives_live.ex
lib/oli_web/live/workspaces/course_author/analytics_live.ex
lib/oli_web/live/workspaces/course_author/datashop/table_model.ex
lib/oli_web/live/workspaces/course_author/index_csv_live.ex
lib/oli_web/live/workspaces/course_author/overview_live.ex
lib/oli_web/live/workspaces/course_author/overview_table_model.ex
lib/oli_web/router.ex
test/oli_web/live/workspaces/course_author/overview_live_test.exs
test/oli_web/live/workspaces/course_author_test.exs

[MER-3604](https://eliterate.atlassian.net/browse/MER-3604)
This PR updates the routes in the project table so that when entering a project the author/admin is redirected to use the new workspace.
The `Alternatives`, `CSV import` and `Datashop Analytics` liveviews are also migrated, as they were not migrated when working on the `Overview` liveview migration.
https://github.com/user-attachments/assets/4659d48c-47d2-49ef-b6f7-9b94a95b11db
[MER-3598]: https://eliterate.atlassian.net/browse/MER-3598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-3604]: https://eliterate.atlassian.net/browse/MER-3604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3604] Update projects table routes

---

lib/oli_web/live/workspaces/student.ex
test/oli_web/live/workspaces/student_test.exs

If a user can create sections, then the user is considered and instructor and the navigation sidebar should be displayed.
See: https://eliterate.atlassian.net/browse/MER-3300

[BUG FIX] [MER-3300] Show sidebar if user can create sections

---

lib/oli_web/controllers/project_controller.ex
test/oli_web/controllers/project_controller_test.exs

[MER-3604](https://eliterate.atlassian.net/browse/MER-3604)
This PR fixes the redirection after creating a project so that the user is redirected to the overview of the newly created project within the course author's workspace. 
https://github.com/user-attachments/assets/8d020a14-3a5c-4c51-892c-5f2728aaf518
[MER-3604]: https://eliterate.atlassian.net/browse/MER-3604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3604] Fix redirect after creating a project

---

lib/oli/delivery/snapshots/worker.ex

This PR pulls from `master` an adjustment that properly handles duplicate snapshot record insertion attempts.

[BUG FIX] [MER-3858] Handle snapshot conflict

---

lib/oli/delivery/hierarchy.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/section_cache.ex
lib/oli_web/live/delivery/student/home/components/schedule_component.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli/delivery/hierarchy_test.exs
test/oli_web/live/delivery/student/home/components/schedule_component_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/utils_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-3798) to the ticket
https://github.com/user-attachments/assets/6cbefb07-e985-40b8-bae6-7383c7224245
When all the contained pages have scheduling type = "suggested by", the container label will be "Read by".
https://github.com/user-attachments/assets/f54a310d-6bab-4e2d-b7ce-4ad182eae45f

[FEATURE] [MER-3798] update scheduling type labels

---

assets/src/components/activities/common/delivery/SubmitReset.tsx
assets/src/components/activities/common/delivery/submit_button/SubmitButton.tsx
assets/src/components/activities/common/delivery/submit_button/SubmitButtonConnected.tsx
assets/src/components/activities/short_answer/ShortAnswerDelivery.tsx
assets/src/components/activities/short_answer/schema.ts

Legacy OLI had a type of short answer text question called "Submit and Compare". These had no incorrect answer; the purpose was for the student to compose an answer then submit it in order to compare their answer to a correct answer shown as feedback.  The migration tool migrates these to torus short answer questions in which every answer is correct. The migration script includes a "submitAndCompare: true" attribute in the question model to flag these questions. 
This PR changes the Submit button for these questions to read "Submit and Compare" to more closely recreate the legacy experience with these questions. 
To do this it was necessary to pass an optional label parameter through several layers of components. In all cases omitting the parameter or setting it explicitly to "undefined" …

[ENHANCEMENT] [MER-3855] Change Submit to Submit And Compare on migrated SubmitAndCompare questions

---

lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/plugs/redirect_by_attempt_state.ex
test/oli_web/live/delivery/student/lesson_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-3708) to the ticket
The query params in the URL were causing the iframe to crash. The fix removes the query params from adaptive pages routes and, since the `request_path` query param was needed to provide the back URL path, we now pass it through the session.
The request_path (used for the back/home button) was passed as an URL query param
https://github.com/user-attachments/assets/e1afcbf5-75ce-44b7-a9d2-ea0204e57d58
The request_path is set to the conn session to keep back/home button functionality working as before
https://github.com/user-attachments/assets/c158de38-1320-4f67-ae83-ccb3c441edf9

[BUG FIX] [MER-3708] 500 error with iframed lesson launch links

---

assets/src/components/activities/short_answer/sections/MathInput.tsx

MathLive keyboard is used to edit math input questions, but the keyboard toggle button was disappearing on return or reload in authoring. Cause seems to be that our React wrapper uses editMode from authoring context to set mathfield's readOnly property, which hides the keyboard toggle, but changing mathfield to non-readonly is apparently not sufficient to show the keyboard toggle again (arguably a defect in the MathLive version we are using).  Logging shows author mode rendering may pass through initial renders with editMode=false before finally becoming editable, but keyboard toggle was not being re-shown. Always explicitly including the appropriate keyboard option fixes.

[BUG FIX] [MER-3853] ensure MathLive keyboard shows in authoring

---

lib/oli_web/live/workspaces/instructor/index_live.ex
lib/oli_web/live/workspaces/student.ex

https://github.com/user-attachments/assets/16cea1d2-99e0-406a-8a93-47f5b9045648
The code removed was added in commit [1c7af4d](https://github.com/Simon-Initiative/oli-torus/commit/1c7af4dee57f445a0b2cfd024692d70234091059#diff-281eaaca2196c3d882fddc362b9e96e241cc931eec2591cd6212f9c41147fecaR96). I don't know if it is essential to that feature. But it was also present in the student workspace.
See: https://eliterate.atlassian.net/browse/MER-3570

[BUG FIX] [MER-3570] Fix delay when switching between instructor and student tabs

---

lib/oli_web/live/workspaces/instructor/index_live.ex
lib/oli_web/live/workspaces/student.ex

As commented by @nicocirio in https://github.com/Simon-Initiative/oli-torus/pull/5155#pullrequestreview-2345421105, we can add the transitions back but only make them dynamic up to the 6th card which is what the user sees.

[ENHANCEMENT] [MER-3570] Add card transitions back for Instructor/Student index

---

lib/oli_web/live/common/filter_box.ex
lib/oli_web/live/workspaces/course_author/activity_bank_live.ex
lib/oli_web/live/workspaces/course_author/bibliography_live.ex
lib/oli_web/live/workspaces/course_author/curriculum_live.html.heex
lib/oli_web/live/workspaces/course_author/experiments_live.ex
lib/oli_web/live/workspaces/course_author/insights_live.ex
lib/oli_web/live/workspaces/course_author/overview_live.ex
lib/oli_web/live/workspaces/course_author/products/details_live.ex
lib/oli_web/live/workspaces/course_author/products_live.ex
lib/oli_web/live/workspaces/course_author/publish_live.ex
lib/oli_web/live/workspaces/course_author/review_live.ex
test/oli_web/live/all_pages_live_test.exs
test/oli_web/live/sections/admin_index_live_test.exs
test/oli_web/live/workspaces/course_author/experiments_live_test.exs
test/oli_web/live/workspaces/course_author/pages_live_test.exs
test/oli_web/live/workspaces/course_author/products/details_live_test.exs
test/oli_web/live/workspaces/course_author/publish_live_test.exs
test/oli_web/live/workspaces/course_author_test.exs

Ticket: [MER-3869](https://eliterate.atlassian.net/browse/MER-3869)
This PR adds headers for resources in the course author space.
https://github.com/user-attachments/assets/8d01fec6-0d6b-4b93-a1af-8ad93e82ffeb
[MER-3869]: https://eliterate.atlassian.net/browse/MER-3869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3869] missing headers in author workspace

---

lib/oli_web/pow/author_controller_callbacks.ex
test/oli_web/live/workspaces/course_author_test.exs

This PR updates the "OliWeb.Pow.AuthorControllerCallbacks," which was bypassing some upstream POW user and authentication management functionality, to allow delegation back upstream "Pow.Extension.Phoenix.ControllerCallbacks." This, in turn, fixes the broken email confirmation issue encountered when creating a new authoring account.

[BUG FIX] [MER-3812] fixes the new author email confirmation broken bug

---

lib/oli_web/live/curriculum/entries/options_modal.ex
test/oli_web/live/curriculum/container_test.exs

[MER-3612](https://eliterate.atlassian.net/browse/MER-3612)
This PR sets a default value of 2 to the numeric input that is used to set the number of attempts of the `After Set Num Attempts` explanation strategy within the modal that an author/admin uses to set the options for a course curriculum page. 
If the above strategy has no value it will default to a value of 2 and otherwise it will use the value that has been set previously.
https://github.com/user-attachments/assets/256110d8-22b3-4433-8645-5e72ca518f47
[MER-3612]: https://eliterate.atlassian.net/browse/MER-3612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3612] Fix set num attempts default value

---

lib/oli/analytics/xapi/events/attempt/part_attempt_evaluated.ex

The xAPI statement for evaluated part attempts is missing the `datashop_session_id` field, which makes DataShop calculations in the cloud a bit harder to do.  This PR adds it in as an extension.

[BUG FIX] [MER-3874] Add session id field

---

assets/src/apps/authoring/components/Flowchart/rules/create-cata-choice-rules.ts
assets/src/apps/authoring/components/Flowchart/rules/create-dropdown-rules.ts
assets/src/apps/authoring/components/Flowchart/rules/create-multiple-choice-rules.ts
assets/src/apps/authoring/components/Flowchart/rules/create-number-input-rules.ts
assets/src/apps/authoring/components/Flowchart/rules/create-slider-rules.ts
assets/src/apps/authoring/components/Flowchart/rules/create-text-input-rules.ts
assets/src/apps/authoring/components/Flowchart/rules/create-three-try-workflow.ts
assets/src/apps/authoring/components/PropertyEditor/schemas/screen.ts

The simple author currently defaults to 3 attempts for a screen, with no option to change this. The requirement was to introduce the ability to change the number of allowed attempts. The default should remain at three, but users should be able to specify a different number of attempts (1, 2, 3, 4, or 5). The system should honor the specified number.

[FEATURE] [MER-3415] Changing number of attempts available in simple author/flowchart tool

---

assets/src/apps/authoring/Authoring.tsx
assets/src/apps/authoring/AuthoringExpertPageEditor.tsx
assets/src/apps/authoring/AuthoringFlowchartPageEditor.tsx
assets/src/apps/authoring/BottomPanel.tsx
assets/src/apps/authoring/components/ExpertHeaderNav.tsx
assets/src/apps/authoring/components/Flowchart/FlowchartEditor.tsx
assets/src/apps/authoring/components/SidePanel.tsx

[Link](https://eliterate.atlassian.net/browse/MER-3877) to the ticket
This PR makes a small refactor on the work done in [MER-3867](https://github.com/Simon-Initiative/oli-torus/pull/5170) (by setting the Authoring component as the source of truth for the sidebar state -collapsed or expanded-) and extends that fix for simple adaptive pages.
https://github.com/user-attachments/assets/488d6a2b-9fd7-4c3d-9afe-64fb679c238f
[MER-3867]: https://eliterate.atlassian.net/browse/MER-3867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3877] Workspace sidebar overlaps simple adaptive pages

---

priv/repo/migrations/20240917111312_add_lifecycle_index.exs

https://eliterate.atlassian.net/browse/MER-3904
This PR adjusts a current migration to only attempt to create the activity_attempts_submitted index if it does not already exist.
This will allow us to create the index up-front before running the deployment in order to avoid excessive downtime and CI disconnects.
Without this, creating the index ahead of time would result in the following error:
```
12:48:26.281 [info] execute "CREATE INDEX activity_attempts_submitted ON activity_attempts (lifecycle_state) WHERE lifecycle_state = 'submitted';"
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "activity_attempts_submitted" already exists
```

[ENHANCEMENT] [MER-3904] only create activity_attempts_submitted index if it doesnt already exist

---

lib/oli_web/components/delivery/scored_activities/assessments_table_model.ex
lib/oli_web/components/delivery/scored_activities/scored_activities.ex
test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs

[MER-3323](https://eliterate.atlassian.net/browse/MER-3323)
This PR adds a new column to the table that shows the `Scored Activities` tab in the instructor dashboard. 
This new column shows the order that each of the pages in the course has and allows the user to filter by it.
https://github.com/user-attachments/assets/9108f97c-6bdd-4973-bbfc-300db5db6019
[MER-3323]: https://eliterate.atlassian.net/browse/MER-3323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3323] Add order column to sort

---

lib/oli/delivery/gating.ex
test/oli_web/live/sections/gating_and_scheduling_test.exs

[MER-3701](https://eliterate.atlassian.net/browse/MER-3701)
This PR fixes the bug happened when an admin or instructor tried to access the student exceptions view when there were already student exceptions on a gate by clicking the `Manage Student Exceptions` button.
https://github.com/user-attachments/assets/22246867-6b74-461b-8688-53664ac9b844
[MER-3701]: https://eliterate.atlassian.net/browse/MER-3701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3701] Error managing gating student exceptions

---

lib/oli_web/components/delivery/layouts.ex

[MER-3668](https://eliterate.atlassian.net/browse/MER-3668)
This PR modifies the way to navigate between resources while inside a page as a student. 
If the previous or next resource is a `Unit` or `Module` type container, navigating to that resource will redirect to the `Learn view`, going to the resource and highlighting it. 
This implementation was already in place, but we believe it was reverted in one of our previous versions. 
We already have written tests for these use cases. 
https://github.com/user-attachments/assets/0a79194c-8a12-48c6-b872-b873cfcc5f52
[MER-3668]: https://eliterate.atlassian.net/browse/MER-3668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3668] Navigation to weird interstitial unit page

---

lib/oli/authoring/collaborators.ex
lib/oli_web/common/breadcrumb.ex
lib/oli_web/controllers/cognito_controller.ex
lib/oli_web/controllers/collaborator_controller.ex
lib/oli_web/controllers/project_activity_controller.ex
lib/oli_web/live/breadcrumb/breadcrumb_trail_live.ex
lib/oli_web/live/collaboration_live/admin_table_model.ex
lib/oli_web/live/community_live/associated/table_model.ex
lib/oli_web/live/ingest/ingest.ex
lib/oli_web/live/ingest/ingestv2.ex
lib/oli_web/live/products/products_table_model.ex
lib/oli_web/live/projects/table_model.ex
lib/oli_web/live/resources/activities_view.ex
lib/oli_web/live/resources/pages_view.ex
lib/oli_web/live/sections/overview_view.ex
lib/oli_web/live/sections/table_model.ex
lib/oli_web/live/users/author_projects_table_model.ex
lib/oli_web/live/workspaces/course_author/pages_live.ex
lib/oli_web/templates/cognito/clone_prompt.html.eex
test/oli_web/controllers/cognito_controller_test.exs
test/oli_web/controllers/collaborator_controller_test.exs
test/oli_web/controllers/project_controller_test.exs
test/oli_web/live/new_course/select_source_test.exs
test/oli_web/live/users/author_detail_view_test.exs

[MER-3933](https://eliterate.atlassian.net/browse/MER-3933)
This PR fixes the routes used to redirect the user on occasions when the user interacts with the functionality of invite collaborators. 
Also, the route used in the `Join as Collaborator` button that a potential collaborator receives in the invitation email is fixed. 
https://github.com/user-attachments/assets/d5be9007-0bb2-4ebd-a9b9-57d23704b4f5
[MER-3933]: https://eliterate.atlassian.net/browse/MER-3933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3933] Authors get sent to old UI when interacting with project collaborators

---

lib/oli/authoring/editing/util.ex
lib/oli/resources/page_content.ex
test/oli/resources/page.json
test/oli/resources/page_content_test.exs

Citations in image captions were found to get broken on ingesting a correctly-migrated course, or on export-ingest of a correctly working course. This happened because the required rewiring process was not hitting cite elements in image captions. This happened because this rewiring used a function from the PageContent module which only traversed through element children, and caption content is in a caption property of the image,  not a child element. 
This PR implements a general solution to modify the relevant PageContent function to visit and process content in properties like the caption property of an image element, and also the relevant properties of a popup element, as is done correctly in the code that rewires links. 
~The relevant function is also used when generating unique ids …

[BUG FIX] [MER-3841] Make PageContent traversal functions hit content in properties like caption

---

lib/oli/accounts.ex
lib/oli_web/controllers/lti_controller.ex
priv/repo/migrations/20241017190834_drop_users_sub_index.exs
test/oli_web/controllers/cognito_controller_test.exs
test/oli_web/controllers/lti_controller_test.exs

[MER-3824](https://eliterate.atlassian.net/browse/MER-3824)
When an LTI launch happened as a student, the system previously used the user's `sub` to create or update the student's data and log him in. Since this sub is an external string, nothing ensures its uniqueness among different LMS institutions.
That's why these changes introduce a new query before an LMS launch to avoid `sub` collisions and be sure that we are under the scope of the LMS institution.
**Important Note:**
The same fix should be made as a separate PR under the SSO process since we could potentially end up with the same issue. 
[MER-3824]: https://eliterate.atlassian.net/browse/MER-3824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-3824] Ensure uniqueness on user subs among different LTI institutions

---

lib/oli_web/controllers/delivery_controller.ex
test/oli_web/controllers/delivery_controller_test.exs

Ticket: [MER-3169](https://eliterate.atlassian.net/browse/MER-3169)
This PR prevents LTI users from enrolling manually.
[MER-3169]: https://eliterate.atlassian.net/browse/MER-3169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3169] LTI users should not be allowed to manually enroll in any course

---

assets/src/apps/bibliography/PlainEntryEditor.tsx

The modal for adding/editing a bibliography entry as a bibTex string was unusable in dark mode: the text box picked up white text color but did not change its white background color to match. This change makes the text area inherit background color so it is properly responsive to dark mode. 
The alternative modal for "manual" entry definition by filling in field values does not have this issue. 
Old:
New:

[BUG FIX] [MER-3960] make bibliography entry editor usable in dark mode

---

assets/src/components/resource/editors/Editors.scss
assets/styles/delivery/layout/delivery.scss
lib/oli_web/live/collaboration_live/collab_space_config_view.ex
test/oli_web/live/delivery/student/lesson_live_test.exs

[MER-3912](https://eliterate.atlassian.net/browse/MER-3912)
Besides fixing the styles when editing a basic page, this PR fixes a flaky test on `lesson_live_tests.exs`.
Before:
https://github.com/user-attachments/assets/a7abb9e1-8432-4f61-ac8a-1dd122e8c92d
After:
https://github.com/user-attachments/assets/2a7a1f94-b074-40ee-b331-07fe24267ae8
[MER-3912]: https://eliterate.atlassian.net/browse/MER-3912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3913] Basic page editor styles broken

---

assets/src/apps/scheduler/SchedulerSaveBar.tsx

[Link](https://eliterate.atlassian.net/browse/MER-3922) to the ticket
A page's scheduled date (start or end date) can be updated in three ways:
1. By dragging the page icon to a different position in the schedule grid
2. By selecting the page icon and then selecting a new date from the date input
3. By selecting the page icon and typing in the new date in the date input
In all cases, the date input and the position of the corresponding page icon should stay synchronized (for example, if I drag a page to 09/10/2024, then the input should be updated to that same date - and vice-versa)
This logic applies to the end date (for graded and un-graded pages) and the start/available-from date (for graded pages).
When the user intended to change the date by the third option (typing in the date in …

[BUG FIX] [MER-3922] Date does not update when using scheduler slider

---

lib/oli_web/plugs/redirect_by_attempt_state.ex
lib/oli_web/router.ex
test/oli_web/live/delivery/student/review_live_test.exs

[MER-3925](https://eliterate.atlassian.net/browse/MER-3925)
This PR fixes a bug happened when an `instructor` or `admin` tried to view student submitted attempts on adaptive pages. 
- As instructor
https://github.com/user-attachments/assets/d3e3b4ba-60da-4709-9b5a-05a78c607eb4
- As Admin
https://github.com/user-attachments/assets/369de110-7265-4888-b3b2-c562479f86da
[MER-3925]: https://eliterate.atlassian.net/browse/MER-3925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3925] Not able to view student attempts

---

lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/controllers/static_page_controller.ex
lib/oli_web/pow/user_routes.ex
test/oli_web/controllers/delivery_controller_test.exs

Ticket: [MER-3926](https://eliterate.atlassian.net/browse/MER-3926)
This PR addresses an issue where a user trying to access an enrollment page, signing in with the Google provider, is redirected to the instructor page instead of the enrollment page.
[MER-3926]: https://eliterate.atlassian.net/browse/MER-3926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3926] enrolling in a course and logging in with google brings student to instructor dashboard

---

lib/oli/resources/page_content.ex

The fix in https://github.com/Simon-Initiative/oli-torus/pull/5179 changed content traversal functions to find content in captions and popups. But it didn't include content in definitions, so citations in definition content were still missed on ingestion, and this case also occurs in the CAHIMS course to be migrated. This PR adds the `meanings `property to the list of content-bearing properties for the `item_with_children` function to visit. 
A definition's `meanings `property contains a list of meaning elements. Meaning elements are like paragraphs, containers which hold content in their children. So, on visiting a meaning element, the content gets visited by the recursion through `children` which has always been part of this process.

[BUG FIX] [MER-3965] make ingestion process citations in definitions

---

assets/src/components/activities/custom_dnd/CustomDnDDelivery.tsx
assets/src/components/activities/custom_dnd/DragCanvas.tsx

Custom Drag-and-Drop on a practice page allows one to change a submitted part answer after evaluation. E.g on a three-item question on a practice page, one may drag item1 into slot1, get feedback, and then try to move it to another slot, or back to the starting position. If the new destination slot is occupied, the current occupant is bumped back to the starting position and replaced by the new one. 
Changes after part submission like this were causing the UI to show “working” and hang. (The working spinner was introduced to help prevent race conditions on multiple rapid changes which trigger async operations)
The error came from sending a bad partAttemptGuid in the submit call, presumably an old one which has been superseded by an intervening part reset. This arises from a complexity of …

[BUG FIX] [MER-3963] prevent drag and drop hang on change

---

lib/oli_web/common/breadcrumb.ex
lib/oli_web/live/workspaces/course_author/activities/activities_table_model.ex
lib/oli_web/live/workspaces/course_author/activities_live.ex
test/oli_web/live/workspaces/course_author/activities_live_test.exs
test/oli_web/live/workspaces/course_author/pages_live_test.exs
test/support/test_helpers.ex

[MER-3946](https://eliterate.atlassian.net/browse/MER-3946)
This PR fixes routes in a couple of places to fix the following flows mentioned in the ticket: 
- After user have created a page through the All Pages view then clicks on the breadcrumb to back to All Pages view.
https://github.com/user-attachments/assets/2cd1d05a-7ec5-4d59-a985-04284a2420c5
- User clicks on a page title in the All Activities view and navigates to the clicked page edit.
https://github.com/user-attachments/assets/c7901169-73b9-46ff-87dd-a149e695fa4c
[MER-3946]: https://eliterate.atlassian.net/browse/MER-3946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3946] Fix routes all pages and all activities views

---

assets/src/components/activity/InlineActivityEditor.tsx
lib/oli_web/live/workspaces/course_author/history_live.ex

[MER-3944](https://eliterate.atlassian.net/browse/MER-3944)
This PR fixes the route used to navigate to the `view revision history` link found in each activity that is added in the Activity Bank view within the Course Author Workspace. 
https://github.com/user-attachments/assets/5f32619c-9852-40cf-b856-de10bc4f6d5d
[MER-3944]: https://eliterate.atlassian.net/browse/MER-3944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3944] Fix activity bank revision history route

---

assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx
assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx
assets/src/apps/authoring/components/Flowchart/rules/create-three-try-workflow.ts
assets/src/apps/authoring/components/Flowchart/toolbar/FlowchartHeaderNav.tsx
assets/src/components/parts/janus-image/ImageAuthor.tsx
assets/src/components/parts/janus-image/schema.ts

Hey @bsparks, could you please look at the PR. Thanks.
This PR contains changes for the following tickets:
1. [Changing number of attempts available in simple author/flowchart tool](https://eliterate.atlassian.net/browse/MER-3415)
2. [Image component has fixed aspect ratio based on image dimensions](https://eliterate.atlassian.net/browse/MER-3412)
3. [Duplicated Text Box (Ctrl+c) Issue](https://eliterate.atlassian.net/browse/MER-3956)
**_#2_**
https://github.com/user-attachments/assets/8b92bcae-8641-480c-a15f-0487ab911949

[ENHANCEMENT] [MER-3412] Image component has fixed aspect ratio based on image dimensions

---

config/dev.exs
lib/oli_web/live/delivery/student/lesson_live.ex

[MER-3931](https://eliterate.atlassian.net/browse/MER-3931)
This PR addresses an issue where, if a student starts a graded attempt, then navigates away from the quiz and then returns to the quiz after the timeout is expired, the quiz erroneously allows the student to answer and submit responses. 
[MER-3931]: https://eliterate.atlassian.net/browse/MER-3931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3931] students can submit after time limit

---

lib/oli_web/templates/static_page/index_logged_in.html.heex
test/oli_web/controllers/static_page_controller_test.exs

[MER-3975](https://eliterate.atlassian.net/browse/MER-3975)
This PR improves the text of the login page seen by students who come from an LMS platform and while logged in visit the login page again.
- Before
- After
[MER-3975]: https://eliterate.atlassian.net/browse/MER-3975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-3975] Change LMS to Learning Management System

---

lib/oli/accounts.ex
test/oli/accounts_test.exs
test/oli_web/controllers/cognito_controller_test.exs
test/oli_web/live/products_test.exs

[MER-3953](https://eliterate.atlassian.net/browse/MER-3953)
This PR aims to fix getting data from infiniscope or any other LMS that uses SSO. 
In the author creation functions with SSO we were taking the field `cognito:username` as name, which was an error since that field brings us the username that sometimes can be a long string with numbers and letters as indicated in the ticket. 
With these changes we correctly assign the `name` field that comes from the LMS.
https://github.com/user-attachments/assets/abd7c694-cd6f-4a49-b2ad-e0c562b49541
[MER-3953]: https://eliterate.atlassian.net/browse/MER-3953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3953] Fix names for infiniscope author accounts

---

lib/oli_web/components/common.ex
lib/oli_web/live/delivery/student/index_live.ex

Link to [comment 1](https://eliterate.atlassian.net/browse/MER-3828?focusedCommentId=24822) and [comment 2](https://eliterate.atlassian.net/browse/MER-3828?focusedCommentId=24827) in the ticket
This PR adds some minor changes omitted in the original PR regarding a blur effect on the progress bar and some styling mismatching in light mode.
While working on this I found that the background color for assignments and agenda components was wrong in light mode, so I pushed a fix for that too.
https://github.com/user-attachments/assets/0394d670-d844-468d-b793-5073cc9da343

[FEATURE] [MER-3828] Home screen course progress card - part 2

---

lib/oli/delivery/sections.ex
lib/oli/delivery/sections/updates.ex
lib/oli/publishing.ex
lib/oli/publishing/publications/publication_diff.ex
test/oli/publishing/publications/diff_agent_test.exs
test/oli/publishing_test.exs

The original plan was to introduce resource link tracking into the DB, but that approach became overly complex - so instead I took this approach of moving the link calculation upfront during the publication process: namely to when the `PublicationDiff` is calculated.  Then, at publication application time, we use those links - but only to cull non-reachable pages from the project pertaining to the publication being updated.  
This does not completely eliminate the issue of "slow queries to calculate links" but it puts a constant upper bound (of 1) on the how many times we run this when a publication is pushed out to many course sections.

[PERFORMANCE] [MER-3934] Move link calculation upfront to publication diff

---

lib/oli_web/live/manual_grading/manual_grading_view.ex

Minor fix on how we detect if attempt is not set after a selection change.
See: https://eliterate.atlassian.net/browse/MER-3541

[BUG FIX] [MER-3541] Manual Grading Activities: When a manual graded attempt is selected, a refresh induces a 500

---

assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx

While working on a ticket related to Pop-up, I found the we are not able to edit the pop-up window. It goes blank and throws an error "`useDispatch() Error: Could not find react-redux context value; please ensure the component is wrapped in a <Provider>`". I removed the code that were using dispatch, and it's handled differently now.

[BUG FIX] [MER-3906] Clicking backspace causes the Delete Component modal to pop up

---

assets/src/components/activities/image_hotspot/ImageHotspotDelivery.tsx

This fixes a coding error which was preventing any existing image hotspot selection from being highlighted on first render. Symptom was that on reloading/returning to practice page or reviewing graded page after selection, the selection was not being highlighted. (Though hovering mouse over ANY hotspot would trigger a re-render that does show the selection). Relevant code to fetch canvas drawing context needed to be located inside the useEffect hook so it executes after rendering the canvas.

[BUG FIX] [MER-4003] fix so hotspot selection highlighted on return to page

---

lib/oli/delivery/attempts/manual_grading.ex

When Oban was enabled, scoring a manually graded activity would queue the snapshot creation instead of creating it immediately. This caused a false error message to appear in the UI. 
See: https://eliterate.atlassian.net/browse/MER-4004

[BUG FIX] [MER-4004] Fix snapshot creation for manually graded activities when Oban is enabled.

---

assets/src/apps/bibliography/BibEntryEditor.tsx

The "manual" bibliography entry editor allows for adding or deleting fields from a bibliography entry. However, the deletions were not taking effect. This occurred because the component was not propagating the change to its parent through props.OnEdit. This PR also recodes to use more concise field deletion code, though this is unrelated to the issue.

[BUG FIX] [MER-3269] Fix deletion of bib entry fields

---

lib/oli/delivery/sections.ex

This PR fixes a bug in a course section where, after students have completed attempts for activities that have learning objectives attached in ungraded pages, the instructor gets a 500 error when accessing the Learning Objectives view.

[BUG FIX] [MER-3980] 500 error in objectives view

---

assets/css/app.css
lib/oli_web/live/delivery/student/lesson/annotations.ex
lib/oli_web/live/delivery/student/lesson/components/outline_component.ex
lib/oli_web/live/delivery/student/lesson_live.ex

[MER-3827](https://eliterate.atlassian.net/browse/MER-3827)
Implement some styling changes on scrollbars across different browsers and operating systems to unify its appearance and make it look more like the Figma designs.
These tests were made in MacOS and Chrome/Firefox. It was not tested in Windows or Edge.
**Before** (Chrome and Firefox):
https://github.com/user-attachments/assets/29149133-ec1d-473c-b6c9-1e73226d4571
**After** (Chrome and Firefox):
https://github.com/user-attachments/assets/d1268e4b-3108-4223-ad0d-dd8a5bfb1809
[MER-3827]: https://eliterate.atlassian.net/browse/MER-3827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-3287] Lesson Page Outline and Annotations Panel Scrollbar Improvements

---

lib/oli/activities/realizer/selection.ex
test/oli/activities/realizer/selection_test.exs

This PR fixes the activity bank selection fulfillment to properly take into account the `:any` operator.

[BUG FIX] [MER-4007] Handle both AND and OR

---

assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx

There was a bug when copying a part which on a sub screen of a layer and pasting it on the same activity. Related approved PRs are https://github.com/Simon-Initiative/oli-torus/pull/5137 &  https://github.com/Simon-Initiative/oli-torus/pull/5166

[BUG FIX] [MER-4013] Update locations of new components added to adaptive pages

---

assets/src/hooks/click_variations.ts
lib/oli_web/live/delivery/instructor_dashboard/html_components.ex
test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs
test/oli_web/live/delivery/student_dashboard/student_dashboard_live_test.exs

Ticket: [MER-4017](https://eliterate.atlassian.net/browse/MER-4017)
This PR fixes the issue caused by the Progress Student tooltip, which was blocking users from navigating to another page.
https://github.com/user-attachments/assets/cfe7b7ba-7d63-4809-b8d4-15b1c8308940
[MER-4017]: https://eliterate.atlassian.net/browse/MER-4017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4017] Fix Progress Student tooltip

---

assets/src/components/activities/common/delivery/inputs/MathInput.tsx
assets/src/components/activities/multi_input/MultiInputAuthoring.tsx
assets/src/components/activities/multi_input/actions.ts
assets/src/components/activities/short_answer/sections/MathInput.tsx
assets/src/components/common/MathLive.tsx

This change allows multi-input questions using the MathLive keyboard to work with the `submitPerPart` option, which allows answers on practice pages to be automatically submitted on hitting Enter or focusing out of an input control with changed contents. 
The implementation updates the MathLive keyboard wrapper component to process the idiosyncratic MathLive events and translate into events the containing MultiInputDelivery relies on to implement the auto submit behavior.
The update also includes a fix for independent bug [MER-4018](https://eliterate.atlassian.net/browse/MER-4018), installing a property setting to ensure MathLive popup keyboard appears at top of the z-order.
The update includes a correction to MathLive component option handling that obviates the need for an earlier …

[ENHANCEMENT] [MER-3987] [MER-4018] support submitPerPart on math keyboard questions

---

lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex
lib/oli_web/live/common/table/instructor_dashboard_paged_table.ex
test/oli_web/live/gradebook_view_live_test.exs
test/support/test_helpers.ex

[MER-3988](https://eliterate.atlassian.net/browse/MER-3988)
This PR fixes the bug that happened in the `All Grades` view when the table had a lot of content and overflowed outside the border.
The bug was fixed by adding an overflow, which allows to scroll the table horizontally if the content is too long. 
It also adds a custom class to display the scrollbar with a different style than what browsers display. 
https://github.com/user-attachments/assets/d5af8f28-2936-4eff-b3ae-3deba03520fc
[MER-3988]: https://eliterate.atlassian.net/browse/MER-3988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3988] Fix horizontal overflow in all grades view

---

lib/oli/delivery/evaluation/rule.ex
test/oli/delivery/evaluation/rule_eval_test.exs

Torus accepts floating point input without leading zero, e.g. `.333`. However, evaluation code was not properly handling this form when a sign was prefixed, e.g. `-.333`, causing answers of this form to be marked incorrect. Error was caused by a step where code converts the zero-less form to a zero-prefixed form; regexp used there was not allowing for possible sign.
This also adds a few unit tests for this case.

[BUG FIX] [MER-4033] fix evaluation of signed floats without leading zero

---

lib/oli_web/components/layouts/workspace.html.heex
lib/oli_web/live/delivery/student/index_live.ex

[MER-4005](https://eliterate.atlassian.net/browse/MER-4005)
This PR aims to fix two errors encountered: 
1 - Fixes the style of the banner on a student's landing page, on the student's first access to the course. 
2 - Fixes the top navbar when a student is in the main view to choose which course section to enter.  
- Banner before
- Banner after
- Navbar before
- Navbar after
[MER-4005]: https://eliterate.atlassian.net/browse/MER-4005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4005] First access to a course displays malformed landing page

---

assets/src/hooks/scroller.ts
lib/oli/utils.ex
lib/oli_web/components/common.ex
lib/oli_web/components/delivery/utils.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/lesson/components/outline_component.ex
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson/components/outline_component_test.exs

[MER-3884](https://eliterate.atlassian.net/browse/MER-3884)
Re-implement the 'Hide/Show Completed' resources feature in the Learn Live, which used to be on a module level.
1. Hide & Show top-level and completed pages.
https://github.com/user-attachments/assets/cd749cdc-98b4-4b04-a0a5-13ad56d46181
2. Hide & Show completed pages and modules within a Unit (and resources within the module).
https://github.com/user-attachments/assets/67e0b226-a335-485a-a540-89e0ce26ac6c
3. Hide & Show completed modules. Edge case when a completed module is expanded and the toggle button is clicked.
https://github.com/user-attachments/assets/583210cc-c4a6-445f-a29a-ae7104b5759e
[MER-3884]: https://eliterate.atlassian.net/browse/MER-3884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

[FEATURE] [MER-3884] Implement Gallery Item Hide/Show Feature

---

assets/css/app.css
lib/oli_web/live/projects/create_project_modal.ex
test/oli_web/live/workspaces/course_author_test.exs

[MER-3981](https://eliterate.atlassian.net/browse/MER-3981)
This PR fixes the color of the texts in the Create Project modal to make them more readable in dark mode. 
These changes include the color of the placeholder text.
The textarea for adding/editing a bibliography entry has been fixed in this [PR](https://github.com/Simon-Initiative/oli-torus/pull/5212).
- Modal to Create Project before
- Modal to Create Project after
[MER-3981]: https://eliterate.atlassian.net/browse/MER-3981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3981] Illegible text in dark mode

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[MER-3883](https://eliterate.atlassian.net/browse/MER-3883)
This PR implements the new design in the outline view for the learn page. 
Also, a button toggle to show and hide completed pages is added.
These changes use existing logic in the module, so its focused in the figma designs changes.
https://github.com/user-attachments/assets/98924787-487a-4ac2-b0f0-f819a31b8810
[MER-3883]: https://eliterate.atlassian.net/browse/MER-3883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3883] Implement outline metrics

---

assets/src/apps/authoring/components/PropertyEditor/PropertyEditor.tsx
assets/src/apps/authoring/components/PropertyEditor/custom/AdvancedFeedbackNumberRange.tsx
assets/src/apps/authoring/components/PropertyEditor/custom/OptionsCustomErrorFeedbackAuthoring.tsx
assets/src/apps/authoring/components/RightMenu/RightMenu.tsx

Simple authoring had some advance feedback widget where the '`onFocus`' was not handled.

[BUG FIX] [MER-4051] Delete Component window pops up with backspace

---

lib/oli_web/components/delivery/layouts.ex
test/oli_web/live/delivery/student/index_live_test.exs

Removes the assignment link in the nav bar for sections that do not have assignments.
https://github.com/user-attachments/assets/aac17c70-945f-439b-9c3e-dc3c76b133dd
See: https://eliterate.atlassian.net/browse/MER-4022

[ENHANCEMENT] [MER-4022] Do not show Assignments navigation if section has no assignments.

---

assets/src/components/editing/elements/link/LinkModal.tsx
assets/src/components/editing/elements/webpage/WebpageModal.tsx

The attempt to insert either a Link or an embedded (iframed) web page using the option to link to an item in the Media Library was failing, showing an error message “Cannot read properties of null (reading store)" inside the containing modal where the embedded MediaManager should be rendered. The connected MediaManager component was not finding a react-redux store provider within these modal contexts. This change adds code to wrap the component in the needed Provider.

[BUG FIX] [MER-3995] Fix error inserting link or webpage from media library

---

assets/src/apps/bank/ActivityBank.tsx
assets/src/apps/bank/CreateActivity.tsx
assets/src/apps/page-editor/PageEditor.tsx
assets/src/components/activity/InlineActivityEditor.tsx
assets/src/components/resource/editors/ActivityEditor.tsx
assets/src/components/resource/editors/Editors.tsx
assets/src/components/resource/editors/GroupEditor.tsx
assets/src/components/resource/editors/PurposeGroupEditor.tsx
assets/src/components/resource/editors/SurveyEditor.tsx
assets/src/components/resource/editors/createEditor.tsx
assets/src/data/persistence/activity.ts
lib/oli/authoring/editing/activity_editor.ex
lib/oli_web/controllers/api/activity_controller.ex

This adds a button to each activity editor to duplicate the given activity within the activity bank and when editing course pages. Because activity duplication is a form of new activity creation, the duplicate button is enabled within the activity bank whether or not the existing activity is unlocked for editing. Demo (activity bank):
https://github.com/user-attachments/assets/4ffe1039-8f6a-4525-a161-b14ea31df052
This does not implement the success/failure flash messages or the Undo behavior specified in [MER-3360](https://eliterate.atlassian.net/browse/MER-3360). Duplicated activities are inserted on the current pageful at the position of the original with a title of "Original Title (Copy)", so user can see immediately that the operation succeeded. And one can always undo the duplication …

[FEATURE] [MER-3360] [MER-3363] Duplicate activity within activity bank and pages

---

priv/repo/migrations/20240917111312_add_lifecycle_index.exs

https://eliterate.atlassian.net/browse/MER-4090
We need the ability to run the activity_attempts_submitted index before migration to prevent extended downtime and CI disconnect to make the deployment go smoother.
This PR adds the `IF NOT EXISTS` specification to the index creation during migration to prevent the migration from throwing an error when the index was created ahead of time.

[CHORE] [MER-4090] only create activity_attempts_submitted index if it does not already exist

---

assets/src/apps/authoring/Authoring.tsx
assets/src/apps/authoring/AuthoringFlowchartPageEditor.tsx
assets/src/apps/authoring/BottomPanel.tsx
assets/src/apps/authoring/ReadOnlyWarning.tsx
assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx
assets/src/apps/authoring/components/ExpertHeaderNav.tsx
assets/src/apps/authoring/components/Flowchart/FlowchartEditor.tsx
assets/src/apps/authoring/components/SidePanel.tsx
assets/src/stories/advanced-authoring/PropertyPanels.stories.tsx
lib/oli_web/components/layouts/workspace.html.heex
lib/oli_web/live/breadcrumb/breadcrumb_trail_workspace_live.ex

[Link](https://eliterate.atlassian.net/browse/MER-3899) to the ticket
There was no need to add the breadcrumbs in advanced authoring since they were already included in the workspace layout (`lib/oli_web/components/layouts/workspace.html.heex`).
So, the work ended up being adding some margin to different react components to make the breadcrumbs visible.
This PR also includes a minor refactor to`OliWeb.Breadcrumb.BreadcrumbTrailWorkspaceLive`
https://github.com/user-attachments/assets/f1451740-6634-4732-94e6-596dccc66712

[FEATURE] [MER-3899] No breadcrumbs in advanced authoring

---

lib/oli_web/live/delivery/student/prologue_live.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4093) to the ticket
https://github.com/user-attachments/assets/415211d9-495b-4b12-b8db-7a4c1aff6197
https://github.com/user-attachments/assets/3d431adc-4584-4262-b122-28bbc72d2df5
https://github.com/user-attachments/assets/f62f544b-2587-47f0-b137-ceaecb494d55
**co-authored by:** @simonchoxx

[FEATURE] [MER-4093] ExtenD term page cases on prologue

---

lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4095) to the ticket
[MER-4093](https://github.com/Simon-Initiative/oli-torus/pull/5286) should have said: "Assignments should not be auto-submitted if late submission is allowed, **except if there is a time limit**"
https://github.com/user-attachments/assets/293ad64b-0717-430f-8efd-2be8e8d21843
**co-authored**: @simonchoxx 
[MER-4093]: https://eliterate.atlassian.net/browse/MER-4093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4095] Extend page submission term logic

---

lib/oli_web/components/layouts/student_delivery_lesson.html.heex
test/oli_web/live/delivery/student/lesson_live_test.exs
test/oli_web/live/delivery/student/prologue_live_test.exs

[MER-4031](https://eliterate.atlassian.net/browse/MER-4031)
This PR adds an enhancement to not show the AI assistant DOT on scored pages. 
It also hides the assistant DOT in the prologue view of the scored pages.
https://github.com/user-attachments/assets/4415ad86-4f1e-405e-b92c-5accfb868f23
[MER-4031]: https://eliterate.atlassian.net/browse/MER-4031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4031] Dot should not be present on scored pages

---

lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

Ticket: [MER-4099](https://eliterate.atlassian.net/browse/MER-4099)
This PR adds logic to display a page term when a time limit is set, but no due date is specified. The message is as follows:
> You have **X minutes** to complete the assessment. If you exceed this time, it will be marked as late.
It also pluralizes the message when more than 1 minute is specified.
Additionally, it conjugates the verb correctly based on whether the due date has passed.
https://github.com/user-attachments/assets/98782b81-8a93-4433-93bb-3bf654a2cc18
[MER-4099]: https://eliterate.atlassian.net/browse/MER-4099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4099] time limit should always be present on prologue page

---

lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

Ticket: [MER-4101](https://eliterate.atlassian.net/browse/MER-4101)
This PR adds the "Time Limit" page term when its value is different from 0, regardless of other conditions.
https://github.com/user-attachments/assets/692041c7-7d8d-4c6b-82b7-02f3c879a402
[MER-4101]: https://eliterate.atlassian.net/browse/MER-4101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4101] Show the Time Limit page term when is configured

---

lib/oli/delivery/sections/section.ex
priv/repo/migrations/20241209175250_update_agenda_default_to_true.exs
test/oli_web/live/delivery/instructor_dashboard/manage/manage_tab_test.exs
test/oli_web/live/delivery/student/index_live_test.exs

[MER-3752](https://eliterate.atlassian.net/browse/MER-3752)
This PR modifies the default value of the agenda field in the `Section` structure. 
Thus, when a new course section is created, it has by default the option to show the agenda enabled. 
https://github.com/user-attachments/assets/b77dba8e-c0a7-494b-8e26-80d03965e2dd
[MER-3752]: https://eliterate.atlassian.net/browse/MER-3752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3752] Make agenda enabled by default

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[MER-3996](https://eliterate.atlassian.net/browse/MER-3996)
This PR fixes the bug where “0m” was displayed on the module cards for the gallery view on the learn page. 
This happened because it did not take into account if the module had pages with a stipulated duration in minutes. 
Thus, if the pages contained in a module do not have a stipulated duration in minutes, no legend will be shown on the module card. 
https://github.com/user-attachments/assets/af0037ef-3d24-4d3b-9a98-00a4c5b231f7
[MER-3996]: https://eliterate.atlassian.net/browse/MER-3996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3996] Modules displaying 0 minutes

---

assets/src/adaptivity/scripting.ts
assets/src/apps/delivery/components/preview-tools/Inspector.tsx
assets/src/apps/delivery/store/features/attempt/actions/savePart.ts
assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx

Previously, we did not save the variable type received during the handshake with the CAPI component. As a result, in the Inspector preview tool, the variable type was auto-detected based on its value. This approach caused issues with variables of type ENUM, as ENUMs require a dropdown with allowed values to be displayed. Instead, the current implementation incorrectly shows a text input because it was thinking ENUM values as string.
To address this specifically for the preview mode (Inspector tool), I have introduced a new variable, `stage.${partId}.variables.Type`, in the scripting (**`_PREVIEW MODE ONLY & NOT SENT TO SERVER_`**). This variable stores all variables along with their types and allowed values, ensuring correct …

[ENHANCEMENT] [MER-3998] Display Enum CAPI as Dropdowns in Author Preview Tools

---

lib/oli/delivery/sections/certificate.ex
lib/oli/delivery/sections/granted_certificate.ex
lib/oli/delivery/sections/section.ex
lib/oli/utils.ex
priv/repo/migrations/20241203184246_create_certificates_tables.exs
test/oli/delivery/sections/certificate_test.exs
test/oli/delivery/sections/granted_certificate_test.exs
test/support/factory.ex

Ticket: [MER-3790](https://eliterate.atlassian.net/browse/MER-3790)
This PR adds the certificate and granted_certificate models, along with their migrations and Ecto schema.
There is additional work required for [MER-3790](https://eliterate.atlassian.net/browse/MER-3790), but this PR enables progress on other tickets dependent on the database models.
[MER-3790]: https://eliterate.atlassian.net/browse/MER-3790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3790] core schema for certificates

---

lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex

Ticket: [MER-4121](https://eliterate.atlassian.net/browse/MER-4121)
This PR removes the top-level objectives pre-filter. With this change, we now target all objectives.
https://github.com/user-attachments/assets/c5ce00ba-fdd8-4798-b1b6-b72882efd086
[MER-4121]: https://eliterate.atlassian.net/browse/MER-4121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4121] Remove top-level objectives pre-filter

---

lib/oli/publishing/delivery_resolver.ex
lib/oli_web/live/sections/assessment_settings/settings_table.ex
test/oli/publishing/delivery_resolver_test.exs
test/oli_web/live/delivery/instructor_dashboard/scored_activities/scored_activities_tab_test.exs
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

[MER-3122](https://eliterate.atlassian.net/browse/MER-3122)
Fix default sorting on the Assessment Settings table to respect the order of pages in the course.
Fix available dates and due dates sorting.
**Before:**
https://github.com/user-attachments/assets/56dc7dea-a892-46f6-a964-c8147b1f5674
**After:**
https://github.com/user-attachments/assets/9b48c010-a93a-4535-bb65-df88ebecec51
[MER-3122]: https://eliterate.atlassian.net/browse/MER-3122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3122] Assessment Settings Sorting Capability Broken

---

lib/oli/rendering/content/html.ex

Internal page links were not rendered correctly in the case where the project slug was the same as the section slug.  I conjecture that code was using this equality to detect authoring mode, because dummy section slug is set to project slug in that case.  But it can arise in delivery as well, on the first section created with the same title as the authoring project, which is very common in testing, but certainly possible in real courses as well. 
This recodes the logic to simply switch on the mode from the rendering context, which seems like it should be sufficient.

[BUG FIX] [MER-4124] broken internal page links

---

lib/oli/delivery/attempts/page_lifecycle/hierarchy.ex

[MER-4126](https://eliterate.atlassian.net/browse/MER-4126)
This PR aims to fix the retake mode `targeted` for pages that have the `one at a time` display configured.
This already worked correctly with the pages that have the presentation configured as `traditional`.
https://github.com/user-attachments/assets/c70b0317-5bfd-42e4-8684-e868b5781772
[MER-4126]: https://eliterate.atlassian.net/browse/MER-4126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4126] Fix targeted retake one question at a time

---

lib/oli_web/live/delivery/student/lesson/components/one_at_a_time_question.ex

[MER-4120](https://eliterate.atlassian.net/browse/MER-4120)
This PR fixes the bug where the auto submit of a page was not working in case the page has a due date and the presentation was `one at a time`. 
With these changes, even if the page has the presentation as `one at a time` if it has a stipulated due date, it will auto submit when the time limit is reached, as it already happens with pages that have a traditional presentation.
https://github.com/user-attachments/assets/90949bb7-0f0c-4523-b5ce-ca4edfeec997
[MER-4120]: https://eliterate.atlassian.net/browse/MER-4120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4120] One at a time setting can prevent submissions

---

assets/src/components/parts/janus-mcq/McqAuthor.tsx

[BUG FIX] [MER-4102] MCQ options in Advanced Author appear in light gray text by default

---

lib/oli_web/live/workspaces/course_author/curriculum/entry.ex
lib/oli_web/live/workspaces/course_author/editor_live.ex

Ticket: [MER-4119](https://eliterate.atlassian.net/browse/MER-4119)
This PR introduces optimizations for how authors navigate through the curriculum using breadcrumbs. Currently, when an author edits a page, a full page load occurs, which negates the benefits of LiveView. Additionally, the navigation page links (the bottom buttons) have been modified to navigate without performing a full page reload.
[MER-4119]: https://eliterate.atlassian.net/browse/MER-4119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4119] curriculum edit page js dependency optimization

---

assets/src/components/activities/DeliveryElement.ts
assets/src/components/activities/common/hints/delivery/HintsDeliveryConnected.tsx
assets/src/components/activities/directed-discussion/discussion/MockDiscussionDeliveryProvider.tsx
assets/src/components/activities/multiple_choice/MultipleChoiceDelivery.tsx
assets/test/check_all_that_apply/cata_delivery_test.tsx
assets/test/multiple_choice/mc_delivery_test.tsx
assets/test/ordering/ordering_delivery_test.tsx
assets/test/short_answer/short_answer_delivery_test.tsx
lib/oli/delivery/sections/section_resource.ex
lib/oli/delivery/settings.ex
lib/oli/delivery/settings/combined.ex
lib/oli/rendering/activity/html.ex
lib/oli_web/live/sections/assessment_settings/settings_table.ex
lib/oli_web/live/sections/assessment_settings/settings_table_model.ex
priv/repo/migrations/20241216193240_allow_hints_scored_pages.exs
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

[MER-3529](https://eliterate.atlassian.net/browse/MER-3529)
This PR aims to add a new setting for the instructor (to be used from the assessments settings table) to enable or disable the hints functionality on a scored page.
If the hints are enabled, then the student will have access to them when entering a scored page (as well as maintain the ability to use the hints on practice pages). 
By default, this option will be disabled for scored pages. 
https://github.com/user-attachments/assets/e1ff79c4-b908-4f40-8d49-0c3d77a6a786
[MER-3529]: https://eliterate.atlassian.net/browse/MER-3529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3529] Hints should be functional on scored pages

---

lib/oli_web/controllers/legacy_superactivity_controller.ex

On the migrated stattutor superactivity in the Alvin statistics course, instructors reviewing student attempts were seeing the problem load successfully, but the student's saved solution state was not being restored, preventing them from seeing what the student had entered. This apparently stemmed from a general problem in the superactivity support: Tutor-saved state files used to restore state are fetched (in part) by user id, and the files were being fetched using the id of the currently logged in user. So, when instructors were current logged in users, the student's solution files were not being found. and no saved file info was included in the BeginSession command response sent to the client. Because of this, the client behaved as if there was no saved solution file to restore. 
This …

[BUG FIX] [MER-4122] Restore superactivity state on instructor review of student solution

---

lib/oli_web/controllers/legacy_superactivity_controller.ex
lib/oli_web/live/sections/overview_view.ex

The Manage Sections view was including an admin-only button labelled “Manage Snapshots” refererencing OliWeb.Snapshots.SnapshotsView, which does not exist in the checked-in codebase, causing a runtime error when admins attempt to load this page. Looks like this represents partial work in progress inadvertently committed along with another change. This removes that button.

[CHORE] [MER-4125] remove failing SnapshotsView reference from manage section view

---

lib/oli_web/components/delivery/content/content.ex
test/oli_web/live/delivery/instructor_dashboard/insights/content_tab_test.exs

[MER-4123](https://eliterate.atlassian.net/browse/MER-4123)
This PR solves the existing problem of the filters in the `content` tab of the `instructor dashboard` whereby if there were no units or modules in the course content, but only pages without containers, the filters did not work correctly. 
In addition, if the case happens that there are only pages in the course content, without containers, the buttons for filtering by modules or units are disabled.
https://github.com/user-attachments/assets/fa914021-8489-4590-9c44-6cce7c6bbb2e
[MER-4123]: https://eliterate.atlassian.net/browse/MER-4123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4123] Fix high progress low proficiency filter

---

lib/oli_web/components/delivery/content/content.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex

[MER-4123](https://eliterate.atlassian.net/browse/MER-4123)
This PR adjusts some corrections in the code to correctly obtain the metrics when there are no containers in the content of a course in the `content` tab of the `instructor dashboard`.
https://github.com/user-attachments/assets/d430ed3a-ad20-4a64-b153-c7ba4d39487d
[MER-4123]: https://eliterate.atlassian.net/browse/MER-4123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4123] Fix high progress low proficiency filter - rework

---

lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex

Fixed boundary miscalculation of Proficiency Distribution tooltip and increased stacking context for proper visibility.
See: https://eliterate.atlassian.net/browse/MER-4127
https://github.com/user-attachments/assets/0c688b09-b403-4249-ab5a-a55085d347e2

[BUG FIX] [MER-4127] Fix Learning Objectives Proficiency Distribution Hover Boundary

---

lib/oli/delivery/sections/blueprint.ex

[MER-4011](https://eliterate.atlassian.net/browse/MER-4011)
This PR will try to fix the bug that happens when trying to create a course section from a given project or product. 
This error occurs in some specific cases. 
The bug fix introduced in this PR is based on and addresses what the AppSignal logs show about the error itself. 
[MER-4011]: https://eliterate.atlassian.net/browse/MER-4011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4011] Real chem course section creation loads indefinitely

---

lib/oli/accounts.ex
lib/oli/accounts/schemas/user.ex
lib/oli_web/controllers/lti_controller.ex
mix.exs
priv/repo/migrations/20250104141507_add_institution_to_user.exs
test/oli/lti_accounts_test.exs

This PR does two main things:
1. Wraps the relevant code within `LtiController.launch` in a DB transaction. 
2. Introduces a new `lti_institution_id` field to the `User` schema.  This field - for LMS users only - gets set with the institution id during LMS user account creation.     We then leverage that field to correctly identify an existing user on future launches - breaking the need to rely on enrollment records.    NOTE: the existing enrollment record check is left in as a secondary check for backward compatibility reasons (because all existing Users have `lti_institution_id` as `nil`)
3. Removes a `status = :active` clause from a function which retrieves User roles by section slug.  That clause should have NEVER been included.  This was something that I happened to notice.  
What …

[BUG FIX] [MER-4138] Fix launch issues

---

lib/oli/accounts/schemas/user.ex
lib/oli/utils.ex
lib/oli_web/live/delivery/student/assignments_live.ex
lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/prologue_live.ex
lib/oli_web/pow/user_context.ex
test/oli/lti_accounts_test.exs

This PR removes `maybe_create_unique_sub` entirely and instead explicitly sets a sub during independent account creation. 
Also fixes the true root cause: the exclusion of the `:sub` field from the User assigns in various LiveViews
Peripheral change to update the conflicting name of a test module introduced during 29.3

[BUG FIX] [MER-4138] Fix maybe create sub

---

lib/oli_web/live/admin/restore_user_progress.ex
lib/oli_web/router.ex

This introduces a (hidden) admin tool to migrate progress forward to the student's TRUE account (the one most recently created).  It operates one student at a time, via the email address of the user's accounts.
The logic for how this is done is well documented in the comments in the code.  
I plan to execute this one student at a time, while looking at the DB records in another window, and verify things as I go.

[FEATURE] [MER-4139] Restore user progress tool

---

lib/oli_web/live/new_course/new_course.ex

[MER-4141](https://eliterate.atlassian.net/browse/MER-4141)
This is a small fix to ensure that instructors are able to create course sections from a base project.
Apparently this bug is happening in Tokamak.
[MER-4141]: https://eliterate.atlassian.net/browse/MER-4141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4141] Course sections cannot be created

---

assets/src/components/activities/ordering/OrderingAuthoring.tsx
assets/src/data/activities/model/responses.ts
assets/src/data/activities/model/rules.ts

Migration tool output did not fill in the targeted feedback map for ordering questions (a bug), so for migrated courses, any targeted feedback included on ordering questions was not displayed -- so not editable or deletable -- in torus authoring. This was particularly a problem for Evidence Based Management where some ordering questions included auto-generated targeted feedbacks for every possible ordering response. In this case, the invisible targeted feedbacks prevented the catchall incorrect feedback from ever being delivered, making it appear that attempted edits to the incorrect feedback were not taking effect.
This change has torus authoring work around the migration error by filling in the targeted feedback map from the response list at runtime if needed. This repair is done at the …

[ENHANCEMENT] [MER-4142] construct targeted feedback map for migrated ordering questions that lack it

---

lib/oli_web/controllers/invite_controller.ex
lib/oli_web/router.ex

[Link](https://eliterate.atlassian.net/browse/MER-4068) to the ticket
As [commented on MER-3893](https://eliterate.atlassian.net/browse/MER-3893?focusedCommentId=25179), I forgot to use an absolute URL instead of a relative URL for the email invitation link. This PR fixes that error

[FEATURE] [MER-4068] Reimplement user's invite - part 2

---

lib/oli/delivery/granted_certificates.ex
lib/oli/delivery/sections/granted_certificate.ex
priv/repo/migrations/20250108052504_add_url_to_granted_certificates.exs
test/oli/delivery/granted_certificates_test.exs
test/support/factory.ex

Wrapper function that calls the AWS Lambda function that given an HTML generates a PDF and stores it in S3 so later it can be viewed by anyone that wants to check if a given certification has been granted.

 [FEATURE] [MER-3794] Granted Certificates PDF generation via AWS Lambda

---

lib/oli_web/router.ex

Since recent change, superactivity support api calls were failing due to unset `current_user` assign. This changes the route to use the `:api` pipeline which will set that, and seems appropriate since these are api calls.

[BUG FIX] [MER-4154] Ensure current_user set on superactivity support API calls

---

assets/src/components/parts/janus-capi-iframe/ExternalActivity.tsx

Hey @bsparks, could you please look at the PR? Thanks.
The state of these SIMs is saved within the SIM itself and is linked to the repository: `git@github.com:SmartSparrow/componentLibrary-Redux.git#~2`.
During my investigation, I discovered that the state is maintained at the lesson ID level. This means that when a student restarts a lesson, the SIM retrieves the state for that lesson rather than resetting itself.
I also found that appending a random number to the lesson ID causes the SIM to reset, as it perceives it as a new lesson.
To address this, we introduced an iframe property called `IFRAME_randomizeLessonId`, similar to `IFRAME_frameVisible`. In authoring, if this property is set to `true`, we append a random number to the lesson ID. This ensures that when a new attempt is …

[BUG FIX] [MER-4131] Dig into chem labs simulations

---

assets/src/apps/authoring/components/AdaptivityEditor/InitStateEditor.tsx

The `init state` has it's own component so this change got missed it.

[BUG FIX] [MER-4153] Backspace Issue in Advanced Author (Initial State)

---

lib/oli_web/user_auth.ex

Ticket: [MER-4145](https://eliterate.atlassian.net/browse/MER-4145)
The issue occurred when a student joined a course through an invitation link. The system renewed the student session but did not preserve the `datashop_session_id`. As a result, when the student navigated to a page that required this key—such as in the case of hints, where it is needed to insert a part_attempt record during an assessment—the record became corrupted due to the `datashop_session_id` being `nil`.
Database queries from Tokamak indicate that the first issue was encountered on 2024-12-19. There are 8,621 part_attempts records with `nil` values. These records are corrupted and need to be addressed appropriately in another ticket.
[MER-4145]: https://eliterate.atlassian.net/browse/MER-4145?atlOrigin=eyJpIjoiNWRkNT …

[BUG FIX] [MER-4145] Add datashop_session_id to renew_session

---

lib/oli_web/controllers/delivery_controller.ex

This removes the "student" field, which was a concatenation of the first and last names, and replaces it with the database id, the user `:sub`, email and last and first names (as separate fields)
Tested locally and it produces the desired .csv:
```
student_id,student_lms_id,student_family_name,student_given_name,student_email,New Assessment,New Assessment
34,82d1fb04-077c-4b93-84af-94fa26a74153,,,adriel_leuschke_33@platform.example.edu,Not finished,Not finished
87,47fe81d3-9e1d-4014-99aa-0ba8159e10fb,,,darian_wuckert_dds_86@platform.example.edu,Not finished,Not finished
89,217d5193-1b1b-4f11-b1c5-c72247027a2a,,,malinda_lehner_88@platform.example.edu,Not finished,Not finished
```

[ENHANCEMENT] [MER-4184] Add user detail fields to grades CSV download

---

lib/oli/delivery/sections/updates.ex
lib/oli_web/live/delivery/student_onboarding/survey.ex
lib/oli_web/plugs/force_required_survey.ex
test/oli/delivery/sections/ensure_resource_test.exs

The core issue here is that the code that applies new publication updates was incorrectly "culling" the survey resource from a course section.  Function `Oli.Delivery.Sections.determine_unreachable_pages/3` takes as its second argument the list of the hierarchy resource ids and a list of page links and determines reachability of all other pages.  Unreachable pages then get removed from the section.   This means then that there is no SectionResource record for the survey, which breaks the display of the Survey from the onboarding wizard and breaks correct functioning of the `Oli.Plugs.ForceRequiredSurvey` plug. 
The problem here was how the original impl attempted to exempt out and keep the required survey from being culled. It simply included the survey page id in the list of hiearchy …

[BUG FIX] [MER-4178] [MER-4186] Fix required survey issues

---

.gitignore
lib/oli/delivery/attempts/page_lifecycle/ungraded.ex
lib/oli/delivery/metrics.ex
lib/oli/resources.ex
lib/oli/resources/revision.ex
lib/oli_web/live/curriculum/entries/options_modal.ex
priv/repo/migrations/20250113190620_add_full_progress_pct.exs
temp_init_file

This adds a new author facing feature, allowing the author some control over the proportion of activities that must be attempted on a page in order to achieve 100% progress (i.e., for the student to then see the "green check" in the Learn view)
We add a new `:full_progress_pct` field to `Revision`, which defaults to the integer value of `100`.  Authors can change this setting in the page options modal from Curriculum or All Pages view. 
This setting is then used in two places during delivery:
1. When a new practice page attempt is started:  If this value is set to `0`, regardless of the number of scoreable activities that are on the page, the system marks the page progress as 100% completed. 
2. When a student attempts an activity: The `:full_progress_pct` value for the revision TIED TO …

[FEATURE] [MER-4150] Page progress setting

---

lib/oli_web/live/delivery/student/learn_live.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[MER-4080](https://eliterate.atlassian.net/browse/MER-4080)
This PR fixes the bug where the unit navigation arrows inside the `Learn Page` were not displayed correctly. 
If a student was in `Gallery` view, switched to `Outline` view and switched back to `Gallery` view, the unit navigation arrows were not displayed as they should be. 
I have tested the bug in `Tokamak` to rule out that there was also an excessive delay in displaying the navigation arrows when entering the view. The navigation arrows seem to be displaying normally when entering the view.
- Bug fixed
https://github.com/user-attachments/assets/c0a3e1c6-8147-4ec7-9e6f-55cc6fb12fb4
- Tokamak before this PR
https://github.com/user-attachments/assets/6c08abc0-f039-4428-bee4-dfc7eea3d296
[MER-4080]: …

[BUG FIX] [MER-4080] Fix learn page navigation arrows

---

lib/oli/activities/reports/providers/OliLikert.ex

This PR reverts the Likert report back to how it looked in the previous PR, which closely matches what legacy displays. See the recording in the PR [https://github.com/Simon-Initiative/oli-torus/pull/4862](https://github.com/Simon-Initiative/oli-torus/pull/4862) for details

[BUG FIX] [MER-4185] Reverts the survey tool report to match legacy display 

---

config/runtime.exs
lib/oli_web/pow/pow_helpers.ex

Exposes Pow `session_ttl_renewal` and `credentials_cache_store` ttl as configurable environment variables.

[BUG FIX] [MER-4203] expose session_ttl_renewal and credentials_cache_store ttl as configurable env vars

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/delivery/user_account.ex
lib/oli_web/components/header.ex
lib/oli_web/live/delivery/student_dashboard/components/helpers.ex
lib/oli_web/live/user_confirmation_live.ex
lib/oli_web/live/user_registration_live.ex
lib/oli_web/router.ex
lib/oli_web/templates/layout/_workspace_header.html.heex
lib/oli_web/user_auth.ex

https://eliterate.atlassian.net/browse/MER-4169
Fixes 2 issues related to guest menu links:
1. "Leave Guest Account" link was missing the "DELETE" HTTP method, resulting in a 404 error
2. "Create account or sign in" was not allowing "logged in" users, including guests, to access the registration or login pages. Moreover, the section parameter was not properly being handed off to the subsequent steps to allow a guest who just created an account to return directly to the section they were in when they clicked the link.

[BUG FIX] [MER-4169] Fix guest menu links

---

assets/src/apps/Components.tsx
assets/src/apps/app.tsx
assets/src/components/editing/elements/audio/AudioSettings.tsx
assets/src/components/editing/elements/video/VideoSettings.tsx
lib/oli_web/components/layouts/workspace.html.heex
lib/oli_web/live/workspaces/course_author/activity_bank_live.ex
lib/oli_web/live/workspaces/course_author/bibliography_live.ex
lib/oli_web/templates/layout/workspace.html.heex
test/oli_web/live/workspaces/course_author/activity_bank_live_test.exs

https://eliterate.atlassian.net/browse/MER-4075
This PR fixes an issue where the Video and Audio settings modals weren't appearing in the basic page editor. I originally fixed the issue by replacing the `useDispatcher` approach with `window.oliDispatch`, though this was only a bandaid and I then noticed once modals were working that some functionality within the modals were still broken, as seen in the screen capture below.
The root cause of the issue was the missing `<ModalDisplay />` component that should be added when client components and apps get registered. This was previously removed to fix a 'double modal' effect in certain views, specifically the Bibliography view. So readding this also reintroduced the double modal issue which needed to be fixed by removing the duplicate …

[BUG FIX] [MER-4075] cant access video settings

---

assets/src/components/activities/common/triggers/TriggerAuthoring.tsx

The AI icon was not appearing on the activity authoring tab because the URL used by the code to load AI icon does not exactly match case of the file icon-AI.svg. This was missed because it worked in local dev environment on MacOS, apparently case-insensitive, but does not work on our servers, apparently case-sensitive. Live and learn.

[BUG FIX] [MER-4216] correct case in AI icon url

---

config/config.exs
config/runtime.exs

Continuation of "fix dataset problems". 
This fixes the actual issue with the oban cron job not running.  We have to enable it, of course, in `runtime.exs`

[ENHANCEMENT] [MER-4127] Update runtime oban settings

---

assets/src/apps/authoring/components/EditingCanvas/EditingCanvas.tsx

This PR is based on the changes done in the https://github.com/Simon-Initiative/oli-torus/pull/5351.
Currently, when user checks only the "CenterPoint" check box 'show-grid show-center' class was getting added instead of only 'show-center'.

[BUG FIX] [MER-3749] Grid and Guide Options for Simple & Advanced Author Interface

---

assets/src/apps/delivery/store/features/attempt/actions/savePart.ts

Hey @bsparks, could you please look at this PR? Thanks
I have updated the condition (`to make sure that the partId variable is used in _PREVIEW MODE ONLY & NOT SENT TO SERVER_`) to resolve the earlier issue where this was causing the part responses not to be saved on server hence resume mode and review mode was not working.
I have tested it with the preview mode / Resume mode / Review Mode and part responses are getting saved and are pre-filled in review mode.
Comment from the original PR where the changes were made (just for reference)->  https://github.com/Simon-Initiative/oli-torus/pull/5282
Previously, we did not save the variable type received during the handshake with the CAPI component. As a result, in the Inspector preview tool, the variable type was auto-detected based on its …

[BUG FIX] [MER-4131] | Dig into chem labs simulations

---

lib/oli_web/components/layouts/workspace.html.heex
lib/oli_web/templates/layout/app.html.eex
lib/oli_web/templates/layout/default.html.heex
lib/oli_web/templates/layout/live.html.heex

https://eliterate.atlassian.net/jira/software/c/projects/MER/boards/2?selectedIssue=MER-4170
This PR addresses an issue where, when displaying alerts in a couple of different parts of the system, they either push content when they shouldn’t or cover up content that might confuse users.

[ENHANCEMENT] [MER-4170] Updates flash message rendering

---

lib/oli/authoring/collaborators.ex

[Link](https://eliterate.atlassian.net/browse/MER-4132?focusedCommentId=25314) to the comment in the ticket
In [this commit](https://github.com/Simon-Initiative/oli-torus/pull/5337/commits/ac5a8a0642046d5d2036b708663a32368c39a4ad) of the previous PR I accidentally wrote "users" instead of "collaborators" when implementing the `url()` function.
This error caused that the email invitation pointed to the users liveview instead of the collaborators one, which caused we ended up looking for the token in the `users_token` table instead of doing it in the `authors_token` table.
Since the token was not found, the liveview returned the "This invitation has expired or does not exist" message.

[BUG FIX] [MER-4132] Reimplement authors invite functionality - part 2

---

lib/oli/analytics/datasets/emr_serverless.ex

This PR adds the missing `|> to_str` to turn the list of sub types into a comma separated string, suitable as an EMR command line argument value. 
Without this, many of the jobs are return zero results - due to no matching event subtypes.

[ENHANCEMENT] [MER-4217] fix sub type concat

---

lib/oli/delivery/sections/certificate.ex
lib/oli_web/live/certificates/certificate_settings_component.ex
test/oli/delivery/sections/certificate_test.exs
test/oli/interop/export_test.exs
test/oli_web/live/certificates/certificate_settings_component_test.exs

[MER-4085](https://eliterate.atlassian.net/browse/MER-4085)
A second version of the Thresholds Tab for handling the Certificate Settings (continuation of https://github.com/Simon-Initiative/oli-torus/pull/5365) includes improvements and small fixes.
- Add default values for the Thresholds form.
- Improve error handling when no scored pages are selected for the certificate.
- Styling fixes (on the percentage symbol when there is an error)
https://github.com/user-attachments/assets/64d29d7c-2d6f-4af3-a0dc-b6f65e3c829e
[MER-4085]: https://eliterate.atlassian.net/browse/MER-4085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4085] Certificates Thresholds Tab Improvements

---

lib/oli/authoring/course.ex

[Link](https://eliterate.atlassian.net/browse/MER-4132?focusedCommentId=25539) to the comment in the ticket
When an author accepts a collaborator invitation, the accepted project is not listed in the "Course Author" workspace. So, the collaborator could access the project only by the email invitation link or by hardcoding the URL.
The query fetching all the author's projects (as an owner or as a collaborator) incorrectly checked the AuthorProject `status` and `author_id` on the owner binding instead of doing it on the collaborator binding.
Note that the project is not immediately listed after the invitation was sent. Only after the collaborator accepts the invitation the corresponding project gets listed.
https://github.com/user-attachments/assets/cdd42cb6-bc55-4485-9660-af7364c3df1f

[BUG FIX] [MER-4132] Reimplement authors invite functionality - part 3

---

config/config.exs
config/dev.exs
lib/oli/accounts/schemas/author.ex
lib/oli/assent_auth.ex
lib/oli/assent_auth/author_assent_auth.ex
lib/oli/assent_auth/user_assent_auth.ex
lib/oli/utils.ex
lib/oli_web/common/assent_auth_web.ex
lib/oli_web/controllers/author_authorization_controller.ex
lib/oli_web/controllers/user_authorization_controller.ex
test/oli_web/common/assent_auth_web_test.exs

https://eliterate.atlassian.net/browse/MER-4219
Fixes an issue where OAuth social login may result in infinite confirmation step loop.
**Cause**
The issue identified was that if an existing OAuth social login account was never confirmed, then subsequent logins would never update this field and the user would be stuck in an infinite "confirm email" loop.
**Fix**
The fix here is to actually update user details on every OAuth flow login so that the email will be automatically confirmed if `email_verified: true` is passed along. This has the additional benefit of keeping other user details up to date such as name and profile picture. A step was also added here to properly handle the case where `email_verified: false` is passed in, in which case a confirmation email is automatically sent, …

[BUG FIX] [MER-4219] OAuth google login may result in infinite confirm email step

---

lib/oli/delivery/certificates/certificate_renderer.ex
lib/oli/delivery/sections/certificate.ex
lib/oli_web/live/certificates/certificate_settings_live.ex
lib/oli_web/live/certificates/components/design_tab.ex
priv/repo/migrations/20250131002210_certificates_modify_logos_to_bytea.exs
test/oli/delivery/certificates/certificate_renderer_test.exs
test/oli_web/live/certificates/components/design_tab_test.exs

See: https://eliterate.atlassian.net/browse/MER-4087 and https://eliterate.atlassian.net/browse/MER-3793
Implement the Design tab where the author will input the values needed for generating certificates and preview them.
There are 2 differences with the Figma design:
- There are simple buttons to navigate the different certificate previews instead of chevrons and a carousel style (This will be implemented in another PR)
- In order to be able to have access to the uploaded images, the form had to be submitted, that is why there is only one button "Save Design" instead of two ("Preview" and "Save Design")
https://github.com/user-attachments/assets/778d7933-c300-47e8-a93e-dc4601c5a20e

[FEATURE] [MER-4087] Certificates Design and Preview Tab

---

lib/oli/delivery/attempts/core.ex
lib/oli_web/live/common/utils.ex
lib/oli_web/live/delivery/student/prologue_live.ex
lib/oli_web/live/progress/page_attempt_summary.ex
lib/oli_web/live/progress/student_resource_view.ex
test/oli_web/live/delivery/student/prologue_live_test.exs
test/oli_web/live/progress/page_attempt_summary_test.exs
test/oli_web/live/progress/student_resource_view_live_test.exs

[MER-3777](https://eliterate.atlassian.net/browse/MER-3777)
This PR aims to show the feedback that an instructor gives to a student if the activity that the student solves is set to be manually evaluated. 
This implementation works for both basic and adaptive pages.
The feedback that the instructor can give will be displayed in two places:
- For the student, in the prologue view of the attempts the student made for a given page.
- For the instructor, in the view showing the attempts a student made on a given page.
https://github.com/user-attachments/assets/655c8a31-a5dc-43bd-a45a-1af9f1ed69f9
[MER-3777]: https://eliterate.atlassian.net/browse/MER-3777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3777] Cannot see comments from manually graded adaptive assignments

---

lib/oli/delivery/sections.ex
test/oli/delivery/sections_test.exs
test/oli_web/live/delivery/student/explorations_live_test.exs

[MER-4191](https://eliterate.atlassian.net/browse/MER-4191)
This PR addresses a bug where exploration purpose pages that are not contained within a Unit or Module type container (orphaned pages) were not displayed in the Explorations tab.
**Root Cause**
The issue was caused by incorrectly retrieving the hierarchy data to display exploration pages. Previously, we were using the function `Hierarchy.flatten`, which only considers pages inside Unit or Module type containers. This approach overlooked pages that are directly attached to the root container, leading to them not being displayed in the Explorations tab.
**Fix**
To ensure that all exploration purpose pages are correctly included, we replaced `Hierarchy.flatten` with `Hierarchy.flatten_hierarchy`. Unlike the previous function, …

[BUG FIX] [MER-4191] Exploration pages dont display in explorations tab

---

lib/oli/analytics/datasets.ex
lib/oli/analytics/datasets/emr_serverless.ex
lib/oli/analytics/datasets/job_config.ex
lib/oli/analytics/datasets/utils.ex
lib/oli_web/live/workspaces/course_author/create_job_live.ex
test/oli/analytics/datasets_test.exs

This PR adds a new option for dataset job creation - whether to anonymize the student identifiers.  If anonymize is `true` (which is the default), datasets will continue to use opaque database ids for student identifiers.  When set to `false`, the dataset will use the student email address.  
In the case where there is no email address (e.g. for a guest user), the dataset falls back to using the database id.  
This change required that all jobs (not just Datashop jobs, as previously implemented) generate and have access to "lookup data".  This lookup data has been extended to include the mapping of database id to user email address.

[ENHANCEMENT] [MER-4250] Anonymous option

---

lib/oli/accounts.ex
lib/oli/accounts/schemas/user.ex
lib/oli/lti/lti_params.ex
lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/live/new_course/new_course.ex
lib/oli_web/live/new_course/select_source.ex
test/oli/delivery/sections/ensure_resource_test.exs

https://eliterate.atlassian.net/browse/MER-4231
Fixes an issue related to the LTI launch issue where the system was using the wrong LTIParams for a user, resulting in a previous/incorrect section being loaded.
The underlying issue here is that the relationship for user LTI params was specified as a `has_one`, however a user can have multiple associated params records. It seems that by preloading the LTI params, we had no control over which record is loaded (I assume it is the first one returned ordered by the database id, which would result in the first/oldest section a user ever launched into).
The fix here updates the relationship to be more accurately specified as a `has_many` and adds a function to load the latest LTI launch params ordered by the `updated_at` field, which are then …

[BUG FIX] [MER-4231] LTI course sections are incorrectly automatically created

---

cloud/generate-pdf-certificate/lambda_function.py
config/runtime.exs
lib/oli/delivery/certificates/certificate_renderer.ex
lib/oli/delivery/granted_certificates.ex
lib/oli_web/controllers/certificate_controller.ex
lib/oli_web/router.ex
lib/oli_web/templates/certificate/index.html.eex
lib/oli_web/templates/certificate/show.html.eex
lib/oli_web/views/certificate_view.ex
oli.example.env
test/oli/delivery/certificates/certificate_renderer_test.exs
test/oli/delivery/granted_certificates_test.exs
test/oli_web/controllers/certificate_controller_test.exs

Implement page for verification of granted certificates
Changes:
- Add new endpoint `GET /certificates/` for searching a certificate by its ID (guid)
- Add new endpoint `POST /certificates/verify` for veryfing if the certificate is earned and if so, display it on the browser
- **cloud/generate-pdf-certificate/lambda_function.py**:
- Store certificate in S3 so it is served with `Content-Type: 'application/pdf'`
- **lib/oli/delivery/certificates/certificate_renderer.ex**: 
- `render/1 `now allows to pass a `GrantedCertificate` struct.
- Use `DejaVu Serif` if available, if not `Times New Roman` for the title
- **lib/oli/delivery/granted_certificates.ex**:
- Add `get_granted_certificate_by_guid/1` function
- Rely on `CertificateRenderer.render/1` for generating the certificate html in …

[FEATURE] [MER-3809] Certificate Verification

---

assets/src/components/parts/janus-image/ImageAuthor.tsx

The behavior is coming due to the changes made for [Image component has fixed aspect ratio based on image dimensions](https://eliterate.atlassian.net/browse/MER-3418). 
With this PR, I am making sure that we only adjust the aspect ratio changes if he `lockAspectRatio` property is set to true else do not adjust the aspect ratio. This property was never used anywhere so I didn't know what this was really meant for.

[BUG FIX] [MER-4254] Image Component height repopulates with old numbers

---

assets/src/phoenix/activity_bridge.ts
lib/oli/delivery/attempts/activity_lifecycle.ex
lib/oli_web/controllers/api/attempt_controller.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/prologue_live.ex
lib/oli_web/router.ex
test/oli_web/controllers/api/attempt_controller_test.exs
test/oli_web/live/delivery/student/prologue_live_test.exs

https://eliterate.atlassian.net/browse/MER-4252
https://eliterate.atlassian.net/browse/MER-4255
This restores some previously removed changes which allow basic page assessments to be open in multiple browser windows and still work correctly.
The fix here follows the technical notes in the ticket by adding separate endpoints to save activity and part attempts for basic pages. These new endpoints, appended with `/active` are a slight variation of the original endpoints (which are still used by the adaptive player) and will only consider a currently active attempt, otherwise will return an error.
It also fixes an issue related to https://eliterate.atlassian.net/browse/MER-3777 that was blocking testing this functionality for basic pages. The issue here was that this logic was only intended …

[BUG FIX] [MER-4252] [MER-4255] restore basic page mutli tab with separate endpoint

---

lib/oli/delivery/sections/section_resource_depot.ex

This PR fixes a subtle problem in the way that the original code was allowing an update to the `SectionResourceDepot`.  The code was directly updating the ETS table - which works fine on single node setups, but which will fail on multi-node.
Instead, we have to use the `DepotCoordinator.update_all/2` - which (through delegation to the `DistributedDepotCoordinator` impl on multi-node setups) will broadcast a message to the depots in all nodes in the cluster telling them to update this entry in their cache.
Without this, we would have seen:
1. Instructor changes some setting for an assessment
2. Only the local node Depot is updated
3. Processes running on the other node will continue to pull stale section resource records due to this cache coherence issue

[BUG FIX] [MER-4291] Fix cache coherence issue caused by Assessment Settings update

---

lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

This PR adjusts the message that students see on the prologue page when Late Submit is set to Allow and there is no time limit.  It that case, we instead tell them " If you submit after the due date, it will be marked late."

[BUG FIX] [MER-4212] Adjust late message

---

lib/oli_web/router.ex
lib/oli_web/user_auth.ex
test/oli_web/user_auth_test.exs

This PR fixes an issue where students enrolling/accessing an independent section where the "Omit email verification" setting is checked were still being prompted to confirm their email.
The issue was simply that this feature was not re-implemented when we migrated away from Pow auth. It is now included.
There are some strange quirks with this feature that probably existed before the Pow migration, specifically when a user/student tries to access any route that doesn't require a section, including the Edit Account screen. Since no section is loaded the system cannot identify that a user should have access without requiring email verification, therefore as soon as a student in this mode steps outside of the the section view, they are required …

[BUG FIX] [MER-4243] fix omit email verification

---

assets/src/apps/authoring/store/groups/layouts/deck/actions/updateActivityRules.ts

Hey @bsparks, could you take a look at the PR? Thanks!  
After an adaptive page is published, if the author opens the lesson in edit mode without making any changes and then attempts to publish again, a list of changes always appears.  
When multiple trap states contain the same variable, the `conditionWithExpression` array ends up with duplicate entries for each trap state.  
Example:  
```js
conditionWithExpression: [
"stage.HypothesisReflect.selectedChoice",
"stage.HypothesisReflect.selectedChoice",
"stage.HypothesisReflect.selectedChoice",
"stage.HypothesisReflect.selectedChoice",
"stage.HypothesisReflect.selectedChoice"
]
```  
However, the conditionsRequiredEvaluation variable had unique conditions like this
```js
conditionsRequiredEvaluation: …
```

[BUG FIX] [MER-4288] Adaptive page lessons always show edits to publish

---

lib/oli_web/templates/certificate/index.html.eex

So it follows the Figma Design:

[ENHANCEMENT] [MER-3809] Certificate Verification: placeholder text white

---

assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts

This issue is coming because of the changes made in https://github.com/Simon-Initiative/oli-torus/pull/5307.
The '`session.attemptNumber`' variable should always increment even though the `attempt?.hasMoreAttempts` is false.

[BUG FIX] [MER-4299] session.attemptNumber not increasing past 5 in delivery - Advanced Author

---

lib/oli_web/live/delivery/student_onboarding/wizard.ex

This PR simply removes the suppression of the scrollbar - allowing a student to scroll with a "click and drag" of their mouse.

[BUG FIX] [MER-4247] Render the scrollbar in onboarding wizard

---

lib/oli_web/plugs/enforce_paywall.ex
lib/oli_web/plugs/ensure_user_section_visit.ex
lib/oli_web/plugs/require_enrollment.ex
lib/oli_web/router.ex
test/oli_web/controllers/page_delivery_controller_test.exs
test/oli_web/live/collaboration_live_test.exs
test/oli_web/live/delivery/student/assignments_live_test.exs
test/oli_web/live/delivery/student/discussions_live_test.exs
test/oli_web/live/delivery/student/explorations_live_test.exs
test/oli_web/live/delivery/student/index_live_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs
test/oli_web/live/delivery/student/prologue_live_test.exs
test/oli_web/live/delivery/student/review_live_test.exs
test/oli_web/live/delivery/student/schedule_live_test.exs
test/oli_web/plugs/ensure_user_section_visit_test.exs

https://eliterate.atlassian.net/browse/MER-4259
When using a join link for a course section, a user was prompted to sign in then redirected to an "Unauthorized" page after being authenticated.
The issue identified here was some intertwined logic in the `OliWeb.Plugs.EnsureUserSectionVisit` plug. The original intention of this plug was to maintain a key in the user session that indicated whether a user has already visited a section or not in order to efficiently determine whether or not to show the welcome wizard. Though it appears this plug was also being used to verify user enrollment in the cases that `EnforceEnrollAndPaywall` didn't cover, specifically cases where there is no paywall required for a section. This plug was not considering the case where a user tries to access a course …

[BUG FIX] [MER-4259] fix an issue where user is redirected to unauthorized after login

---

lib/oli_web/live/users/invitations/users_invite_view.ex
test/oli_web/live/users/invitations/users_invite_view_test.exs

This PR fixes and issue where the student invitation process will not allow a student account created via social login to complete accepting an invitation to a course. It erroneously lands the student on a “create account” page after they have accepted the invitation

[BUG FIX] [MER-4298] Fixes social login account course invite bug

---

lib/oli/conversation/triggers.ex
lib/oli_web/live/dialogue/window_live.ex
test/oli/conversation/triggers_test.exs

Hint requesting wasn't working when Trigger points feature was being developed, due to a datashop session id issue.  This PR fixes problems with hint triggers that now are visible. 
It also adjusts the styling and position of the Trigger "teaser" window

[FEATURE] [MER-4039] Fix hint triggers and adjust teaser window styling

---

lib/oli_web/live/sections/assessment_settings/settings_live.ex
lib/oli_web/live/sections/assessment_settings/settings_table.ex
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

https://eliterate.atlassian.net/browse/MER-4262
Fixes an issue where when logged in as an admin, the assessment settings page throws a 500 error.
The issue was caused by the result user of `Mount.for` in `SettingsLive` overwriting the `current_user` assigns with an Author (when logged in admin account). This was causing some of the UserAuth logic to break.
This was originally being worked on as part of MER-4262, but since there is a separate ticket targeted for this specific issue I am submitting this fix for MER-4262 and any additional work done for MER-4262 will be tracked by that Jira ticket and completed with another PR.

[BUG FIX] [MER-4262] 500 internal server error when accessing assessment settings

---

lib/oli/delivery/certificates.ex
lib/oli_web/live/delivery/student/certificate_live.ex
lib/oli_web/live/delivery/student/index_live.ex
lib/oli_web/router.ex
test/oli_web/live/delivery/student/certificate_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4335) to the ticket
https://github.com/user-attachments/assets/471eb50e-0c83-4408-a2e6-3fdef7412439
In case the student tries to see the certificate while it has not yet finished it's PDF creation process (very unlikely case), this will be the feedback

[FEATURE] [MER-4335] Implement new liveview to show certificate to a student

---

lib/oli/delivery/sections/certificates/email_templates.ex
lib/oli_web/templates/email/certificate_instructor_pending_approval.html.eex
lib/oli_web/templates/email/certificate_instructor_pending_approval.text.eex

[Link](https://eliterate.atlassian.net/browse/MER-4333) to the ticket
Note: this email will be triggered automatically by the Check Certification Worker ([MER-4106](https://eliterate.atlassian.net/browse/MER-4106)) once the required wiring is done ([MER-4334](https://eliterate.atlassian.net/browse/MER-4334))
After manually triggering the email in the console, we see this result:
[MER-4106]: https://eliterate.atlassian.net/browse/MER-4106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-4334]: https://eliterate.atlassian.net/browse/MER-4334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4333] Instructor approval email template

---

lib/oli/analytics/summary/attempt_group.ex
lib/oli/delivery/snapshots/worker.ex

The base query that runs to pull all the info needed to execute the summary analytics pipeline and to emit xAPI statements includes the full page revision **joined through to every part attempt returned**.  The page revision was only being used to get the resource_id, which can instead be retrieved from the already included `ResourceAccess`.   This PR removes the page revision, lowering the overall overhead of this query.

[PERFORMANCE] [MER-4342] Eliminate page revision from analytics base query

---

assets/src/components/editing/elements/youtube/youtubeActions.tsx

For about a year now, hitting "share" for a video on youtube generates a URL of the form
`https://youtu.be/_gnfkFb8h3U?si=aw76mRazP7ZRHNDl`
where the “si” parameter is a token appended to allow google to track the sharing of videos. Torus'  insert youtube dialog was failing silently on these. But it is natural for authors to obtain a URL via the "share" button. 
The bug stemmed from an error in parsing logic used to extract the video id from a URL. The code  in effect assumed that if the URL had a query parameter at all, it must be the video id parameter as used in the "watch" form URL `https://youtube.com/watch?v=_gnfkFb8h3U` However, query parameters can be included in other form URLs as seen above (and other query parameters are possible in any form). 
This PR recodes the relevant …

[BUG FIX] [MER-4246] Fix youtube URL parsing to handle "share"-generated urls

---

lib/oli_web/components/layouts/workspace.html.heex
lib/oli_web/live/workspaces/course_author/activity_bank_live.ex
lib/oli_web/live/workspaces/course_author/bibliography_live.ex
lib/oli_web/templates/layout/authoring.html.heex
lib/oli_web/templates/layout/delivery.html.heex
lib/oli_web/templates/layout/workspace.html.heex
test/oli_web/live/workspaces/course_author/activity_bank_live_test.exs

This PR addresses issues described in both [MER-4324 ](https://eliterate.atlassian.net/jira/software/c/projects/MER/boards/2?selectedIssue=MER-4324)and [MER-4325](https://eliterate.atlassian.net/jira/software/c/projects/MER/boards/2?selectedIssue=MER-4325). 
The problem was that every time a live component remounts due to a change in navigation, a new react `Components.ModalDisplay` web component is rendered but never registered in the web component's global scope. 
The solution was to shift the react component `Components.ModalDisplay` placement out of particular live components into the `delivery` and `authoring` layout templates. 
[MER-4325]: https://eliterate.atlassian.net/browse/MER-4325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4324] Fixes an issue where sometimes launching a modal requires a page refresh

---

assets/src/apps/page-editor/PageTriggerEditor.tsx
assets/src/components/editing/elements/trigger/TriggerEditor.tsx
assets/src/components/resource/editors/PurposeGroupEditor.tsx

This PR adjusts the dark mode styles for the trigger editing UIs, so that there is better contrast for the sample dropdown and no longer 'white text on white background' for the prompt editing.

[FEATURE] [MER-4360] update dark mode styles

---

lib/oli/certification_eligibility.ex
lib/oli/delivery/sections/certificates/workers/check_certification.ex

Ticket: [MER-4357](https://eliterate.atlassian.net/browse/MER-4357)
When a student submits a graded page, our system kicks off an Oban job. This job’s job (pun intended!) is to figure out if the student has hit the required thresholds. It’s supposed to run every time a student submits a graded page (with some smart optimizations in the mix). But right now, it only runs once, and any follow-up submissions get skipped. This is a problem because the student’s page thinks the thresholds have been reached, but that’s not actually the case since we’re not running all the necessary checks.
The Issue: Once an Oban job runs, it’s marked as "completed." Because of a unique constraint, we can’t run the same job again for the same user and section.
The Fix We’re Proposing: Before inserting a new Oban …

[BUG FIX] [MER-4357] Fix issue preventing threshold checks from triggering on completed jobs

---

lib/oli/rendering/group/html.ex
test/oli/rendering/page/html_test.exs

This PR addresses an issue where when accessing any course in v30, the group styles (Learn by doing, Did I Get This, etc…) are missing.
This issue was introduced by a previous PR that added the new AI trigger button on the group header.

[BUG FIX] [MER-4359] Fixes group container header styling issue on delivery

---

lib/oli_web/live/projects/projects_live.ex

https://eliterate.atlassian.net/browse/MER-4366
This PR fixes an issue related to https://eliterate.atlassian.net/browse/MER-4350 where the account admin status was not showing the Admin Panel link.
The crux of the issue was that the `is_admin` assign which is set in the base pipelines was being overwritten by the Projects LiveView to only be true when a user is a content admin. This PR simply renames that assign.

[BUG FIX] [MER-4366] do not overwrite is_admin assign in projects live view

---

lib/oli_web/controllers/delivery_controller.ex
test/oli_web/controllers/delivery_controller_test.exs

https://eliterate.atlassian.net/browse/MER-4331
This PR reverts the changes in https://github.com/Simon-Initiative/oli-torus/pull/5208. The original ticket [MER-3169](https://eliterate.atlassian.net/browse/MER-3169) didn't consider this use case of infiniscope users needing the ability to enroll themselves in direct delivery sections, even though they are not independent users.
The spirit of the original ticket still remains an issue, LMS/LTI users who are not infiniscope user and unintentionally enroll in a direct delivery section while logged in as an LTI account could lose access to that direct delivery section and their progress when their LMS access expires at whichever institution they are currently a part of. But this PR resolves the immediate need for infiniscope users. …

[BUG FIX] [MER-4331] fix an issue where infiniscope users cannot enroll in direct delivery course

---

lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/user_account.ex
lib/oli_web/live/author_confirmation_instructions_live.ex
lib/oli_web/live/user_confirmation_instructions_live.ex
lib/oli_web/user_auth.ex
test/oli_web/live/workspaces/student_test.exs
test/oli_web/user_auth_test.exs

Fixes an issue uncovered in QA where an unconfirmed student can get lost and have no way to return to their section.
The fix here allows unconfirmed students to access the student workspace when they are enrolled in any course that does not require email confirmation.

[BUG FIX] [MER-4243] allow non-confirmed user to access student workspace

---

lib/oli/delivery/certificates.ex
lib/oli_web/controllers/granted_certificates_controller.ex
lib/oli_web/live/certificates/certificate_settings_live.ex
lib/oli_web/live/certificates/components/certificates_issued_tab.ex
lib/oli_web/live/delivery/instructor_dashboard/helpers.ex
test/oli/delivery/certificates_test.exs
test/oli_web/controllers/granted_certificates_controller_test.exs
test/oli_web/live/certificates/components/certificates_issued_tab_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4361) to the ticket
The main issue was that the query that fetches the granted certificates for the current product did not include all granted certificates of courses created based on that product.
The fix was to extend `browse_granted_certificates/4` to include those certificates.
That same query was not filtering by state -> now [we only consider GC with state = :earned](https://eliterate.atlassian.net/browse/MER-4361?focusedCommentId=25919)
Tests for all modified/extended context functions are included in the PR.
The `download CSV` link returned a blank spreadsheet since the query used to fetch the GCs had the same issue as the other one (it was not considering GC from courses created based on that product and was not filtering by …

[BUG FIX] [MER-4361] Fix product credentials issued tab

---

lib/oli_web/components/delivery/user_account.ex

[Link](https://eliterate.atlassian.net/browse/MER-4366) to the ticket
As [Dovid pointed](https://eliterate.atlassian.net/browse/MER-4366?focusedCommentId=25922) the bug was introduced on MER-4350.
The `!` on the if condition was on the admin case instead of the author case.

[BUG FIX] [MER-4366] Fix author label on workspace menu

---

lib/oli_web/live/certificates/components/thresholds_tab.ex

Assign certificate to socket assigns after inserting it so next time an update happens instead a new insert.
See: https://eliterate.atlassian.net/browse/MER-4375

[BUG FIX] [MER-4375] Do not create duplicate certificates in thresholds tab

---

lib/oli_web/live/certificates/certificate_settings_live.ex
lib/oli_web/live/sections/overview_view.ex

This PR address an issue where the breadcrumb link under a delivery course `Manage Certificate Settings` page erroneously redirects a course instructor into an `authoring` page, generating a 500 error.

[BUG FIX] [MER-4370] Fixes error navigating as an instructor from certificate settings

---

lib/oli_web/live/certificates/components/design_tab.ex

Remove default browser style for file input label
https://eliterate.atlassian.net/browse/MER-4365

[BUG FIX] [MER-4365] Change style for the File Input used for uploading Certificate logos

---

lib/oli/delivery/certificates.ex
lib/oli/delivery/sections.ex
test/oli/delivery/certificates_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4372) to the ticket
The issue was caused by remixing a section with a certificate configured to consider "all" assessments as required for gaining the certificate.
In the fix, if the section has a certificate enabled and set to require "all" assessments,  we change the certificate configuration to "custom" and set the list of required assessments to match the original list of assessments (by original we refer to the ones that existed before this remix was required).
On the other hand, we realized that an instructor may delete a required assessment in a certificate configured as "custom". In that case, we would have an "impossible" certificate (a student can't attempt an assessment that no longer belongs to the course). To prevent this …

[BUG FIX] [MER-4372] Fix certificates when instructor remixes course

---

lib/oli_web/live/common/paged_table.ex

This PR fixes an issue where, upon clicking on the pagination to navigate to another page on the Insights view of a project, the view refreshes and stays on the first page.

[BUG FIX] [MER-4379] Fixes paged table not paging issue

---

lib/oli_web/router.ex

The issue is related to the enforcement of research consent by redirecting a user to the `/research_consent` route which landed in parallel with this one, and it was not included in the list of routes that allow access when a student is enrolled in any section that omits email verification.
The fix here is to add the `maybe_skip_email_verification` pipe to the research consent route.

[BUG FIX] [MER-4243] fix an issue where non-confirmed students could not access research consent form

---

lib/oli/delivery/depot/match_spec_translator.ex
lib/oli/delivery/sections/section_resource_depot.ex
test/oli/delivery/sections/section_resource_depot_test.exs

This PR addresses an issue where a course without surveys lists all section resources when one views the `Surveys` table under the course `Insights` tab.

[BUG FIX] [MER-4395] Ensures that a section resource page query with zero page ids returns empty array

---

lib/oli_web/components/common.ex
test/oli_web/live/sections/edit_live_test.exs

Ticket: [MER-4374](https://eliterate.atlassian.net/browse/MER-4374)
This PR addresses the issue encountered when modifying section details, which also altered other unrelated parts that were not touched.
The problem was caused by how we were handling the disabled attribute. When an input is set to disabled, the browser ignores it during form submission, causing the hidden input to send its corresponding value, which was set to false. This behavior is expected since browsers intentionally exclude disabled inputs from form data.
This ticket is part of v31 and should point to master. ⚠️ 
[MER-4374]: https://eliterate.atlassian.net/browse/MER-4374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4107] Fix: ensure checkbox value is submitted even when disabled. The hidden input reflects the checkbox state based on @checked

---

lib/oli_web/icons.ex
lib/oli_web/live/delivery/student/assignments_live.ex
test/oli_web/live/delivery/student/assignments_live_test.exs

[MER-3882](https://eliterate.atlassian.net/browse/MER-3882)
Add Certificate requirements information to the assignments page when the course section has a certificate.
Add filter to display all assignments or required assignments for the certificate.
https://github.com/user-attachments/assets/18a75bb8-5780-45b6-91f1-b691dc863fd0
[MER-3882]: https://eliterate.atlassian.net/browse/MER-3882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-3882] Add Certificate Requirements to Assignments Page

---

.github/actions/amazon-linux-builder/Dockerfile

The erlang.org site primary downloads become unavailable when the site is under maintenance. This will allow getting the source from the secondary location if the first wget fails.

[ENHANCEMENT] [MER-4405] Allow erlang download to failover to secondary download location

---

lib/oli_web/plugs/ensure_datashop_id.ex
mix.exs
test/oli_web/plugs/ensure_datashop_id_test.exs

https://eliterate.atlassian.net/browse/MER-4403
This PR implements a datashop session id refresh policy that mints a new datashop session id after 30 mins of inactivity.
This is implemented via the `OliWeb.Plugs.EnsureDatashopId` plug. A new value `:datashop_session_updated_at` is not tracked in the session and is checked to see if the last update was more than 30 mins ago. If so, then a new datashop id is created and set in the session. Otherwise, this timestamp is updated to the current time to keep the datashop session "rolling" until 30 mins of inactivity occurs.

[BUG FIX] [MER-4403] mint new datashop id after 30 mins of inactivity

---

lib/oli_web/live/user_login_live.ex
lib/oli_web/plugs/maybe_skip_email_verification.ex
lib/oli_web/router.ex
test/oli_web/live/user_login_live_test.exs

As seen by the multiple reworks of this issue, it is tricky to identify all routes that might need this check in place and as it expands, it is starting to impact more users and clutters the router pipelines.
This PR takes a more measured approach to restricting access to non-confirmed users. Instead of trying to "whack-a-mole" all of the routes that may or may not be required for non-confirmed user access, this PR simply adds the check for non-confirmed user to the delivery_protected plug and only runs the check for users who are not confirmed.
So for **all** delivery protected routes, if a user is non-confirmed then a check will be performed to see if the student is enrolled in any section that omits student email verification, and if so …

[BUG FIX] [MER-4243] checkbox for omit student email verification not being honored

---

lib/oli/delivery/sections/section_resource_depot.ex
lib/oli_web/components/delivery/practice_activities/practice_activities.ex
lib/oli_web/components/delivery/practice_activities/practice_assessments_table_model.ex
lib/oli_web/live/delivery/instructor_dashboard/helpers.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
test/oli/delivery/sections/section_resource_depot_test.exs
test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4396) to the ticket
The issue was that when [we replaced the DB queries with the SectionResourceDepot implementation](https://github.com/Simon-Initiative/oli-torus/pull/5442), the container_id assigned in the `Helpers.return_page` function was the id of the section_resource instead of the resource_id. When applying a container filter we expected the resource_id, since we filter all practice pages where the container_id matches that given resource_id.
That was the reason all tests from `test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs` were failing (that file was removed in the same PR that implemented the SectionResourceDepot approach). So, that file was restored.
We were sorting all container …

[BUG FIX] [MER-4396] Practice activities container filter not working

---

config/config.exs
config/runtime.exs
lib/oli/application.ex
lib/oli/logger_truncator.ex

This PR introduces and installs a configurable `Oli.LoggerTruncator`, which truncates items being logged.  
This addresses a shortcoming of the currently used `:logger` `truncate` (see `runtime.exs`) which only truncates what is actually written to the logs.  The new `Oli.LoggerTruncator` truncates the in-memory representation, which is important as that is what is passed around between things like the Logger and downstream backends like AppSignal.  
We have been seeing huge memory spikes on Proton which look like this:
This PR will eliminate this problem by ensure that the seemingly HUGE message being stored in memory gets truncated down to max size in bytes (default `5_000`)
This is a low risk addition because we can completely turn this off by setting `LOGGER_TRUNCATION_ENABLED` equal …

[PERFORMANCE] [MER-4412] Truncate in memory representation of log messages

---

lib/oli_web/controllers/user_session_controller.ex
test/oli_web/controllers/user_session_controller_test.exs

[MER-4401](https://eliterate.atlassian.net/browse/MER-4401)
Fixed a 500 error when logging in with an email associated with both an LTI user and an independent learner.
Root Cause
The issue was caused by a query that did not properly filter independent users, resulting in multiple records for the same email. Since LTI users and independent learners can share the same email, the query returned multiple results, leading to an Ecto.MultipleResultsError.
Fix
An existing function that properly filters users based on the independent_learner flag was used, ensuring that any login attempt by email only considers independent learners and preventing the multiple results error.
[MER-4401]: https://eliterate.atlassian.net/browse/MER-4401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

[BUG FIX] [MER-4401] User login is not being constrained to independent users

---

lib/oli_web/live/delivery/student/lesson_live.ex
test/oli_web/live/delivery/student/lesson_live_test.exs

[MER-4426](https://eliterate.atlassian.net/browse/MER-4426)
This PR ensures that when an assessment has a past suggested date with the late policy set to “Disallow late start and late submit” and the scheduling type is :read_by, the attempt is not auto-submitted upon entering the page.
Root Cause
Previously, the logic determining whether an attempt should be auto-submitted did not account for assessments with :read_by scheduling type. As a result, even when late start and late submit were disallowed, and the suggested date had passed, the attempt was incorrectly auto-submitted upon page entry.
Fix
The logic now correctly excludes :read_by assessments from the auto-submit condition, ensuring that students can enter and view their attempt without it being immediately submitted. …

[BUG FIX] [MER-4426] Attempts auto submit after suggested date has passed

---

lib/oli_web/common/params.ex

This PR fixes a bug where in the "create dataset job" tab, a user cannot select course sections nested in other pages due to a pagination problem preventing navigating to other pages.

[BUG FIX] [MER-4430] Cannot navigate pages in dataset

---

assets/src/apps/authoring/store/activities/templates/simpleText.ts
assets/src/components/parts/janus-text-flow/QuillEditor.tsx
assets/src/components/parts/janus-text-flow/quill-utils.ts
assets/src/components/parts/janus-text-flow/schema.ts

Hey @bsparks could you please review the PR? Thanks
This PR contains 2 main changes:
1. newly added text flow will have REM based font rendering
2. updated the Quill Editor font size whitelist to include bigger font size. They won't be visible in font size selection

[ENHANCEMENT] [MER-4190] Font Size Dropdown Not Reflecting Selected Option and Lacking Clear Labels (Simple & Advanced Author)

---

lib/oli_web/live/workspaces/course_author/pages_live.ex
test/oli_web/live/workspaces/course_author/pages_live_test.exs

[MER-3510](https://eliterate.atlassian.net/browse/MER-3510)
This PR fixes the issue where attempting to create an adaptive page from the `All Pages` view resulted in a page reload without actually creating a new adaptive page.
Root Cause
The root cause of the issue was that incorrect parameters were being passed to the function responsible for creating both adaptive and basic pages.
Fix
The fix was based on fixing the parameters passed to the function responsible for creating pages, ensuring the page type and grading status are properly defined.
https://github.com/user-attachments/assets/b0e723b9-7502-4e95-913e-3f735bcda3e4
[MER-3510]: https://eliterate.atlassian.net/browse/MER-3510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-3510] Cannot create adaptive page from all pages

---

lib/oli_web/live/workspaces/instructor/index_live.ex

If for any given reason the instructors of a section end up in a inconsistent state and they do not have a name associated, when filtering the sections list (specifically when downcasing the instructor names, see: [Appsignal Incident](https://appsignal.com/open-learning-initiative/sites/618539ab2cf81d7e3cd051ca/exceptions/incidents/62/samples/618539ab2cf81d7e3cd051ca-477208838546314286517424913201)) it would fail returning a 500.
I will add a log to detect these cases in a separate PR, related to this same bug, since the other ticket also involves work in the "Manage Source Materials" section.
See: https://eliterate.atlassian.net/jira/software/c/projects/MER/issues/MER-4429

[BUG FIX] [MER-4429] Instructor Dashboard search: ignore nil instructor names

---

lib/oli_web/live/common/utils.ex
test/oli_web/live/common/utils_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4436) to the ticket
The issue was that the recently added `extract_text` helper function did not consider the case where the feedback text might be contained within the `model` key. An activity part attempt may have the feedback in two ways:
```
%Oli.Delivery.Attempts.Core.PartAttempt{
__meta__: #Ecto.Schema.Metadata<:loaded, "part_attempts">,
id: 1275,
...
feedback: %{
"content" => [
%{
"children" => [
%{
"text" => "Incorrect. A liquid has a definite volume and takes the shape of its container."
}
],
"id" => "dd888118ccd946a49ba0d2bf0dee6c2d",
"type" => "p"
}
],
"id" => "3295844819"
},
...
}
```
```
%Oli.Delivery.Attempts.Core.PartAttempt{
__meta__: #Ecto.Schema.Metadata<:loaded, "part_attempts">,
id: 1249,
...
feedback: %{
"content" => …
```

[BUG FIX] [MER-4436] 500 error when accessing student quizz attempts

---

lib/oli/delivery/metrics.ex
test/oli/delivery/metrics/progress_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4437) to the ticket
The issue was that we were calculating the progress in a way that it could never reach 1.0, since the denominator was always slightly larger than the numerator (because we were adding 0.0001 to the denominator):
```
completed_count / (total_count * ((COALESCE(rev.full_progress_pct, 100) / 100) + 0.0001))
```
```
completed_count / (total_count * ((COALESCE(rev.full_progress_pct, 100) / 100.0)))
```
https://github.com/user-attachments/assets/236ac93d-eca6-4024-9d33-14d4193dcac7
https://github.com/user-attachments/assets/f5805475-01e2-4cd4-bd7a-2df2bcccc301

[BUG FIX] [MER-4437] Progress for practice page not counting on homepage

---

lib/oli_web/common/assent_auth_web.ex
lib/oli_web/plugs/allow_iframe.ex
lib/oli_web/router.ex

https://eliterate.atlassian.net/browse/MER-4451
Fixes an issue where trying to load a section directly in an iframe within an LMS refused to connect. The root issue was the x-frame-options header was implicitly being set by phoenix. I am not sure what actually changed between v29 and v30 to introduce this issue but adding an explicit plug to unset this header fixes the problem.
This only enables iframe embedding for delivery routes. Authoring and other non-delivery routes will still be prohibited from being loaded in an iframe.

[BUG FIX] [MER-4451] canvas embed view refuses to connect

---

lib/oli/delivery/settings.ex
test/oli/delivery/attempts/was_late_test.exs
test/oli/delivery/settings_test.exs

Ticket: [MER-4446](https://eliterate.atlassian.net/browse/MER-4446)
This PR fixes an issue where an instructor sets a graded page with a suggested "read by" date, but it is not honored.
The fix can be found in commit e4508cce38e6815f549f66d6f8ae992b3dba5da3 , where the `Oli.Delivery.Settings.was_late?/3` function was not considering the case when `%Combined{scheduling_type: :read_by}`. This case is used to determine that the grade page is not late.
[MER-4446]: https://eliterate.atlassian.net/browse/MER-4446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4446] assessments are being marked late when submitting after suggested date

---

lib/oli/delivery/settings.ex
test/oli/delivery/attempts/was_late_test.exs
test/oli/delivery/settings_test.exs

[MER-4446](https://eliterate.atlassian.net/browse/MER-4446)
This PR reverts the changes made by @Francisco-Castro in [this other PR](https://github.com/Simon-Initiative/oli-torus/pull/5517) in order to keep the functionality identical to how it is currently in Proton.
[MER-4446]: https://eliterate.atlassian.net/browse/MER-4446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4446] Revert assessments are being marked late when submitting after suggested date

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
test/oli_web/live/delivery/student/lesson_live_test.exs

[MER-4035](https://eliterate.atlassian.net/browse/MER-4035)
Add missing Support link to lesson pages:
1. It is displayed in both practice and graded pages.
2. It is not displayed on adaptive pages.
https://github.com/user-attachments/assets/563ab371-aa9c-4a1c-b914-f4ef6e52b1fb
[MER-4035]: https://eliterate.atlassian.net/browse/MER-4035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4035] Add Support link to lesson pages

---

assets/src/hooks/fixed_navigation_bar.ts
assets/src/hooks/index.ts
lib/oli/delivery/metrics.ex
lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/live_session_plugs/init_page.ex
test/oli/delivery/metrics/progress_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[MER-3452](https://eliterate.atlassian.net/browse/MER-3452)
This PR introduces changes and improvements to the navigation bar displayed at the bottom of the `Lesson Pages`.
It improves the way the navigation bar is displayed, leaving it hidden by default and showing it when the user hovers on it. 
Also, when the user navigates to the bottom of the page, the bar will be fixed at the bottom. 
On the other hand, icons are added next to the title of the previous page and the next page, indicating what type of page they are and if they are completed or not. 
For the icons, the same logic used in the `Learn View` is maintained, i.e.: 
- Scored pages completed ---> Square check icon
- Scored pages not completed ---> Orange flag icon
- Practice pages completed ---> Check icon
- Practice pages not …

[FEATURE] [MER-3452] Bottom bar improvement lesson pages

---

assets/src/components/parts/janus-mcq/schema.ts

This PR contains fix for a follow-up issue that came in this ticket. 
The correct UI schema was
```
correctFeedback: {
'ui:widget': 'textarea',
'ui:options': {
rows: 2,
},
},
incorrectFeedback: {
'ui:widget': 'textarea',
'ui:options': {
rows: 2,
},
},
commonErrorFeedback: {
'ui:widget': 'MCQCustomErrorFeedbackAuthoring',
},
```
but by mistake, in my previous [PR](https://github.com/Simon-Initiative/oli-torus/pull/5509), I made it like this when changing the UI widget from text to text-area: 
```
correctFeedback: {
'ui:widget': 'textarea',
'ui:options': {
rows: 2,
},
},
incorrectFeedback: {
'ui:widget': 'MCQCustomErrorFeedbackAuthoring',
},
commonErrorFeedback: {
items: {
'ui:widget': 'textarea',
'ui:options': {
rows: 2,
},
},
},
```

[BUG FIX] [MER-4387] Update Single-line feedback to Multi line feedback input in Simple Author

---

lib/oli_web/components/common.ex

Ticket: [MER-4374](https://eliterate.atlassian.net/browse/MER-4374)
This PR updates the checkbox to match the one in the [current](https://github.com/phoenixframework/phoenix/blob/819fcf8a3d119b98c439fe304f5e53aaf86ce5bf/installer/templates/phx_web/components/core_components.ex#L183) core_component Phoenix module and fixes the issue with the checkbox mentioned in the ticket.
[MER-4374]: https://eliterate.atlassian.net/browse/MER-4374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4374] Fix checkbox input

---

lib/oli_web/components/delivery/layouts.ex
lib/oli_web/components/layouts/student_delivery_lesson.html.heex

[Link](https://eliterate.atlassian.net/browse/MER-4035) to the ticket
The issue was that the width of the support button was set to `full`, and since its `z-index` was bigger than the one for the previous-next navigation bar, whenever we tried to click on the navigation bar, we ended up clicking on the support button.
By setting a width to the support button, we do not have the overlay issue between those 2 elements.
https://github.com/user-attachments/assets/dec2179f-db4e-49a4-abc3-5354d307d525

[BUG FIX] [MER-4035] Add support link to lesson pages - part 2

---

lib/oli/delivery/sections.ex

The PR fixes a bug where the “Student Proficiency” metric does not match the “Proficiency Distribution” graphic.

[BUG FIX] [MER-4450] fixes proficiency mismatch bug

---

lib/oli/delivery/certificates/certificate_renderer.ex

Add cursive paragraph style with cross-platform font stack because in certain operating systems/browsers where the font was not available signatures were rendered in Comic Sans.
See: https://eliterate.atlassian.net/browse/MER-4483

[BUG FIX] [MER-4483] Improve Certificates signatures font stack

---

assets/src/apps/page-editor/PageTriggerEditor.tsx
assets/src/components/TriggerButton.tsx
assets/src/components/activities/common/triggers/TriggerAuthoring.tsx
assets/src/components/activities/common/triggers/TriggerUtils.tsx
assets/src/components/activities/image_coding/ImageCodingAuthoring.tsx
assets/src/components/editing/elements/trigger/TriggerEditor.tsx
assets/src/hooks/evaluate_mathjax_expressions.ts
lib/oli/activities/model/response.ex
lib/oli/conversation/dialogue.ex
lib/oli/conversation/dialogue_handler.ex
lib/oli/conversation/functions.ex
lib/oli/conversation/triggers.ex
lib/oli/delivery/evaluation/evaluator.ex
lib/oli_web/components/delivery/dialogue.ex
lib/oli_web/live/dialogue/window_live.ex
lib/oli_web/live/sections/overview_view.ex
lib/oli_web/live/workspaces/course_author/overview_live.ex
test/oli/conversation/triggers_test.exs

This PR fixes the following issues:
The fix here is to queue for later processing any trigger that arrives when DOT is currently streaming a response. This effectively "serializes" DOT's operation, ensuring that it can never interleave the streaming results of multiple triggers.
This was addressed in another ticket, but it actually was including the activity `Response` object and not the student's actual response (from the part attempt).  Changes were made to encode into the context the `:response` from the part attempt.
This is addressed by providing a new `course_sequence` function to DOT - so that it can get a full listing of the containers and pages in the course. 
This was handled by adjusting the prompt, giving access to the specific part id that was triggered, and instructing DOT …

[ENHANCEMENT] [MER-4487] [MER-4500] Collection of Trigger point updates

---

lib/oli_web/live/sections/overview_view.ex

Ticket: [MER-4493](https://eliterate.atlassian.net/browse/MER-4493)
This PR changes the banner message after updating the AI settings.
Note: I added the word 'AI' to match the group section.
[MER-4493]: https://eliterate.atlassian.net/browse/MER-4493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4493] Change the text on the banner after updating AI settings

---

assets/src/hooks/evaluate_mathjax_expressions.ts
lib/oli/conversation/triggers.ex

This restores the typesetting on pages, this `EvaluateMathJaxExpressions` hook is actually called from `lib/oli_web/components/layouts/student_delivery_lesson.html.heex`.  In my original PR, I did a search through `*.ex` files and didn't see it being used - and changed it in a way that precluded it from working on formulas.   This PR restores `.formula` and `.formula-inline` - adding in `.chat-message` which after testing shows both page Latex and DOT messages now correctly rendering Latex.
I also saw an `IO.inspect()` call that should have been removed from Triggers code.

[BUG FIX] [MER-4487] Restore latex page rendering

---

.github/workflows/build.yml
lib/oli/branding.ex
lib/oli/delivery/granted_certificates.ex
lib/oli/delivery/sections/certificates/workers/generate_pdf.ex
lib/oli_web/live/delivery/student/assignments_live.ex
test/oli/analytics/datasets_test.exs
test/oli/analytics/xapi/pipeline_test.exs
test/oli/branding_test.exs
test/oli/delivery/section_cache_test.exs
test/oli/delivery/sections/blueprint_test.exs
test/oli/publishing/authoring_resolver_test.exs
test/oli/search/embeddings_test.exs
test/oli_web/controllers/api/xapi_controller_test.exs
test/oli_web/controllers/legacy_superactivity_controller_test.exs
test/oli_web/controllers/page_delivery_controller_test.exs
test/oli_web/live/certificates/components/certificates_issued_tab_test.exs
test/oli_web/live/delivery/student/discussions_live_test.exs
test/oli_web/live/delivery/student/learn_live_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs
test/oli_web/live/grades_live_test.exs
test/oli_web/live/ingest_live_test.exs
test/oli_web/live/new_course/course_details_test.exs
test/oli_web/live/objectives_live_test.exs
test/oli_web/live/payments_live_test.exs
test/oli_web/live/products_test.exs
test/oli_web/live/sections/gating_and_scheduling_test.exs
test/oli_web/live/workspaces/course_author/objectives_live_test.exs
test/oli_web/plugs/header_size_logger_test.exs
test/support/test_helpers.ex
test/test_helper.exs

Now flaky tests are tagged as such, and tests that _always_ fail are marked as skipped (we need to get into those and try to fix them and remove the ones that are related to legacy features)
The Github action that runs the tests, now reruns the initial failed tests once more in order to avoid having to retrigger the CI because of flaky tests.
See: https://eliterate.atlassian.net/browse/MER-3983
----
| File                                                                                             | Count |
|--------------------------------------------------------------------------------------------------------|----------------|
| test/oli_web/controllers/page_delivery_controller_test.exs                                             | 38             |
| …

[ENHANCEMENT] [MER-3983] Flaky Tests (Part 1)

---

lib/oli/delivery/settings.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli/delivery/settings_test.exs
test/oli_web/live/delivery/student/prologue_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4490?focusedCommentId=27024) to the comment in the ticket
When I opened the previous PR, I understood that none of the logic of the [Schedule and Assessment Settings](https://docs.google.com/drawings/d/1LDzW7DH6fX7BW6oFBYgPR9H2ZkqHn-YP5JuvcfSq1xw/edit) document had to be applied when the page had a scheduling type of `:read_by`. The note that made me confuse was: 
Amanda [explained](https://eliterate.atlassian.net/browse/MER-4490?focusedCommentId=27030) to me that `“Suggested by” date has no impact on the logic, meaning one should follow the logical path on the flow chart that exists when there is no due date”`.
That being clarified, then we should mark an attempt as late when the page has read_by + allow_late_submit + time_limit and the …

[BUG FIX] [MER-4490] Fix date comparison and submit page term - part 2

---

lib/oli_web/live/delivery/student/assignments_live.ex
lib/oli_web/live/delivery/student/lesson_live.ex
lib/oli_web/live/delivery/student/prologue_live.ex
lib/oli_web/live/delivery/student/review_live.ex
test/oli_web/live/delivery/student/lesson_live_test.exs
test/oli_web/live/delivery/student/prologue_live_test.exs

[MER-4507](https://eliterate.atlassian.net/browse/MER-4507)
This PR updates the `required_keys_per_assign` configuration to include the `:open_and_free` key in the section assign. This makes sure that the open_and_free value stays in the LiveView socket after calling slim_assigns/1, which is used to reduce memory usage.
Before this change, open_and_free was not included in the slimmed version of section. Because of that, some logic depending on this flag—like the branding logic that decides which logo to show—did not work correctly.
As a result, even when a section had a custom brand with its own logo, the system was always showing the default logo, since section.open_and_free was missing and treated as false.
With this fix, the open_and_free value is kept, and the branding logic can now …

[BUG FIX] [MER-4507] Branding isnt working on course pages as expected

---

lib/oli_web/live/user_login_live.ex
lib/oli_web/templates/layout/authoring.html.heex
lib/oli_web/templates/layout/chromeless.html.heex
lib/oli_web/templates/layout/delivery.html.heex
lib/oli_web/templates/layout/error.html.heex
lib/oli_web/templates/layout/lti.html.heex

Instructor sign-in page was defaulting to hard-coded page title of "Sign in", which was inconsistent with other sign-in pages which have page title taken from brand name, coming out as "OLI Torus" under default branding. This inconsistency was interfering with automating QA testing. This PR changes to use the ~~name from branding~~ short name from vendor properties consistently for page title in all cases.
Note "page title" here means the title shown in the browser tab, obtained from meta information in the HTML head element. It is not part of the page body content.

[BUG FIX] [MER-4536] make instructor sign-in page use same page title as student and author sign-in

---

lib/oli_web/live/admin/admin_view.ex
lib/oli_web/live/admin/external_tools/external_tools_view.ex
lib/oli_web/router.ex
test/oli_web/live/admin_live_test.exs

[MER-4290](https://eliterate.atlassian.net/browse/MER-4290)
This PR adds a link to navigate to the view that will manage the `LTI 1.3 external tools` within the account management section of the admin panel. 
It also creates the view that will be used to manage the `LTI 1.3 external tools`.
https://github.com/user-attachments/assets/9551e062-dc2a-46f4-864e-37a5b4528e0b
[MER-4290]: https://eliterate.atlassian.net/browse/MER-4290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4290] Adding admin manage lti 1.3 external tools

---

assets/src/components/parts/janus-text-slider/SliderTextAuthor.tsx

The issues here was the slider text is showing the same Max number as labels. The max value should be labels minus 1. (e.g., 5 labels, max is 4).

[BUG FIX] [MER-3990] Add Text Option to Slider Component

---

lib/oli_web/live/admin/external_tools/external_tools_view.ex

[MER-4290](https://eliterate.atlassian.net/browse/MER-4290)
This PR fixes the breadcrumb text in the `Manage LTI 1.3 External Tools` view by changing it from the wrong text “LTI 1.3 External Tools” to the correct text “Manage LTI 1.3 External Tools”. 
[MER-4290]: https://eliterate.atlassian.net/browse/MER-4290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4290] Fix breadcrumb text in external tools liveview

---

assets/src/components/activities/common/triggers/TriggerUtils.tsx

The ResponseMult activity type can break trigger type detection code - as when parts are linked there are then less parts than there are inputs. 
The change here is to catch the exception that `findTargetedResponses` throws in this case, and omit this activity instance from including targeted triggers.

[BUG FIX] [MER-4547] More robust trigger type determination for ResponseMult

---

lib/oli/delivery.ex
lib/oli/delivery/paywall.ex
lib/oli/delivery/paywall/discount.ex
lib/oli_web/live/products/payments/discounts/form.ex
lib/oli_web/live/products/payments/discounts/show_view.ex
lib/oli_web/live/products/payments/discounts/table_model.ex
priv/repo/migrations/20250428165356_add_bypass_paywall_field_to_discounts.exs
test/oli/delivery/paywall/discount_test.exs
test/oli/delivery/paywall_test.exs

[MER-4510](https://eliterate.atlassian.net/browse/MER-4510)
This PR fixes the case when an admin or instructor wants to give students a 100% discount (meaning $0 cost) for a given product or institution. A new field is added to the `discounts` table and the "Create Discounts" form.
**Before:** 
https://github.com/user-attachments/assets/b3b55908-a838-4024-979f-f885d57a4d8c
**After:**
https://github.com/user-attachments/assets/e7045505-7370-4cfe-be6b-b17a25737db7
NOTE:
I added to our tech debt list that we need to add tests for the Paywall and Discounts integrated logic (there are no test files for this flow) and for the section creation logic (create from product and project). Since this is a bug that needs to be addressed ASAP, I didn't add those test cases in this PR.
[MER-4510]: …

[BUG FIX] [MER-4510] Fix Bypass Paywall logic

---

assets/src/apps/authoring/components/ComponentToolbar/AddComponentToolbar.tsx

This is a follow-up issue that I found due to the changes made https://github.com/Simon-Initiative/oli-torus/pull/5572/files.

[BUG FIX] [MER-3586] Resizing window will cause component icons to not appear in Advanced Author

---

assets/src/apps/bank/CreateActivity.tsx
assets/src/components/activities/creation.ts

https://eliterate.atlassian.net/browse/MER-4551
This PR fixes an issue where authors cannot add activities to the activity bank. The issue was caused by a change made in LTI external tools groundwork which modified the invokeCreationFunc to register activities using their authoringElement, instead of activity slug, in order to support multiple registered activities under the same authoring element (for LTI activities).
The fix here is to update activity bank to use authoringElement for the key in invokeCreationFunc.

[BUG FIX] [MER-4551] Cannot add activity to bank

---

lib/oli/delivery/metrics.ex
lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex
lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex
test/oli/analytics/summary/metrics_v2_test.exs

This PR updates aggregate student proficiency calculations for both content containers (Units, Modules) and Learning objectives to use the **mode**, meaning the proficiency category (Low, Medium, High, Not enough data) that describes the largest number of students. 
Refer to the ticket for details and examples. [MER-4506](https://eliterate.atlassian.net/jira/software/c/projects/MER/boards/2?selectedIssue=MER-4506)
[MER-4506]: https://eliterate.atlassian.net/browse/MER-4506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4506] Switches aggregate student proficiency for content and objectives the using mode instead of average

---

lib/oli/delivery/metrics.ex
lib/oli/delivery/sections.ex
test/oli/analytics/summary/metrics_v2_test.exs

This PR updates the insights in the content and objectives table to account for users who have not yet interacted with the content. It also ensures that, where there is more than one mode, the displayed value should be the highest value according to this hierarchy:
1. Low
2. Medium
3. High
4. Not enough information

[ENHANCEMENT] [MER-4506] Updates aggregates mode calculation to include all students

---

lib/oli_web/controllers/page_delivery_controller.ex
test/oli_web/controllers/page_delivery_controller_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4261) to the ticket
This PR extends the work done on [MER-4261](https://github.com/Simon-Initiative/oli-torus/pull/5569), fixing the container-preview case key-error.
https://github.com/user-attachments/assets/79c788ef-56bc-4a81-a3a2-3697782e5f7b
https://github.com/user-attachments/assets/713f5fb1-2f00-4fa7-a4e6-5625a9e4b23f
This PR also un-skips some tests that were skipped on [MER-3983](https://github.com/Simon-Initiative/oli-torus/pull/5527), since some of them are needed (they test, for instance, the case fixed in this PR)
[MER-4261]: https://eliterate.atlassian.net/browse/MER-4261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-3983]: …

[BUG FIX] [MER-4261] Student home page when no schedule set - part 2

---

lib/oli/authoring/editing/page_editor.ex
lib/oli/delivery/sections.ex
lib/oli/resources.ex
lib/oli/resources/revision.ex
priv/repo/migrations/20250428195108_add_activity_refs_to_revisions.exs
test/oli/sections_test.exs
test/oli_web/live/products_test.exs
test/support/factory.ex

- Added `activity_refs` array field to the revisions table to track the list of activity resource IDs referenced within a page.
- Updated the `PageEditor` logic to recompute and persist the `activity_refs` field on every page edit.
- Implemented `Oli.Delivery.Sections.get_section_resources_with_lti_activities/1` which:
- Accepts a course section
- Identifies all LTI activities in the section via the activity_registrations table.
- Locates all pages (via section resources) whose activity_refs include any of the LTI activity resource IDs.
- Returns results grouped by activity resource ID.
See: https://eliterate.atlassian.net/browse/MER-4469

[FEATURE] [MER-4469] Track LTI activities

---

lib/oli_web/common/session_context.ex
lib/oli_web/live/attempt/attempt_live.ex
lib/oli_web/live/certificates/certificate_settings_live.ex
lib/oli_web/live/collaboration_live/index_view.ex
lib/oli_web/live/delivery/instructor_dashboard/initial_assigns.ex
lib/oli_web/live/delivery/manage_source_materials.ex
lib/oli_web/live/delivery/remix_section.ex
lib/oli_web/live/delivery/student_dashboard/initial_assigns.ex
lib/oli_web/live/grades/browse_updates_view.ex
lib/oli_web/live/grades/failed_grade_sync.ex
lib/oli_web/live/grades/gradebook_view.ex
lib/oli_web/live/grades/grades.ex
lib/oli_web/live/grades/observe_grade_updates.ex
lib/oli_web/live/manual_grading/manual_grading_view.ex
lib/oli_web/live/products/details_view.ex
lib/oli_web/live/progress/student_resource_view.ex
lib/oli_web/live/progress/student_view.ex
lib/oli_web/live/sections/assessment_settings/settings_live.ex
lib/oli_web/live/sections/assistant/student_conversations.ex
lib/oli_web/live/sections/edit_view.ex
lib/oli_web/live/sections/gating_and_scheduling.ex
lib/oli_web/live/sections/gating_and_scheduling/edit.ex
lib/oli_web/live/sections/gating_and_scheduling/new.ex
lib/oli_web/live/sections/invite_view.ex
lib/oli_web/live/sections/mount.ex
lib/oli_web/live/sections/overview_view.ex
lib/oli_web/live/sections/schedule_view.ex
lib/oli_web/live/workspaces/course_author/products/details_live.ex

https://eliterate.atlassian.net/browse/MER-4562
Fixes the root cause of an issue identified during smoke testing where deleting an author who was logged in would crash liveviews being accessed by instructor if that author session was still also active. In general, this `Mount.for` module used by a number of LiveViews was not pulled forward as part of the phx.gen.auth migration to use socket assigns for current author/user and instead relied on the session ids to load these users itself.
By using the assigns in the socket set by the new auth mount plugs, we can have a single source of truth for user sessions and these records only need to be loaded and preloaded a single time for a request. This PR updates this module to use the already loaded assigns instead of trying to re-load the users …

[BUG FIX] [MER-4562] Refactor Mount.for to use auth socket assigns instead of session ids

---

lib/oli_web/live/admin/external_tools/new_external_tool_view.ex

[MER-4292](https://eliterate.atlassian.net/browse/MER-4292)
This PR fixes the color of the success flash message icon
https://github.com/user-attachments/assets/bf7bd402-9d7d-421d-91e2-403c102ac7c5
[MER-4292]: https://eliterate.atlassian.net/browse/MER-4292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4292] Fix success icon color - rework

---

lib/oli_web/live/sections/assessment_settings/student_exceptions_table.ex
lib/oli_web/live/sections/assessment_settings/student_exceptions_table_model.ex
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

[MER-4275](https://eliterate.atlassian.net/browse/MER-4275)
This PR updates the Student Exceptions tab by replacing the separate `Late Submit` and `Late Start` settings with a unified `Late Policy` setting, ensuring consistency with the Assessment Settings. 
This change provides instructors with a clearer understanding of which settings are applied to student exceptions, avoiding confusion. 
The `Late Policy` setting in the Student Exceptions tab now mirrors the options and behavior found in the Assessment Settings.
https://github.com/user-attachments/assets/2376addf-80b6-4397-90b9-bd6eaeb884b3
[MER-4275]: https://eliterate.atlassian.net/browse/MER-4275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4275] Update student exceptions late policy

---

lib/oli_web/live/delivery/student/home/components/schedule_component.ex
lib/oli_web/live/delivery/student/index_live.ex
test/oli_web/live/delivery/student/home/components/schedule_component_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4263?focusedCommentId=27883) to the comment in the ticket
In a refactor, I accidentally removed that implementation.

[FEATURE] [MER-4263] Remove mentions of not yet scheduled - part 2

---

assets/src/components/content/add_resource_content/AddActivity.tsx
assets/src/data/content/editors.ts
lib/oli/activities.ex
lib/oli/activities/activity_map_entry.ex
lib/oli/activities/activity_registration.ex
test/oli/activities_test.exs

[MER-4308](https://eliterate.atlassian.net/browse/MER-4308)
This PR verifies that an author can place an LTI tool on a page to have control over where students interact with the tool.
In addition, a small implementation is made so that when the user hovers over an LTI activity the correct text is displayed, i.e. “Insert an instance of [tool name]”.
https://github.com/user-attachments/assets/8d3763e5-25ae-45f0-bed1-c233b0f90f84
[MER-4308]: https://eliterate.atlassian.net/browse/MER-4308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4308] LTI content type button

---

lib/oli/activities.ex
lib/oli/activities/activity_registration.ex
test/oli_web/live/workspaces/course_author/overview_live_test.exs

[MER-4294](https://eliterate.atlassian.net/browse/MER-4294)
Do not list disabled LTI External Tools in the Activities section in the Project Overview page.
https://github.com/user-attachments/assets/6036d467-6587-4cf2-a202-798627808c6b
[MER-4294]: https://eliterate.atlassian.net/browse/MER-4294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4294] Do not show disabled activities in the project overview page

---

assets/src/components/content/add_resource_content/AddResourceContent.modules.scss
assets/src/components/lti/LTIExternalToolFrame.tsx
assets/src/data/persistence/lti_platform.ts
lib/oli_web/controllers/api/lti_controller.ex

[MER-4312](https://eliterate.atlassian.net/browse/MER-4312)
This PR adds a warning message below the LTI activities that have been removed/deleted at the system level.
This warning message is intended for authors when they are editing any page of the curriculum and the page has in its content any LTI activity that has been removed or deleted at the system level.
https://github.com/user-attachments/assets/6ac8edee-66e0-4192-af2b-9cacb1d37261
[MER-4312]: https://eliterate.atlassian.net/browse/MER-4312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4312] Tool removal message

---

lib/oli/activities.ex

[MER-4294](https://eliterate.atlassian.net/browse/MER-4294)
This PR excludes LTI tools that were disabled or removed at the system level, showing only LTI tools enabled to be added to a curriculum page. 
https://github.com/user-attachments/assets/cc92e9d9-9b1d-4583-9097-e0e4032e51ea
[MER-4294]: https://eliterate.atlassian.net/browse/MER-4294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4294] Enable/Disable a tool at system level - rework

---

assets/src/hooks/submit_tech_support_form.ts
lib/oli_web/components/tech_support_live.ex

Ticket: [MER-4034](https://eliterate.atlassian.net/browse/MER-4034)
This PR adds logging for failed help requests, which is important for diagnosing the cause of the failures. I set up logging on both the front-end and back-end, but we'll likely remove the front-end one.
[MER-4034]: https://eliterate.atlassian.net/browse/MER-4034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4034] Add logging on failure

---

lib/oli_web/templates/layout/delivery.html.heex

#5565 addressing MER-4536 adjusted page titles shown in browser tabs. This had an error causing "Delivery" to be shown as browser tab page title on pages using the delivery template. This corrects to show product short name from vendor properties just as in other cases addressed in that PR.

[BUG FIX] [MER-4602] fix browser tab title in delivery template

---

assets/src/components/activities/lti_external_tool/LTIExternalToolAuthoring.tsx
assets/src/components/activities/lti_external_tool/LTIExternalToolDelivery.tsx
assets/src/components/lti/LTIExternalToolFrame.tsx
assets/src/data/persistence/lti_platform.ts
lib/oli/rendering/activity/html.ex
test/oli/rendering/activity/html_test.exs
test/oli/rendering/alternatives/html_test.exs
test/oli/rendering/survey/html_test.exs
test/oli_web/controllers/user_session_controller_test.exs
test/oli_web/plugs/header_size_logger_test.exs
test/oli_web/plugs/maybe_gated_resource_test.exs

https://eliterate.atlassian.net/browse/MER-4321
Fixes several issues uncovered while testing the LTI tool launch as a student. The root cause of the issue was that there was no "id" on the model, this really should have been reading the resource ID (or activity ID) to uniquely identify the tool within the page. This is also the ID that gets passed along to the tool as part of the LTI claims. There was a little bit of work required to expose this to the LTI External Tool activity from the rendering code.
I also identified and fixed an issue where LTI tools would not load in the Instructor Preview.

[BUG FIX] [MER-4321] Rework: Student LTI tool opens in a new window

---

lib/oli_web/live/workspaces/course_author/datasets/job_shortcuts.ex

This PR fixes a datasets problem where the defined job shortcuts contained misspellings of the event subtypes for both `part_attempt_evaluated` and `page_attempt_evaluated`.  This was causing certain Dataset jobs to run and miss some results.   A workaround has been deployed on the Datasets side - which significantly lowers the priority of this issue.

[BUG FIX] [MER-4604] Fix spelling issues in defined Datasets job shortcuts

---

assets/src/components/lti/LTIExternalToolFrame.tsx

https://eliterate.atlassian.net/browse/MER-4321
Fixes an issue identified in QA where the LTI launch button was missing some text that was in the designs.

[BUG FIX] [MER-4321] Rework: Student LTI tool opens in a new window rework 2

---

assets/src/hooks/submit_tech_support_form.ts
config/dev.exs
lib/oli/help/requester_data.ex
lib/oli_web/components/common.ex
lib/oli_web/components/tech_support_live.ex
lib/oli_web/controllers/help_controller.ex
lib/oli_web/templates/layout/authoring.html.heex
lib/oli_web/templates/layout/delivery.html.heex
lib/oli_web/templates/layout/lti.html.heex
test/oli_web/controllers/help_controller_test.exs

Ticket: [MER-4034](https://eliterate.atlassian.net/browse/MER-4034)
This PR adds the captcha directly to the TechSupport LiveView, as AppSignal logs indicate the error originates there:
```
05-19-2025 10:15:41.950[application][ERROR][tokamak.oli.cmu.edu][phoenix]Error when processing help message "reCaptcha failure"
```
Additionally, this PR includes a fix for the flash message rendering twice. A custom flash implementation was added, inspired by PR: https://github.com/Simon-Initiative/oli-torus/pull/5595.
Finally, this PR updates the `knowledgebase_url` to open in a new tab (see commit: 01b6d68c748a7cf32c737049db283984ca02475a) and removes the `console.log` added in PR: https://github.com/Simon-Initiative/oli-torus/pull/5614, as it was not providing useful information. (see commit: …

[BUG FIX] [MER-4034] improvements to the torus support modal rework 2

---

assets/src/apps/scheduler/ScheduleGrid.tsx
assets/src/apps/scheduler/ScheduleLine.tsx
assets/src/apps/scheduler/scheduler-slice.ts
assets/test/scheduler/expand-collapse-schedule_test.ts

[MER-4268](https://eliterate.atlassian.net/browse/MER-4268)
This PR adds functionality to the button that collapses and expands the schedule grid in the instructor’s schedule view.
- When the user clicks Expand All, all containers in the grid will be expanded, and the button text and icon will switch to Collapse All.
- When the user clicks Collapse All, all containers in the grid will be collapsed, and the button text and icon will switch to Expand All.
Additionally, if there are no expandable or collapsible containers in the grid, the button will be disabled and a tooltip will show  **"No expandable containers available."**
https://github.com/user-attachments/assets/202966ae-6884-4713-a63a-d444a9ee088d
[MER-4268]: https://eliterate.atlassian.net/browse/MER-4268?atlOrigin=eyJpIjoiNWRkNTljN …

[FEATURE] [MER-4268] Instructor schedule expand all

---

assets/src/apps/scheduler/ScheduleGrid.tsx

[MER-4268](https://eliterate.atlassian.net/browse/MER-4268)
This PR fixes the styling of the button used to expand and collapse the schedule grid.
It adjusts the hover colors for both light and dark modes.
Also, the following rules are applied to the button styling:
- When the user clicks “expand all”: button is blue to show it is active
- When the user clicks “collapse all”: button is black again (back to default) to show it is not active 
https://github.com/user-attachments/assets/ad7af957-7b49-4b15-8e4c-534608278ad9
[MER-4268]: https://eliterate.atlassian.net/browse/MER-4268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4268] Instructor schedule expand all - rework

---

config/dev.exs

Ticket: [MER-4595](https://eliterate.atlassian.net/browse/MER-4595)
This PR adds a configuration to the development environment to prevent cron jobs from running and cluttering the IEx session console.
[MER-4595]: https://eliterate.atlassian.net/browse/MER-4595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4595] Add crontab configuration to dev environment.

---

lib/oli_web/live/workspaces/course_author/overview_live.ex

Selecting a license type in the Project Attributes section of the Project Overview page was having the effect of resetting any other unsaved attribute values in that section (Language and, for admins, Calculate Embeddings on Publish). This issue posed a nuisance for automated QA testing.
The bug was caused by an error in the state management in the event handler for selections from the license type dropdown, which is needed to maintain state to show/hide the input box for custom license details. 
This recodes to use a simple `custom_license` flag in the assigns to show/hide the details, setting on mount and updating on changes to license type. This avoids the problem of trying to do this by manipulating the involved changeset structure.

[BUG FIX] [MER-3114] Fix license selection resetting other project attributes in form

---

lib/oli/lti/platform_external_tools.ex
lib/oli_web/live/admin/external_tools/usage_view.ex
test/oli/lti/platform_external_tools_test.exs
test/oli_web/live/admin/external_tools/usage_view_test.exs

- Improved the query in `Oli.Lti.PlatformExternalTools.get_sections_with_lti_activities_for_platform_instance_id/1`
- Added new function `Oli.Lti.PlatformExternalTools.get_sections_grouped_by_platform_instance_ids/1` to enable retrieving sections for multiple platform instances. (This improves the efficiency when displaying the usage count `/admin/external_tools`)
- Fixed the sorting behaviour in `/admin/external_tools/:platform_instance_id/usage` and when sorting by _usage count_ in `/admin/external_tools`
See: https://eliterate.atlassian.net/browse/MER-4332

[ENHANCEMENT] [MER-4332] Improve efficiency of queries when retrieving LTI activity IDs by platform instance

---

lib/oli/analytics/datasets/utils.ex
test/oli/analytics/datasets/utils_test.exs

This PR adjusts the approach that Datasets infrastructure uses to determine which user ids to ignore.  The intent here is to ignore all "non students" and all students who opt out of research consent.  The previous impl was not robust against students having multiple roles (`:context_learner` and `:context_member`), which certain LMSes were assigning. 
The new approach handles this edge case.

[ENHANCEMENT] [MER-4621] Refine approach for determining student ids to ignore

---

lib/oli_web/router.ex

https://eliterate.atlassian.net/browse/MER-4640
This reverts a change that breaks LTI launch. With this plug in place, any LTI launch returns a 403 forbidden.

[BUG FIX] [MER-4640] Remove protect_from_forgery plug from LTI pipeline

---

assets/static/ebsco/login.html
lib/oli_web/endpoint.ex

The Evidence Based Management course makes use of links to research databases hosted on a site called EBSCO for various exercises. These rely on a feature of EBSCO to allow loginless access via the referrer header for origins that are whitelsted at EBSCO. However, torus links use rel="noreferrer" to suppress the referrer header for security and privacy reasons. 
This provides a wrapper or proxy page hosted on the torus server to work around this. The idea is that EBSCO links in courses will be rewritten to link instead to the proxy page, which then uses script to construct a link to EBSCO that can be clicked while not suppressing referrer. For convenience, the proxy page is coded to automatically redirect to the EBSCO site, so clicking an ebsco access page link from a course will take one …

[ENHANCEMENT] [MER-4639] add static page providing EBSCO access link w/referrer

---

assets/src/apps/scheduler/ScheduleEditor.tsx
assets/src/apps/scheduler/ScheduleGrid.tsx
assets/src/components/misc/BackdropModal.tsx

[MER-4270](https://eliterate.atlassian.net/jira/software/c/projects/MER/boards/2?selectedIssue=MER-4270)
This PR introduces a new **“View” button** to the scheduling toolbar, enabling instructors to preview how students will see the **Agenda** and **Schedule** based on the current scheduling configuration.
- Added **“View” button** between “Expand all” and “Clear” on the schedule tab toolbar.
- Clicking the button opens a **dropdown with two options**:
- **View Agenda**
- **View Schedule**
- Selecting an option opens the corresponding **student-facing view in a new tab** using the last saved schedule.
- If unsaved changes exist, a **confirmation modal** is shown:
- **“Keep editing”** brings the user back to the scheduling tool.
- **“View without saving”** proceeds with the last saved …

[FEATURE] [MER-4270] Adds support for save and preview of schedule and agenda

---

assets/src/apps/scheduler/ScheduleGrid.tsx
assets/src/apps/scheduler/ScheduleLine.tsx
assets/src/apps/scheduler/schedule-selectors.ts
assets/src/apps/scheduler/scheduler-slice.ts
assets/test/scheduler/expand-collapse-schedule_test.ts

[MER-4267](https://eliterate.atlassian.net/browse/MER-4267)
This PR introduces a filtering feature in the schedule tab that allows instructors to search for specific content by title. The main goal is to improve navigation and reduce the time instructors spend scanning through the schedule.
With this update, instructors can use a search bar to filter the content displayed in the schedule grid. The search functionality matches input text with resource titles (such as pages or containers).
When the search is cleared, the schedule view returns to its default, unfiltered state.
https://github.com/user-attachments/assets/63f0d8eb-5254-4ccf-b5e0-198ca4ea1719
[MER-4267]: https://eliterate.atlassian.net/browse/MER-4267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

[FEATURE] [MER-4267] Instructor Schedule: Adding Search

---

lib/oli/delivery/sections/section_resource_migration.ex
test/oli/delivery/sections/section_resource_migration_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4575?focusedCommentId=28576) to the comment in the ticket
On [MER-4332](https://github.com/Simon-Initiative/oli-torus/pull/5600#issuecomment-2913884490), we discovered that some queries fail when section resources were still not migrated. Specifically, queries that join with the `revisions` table using the `revision_id` field (such as `get_section_resources_with_lti_activities/1`) fail when `revision_id` is `nil` for unmigrated section resources.
The issue occurs when:
1. A section has existing section resources that have already been migrated (`revision_id` and other fields populated)
2. New section resources are added (e.g., when an author adds an LTI activity to a page and publishes updates)
3. These new section resources are created …

[BUG FIX] [MER-4575] Rework: tools not showing on products

---

lib/oli_web/controllers/lti_controller.ex

https://eliterate.atlassian.net/browse/MER-4660
When performing an LTI external tools launch, the launch was failing for some tools because the resource_link id claim payload was double nested under the "id" key.
This PR resolves the issue by removing the outer "id" key that was causing the issue.

[BUG FIX] [MER-4660] fix an issue where resource_link id is double nested

---

assets/src/components/content/Popup.tsx

Ticket: [MER-4214](https://eliterate.atlassian.net/browse/MER-4214)
This PR resolves the positioning offset issue affecting popovers. From the [documentation](https://www.npmjs.com/package/react-tiny-popover):
```
reposition={false} // prevents automatic readjustment of content position that keeps your popover content within its parent's bounds
```
[MER-4214]: https://eliterate.atlassian.net/browse/MER-4214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4214] Fix popover positioning offset issue

---

assets/src/apps/scheduler/DragBar.tsx
assets/src/apps/scheduler/PageDragBar.tsx
assets/src/apps/scheduler/PageScheduleLine.tsx
assets/src/apps/scheduler/ScheduleGrid.tsx
assets/src/apps/scheduler/ScheduleLine.tsx
assets/src/apps/scheduler/schedule-selectors.ts
assets/src/apps/scheduler/scheduler-slice.ts
assets/src/components/misc/icons/Icons.tsx
assets/test/scheduler/agenda-visibility_test.tsx
assets/test/scheduler/expand-collapse-schedule_test.ts
lib/oli/delivery/sections/scheduling.ex

[MER-4344
](https://eliterate.atlassian.net/jira/software/c/projects/MER/boards/2?selectedIssue=MER-4344)
This PR implements the ability for instructors to **view and restore previously removed items** from the course schedule, providing flexibility to experiment with and adjust scheduling decisions.
- Adds a **"Filter"** button to the scheduling tab toolbar.
- Introduces a **"Show Removed"** checkbox in the filter dropdown:
- Disabled if no items have been removed.
- Enabled if one or more items (pages, modules, sections, units) have been removed.
- When "Show Removed" is selected:
- Removed items are displayed:
- **Rows** of removed content are styled in **red**.
- **Bars** of removed units/modules/sections use a **striped design** (per Figma spec).
- The schedule layout updates to …

[ENHANCEMENT] [MER-4344] Re-add removed item to schedule

---

assets/src/apps/delivery/Delivery.tsx
assets/src/apps/delivery/components/ActivityRenderer.tsx
assets/src/apps/delivery/layouts/deck/DeckLayoutFooter.tsx
assets/src/apps/delivery/layouts/deck/DeckLayoutView.tsx
assets/src/apps/delivery/layouts/deck/components/EverappRenderer.tsx
assets/src/apps/delivery/store/features/adaptivity/actions/triggerCheck.ts
assets/src/apps/delivery/store/features/groups/actions/deck.ts
assets/src/apps/delivery/store/features/page/actions/loadInitialPageState.ts
assets/src/apps/delivery/store/features/page/slice.ts
assets/src/data/persistence/blob.ts
assets/src/data/persistence/extrinsic.ts
assets/src/data/persistence/state/intrinsic.ts
config/config.exs
config/runtime.exs
lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
lib/oli/delivery/text_blob.ex
lib/oli/delivery/text_blob/storage.ex
lib/oli_web/controllers/api/blob_storage_controller.ex
lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live_session_plugs/init_page.ex
lib/oli_web/router.ex
test/oli_web/controllers/api/blob_storage_controller_test.exs

This PR introduces a (configurable, optional) replacement for the database backed storage for global and page attempt level.   Prior to this PR, the `users` and `resource_attempts` each used a `state` field to store arbitrary JSON blobs.  This feature is used by the Adaptive Player to store EverApp and Simulation data, but the large of amount of data being stored has proved to be a performance and scalability issue.   We solve these performance issues by 1) Storing these large JSON blobs in S3 storage and 2) Eliminating all of the server JSON encoding and decoding by providing a pure `plain/text` API and distributing the JSON encoding/decoding to the client browser.
To enable this new "text blob storage", we set a new run time environment variable `BLOB_STORAGE_USE_DEPRECATED_API=false`. …

[FEATURE] [MER-4647] Text blob storage replacement for main DB extrinsic storage

---

lib/oli/delivery/settings.ex
lib/oli_web/live_session_plugs/init_page.ex
test/oli/delivery/settings_test.exs

Score as you go assessments (i.e., those with `batch_score: false`) use the `:max_attempts` to control the number of times a student can retry each activity with in the single page attempt.  Given that time limits and hard deadlines with auto submit can finalize a score as you attempt - we needed a way to prevent the student from starting another attempt (as the original prologue logic was still applying `:max_attempts` to the number of page attempts).  
This PR adjusts the logic used to determine if a new page attempt can be started, taking into account our desire to limit Score as you go to 1 page attempt.

[ENHANCEMENT] [MER-4644] Limit score as you go to 1 completed attempt

---

lib/oli_web/live/sections/enrollments_table_model.ex

[MER-4611](https://eliterate.atlassian.net/browse/MER-4611)
This PR updates the student progress report under `Insights > Content` to remove the “Type” column from the on-screen view.
Since only students are shown in the report, the column wasn’t adding value and could cause confusion. This change helps simplify the view and make the information clearer for instructors.
- Before 
- After
[MER-4611]: https://eliterate.atlassian.net/browse/MER-4611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4611] Remove type column from student progress report

---

assets/src/components/parts/janus-text-flow/QuillFIBOptionEditor.tsx

This PR contains 2 changes mentioned in the comment:
-> can the correct check also get that blue color?
-> Can the quotation mark be removed? Also is there any way this can be one line? Maybe make the dropdown just a little narrower (where “blank 2” is in the image)?  Maybe removing the quotation mark is enough.

[BUG FIX] [MER-4645] Minor updates to FITB

---

lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/prologue_live_test.exs

Scoring statement message considers both the scoring policy (batch_scoring) and scoring strategy (scoring_strategy_id)
Follows new format: "For [this assignment / each question], your score will be determined by [your best attempt / your last attempt / the average of your attempts]"
---
The new implementation generates messages based on:
Scoring Policy:
- batch_scoring: true → "this assignment" (score at the end)
- batch_scoring: false → "each question" (score as you go)
Scoring Strategy:
- Strategy ID 1 → "the average of your attempts"
- Strategy ID 2 → "your best attempt"
- Strategy ID 3 → "your last attempt"
- Strategy ID 4 → "the total sum of your attempts"
--- 
See: https://eliterate.atlassian.net/browse/MER-4642

[ENHANCEMENT] [MER-4642] Update scoring statement for assesments

---

lib/oli/delivery/settings.ex
lib/oli_web/live/delivery/student/lesson_live.ex
test/oli/delivery/settings_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4648) to the ticket
- When a student is in the browser and the time limit is reached, a js script auto-triggers a click on the submit button.
- When the student closes the browser and the time limit is reached, an oban job auto-submits the attempt (one minute after the time limit is reached)
So, there was a one-minute window that allowed the student to re-enter the assessment and make changes to the responses. That bug was fixed on [MER-3931](https://github.com/Simon-Initiative/oli-torus/pull/5223)
The logic for determining the deadline was considering a soft end date as part of the logic. According to the [Schedule and Assessment Settings Logic](https://docs.google.com/drawings/d/1LDzW7DH6fX7BW6oFBYgPR9H2ZkqHn-YP5JuvcfSq1xw/edit) only …

[BUG FIX] [MER-4648] Autosubmission not working correctly

---

lib/oli_web/live/grades/gradebook_table_model.ex
test/oli_web/live/grades/gradebook_table_model_test.exs

Fix the formatting of the score when viewing it inside the Student Report page (`/sections/:course_section/student_dashboard/:id/quizz_scores`)

[BUG FIX] [MER-4682] Instructor Quiz Scores: Format scores up to 2 decimal places

---

lib/oli/delivery/sections/section_resource_depot.ex
lib/oli/grading.ex
lib/oli/grading/gradebook_score.ex
lib/oli_web/components/delivery/quiz_scores/quiz_scores.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
lib/oli_web/live/delivery/student_dashboard/components/helpers.ex
lib/oli_web/live/delivery/student_dashboard/student_dashboard_live.ex
lib/oli_web/live/grades/gradebook_table_model.ex
lib/oli_web/live/grades/gradebook_view.ex
lib/oli_web/live/sections/overview_view.ex
lib/oli_web/live/workspaces/utils.ex
test/oli_web/live/delivery/instructor_dashboard/insights/quiz_scores_tab_test.exs
test/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live_test.exs
test/oli_web/live/delivery/student_dashboard/components/progress_tab_test.exs
test/oli_web/live/delivery/student_dashboard/components/quizz_scores_tab_test.exs
test/oli_web/live/workspaces/instructor/dashboard_live_test.exs
test/support/test_helpers.ex

Ticket: [MER-4606](https://eliterate.atlassian.net/browse/MER-4606)
This PR replaces many occurrences of **_Quiz_** with **_Assessment_**.
[MER-4606]: https://eliterate.atlassian.net/browse/MER-4606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4606] rename and update assessment scores

---

priv/repo/migrations/20250625153539_change_sr_datatypes.exs
test/oli/delivery/sections/data_types_test.exs

This PR changes the data type of the `title`, `poster_image` and `intro_video` fields of the `section_resources` table from `VARCHAR(255)` to `TEXT`, thus matching the same type for those fields from the `revisions` table.  
This prevents project resources with titles greater than 255 characters from breaking the publication process.
The added unit test fails without the migration.  With the migration in place it succeeds.

[BUG FIX] [MER-4724] Fix data types of section resource fields

---

lib/oli/grading.ex
lib/oli_web/components/delivery/students/students.ex
lib/oli_web/controllers/delivery_controller.ex
test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs

Ticket: [MER-4738](https://eliterate.atlassian.net/browse/MER-4738)
This PR makes student name and email sorting case-insensitive in customer reports and UI tables, in the areas specified in the ticket.
Note: The approach used here doesn't prevent a random order when names are identical. For example, having `Smith, Joe` and `smith, joe `could result in:
```
[Smith, Joe, smith, joe]
or
[smith, joe, Smith, Joe]
```
[MER-4738]: https://eliterate.atlassian.net/browse/MER-4738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENHANCEMENT] [MER-4738] student name sorting in customer reports is case insensitive

---

lib/oli_web/components/delivery/students/students.ex
lib/oli_web/controllers/delivery_controller.ex

Tickets: [MER-4742](https://eliterate.atlassian.net/browse/MER-4742), [MER-4743](https://eliterate.atlassian.net/browse/MER-4743)
This PR fixes an issue where having empty emails on the Student Report page causes an error when sorting by that column or downloading the report. The error occurred because `String.downcase/2` expects a string as its first argument, but emails are `nil` for guest users.
https://github.com/user-attachments/assets/0217481f-05c7-4ecc-b7ab-1721f12f2d6b
[MER-4742]: https://eliterate.atlassian.net/browse/MER-4742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MER-4743]: https://eliterate.atlassian.net/browse/MER-4743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4742] [MER-4743] Fix issue when sorting by empty emails -- case: guess users

---

lib/oli/delivery/evaluation/rule.ex
test/oli/delivery/evaluation/rule_eval_test.exs

[MER-4733](https://eliterate.atlassian.net/browse/MER-4733)
Previously, the evaluation logic for numeric answers in scientific notation used only an absolute tolerance (`0.00001`) when comparing floating-point values. This approach caused a bug where, for very small numbers (e.g., `2.2e-10`), the absolute tolerance was much larger than the actual values being compared. As a result, answers with different exponents (such as `2.2e-10` and `2.2e-11`) were incorrectly considered equal, allowing students to submit answers with the wrong exponent and still be marked correct.
**Example of the bug:**
- Expected answer: `2.2e-10`
- Student input: `2.2e-11`
- Result: Marked as correct (incorrect behavior)
This PR updates the float comparison logic to use only a relative tolerance when comparing …

[BUG FIX] [MER-4664] Fix Scientific Notation Failure On Very Small Floats

---

lib/oli/delivery/sections.ex
test/oli/delivery/sections_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4756) to the ticket
The issue was that the retake mode was not being copied into the section resource insert when creating a new course

[BUG FIX] [MER-4756] Targeted retake not persisting from project to section

---

assets/src/components/activities/common/ScoreAsYouGoSubmitReset.tsx
lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
lib/oli_web/live/delivery/student/lesson/components/one_at_a_time_question.ex
test/oli_web/live/delivery/student/lesson/components/one_at_a_time_question_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4761) to the ticket
This PR reverted and adjusted some changes made on [MER-4348](https://github.com/Simon-Initiative/oli-torus/pull/5586), to allow the one-question-at-a-time component to support both `score as you go` and `score at the end` configurations.
https://github.com/user-attachments/assets/1e2a0ad4-cbfa-48ab-90d5-0c3cecdc3cb9
No changes were made to the `score as you go` case.
[MER-4348]: https://eliterate.atlassian.net/browse/MER-4348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4761] One question at a time (with score at the end)

---

lib/oli_web/live/sections/assessment_settings/settings_table.ex
test/oli_web/live/sections/assessment_settings/settings_live_test.exs

Ticket: [MER-4077](https://eliterate.atlassian.net/browse/MER-4077)
This PR adds the ability to remove an assessment’s password by leaving the input field empty.
https://github.com/user-attachments/assets/0698b4fc-680b-47b7-be6c-fe08a27eca9f
[MER-4077]: https://eliterate.atlassian.net/browse/MER-4077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4077] Add ability to remove password in assessment settings

---

lib/oli_web/live/delivery/student/index_live.ex

[MER-4438](https://eliterate.atlassian.net/browse/MER-4438)
This PR fixes a visual issue in the `My Assignments` section on the student’s home page, where the Unit and Module texts were overflowing the container and hiding content and icons. 
Now, the texts respect the maximum width defined, wrapping to a new line if necessary to prevent overlapping or content going outside the container. 
Additionally, the container height adjusts automatically to display the full content.
- Before
- After
[MER-4438]: https://eliterate.atlassian.net/browse/MER-4438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BUG FIX] [MER-4438] My Assignments text formatting is wonky

---

lib/oli/accounts/schemas/author.ex
lib/oli/accounts/schemas/user.ex
lib/oli/utils.ex
lib/oli_web/live/author_settings_live.ex
lib/oli_web/live/user_settings_live.ex
lib/oli_web/live/users/author_detail_view.ex
test/oli/delivery/sections/enrollments_browse_test.exs
test/oli_web/live/admin_live_test.exs
test/oli_web/live/author_settings_live_test.exs
test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs
test/oli_web/live/user_settings_live_test.exs
test/oli_web/live/users/user_detail_view_test.exs

[MER-4686](https://eliterate.atlassian.net/browse/MER-4686)
This PR fixes the bug  view that allowed leaving the First Name and Last Name fields empty and saving the changes in the Account Settings. Now, the First Name cannot be empty and the Last Name must have at least two non-whitespace characters.
Additionally, the Full Name is automatically updated on the screen as the First Name or Last Name fields are edited. If the entered values do not meet the validation requirements, error messages are shown on the corresponding fields.
Both the First Name and Last Name are saved without leading or trailing spaces, as was already the case. This applies both when a user edits their own account and when an administrator edits another user’s account.
Author Account Settings …

[BUG FIX] [MER-4686] Can leave names empty on account editing

---

assets/src/data/content/writers/renderer.tsx

[Link](https://eliterate.atlassian.net/browse/MER-4440?atlOrigin=eyJpIjoiOTlkZTlhOTQzM2YwNDU2OThhNzRjZDI3YzRiZTkzYzQiLCJwIjoiaiJ9) to the ticket
The issue was that the HtmlContentModelRenderer component did not have the required [`content`](https://github.com/Simon-Initiative/oli-torus/blob/cab4c4a84b19e152bb0baa7bf35cc1435d14c071/assets/styles/common/elements.scss#L49) class that adds spacing between p tags (line height and margin bottom)

[BUG FIX] [MER-4440] No paragraph spacing for long questions

---

lib/oli_web/live/curriculum/container/container_live.ex
lib/oli_web/live/curriculum/container/container_live_helpers.ex
lib/oli_web/live/resources/pages_view.ex
lib/oli_web/live/workspaces/course_author/curriculum_live.ex
lib/oli_web/live/workspaces/course_author/pages_live.ex
test/oli_web/live/workspaces/course_author/curriculum_live_test.exs
test/oli_web/live/workspaces/course_author/pages_live_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4689) to the ticket
The issue was that the `author_id` was not being updated when editing a revision.
In this PR I also refactored some code to avoid event-handling logic duplication between different liveviews
https://github.com/user-attachments/assets/8241d106-0aef-4766-ad9e-0539ecee29b9
https://github.com/user-attachments/assets/e7977b81-0093-4daa-a41d-5102167f5efd

[BUG FIX] [MER-4328] Page edits not attributed to correct author

---

lib/oli/delivery/sections.ex
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex
lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
test/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab_test.exs

Ticket: [MER-4685](https://eliterate.atlassian.net/browse/MER-4685)
This PR restores the subobjectives on both the Section Learning Objectives page (Insight Tab) and the Student Learning Objectives page (Overview Tab).
https://github.com/user-attachments/assets/1aef234a-8958-4e3a-9ccc-ff9942712cd5
Note: For the following URL: http://localhost/sections/coursesection2/student_dashboard/3/learning_objectives?limit=10&sort_by=student_proficiency_obj the page crashes. This bug already exists in master. It **only** happens when the application starts, not when we visit the page.
Here is a snippet of the error trace:
```
[error] GenServer #PID<0.1186.0> terminating
** (FunctionClauseError) no function clause matching in OliWeb.Delivery.StudentDashboard.StudentDashboardLive.handle_event/3
(oli …
```

[BUG FIX] [MER-4685] sub objectives missing from instructor insights tab

---

lib/oli_web/components/utils.ex
lib/oli_web/live/common/utils.ex
lib/oli_web/live/workspaces/instructor/index_live.ex
lib/oli_web/live/workspaces/student.ex
test/oli_web/live/workspaces/instructor_test.exs
test/oli_web/live/workspaces/student_test.exs

[MER-4683](https://eliterate.atlassian.net/browse/MER-4683)
This PR adds the display of the course start and end dates, as well as instructor names, on the “My Courses” page for both students and instructors. 
This information is now visible directly on each course card.
**Instructor view**
**Student view**
[MER-4683]: https://eliterate.atlassian.net/browse/MER-4683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4683] Critical information missing from my courses page

---

lib/oli/delivery/attempts/activity_lifecycle.ex
test/oli/delivery/attempts/attempt_reset_test.exs

This PR changes the "reset attempt" logic to carry forward the `selection_id` of the original attempt in creating the new attempt.   Without this, Score as you Go activities that had multiple attempts could not be migrated to new page attempts correctly.  The migration logic basically would fail to pair up the corresponding attempt prototype for an activity bank selection, resulting in the creation of a different question instead of carrying forward the same question.

[BUG FIX] [MER-4793] Preserve selection id in new attempt creation

---

lib/oli_web/live/sections/assessment_settings/settings_table_model.ex

In the table used in Manage Section/Assessment Settings, the scoring strategy shown as "Last" was inconsistent with the label used in authoring, leading to confusion. This changes the label there to "Most Recent" to match the label used in authoring.

[BUG FIX] [MER-4758] change "Last" to "Most Recent" in assessment settings to match authoring

---

lib/oli_web/live/workspaces/student.ex
test/oli_web/live/workspaces/student_test.exs

Prevent search input submission to avoid LiveView reloads
The search is already handled on each keystroke (with debounce), so form submission via Enter is unnecessary and causes a full LiveView reload.
Also ignore nil fields in sections' instructors / titles (See: https://github.com/Simon-Initiative/oli-torus/pull/5511)

[BUG FIX] [MER-4690] Student search field does not work for specific users

---

lib/oli_web/live/delivery/student/learn_live.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/learn_live_test.exs

[MER-4684](https://eliterate.atlassian.net/browse/MER-4684)
This PR introduces changes to ensure that due and available dates are always displayed, regardless of whether the course resources have a schedule set or not.
If the resources don’t have a schedule set, it will display:
`Available: Now         Due by: None`
- Gallery view
- Outline view
[MER-4684]: https://eliterate.atlassian.net/browse/MER-4684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4684] Add available dates to student assignment UI - rework

---

lib/oli_web/live/delivery/student/assignments_live.ex
lib/oli_web/live/delivery/student/utils.ex
test/oli_web/live/delivery/student/assignments_live_test.exs

[MER-4684](https://eliterate.atlassian.net/browse/MER-4684)
This PR is a rework to address the issues found during QA based on the expectations defined in the related ticket.
It specifically aims to fix the behavior mentioned in [these comments](https://eliterate.atlassian.net/browse/MER-4684?focusedCommentId=31148).
I added a private `format_date/3` function in `AssignmentsLive` module to handle cases where the end date is nil, displaying the text "None".
I chose not to modify the public `FormatDateTime.to_formatted_datetime/3` function to return "None" when the end date is nil, as I’m unsure whether such a change would conflict with expected behavior elsewhere in the application.
[MER-4684]: https://eliterate.atlassian.net/browse/MER-4684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

[FEATURE] [MER-4684] Add available dates to student assignment UI- Rework 2

---

lib/oli_web.ex
lib/oli_web/components/delivery/utils.ex
lib/oli_web/components/tech_support_live.ex
lib/oli_web/components/utils.ex
lib/oli_web/views/delivery_view.ex
test/oli_web/components/tech_support_live_test.exs
test/oli_web/components/utils_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4689?focusedCommentId=30821) to the comment in the ticket
This bug existed before the introduction of MER-4689. The issue occurred when guest users intended to send a support message within a course section; the support form has some hidden fields (name, email) that are populated with the user assigned in the socket. Since guest users have those fields empty, the changeset validation failed on the form submission.
The fix identifies when a guest user is logged in and shows those fields (name, email) in the form for the user to complete.
This PR also refactors the `user_is_guest?` function to support both `assigns` or `session` as an argument, and moves that function from the deprecated `OliWeb.Components.Delivery.Utils` module to the …

[BUG FIX] [MER-4689] Support modal routing by publisher - rework

---

lib/oli/delivery/attempts/activity_lifecycle/evaluate.ex
lib/oli/delivery/attempts/core.ex
lib/oli_web/controllers/page_delivery_controller.ex
lib/oli_web/live_session_plugs/init_page.ex

Fixes an issue where the adaptive player was not working properly in review mode.
The issue was caused from the migration from resource.state storage to text blob storage, where the necessary state for review mode was trying to be loaded via the old resource.state method even when the system is configured to use the new blob storage.
The fix here is to use the new blob storage mechanism to load state when the system is configured to use this storage.

[BUG FIX] [MER-4814] cant review attempts in adaptive pages

---

lib/oli/delivery/sections/section_cache.ex
lib/oli/utils/db_seeder.ex
test/support/factory.ex

[MER-4730](https://eliterate.atlassian.net/browse/MER-4730)
This PR adds and updates module documentation related to deprecations and usage guidance.
- **SectionCache**: marked as deprecated and added a clear notice to avoid introducing new keys or logic. It also points developers to use `Oli.Delivery.Sections.SectionResourceDepot` instead.
- **SectionResourceDepot**: left unchanged, as its existing documentation already provides enough clarity.
- **Oli.Seeder**: marked as deprecated in the module documentation and replaced by `Oli.Factory`.
**Note**: @deprecated annotations were intentionally not added to each function, since they produce warnings during test runs and clutter the output unnecessarily.
- **Oli.Factory**: documentation was added to establish it as the canonical way of …

[ENHANCEMENT] [MER-4730] Improve modules documentation

---

lib/oli/delivery/paywall.ex
lib/oli/delivery/sections.ex
lib/oli/delivery/sections/browse.ex
lib/oli/interop/custom_activities/authorizations.ex
lib/oli/interop/custom_activities/registration.ex
lib/oli_web/components/delivery/utils.ex
lib/oli_web/controllers/delivery_controller.ex
lib/oli_web/live/workspaces/instructor/index_live.ex
test/oli/sections_test.exs

[MER-4078](https://eliterate.atlassian.net/browse/MER-4078)
This PR updates Torus to treat users with the Canvas "Designer" role (represented as ContentDeveloper in LTI) as instructors throughout the platform. Previously, Designers were incorrectly mapped to students, preventing them from configuring or managing course sections. With this change, both Instructors and Designers are recognized as instructors in the system.
- The LTI role ContentDeveloper is now included wherever instructor roles are checked (e.g., enrollments, permissions, filters, and UI helpers).
- All queries and helper functions that previously only considered context_instructor now also include context_content_developer.
💡 **Note:** The TA role was already mapped to instructor in Torus, so no changes were required for …

[ENHANCEMENT] [MER-4078] Designer or TA Role in Canvas Does Not Work

---

.github/actions/amazon-linux-builder/Dockerfile

This PR fixes the version of OTP that was failing to be downloaded because that specific version does not exist in the available downloads:

[ENHANCEMENT] [MER-4731] Upgrade Elixir to 1.18.4 and Erlang to OTP 28.0.2

---

.github/actions/amazon-linux-builder/Dockerfile

The JIT compiler in OTP 28.0 has known compatibility issues with certain versions of GCC on Amazon Linux 2. Disabling JIT still gives a fully functional Erlang/OTP installation, just without JIT optimizations.
This fix adds the --disable-jit flag to the OTP configure command in the amazon-linux-builder image. This disables the Just-In-Time compiler that was causing the segmentation fault.
In the future, we will probably want to upgrade to a newer version of Amazon Linux 2023 or alternatively use the docker container for deployments moving forward.

[CHORE] [MER-0000] disable JIT to restore amazon linux builder

---

assets/css/bootstrap-shims.css
assets/css/table.css
lib/oli_web/components/delivery/buttons.ex
lib/oli_web/components/delivery/content/card_highlights.ex
lib/oli_web/components/delivery/content/content.ex
lib/oli_web/components/delivery/content/content_table_model.ex
lib/oli_web/components/delivery/content/multi_select.ex
lib/oli_web/components/delivery/content/progress.ex
lib/oli_web/icons.ex
lib/oli_web/live/common/chip.ex
lib/oli_web/live/common/paging.ex
lib/oli_web/live/common/search_input.ex
lib/oli_web/live/common/sortable_table/striped_table.ex
lib/oli_web/live/common/table/striped_paged_table.ex
lib/oli_web/live/delivery/instructor_dashboard/html_components.ex
test/oli_web/live/delivery/instructor_dashboard/insights/content_tab_test.exs
test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs
test/oli_web/live/delivery/student_dashboard/student_dashboard_live_test.exs

[MER-4693](https://eliterate.atlassian.net/browse/MER-4693)
This PR introduces a set of UI improvements to the `Content` tab in the instructor `Insights` view.
A new reusable table component was created, implementing zebra striping and following the visual style defined in Figma. This component is intended to be used across future views.
Additionally, several components were created or improved to promote reusability in upcoming tickets:
- A chip component to visually represent proficiency levels (green for high, orange for medium, red for low, gray for not enough data)
- An updated search input component (OliWeb.Common.SearchInput).
- An improved progress filter component (OliWeb.Delivery.Content.Progress) to align with the new filtering interface
- A new multi-select component …

[FEATURE] [MER-4693] Insights content table UI

---

lib/oli/delivery/metrics.ex

[Ticket](https://eliterate.atlassian.net/browse/TRIAGE-1802) Background: At one time we found Logic and Proofs was causing divide-by-zero exceptions in certain proficiency metric calculations done within queries containing divisions. The queries were not protecting against possible divide-by-zero, but this was usually harmless as they normally find nulls rather than explicit zeros for total number of first attempts, and nulls in calculations are OK (turning all results to null). However Logic and Proofs evidently can give rise to zeros, perhaps because of quirks in the LogicLab activity implementation which is an outlier among torus activities in several respects. And no comment in the code gives any argument why zeros couldn't arise. 
That was fixed with …

[BUG FIX] [MER-4683] fix proficiency queries to avoid divide by zero in Logic course

---

lib/oli/delivery/attempts/core.ex
test/oli/delivery/attempts/core_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4860) to the ticket
This PR enhances the performance of `get_graded_resource_access_for_context` by utilizing the SectionResourceDepot to retrieve the graded page resource IDs, thereby eliminating all joins in the query.
This PR also adds tests to the `Oli.Delivery.Attempts.Core` module

[ENHANCEMENT] [MER-4860] Gradebook view uses expensive query

---

lib/oli/release.ex

[MER-4836](https://eliterate.atlassian.net/browse/MER-4836)
Students got 500 errors when accessing sections with AI Assistant enabled because the required GenAI infrastructure data (registered models, service configs, feature configs) wasn't seeded in the database.
During deployment, seeds were failing with `Ecto.ChangeError` for encrypted fields because `Oli.Vault` wasn't initialized when running seeds in release context ([example failing job](https://github.com/Simon-Initiative/oli-torus/actions/runs/17045887187/job/48321457692)):
```
** (Ecto.ChangeError) value `"model-key"` for `Oli.GenAI.Completions.RegisteredModel.api_key` in `insert` does not match type Oli.Encrypted.Binary
```
Added `Oli.Vault.start_link()` to `Oli.Release.seed()` to ensure Vault is initialized before executing …

[BUG FIX] [MER-4836] Add Vault Init on Release Seed Function

---

lib/oli/delivery/metrics.ex

https://github.com/Simon-Initiative/oli-torus/pull/5805 fixed divide-by-zero occuring in proficiency queries that include divisions. This addition prevents divide-by-zero at another place in the metric computations missed in that PR, namely the bucketing calculation for container proficiences. 
Again it seems to be only the LogicLab activity used in Logic and Proofs course that gives rise to zero values (as opposed to nulls) that trip divide-by-zero errors here. But code ought to be safe against these. See original PR for detail.

[BUG FIX] [MER-4867] fix divide-by-zero in proficiency bucket calculation

---

lib/oli/delivery/metrics.ex

https://github.com/Simon-Initiative/oli-torus/pull/5813 prevented divide-by-zero in routine `bucket_into_container_totals`. This extends that to prevent it in a second location missed by that PR, routine `bucket_into_container_mode ` Have examined all occurrences of / in metrics.ex to check for others.
Also minor recoding to use if/else rather than cond.

[BUGFIX] [MER-4867] fix bucketing divide by zero, location 2

---

assets/tailwind.tokens.js
lib/oli_web/components/delivery/content/content_table_model.ex
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex
lib/oli_web/live/common/sortable_table/striped_table.ex
lib/oli_web/live/common/table/striped_paged_table.ex
lib/oli_web/live/delivery/instructor_dashboard/html_components.ex
lib/oli_web/live/dev/tokens_live.ex
test/oli_web/live/delivery/instructor_dashboard/insights/learning_objectives_tab_test.exs

[MER-4699](https://eliterate.atlassian.net/browse/MER-4699)
This PR implements visual changes to the instructor’s `Learning Objectives` view, aligning it with the style defined in Figma. 
Enhancements have been introduced to improve readability, such as zebra striping, a sticky header when scrolling, and a redesigned toolbar for filters and search. Row visual states (default, hover, and selected) have been updated for greater clarity, and the proficiency column now uses colored chips to represent each status.
https://github.com/user-attachments/assets/c4dd2db3-fd69-4877-948c-4d14a1a92b08
[MER-4699]: https://eliterate.atlassian.net/browse/MER-4699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4699] Learning Objectives Table UI

---

config/runtime.exs
lib/oli/analytics/xapi/pipeline_config.ex

Bug Fixed: MER-3833 - Incorrect environment variable for batch_timeout
Problem: Both lib/oli/analytics/xapi/pipeline_config.ex:36 and config/runtime.exs:237 were incorrectly
using "XAPI_BATCHER_CONCURRENCY" as the environment variable for batch_timeout.
Solution: Changed the environment variable name to the correct "XAPI_BATCH_TIMEOUT" in both files.

[BUG FIX] [MER-3833] Fix batch_timeout variable name bug

---

assets/src/components/activities/common/ScoreAsYouGoSubmitReset.tsx
lib/oli/delivery/attempts/activity_lifecycle.ex
lib/oli/delivery/attempts/activity_lifecycle/roll_up.ex
test/oli/delivery/attempts/activity_lifecycle/roll_up_fix_bad_records_test.exs
test/oli/delivery/submission_test.exs

Here's a detailed description of the three-pronged approach to address the race condition issues which are affecting (but not caused by) Score as you Go.  I believe this issue has been in the codebase for quite some time, but we never saw reports about it because up until this point in time, there had never been a way to "reset" an activity in a high stakes context.  
The original implementation had a critical race condition where multiple concurrent reset requests could:
- Read the same activity attempt simultaneously
- Both calculate the same "next attempt number"
- Create duplicate attempts with identical attempt numbers
- Corrupt the scoring calculations that depend on sequential attempt numbering 
Serializable Isolation Level: The transaction runs with isolation: :serializable, the …

[BUG FIX] [MER-4880] Fix for the activity reset race condition

---

assets/css/bs/tooltip.css
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex
lib/oli_web/live/common/sortable_table/striped_table.ex
test/oli_web/live/delivery/instructor_dashboard/insights/learning_objectives_tab_test.exs
test/oli_web/live/delivery/student/lesson_live_test.exs

[MER-4699](https://eliterate.atlassian.net/browse/MER-4699)
This PR addresses several issues previously reported during the QA process.
- Fixed a bug that caused empty rows to appear in the table after applying filters.
This was resolved by adjusting the logic used to generate and render expandable rows for each data entry.
- Fixed an issue where the `Proficiency Distribution` tooltip content would appear underneath the column header when scrolling the table.
- Updated the background, text, and border colors of the tooltip in the `Student Proficiency` column to match the Figma design specifications.
https://github.com/user-attachments/assets/42b1bf27-16e4-4291-893d-dbb99f2403c1
[MER-4699]: https://eliterate.atlassian.net/browse/MER-4699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

[FEATURE] [MER-4699] Learning objectives table UI - rework

---

lib/oli/authoring/course.ex
lib/oli_web/live/projects/table_model.ex
test/oli_web/live/projects_live_test.exs
test/support/factory.ex

[MER-4669](https://eliterate.atlassian.net/browse/MER-4669)
This PR introduces two changes requested during the QA process
- The `Created By` column has been updated so that the project creator’s name is now a clickable link that navigates to the author’s detail view.
- The `Institution` column has been removed from the table, since there is no way to associate an institution with a project, as confirmed in conversation with Jess.
https://github.com/user-attachments/assets/e2d95fef-6942-464f-8f65-2468203a07e7
[MER-4669]: https://eliterate.atlassian.net/browse/MER-4669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4669] Browse All Projects Information - Rework

---

lib/oli/delivery/sections/section_resource_migration.ex
lib/oli/delivery/sections/updates.ex
test/oli/delivery/sections/section_resource_migration_test.exs
test/oli/sections_test.exs

[Link](https://eliterate.atlassian.net/browse/MER-4854) to the ticket
https://github.com/user-attachments/assets/a28bf790-c65f-404d-9302-d87c3db96330
https://github.com/user-attachments/assets/3e70d2c0-c2d0-453d-a757-fb26587ba447
When we improved the app's performance by implementing the SectionResourceDepot, we extended the `section_resources` table to include/replicate some fields from the revision (such as the `graded` field). This optimization eliminated the need for four joins to retrieve revision data for a specific section resource, instead providing all necessary data directly in the Depot's section resource record.
When an author made minor changes to a page (e.g., changing "PAGE_A" from `graded: false` to `graded: true`) and published those changes, the updates were not …

[BUG FIX] [MER-4854] Course with scored pages has no assignments

---

assets/src/hooks/evaluate_mathjax_expressions.ts
assets/src/hooks/highlight_code.ts
assets/src/hooks/index.ts
assets/src/hooks/page_content_hooks.ts
assets/src/phoenix/app.ts
assets/styles/common/elements.scss
lib/oli_web/components/layouts/student_delivery_lesson.html.heex
lib/oli_web/templates/layout/authoring.html.heex
lib/oli_web/templates/layout/chromeless.html.heex
lib/oli_web/templates/layout/delivery.html.heex
lib/oli_web/templates/layout/delivery_from_payment.html.heex

This addresses two issues with code block styling in delivery:
[MER-4871 ](https://eliterate.atlassian.net/browse/MER-4871) Even though the `highlightjs` syntax highlighting script was being loaded by the page, syntax highlighting was not getting applied in delivery. This happened because the highlightjs processing of code elements on the page was not getting kicked off at the right time for a LiveView page. Added `HighlightCode` hook for this purpose. Wrapped together with `EvaluateMathJaxExpressions` in new `PageContentHooks` composite hook to execute both over the same element scope to find and adjust content elements on page. 
[MER-4754](https://eliterate.atlassian.net/browse/MER-4754) Code line numbering as in legacy was not being done. This implements via the …

[BUG FIX] [MER-4871] [MER-4754] fix code syntax highlighting & add line numbering

---

lib/oli_web/controllers/api/attempt_controller.ex

We now handle correctly the `:already_reset` case, but it is now leading to a flood of AppSignal errors.  This disables those for now.

[ENHANCEMENT] [MER-4890] AppSignal: Ignore already-reset failures

---

lib/oli/rendering/content.ex
lib/oli_web/controllers/api/attempt_controller.ex
test/oli/rendering/content/html_test.exs

Fixes the longstanding AppSignal error `** (RuntimeError) Content element is invalid`
```
%{"model" => [%{"children" => [%{"text" => "Regardless of the tool you might use to check these columns, first try to briefly explain programmatically how you might examine these fields. Feel free to describe your approach using pseudocode. Feel free to...
```
```
lib/oli/utils/appsignal.ex:21 Oli.Utils.Appsignal.capture_error/2
lib/oli/utils.ex:41 Oli.Utils.log_error/2
lib/oli/rendering/content.ex:470 Oli.Rendering.Content.render/3
lib/oli/rendering/activity/markdown.ex:22 Oli.Rendering.Activity.Markdown.activity/2
lib/oli/rendering/elements.ex:42 anonymous fn/4 in Oli.Rendering.Elements.render/3
lib/enum.ex:2531 Enum."-reduce/3-lists^foldl/2-0-"/3
lib/oli/rendering/elements.ex:31 …
```

[BUG FIX] [MER-4894] AppSignal: Render malformed content item

---

lib/oli/authoring/course.ex
lib/oli_web/live/common/sortable_table/striped_table.ex
lib/oli_web/live/products/products_table_model.ex
lib/oli_web/live/products/products_view.ex
lib/oli_web/live/projects/projects_live.ex
lib/oli_web/live/projects/table_model.ex
lib/oli_web/live/sections/sections_view.ex
lib/oli_web/live/sections/table_model.ex
lib/oli_web/live/workspaces/course_author/products_live.ex
test/oli_web/live/admin/institutions/sections_and_students_view_test.exs
test/oli_web/live/products_test.exs
test/oli_web/live/projects_live_test.exs
test/oli_web/live/sections/admin_index_live_test.exs
test/oli_web/live/sections/sections_table_model_test.exs

[MER-4667](https://eliterate.atlassian.net/browse/MER-4667)
This PR introduces some improvements to the tables in the `Browse All Projects`, `Browse All Products`, and `Browse All Course Sections` views:
- Fixes sorting for the `Published` and `Created By` columns in the Browse All Projects table.
- Implements sticky first column (usually the Title column) when horizontal overflow occurs.
- Sets default table sorting by `creation date`, displaying the most recently created items first.
https://github.com/user-attachments/assets/03434bea-7728-4b0e-8854-3ccaf8810e86
https://github.com/user-attachments/assets/a53721f6-8c7c-4f8b-b9b2-e75b65f56e68
https://github.com/user-attachments/assets/e9b9c858-8d63-4642-a867-8b57522eb542
[MER-4667]: …

[FEATURE] [MER-4667] Browse all table logic

---

lib/oli_web/live/projects/projects_live.ex

[MER-4677](https://eliterate.atlassian.net/browse/MER-4677)
This PR fixes the button color styling for downloading the CSV file on the `Browse All Projects` view.
https://github.com/user-attachments/assets/718f16a6-e73f-4d11-9c54-cf19d81a3929
[MER-4677]: https://eliterate.atlassian.net/browse/MER-4677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FEATURE] [MER-4677] Browse All Projects - Fix CSV download button style

---

assets/src/apps/authoring/components/SequenceEditor/SequenceEditor.tsx

Hey @bsparks, could  you please look at the PR? Thanks
This PR continues the work from [#5822](https://github.com/Simon-Initiative/oli-torus/pull/5822).
**Changes in this PR**
- Removed temporary code used to finalize the drag-and-drop (DnD) approach.
- Fixed issues where:
1. The new sequence order was not being saved correctly after DnD.
2. Renaming a sequence caused state-related issues due to React re-rendering behavior.
3. Added logic to prevent unnecessary re-renders and infinite loops after save operations.
https://github.com/user-attachments/assets/da068c36-5fd8-4f3e-8c30-b850832efc7c

[BUG FIX] [MER-1879] Advanced Author - Click and Drag Screens

---

lib/oli/delivery/sections.ex

In `Sections.enroll/3` when the enrollment already exists update the status (Default status: enrolled).
This fixes the case when an existing pending enrollment exists, and we call Sections.enroll for that user, the status should be updated to `:enrolled`
See: https://eliterate.atlassian.net/browse/MER-4956

 [BUG FIX] [MER-4956] Captcha Loop if student is invited via email, but signs-in with invitation link

---

lib/oli_web/components/delivery/content/card_highlights.ex
lib/oli_web/components/delivery/content/content.ex
lib/oli_web/components/delivery/content/multi_select.ex
lib/oli_web/components/delivery/content/progress.ex
lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
lib/oli_web/components/delivery/practice_activities/practice_activities.ex
lib/oli_web/components/delivery/practice_activities/practice_assessments_table_model.ex
lib/oli_web/components/delivery/students/students.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
test/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live_test.exs
test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs

[MER-4710](https://eliterate.atlassian.net/browse/MER-4710)
This PR implements visual improvements to the `Insights > Practice Pages` view to help instructors scan information more quickly and effectively, following the design specifications provided in Figma.
Key changes include:
- Applied zebra striping to table rows for better readability.
- Grouped the `Progress`, `Attempts`, and `Score` filters together with the search field into a unified toolbar.
- Added a visually updated `Clear All Filters` button matching the Figma design.
- Made the table header row sticky, keeping it visible while scrolling vertically.
- Pagination behavior remains unchanged.
- The `Download CSV` button has been added to match the Figma design, but its functionality is not implemented in this ticket.
In …

[FEATURE] [MER-4710] Practice Pages Formatting Table UI

---

lib/oli/application.ex
lib/oli/conversation/dialogue_handler.ex
lib/oli/conversation/page_trigger_reply_cache.ex
lib/oli_web/live/dialogue/window_live.ex

This PR adds a per node cache for the page view activation points.  This should significantly cut down on OpenAI API endpoint usage and thus lower costs.

[ENHANCEMENT] [MER-4960] Cache activation points

---

lib/oli_web/live_session_plugs/require_enrollment.ex
test/oli_web/live_session_plugs/require_enrollment_test.exs

If section doesn't require enrollment and the user or author is logged in:
1) [If user is logged in] enrolls it to the section (this is needed for future steps like checking if the user has visited that section)
2) Assigns `is_enrolled: true` and continues
See: https://eliterate.atlassian.net/browse/TRIAGE-1882

[BUG FIX] [MER-4958] Skip enrollment check in LiveSession plug if section does not require enrollment.

---

devmode.sh

The c alias definition was giving error message because it needed quotes to include the argument.

[BUG FIX] [MER-000] devmode.sh quote claude alias body with argument

---

assets/src/components/activities/logic_lab/LogicLabDelivery.tsx
assets/src/components/activities/logic_lab/LogicLabModelSchema.tsx

In the delivery component, the probing of the logiclab url is probably unnecessary and thus removed.  This also greatly simplifies the code and is an extension of the work for #5891.  Most of the probing checks were to verify that ACTIVITY_LOGICLAB_URL was properly set but adding a hard-coded default value mitigates the need for these checks.  Eventually, the hard coded default should be removed, but that requires changes in deployment to guarantee that this environment variable is set.  If it is not set, the logiclab activity should probably not be made available as an activity option or some other indication that it is not set in the activity configuration page.

[FIX] Removes prefetching logiclab in delivery.

---

assets/src/components/activities/common/choices/delivery/ChoicesDelivery.modules.scss
assets/src/components/activities/common/choices/delivery/ChoicesDelivery.tsx
assets/src/components/activities/ordering/sections/ResponseChoices.tsx
assets/src/components/common/DraggableColumn.tsx

Choices in multiple choice, CATA and ordering questions were appearing not to respect the right-to-left text direction setting in preview and delivery. This has a severe impact on Arabic courses that rely on right-to-left text.
This happened because the dir="rtl" attribute was being set at the wrong level, at the choice content itself (leading to it being set on, say, a `<p>` within which the choice content is rendered), but NOT the containing div that groups the relevant icon (e.g. radio button for mcq) and choice content as a unit. The choice content box winds up laid out within a flex box container that lays out left to right and sizes its children to fit their content. Because choice content is rendered within such a left-aligned, sized-to-fit layout box, it makes no difference that …

[BUG FIX] [MER-4992] fix right-to-left text in mcq/CATA/ordering choice delivery

---

lib/oli/delivery/sections.ex
lib/oli_web/live_session_plugs/require_enrollment.ex

This adds a `Sections.has_enrollment?` guard around the (dangerous) upsert of `Sections.enroll`
The existing `Sections.is_enrolled?` is NOT safe to use as it constrains on `s.active = true`.  Which means if an instructor or admin visited an inactive section they would STILL be turned into a student.

[BUG FIX] [MER-4996] Fix auto enroll

---

assets/css/app.css
lib/oli/authoring/course.ex
lib/oli/delivery/sections/blueprint.ex
lib/oli/delivery/sections/browse.ex
lib/oli_web/live/common/utils.ex
lib/oli_web/live/products/products_table_model.ex
lib/oli_web/live/products/products_view.ex
lib/oli_web/live/projects/projects_live.ex
lib/oli_web/live/projects/table_model.ex
lib/oli_web/live/sections/sections_view.ex
lib/oli_web/live/sections/table_model.ex
test/oli/course_browse_test.exs
test/oli_web/live/products_test.exs
test/oli_web/live/projects_live_test.exs
test/oli_web/live/sections/admin_index_live_test.exs

- Expanded admin search to cover IDs, titles, owners, collaborators, institutions, and base products/projects across Projects, Sections, and Products, with 3-char minimum 
- Added themed span-based highlighting for matched terms.
https://github.com/user-attachments/assets/1b07c382-099a-47a3-8745-2d1007029a16
See: https://eliterate.atlassian.net/browse/MER-4666

[FEATURE] [MER-4666] Better search for "Browse all" type tables in Admin workspace

---

lib/oli_web/components/delivery/content/card_highlights.ex
lib/oli_web/components/delivery/practice_activities/practice_activities.ex
lib/oli_web/components/delivery/scored_activities/scored_activities.ex
lib/oli_web/live/common/table/striped_paged_table.ex
lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
test/oli_web/components/delivery/scored_activities/scored_activities_test.exs
test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs

[MER-4706](https://eliterate.atlassian.net/browse/MER-4706)
This PR implements filtering functionality in the `Scored Pages` section under `Insights > Practice Pages`, both at the page level and the question level, following Figma designs and reusing shared components where appropriate.
✅ Page-Level Filters
- Added three main filters to help instructors quickly identify problematic content:
- **Low Scores**: filters pages with average scores flagged in red.  
- **Low Progress**: filters pages with low completion percentage.  
- **Low or No Attempts**: filters pages with either 0 attempts or fewer than 5 attempts.  
- Added toolbar filters:
- **Progress**: allows filtering by completion percentage range.  
- **Attempts**: dropdown with `None`, `< 5`, `> 5` options.  
- **Score**: allows …

[FEATURE] [MER-4706] Scored Pages Filters

---

lib/oli/analytics/datasets.ex
lib/oli/analytics/datasets/utils.ex
mix.exs

Reverse user lookup data cannot exist when the dataset if anonymous.

[BUG FIX] [MER-5000] Only include users when dataset is non anonymized
